### ISSUE TITLE
Upstream integration?

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium-desktop#1]
[WebDriverAgent](https://github.com/facebook/WebDriverAgent/tree/master/Inspector) already has a react based inspector tool. Although there's no electron shell. Any thoughts on if it makes sense to collaborate with upstream on their inspector?

**Comment by jlipps** [comment]
That's a good idea. I need to play around with it to see if it will meet our needs.

**Comment by jlipps** [comment]
I looked into this and their inspector is too tightly tied to WDA. We want an inspector which doesn't know anything about particular drivers.
