### ISSUE TITLE
on macOS 10.12.3, the inspector is broken

### ISSUE THREAD

**Issue by lionel-pushios** [appium/appium-desktop#100]
se
![appiuminspectorbug](https://cloud.githubusercontent.com/assets/24396183/24374748/faa280ce-1303-11e7-88fb-246b0db44d3e.gif)
e attached .gif

**Comment by jlipps** [comment]
@lionel-pushios if you restart your computer does the issue persist?

**Comment by dpgraham** [comment]
Are you able to open the Chrome inspector and see any console logs?

**Comment by lionel-pushios** [comment]
@jlipps Yes, once I get to the Inspector window, I can only select the type dropdown and then everything seizes to function. Here are the console logs for every click it seems to throw an error.




![appiuminspectorbug](https://cloud.githubusercontent.com/assets/24396183/24376449/e6db3a08-1309-11e7-9333-fcc6519416ce.gif)

**Comment by dpgraham** [comment]
Yeah we've seen this error before. We put in a fix for it a month or so ago. What version are you using?

**Comment by lionel-pushios** [comment]
The latest beta5

**Comment by dpgraham** [comment]
Can you try deleting `/Users/<you>/Library/Application Support/appium-desktop` and then run it again.

**Comment by lionel-pushios** [comment]
Yes, that solves the issue. Thank you very much.

**Comment by dpgraham** [comment]
No problem.
