### ISSUE TITLE
error on latest version of Appium 1.13 "impossible to create new session"

### ISSUE THREAD

**Issue by ArathiSawai** [appium/appium-desktop#1001]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by ArathiSawai** [comment]
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app","newCommandTimeout":180,"platformVersion":"12.1","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone XS Max","autoAcceptAlerts":true},"capabilities":{"alwaysMatch":{"appium:app":"/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app","appium:autoAcceptAlerts":true,"appium:automationName":"XCUITest","appium:deviceName":"iPhone XS Max","appium:newCommandTimeout":180,"platformName":"ios","appium:platformVersion":"12.1"},"firstMatch":[{}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app","newCommandTimeout":180,"platformVersion":"12.1","automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone XS Max","autoAcceptAlerts":true},null,{"alwaysMatch":{"appium:app":"/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app","appium:autoAcceptAlerts":true,"appium:automationName":"XCUITest","appium:deviceName":"iPhone XS Max","appium:newCommandTimeout":180,"platformName":"ios","appium:platformVersion":"12.1"},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1559626277037 (15:31:17 GMT+1000 (AEST))
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app
[Appium]   autoAcceptAlerts: true
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone XS Max
[Appium]   newCommandTimeout: 180
[Appium]   platformVersion: 12.1
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"/Users/araghave/Lib... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 2f7e09e7-467d-4241-b0c0-9c54602683c0
[XCUITest] Current user: 'araghave'
[iOSSim] Constructing iOS simulator for Xcode version 10.1 with udid '38E6D1DC-2C02-4E89-9CA5-12363563D6FD'
[XCUITest] Determining device to run tests on: udid: '38E6D1DC-2C02-4E89-9CA5-12363563D6FD', real device: false
[XCUITest] iOS SDK Version set to '12.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1559626278292 (15:31:18 GMT+1000 (AEST))
[BaseDriver] Using local app '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app'
[BaseDriver] Event 'appConfigured' logged at 1559626278296 (15:31:18 GMT+1000 (AEST))
[XCUITest] Checking whether app '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app' is actually present on file system
[XCUITest] App is present
[Support] Error: Plist file doesn't exist: '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app/Info.plist'
[Support]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Support]     at Object.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/plist.js:22:11)
[Support]     at Generator.next ()
[Support]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[Support]     at _next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[Support]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:75:22)
[Support]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:92:30
[Support]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/_microtask.js:18:9)
[Support]     at process._tickCallback (internal/process/next_tick.js:61:11)
[iOS] Error: Could not extract Info.plist from application: Plist file doesn't exist: '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app/Info.plist'
[iOS]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[iOS]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/app-utils.js:14:9)
[iOS]     at process._tickCallback (internal/process/next_tick.js:68:7)
[XCUITest] Error: Could not extract Info.plist from application: Plist file doesn't exist: '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app/Info.plist'
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/app-utils.js:14:9)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:68:7)
[BaseDriver] Event 'newSessionStarted' logged at 1559626278309 (15:31:18 GMT+1000 (AEST))
[W3C] Encountered internal error running command: Error: Could not extract Info.plist from application: Plist file doesn't exist: '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app/Info.plist'
[W3C]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[W3C]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/app-utils.js:14:9)
[W3C]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 1287 ms - 1080
[HTTP]

**Comment by KazuCocoa** [comment]
As a workaround, in a case Appium.app could not create proper files inside the app, https://github.com/appium/appium-desktop#connect-to-local-appium-server may help

**Comment by KazuCocoa** [comment]
The app under test might have no necessary files for iOS.

```
[iOS] Error: Could not extract Info.plist from application: Plist file doesn't exist: '/Users/araghave/Library/Developer/Xcode/DerivedData/Banking-bvtlsmizssxmgqhbzqeptswuajey/Build/Products/Debug-iphonesimulator/Macquarie.app/Info.plist'
```
