### ISSUE TITLE
Appium desktop client continuously crashing on MAC 10.14.5

### ISSUE THREAD

**Issue by sanyesz123** [appium/appium-desktop#1004]
## The problem

Appium desktop crashes after updating MAC to 10.14.5. I had a saved preset with the necessary configurations which worked before. Currently every time the simulator should be started, or the simulator is already started and the app should be started the appium desktop client crashes. From the server logs the last line does not show any error, just says that the application is installing. 

I have tried 1.13.0, 1.12.1 appium desktop clients, both have the same behaviour ⬆️. I also tried out the same configurations on my colleague's machine (the previous setup was made by me on that machine), that machine has 10.14.4 MAC version and everything is working as expected. 

## Environment

- I am running Appium Desktop version 1.13.0
- I am on (pick one):
    - [x ] Mac 10.14.5

**Comment by KazuCocoa** [comment]
It appreciated if you could launch as developer as https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md#setting-up to get the crash log...

**Comment by KazuCocoa** [comment]
no log
