### ISSUE TITLE
appium-desktop Unable to find Wechat Payment Interface Elements

### ISSUE THREAD

**Issue by hagyao520** [appium/appium-desktop#1009]
![image](https://user-images.githubusercontent.com/24785603/59651426-522beb80-91bc-11e9-973e-254a16af7fbc.png)
1.The appium-inspector function on the Appium desktop can't capture the payment interface information of Wechat, so it keeps turning around.
![image](https://user-images.githubusercontent.com/24785603/59651457-725baa80-91bc-11e9-8cb4-254d35166ef6.png)
2.appium-desktop How to turn on Chrome Options settings
3.Does the latest version of Appium support testing Weichat widget payment?

**Comment by dpgraham** [comment]
I'm not sure what the error is.
