### ISSUE TITLE
Inspector unable to capture App Activity

### ISSUE THREAD

**Issue by thv92** [appium/appium-desktop#1010]
## Appium Desktop Client

- The issue appears in both Appium and the Appium Desktop Client Inspector

### The issue occurs after navigating around the Activity. 

Log of Issue:
```
[debug] [35m[WD Proxy]
[39m Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/977d14c7-5799-488d-b958-a5f031f6c960/screenshot] with no body
[debug] [35m[MJSONWP (16f73f37)][39m Encountered internal error running command: 
ProxyRequestError: Could not proxy command to remote server. 
Original error: 500 - "{\"sessionId\":\"977d14c7-5799-488d-b958-a5f031f6c960\",\"status\":13,\"value\":
\"io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: 
Timed out after 10000 milliseconds waiting for root AccessibilityNodeInfoio.appium.uiautomator2.utils.AXWindowHelpers.refreshRootAXNode(AXWindowHelpers.java:78)
at io.appium.uiautomator2.handler.Source.safeHandle(Source.java:38)
at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:37)
at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:243) 
```

- For the Inspector's case, it was able to capture the activity on initial load. However, after navigating around a few times the Appium Desktop Client would cause the Exception above.

- For the case of Appium, after the test script navigates to the Activity. It was able to click on the hamburger icon twice and would give the same issue afterwards.

The Activity has a navigation list of items that when clicked on will navigate you towards the target section. It will contain mainly text, videos, and images.

I've tried resetting the Emulator and the Appium Desktop Client, but to no avail. It was remedied when I changed the port, but it was only able to perform the tasks once. It appears that when starting another session, the same issue occurs again.

Would you be able to provide some insight into what may be causing this issue? Could it be that it's somehow unable to clear the cache?

- This image here is showing that after clicking on NavigationItem 7, the Inspector was unable to refresh and capture it.
<img width="1680" alt="Screen Shot 2019-06-17 at 5 14 44 PM Markup" src="https://user-images.githubusercontent.com/5522936/59654713-17df3180-915d-11e9-958a-dc6473fb3583.png">

Appium Configuration:
```
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   sessionOverride: true
[info] [35m[Appium][39m   logTimestamp: true
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
```

## Environment

- I am running Appium Desktop version 1.13.0
- I am using the Java Client of Appium version 7.0.0
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
This looks AccessibilityNodeInfo by Android could not get the target element properly.
Potentially, espresso driver can solve it...
