### ISSUE TITLE
Locator strategy "tag-view" support for Espresso driver

### ISSUE THREAD

**Issue by uterator** [appium/appium-desktop#1016]
This is an enhancement for Appium Desktop to support the locator strategy "tag-name" for Espresso driver. 

Please add "tag name" strategy in the "Locator Strategy:" dialog of Appium Desktop.

Appium already supports "tag-name" - http://appium.io/docs/en/commands/element/attributes/name/
Appium-Desktop doesn't have it in the locator strategies list

Here is an example of a command  
```
[HTTP] --> POST /wd/hub/session/<sessionId:>/element
[HTTP] {"using":"tag name","value":"welcome_dialog"}
```

## 

## Environment

- I am running Appium Desktop version 1.14.0-beta.1
- I am on (pick one):
    - [ ] Mac
    - [ X ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Agreed. It should be in Appium Desktop.

Do you have time to put in a PR for it? It should just be a couple lines of code.

**Comment by uterator** [comment]
Sure, I will try. BTW, it will be my first push to here ))

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/pull/1087
