### ISSUE TITLE
Problem starting a new session after closing one using Appium Desktop.

### ISSUE THREAD

**Issue by Arekssio** [appium/appium-desktop#1023]
I'm using Appium Desktop in an automation UI testing WPF proyect for a windows desktop app.
I start a new windows driver session in each test method. When a test ends and the session closes and the next test starts, Appium gets stuck trying to close the previous session (that does not exists btw) before starting a new one, giving this message:

**[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in ('netstat -nao ^| findstr /I winappdriver.exe') do (IF NOT %b=="" TASKKILL /F /PID %a))**

It takes like 40-50 seconds to start a new session.
In consecuence, my test method stops with timeout error because can't start the new driver session.

I have the problem using these **two ways of closing the session**:
- I've implemented a disposable class to manage the driver session life cicle. I've tryed using methods Quit(), CloseApp() and Dispose() in the Dispose() method of this class.
- Closing the session directly in the test method using Quit, Close, CloseApp...
 
I have to say that the problem does not always happen. Sometimes the test can run because it took less time closing and starting session, but it always takes so much time anyway.

Any idea? If you need more info just ask for it.

## Environment

- I am running Appium Desktop version v1.10.0.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
I would go to the WinAppDriver github page. This isn't a UI issue.
