### ISSUE TITLE
[KeepAliveFailure] -Error getting in between execution on real device with remote appium server

### ISSUE THREAD

**Issue by rajarlm007** [appium/appium-desktop#1025]
I have setup Appium server 1.13 version in Mac machine and real device connected (iPhone XR). Test cases executing from window machine with visual studio. Running fine around 40 min and then getting error like [KeepAliveFailure] and got connection closed. Can anyone give me solution to fix this issue.

**Error: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://192.168.137.233:4723/wd/hub/session/71e96643-a219-462f-a7af-c89d11d874db/elements. The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. -> The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.**
--

**Comment by rajarlm007** [comment]
Can anyone having solution for this issue?

**Comment by KazuCocoa** [comment]
Did you wait for sending another command to the server?
You can send some methods like `status` as a heartbeat.

**Comment by KazuCocoa** [comment]
Newer versions may be improved...
https://github.com/search?q=org%3Aappium+KeepAlive&type=Issues
