### ISSUE TITLE
Error An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by lionel-pushios** [appium/appium-desktop#103]
I know this error has something to do with Xcode signing provisions, and I have followed these steps:
1) Goto /usr/local/lib/node_modules/app-inspector/node_modules -> webdriveragent -> WebDriverAgent -> WebDriverAgent.xcodeproj
changed team to your apple developer account team name for all under TARGETS
2) Installed WebDriverAgent through xcode on the test device.

However, once I tried running Appium again, I got the same error message.

**Comment by jlipps** [comment]
Hi @lionel-pushios, this is not an appium desktop issue, this is an appium issue and should be reported at the appium repo, not here.

**Comment by lionel-pushios** [comment]
Okay, sorry. Thanks.
