### ISSUE TITLE
server in device no response for command

### ISSUE THREAD

**Issue by Tiny1213** [appium/appium-desktop#1034]
## The problem

![image](https://user-images.githubusercontent.com/9071200/60796350-c6e0bd00-a19f-11e9-9130-3db31e110068.png)

why io.appium.uiautomator2.server receive the command,but no response until timeout ?

## Environment

- I am running Appium Desktop version _<1.13.0>_.
- I am on Windows,test on Android photo

**Comment by KazuCocoa** [comment]
How about the logcat?
It might help to figure it out
