### ISSUE TITLE
Empty space in View menu

### ISSUE THREAD

**Issue by kasprzakdanielt** [appium/appium-desktop#1037]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
After launching Appium there is an empty space in View menu.
![Zrzut ekranu (1)](https://user-images.githubusercontent.com/9053610/60869293-fc80b700-a22e-11e9-815c-b6e6aa96da80.png)

## Environment

- I am running Appium Desktop version 1.14.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Which OS is this?

**Comment by kasprzakdanielt** [comment]
> 
> 
> Which OS is this?

Windows 10

**Comment by marksmayo** [comment]
Can confirm, I'm seeing it on Windows 10 as well. But only in 'production' build, not when I  build from source?

**Comment by dpgraham** [comment]
Strange. Okay, thanks for reporting it. I'll have a look when I get a chance.
