### ISSUE TITLE
'app' option is required although 'appPackage' and 'appActivity' are set

### ISSUE THREAD

**Issue by NecatiQR** [appium/appium-desktop#1038]
## Appium or Appium Desktop?
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does not reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

[Desired Capabilities](http://appium.io/docs/en/writing-running-appium/caps/) states that `app`  capability is not required for Android if you specify `appPackage` and `appActivity` capabilities. But when I am trying to start a session from Appium Desktop with `appPackage` and `appActivity` capabilities set, I get the error:

> Original error: 'app' option is required for reinstall

When I create session with the same capabilities from CLI, it does not give an error.

## Environment

- I am running Appium Desktop version 1.14.0.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by crenshaw78** [comment]
Why is this closed? I am seeing this in my tests with Windows users. And it also is opening application on other devices not specified as well.

**Comment by pashkatrick** [comment]
same error, need re-open

**Comment by jlipps** [comment]
The inspector is no longer in this repo. If you are having errors with the current version of the inspector (found [here](https://github.com/appium/appium-inspector), make an issue in that repo.

**Comment by jlipps** [comment]
then this issue has been reported at the wrong repo.

anyway, the problem is probably that someone has set fullReset to true or something like that, for which the actual app path is required.
