### ISSUE TITLE
appium on IOS: node:21474) UnhandledPromiseRejectionWarning: WebDriverError: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device

### ISSUE THREAD

**Issue by tejas900** [appium/appium-desktop#1040]
## Appium or Appium Desktop?
Appium command line

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue
It occurs with Appium. I dont have the desktop version at all on the mac machine i am trying to setup automation for mobile app

## The problem

All the required softwares are installed. When i run the sample test in JS using node, it installs the app and launches it as well on the iphone XR simulator. But when test try to communicate with the object in the native mobile app, it gives following error. Attaching the complete appium logs for reference. 
[Terminal Saved Output.zip](https://github.com/appium/appium-desktop/files/3380199/Terminal.Saved.Output.zip)
[Terminal Saved Output.zip](https://github.com/appium/appium-desktop/files/3380200/Terminal.Saved.Output.zip)
[Terminal Saved Output.zip](https://github.com/appium/appium-desktop/files/3380201/Terminal.Saved.Output.zip)

node:21474) UnhandledPromiseRejectionWarning: WebDriverError: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device

## Environment

- I am running Appium Desktop version _<insert version here>_.No
- I am on (pick one):
    - [x] Mac -- YES
    - [ ] Windows
    - [ ] Linux

**Comment by tejas900** [comment]
can someone please take a look

**Comment by KazuCocoa** [comment]
Hm, the error probably happened the device was disconnected by Web Inspector.
If so, macOS, Xcode and simulator version might be related.
