### ISSUE TITLE
Not able to launch Android emulator, OpenGL errors

### ISSUE THREAD

**Issue by MioOgbeni** [appium/appium-desktop#1043]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

Problem occurred only when I run tests on Appium Desktop, Appium version from npm is fine.

## The problem

Appium cannot automatically run AVD, it is always stuck on the Google logo screen and displays OpenGL errors in the console (glClear:481 GL err 0x505).

I tried it on every version from 1.14.0 to 1.9.0 and the problem only occurred on 1.11.0 or more.
I also tried Appium server from npm and it works fine on all versions.

BTW: I use Hyper-V for faster AVD emulation to the latest Windows version, not HAXM.
 
Here is log 
https://gist.github.com/MioOgbeni/f57120032839d564346ae2e270e376e4

## Environment

- I am running Appium Desktop version _<1.11.0>_ or more.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux
- I am using Hyper-V emulation

**Comment by KazuCocoa** [comment]
It looked avd command failed to create a device?

```
[debug] [35m[ADB][39m Emulator AND_8.0.0_1080x1920_5.0in_EN not running[info] [35m[ADB][39m [AVD OUTPUT] Windows Hypervisor Platform accelerator is operational
[info] [35m[ADB][39m [AVD OUTPUT] dsound: Could not initialize DirectSoundCapture
[info] [35m[ADB][39m [AVD OUTPUT] dsound: Reason: No sound driver is available for use, or the given GUID is not a val
[info] [35m[ADB][39m [AVD OUTPUT] id DirectSound device ID
[info] [35m[ADB][39m [AVD OUTPUT] dsound: Attempt to initialize voice without DirectSoundCapture object
[info] [35m[ADB][39m [AVD OUTPUT] dsound: Attempt to initialize voice without DirectSoundCapture object
[info] [35m[ADB][39m [AVD OUTPUT] audio: Failed to create vo
[info] [35m[ADB][39m [AVD OUTPUT] ice `goldfish_audio_in'
[info] [35m[ADB][39m [AVD OUTPUT] C:\Users\Admin\AppData\Local\Android\Sdk\emulator\qemu\windows-x86_64\qemu-system-i386.exe: warning: opening audio input failed
[info] [35m[ADB][39m [AVD OUTPUT] dsound: Attempt to initialize voice without DirectSoundCapture object
[info] [35m[ADB][39m [AVD OUTPUT] dsound: Attempt to initialize voice without DirectSoundCapture object
[info] [35m[ADB][39m [AVD OUTPUT] audio: Failed to create voice `adc'
[debug] [35m[ADB][39m Trying to find AND_8.0.0_1080x1920_5.0in_EN emulator
[debug] [35m[ADB][39m Getting connected emulators
[debug] [35m[ADB][39m Getting connected devices...
```

Appium Desktop itself does not handle emulators directly. Everything is via appium server. Thus, I think nothing can do for the avd feature in appium desktop layer, unfortunately
