### ISSUE TITLE
connect iOS 12.3.1 device failed

### ISSUE THREAD

**Issue by allenchann** [appium/appium-desktop#1044]
Appium Desktop?

- [✅] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

I used appium desktop to connect my iPhone.But it failed.The message is inside the pic.The system of device is iOS 12.3.1

![image](https://user-images.githubusercontent.com/16041349/61344449-e3f24b80-a883-11e9-905b-f065aa6c1b74.png)

- I am running Appium Desktop version _<1.14.0>_.
- I am on (pick one):
    - [✅] Mac

**Comment by shenjianyun** [comment]
I set the capabilities platformVersion to 12.1 or 12.2

**Comment by allenchann** [comment]
But my iPhone is iOS12.3.1.

**Comment by shenjianyun** [comment]
@allenchann , may be you can try with this https://github.com/appium/appium/issues/12581

**Comment by lhimo** [comment]
Same here.. iOS 12.3.1 appium 1.13.0.20190505.6

**Comment by caeser1988** [comment]
Any news on this ? i'm facing the same problem with the iphone X with iOS 13.1.3 and appium desktop 1.15.1.

**Comment by KazuCocoa** [comment]
Please follow https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md to ensure your local environment can build WDA first.
As the page addresses, mostly `xcodeOrgId`, `xcodeSigningId` and `updatedWDABundleId` help this 65 error.

If you still have the issue, please create a new issue with the full log
