### ISSUE TITLE
Will restart app for loop when open Appium inspector and can't open inspector at last

### ISSUE THREAD

**Issue by shenjianyun** [appium/appium-desktop#1046]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When launch Appium inspector, The testing app will restart for many times, and then get error and can't open Appium inspector

NOTE: the WebDriverAgent.xcodeproj builded successes in Xcode 

## Environment

- I am running Appium Desktop version 1.12.1
- I am on (pick one):
    - [ ] Mac 10.14.5
   Xcode 10.2.1
  
below is my capabilities:
<img width="484" alt="2" src="https://user-images.githubusercontent.com/48910607/61426155-fafc7080-a94b-11e9-9ad7-614963063baf.png">

below is Appium log:
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/3404614/appium-server-logs.txt)

there are the error log to see more clearly:
<img width="650" alt="e1" src="https://user-images.githubusercontent.com/48910607/61428440-b0332680-a954-11e9-86e7-20ff9183a818.png">
<img width="650" alt="e2" src="https://user-images.githubusercontent.com/48910607/61428443-b5907100-a954-11e9-9534-dc563df76b48.png">

**Comment by shenjianyun** [comment]
here is my step:
step1: download the webdriverageent form https://github.com/facebookarchive/WebDriverAgent

step2:put the downloaded to /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver

step3: in terminal with the path mentioned execute:
        mkdir -p Resources/WebDriverAgent.bundle
        ./Scripts/bootstrap.sh -d

step4: open WebDriverAgent.xcodeproj with Xcode, build successes and install webdrvierageent on iPhone, also can get son from http://iphone ip:8100/status

step5: open Appium desktop and launch inspector

**Comment by shenjianyun** [comment]
I resolved this problem through https://github.com/appium/appium/issues/12462, download Appium WebDriverAgent(https://github.com/appium/WebDriverAgent) replace of facebook, finally it works!

**Comment by hw526874784** [comment]
> 我通过[appium / appium＃12462](https://github.com/appium/appium/issues/12462)解决了这个问题，下载Appium WebDriverAgent（https://github.com/appium/WebDriverAgent）取代facebook，最后还可以！

我现在不会闪退了   但是appium投屏显示不出来·····也是醉了

**Comment by shenjianyun** [comment]
@hw526874784 , give more appium log to see the cause

**Comment by hw526874784** [comment]
> @ hw526874784，给出更多的appium日志来查看原因

搞定了  是ios系统版本问题  我开始用的是10.3.1的不行，换了个12.1的系统就可以了
