### ISSUE TITLE
No results when inspecting elements on IOS application

### ISSUE THREAD

**Issue by glassalle59** [appium/appium-desktop#1048]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hello,

I want to test a IOS application with Appium

However, when I want to find xpath elements, I see nothing with Appium Inspector. No element are displayed (just the battery, hour, etc...)  :

![image](https://user-images.githubusercontent.com/33724879/61323505-71945380-a810-11e9-8310-a06e3bddfaeb.png)

I need to see at least the "Text" elements. Not necessarily IDs.

My ipa is a release build with App Store distribution.
=> Is it because of that ? Do I must need a debug build with Development distribution ?  

Thanks per advance,

## Environment

- I am running Appium Desktop
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
This is an outdated application that we don't support. Appium Desktop is github.com/appium/appium-desktop/releases/latest
