### ISSUE TITLE
Could not start a new session with iOS. Appium Desktop, Version 1.0.0-beta.5

### ISSUE THREAD

**Issue by louis57** [appium/appium-desktop#105]
I am using Appium Desktop, Version 1.0.0-beta.5. It works fine with Android, but when I test iOS app, the app is not installed on device and I get this error message about ideviceinstaller, as the screenshot below with desired capabilities settings:

![screen shot 2017-03-28 at 10 49 53](https://cloud.githubusercontent.com/assets/12949146/24399662/bcd0663a-13ad-11e7-899e-59c220955816.png)

I am not sure if it is because this ipa file is not built with Developer Signature or if my desired capabilities settings missing something. So I try with another ipa file. I also add "bundleId" capability, and this time, the app is installed, but it keeps blinking (open and close real quick) and after few times, I get this message:

> Error: An unknown server-side error occurred while processing the command. Original error: We exceeded the number of retries allowed for instruments to successfully start; failing launch

Can someone help me with a solution? Much appreciated. Thanks

My environment: 
- Appium Desktop, Version 1.0.0-beta.5
- OS: Mac OS Sierra, Version 10.12.3

**Comment by jlipps** [comment]
Hi @louis57 it doesn't appear that this issue is isolated to Appium Desktop, does it? Please note that if the issue is not specific to Appium Desktop but also reproduces in Appium in general, then the discussion should not happen here but at https://github.com/appium/appium/issues.

**Comment by louis57** [comment]
Hi @jlipps, it seems this issue is related to Appium in general. I'm gonna ask this question there. Thanks

**Comment by jlipps** [comment]
ok sounds good
