### ISSUE TITLE
Cannot not run with appium in iOS real devices

### ISSUE THREAD

**Issue by allenchann** [appium/appium-desktop#1050]
## The problem

![image](https://user-images.githubusercontent.com/16041349/61516995-c4505400-aa38-11e9-970c-ee45cb4a9a91.png)

I used node to run appium testcase.But it have problem `Could not navigate to webview!`.
I made sure my iPhone had open web inspector.And i cannot connect with my iPhone use`ios_webkit_debug_proxy`.
Appium version is 1.13.0 and my device is iOS 12.3.1.

## Environment
- I am on (pick one):
    - [✅] Mac

**Comment by KazuCocoa** [comment]
Newer Appium version could resolve this.
(Over Appium 1.15.0, it no longer depends on `ios_webkit_debug_proxy`)
