### ISSUE TITLE
Can't locate ios selection by appium inspector

### ISSUE THREAD

**Issue by shenjianyun** [appium/appium-desktop#1052]
<img width="1440" alt="gender" src="https://user-images.githubusercontent.com/48910607/61578928-99e1c200-ab30-11e9-86cc-11a4390f93fe.png">

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

There are gender selection include male and female, I want to select one of them, but Appium inspector can't locate the selection, what I need to do? 

## Environment

- I am running Appium Desktop version 1.12.1
- I am on (pick one):
    - [x] Mac

**Comment by KazuCocoa** [comment]
Appium inspector cannot select any elements which are not in the page_source.
Please check the page source first
