### ISSUE TITLE
Unable to locate google maps poi on iOS app using Appium inspector

### ISSUE THREAD

**Issue by shenjianyun** [appium/appium-desktop#1053]
## Appium or Appium Desktop?
- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Our native app use google maps sdk, unable to locate poi points when use Appium inspector

## Environment

- I am running Appium Desktop version _1.12.1_
- I am on (pick one):
    - [ ] Mac
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/48910607/61612233-8e0d1180-ac90-11e9-8ad7-9b21abce1506.png">

**Comment by KazuCocoa** [comment]
Do them exist in page source output?
If no, Appium cannot detect them.
(It is easy to happen this kind of errors in WebView)
