### ISSUE TITLE
cannot start appium-service by adb

### ISSUE THREAD

**Issue by yueyue10** [appium/appium-desktop#1054]
## Appium or Appium Desktop?

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

cannot start appium-service by adb

![python_demo](https://github.com/yueyue10/MyApplication/raw/master/python_project/python_demo/appium_demo/appium_error.png)

## Environment

- I am running Appium Desktop version _<Version 1.14.0>_.
- I am on (pick one):
    - [ ] Windows

**Comment by KazuCocoa** [comment]
What do you mean _appium-service_?
