### ISSUE TITLE
Selecting element in App Source in Appium Inspector blanks the window (Real iPad device)

### ISSUE THREAD

**Issue by roddymunro** [appium/appium-desktop#1057]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am running Appium Inspector on both a physical iPad device running iOS 12.4, and a physical iPhone X running 12.2. After starting a new session from Appium Inspector, the app installs and loads as expected. When I click on an element in the XML App Source, the Appium Inspector window 'blanks out' and becomes unusable. The app running on the device doesn't crash. I can also reproduce this consistently

![Screenshot 2019-07-25 at 13 52 22](https://user-images.githubusercontent.com/11502253/61875894-82fdef80-aee3-11e9-94e3-ffe44291699a.png)

The latest logs I have:
https://gist.github.com/roddymunro/238b2c92385356d6c223c83f9daee620

## Environment

- I am running Appium Desktop version 1.13.0.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by craigatpodium** [comment]
@roddymunro were you able to figure out what the issue was with this?

**Comment by roddymunro** [comment]
@craigatpodium Hi Craig, no I wasn't. I'll be able to check in the next few days whether I still see this issue... are you seeing the same thing?

**Comment by cdaringe** [comment]
i put an error boundary around the `<Root />` component.  the plot thickens:

![image](https://user-images.githubusercontent.com/1003261/72636060-181df600-3913-11ea-8019-ec8781fed7a3.png)
