### ISSUE TITLE
TestObject API Key field should be a check Box+Field

### ISSUE THREAD

**Issue by MMooreGitHub** [appium/appium-desktop#1058]
Can you provide the ability to have multiple Test Objects API keys by changing the Text Field above into a selection box or a text field with an adjacent text box?
This would mitigate the constant need to copy/re-paste API keys when testing across different apps.  

Please see attached  screen shot.
![Screen Shot 2019-07-25 at 9 39 27 AM](https://user-images.githubusercontent.com/19997256/61880252-8c2a9480-aec2-11e9-9a7a-429013c6be93.png)

**Comment by KazuCocoa** [comment]
@MMooreGitHub Could you send a request to the test object contact?

**Comment by KazuCocoa** [comment]
According to https://github.com/appium/appium-desktop/issues/848 , this section will be removed or modified
