### ISSUE TITLE
Not able to generate properties of offscreen object  using appium in Android 8 & 9

### ISSUE THREAD

**Issue by deviraghubabu** [appium/appium-desktop#1069]
## Appium or Appium Desktop?

Verified this only in Appium Desktop

## The problem

In my app we have list of subjects, in android 8 & 9 , while launching the appium inspector it is just showing only the object which are ONSCREEN, but in android 7  appium inspector is showing all object properties (OnSceen & OffScreen)

## Environment

- I am running Appium Desktop version v1.13.0
- I am on (pick one):
  
    -  Windows

**Comment by KazuCocoa** [comment]
It seems to depend on appium CLI (Not AD) and Android versions.
Potentially, `allowInvisibleElements` http://appium.io/docs/en/advanced-concepts/settings/ may help for UIA2.
