### ISSUE TITLE
Build webdriveragent, get ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:      eslint --init error

### ISSUE THREAD

**Issue by qinlizql** [appium/appium-desktop#1075]
## Appium or Appium Desktop?
Using :
Xcode10.3
Appium Deskptop 1.14.beta version
OS: Mac

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

When build webdriveragent, get below error:
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

Does anyone meet same issue? How to solve?

**Comment by ishpreetnanda14** [comment]
I had same issue. Resolved it by reinstalling doing following steps- 
npm uninstall -g appium && npm install -g appium@latest

cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/

mkdir -p Resources/WebDriverAgent.bundle

./Scripts/bootstrap.sh -d

**Comment by dpgraham** [comment]
Thank you @ishpreetnanda14 !
