### ISSUE TITLE
appium 1.14.0-beta.1 shows update popup for 1.13

### ISSUE THREAD

**Issue by jpita** [appium/appium-desktop#1077]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After starting a new server with appium-desktop 1.14.0-beta.1, a popup shows saying that there's a new version available for download, version 1.13
## Environment

- I am running Appium Desktop version 1.14.0-beta.1
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by SebastianSolidwork** [comment]
The reason is the unpublishing of 1.14.
https://github.com/appium/appium-desktop/issues/1042

**Comment by dpgraham** [comment]
Yep. 1.13 is the latest (tehnically). We had to unpublish 1.14
