### ISSUE TITLE
The New Session window is not fully loaded 

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium-desktop#108]
## The problem

When New Session window opened it loaded not fully. And on click any buttons nothing has happened.
But when I upload this app to another machine it works fine.

## Environment

* Appium desktop version (or git revision) that exhibits the issue: 1 1.0.0-beta.5
* MacOS: 10.12.3 

## Screenshot
![screen shot 2017-03-29 at 1 01 08 pm](https://cloud.githubusercontent.com/assets/11422447/24449449/f35fcc68-147f-11e7-8259-2700008dcfa2.png)

**Comment by jlipps** [comment]
@HlebHalkouski can you close the app, delete `~/Library/Application Support/appium-desktop` and try to launch the app again?

**Comment by HlebHalkouski** [comment]
@jlipps Thank you, issue was solved.
