### ISSUE TITLE
Can't run command npx build command

### ISSUE THREAD

**Issue by aldochristiaan** [appium/appium-desktop#1082]
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Can't run `npx build --publish never`
It said :
```
npx: installed 50 in 4.812s
command not found: build
```

## Environment

- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/pull/1079 should help

**Comment by aldochristiaan** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7087414/64598541-1c288d00-d3e2-11e9-97e9-3c71f4bfabaf.png">

I got something like this after build it into .dmg and installing it ..
@KazuCocoa

**Comment by KazuCocoa** [comment]
it is code-sign issue.
You should follow  https://www.electron.build/code-signing
Appium desktop does like https://github.com/appium/appium-desktop/blob/master/ci-jobs/templates/package.yml

**Comment by dpgraham** [comment]
We sign this using the JSFoundation certificate.

If you want to build a DMG that's signed with a different certificate (which you're welcome to do) you'll need to get a separate cert.

Also, you could probably amend the code to skip line 23 in autoUpdater.js in a local fork to create an unsigned DMG.
