### ISSUE TITLE
There are some H5 pages where elements cannot be retrieved in Android

### ISSUE THREAD

**Issue by liuzhiyang123** [appium/appium-desktop#1089]
## Appium or Appium Desktop?
![image](https://user-images.githubusercontent.com/43614024/64949694-57c4ca80-d8ac-11e9-8f38-de8ca46c05dd.png)

Reference picture,There are some H5 pages where elements cannot be retrieved

- [ o ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ o ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
It looks the element is WebView. It strongly depends on Android framework side.
Potentially, espresso driver returns a better result, or web context may help. (But Appium Desktop cannot handle WebContext well so far)
