### ISSUE TITLE
[MJSONWP (6d7b2baa)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCApplicationQuery elementSnapshotForDebugDescription]: unrecognized selector sent to instance 0x600002433f00

### ISSUE THREAD

**Issue by zzq22406** [appium/appium-desktop#1094]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

[HTTP] --> GET /wd/hub/session/6d7b2baa-405d-4a5e-9081-8f5178403eae/screenshot
[HTTP] {}
[MJSONWP (6d7b2baa)] Calling AppiumDriver.getScreenshot() with args: ["6d7b2baa-405d-4a5e-9081-8f5178403eae"]
[XCUITest] Executing command 'getScreenshot'
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : "-[XCUIApplication resolve]: unrecognized selector sent to instance 0x600002b097a0\n\n(\n\t0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23bb9704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      0x00007fff23b9d7bc ___forwarding___ + 1436\n\t4   CoreFoundation                      0x00007fff23b9f6c8 _CF_forwarding_prep_0 + 120\n\t5   WebDriverAgentLib                   0x000000010da7c3e1 -[XCUIElement(FBUtilities) fb_snapshotWithAttributes] + 97\n\t6   WebDriverAgentLib                   0x000000010da4a746 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 966\n\t7   WebDriverAgentLib                   0x000000010da49abd +[FBXPath xmlRepresentationWithRootElement:writer:elementStore:query:] + 429\n\t8   WebDriverAgentLib            ...
[WD Proxy] The response has an unknown format
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[WD Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/CFDB509D-F487-4218-B440-9CFAAD8739AA/window/size] with no body
[MJSONWP (6d7b2baa)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplication resolve]: unrecognized selector sent to instance 0x600002b097a0
[MJSONWP (6d7b2baa)] 
[MJSONWP (6d7b2baa)] (
[MJSONWP (6d7b2baa)] 	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
[MJSONWP (6d7b2baa)] 	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
[MJSONWP (6d7b2baa)] 	2   CoreFoundation                      0x00007fff23bb9704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
[MJSONWP (6d7b2baa)] 	3   CoreFoundation                      0x00007fff23b9d7bc ___forwarding___ + 1436
[MJSONWP (6d7b2baa)] 	4   CoreFoundation                      0x00007fff23b9f6c8 _CF_forwarding_prep_0 + 120
[MJSONWP (6d7b2baa)] 	5   WebDriverAgentLib                   0x000000010da7c3e1 -[XCUIElement(FBUtilities) fb_snapshotWithAttributes] + 97
[MJSONWP (6d7b2baa)] 	6   WebDriverAgentLib                   0x000000010da4a746 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 966
[MJSONWP (6d7b2baa)] 	7   WebDriverAgentLib                   0x000000010da49abd +[FBXPath xmlRepresentationWithRootElement:writer:elementStore:query:] + 429
[MJSONWP (6d7b2baa)] 	8   WebDriverAgentLib                   0x000000010da48e8f +[FBXPath xmlStringWithRootElement:] + 95
[MJSONWP (6d7b2baa)] 	9   WebDriverAgentLib                   0x000000010da57b36 -[XCUIApplication(FBHelpers) fb_xmlRepresentation] + 54
[MJSONWP (6d7b2baa)] 	10  WebDriverAgentLib                   0x000000010da78c7a +[FBDebugCommands handleGetSourceCommand:] + 538
[MJSONWP (6d7b2baa)] 	11  WebDriverAgentLib                   0x000000010da65796 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182
[MJSONWP (6d7b2baa)] 	12  WebDriverAgentLib                   0x000000010da52b2b __37-[FBWebServer registerRouteHandlers:]_block_invoke + 555
[MJSONWP (6d7b2baa)] 	13  RoutingHTTPServer                   0x000000010db9fa37 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
[MJSONWP (6d7b2baa)] 	14  RoutingHTTPServer                   0x000000010dba034a __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
[MJSONWP (6d7b2baa)] 	15  libdispatch.dylib                   0x00007fff511fc7f9 _dispatch_client_callout + 8
[MJSONWP (6d7b2baa)] 	16  libdispatch.dylib                   0x00007fff512098e8 _dispatch_async_and_wait_invoke + 109
[MJSONWP (6d7b2baa)] 	17  libdispatch.dylib                   0x00007fff511fc7f9 _dispatch_client_callout + 8
[MJSONWP (6d7b2baa)] 	18  libdispatch.dylib                   0x00007fff51208d22 _dispatch_main_queue_callback_4CF + 1212
[MJSONWP (6d7b2baa)] 	19  CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
[MJSONWP (6d7b2baa)] 	20  CoreFoundation                      0x00007fff23af62f9 __CFRunLoopRun + 2329
[MJSONWP (6d7b2baa)] 	21  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
[MJSONWP (6d7b2baa)] 	22  Foundation                          0x00007fff2566d0df -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
[MJSONWP (6d7b2baa)] 	23  WebDriverAgentLib                   0x000000010da51450 -[FBWebServer startServing] + 368
[MJSONWP (6d7b2baa)] 	24  WebDriverAgentRunner                0x000000010da3dfba -[UITestingUITests testRunner] + 106
[MJSONWP (6d7b2baa)] 	25  CoreFoundation                      0x00007fff23b9f95c __invoking___ + 140
[MJSONWP (6d7b2baa)] 	26  CoreFoundation                      0x00007fff23b9cd8f -[NSInvocation invoke] + 287
[MJSONWP (6d7b2baa)] 	27  XCTest                              0x000000010b908121 __24-[XCTestCase invokeTest]_block_invoke.208 + 78
[MJSONWP (6d7b2baa)] 	28  XCTest                              0x000000010b9621e2 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
[MJSONWP (6d7b2baa)] 	29  XCTest                              0x000000010b962100 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
[MJSONWP (6d7b2baa)] 	30  XCTest                              0x000000010b907c0a __24-[XCTestCase invokeTest]_block_invoke + 1153
[MJSONWP (6d7b2baa)] 	31  XCTest                              0x000000010b969424 -[XCUITestContext performInScope:] + 117
[MJSONWP (6d7b2baa)] 	32  XCTest                              0x000000010b9076c6 -[XCTestCase testContextPerformInScope:] + 183
[MJSONWP (6d7b2baa)] 	33  XCTest                              0x000000010b90777c -[XCTestCase invokeTest] + 137
[MJSONWP (6d7b2baa)] 	34  XCTest                              0x000000010b9094ed __26-[XCTestCase performTest:]_block_invoke_2 + 43
[MJSONWP (6d7b2baa)] 	35  XCTest                              0x000000010b9621e2 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
[MJSONWP (6d7b2baa)] 	36  XCTest                              0x000000010b962100 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
[MJSONWP (6d7b2baa)] 	37  XCTest                              0x000000010b909404 __26-[XCTestCase performTest:]_block_invoke.334 + 88
[MJSONWP (6d7b2baa)] 	38  XCTest                              0x000000010b975492 +[XCTContext runInContextForTestCase:block:] + 219
[MJSONWP (6d7b2baa)] 	39  XCTest                              0x000000010b908b73 -[XCTestCase performTest:] + 668
[MJSONWP (6d7b2baa)] 	40  XCTest                              0x000000010b94e077 -[XCTest runTest] + 57
[MJSONWP (6d7b2baa)] 	41  XCTest                              0x000000010b90314a __27-[XCTestSuite performTest:]_block_invoke + 365
[MJSONWP (6d7b2baa)] 	42  XCTest                              0x000000010b902874 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
[MJSONWP (6d7b2baa)] 	43  XCTest                              0x000000010b902b71 -[XCTestSuite performTest:] + 355
[MJSONWP (6d7b2baa)] 	44  XCTest                              0x000000010b94e077 -[XCTest runTest] + 57
[MJSONWP (6d7b2baa)] 	45  XCTest                              0x000000010b90314a __27-[XCTestSuite performTest:]_block_invoke + 365
[MJSONWP (6d7b2baa)] 	46  XCTest                              0x000000010b902874 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
[MJSONWP (6d7b2baa)] 	47  XCTest                              0x000000010b902b71 -[XCTestSuite performTest:] + 355
[MJSONWP (6d7b2baa)] 	48  XCTest                              0x000000010b94e077 -[XCTest runTest] + 57
[MJSONWP (6d7b2baa)] 	49  XCTest                              0x000000010b90314a __27-[XCTestSuite performTest:]_block_invoke + 365
[MJSONWP (6d7b2baa)] 	50  XCTest                              0x000000010b902874 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 54
[MJSONWP (6d7b2baa)] 	51  XCTest                              0x000000010b902b71 -[XCTestSuite performTest:] + 355
[MJSONWP (6d7b2baa)] 	52  XCTest                              0x000000010b94e077 -[XCTest runTest] + 57
[MJSONWP (6d7b2baa)] 	53  XCTest                              0x000000010b98443e __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
[MJSONWP (6d7b2baa)] 	54  XCTest                              0x000000010b984541 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.84 + 118
[MJSONWP (6d7b2baa)] 	55  XCTest                              0x000000010b91ce83 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
[MJSONWP (6d7b2baa)] 	56  XCTest                              0x000000010b9841fd -[XCTTestRunSession runTestsAndReturnError:] + 623
[MJSONWP (6d7b2baa)] 	57  XCTest                              0x000000010b8e66d7 -[XCTestDriver runTestsAndReturnError:] + 456
[MJSONWP (6d7b2baa)] 	58  XCTest                              0x000000010b9716e4 _XCTestMain + 2484
[MJSONWP (6d7b2baa)] 	59  WebDriverAgentRunner-Runner         0x000000010b638edd -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
[MJSONWP (6d7b2baa)] 	60  WebDriverAgentRunner-Runner         0x000000010b638ddb _XCTRunnerRunTests + 0
[MJSONWP (6d7b2baa)] 	61  CoreFoundation                      0x00007fff23afb8ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
[MJSONWP (6d7b2baa)] 	62  CoreFoundation                      0x00007fff23afb058 __CFRunLoopDoBlocks + 312
[MJSONWP (6d7b2baa)] 	63  CoreFoundation                      0x00007fff23af5ee4 __CFRunLoopRun + 1284
[MJSONWP (6d7b2baa)] 	64  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
[MJSONWP (6d7b2baa)] 	65  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
[MJSONWP (6d7b2baa)] 	66  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
[MJSONWP (6d7b2baa)] 	67  WebDriverAgentRunner-Runner         0x000000010b639098 main + 183
[MJSONWP (6d7b2baa)] 	68  libdyld.dylib                       0x00007fff5123bcf5 start + 1
[MJSONWP (6d7b2baa)] 	69  ???                                 0x0000000000000005 0x0 + 5
[MJSONWP (6d7b2baa)] )
[MJSONWP (6d7b2baa)]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[MJSONWP (6d7b2baa)]     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[MJSONWP (6d7b2baa)]     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:279:19)
[HTTP] <-- GET /wd/hub/session/6d7b2baa-405d-4a5e-9081-8f5178403eae/source 500 55 ms - 7721
[HTTP] 
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : "-[XCApplicationQuery elementSnapshotForDebugDescription]: unrecognized selector sent to instance 0x600002433f00\n\n(\n\t0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23bb9704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      0x00007fff23b9d7bc ___forwarding___ + 1436\n\t4   CoreFoundation                      0x00007fff23b9f6c8 _CF_forwarding_prep_0 + 120\n\t5   WebDriverAgentLib                   0x000000010da7c354 -[XCUIElement(FBUtilities) fb_lastSnapshot] + 68\n\t6   WebDriverAgentLib                   0x000000010da739d1 -[XCUIElement(WebDriverAttributesForwarding) fb_snapshotForAttributeName:] + 785\n\t7   WebDriverAgentLib                   0x000000010da73c18 -[XCUIElement(WebDriverAttributesForwarding) forwardingTargetForSelector:] + 152\n\t8   CoreFoundation ...
[WD Proxy] The response has an unknown format
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/CFDB509D-F487-4218-B440-9CFAAD8739AA/screenshot] with no body

## Environment

- I am running Appium Desktop version _1.13.0_.
- I am on :
    - [x] Mac
    - [x] Xcode 11

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/13274#issuecomment-534104665

You can try out the latest rc or beta which has Xcode 11 fixes.
https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Comment by Yelisey** [comment]
@KazuCocoa but, in 1.14.0-beta.1 (https://github.com/appium/appium-desktop/releases/tag/v1.14.0-beta.1) - bug reproduced

**Comment by KazuCocoa** [comment]
Appium desktop has no fixes for Xcode 11.
I meant Appium server which can get via `npm` command.

Could you try out installing `appium@beta`(which is labeled as 1.15.0) following https://github.com/appium/appium-desktop#connect-to-local-appium-server ?

**Comment by zzq22406** [comment]
Ok I will try，thank u




| |
张振强
|
|
邮箱：zzq22406@163.com
|

签名由 网易邮箱大师 定制

On 09/24/2019 06:57, Kazuaki Matsuo wrote:

appium/appium#13274 (comment)

You can try out the latest rc or beta which has Xcode 11 fixes.
https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Comment by Mmallineni** [comment]
same issue. I 'm facing. I have 1.15.0-rc.5. An unknown server-side error occurred while processing the command. Original error: -[XCApplicationQuery elementSnapshotForDebugDescription]: unrecognized selector sent to instance 0x600003c46b80

**Comment by KazuCocoa** [comment]
Could you share the full log with showXcodeLog?

**Comment by zzq22406** [comment]
You can try Xcode10.3 ,Appium 1.14.0
Now I have no problems








At 2019-10-01 19:47:46, "Kazuaki Matsuo" <notifications@github.com> wrote:


Could you share the full log with showXcodeLog?
