### ISSUE TITLE
When appium-desktop 1.15 comes out, you can't locate the element now

### ISSUE THREAD

**Issue by liuchengxu11** [appium/appium-desktop#1100]
Appium Desktop

## The problem

Element positioning problems can not be accurately positioned to button and input box, can only find the outermost layer of the region
![image](https://user-images.githubusercontent.com/33363646/65779857-1faa6b00-e17b-11e9-81e8-a042297b8c32.png)

## Environment
.
    - Mac
    -iphone  ios-13
    - appium 1.15

**Comment by KazuCocoa** [comment]
Sorry for the delay. A task to create the package failed, I found.
We can push the 1.15.0 package after fixing it.
Maybe https://github.com/appium/appium-desktop/pull/1102 can fix it.

**Comment by KazuCocoa** [comment]
Should be, but the latest desktop has another issue, `The "path" argument must be of type string. Received type undefined`, which happens in some environment.

You can try out the latest Appium 1.15.0 via your desktop as https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Comment by pazzinivinicius** [comment]
I am using this one **Version 1.15.0-1 (1.15.0-1.20191004.1)** and still having problem

**Comment by KazuCocoa** [comment]
The elements do not appear on the page source, apple's xctest framework cannot detect them, perhaps.

For iOS 13, IncludeNonModalElements setting API may help in case the view is nested modal views, for example.
http://appium.io/docs/en/advanced-concepts/settings/

**Comment by pazzinivinicius** [comment]
Thank you, it worked.
For anyone looking for how to set the settings on Appium Desktop:
![image](https://user-images.githubusercontent.com/56402411/66636615-d7c32380-ec11-11e9-8384-0dfd6c6e3ced.png)
