### ISSUE TITLE
where can I get Appium desktop Appium-mac-1.15.0.dmg

### ISSUE THREAD

**Issue by automationpss** [appium/appium-desktop#1105]
cannot find Appium-mac-1.15.0.dmg file from https://github.com/appium/appium-desktop/releases/tag/v1.15.0
where can I get Appium desktop Appium-mac-1.15.0.dmg

**Comment by KazuCocoa** [comment]
Our packaging tasks on CI is failing because of the environment issue.
After it succeeds, they will be in https://github.com/appium/appium-desktop/releases

Please follow https://github.com/appium/appium-desktop/issues/1096 until it...

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.15.0
Published
