### ISSUE TITLE
Cannot Get Appium Desktop to Work in iOS13

### ISSUE THREAD

**Issue by awhisler-nutrien** [appium/appium-desktop#1109]
##Appium Desktop

Tried running iOS13 with Appium 1.13.0 and 1.14.0 
Appium Desktop 1.14.0 throws this error when I try opening the inspector
`[HTTP] <-- GET /wd/hub/session/9cb9fe75-264e-4dbd-9281-0666a59259ce/window/current/size 500`

And infinite spinner happens

## The problem
Can't open the Appium Desktop inspector with iOS13

## Environment

- I am running Appium Desktop version 1.14.0
- I am on:
    - [x] Mac

**Comment by awhisler-nutrien** [comment]
I tried doing the 1.14.0 workaround and it does not work for me

**Precondition:** Appium Desktop version 1.13.0
**Steps:**
1. In terminal: npm install -g appium@1.14.0
2. In terminal: appium
3. Open Appium Desktop - change host to localhost, port 4723
4. Select menu "Appium" > New Session Window
5. Tab to Custom Server
6. Remote host: localhost, Remote port: 4723, Remote path: /wd/hub
7. Selected my capabilities
8. Start session

Infinite spinning!!
**Appium Error:** [HTTP] <-- GET /wd/hub/session/3b7e00b1-443b-4cbe-99b5-9c4d46fa6164/window/current/size 500

**Comment by KazuCocoa** [comment]
Please install appium 1.15.0 instead of `appium@1.14.0`

**Comment by dpgraham** [comment]
Appium v1.15.0 is out (Appium Desktop v1.15.0-1)

**Comment by Neetzis** [comment]
Step by Step work around is:

1. Start Appium server from the command line (1.15.0-beta.1)
2. Start the Appium Desktop app. Do NOT click "Start Server"
3. Launch the new session window (go up to "Appium desktop" (mac) or "File" (windows) and click new session from the menu)
4. Open the "Custom Server" tab of the new session window
5. Enter your local Appium server host and port (localhost / 4723)
6. Enter your capabilities 
7. Start the session as normal. This will start a session using the Appium instance you have running on the command line, which is 1.15.0-beta.1

Original error:
On using Appium desktop 1.14 with server version 1.15.0-beta.1- accessibility inspector does not work. Loads infinitely.

Error - [HTTP] <-- GET /wd/hub/session/517796b5-170a-4258-ad88-228f502bf9b6/window/current/size 500 284 ms - 8215

& 
Error- 
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[MJSONWP (0713876f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[FBApplication resolve]: unrecognized selector sent to instance 0x282d10230
