### ISSUE TITLE
where can I get Appium desktop Appium-mac-1.15.0.dmg

### ISSUE THREAD

**Issue by automationpss** [appium/appium-desktop#1110]
I created ticket 1105, which told me to follow #1096, which is closed now.
But from https://github.com/appium/appium-desktop/releases/tag/v1.15.0, I cannot find Appium-mac-1.15.0.dmg
Am I supposed to build Appium-mac-1.15.0.dmg file based on "Source code"?

**Comment by automationpss** [comment]
I saw someone downloaded Appium-mac-1.15.0.dmg already, can someone tell me where to download it?

**Comment by KazuCocoa** [comment]
It was disabled because of https://github.com/appium/appium-desktop/issues/1107

**Comment by dpgraham** [comment]
Out now as 1.15.0-1
