### ISSUE TITLE
Could not install app with Appium 1.15.0-1

### ISSUE THREAD

**Issue by KS261187** [appium/appium-desktop#1116]
## The problem

I have recently downloaded the latest version of Appium which is 1.15.1 and when I try to install the app through inspector, I get the error Could not install app: 'The "path" argument must be of type string. Received type undefined'. I have also tried upgrading the node js and it didn't work either. Before this Appium, I was using the beta version of Appium 1.15 and it was working fine. Not sure what I am doing wrong here.

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.0-1
* Last Appium version that did not exhibit the issue (if applicable):1.15 beta
* Desktop OS/version used to run Appium:Mac OS
* Node.js version (unless using Appium.app|exe):v12.11.1
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:IOS
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
@KS261187 I'll look into but installing and running appium through the command line:

```
npm install -g appium
appium
```

...is always a good workaround for problems with the Appium bundle.

**Comment by viktorgogulenko** [comment]
I was going to post this bug, but @KS261187 was faster :). This is definitely a problem with 1.15.0-1 as when I'm launching appium server from command line (which is 1.15.0) and then configure Appium Desktop to use this custom server - everything fine. And as soon as I'm switching to default desktop version server - I'm receiving an error with path while installation. Is it related to [these changes](https://github.com/appium/appium-xcuitest-driver/commit/35ae6c5598fed3b3b880ed0a9497c7d0707ed6fc#diff-aedbcb2865a6aa45e4b096f30c094992)?
P.S. when I'm switching to Appium 1.14.0 - also installation is going fine.

**Comment by ervuks** [comment]
Just updated Appium Desktop app to `v1.15.0` and run into the same issue about the path. Here are logs from appium: 
```js
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Installing 'some.app' on device with UUID '**************************'...
[XCUITest] Error was thrown during the installation process
[XCUITest] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[XCUITest]     at assertPath (path.js:39:11)
[XCUITest]     at Object.join (path.js:1157:7)
[XCUITest]     at Object.join [as walkDir] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/fs.js:76:29)
[XCUITest] Error: Could not install app: 'The "path" argument must be of type string. Received type undefined'
[XCUITest]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[DevCon Factory] Releasing connections for  '**************************'... device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1570443775901 (13:22:55 GMT+0300 (EEST))
[MJSONWP] Encountered internal error running command: Error: Could not install app: 'The "path" argument must be of type string. Received type undefined'
[MJSONWP]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[HTTP] <-- POST /wd/hub/session 500 1266 ms - 231
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 4 ms - 57
[HTTP] 
```

When using a custom server from CLI (`1.15.0`), it works as expected.

**Comment by SlawpLabs** [comment]
Same problem here. All good on 1.15.0, not working anymore on 1.15.0-1, same error message.

Thank you!

**Comment by claudiamariana04** [comment]
Same problem here. with 1.15.0 but when try run appium using only the bundle my appium work but with try install de app, same error message.

**Comment by anht3889** [comment]
Same problem here. I will downgrade to 1.15.0 to check if the issue happens.

**Comment by kawerty2** [comment]
The same issue.

It's sad you make a prod version with such bugs

**Comment by hadrianjmnz90** [comment]
Same issue

**Comment by SlawpLabs** [comment]
> The same issue.
> 
> It's sad you make a prod version with such bugs

Dude, it's a free tool, just use the previous version and say thank you.

**Comment by bennid** [comment]
Double check your node version... I saw this "path" error when my node version was older.

**Comment by dpgraham** [comment]
New pre-release is out for v1.15.1: https://github.com/appium/appium-desktop/releases/tag/v1.15.1

This should solve the problems. Let me know if it works.

**Comment by SlawpLabs** [comment]
> New pre-release is out for v1.15.1: https://github.com/appium/appium-desktop/releases/tag/v1.15.1
> 
> This should solve the problems. Let me know if it works.

Problem solved for me on v1.15.1, thank you!

**Comment by KazuCocoa** [comment]
thanks for the confirmation :)

**Comment by nguyenryan147** [comment]
> @KS261187 I'll look into but installing and running appium through the command line:
> 
> ```
> npm install -g appium
> appium
> ```
> 
> ...is always a good workaround for problems with the Appium bundle.

I'm curious. For those that use Appium in the terminal. How do you inspect for accessibility id's. Are there other tools that are used? I figure using Appium in the terminal might solve some of my issues but I use desktop for the inspector. Maybe I can just use both....

**Comment by KS261187** [comment]
You have to use the custom server from the Appium desktop, in order to inspect the elements for the Appium server that is launched from the terminal.

Step 1. Start the Appium server from the terminal, probably with the port 4443
Step 2. Start the Appium desktop and change the terminal to 4444 and then click on custom server and then start inspecting the elements.

You should be good to go.

Thanks
Krishann

**Comment by KazuCocoa** [comment]
As https://github.com/appium/appium-desktop/issues/1116#issuecomment-541546663 , 1.15.1 should work without the path error

**Comment by hadrianjmnz90** [comment]
I upgraded to v1.15.1 but at launch i get a pop up that says that the new version 1.15.0.1 is out now, i can live with that issue but i think i should not get that warning, right?

**Comment by KazuCocoa** [comment]
Yes, It is because the desktop 1.15.1 is pre-release in https://github.com/appium/appium-desktop/releases
After the label will be `release`, the latest one will be `1.15.1`

Let me check if we can add a description about the update system does not include pre-release version.
