### ISSUE TITLE
Appium-windows-1.15.0-1.exe can't download

### ISSUE THREAD

**Issue by ctlddey** [appium/appium-desktop#1118]
All other files can be downloaded normally.But Appium-windows-1.15.0-1.exe  download speed is  very slow and then it shows:
Download failure: server refuses to execute user request

**Comment by ctlddey** [comment]
Do you have any torrent

**Comment by KazuCocoa** [comment]
mm, I was able to download it.
Could you try again after a while?

**Comment by ctlddey** [comment]
> mm, I was able to download it.
> Could you try again after a while?

the speed is still very slow and then faild，but I find someone download @https://www.lanzous.com/i6n2fij

**Comment by KazuCocoa** [comment]
thanks.
It might be the internet route issue from github...
