### ISSUE TITLE
Encountered internal error running command: Error: No sim found with udid 

### ISSUE THREAD

**Issue by hujiachun** [appium/appium-desktop#112]
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"UDID":"ecab65eca01ae1d42874c26e645a33aee78296b6","app":"com.pingan.parsDev","autoAcceptAlerts":true,"deviceName":"iPhone 6","noReset":"false","platformName":"iOS","platformVersion":"9.3.2","resetKeyboard":"True","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"UDID":"ecab65eca01ae1d42874c26e645a33aee78296b6","app":"com.pingan.parsDev","autoAcceptAlerts":true,"deviceName":"iPhone 6","noReset":"false","platformName":"iOS","platformVersion":"9.3.2","resetKeyboard":"True","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1490942260349 (14:37:40 GMT+0800 (CST))
[Appium] Creating new IosDriver (v1.18.0) session
[Appium] Capabilities:
[Appium]   UDID: 'ecab65eca01ae1d42874c26e645a33aee78296b6'
[Appium]   app: 'com.pingan.parsDev'
[Appium]   autoAcceptAlerts: true
[Appium]   deviceName: 'iPhone 6'
[Appium]   noReset: 'false'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3.2'
[Appium]   resetKeyboard: 'True'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[iOS] IosDriver version: 1.18.0
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: UDID, resetKeyboard, connectHardwareKeyboard.
[BaseDriver] Session created with session id: 23bfd004-0c54-4a27-a033-c3f854d06c90
[iOS] Xcode version set to 7.3.1
[iOS] Not auto-detecting udid.
[iOS] App is an iOS bundle, will attempt to run as pre-existing
[iOS] Removing any remaining instruments sockets
[iOS] Cleaned up instruments socket /var/folders/vj/v1jr__5d0853wc35vlvrjyk40000gn/T/instruments_sock
[iOS] Setting iOS SDK Version
[iOS] iOS SDK Version set to 9.3
[Instruments] Getting list of devices instruments supports
[Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[Instruments] Available devices: iPhone 6 (9.3.2) [ecab65eca01ae1d42874c26e645a33aee78296b6],Apple TV 1080p (9.2) [097C0B35-32F5-4D71-A845-BFD7C3ACCDD4] (Simulator),iPad 2 (9.3) [0433D42C-E9F7-4746-AAAF-86183496BAB8] (Simulator),iPad Air (9.3) [08F615D7-1893-46E5-9E1A-094AC5B1E90A] (Simulator),iPad Air 2 (9.3) [6C99428B-53B9-4B83-9401-4E2C68A2D5F5] (Simulator),iPad Pro (9.3) [82F9C9D2-28A4-446B-A4DF-A42568036A3D] (Simulator),iPad Retina (9.3) [246EC63C-FE82-4D0E-B66B-E356CDF628D9] (Simulator),iPhone 4s (9.3) [FA0E52D2-6007-49DE-94A0-29319741B9E3] (Simulator),iPhone 5 (9.3) [BECF8C21-D143-4E22-9CAD-22301390855F] (Simulator),iPhone 5s (9.3) [BE570433-7F09-4994-B33D-1089D449FC49] (Simulator),iPhone 6 (9.3) [F099543A-FE2C-4CA7-81AE-2F3168B5D663] (Simulator),iPhone 6 Plus (9.3) [544BAA36-9CE0-4E44-BB01-EC4638E3F2AF] (Simulator),iPhone 6s (9.3) [01FF3920-160D-43AA-9324-4028E0D3897B] (Simulator),iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [95EF1273-423E-41B7-BD9E-2A58AED83404] (Simulator),iPhone 6s Plus (9.3) [98E7F54B-1510-4B96-BE4F-3FD8389AAC36] (Simulator),iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [F106F29C-3A58-425E-9AAC-D9628D9B752E] (Simulator)
[iOS] Checking whether our device string is supported
[iOSSim] Retrieving device name string for Xcode version 7.3.1
[iOSSim] Getting device string from options: {"deviceName":"iPhone 6","platformVersion":"9.3.2","forceIphone":false,"forceIpad":false}
[iOSSim] Final device string is 'iPhone 6 (9.3.2)'
[iOS] iOS sim UDID is ecab65eca01ae1d42874c26e645a33aee78296b6
[MJSONWP] Encountered internal error running command: Error: No sim found with udid ecab65eca01ae1d42874c26e645a33aee78296b6
    at getSimulator$ (/Applications/Appium 4.app/Contents/Resources/app/node_modules/appium-ios-simulator/lib/simulator.js:25:11)
    at tryCatch (/Applications/Appium 4.app/Contents/Resources/app/node_modules/appium-ios-simulator/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium 4.app/Contents/Resources/app/node_modules/appium-ios-simulator/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium 4.app/Contents/Resources/app/node_modules/appium-ios-simulator/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium 4.app/Contents/Resources/app/node_modules/appium-ios-simulator/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 1655 ms - 200 
[HTTP] --> DELETE /wd/hub/session {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 2 ms - 57

**Comment by dpgraham** [comment]
Try omitting the UDID from your desired capabilities.
