### ISSUE TITLE
[iOS] Invalid argument error thrown while installing the app

### ISSUE THREAD

**Issue by sasasa42** [appium/appium-desktop#1120]
## The problem
While trying to create a new session and installing the app.ipa on a real iOS device, I am facing the below error:
[XCUITest] Error: Could not install app: 'The "path" argument must be of type string. Received type undefined'. PFA the appium server logs.
Until before I updated to appium-desktop 1.15.0-1, I had no such issues while I was on 1.14.0.
This problem does not occur on appium 1.15.0, which means that I am able to execute well without any issues. I have already referred the linked issue https://github.com/appium/appium/issues/13318, but even after updating my node version to 10.16.3 LTS and 12.11.1, I don't find any change.

## Environment

- I am running Appium Desktop version _1.15.0-1_.
- I am on Mac

Logs:  [appium-server-logs-InvalidArg.txt](https://github.com/appium/appium-desktop/files/3700683/appium-server-logs-InvalidArg.txt)

**Comment by ynesterssl** [comment]
I have the same issue when running Appium Desktop version 1.15.0-1 and node v12.11.1.

When downgrade to Appium Desktop version 1.15.0 there is no error. But I cannot locate any element so app is useless.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.15.1

**Comment by KazuCocoa** [comment]
This error should be fixed in AD 1.15.1
appium/appium-desktop#1121
