### ISSUE TITLE
After installing Appium DeskTop / Appium Server, system is not creating WebDriverAgent Directory.

### ISSUE THREAD

**Issue by hp001** [appium/appium-desktop#1122]
## Appium Server and Appium Desktop? Both

Issue: I installed Appium Server and Appium Desktop latest version 1.15 and after installation I am not seeing WebDriverAgent directory. Any idea why and any one else having same issue.

****
java version "1.8.0_211"
Homebrew 2.1.13
Node: v12.11.1
NPM: 6.12.0
carthage version: 0.33.0
Xcode: 10.2.1
os: Mac Mojave 10.14.6 (18G95) 

I tried 4 to 5 times to uninstall and install every thing but WeDriverAgent folder is not finding under 
For appium DeskTop
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver

OR
For Appium Server under 
 /Users/local/node_modules/appium-xcuitest-driver/

Any one else having this issue?

if yes then how you resolved it?

**Comment by ynesterssl** [comment]
@hp001  check this directory 
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/

**Comment by hp001** [comment]
@ynesterssl it worked. Thanks a lot.
