### ISSUE TITLE
Could not connect to simulator - Make sure both host and port are correct and reachable

### ISSUE THREAD

**Issue by johnlim-tech** [appium/appium-desktop#1123]
## Appium or Appium Desktop?
Appium command line (Appium Desktop have the same issue )

## The problem
Launching the simulator will have an error 
 Make sure both host and port are correct and reachable

This is working when I have xcode 10. The setup is correct as Appium-doctor indicate it is config correctly 

This is my desired capabilities (in form of json)
"deviceName": "iPhone 11",
"platformName": "IOS",
"automationName": "XCuiTest",
"app": /Users//johnlim//Fintool//API//app//FintoolTracker-1.app",
"platformVersion" : "13.1"

_Replace this section with a description of your issue_

Appium Logs
https://gist.github.com/johnlim-tech/493bcc897b669833f53cb602ae4c7930

## Environment

Appium CLI
Mac OS 10.15 Catalina
Appium 15.0 CLI

**Comment by KazuCocoa** [comment]
That is `idb` https://github.com/facebook/idb  issue for Xcode 11, perhaps.
Do you mean Appium works, but idb had the issue?

**Comment by johnlim-tech** [comment]
Basically , when i launch with the desired capabilities setting  using Appium 1.15, webdriver agent is not installed.

**Comment by KazuCocoa** [comment]
The output of `./Scripts/bootstrap.sh -d` was expected.

But sorry your log is partial.
I cannot assume your situation without the full log.

**Comment by johnlim-tech** [comment]
@KazuCocoa 

Below is the full appium log :

https://gist.github.com/johnlim-tech/3dd93915d9be3c3df22b0fdcdaf62a9b

I added usePrebuiltWDA (true or false) , but the issue is still the same. 

Thanks

**Comment by johnlim-tech** [comment]
I found the offending issue. I remove the IDB and appium is working. Will file a defect in appium idb

**Comment by KazuCocoa** [comment]
thanks!
Closing this issue and please watch https://github.com/appium/appium-idb/issues/18
