### ISSUE TITLE
Appium Desktop 15 Unable to enter Chinese normally

### ISSUE THREAD

**Issue by LazyTang** [appium/appium-desktop#1125]
## Appium Desktop
Appium Desktop V.15 Unable to enter Chinese normally,Can normally enter a number;
# environment
1.Mac mini
2.robotframework+appium-desktop V.15
3.iOS模拟器
![image](https://user-images.githubusercontent.com/37360490/66639569-a36b5980-ec49-11e9-9763-3cc10c019901.png)
#LOG
[W3C (cd713671)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command
[W3C (cd713671)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:802:25)
[W3C (cd713671)]     at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:685:14)
[W3C (cd713671)]     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)
[HTTP] <-- POST /wd/hub/session/cd713671-0d14-48f1-b42a-d062c04042db/element/CB010000-0000-0000-117D-000000000000/value 500 5030 ms - 917
[HTTP] 
[HTTP] --> GET /wd/hub/session/cd713671-0d14-48f1-b42a-d062c04042db/screenshot
[HTTP] {}

**Comment by KazuCocoa** [comment]
Could you share the log with `showXcodeLog` true?

**Comment by LazyTang** [comment]
> 您可以与`showXcodeLog`true 共享日志吗？
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/3723458/appium-server-logs.txt)
这是appium的完整日志

**Comment by KazuCocoa** [comment]
Thanks.
`showXcodeLog` is a capability https://github.com/appium/appium-xcuitest-driver. You can set it as `true` to enable the capability.

btw, I can see only you sent numbers to the target element. Did you send Chinese characters?

```
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/a566181e-6da4-4fce-a08c-462c7eb012fa/elements [39m[32m200[39m [90m3232 ms - 139[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/a566181e-6da4-4fce-a08c-462c7eb012fa/element/BC010000-0000-0000-46F3-000000000000/value[39m
[info] [35m[HTTP][39m [90m{"text":"1232","sessionId":"a566181e-6da4-4fce-a08c-462c7eb012fa","id":"BC010000-0000-0000-46F3-000000000000","value":["1","2","3","2"]}[39m
[debug] [35m[W3C (a566181e)][39m Calling AppiumDriver.setValue() with args: [["1","2","3","2"],"BC010000-0000-0000-46F3-000000000000","a566181e-6da4-4fce-a08c-462c7eb012fa"]
[debug] [35m[XCUITest][39m Executing command 'setValue'
[debug] [35m[WD Proxy][39m Matched '/element/BC010000-0000-0000-46F3-000000000000/value' to command name 'setValue'
[debug] [35m[Protocol Converter][39m Added 'text' property "1232" to 'setValue' request body
[debug] [35m[WD Proxy][39m Proxying [POST /element/BC010000-0000-0000-46F3-000000000000/value] to [POST http://localhost:8100/session/4625B45A-CD01-4AD4-A32E-1FA940F04290/element/BC010000-0000-0000-46F3-000000000000/value] with body: {"value":["1","2","3","2"],"text":"1232"}[info] [35m[WD Proxy][39m Got an unexpected response with status 500: {"value":{"error":"unknown error","message":"An unknown server-side error occurred while processing the command","traceback":""},"sessionId":"4625B45A-CD01-4AD4-A32E-1FA940F04290"}
[debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
[debug] [35m[WD Proxy][39m Matched '/element/BC010000-0000-0000-46F3-000000000000/attribute/type' to command name 'getAttribute'
[debug] [35m[WD Proxy][39m Proxying [GET /element/BC010000-0000-0000-46F3-000000000000/attribute/type] to [GET http://localhost:8100/session/4625B45A-CD01-4AD4-A32E-1FA940F04290/element/BC010000-0000-0000-46F3-000000000000/attribute/type] with no body[debug] [35m[WD Proxy][39m Got response with status 200: {
[debug] [35m[WD Proxy][39m   "value" : "XCUIElementTypeStaticText",
[debug] [35m[WD Proxy][39m   "sessionId" : "4625B45A-CD01-4AD4-A32E-1FA940F04290"
[debug] [35m[WD Proxy][39m }
[debug] [35m[W3C (a566181e)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command
[debug] [35m[W3C (a566181e)][39m     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:802:25)
[debug] [35m[W3C (a566181e)][39m     at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:685:14)
[debug] [35m[W3C (a566181e)][39m     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/a566181e-6da4-4fce-a08c-462c7eb012fa/element/BC010000-0000-0000-46F3-000000000000/value [39m[31m500[39m [90m3659 ms - 
```


And I was able to see below error. The target element is `XCUIElementTypeStaticText`. I wonder if Appium can set values into the element. I mean the element is not `XCUIElementTypeTextField`, but it works?

```
[debug] [35m[WD Proxy][39m Matched '/element/BC010000-0000-0000-46F3-000000000000/attribute/type' to command name 'getAttribute'
[debug] [35m[WD Proxy][39m Proxying [GET /element/BC010000-0000-0000-46F3-000000000000/attribute/type] to [GET http://localhost:8100/session/4625B45A-CD01-4AD4-A32E-1FA940F04290/element/BC010000-0000-0000-46F3-000000000000/attribute/type] with no body[debug] [35m[WD Proxy][39m Got response with status 200: {
[debug] [35m[WD Proxy][39m   "value" : "XCUIElementTypeStaticText",
[debug] [35m[WD Proxy][39m   "sessionId" : "4625B45A-CD01-4AD4-A32E-1FA940F04290"
[debug] [35m[WD Proxy][39m }
[debug] [35m[W3C (a566181e)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command
[debug] [35m[W3C (a566181e)][39m     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:802:25)
[debug] [35m[W3C (a566181e)][39m     at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:685:14)
[debug] [35m[W3C (a566181e)][39m     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)
```

**Comment by LazyTang** [comment]
> XCUIElementTypeTextField
Before the input of Chinese characters is not good, I tried to input Numbers, is not good; Let me see. Thanks for the answer

**Comment by KazuCocoa** [comment]
You can also try out appium server (not this desktop app) if the root issue is AD side or xcuitest side

**Comment by LazyTang** [comment]
在这个环境下能正常输入
[info] [35m[Appium][39m Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   platformName: iOS
[info] [35m[Appium][39m   platformVersion: 12.4
[info] [35m[Appium][39m   deviceName: 'iPhone Xs Max'
[info] [35m[Appium][39m   bundleId: com.tgf.kcwc
[info] [35m[Appium][39m   udid: 4418A944-49EF-4282-8FB3-997A3DB815EF
[info] [35m[Appium][39m   automationName: XCUITest
[info] [35m[Appium][39m   noReset: true
[info] [35m[Appium][39m   unicodeKeyboard: True
[info] [35m[Appium][39m   resetKeyboard: True
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"iOS","plat... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[warn] [35m[BaseDriver][39m Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: unicodeKeyboard, resetKeyboard.
[info] [35m[BaseDriver][39m Session created with session id: 9935d6fc-185b-4ee8-8fa3-b0934287c0cf
[debug] [35m[XCUITest][39m Current user: 'tiger'
[debug] [35m[XCUITest][39m Available devices: [info] [35m[iOSSim][39m Constructing iOS simulator for Xcode version 10.3 with udid '4418A944-49EF-4282-8FB3-997A3DB815EF'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: '4418A944-49EF-4282-8FB3-997A3DB815EF', real device: false
[info] [35m[XCUITest][39m iOS SDK Version set to '12.4'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1574235892646 (15:44:52 GMT+0800 (CST))
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1574235892647 (15:44:52 GMT+0800 (CST))
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1574235892647 (15:44:52 GMT+0800 (CST))
[debug] [35m[XCUITest][39m Reset: noReset is on. Leaving simulator as is
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1574235892647 (15:44:52 GMT+0800 (CST))[debug] [35m[XCUITest][39m Starting log capture for iOS Simulator with udid '4418A944-49EF-4282-8FB3-997A3DB815EF', using 'xcrun simctl spawn 4418A944-49EF-4282-8FB3-997A3DB815EF log stream --style compact'[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1574235893433 (15:44:53 GMT+0800 (CST))
[info] [35m[XCUITest][39m Setting up simulator
[debug] [35m[iOS][39m No reason to set locale
[debug] [35m[iOS][39m No iOS / app preferences to set
[debug] [35m[iOSSim][39m Setting preferences of 4418A944-49EF-4282-8FB3-997A3DB815EF Simulator to {"ConnectHardwareKeyboard":false}
[debug] [35m[iOSSim][39m Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [35m[iOSSim][39m Updated 4418A944-49EF-4282-8FB3-997A3DB815EF Simulator preferences at '/Users/tiger/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"4418A944-49EF-4282-8FB3-997A3DB815EF":{"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}[debug] [35m[iOSSim][39m Got Simulator UI client PID: 8838
[info] [35m[iOSSim][39m Both Simulator with UDID 4418A944-49EF-4282-8FB3-997A3DB815EF and the UI client are currently running
[debug] [35m[BaseDriver][39m Event 'simStarted' logged at 1574235893785 (15:44:53 GMT+0800 (CST))[info] [35m[XCUITest][39m Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [35m[XCUITest][39m Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [35m[XCUITest][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found[debug] [35m[XCUITest][39m Parsed BUILD_DIR configuration value: '/Users/tiger/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products'
[debug] [35m[XCUITest][39m Got derived data root: '/Users/tiger/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key '/Users/tiger/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.4\",\n      \"sdkVersion\" : \"12.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.4\",\n      \"ip\" : \"192.168.0.114\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1574235679980\",\n      \"time\" : \"Nov 20 2019 15:41:29\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"A46A24F5-1318-43F4-AD0A-0C912341A045\",\n  \"status\" : 0\n}"
[debug] [35m[WD Proxy][39m Determined that the downstream protocol for proxy is MJSONWP
[debug] [35m[XCUITest][39m Upgrade timestamp of the currently bundled WDA: 1574235679980
[debug] [35m[XCUITest][39m Upgrade timestamp of the WDA on the device: 1574235679980
[info] [35m[XCUITest][39m Will reuse previously cached WDA instance at 'http://localhost:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1574235897120 (15:44:57 GMT+0800 (CST))
[info] [35m[XCUITest][39m Using provided WebdriverAgent at 'http://localhost:8100/'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.4\",\n      \"sdkVersion\" : \"12.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.4\",\n      \"ip\" : \"192.168.0.114\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1574235679980\",\n      \"time\" : \"Nov 20 2019 15:41:29\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"A46A24F5-1318-43F4-AD0A-0C912341A045\",\n  \"status\" : 0\n}"
[debug] [35m[WD Proxy][39m Determined that the downstream protocol for proxy is MJSONWP
