### ISSUE TITLE
UIAutomation2 is only supported since Android 5.0 (Lollipop). You could still use other supported backends in order to automate older Android versions.

### ISSUE THREAD

**Issue by godtang** [appium/appium-desktop#1127]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: UIAutomation2 is only supported since Android 5.0 (Lollipop). You could still use other supported backends in order to automate older Android versions.
_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version 1.15.0.
- I am on Windows

it's worked on redmi note 6 A (android 9)and huawei honor dua-al00(android 8.1.0)
but in huawei honor pe-tl20(android 4.2.2) , it doesn't work
i used python like this
def get_desired_capabilities():
    desired_caps={}
    desired_caps['platformName']='Android'
    
    #华为荣耀X1
    desired_caps['platformVersion']='4.4.2'
    desired_caps['deviceName'] = 'T7K6R14B01000626'
    '''
    #华为荣耀6P
    desired_caps['platformVersion']='4.4.2'
    desired_caps['deviceName'] = 'F8UDU15818002253'
    #华为荣耀畅玩7
    desired_caps['platformVersion']='8.1.0'
    desired_caps['deviceName']='HFK9K19330910557'
    #小米NOTE6A
    desired_caps['platformVersion']='9'
    desired_caps['deviceName'] = '0d68e2427d32'
    '''

    desired_caps['noReset']=True

    #测试apk包的路径
    #desired_caps['app']="D:/CODE/IM_project_net_phone/android/app/build/outputs/apk/debug/app-debug.apk" 

    #如果设置了apk包的路径，则不需要配appPackage和appActivity
    desired_caps['appPackage']='com.lx.netphone'
    desired_caps['appWaitPackage']='com.lx.netphone'
    desired_caps['appActivity']='MainActivity'
    
    desired_caps['newCommandTimeout']=30
    desired_caps['automationName']='Appium'
    #desired_caps['autoGrantPermissions']=True

    return desired_caps

def get_uri():
    return 'http://localhost:4723/wd/hub'

**Comment by KazuCocoa** [comment]
Could you share the full log?
The default `automationName` has been changed in Appium 1.14.0.
https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-1140-from-1130
As the error, you should specify the `automationName` as UIAutomation1 for Android 4.4

**Comment by godtang** [comment]
yes , it's worked, thank you
