### ISSUE TITLE
service error

### ISSUE THREAD

**Issue by lzhang1** [appium/appium-desktop#1129]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist."

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you attache the full appium log?

**Comment by lzhang1** [comment]
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2019-10-15 16:21:40.174 xcodebuild[45956:292700] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/zhanglei/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fd09d15bc90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2019-10-15 16:21:40.188 xcodebuild[45956:292763] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/zhanglei/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2019.10.15_16-21-40-+0800.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-B4C144F3-483C-4086-92B9-C45546B2D0E6/WebDriverAgentRunner-74F2EE2C-89BB-418E-80DE-33BDF5E69AEB/Session-WebDriverAgentRunner-2019-10-15_162140-8TXVIM.log 2019-10-15 16:21:40.189 xcodebuild[45956:292545] [MT] IDETestOperationsObserverDebug: (45198631-C30E-4F30-813D-6344BEEA38FA) Beginning test session WebDriverAgentRunner-45198631-C30E-4F30-813D-6344BEEA38FA at 2019-10-15 16:21:40.189 with Xcode 11A1027 on target 📱<DVTiOSDevice (0x7fd09d2c62a0), iPhone6s, iPhone, 9.3.5 (13G36), 779d002b3af2d440460a16a4a5567bc9ac919470> { deviceSerialNumber: FFMS2GZCGRYF identifier: 779d002b3af2d440460a16a4a5567bc9ac919470 deviceClass: iPhone deviceName: iPhone6s deviceIdentifier: 779d002b3af2d440460a16a4a5567bc9ac919470 productVersion: 9.3.5 buildVersion: 13G36 deviceSoftwareVersion: 9.3.5 (13G36) deviceArchitecture: arm64 deviceTotalCapacity: 59707891712 deviceAvailableCapacity: 57362370560 deviceIsTransient: NO ignored: NO deviceIsBusy: NO deviceIsPaired: YES deviceIsActivated: YES deviceActivationState: Activated isPasscodeLocked: NO deviceType: <DVTDeviceType:0x7fd09cf54bc0 Xcode.DeviceType.iPhone> supportedDeviceFamilies: ( 1 ) applications: (null) provisioningProfiles: (null) hasInternalSupport: NO hasWritableSystem: NO isSupportedOS: YES bootArgs: (null) nextBootArgs: (null) connected: YES isWirelessEnabled: NO connectionType: direct hostname: iPhone6s.local. bonjourServiceName: 8c:8e:f2:b7:79:71@fe80::8e8e:f2ff:feb7:7971._apple-mobdev2._tcp.local. activeProxiedDevice: (null) } (9.3.5 (13G36)) 2019-10-15 16:21:44.367 xcodebuild[45956:292545] [MT] IDETestOperationsObserverDebug: (45198631-C30E-4F30-813D-6344BEEA38FA) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/zhanglei/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2019.10.15_16-21-40-+0800.xcresult 2019-10-15 16:21:44.386 xcodebuild[45956:292545] [MT] IDETestOperationsObserverDebug: 4.203 elapsed -- Testing started completed. 2019-10-15 16:21:44.386 xcodebuild[45956:292545] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2019-10-15 16:21:44.386 xcodebuild[45956:292545] [MT]

**Comment by lzhang1** [comment]
This command result 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=xxx' test


Test Case '-[UITestingUITests testRunner]' started.
    t =     0.02s Start Test at 2019-10-15 16:15:56.322
    t =     0.03s Set Up
2019-10-15 16:15:56.327 WebDriverAgentRunner-Runner[260:15252] Built at Oct 15 2019 16:15:30
2019-10-15 16:15:56.348 WebDriverAgentRunner-Runner[260:15252] ServerURLHere->http://10.40.32.59:8100<-ServerURLHere
2019-10-15 16:15:56.349 WebDriverAgentRunner-Runner[260:15295] Using singleton test manager
2019-10-15 16:15:56.350 WebDriverAgentRunner-Runner[260:15295] MJPEG server cannot start because the current iOS version is not supported

**Comment by KazuCocoa** [comment]
> An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2019-10-15 16:21:40.174 xcodebuild[45956:292700] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/zhanglei/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fd09d15bc90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2019-10-15 16:21:40.188 xcodebuild[45956:292763] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/zhanglei/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2019.10.15_16-21-40-+0800.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-B4C144F3-483C-4086-92B9-C45546B2D0E6/

Could you attach the full log?
I wondered what was your capabilities, and xcodebuild processes.
