### ISSUE TITLE
appium-desktop 1.15.0 -1 ，java TouchAction.press().moveTo().release().perform() is invalid.

### ISSUE THREAD

**Issue by YiQingZi** [appium/appium-desktop#1133]
#1090  appium-desktop 1.15.0 -1 ，java TouchAction.press().moveTo().release().perform()  is invalid.

`TouchAction touchAction = new TouchAction(androidDriver);`

`touchAction.press(new PointOption().withCoordinates(w_start,h_start)).moveTo(new PointOption().withCoordinates(w_end,h_end)).release().perform();`

But java TouchAction  works at appium-desktop 1.13.0.

## Environment

OS Name: Windows 10

Java Version: 1.8.0_161

**Comment by QITIE** [comment]
Face the same issue, using import io.appium.java_client.TouchAction;

**Comment by KazuCocoa** [comment]
Please attach the full server-side log.

I thought automationName change affected, but no idea
https://github.com/appium/appium/releases/tag/v1.14.0
