### ISSUE TITLE
Some elements are not recognized

### ISSUE THREAD

**Issue by liuchengxu11** [appium/appium-desktop#1134]
It is found that some elements on IOS are not recognized, but Android can. Is it related to the fact that app is developed using react native?

The screenshots below correspond to IOS and Android respectively！

-------------------------------ios----------------------------------------------------

![image](https://user-images.githubusercontent.com/33363646/66914042-8b7c4700-f048-11e9-80f7-c8bd2c98025f.png)
IOS has only one screen！！！
---------------------------------------android--------------------------------------
![image](https://user-images.githubusercontent.com/33363646/66914098-a3ec6180-f048-11e9-890a-b89c74237491.png)

![image](https://user-images.githubusercontent.com/33363646/66914151-bebed600-f048-11e9-99f7-3d5b93bec99f.png)

**Comment by KazuCocoa** [comment]
It depends on RN framework and how to implement them.

**Comment by liuchengxu11** [comment]
> 它取决于RN框架以及如何实现它们。

No elements, no automation. Is there any way to solve this problem?

**Comment by KazuCocoa** [comment]
How about adding testId http://facebook.github.io/react-native/docs/view#testid ?
It adds accessibilityLabel for iOS. Then, maybe iOS can detect the element...

You can also search and ask about this kind of question in https://discuss.appium.io

**Comment by likern** [comment]
@liuchengxu11 Does providing `accessible={true}` helps?

**Comment by KazuCocoa** [comment]
This root cause was RN side like the above accessible, accessibility or test id etc.
It seems not AppiumDesktop specific problem
