### ISSUE TITLE
Update generated WebdriverIO code to be compatible with the lastest version

### ISSUE THREAD

**Issue by wooseopkim** [appium/appium-desktop#1135]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

At this time, code generated by Appium Desktop's action recorder doesn't match the API provided with the latest version of WebdriverIO. For instance, you should find an element like `driver.$(selector)` with v5 API. But at this time the generated code uses `driver.element(selector)` method which used to be provided via v4.

Please note that most of the Appium documentations have already migrated to WebdriverIO v5, as you could see [here](http://appium.io/docs/en/about-appium/getting-started/).

- WebdriverIO latest documentation: <https://webdriver.io/docs/api/browser/$.html>
- WebdriverIO v4 documentation: <http://v4.webdriver.io/api/protocol/element.html>
- Appium Desktop code generator: <https://github.com/appium/appium-desktop/blob/master/app/renderer/lib/client-frameworks/js-wdio.js#L60>

## Environment

- I am running Appium Desktop version 1.15.0.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
thanks.
It is appreciated if you could create a PR :)
