### ISSUE TITLE
Cannot able to set to proxy -27753 for ios-webkit-debug-proxy.Working on real iOS device automation.

### ISSUE THREAD

**Issue by lakshmi-chaitanya1102** [appium/appium-desktop#1139]
Please help .

Cannot able to identify elements as proxy is not set to 27753

**Comment by KazuCocoa** [comment]
Please attach the log.
BTW, we no longer use  ios-webkit-debug-proxy in appium 1.15.0

**Comment by lakshmi-chaitanya1102** [comment]
Thanks ..

I can able to launch url using code but cannot able to enter username or password.

Giving error at below line -
AppiumDriver<WebElement> driver=new IOSDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

**Comment by KazuCocoa** [comment]
Not sure what the `username or password` means, but if the cause was your view interaction, please make sure they exist in your page source structure.

https://discuss.appium.io will help for asking questions.
