### ISSUE TITLE
Unable to get inspector in Safari browser in real device.

### ISSUE THREAD

**Issue by lakshmi-chaitanya1102** [appium/appium-desktop#1140]
iOS device-13.0
Appium-1.15

Below is the output from terminal:
ios_webkit_debug_proxy -c 2e14f5676455jdafkj3986c269fb374e2:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=851
ss.add_server_fd(4)
Could not connect to lockdownd, error code -17. Exiting.
ss.remove_server_fd(4)
Unable to attach e14f5676455jdafkj3986c269fb374e2 inspector

**Comment by KazuCocoa** [comment]
They haven't released ios 13 support https://github.com/google/ios-webkit-debug-proxy
We no longer use ios-webkit-debug-proxy in Appium 1.15.0+, so please ask them about ios_webkit_debug_proxy
