### ISSUE TITLE
Appium Desktop : “Appium” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by jutamasJeab** [appium/appium-desktop#1142]
## The problem
After install Appium desktop , I can't open appium.
<img width="424" alt="Screen Shot 2562-10-21 at 11 06 37" src="https://user-images.githubusercontent.com/9444184/67176559-b40f9280-f3f4-11e9-858d-c545ca2ebda7.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0-1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.0-1
* Desktop OS/version used to run Appium: MacOS Catalina 10.15
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Appium.app

**Comment by KazuCocoa** [comment]
The behaviour happens for apps which are not installed from app store.
(And security & privacy preferences)

**Comment by suaadBatis** [comment]
@KazuCocoa  it is working thanks boss

**Comment by ariarora14** [comment]
@KazuCocoa doesn't work any more :/

**Comment by KazuCocoa** [comment]
What macOS version did you use?
So far, I confirmed to open the app via context menu in the initial time or https://github.com/appium/appium-desktop#cannot-open-appium-desktop with macOS 11.5.
