### ISSUE TITLE
Is there any command parameters for "Appium.exe" to start server automatically ?

### ISSUE THREAD

**Issue by wzlsquall** [appium/appium-desktop#1147]
Excuse me

## The problem

Now I want to load "Appium.exe" and start the server automatically after Widows started up, is there any command parameters for "Appium.exe" that can help me ?

## Environment

- I am running Appium Desktop version _1.15.0-1.
- I am on : Windows 10

**Comment by KazuCocoa** [comment]
Do you mean you'd like to launch an appium server in Appium Desktop automatically after login to windows?
You can launch Appium Desktop, but maybe we have no way to launch the server without interactions.

I'm not familiar with windows settings, but you can try appium https://github.com/appium/appium/releases to launch the server automatically after logging into Windows.

**Comment by KazuCocoa** [comment]
You can also post the question in https://discuss.appium.io
