### ISSUE TITLE
"Failed to download update. Reason: Error: Can not find Squirrel"

### ISSUE THREAD

**Issue by WoLpH** [appium/appium-desktop#1148]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The update dialog, not just for 1.15.1 but for every version I've tested (first one I tried was 1.13.x), gives me this error.

![image](https://user-images.githubusercontent.com/270571/67369224-eb0eb100-f578-11e9-89f5-f3a4ebc45cf6.png)

![squirrel](https://user-images.githubusercontent.com/270571/67369475-5ce6fa80-f579-11e9-8edc-0454acadd5f3.gif)

## Environment

- I am running Appium Desktop version 1.15.0-1
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Thanks

Yes, it is known https://github.com/appium/appium-desktop/issues/1042
(Not fixed yet though)

**Comment by WoLpH** [comment]
Odd, I looked for "can not find squirrel" (seems unique enough) and couldn't find anything :P

**Comment by KazuCocoa** [comment]
Yeah, the issue's description only has the image :P
Let me add a comment...

**Comment by WoLpH** [comment]
Next time they'll stumble on this issue in any case :)
