### ISSUE TITLE
New version selection element attribute is missing instance

### ISSUE THREAD

**Issue by houlandong** [appium/appium-desktop#1149]
The original positioning element can be used class and instance,now I don't know the value of instance

**Comment by KazuCocoa** [comment]
Could you tell us more details?
Your test environments, targets etc

**Comment by houlandong** [comment]
I used version 1.15.1 for mac。Some page lists have the same element attributes, except for instance. I can take advantage of the different location elements of instance（for example：MobileBy.AndroidUIAutomator(newUiSelector().resourceId("com.zhangdan.app:id/iv_ico").instance(9));）. But in this version, there is no instance for element attributes.

**Comment by houlandong** [comment]
![image](https://user-images.githubusercontent.com/33894720/67390505-5b482180-f5cf-11e9-9cf7-eeab69a853db.png)
![Uploading image.png…]()

**Comment by KazuCocoa** [comment]
What `automationName` did you specify?

I guess the previous one was `uiautomator1` and the new one was `uiautomator2`.
The default value has been changed in https://github.com/appium/appium/releases/tag/v1.14.0



`uiautomator2` does not have the instance number.
`index` can be an alternative in most cases, I think.
(The number starts from `0` in index case though.)

**Comment by houlandong** [comment]
I see thank you
