### ISSUE TITLE
V1.0.0-Beta6 - Fail To Build WebDriverAgent 

### ISSUE THREAD

**Issue by NirBY** [appium/appium-desktop#115]
**When running session getting error**:
[Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBKeyboard.m:36:58: error: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
[Xcode]   [FBLogger logFmt:@"Typing with maximum frequency %lu", freq];

**Appium Log**:
[Appium1.0.0-beta6.txt](https://github.com/appium/appium-desktop/files/888398/Appium1.0.0-beta6.txt)

**Comment by NirBY** [comment]
Fixed by modifying  FBKeyboard.m (line 36), added the casting worked..

**From**:
 [FBLogger logFmt:@"Typing with maximum frequency %lu", freq];

**To**:
 [FBLogger logFmt:@"Typing with maximum frequency %lu", (unsigned long)freq];

**File path**:
/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBKeyboard.m

**Comment by imurchie** [comment]
Interesting. Never seen this happening myself, but the fix is in.

The latest beta, with `appium-xcuitest-driver@2.26.2`, should fix this.
