### ISSUE TITLE
WebDriverAgent folder is missing with Appium download

### ISSUE THREAD

**Issue by susantharakan** [appium/appium-desktop#1150]
## Appium CLI & Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue- Occurs with Appium CLI and Appium Desktop with v1.15.1

## The problem
WebDriverAgent source is not automatically downloaded with Appium.
After Appium install via CLI or Appium Desktop, the WebDriverAgent folder structure is missing

## Environment

- I am running Appium Desktop version _1.15.1
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Do you mean no WebDriverAgent folder in appium-xcuitest-driver?
If so, it has been changed as npm module. `appium-webdriveragent` exists in node_modules instead.
e.g.,
https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md
