### ISSUE TITLE
Unable to get hidden elements of virtualized WPF listBox 

### ISSUE THREAD

**Issue by Francis300** [appium/appium-desktop#1157]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I have a virtualized WPF ListBox with 300 rows and only 8 rows are displayed. I wrote a test case to get all the rows of the listBox but it can only get the 8 visible rows. 
Is there an existing solution to get all the rows ? 

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [X ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Is this associated with https://github.com/microsoft/WinAppDriver ?
Then, could you report this to the repository instead of here? @Francis300

**Comment by Francis300** [comment]
Thank you for your response.
