### ISSUE TITLE
How to change appium server to use 1.6.3 its bydefault showing Start Server v1.6.4-beta

### ISSUE THREAD

**Issue by shyam27** [appium/appium-desktop#116]
Hi All,

Earlier I have installed appium 1.6.3  and generated webdriveragent to test ios 10 mobiles. I am able to run tests.
Today i have installed appium-desktop for inspecting elements where it is using appium 1.6.4. when i started my new session i am getting below error

```
[Xcode] 2017-04-03 12:41:53.194 xcodebuild[1915:39792] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/shyam/Library/Developer/Xcode/DerivedData/WebDriverAgent-eajirzirbxveykgwvxgnmdlzufcn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f97f4374370 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-04-03 12:41:53.194 xcodebuild[1915:39792] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
```

Which means again i have to generate WDA for appium-desktop. Is there any possibility to use appium 1.6.3 instead of appium 1.6.4 in appium-desktop.

Or i have to generate a new WDA for Appium 1.6.4

Thanks

**Comment by dpgraham** [comment]
Yes, that's possible
* Run an Appium server
* Open appium desktop (do not start the server)
* In the menu, select 'Appium > New Session Window...'
* Select the 'Custom' tab
* Enter the hostname and port of the appium server you have running

**Comment by shyam27** [comment]
Thanks @dpgraham  its working.

**Comment by dpgraham** [comment]
No problem!

**Comment by arrk-shch** [comment]
<img width="1280" alt="screen shot 2017-04-18 at 9 12 17 am" src="https://cloud.githubusercontent.com/assets/4715168/25113735/27540006-2417-11e7-909a-8b5898b6230d.png">
@dpgraham I have followed the steps but I am getting error as "Error
Could not connect to server; are you sure it's running?"
I have appium server running with Appium v1.6.5-beta
I have attached screenshot.

**Comment by shyam27** [comment]
@arrk-shch what is the remote host value you passed?

**Comment by arrk-shch** [comment]
remote host : 0.0.0.0

**Comment by shyam27** [comment]
@arrk-shch please use remote host value : 127.0.0.1

**Comment by arrk-shch** [comment]
<img width="1280" alt="screen shot 2017-04-18 at 11 43 50 am" src="https://cloud.githubusercontent.com/assets/4715168/25116754/563de8a4-242c-11e7-9a88-15a501e7f91f.png">
Done. But same issue.

**Comment by shyam27** [comment]
@arrk-shch I have started appium from terminal, now appium is running on 0.0.0.0:4723.

In Custom Server configuration i have passed remote host as 127.0.0.1 and port as 4723, its working fine from side.

**Comment by amarnathrayudu** [comment]
Just switch to Custom server to  Automatic server and it works

**Comment by AnubhavGitHub** [comment]
I tried all of the above options.But still its not working out.

**Comment by rahulkulkarniyahoo** [comment]
I opened a terminal window and execute the following commands and it worked for me
adb kill-server
adb start-server

**Comment by Djeffoo** [comment]
Eureka! 

adb kill-server
adb start-server

finally worked !

**Comment by sumitgpt1** [comment]
Thanks its works for me also.....but new error came

**Comment by sumitgpt1** [comment]
Error
An unknown server-side error occurred while processing the command. Original error: 'app' option is required for reinstall

**Comment by jayashree28** [comment]
> I opened a terminal window and execute the following commands and it worked for me
> adb kill-server
> adb start-server

yea it's worked for me also
