### ISSUE TITLE
Appium Desktop > Start Inpector Session > Selected Element > Clear button not working

### ISSUE THREAD

**Issue by automationpss** [appium/appium-desktop#1160]
## Appium Desktop?
click Appium Desktop > Start Inpector Session > Selected Element > Clear button, 
nothing is cleared, see logs below, and screenshot attached 
<img width="360" alt="ClearButtonNot wokring" src="https://user-images.githubusercontent.com/45472980/67807735-a1c7d100-fa52-11e9-8b8c-03ed3a9b0d01.png">

Clear button used to work on Appium 1.13 and below

But on Appium 1.15.0-1 and Appium 1.15.1, it is not working
MacOS, 10.14.6 Mojave

++++++++++++++++++++logs ++++++++++++++
[HTTP] 
[HTTP] --> POST /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/element/23000000-0000-0000-530C-000000000000/clear
[HTTP] {}
[MJSONWP (c5242b81)] Calling AppiumDriver.clear() with args: ["23000000-0000-0000-530C-000000000000","c5242b81-26ed-42e7-8fa2-ab1e2d5c3038"]
[XCUITest] Executing command 'clear'
[WD Proxy] Matched '/element/23000000-0000-0000-530C-000000000000/clear' to command name 'clear'
[WD Proxy] Proxying [POST /element/23000000-0000-0000-530C-000000000000/clear] to [POST http://localhost:8100/session/8226CED0-8085-46F1-9007-B054704F3537/element/23000000-0000-0000-530C-000000000000/clear] with no body
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : null,
[WD Proxy]   "sessionId" : "8226CED0-8085-46F1-9007-B054704F3537"
[WD Proxy] }
[MJSONWP (c5242b81)] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/element/23000000-0000-0000-530C-000000000000/clear 200 168 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/screenshot
[HTTP] {}
[MJSONWP (c5242b81)] Calling AppiumDriver.getScreenshot() with args: ["c5242b81-26ed-42e7-8fa2-ab1e2d5c3038"]
[XCUITest] Executing command 'getScreenshot'
[HTTP] --> GET /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/source
[HTTP] {}
[MJSONWP (c5242b81)] Calling AppiumDriver.getPageSource() with args: ["c5242b81-26ed-42e7-8fa2-ab1e2d5c3038"]
[XCUITest] Executing command 'getPageSource'
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/8226CED0-8085-46F1-9007-B054704F3537/screenshot] with no body
[HTTP] --> GET /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/window/current/size
[HTTP] {}
[MJSONWP (c5242b81)] Calling AppiumDriver.getWindowSize() with args: ["current","c5242b81-26ed-42e7-8fa2-ab1e2d5c3038"]
[XCUITest] Executing command 'getWindowSize'
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAGzW7M2Pv0AAEAASURBVHgB\r\n7L0HnBZFtv5\/7\/3fnOP\/7s13b85x766S85CTeQ2wiqDA5IBgwkSGgRkmzxDEnNY1\r\nu4KIiiKimEgSVERUEMlpUv++Vc\/71jQvM4AMOuqe\/vTUVFefOnXq6VNVp05V9\/tz\r\nkR2GgCFgCBgChoAh8O1DoNFV6WgUHfFnHRek1DdEtXVRbW1UXxs1kFbn0pKnI2hw\r\nZ2PUUO\/\/uRR\/97Bn5e6SiYwu79fl+LmviyAmhyFgCBgChoAhYAicQQQwO7wVgjXD\r\nib3iTRlskTp31tdFjc4qwVbR6Qg44qaMrBmfF3sIJu4udA0YO567z9HmgZkybf4I\r\nTABDwBAwBAwBQ+BLQMAbJdgpxztdEraI97i4gr0tEzNlsG\/c6SwXf4sgYcp4Yi4T\r\nxF+C1KfB0kyZ0wDNshgChoAhYAgYAl97BJKmDOaIjA9vljQntr+BdcJ\/525pxI6p\r\nq\/crSbok2a1FJbMScR6ar81hpszX5lGYIIaAIWAIGAKGwBlEwBsl3hZJmDIyQbTe\r\nRFy2izNfOLzzxsedBeSXoCBhEcqvJXljyBs6jhUccNJ8fQ4zZb4+z8IkMQQMAUPA\r\nEDAEziACtd4WwSJx1gkmCDFtAdZqkayZUB4EOtnwe9SfyTWmhDXjbsMJj415ZQJq\r\nFjEEDAFDwBAwBAyBLwmBRme3YM2EkzUjbJSENUMksaKkPTEudEfc4vEbYrwdwz5f\r\n7nOt0ztpRP91CM0r83V4CiaDIWAIGAKGgCFwhhGoj2obm+yY2uT7SrxlHQwSleh8\r\nNu6u\/08SBGERCsvGO2MwZRoS2SCTe+YMy3v67E5ky...
[WD Proxy] Matched '/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/8226CED0-8085-46F1-9007-B054704F3537/source] with no body
[MJSONWP (c5242b81)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAGzW7M2Pv0AAEAASURBVHgB\r\n7L0HnBZFtv5/7/3fnOP/7s13b85x766S85CTeQ2wiqDA5IBgwkSGgRkmzxDEnNY1\r\nu4KIiiKimEgSVERUEMlpUv++Vc/71jQvM4AMOuqe/vTUVFefOnXq6VNVp05V9/tz\r\nkR2GgCFgCBgChoAh8O1DoNFV6WgUHfFnHRek1DdEtXVRbW1UXxs1kFbn0pKnI2hw\r\nZ2PUUO//uRR/97Bn5e6SiYwu79fl+LmviyAmhyFgCBgChoAhYAicQQQwO7wVgjXD\r\nib3iTRlskTp31tdFjc4qwVbR6Qg44qaMrBmfF3sIJu4udA0YO567z9HmgZkybf4I\r\nTABDwBAwBAwBQ+BLQMAbJdgpxztdEraI97i4gr0tEzNlsG/c6SwXf4sgYcp4Yi4T\r\nxF+C1KfB0kyZ0wDNshgChoAhYAgYAl97BJKmDOaIjA9vljQntr+BdcJ/525pxI6p\r\nq/crSbok2a1FJbMScR6ar81hpszX5lGYIIaAIWAIGAKGwBlEwBsl3hZJmDIyQbTe\r\nRFy2izNfOLzzxsedBeSXoCBhEcqvJXljyBs6jhUccNJ8fQ4zZb4+z8IkMQQMAUPA\r\nEDAEziACtd4WwSJx1gkmCDFtAdZqkayZUB4EOtnwe9SfyTWmhDXjbsMJj415ZQJq\r\nFjEEDAFDwBAwBAyBLwmBRme3YM2EkzUjbJSENUMksaKkPTEudEfc4vEbYrwdwz5f\r\n7nOt0ztpRP91CM0r83V4CiaDIWAIGAKGgCFwhhGoj2obm+yY2uT7SrxlHQwSleh8\r\nNu6u/08SBGERCsvGO2MwZRoS2SCTe+YMy3v67E5kytTXUx2Eb2hsbCQkTooi4VKJ\r\n...
[HTTP] <-- GET /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/screenshot 200 131 ms - 323478
[HTTP] 
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : "\n\n  \n    \n      \n      \n      
[WD Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/8226CED0-8085-46F1-9007-B054704F3537/window/size] with no body
[MJSONWP (c5242b81)] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n      \n      
[HTTP] <-- GET /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/source 200 1484 ms - 12653
[HTTP] 
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : {
[WD Proxy]     "width" : 375,
[WD Proxy]     "height" : 667
[WD Proxy]   },
[WD Proxy]   "sessionId" : "8226CED0-8085-46F1-9007-B054704F3537"
[WD Proxy] }
[MJSONWP (c5242b81)] Responding to client with driver.getWindowSize() result: {"width":375,"height":667}
[HTTP] <-- GET /wd/hub/session/c5242b81-26ed-42e7-8fa2-ab1e2d5c3038/window/current/size 200 1541 ms - 98

**Comment by KazuCocoa** [comment]
What the target OS version and the Xcode version?
https://github.com/appium/appium/issues/13288 is a known issue on Xcode 11 and non iOS 13 env.

**Comment by automationpss** [comment]
my iOS is 12.2, and 13.1. thanks. you may close this one due to duplicate of 13288. Since I thought this issue belong to appium desktop. May I used non-desktop appium to open inspector? If yes, how?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop#connect-to-local-appium-server is the method to connect to the local non-desktop server
