### ISSUE TITLE
appium on android find and click element cost 40s

### ISSUE THREAD

**Issue by tinagongtester** [appium/appium-desktop#1162]
appium on android find and click element cost 40s，如下图：
![企业微信截图_15724378377120](https://user-images.githubusercontent.com/54583220/67857635-45e47180-fb52-11e9-9ce5-2a732c3e9f19.png)
![image](https://user-images.githubusercontent.com/54583220/67857671-5c8ac880-fb52-11e9-8390-f1d8fed2d641.png)
how can i  improve the speed，it so slow
[logcat.txt](https://github.com/appium/appium-desktop/files/3788822/logcat.txt)

**Comment by tinagongtester** [comment]
i use android8.1  meizu plus

**Comment by tinagongtester** [comment]
i have add ignoreUnimportantViews when i use uiautomator2，but it not works。
and i found if i change uiautomator2  to uiautomator1，it will run very fast，but getPageSource will 
have not response sometimes。
![image](https://user-images.githubusercontent.com/54583220/67932071-36226700-fbfe-11e9-8bdf-59e04a1d77a7.png)

**Comment by KazuCocoa** [comment]
Did you try `waitForIdleTimeout` via settings api or "Update settings" section in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md ?

btw, 'ignoreUnimportnatViews' is settings API. You should call http://appium.io/docs/en/commands/session/settings/update-settings/ or "Update settings" section in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by tinagongtester** [comment]
that ‘s great’，The problem is solved，thank you very much！
