### ISSUE TITLE
Outlook Add-Ins are not showing in inspect element

### ISSUE THREAD

**Issue by erangawarna** [appium/appium-desktop#1163]
## Appium Desktop
1.13.0

## The problem
Outlook Add-Ins cannot find when open in Appium desktop

## Environment

- I am running Appium Desktop version _<1.13.0>_.
- I am on:
    - [ ] Windows

## Screenshots

**Normal Outlook App**
![image](https://user-images.githubusercontent.com/13641981/67987058-5e0eda80-fc91-11e9-9a60-41ad81e338c9.png)

**Outlook App open using Appium Desktop**
![image](https://user-images.githubusercontent.com/13641981/67987070-649d5200-fc91-11e9-8bb0-d781e39d48aa.png)

**Comment by KazuCocoa** [comment]
Not sure the app's implementation, but I predict the app check if any packages are installed in the test device. It takes a few seconds. Possibly, it is a timing issue when the items appear and when the appium desktop gets the source and screenshot.

Meanwhile, basically the behaviour depends on the app under test's implementation.

**Comment by mykola-mokhnach** [comment]
This menu could be a part of another window. In order to enable multi-window support one needs appium 1,15+ and `enableMultiWindows` setting set to `true`

**Comment by KazuCocoa** [comment]
Please try the above caps
