### ISSUE TITLE
Cannot Start Appium Inspector: Appium crashes and quits after it launches  the iOS Simulator

### ISSUE THREAD

**Issue by bhadmus** [appium/appium-desktop#1165]
## The problem

I am trying to launch the the inspector session on Appium for the IOS simulator, but once the simulator is launched, the appium desktop client exits like I didn't even launch it leaving the simulator only

## Environment

* Appium versio: 1.15.1, 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.15
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 12.4, 13.1
* Real device or emulator/simulator: iOS Simulator
* Appium CLI or Appium.app|exe: Appium Desktop app

## Details

I was able to get the logs available for both versions before they crashed and exited.

## Link to Appium logs

Appium 1.15.1 => https://gist.github.com/bhadmus/3d9e3177c8fca9ac72bc2fb8db464a6d.js

Appium 1.14.0 => https://gist.github.com/bhadmus/7a4741f008cacc23e7194f6caa108268.js

## Code To Reproduce Issue 
{
  "platformName": "iOS",
  "deviceName": "iPhone 8",
  "app": "/Users/bhadmus/Library/Developer/Xcode/DerivedData/MAX_Go-geeqxenvidzhobdonkeonrdaopul/Build/Products/StagingDebug-iphonesimulator/MAX.NG Staging Debug.app",
  "plaformVersion": "13.1",
  "automationName": "XCUITest",
  "forceMjsonwp": true
}
 Desired Capabilities Documentation

**Comment by bhadmus** [comment]
I have corrected the Typographical error and the same thing still happens. So what other options do I have? I mean what can I do? Please advise

**Comment by KazuCocoa** [comment]
How to provide the caps via Appium Desktop?
If the cause is `plaformVersion` in AD, need to know how you provide the value to AD like below:

![image](https://user-images.githubusercontent.com/5511591/68033192-8d116480-fd02-11e9-95ad-a9151dde2e11.png)

**Comment by KazuCocoa** [comment]
ah, okay, > I have corrected the Typographical error

**Comment by tonebot13** [comment]
seeing the same issue @bhadmus is experiencing. I've tried several different iOS simulators - the inspector session starts to launch as does the simulator - then AD crashes.

**Comment by alishaker** [comment]
I'm facing the same problem here, any help guys
<img width="599" alt="Screen Shot 2020-03-09 at 9 31 03 AM" src="https://user-images.githubusercontent.com/24529156/76191740-b8441d00-61e8-11ea-98cc-30f6d2f51c54.png">

**Comment by bhadmus** [comment]
@alishaker and @tonebot13 I was able to resolve the crash myself with this. Check the link below, I hope it helps.

https://www.linkedin.com/pulse/appium-ios-simulator-challenges-ademola-bhadmus/
