### ISSUE TITLE
appium启动微信

### ISSUE THREAD

**Issue by zjing306** [appium/appium-desktop#1166]
通过appium启动微信，进入公众号会检测到微信自带的“搜一搜”H5，手动操作是检测不到搜一搜的，
![image](https://user-images.githubusercontent.com/45554421/68070993-6f023d80-fdb0-11e9-9da5-ac08302ac20f.png)

**Comment by KazuCocoa** [comment]
Could you add more info like the issue template, you can see via _new issue_ on GitHub, in English?
(Translation by a translator is enough)

Please create an issue if you addressed general webview issue in Appium.
https://github.com/appium/appium
