### ISSUE TITLE
start session java.long.NullPointerException   

### ISSUE THREAD

**Issue by weigtman** [appium/appium-desktop#1167]
APPIUM_LOG
BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   connectHardwareKeyboard
[BaseDriver] Session created with session id: 650e84bb-f89e-44f8-b828-ee7b4175841e
[UiAutomator2] Starting 'com.android.settings' directly on the device
[ADB] Using 'adb.exe' from 'E:\Program File\sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] Connected devices: [{"udid":"JBVV1V0M10","state":"device"}]
[AndroidDriver] Using device: JBVV1V0M10
[ADB] Using 'adb.exe' from 'E:\Program File\sdk\platform-tools\adb.exe'
[ADB] Setting device id to JBVV1V0M10
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 25
[ADB] Device API level: 25
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 wait-for-device'
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell dumpsys package io.appium.settings'
[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Could not find 'apkanalyzer.bat' in ["E:\\Program File\\sdk\\platform-tools\\apkanalyzer.bat","E:\\Program File\\sdk\\emulator\\apkanalyzer.bat","E:\\Program File\\sdk\\tools\\apkanalyzer.bat","E:\\Program File\\sdk\\tools\\bin\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\28.0.3\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\28.0.2\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\27.0.3\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\26.0.2\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\26.0.1\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\25.0.0\\apkanalyzer.bat"]. Do you have Android Build Tools installed at 'E:\Program File\sdk'?
[ADB] Using 'aapt.exe' from 'E:\Program File\sdk\build-tools\28.0.3\aapt.exe'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.2' >= '2.14.2')
[ADB] There is no need to install/upgrade 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell 'pgrep --help; echo $?''
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell pgrep \^appium\\.settings\$'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[UiAutomator2] Server package at 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.3.0.apk' is not writeable. Will copy it into the temporary location at 'C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[UiAutomator2] Server package at 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Will copy it into the temporary location at 'C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell dumpsys package io.appium.uiautomator2.server'
[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Could not find 'apkanalyzer.bat' in ["E:\\Program File\\sdk\\platform-tools\\apkanalyzer.bat","E:\\Program File\\sdk\\emulator\\apkanalyzer.bat","E:\\Program File\\sdk\\tools\\apkanalyzer.bat","E:\\Program File\\sdk\\tools\\bin\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\28.0.3\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\28.0.2\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\27.0.3\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\26.0.2\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\26.0.1\\apkanalyzer.bat","E:\\Program File\\sdk\\build-tools\\25.0.0\\apkanalyzer.bat"]. Do you have Android Build Tools installed at 'E:\Program File\sdk'?
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.3.0' >= '4.3.0')
[UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[ADB] Checking app cert for C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-v4.3.0.apk
[ADB] Using 'apksigner.bat' from 'E:\Program File\sdk\build-tools\28.0.3\apksigner.bat'
[ADB] Starting 'E:\Program File\sdk\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\admin\\AppData\\Local\\Temp\\2019103-12464-15v3tud.wwdyg\\appium-uiautomator2-server-v4.3.0.apk"]'
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] 'C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-v4.3.0.apk' is already signed.
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell dumpsys package io.appium.uiautomator2.server.test'
[ADB] 'io.appium.uiautomator2.server.test' is not installed
[ADB] Checking app cert for C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Starting 'E:\Program File\sdk\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\admin\\AppData\\Local\\Temp\\2019103-12464-15v3tud.wwdyg\\appium-uiautomator2-server-debug-androidTest.apk"]'
[ADB] apksigner stdout: Signer #1 certificate DN: CN=Android Debug, O=Android, C=US
[ADB] Signer #1 certificate SHA-256 digest: 3e4f2ab66d641bbbd363421151755f8b12b66ea37a5db43c52116596b7392a8e
[ADB] Signer #1 certificate SHA-1 digest: e24fc8971c0aad07d1df6cc62af7fb0d48b45b60
[ADB] Signer #1 certificate MD5 digest: 5623d53469c7f7147b52ace9d09901eb
[ADB] 
[ADB] 'C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-debug-androidTest.apk' is signed with non-default certificate
[ADB] Using 'zipalign.exe' from 'E:\Program File\sdk\build-tools\28.0.3\zipalign.exe'
[ADB] C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-debug-androidTest.apk' is already zip-aligned. Doing nothing
[ADB] Signing 'C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-debug-androidTest.apk' with default cert
[ADB] Starting 'E:\Program File\sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Users\\admin\\AppData\\Local\\Temp\\2019103-12464-15v3tud.wwdyg\\appium-uiautomator2-server-debug-androidTest.apk"]'
[UiAutomator2] Server packages are going to be (re)installed
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[ADB] The count of applications in the cache: 2
[ADB] The application at 'C:\Users\admin\AppData\Local\Temp\2019103-12464-15v3tud.wwdyg\appium-uiautomator2-server-v4.3.0.apk' is already cached to '/data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk'
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk'
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 shell am force-stop com.android.settings'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'E:\Program File\sdk\platform-tools\adb.exe -P 5037 -s JBVV1V0M10 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command ''E:\\Program File\\sdk\\platform-tools\\adb.exe' -P 5037 -s JBVV1V0M10 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1572758092373 (13:14:52 GMT+0800 (中国标准时间))
[MJSONWP] Encountered internal error running command: Error executing adbExec. Original error: 'Command ''E:\\Program File\\sdk\\platform-tools\\adb.exe' -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' exited with code 1'; Stderr: 'Error: java.lang.NullPointerException: Attempt to read from null array'; Code: '1'
[MJSONWP] Error: Command ''E:\\Program File\\sdk\\platform-tools\\adb.exe' -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' exited with code 1
[MJSONWP]     at ChildProcess.proc.on.code (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[MJSONWP]     at ChildProcess.emit (events.js:182:13)
[MJSONWP]     at maybeClose (internal/child_process.js:961:16)
[MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 15427 ms - 474
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP] 

android_logcat
--------- beginning of main
11-03 13:14:47.927 I/vpu_api (27939): dlopen vpu lib /system/lib/librk_vpuapi.so success
11-03 13:14:47.933 D/AndroidRuntime(27939): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-03 13:14:47.937 D/AndroidRuntime(27939): CheckJNI is OFF
11-03 13:14:47.975 D/ICU     (27939): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-03 13:14:48.013 E/memtrack(27939): Couldn't load memtrack module (No such file or directory)
11-03 13:14:48.013 E/android.os.Debug(27939): failed to load memtrack module: -2
11-03 13:14:48.015 I/Radio-JNI(27939): register_android_hardware_Radio DONE
11-03 13:14:48.029 D/AndroidRuntime(27939): Calling main entry com.android.commands.pm.Pm
11-03 13:14:48.030 W/Pm      (27939):  args[0] install
11-03 13:14:48.061 E/Pm      (27939): Error
11-03 13:14:48.061 E/Pm      (27939): java.lang.NullPointerException: Attempt to read from null array
11-03 13:14:48.061 E/Pm      (27939):   at com.android.commands.pm.Pm.runInstall(Pm.java:414)
11-03 13:14:48.061 E/Pm      (27939):   at com.android.commands.pm.Pm.run(Pm.java:168)
11-03 13:14:48.061 E/Pm      (27939):   at com.android.commands.pm.Pm.main(Pm.java:124)
11-03 13:14:48.061 E/Pm      (27939):   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-03 13:14:48.061 E/Pm      (27939):   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
11-03 13:14:48.062 I/art     (27939): System.exit called, status: 1
11-03 13:14:48.062 I/AndroidRuntime(27939): VM exiting with result code 1.
11-03 13:14:48.722 I/vpu_api (27955): dlopen vpu lib /system/lib/librk_vpuapi.so success
11-03 13:14:48.728 D/AndroidRuntime(27955): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
11-03 13:14:48.732 D/AndroidRuntime(27955): CheckJNI is OFF
11-03 13:14:48.769 D/ICU     (27955): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-03 13:14:48.800 E/memtrack(27955): Couldn't load memtrack module (No such file or directory)
11-03 13:14:48.801 E/android.os.Debug(27955): failed to load memtrack module: -2
11-03 13:14:48.802 I/Radio-JNI(27955): register_android_hardware_Radio DONE
11-03 13:14:48.817 D/AndroidRuntime(27955): Calling main entry com.android.commands.am.Am
--------- beginning of system
11-03 13:14:48.819 I/ActivityManager(  687): Force stopping com.android.settings appid=1000 user=0: from pid 27955
11-03 13:14:48.819 D/AndroidRuntime(27955): Shutting down VM

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
```
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command ''E:\Program File\sdk\platform-tools\adb.exe' -P 5037 -s JBVV1V0M10 forward --remove tcp:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1572758092373 (13:14:52 GMT+0800 (中国标准时间))
[MJSONWP] Encountered internal error running command: Error executing adbExec. Original error: 'Command ''E:\Program File\sdk\platform-tools\adb.exe' -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' exited with code 1'; Stderr: 'Error: java.lang.NullPointerException: Attempt to read from null array'; Code: '1'
[MJSONWP] Error: Command ''E:\Program File\sdk\platform-tools\adb.exe' -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' exited with code 1
[MJSONWP] at ChildProcess.proc.on.code (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[MJSONWP] at ChildProcess.emit (events.js:182:13)
[MJSONWP] at maybeClose (internal/child_process.js:961:16)
[MJSONWP] at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 15427 ms - 474
[HTTP]
```


Perhaps, `adb` command failed to install your app. How about removing it and run appium again?
I guess `adb push` the test apk to your device breaks the apk..


You can try out `remoteAppsCacheLimit: 0` capability to remove the apk from your device local to remove the device local apk, too.

**Comment by weigtman** [comment]
> 
> 
> ```
> [UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command ''E:\Program File\sdk\platform-tools\adb.exe' -P 5037 -s JBVV1V0M10 forward --remove tcp:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
> [BaseDriver] Event 'newSessionStarted' logged at 1572758092373 (13:14:52 GMT+0800 (中国标准时间))
> [MJSONWP] Encountered internal error running command: Error executing adbExec. Original error: 'Command ''E:\Program File\sdk\platform-tools\adb.exe' -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' exited with code 1'; Stderr: 'Error: java.lang.NullPointerException: Attempt to read from null array'; Code: '1'
> [MJSONWP] Error: Command ''E:\Program File\sdk\platform-tools\adb.exe' -P 5037 -s JBVV1V0M10 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' exited with code 1
> [MJSONWP] at ChildProcess.proc.on.code (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
> [MJSONWP] at ChildProcess.emit (events.js:182:13)
> [MJSONWP] at maybeClose (internal/child_process.js:961:16)
> [MJSONWP] at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
> [HTTP] <-- POST /wd/hub/session 500 15427 ms - 474
> [HTTP]
> ```
> 
> Perhaps, `adb` command failed to install your app. How about removing it and run appium again?
> I guess `adb push` the test apk to your device breaks the apk..
> 
> You can try out `remoteAppsCacheLimit: 0` capability to remove the apk from your device local to remove the device local apk, too.

ths u very much. but  why is this parameter

**Comment by KazuCocoa** [comment]
Appium caches apks on the target device to reduce communication time.
it means if the cached apk is broken, it remains. The capability keep the number zero so that you can keep the cache clean. (And It helps to detect the failure is broken apk on the device)

**Comment by weigtman** [comment]
> 
> 
> Appium caches apks on the target device to reduce communication time.
> it means if the cached apk is broken, it remains. The capability keep the number zero so that you can keep the cache clean. (And It helps to detect the failure is broken apk on the device)

okey  i see ths
