### ISSUE TITLE
appium cannot switch to webview

### ISSUE THREAD

**Issue by tinagongtester** [appium/appium-desktop#1172]
i have open x5 core to debug webview,but appium cannot start driver.the log as bellows:
because the app use x5 driver is 
![image](https://user-images.githubusercontent.com/54583220/68562375-56ff7d80-0484-11ea-9448-ed5d14ccacf4.png)
so i need to download older chromedriver,the version is 2.29,but when i switch to webview in script,it not successfuly,the log as bellows:

![image](https://user-images.githubusercontent.com/54583220/68562350-40592680-0484-11ea-805d-00c76627a298.png)
[appium_webview.txt](https://github.com/appium/appium-desktop/files/3829782/appium_webview.txt)

the capabilities is:
![image](https://user-images.githubusercontent.com/54583220/68562453-ad6cbc00-0484-11ea-953d-0e0e45622e51.png)

switch to webview as bellows:
![image](https://user-images.githubusercontent.com/54583220/68562483-cbd2b780-0484-11ea-97b6-d5edb4ec4236.png)

**Comment by KazuCocoa** [comment]
Hm...What version of appium did you try?

You can set `chromedriverExecutable` and the proper chromeversion to use the driver. Does this help?
https://appium.io/docs/en/writing-running-appium/caps/

**Comment by KazuCocoa** [comment]
AD is designed to support only native app, while the latest one has a few commands to handle contexts
