### ISSUE TITLE
Original error: Could not sign with default certificate. An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by gpankajgupta929** [appium/appium-desktop#1175]
##Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

An unknown server-side error occurred while processing the command. 

Original error: Could not sign with default certificate. 

Original error Command ''C:\\Program Files\\Java\\jdk-13\\bin\\java.exe' -jar '

C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar' '

C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk'
 --override' exited with code 1.

Original error: The application at 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\
appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. 
Please grant write permissions to this file or to its parent folder 'C:\Program Files\Appium\resources\app\node_modules\
appium\node_modules\appium-uiautomator2-server\apks' for the Appium process, so it could sign the application.

## Environment

- I am running Appium Desktop version _<1.12.1 & 1.13.0 & 1.14.0 & 1.15.1>_.
- I am on (pick one):
    - [x] Windows

**Comment by gpankajgupta929** [comment]
Struggling to this since last 15 days.

**Comment by KazuCocoa** [comment]
Duplication of https://github.com/appium/appium-desktop/issues/1115

It is Windows permission stuff for the directories when we install AD with administrator permission.
So far, it can fix with launching the AD as administrator.

**Comment by gpankajgupta929** [comment]
> Duplication of #1115
> 
> It is Windows permission stuff for the directories when we install AD with administrator permission.
> So far, it can fix with launching the AD as administrator.

I've done all those things before but can't came up with any Solution so far....  :(

**Comment by KazuCocoa** [comment]
hm, if the path was writable, another case is the app has been removed by someone such as security apps.

Did the app exist in the path?
I saw a comment some? virus managers deleted an apk from AD package.

**Comment by gpankajgupta929** [comment]
I understand that for some Security reasons app might get removed by Virus managers but I'm sure that in my machine I removed all of those restrictions or managers. 

And about which app you're talking about that Exist in path?

If you're saying about "androidTest.apk" then it's there on path & whenever I click on that File it directly Navigates to Chrome Browser & directly starts downloading that same kind of apk.

**Comment by KazuCocoa** [comment]
Yeah, as you addressed, I meant `androidTest.apk`.

Hm...
Then, as far as I knew, the cause was the permission stuff. I also got the same issue before, but that case was this administrator stuff.

But your env was not writable even though you ran the AD as administrator permission.
Sorry I have no good idea to resolve since I'm not familiar with Windows permissions.

Asking it in https://discuss.appium.io/ could help by Windows user.

**Comment by gpankajgupta929** [comment]
Thanks for your contribution man!

And I'm New to Appium so here I'm also trying to dig as much as I can....

**Comment by KazuCocoa** [comment]
@gpankajgupta929 
As a workaround, you also can install appium cli via `npm` command.
Appium Desktop has an ability to connect to the local another appium server as https://github.com/appium/appium-desktop#connect-to-local-appium-server . Then, you can avoid this permission issue.

**Comment by MarcSteven** [comment]
@KazuCocoa  The issue was still existing, today I met the issue!

**Comment by KazuCocoa** [comment]
This root cause is write permission. In some environment, AppiumDesktop does not get write permission, so https://github.com/appium/appium-desktop/issues/1175#issuecomment-554398946 could be a workaround.

**Comment by siya-mayaya** [comment]
@KazuCocoa I have a similar issue with appium desktop v1.18.2 
My Java_Home path is correct and appium picks that up but still throws an error. Please help
![1](https://user-images.githubusercontent.com/20128533/96266676-33638200-0fc7-11eb-88f3-2bafb024c009.PNG)
![2](https://user-images.githubusercontent.com/20128533/96266681-352d4580-0fc7-11eb-9d01-8722178b55ee.PNG)

**Comment by Arya-creator696** [comment]
@KazuCocoa I have the same issue mentioned above.
Below mentioned is the exact error:-
**" An unknown server-side error occured while processing the command. Original error:Could not sign with default certificate. Original error: Command 'C:\Program Files\Java\jdk-15.0.1\bin\bin\java.exe not found. Is it installed?**

How can i resolve it?

**Comment by jlipps** [comment]
Do you see `bin\bin` in the path? Obviously that's not correct. JAVA_HOME should not include the `bin` dir.

**Comment by thembanator** [comment]
![image](https://user-images.githubusercontent.com/16664085/161431382-58ff310c-c5c5-4e84-8871-b6cdb2ac9018.png)

Java Home set as picture above but still getting an error: " An unknown server-side error occured while processing the command. Original error: Could not sign with default certificate. Original error: Command 'C:\Program Files\Java\jdk-18\bin\bin\java.exe not found. Is it installed?". Obviously the path: C:\Program Files\Java\jdk-18\bin\bin\ does not exist

**Comment by jlipps** [comment]
@thembanator see the previous comment. you have JAVA_HOME defined incorrectly. JAVA_HOME should be the path to the java home dir, not the java bin dir.
