### ISSUE TITLE
The dmg downloaded slowly 

### ISSUE THREAD

**Issue by MarcSteven** [appium/appium-desktop#1180]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The version of mac downloaded slowly 

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by MarcSteven** [comment]
<img width="412" alt="Screen Shot 2019-11-16 at 22 16 48" src="https://user-images.githubusercontent.com/13824297/68994786-d72d4500-08c1-11ea-81ce-dee8aed8ae1a.png">
Please  see the pic

**Comment by KazuCocoa** [comment]
It looks GitHub issue since we simply upload packages to GitHub release.
Could you ask the slowness to GitHub team?

I assume CDN stuff or network route....
