### ISSUE TITLE
Simulator Failure: xcodebuild exited with code '65' and signal 'null'

### ISSUE THREAD

**Issue by dcdement** [appium/appium-desktop#1187]
## The problem

iOS 11, 12, and 13 Simulator does not install the WebDriverAgent. Simulators open, install our app to tes, then loops while trying to install the WebDriverAgent and crashes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe):node 10.14.1
* Npm or Yarn package manager: 6.13.0
* Mobile platform/version under test: iOS 13.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:.app|exe

## Details

Works in real 13.2, but failing in simulator

## Link to Appium logs

<script src="https://gist.github.com/dcdement/9e602ad9d755ddc38f79fc8d5440bf58.js"></script>

## Code To Reproduce Issue [ Good To Have ]

appiumDriver = new IOSDriver<IWebElement>(new Uri(Helpers.MobileHelper.GetValueFromKey(testMethod.DataFields, "IOSUri")),
                            capabilities, TimeSpan.FromSeconds(500));

**Comment by dcdement** [comment]
Using Appium v1.16.0-beta.1 via command line and got an interesting error: Scheme WebDriverAgentRunner is not currently configured for the build-for-testing action
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/3881512/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
This seems very odd. Which command did you use to install appium via command line?

Try to remove the current installation completely and make sure there are no leftovers. Then install it via `npm i -g appium@beta`

**Comment by dcdement** [comment]
Not sure what command I used, it was a while ago, but I tried to remove the current installation and got

Mac-mini:~ testmc3$ npm uninstall appium
npm WARN saveError ENOENT: no such file or directory, open '/Users/testmc3/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/testmc3/package.json'
npm WARN testmc3 No description
npm WARN testmc3 No repository field.
npm WARN testmc3 No README data
npm WARN testmc3 No license field.

so after this I tried to run appium from command line and it still opens

**Comment by mykola-mokhnach** [comment]
I would try to remove it completely first and then perform full reinstall. Check if `npm uninstall -g appium` works

**Comment by KazuCocoa** [comment]
Another way is `derivedDataPath`. https://github.com/appium/appium-xcuitest-driver
It allows appium to build WDA in the path instead of `/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/Build/...`  It could avoid permission issue.
