### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

### ISSUE THREAD

**Issue by chaitanyadeshmukh** [appium/appium-desktop#119]
Hello Team,

I am able to run **appium (v1.6.3)through Command Line**. I have already setup my ANDROID_HOME path.
We r able to run app on my simulator via appium CLI. Due to Visual Inspector we moved to AppiumDesktop version.

I have installed **appium-desktop-1.0.0-beta.6.dmg** app on mac. I have **Appium v1.6.4-beta server** running at my end. 
I have started server, then select on "Select New Session" & added below desired capablities to run my app 
{
  "deviceName": "Android Emulator",
  "app": my_apk_path,
  "appiumVersion": "1.6.3",
  "platformName": "Android"
}

while click on "Start Session" it gives me above error.

Please help me urgent on fixing of this issue.

**Comment by dpgraham** [comment]
The readme (https://github.com/appium/appium-desktop) explains under 'The New Session Window' how to use a separate server so you can use the inspector with the Appium v1.6.3 that you have running on your command line.

**Comment by jlipps** [comment]
What shell do you normally use for the command line? Appium Desktop will load your shell environment through common shell login scripts like ~/.bashrc and ~/.bash_profile. If you are using a non-standard shell you should probably set your PATH and ANDROID_HOME variables in one of those standard shell locations to successfully use Appium Desktop.

**Comment by chaitanyadeshmukh** [comment]
Thanks It works after updating  ~/.profile  file.

**Comment by jlipps** [comment]
Added a note about this to the readme in https://github.com/appium/appium-desktop/pull/122

**Comment by test-jj** [comment]
Hello, I had set the PATH and ANDROID_HOME variable already, but can't solve this problem . Can you help me ,please

**Comment by trivenibhalerao** [comment]
in MAC, updating profile file with below command working for me
$ nano ~/.profile

**Comment by it-shivani** [comment]
Hi,

I am still facing the issue. I have already set ANDROID_HOME and My appium-doctor shows all green not sure why it cannot pick adb from Android home.

Please help.

**Comment by dpgraham** [comment]
I'm going to revisit this probably some time this week. I'd like to be able to set ANDROID_HOME inside of Appium Desktop instead of having to do it on terminal.

**Comment by siddhartha-2107** [comment]
An unknown server-side error occurred while processing the command. Original error: Could not find 'adb' in ["/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/platform-tools/adb","/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/emulator/adb","/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/tools/adb","/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/tools/bin/adb"]. Do you have Android Build Tools installed at '/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home'? in mac

**Comment by AvrahamAtia** [comment]
@siddhartha-2107 It happens the same for me, but only in the declarative pipeline?

**Comment by farabi** [comment]
I have fixed this by setting manuallly ANDROID_HOME and JAVA_HOME in Appium->Configurations.
