### ISSUE TITLE
How to embed Appium-desktop in a docker image

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [appium/appium-desktop#1191]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I have an existing Docker image with appium and all the needed tools.
Don't know how to add Appium-desktop.
If I embed the provided snap file, a lot of duplication occurs, and it would generate a very big Possible base Docker image to use: https://github.com/budtmo/docker-android

## Environment

- I am running Appium Desktop version _<latest>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [x] Linux

**Comment by KazuCocoa** [comment]
I haven't run appium desktop on a docker environment, but I think you can copy https://github.com/appium/appium-desktop/releases for Linux (AppImage) on the docker env.

**Comment by DavidPerezIngeniero** [comment]
If I install AppImage runner, it will probably run with some tweaks, but I'll have a lot of redundancy (twice Appium, Node and many other dependencies.

**Comment by KazuCocoa** [comment]
Do you mean you'd like to add only _inspector_ module in appium desktop?

AD has appium module as a part of appium-desktop.
So, I wondered _twice Appium, Node and many..._ meant appium servers included in appium-desktop.

**Comment by DavidPerezIngeniero** [comment]
Thanks KazuCocoa
The docker image https://github.com/budtmo/docker-android has Appium, and Node.
But how to add the inspector in this image?

**Comment by KazuCocoa** [comment]
Copying the blow Linux binary into the docker may help. Probably x-window stuff will be needed.
https://github.com/appium/appium-inspector
