### ISSUE TITLE
Server error: Could not connect to server; are you sure it's running?

### ISSUE THREAD

**Issue by Shivani592** [appium/appium-desktop#1192]
Unable to launch..

Getting this error or Sometimes give

Could not connect to server; are you sure it's running?

![image](https://user-images.githubusercontent.com/57714857/69796869-c8fdf380-11f4-11ea-9072-b34017235245.png)

**Comment by KazuCocoa** [comment]
it looks the path to Java SDK was not expected.
Could you make sure the path? You can customise it via "Edit Configuration" on the top of appium desktop, too.

**Comment by Shivani592** [comment]
![image](https://user-images.githubusercontent.com/57714857/69866283-aa1d6100-12c9-11ea-94af-46c131381dee.png)

**Comment by Shivani592** [comment]
Java Path & SDK path both are correct, still unable to launch (start session) in appium.

Please resolve my query.

**Comment by KazuCocoa** [comment]
What about updating the ANDROID_HOME to `C:\.....\Android\Sdk` instead of `C:\....\Android\Sdk\tools`?

**Comment by KazuCocoa** [comment]
Close for now since the android home path was wrong.

**Comment by Shivani592** [comment]
Andriod Path is correct. 

I have installed appium lower version i.e. 1.13.1 

Now, it is working.

**Comment by KazuCocoa** [comment]
Thanks. I don't remember which part we changed though.

For Java env, I set `C:\Program Files\Android\Android Studio\jre` in my PC to follow Android environment. It works well with 1.15.

**Comment by Shivani592** [comment]
I set :     C:\Program Files\Java\jdk-12.0.1 for JAVA

**Comment by Souj07** [comment]
Hello , for Appium Inspector verison 1.22 , I am not able to proceed further due to this error. 
![image](https://user-images.githubusercontent.com/92786508/137895743-f5ed87d6-086a-4e8d-ab88-a93fa17d9a3d.png)
Please help tp resolve it

**Comment by KazuCocoa** [comment]
Where was your appium server running?
Your attached image had a typo in the path. Did you input the path as `wd` correctly?
