### ISSUE TITLE
Error An unknown server-side error occurred while processing the command. Original error: Xcode version '1.2.1'. Support for Xcode 1.2.1 is not supported. Please upgrade to version 7.3 or higher

### ISSUE THREAD

**Issue by luojinhang** [appium/appium-desktop#1194]
Error
An unknown server-side error occurred while processing the command. Original error: Xcode version '1.2.1'. Support for Xcode 1.2.1 is not supported. Please upgrade to version 7.3 or higher

**Comment by luojinhang** [comment]
Xcode 11.2.1

**Comment by KazuCocoa** [comment]
Which version of appium/appium desktop did you use?
Please update to the latest one for Xcode 11

**Comment by KazuCocoa** [comment]
Please update to the latest one :)
