### ISSUE TITLE
Appium GUI issue on MAC Sierra - "$npm start"not launching the appium 1.6.0 GUI

### ISSUE THREAD

**Issue by shabinmohan** [appium/appium-desktop#12]
I am getting below error when try to launch the Appium GUI

Please find the below logs

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! appium-desktop@0.1.0 start: `cross-env NODE_ENV=production electron ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-desktop@0.1.0 start script 'cross-env NODE_ENV=production electron ./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production electron ./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sunil/appium-desktop/npm-debug.log
Sankar:appium-desktop sunil$

**Comment by shabinmohan** [comment]
This is the issue i got while building :

ERROR in ./main.js from UglifyJs
SyntaxError: Unexpected token punc «}», expected punc «:» [./~/electron-debug/index.js:23,32]

**Comment by jlipps** [comment]
Did you follow all the developer instructions in the README? This project is not yet ready for users.

**Comment by dpgraham** [comment]
Resolved by dc6be8460fa36b298858532b00dc91ce7c10eded
