### ISSUE TITLE
Does Appium Desktop removes the dependency of MAC for iOS Scripting

### ISSUE THREAD

**Issue by nidhitri** [appium/appium-desktop#120]
Hi just wanted to get the confirmation , that can we inspect elements on iPhone application using windows machine.

**Comment by dpgraham** [comment]
No you still need a Mac to inspect/test applications locally.

You can test iPhone applications if you use a service like SauceLabs (https://saucelabs.com/) or TestObject (https://testobject.com/) which provides cloud based Appium testing for iPhone and Android applications (disclaimer: I work for SauceLabs)
