### ISSUE TITLE
无法写入文件 uninstall appium .exe

### ISSUE THREAD

**Issue by drduan** [appium/appium-desktop#1209]
无法写入文件 uninstall appium .exe
![图片](https://user-images.githubusercontent.com/7875572/71805317-e5693780-30a0-11ea-9037-8dcf5c618cec.png)

**Comment by KazuCocoa** [comment]
Did you remove Appium related stuff before the uninstallation?

**Comment by KazuCocoa** [comment]
No response for a while.
Probably it needs to reproduce first to debug more though...
