### ISSUE TITLE
Not Able to automate due to appium timeout

### ISSUE THREAD

**Issue by Nicollas-stack** [appium/appium-desktop#1211]
Hi Everyone
Im using the 1.15.1 version of the appium
with the IOS version 10.15.1
and the Xcode with 11.3

and everytime i try to type anything on the automation i have this error: 
<img width="640" alt="Captura de Tela 2019-12-17 às 5 53 33 PM" src="https://user-images.githubusercontent.com/59582212/71849604-32550a00-30b1-11ea-9ebf-64e1b63fb484.png">

Can someone help me please?

Thanks!!

**Comment by KazuCocoa** [comment]
Could you attach the full log as gist?

**Comment by KazuCocoa** [comment]
no full log
