### ISSUE TITLE
Appium” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by KS261187** [appium/appium-desktop#1217]
Unable to open Appium 1.16 in Mac. It is saying that the "Appium” can’t be opened because Apple cannot check it for malicious software."

This software needs to be updated. Contact the developer for more information.

## The problem

I am unable to open the 1.16 Appium desktop in my Mac. It is complaining that the "This software needs to be updated. Contact the developer for more information.".

## Environment

- I am running Appium Desktop version _<insert version here>_.1.16
- I am on (pick one): Mac
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by sme81** [comment]
Ctrl and click, then the open option

**Comment by spartha1** [comment]
<img width="488" alt="Screen Shot 2020-01-17 at 3 08 48 PM" src="https://user-images.githubusercontent.com/49630854/72601384-4fa09880-393b-11ea-92ed-558aceca49c4.png">
HI
I am trying to install Appium in Mac OS Catalina and I am getting this error

**Comment by sme81** [comment]
> <img alt="Screen Shot 2020-01-17 at 3 08 48 PM" width="488" src="https://user-images.githubusercontent.com/49630854/72601384-4fa09880-393b-11ea-92ed-558aceca49c4.png">
> 
> HI I am trying to install Appium in Mac OS Catalina and I am getting this error

see above for the fix

**Comment by spartha1** [comment]
Hi 
Please follow the below steps
1. Right-click
2. Select Open
3. Now move the appium to the Application folder

**Comment by LoveleshQA** [comment]
You can download an older version ...its working fine

**Comment by gillett-hernandez** [comment]
this might have only worked for me for my java installation (when i tried to do `brew cask install java`), but after it tries once you can go to System Preferences > Security and privacy > General and then click Allow (near the bottom of the window there should be something that says something like "Appium tried to run but was blocked" and a box that says allow. it should then let you run it the next time you try.

**Comment by crenshaw78** [comment]
<img width="697" alt="Screen Shot 2020-06-16 at 5 10 05 PM" src="https://user-images.githubusercontent.com/21042283/84833131-3daf4880-aff4-11ea-9a50-af3d41b6646f.png">

Yeah this is what you need to do in System Settings -> Security & Privacy -> General.
Still think this is a signing issue and needs to be dealt with on you Appium side.

**Comment by KazuCocoa** [comment]
Yes, it needs paid sign, but it is not handy for a voluntary based project like this.

Perhaps https://github.com/appium/appium-desktop/issues/1264 may help though.

**Comment by KazuCocoa** [comment]
`xattr -cr Appium.app` also help

**Comment by jamalalatrash93** [comment]
Download (.dmg) version not .zip and it's will work fine.

**Comment by HelderItiro** [comment]
This one worked for me 
https://www.youtube.com/watch?v=Vyaszsfq1uk

**Comment by geeethub** [comment]
> this might have only worked for me for my java installation (when i tried to do `brew cask install java`), but after it tries once you can go to System Preferences > Security and privacy > General and then click Allow (near the bottom of the window there should be something that says something like "Appium tried to run but was blocked" and a box that says allow). it should then let you run it the next time you try.

Thanks,that worked for me

**Comment by bikkyseemanta** [comment]
Definitely, this one worked for you guys
https://www.youtube.com/watch?v=Vyaszsfq1uk

**Comment by sureshautomation** [comment]
> `xattr -cr Appium.app` also help

this command helped launched the Appium desktop app on my Mac. thanks @KazuCocoa

**Comment by KazuCocoa** [comment]
We now address the `xattr` command in readmes.
Close this so far. (and pins this in issues tab)
https://github.com/appium/appium-desktop#installing-on-macos
https://github.com/appium/appium-inspector#installing-on-macos

**Comment by euexplorer** [comment]
@KazuCocoa no i am not using M1. Is there an older version available for appium inspector other than Appium-Inspector-mac-2022.1.2.dmg?

**Comment by KazuCocoa** [comment]
then, what about calling `xattr -cr Appium\ Inspector.app` after moving the `.app` into `/Applications`?
https://github.com/appium/appium-inspector/releases has past releases.

**Comment by anizali** [comment]
![image](https://user-images.githubusercontent.com/65526871/165869910-18953780-fa1e-4caa-9ed5-3cb3dd9f142a.png)
I am getting this error. while running appium desktop. 
I ran this command before opening for the first time. xattr -cr "/Applications/Appium Server GUI.app"

**Comment by jlipps** [comment]
@anizali https://github.com/appium/appium-desktop/issues/2024

**Comment by Mynziak** [comment]
> @anizali #2024

I have the same issue but tried run next commands before opening app :
xattr -cr /Applications/Appium\ Server\ GUI.app
codesign --deep --sign - /Applications/Appium\ Server\ GUI.app

**Comment by Mynziak** [comment]
I installed another (lower version) 1.22.2 and it works for me

**Comment by antarappnap** [comment]
> > @anizali #2024
> 
> I have the same issue but tried run next commands before opening app : xattr -cr /Applications/Appium\ Server\ GUI.app codesign --deep --sign - /Applications/Appium\ Server\ GUI.app

its work for me

**Comment by atikahasriana1** [comment]
> Hi Please follow the below steps
> 
> 1. Right-click
> 2. Select Open
> 3. Now move the appium to the Application folder

it's working here. Thank youuuu
