### ISSUE TITLE
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by qq490456661** [appium/appium-desktop#1218]
## Appium or Appium Desktop?

Appium 

## The problem

Run appnium in the console, memory overflow will occur over time.
A similar phenomenon occurs when running appnium.exe on Windows 10, except that appnium.exe automatically closes and disappears.
 
 
![image](https://user-images.githubusercontent.com/6499713/72308746-055bb500-36b8-11ea-971a-29d8812eb7f4.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
1.51
- I am on (pick one):
    - [ √ ] Windows

**Comment by KazuCocoa** [comment]
Appium got improvements for such memory stuff. Please try the latest one
