### ISSUE TITLE
Is there a DMG file for 1.16.0 release?

### ISSUE THREAD

**Issue by hqfking** [appium/appium-desktop#1226]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
We disabled 1.16.0 for now because of https://github.com/appium/appium-desktop/issues/1173 until the build issue will fix.

Please try to connect to a local server as https://github.com/appium/appium-desktop#connect-to-local-appium-server if you want to use 1.16.0.
