### ISSUE TITLE
Why "force-stop" app when delete session?

### ISSUE THREAD

**Issue by JF-Rabbit** [appium/appium-desktop#123]
After finish test, run code "driver.quit();"
On appium desktop(1.0.0-beta6), will "force-stop" app:
Log: 
[ADB] Running 'D:\Program Files\adt-bundle-windows-x86-20130917\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","G2W7N15323012269","shell","am","force-stop","com.xxxx.test"]

Bug on appium(Windows 1.4.16.1 or Mac 1.5.3), only delete session and do not stop app.

Is there a method could do not "force-stop"?
Cause I hope app will remain some evidences on screen when error happened, especially in unit test. If force stop app, only can find in log file.

**Comment by jlipps** [comment]
This is not related to appium desktop. You should open this query at the appium repo instead.
