### ISSUE TITLE
Outdated Version Shown (1.14.1) for Appium-Desktop on npmjs.com/package/appium-desktop

### ISSUE THREAD

**Issue by mrk-han** [appium/appium-desktop#1233]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

https://www.npmjs.com/package/appium-desktop

The latest shown version on npmjs is 1.14.1

![image](https://user-images.githubusercontent.com/22263679/73370305-ffea9700-4281-11ea-814b-eada98bafb71.png)

Will this be updated to enable running `npm i appium-desktop` for version 1.16.0?

**Comment by KazuCocoa** [comment]
hm... I didn't know the npm module.
Let me ask appium developers if someone published this module via npm

**Comment by imurchie** [comment]
It was published by someone I've never heard of...

https://www.npmjs.com/~ozcan.durak

**Comment by mrk-han** [comment]
@KazuCocoa @imurchie Are there any plans on hosting appium-desktop on homebrew or npm?

I am creating a script that sets up users for Appium Development, would be nice to have a one line command.

**Comment by imurchie** [comment]
No plans, no. But since it's hosted on github it should be relatively easy to write a script to get the dmg and install.

**Comment by mrk-han** [comment]
Ahh good point @imurchie . I'll do this. Thank you! 

The level of effort isn't too high to be available as a third-party tap for `brew cask` right? Would that be something y'all would be interested in?

**Comment by KazuCocoa** [comment]
Yes, no for official for now as https://github.com/appium/appium-desktop/issues/1233#issuecomment-580818459

**Comment by mrk-han** [comment]
Curious if there is any con for having the cask? What are the downsides?

**Comment by KazuCocoa** [comment]
No much resource, for now, to introduce new toolchain to support like brew.
It is welcome you to join us to maintain and help users them
