### ISSUE TITLE
appium ios blocked due to invalid server ip

### ISSUE THREAD

**Issue by coolvasanth** [appium/appium-desktop#1238]
Appium Desktop

## The problem

When I try to create a session with Appium, using below parameters, the creation fails and a popup comes which exists only for 5 seconds.  It consists of a HTML the body shows the below error: 
**Appium ios blocked due to invalid server ip**. Stuck with same since 3 days. Tried almost all the ways suggested on web, but no luck. 
`{
  "udid": "BBFA2DC3-7E84-49F0-A82C-***',
  "deviceName": "iPhone 8 (13.2.2)",
  "automationName": "XCUITest",
  "platformName": "iOS",
  "app": "/Users/Desktop/mm/Media\\ test.ipa"
}`

## Environment
Appium Desktop version : 1.15.1
Mac OS  :  Mojave
Xcode Version : 11.2.1
Simulato : iPhone 8 (13.2.2)

Note: I tried the same version of Appium Desktop in Windows machine and there it works perfectly fine. Facing issue only in Mac when testing for iPhone. 

- I am running Appium Desktop version _1.15.1
- I am on (pick one):
    - [* ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Please attach the full log to see your environment

**Comment by coolvasanth** [comment]
When I hit start session with above parameter a modal is opened with a lots of HTML contents, shall I paste that ? if Log is present, then let me know how to find it ?

**Comment by KazuCocoa** [comment]
Yes.

I haven't seen the error message, so need to track all appium logs to understand your situation. It is appreciated to use GitHub Gist to attach the log.
You can get raw log via the below icon, for example. 

![image](https://user-images.githubusercontent.com/5511591/73848173-f7d6bc80-486a-11ea-9f86-ba8216575e20.png)

**Comment by coolvasanth** [comment]
Unfortunately there have been no logs when I starting of session fails. I just get a popup with below HTML. This could be a problem with my office network, they are ready to help in all way. I just want to know, how to overcome this. 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="My Company Captcha Page">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://static.mycompany.com/captcha/images/apple-touch-icon-72px.png" rel="apple-touch-icon-precomposed" sizes="72x72" />
    <link rel="preconnect" href="https://static.mycompany.com" />
    <link rel="shortcut icon" href="https://static.mycompany.com/captcha/images/favicon-bluesteel-72px.png" type="image/png" />
    <link href="https://static.mycompany.com/captcha/images/apple-touch-icon-114px.png" rel="apple-touch-icon-precomposed" sizes="114x114" />
    <link href="https://static.mycompany.com/captcha/images/apple-touch-icon-144px.png" rel="apple-touch-icon-precomposed" sizes="144x144" />
    <title>Block page</title>
    <link rel="stylesheet" href="https://static.mycompany.com/captcha/css/bootstrap-3.3.7.min.css" media="all" />
    
    
    <link rel="stylesheet" href="https://static.mycompany.com/captcha/css/style-1.7.css" media="all" /> </head>

<body>
    <div class="container">
        <div class="row header">
            <div class="col-md-12"> <img src="https://static.mycompany.com/captcha/images/monogram_red.png" width="58" height="58" alt="mycompany.com" /> <span>My Companyk</span> </div>
        </div>
        
        <div class="row main">
            <div class="col-sm-12 vcenter table-responsive">
                <div class="title"> <img src="https://static.mycompany.com/captcha/images/warn.png" width="48" height="48" alt="" /> <span class="title">Access Blocked</span> </div>
                
                <div class="message">MyCompany currently <b>blocks access</b> to this website. This action is blocked because of the following reason:
                    <br/>
                    <p><b>Blocked due to invalid server IP</b></p>
                    <p class="blockurl">URL:&nbsp;<b>http://localhost:4723/wd/hub/session</b></p> <span class="blockhighlight">If there is a legitimate business need to access this website, please follow <a href="https://mycompany.service-now.com/nav_to.do?uri=%2Fcom.glideapp.servicecatalog_cat_item_view.do%3Fv%3D1%26sysparm_id%3D95a6de1edbf85b80d087d8965e9619a4">this link</a> to request an exception.</span></div>
            </div>
            
        </div>
        
        <div class="row languages row-centered">
            <div class="col-sm-12 col-centered languages"><a href="/pitc/?url=http%3A%2F%2Flocalhost%3A4723%2Fwd%2Fhub%2Fsession&referer=&reason=Blocked+due+to+invalid+server+IP&reasoncode=INVALID_SERVER_IP_DENIED&timebound=1&action=deny&kind=category&rule=&cat=Image+host&user=other&lang=en&zsq=BmF543SnWj87987DF43sJHBM89BmF543SnWj879zsq">English</a> | <a href="/pitc/?url=http%3A%2F%2Flocalhost%3A4723%2Fwd%2Fhub%2Fsession&referer=&reason=Blocked+due+to+invalid+server+IP&reasoncode=INVALID_SERVER_IP_DENIED&timebound=1&action=deny&kind=category&rule=&cat=Image+host&user=other&lang=fr&zsq=BmF543SnWj87987DF43sJHBM89BmF543SnWj879zsq">Français</a> | <a href="/pitc/?

**Comment by coolvasanth** [comment]
Unfortunately there are no logs when session creation fails. I think there could be a network problem from my company. But they are open to help me in all ways. Below gist consists of the message I,e shown on the popup. 
https://gist.github.com/coolvasanth/90d75b5aad40396ad4e6a1b7192bf093
Kindly check and help.

**Comment by KazuCocoa** [comment]
> Unfortunately there have been no logs when I starting of session fails.

Do you mean the error happens before appium server started? So, no Appium logs existed.
The below error means your local environment cannot resolve or access to the `localhost` name.

> Blocked due to invalid server IP
> URL: http://localhost:4723/wd/hub/session

If the local block can avoid non `localhost` name, `-a` may help.
https://appium.io/docs/en/writing-running-appium/server-args/

e.g.
```
appium -a your-local-hostname -p 5555
```

Then, the appium server works as `http://your-local-hostname:5555`

**Comment by coolvasanth** [comment]
Yes  There are no logs, before starting of session itself, I'm getting this error. After starting the Appium server, If I visit : this URL"http://localhost:4723/wd/hub/session" I get error like,  '/wd/hub/session' did not map to a valid resource.

**Comment by KazuCocoa** [comment]
mm, it sounds npm install issue.

What about clean your npm environment once?
If the installation failure was because of `NODE_ENV `, https://github.com/appium/appium-desktop/issues/1215 may help

**Comment by coolvasanth** [comment]
I do not see any problem with my npm environment. Everything seems to work fine, you also specify how to evaluate, if any problem in npm environment. I can check and confirm.

**Comment by KazuCocoa** [comment]
I have no idea except for the environment variables.
What about running appium server outside the desktop environment and trying to connect to it?
https://github.com/appium/appium-desktop#advanced-topics-and-troubleshooting

**Comment by harivenkatesh-id** [comment]
Even im facing same issue.
