### ISSUE TITLE
Error: Bad app. App paths need to be absolute

### ISSUE THREAD

**Issue by Sangitasubudhi** [appium/appium-desktop#1239]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
[XCUITest] Error: Bad app: /Users/sangitasubudhi/Documents/ssp_plugin.ipa. App paths need to be absolute or an URL to a compressed app file: Cannot calculate sha1 hash for '/Users/sangitasubudhi/Documents/ssp_plugin.ipa'. Original error: EISDIR: illegal operation on a directory, read

[debug] [W3C] Encountered internal error running command: Error: Bad app: /Users/sangitasubudhi/Documents/ssp_plugin.ipa. App paths need to be absolute or an URL to a compressed app file: Cannot calculate sha1 hash for '/Users/sangitasubudhi/Documents/ssp_plugin.ipa'. Original error: EISDIR: illegal operation on a directory, read

_Replace this section with a description of your issue_
I am using appium 1.16,xcode 11.3 and using iphone x getting bad app path 
## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Is https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a related?
