### ISSUE TITLE
Appium Inspector can't get the Xpath of Flutter elements in iOS app，but it works with Android app

### ISSUE THREAD

**Issue by zhongyazhang** [appium/appium-desktop#1240]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Inspector can't get the Xpath of Flutter elements in iOS app，but it works with Android app on Windows ，is there anyone tell me the reason？

## Environment

- I am running Appium Desktop version _<1.15.1>_.
- I am on (pick one):
    - [√] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Did the app return correct XML as `source` command?

**Comment by zhongyazhang** [comment]
No,I can select the native elements and the XML of them show in source pannel ,but when I put the Seletor on Flutter elements and click , there are no XML shows.

**Comment by mykola-mokhnach** [comment]
Flutter apps must be automated using their own driver. See https://github.com/truongsinh/appium-flutter-driver

**Comment by zhongyazhang** [comment]
Thanks for your reply.

**Comment by sahanaprasad** [comment]
is there any way to automate flutter apps without the app source code?

**Comment by KazuCocoa** [comment]
Possibly could with UIA2 or Espresso driver, but they cannot access to Flutter part(Dart VM) fully
