### ISSUE TITLE
Is there an Appium recommended cloud based service (paid) for running appium tests ?

### ISSUE THREAD

**Issue by Devapal** [appium/appium-desktop#1241]
Is there an Appium recommended cloud based service (Paid) for running appium mobile tests in cloud?
I tried Microsoft Appcenter, AWS Device Farm. Just wondering if Appium has a recommended could based service that is integrated with Appium better that the others.

I see some challenges with each of these cloud services. For example, Microsoft appcenter has a great device set but does not give you the flexibility to update Appium version (they are currently at 1.11 and takes years before they upgrade).

Can someone shed some light in to this ?

**Comment by Rup1** [comment]
Saucelabs

**Comment by ChanduReddy28041996** [comment]
Hi Devapal,

I recommend you to go with pCloudy(www.pcloudy.com) - Its a cloud-based mobile app testing platform where you can run your Appium based scripts on the platform.

You can write an email to sales@sstsinc.com or to vardhan.reddy@sstsinc.com, they can directly get in touch with you.

Thank you in Advance.

**Comment by KazuCocoa** [comment]
HeadSpin https://www.headspin.io/ as well

**Comment by dpgraham** [comment]
The Appium OSS contributors don't officially recommend cloud providers, we're neutral on that.

But disclaimer, I'm an employee of Sauce Labs and that's my personal recommendation.
