### ISSUE TITLE
Fails when sending text,: Error Message "org.openqa.selenium.InvalidElementStateException: Cannot set the element to 'Text'. Did you interact with the correct element?"

### ISSUE THREAD

**Issue by samratsusi** [appium/appium-desktop#1246]
Hello All, 
I am using Appium Desktop Version 1.15.1 and I have Android 8 on my Emulator. 

I am trying to send a text in one of the edit boxes but no luck. 
When I click that Elements it clicks it, when when I try to locate that element its Visible but its failing when I am trying to sent a text. 

Code: 
 AndroidDriver<AndroidElement> driver = new AndroidDriver<AndroidElement>( new URL("http://127.0.0.1:4723/wd/hub"), setCapabilities()); 

driver.findElement(By.xpath("//android.widget.EditText[@text='Username']")).sendKeys("Hey");

The error message is: 
org.openqa.selenium.InvalidElementStateException: Cannot set the element to 'Su'. Did you interact with the correct element?

Can someone help me out? 
I really appreciate it.

**Comment by KazuCocoa** [comment]
Could you share the full server log and page source as GIST?

**Comment by samratsusi** [comment]
Hello Kazu, These are the full server logs

Here is the link for GIST: 
https://gist.github.com/samratsusi/35c4e178c1f1ca2fb59fe6e764482f2a

**Comment by KazuCocoa** [comment]
Probably UIAutomator itself cannot set value to the element directly. For example, the element is not textfield, has no some attributes etc could affect it.

> I tried using getKeyboard and send text through it

This was because just type something to a focused element. This could be a workaround actually.
