### ISSUE TITLE
Appium Desktop 1.15.1 just crashes when iOS App is being called.

### ISSUE THREAD

**Issue by raosumanth** [appium/appium-desktop#1248]
## Appium or Appium Desktop?
Appium Desktop 1.15.1 just crashes when iOS App is being called.
Is there any other way of getting the logs? Also this is perfectly fine in Appium CLI. I was mainly trying to use Appium Desktop as I want to get the iOS App locators.

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I have the following desired capabilities :
{
  "deviceName": "iPhone 11 Pro Max",
  "platformName": "iOS",
  "platformVersion": "13.3",
  "app": "/Users/xxxx/Desktop/SDKTest4.194.app",
  "noreset": true,
  "automationName": "XCUITest",
  "useNewWDA": false
}

## Environment

- I am running Appium Desktop version 1.15.1.
- I am on (pick one):
    - [ X] Mac
    - [ ] Windows
    - [ ] Linux
[Screen Recording 2020-02-19 at 2.28.53 PM.zip](https://github.com/appium/appium-desktop/files/4227835/Screen.Recording.2020-02-19.at.2.28.53.PM.zip)

**Comment by KazuCocoa** [comment]
What about uninstalling `idb`?

**Comment by vkiN9art** [comment]
https://www.facebook.com/art.kanet.9/videos/644670716309487/?t=0 >> me too pls help

**Comment by KazuCocoa** [comment]
Did you uninstall `idb` from your machine as I commented https://github.com/appium/appium-desktop/issues/1248#issuecomment-589567781 ?

**Comment by raosumanth** [comment]
I am in the middle of some important work which needs idb, let me finish it and then update this thread. Since everything seems to be fine in Appium CLI, I am kind of not blocked.

**Comment by raosumanth** [comment]
Did a quick uninstall (not sure how to exactly remove idb on Mac), as brew uninstall --force idb succeeded but which idb still shows 
xxxx-MacBook-Pro:~ suma$ brew uninstall --force idb
xxxx-MacBook-Pro:~ suma$ brew cleanup -s idb
xxxx-MacBook-Pro:~ suma$ brew cleanup --prune-prefix
xxxx-MacBook-Pro:~ suma$ which idb
/usr/local/bin/idb

But a good thing is that appium-desktop does not crash. Again I am not sure how to uninstall idb completely.

Need to re-intsall idb :(

**Comment by KazuCocoa** [comment]
If you followed https://github.com/facebook/idb#quick-start , you probably should also uninstall from pipy, too.

**Comment by KazuCocoa** [comment]
This was idb stuff
