### ISSUE TITLE
Unable to install appium desktop in windows 10( 32 bit ).

### ISSUE THREAD

**Issue by Sha-123** [appium/appium-desktop#1249]
Unable to install appium desktop in windows 10( 32 bit ). Showing error popup as "windows 64-bit is needed". Please help me to resolve this issue.

## Environment
- I am trying to install Appium Desktop version _<1.15.0>_.
- I am on Windows 10(32-bit)

**Comment by Sha-123** [comment]
![image](https://user-images.githubusercontent.com/36278770/75026462-06f07800-54c3-11ea-8d40-020dfb011e52.png)

**Comment by KazuCocoa** [comment]
https://www.dropbox.com/s/1acc7xy6qvwneuw/Appium-windows-1.15.0.exe_.zip?dl=0
Can you install with this? @Sha-123 
I generated the module with `npx electron-builder build -w --ia32 --x64`

**Comment by Sha-123** [comment]
I really appreciate your help. Thank you

> https://www.dropbox.com/s/1acc7xy6qvwneuw/Appium-windows-1.15.0.exe_.zip?dl=0
> Can you install with this? @Sha-123
> I generated the module with `npx electron-builder build -w --ia32 --x64`

Able to install now. I really appreciate your help. Thank you

**Comment by KazuCocoa** [comment]
Okay, thanks for your checking.
Will wrap up the PR

**Comment by saiarun18** [comment]
I am trying to install appium 1.17 version. in my 32-bit system. 

need 32-bit compatible exe.

**Comment by KazuCocoa** [comment]
Could you try out this?
https://github.com/appium/appium-desktop/releases/tag/v1.18.0-beta.0
This is not appium 1.17.1 (appium beta), but I've built it by https://github.com/appium/appium-desktop/pull/1414
If it worked on 32 bit machine, we probably can add the package in our regular package

**Comment by KazuCocoa** [comment]
Next release has https://github.com/appium/appium-desktop/pull/1414
