### ISSUE TITLE
Appium Locator displayed unknown symbols

### ISSUE THREAD

**Issue by dmitry-zhemchugov** [appium/appium-desktop#1258]
## The problem
Appium Locator displayed unknown symbols in the `Selected Element` window

## Environment

- I am running Appium Desktop  _Version 1.15.1 (1.15.1.20191013.2)_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux
<img width="1007" alt="Screen Shot 2020-03-06 at 16 32 17" src="https://user-images.githubusercontent.com/44227371/76092764-a2581180-5fc8-11ea-935d-436e568eb9a1.png">

**Comment by KazuCocoa** [comment]
What about them in the result of `source` command?

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium-desktop/pull/1348 fixed this, too
