### ISSUE TITLE
Mac and Windows Installer Signing

### ISSUE THREAD

**Issue by imurchie** [appium/appium-desktop#1264]
## Installer Signing?

There is some discussion in the OpenJS about the foundation paying for, and maintaining, accounts for signing apps for distribution: https://github.com/openjs-foundation/cross-project-council/issues/476

I'm not sure of the implications of this, or if it is something we might want to make use of, so I'm bringing it up here. What are folks' thoughts?

**Comment by KazuCocoa** [comment]
Windows signing seems already by the foundation.
So far, https://github.com/appium/appium-desktop/issues/1217#issuecomment-660581904 allows users to open AD on macOS. AD cannot publish via store since WDA refers to private APIs

**Comment by KazuCocoa** [comment]
Close for now.
Win has a signing. macOS does not, but we guide them to `xattr -cr` for now. It is enough so far since we won't publish this via mac store for now.
