### ISSUE TITLE
Appium Desktop failing to connect to TestObject with error EPROTO

### ISSUE THREAD

**Issue by kirksl** [appium/appium-desktop#127]
Appium Desktop failing to connect to TestObject with error EPROTO

No Appium log is available from TestObject end as nothing executes.  Please advise if any logs are needed from the Appium Desktop machine and where to locate those logs.

Repro
1. From either Windows 10 or OSX El Capitan open Appium Desktop.
2. Leave everything set to defaults and click Start Server.
3. Click Start New Session.
4. Click TestObject option from the top.
5. Enter a valid TestObject API Key.
6. Enter a capability to target a TestObject device (eg "testobject_device": "iPad_mini_3_16GB_real_2")
7. Click Start Session.
8. Error: EPROTO displays --> http://pasteboard.co/1bI0ZrvQZ.png
9. Uninstall/install Appium Desktop and repeat steps above. EPROTO error displays again at step 8.
10. Note the original install was not experiencing this error yesterday.
11. Knowing the information in 10. continue with further testing.
12. Execute a test against the same TestObject API Key and testobject_device from wdio.
13. Test successfully connects, executes and passes. TestObject UI also functions correctly.

Appium version (or git revision) that exhibits the issue: 1.6.4-beta
Last Appium version that did not exhibit the issue (if applicable): 1.6.4-beta
Desktop OS/version used to run Appium: Windows 10 | OSX El Capitan
Node.js version (unless using Appium.app|exe): Not sure what TestObject is using
Mobile platform/version under test: Agnostic happens to any device type on TestObject
Real device or emulator/simulator: TestObject uses real devices
Appium CLI or Appium.app|exe: Appium Desktop both .app and .exe

**Comment by crummy** [comment]
Hi, Malcolm from TestObject here. Can you try this with Appium version 1.6.3?

**Comment by kirksl** [comment]
Hi Malcom.  I get the same error spec'ing 1.6.3 in capabilities.

{
  "testobject_device": "iPad_mini_3_16GB_real_2",
  "testobject_appium_version": "1.6.3"
}

**Comment by dpgraham** [comment]
I'm working on this now. @jlipps uncovered that it's actually an error with the client and not TestObject.

We should have a fix in for v1.0.0 of appium desktop which I'm going to try to get out no later than early next week.

**Comment by dpgraham** [comment]
I was able to fix it by changing from 'http' to 'https' and `port 80` to `port 443`

@crummy Have you seen this issue before? When I tried starting an Appium session with OpenSSL this happened:

`Error: write EPROTO 140735917638592:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794`

Strangely, it doesn't happen when attempting to run a session via cURL.

**Comment by dpgraham** [comment]
Fix is being pushed to v1.0.0

**Comment by kirksl** [comment]
thanks @dpgraham appreciate the fast turnaround.  this is an appium desktop change?  travis build for it looks like it's failing.

**Comment by dpgraham** [comment]
It is a Desktop change, and yeah, the Travis build always fails for Mac

The .dmg is available at https://github.com/appium/appium-desktop/releases/latest

**Comment by dpgraham** [comment]
@crummy I just confirmed that it's happening in both webdriverio and wd so I don't think it's a client specific issue.

WebdriverIO Code
```javascript
const webdriverio = require('webdriverio');

const hostname = 'appium.testobject.com';
const port = 80;
const https = false;


const client = webdriverio.remote({
  hostname,
  port,
  //protocol: 'http',
  username: undefined,
  accessKey: undefined,
  https,
  desiredCapabilities: {
    "testobject_api_key": "<api_key>",
    "testobject_device": "LG_Nexus_4_E960_real",
    "testobject_appium_version": "1.6.3",
    "testobject_cache_device": "false",
    "testobject_app_id": "1",
    "testobject_suite_name": "appium desktop dev",
    "testobject_test_name": "appium desktop dev"
  },
});

client.init()
  .getSource()
  .then(console.log.bind(console.log));
```

WD
```javascript
const wd = require('wd');

let driver = wd.promiseChainRemote({
  hostname,
  port,
  username: undefined,
  accessKey: undefined,
  https
});

async function simple () {
  await driver.init({
    "testobject_api_key": "<api_key>",
    "testobject_device": "LG_Nexus_4_E960_real",
    "testobject_appium_version": "1.6.3",
    "testobject_cache_device": "false",
    "testobject_app_id": "1",
    "testobject_suite_name": "appium desktop dev",
    "testobject_test_name": "appium desktop dev"
  });
  let source = await driver.source();
  console.log('source', source);
  await driver.quit();
}

simple().then(console.log.bind(console)).catch(console.log.bind(console));
```

**Comment by kirksl** [comment]
@dpgraham DMG is fixed.  Tested on El Capitan.  When EXE is ready I can test it.

**Comment by kirksl** [comment]
@jlipps FYI not sure if related but after starting session from Appium Desktop, TestObject's running result session displays the device's screen output instead of an all white screen.

**Comment by dpgraham** [comment]
The exe is ready too.
