### ISSUE TITLE
Inspect problem in Drop down elements

### ISSUE THREAD

**Issue by mahendra1999** [appium/appium-desktop#1270]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I inspect in 12.2 IOS version of simulator Drop Down Ids are Visible but while going on 13.3 version of IOS not able to see the Drop Down class.
Appium Version- 1.15.1
Xcode - 11.3.1
Simulator- 13.3
Mac version- 10.14.6
missing elements- //XCUIElementTypeOther[@name="drop_down"]

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - Mac

**Comment by mahendra1999** [comment]
In  App Source I can't able to see the //XCUIElementTypeOther[@name="drop_down"] elements

**Comment by KazuCocoa** [comment]
If you could not find the element in the source, Appium cannot do anything since the cause is in XCTest framework side.
What about using the latest `appium@1.17.0 rc` for iOS 13?

**Comment by mahendra1999** [comment]
Is Appium@1.17.0 Desktop version available?

**Comment by mahendra1999** [comment]
In Whole App of IOS 13.3, Drop Down options not showning in App source. what developer should do changes?

**Comment by KazuCocoa** [comment]
No. Only CLI is available > 1.17..0

Okay. So, the cause is XCTest internal. > Drop Down options not showning in App source.
Please try to report to Apple or ask them if they have a workaround

**Comment by mahendra1999** [comment]
I have dev with me, but he is doesn't have idea of this issue

**Comment by KazuCocoa** [comment]
Me, neither, unfortunately.
You probably can try Xcode 11.4 beta if Apple improved XCTest internal.

**Comment by mahendra1999** [comment]
okay, Thanks

**Comment by mykola-mokhnach** [comment]
Some good stuff for devs to read on this topic:
https://medium.com/@jchen_77520/accessibility-and-ui-testing-in-ios-3eb0822a17fb
https://www.raywenderlich.com/6827616-ios-accessibility-getting-started
