### ISSUE TITLE
can not create session with Espresso 

### ISSUE THREAD

**Issue by dodosophia** [appium/appium-desktop#1271]
## The problem

{
  "platformName": "Android",
  "udid": "",
  "automationName": "Espresso",
  "deviceName": "myPhone",
  "noSign": false,
  "platformVersion": "7.0",
  "app": "debug.apk",
  "fullReset": true,
  "forceEspressoRebuild": true
}
java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=com.test/com.test.android.pt.homepage.activity.Welcome launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1584019044476 and now the last time the queue went idle was: 1584019090684. If these numbers are the same your activity might be hogging the event queue.
## Environment

- I am running Appium Desktop version 1.15.1.
- I am on (pick one): Mac

**Comment by KazuCocoa** [comment]
> Perhaps the main thread has not gone idle within a reasonable amount of time?

Perhaps your app hadn't been idle for Espresso (Android framework).
Or probably it can work if you set `appWaitActivity` properly https://appium.io/docs/en/writing-running-appium/caps/
