### ISSUE TITLE
An unknown server-side error occurred while run appium 

### ISSUE THREAD

**Issue by DuMintong** [appium/appium-desktop#1277]
## Appium   1.15.1   
Run on window

ISSUE:
This error always occurs during start appium to run test cases.  When this happen, the Ride stop run and similarly hangs up. Then fail log output in ride after some times.
Follow logs output from appium when this issue occurs.  
This issue also happens even I try to run appium one more time in one phone and can't recovery.
I change a new phone to avoid this issue but also will be happen on this new phone  after appium run for a while. 

What possible reason for this issue?

********************************************************************
[W3C (980e7ca6)] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.TextView[@resource-id = 'com.oneplus.mms:id/title' and @text='Block number']","980e7ca6-c45d-409b-8f3f-a68e39c4f18a"]

[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator

[BaseDriver] Waiting up to 0 ms for condition

[WD Proxy] Matched '/elements' to command name 'findElements'

[WD Proxy] Proxying [POST /elements] to [POST http://localhost:8203/wd/hub/session/0c0682f0-57c3-4f47-8706-e770a90c641d/elements] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@resource-id = 'com.oneplus.mms:id/title' and @text='Block number']","context":"","multiple":true}

[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}

[W3C (980e7ca6)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

**Comment by Chiesonski** [comment]
I have the same problem

**Comment by KazuCocoa** [comment]
Please attach the full log as GIST. Possibly with logcat helps to dig it in further.

**Comment by Chiesonski** [comment]
Hi @KazuCocoa, I'm new to github, could you explain this "attach the full log as GIST. Possibly with logcat helps to dig it in further". I get the same problem and I can help to fix.

**Comment by KazuCocoa** [comment]
GIST is https://gist.github.com/new
It is helpful to separate long logs and conversations on this thread

**Comment by Chiesonski** [comment]
https://gist.github.com/Chiesonski/2ca994fd696bb2274b57de35cbd7f9f4

**Comment by KazuCocoa** [comment]
Android devtools 29.0.3 for Windows has an issue : https://github.com/appium/appium/issues/14001
Please downgrade the version. You can specify the version with `buildToolsVersion` caps. @Chiesonski 

Please consider using `automationName=UiAutomator2` as the warning in the log, btw.

**Comment by DuMintong** [comment]
HI  Kazu:

    This is the new logs :  https://gist.github.com/DuMintong/064dd9b8c59c0d408066c688bef84944

The key points:
*********************************************************************
[debug] [35m[WD Proxy][39m Proxying [DELETE /] to [DELETE http://localhost:8201/wd/hub/session/ba981259-60e7-4099-af4d-7e145adc3b21] with no body[warn] [35m[BaseDriver][39m Shutting down because we waited 60 seconds for a command
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[warn] [35m[Appium][39m Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

**Comment by KazuCocoa** [comment]
Something happened in the server since `The process has exited with code 0` suddenly happened

```
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/ea6b3b9b-f179-4bb9-b24e-8ad674786fa7/touch/perform [39m[32m200[39m [90m1304 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m[error] [35m[Logcat][39m Logcat terminated with code 0, signal null
[debug] [35m[Instrumentation][39m The process has exited with code 0[warn] [35m[BaseDriver][39m Shutting down because we waited 60 seconds for a command
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
```


Could you share the logcat?

**Comment by DuMintong** [comment]
[20200317-202600_oemlog.zip](https://github.com/appium/appium-desktop/files/4343432/20200317-202600_oemlog.zip)
Above is the whole logs that the phone output.  And Android.log file within it.

**Comment by KazuCocoa** [comment]
perhaps around below
```
03-17 20:20:53.527  2240  2240 D OpNotificationPanelView: setQsExpansion: height= 475.0, mQsMinExpansionHeight= 475, mQsMaxExpansionHeight= 1336, result= 475.0, getCallers= com.android.systemui.statusbar.phone.NotificationPanelView.onLayout:645 android.view.View.layout:22137 android.view.ViewGroup.layout:6290 android.widget.FrameLayout.layoutChildren:332 android.widget.FrameLayout.onLayout:270 
03-17 20:20:53.541  1498  4707 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10265 user=0: from pid 8953
03-17 20:20:53.541  1498  4707 D OPBF    : UidStateCache makeQuickJudgment, uid:10265 to do nothing for totalStateMap1:0 |needToMeetMap:0 |freezeState:true |reason:check Force stopping package:io.appium.uiautomator2.server reason:from pid 8953
03-17 20:20:53.541  1498  4707 E hw-IPCThreadState: native handle size is 192
03-17 20:20:53.541  1498  2716 D OPBF    : resumeRelateProcess uid:10265 |thread:Thread[OPBF_GeneralThread,5,main]
03-17 20:20:53.541  1498  2716 D PowerManagerService: acquireWL: l=249619767, f=0x1, t="freezeAction", ws=null, uid=1000, pid=1498
03-17 20:20:53.543  1498  2716 D OPBF    : setCGroupState():tofreeze=false, uid:10265 pkg:io.appium.uiautomator2.server --->>> ok reason:Force stopping package:io.appium.uiautomator2.server reason:from pid 8953
03-17 20:20:53.543  1498  2716 D OPBF    : UidStateCache makeQuickJudgment, uid:10265 to freeze for totalStateMap1:0 |needToMeetMap:0 |freezeState:false |reason:check operateNode reconfirm lastOperation:false lastOperatedReason:Force stopping package:io.appium.uiautomator2.server reason:from pid 8953
03-17 20:20:53.543  1498  2716 D OPBF    : setImperceptible uid:10265 to:true from:check match mask
03-17 20:20:53.543  1498  2716 D PowerManagerService: releaseWL: l=249619767 [freezeAction], f=0x1
03-17 20:20:53.543  1498  2716 D OPBF    : operateNodeIfNeeded uid:1000 |tofreeze:false, uid is not exist, return
03-17 20:20:53.543  1498  2716 D OPBF    : getAppStandbyBucket uid:10265 level:30 isQuickChange:true
03-17 20:20:53.544  1498  4707 I ActivityManager: Killing 7840:io.appium.uiautomator2.server/u0a265 (adj 0): stop io.appium.uiautomator2.server
03-17 20:20:53.544  1498  2716 D OPBF    : removeSpecificUidCache uid:10265
03-17 20:20:53.545  1498  2716 I WifiService: setHighPerfRestrict uid=10265 restrict=false callingUid=1000
03-17 20:20:53.545  1498  2716 V OpPowerManager: updateBlockedUids: uid = 10265 isBlocked = false
03-17 20:20:53.545  1498  2716 V OpPowerManager: clearing powerMgr mBGFrozenBlockedUids
03-17 20:20:53.546  1498  4707 E hw-IPCThreadState: native handle size is 531208467009
03-17 20:20:53.546  1498  4707 W ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
03-17 20:20:53.547   892  3238 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: killProcess is called for pid : 7840
03-17 20:20:53.547  1498  4707 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10265 user=0: finished inst
03-17 20:20:53.547  1498  4707 E hw-IPCThreadState: native handle size is 192
03-17 20:20:53.548  8108  8793 W Binder  : Caught a RuntimeException from the binder stub implementation.
03-17 20:20:53.548  8108  8793 W Binder  : java.lang.SecurityException: Calling from not trusted UID!
03-17 20:20:53.548  8108  8793 W Binder  : 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:520)
03-17 20:20:53.548  8108  8793 W Binder  : 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:424)
03-17 20:20:53.548  8108  8793 W Binder  : 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
03-17 20:20:53.548  8108  8793 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1032)
03-17 20:20:53.548  8108  8793 W Binder  : 	at android.os.Binder.execTransact(Binder.java:1005)
03-17 20:20:53.549  2229  2355 W LOMM==> PackageRecord:omm-test: updateKillClazz reason:0 new_res:4 0x4
03-17 20:20:53.550  2229  2355 W LOMM==> PackageRecord: skipped save pss as zero pkg:io.appium.uiautomator2.server
03-17 20:20:53.550  2229  2355 W LOMM==> OPMemoryManager: record has queued before:{10265=com.oneplus.omm.PackageRecord@4b3c8fb}
03-17 20:20:53.550  1498  4707 E hw-IPCThreadState: native handle size is 527051182080
```

**Comment by KazuCocoa** [comment]
Or something related to below?

```
03-17 20:20:54.467  1498  1536 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.uiautomator2.server flg=0x4000010 (has extras) } to com.google.android.gms/.games.chimera.GamesSystemBroadcastReceiverProxy
03-17 20:20:54.467  1498  1536 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.uiautomator2.server flg=0x4000010 (has extras) } to com.google.android.gms/.gass.chimera.PackageChangeBroadcastReceiver
03-17 20:20:54.467  1498  1536 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:io.appium.uiautomator2.server flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
```

If the security restriction was the cause, I guess you can find relaxed option in somewhere like developer options, security sections etc

**Comment by Chiesonski** [comment]
I downgrade Android devtools 29.0.3 to 29.0.2 and now I get this error:

An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.sneakersnstuff.supply' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.sneakersnstuff.supply' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.sneakersnstuff.supplyMainActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

This is the new log: https://gist.github.com/Chiesonski/6415a9cf2643c44bbfa14206d32a09ec

**Comment by KazuCocoa** [comment]
```
[info] [35m[UiAutomator2][39m Starting 'com.sneakersnstuff.supply/com.sneakersnstuff.supplyMainActivity and waiting for 'com.sneakersnstuff.supply/com.sneakersnstuff.supplyMainActivity'
```

and 

```
Original error: Activity name '.com.sneakersnstuff.supplyMainActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
```

Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md to tweak the waiting target. Appium could not find activity name `com.sneakersnstuff.supplyMainActivity` as the top. (Please consider to create a new issue if you found a new issue. You can also post questions in https://discussions.apple.com/ )

**Comment by DuMintong** [comment]
Hi  Kazucocoa，

      The log you point above maybe not the issue time.  I reproduct issue and get new logs.
The issue time is about 16:54:16 where click element.  After then appium stop run and seem blocked.  
The final error log output after several minus. The error output:
******************************************
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
******************************************

The whole appium log：https://gist.github.com/DuMintong/062a66b0a519cfceda4329258c265b77
The Ride runtime log:  https://gist.github.com/DuMintong/1829f1affcfc0e0eea672be2cd522809

The phone logs:
[oem_log.zip](https://github.com/appium/appium-desktop/files/4347992/oem_log.zip)

**Comment by DuMintong** [comment]
Hi Kazucocoa，
   Please help to check the above new logs again.  This issue blocks our team to develop  test   
   case for a long time.
   Thanks a lot.

**Comment by KazuCocoa** [comment]
`system_app_crash@2020-03-18-16_18_44_721`

```
Process: com.android.systemui
PID: 7026
UID: 10206
Flags: 0x30c83e0d
Package: com.android.systemui v29 (10)
Foreground: No
Build: NEWTON/SS9821/SS9821:10/QKQ1.191222.002/2003090449:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
	at com.oneplus.battery.OpChargingAnimationControllerImpl.genOpWarpChargingView(OpChargingAnimationControllerImpl.java:388)
	at com.oneplus.battery.OpChargingAnimationControllerImpl.onConfigChanged(OpChargingAnimationControllerImpl.java:641)
	at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:79)
	at com.android.systemui.Dependency.lambda$onConfigurationChanged$5(Dependency.java:586)
	at com.android.systemui.-$$Lambda$Dependency$kPs__qcikmBW73dMa2KQH8Zuk58.accept(Unknown Source:2)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:185)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:133)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:435)
	at com.android.systemui.Dependency.onConfigurationChanged(Dependency.java:586)
	at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:303)
	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:5561)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5766)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5689)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:42)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7696)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

If this log was the cause, the root cause is inside Android framework. Nothing can do in Appium side, unfortunately.

How about espresso driver?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/issues/1277#issuecomment-601094822 seems it happened outside Appium

**Comment by UpDev1010** [comment]
I also get this same error when new emulator starts up while I am working on with other emultor.
