### ISSUE TITLE
Unable to open Appium Desktop

### ISSUE THREAD

**Issue by yaswanth2216** [appium/appium-desktop#1299]
**Error Message** An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error spawn ENOTDIR

Log : 

The server is running
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 6 ms - 40
[HTTP] 
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 1 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","automationName":"Uiautomator2","deviceName":"Lenovo TB-X606FA","platformName":"Android","platformVersion":"9","udid":"HA12CP32","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","automationName":"Uiautomator2","deviceName":"Lenovo TB-X606FA","platformName":"Android","platformVersion":"9","udid":"HA12CP32","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1584560263971 (12:37:43 GMT-0700 (PDT))
[Appium] Appium v1.15.1 creating new AndroidUiautomator2Driver (v1.37.2) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "appActivity": "com.android.calculator2.Calculator",
[BaseDriver]   "appPackage": "com.android.calculator2",
[BaseDriver]   "automationName": "Uiautomator2",
[BaseDriver]   "deviceName": "Lenovo TB-X606FA",
[BaseDriver]   "platformName": "Android",
[BaseDriver]   "platformVersion": "9",
[BaseDriver]   "udid": "HA12CP32",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   connectHardwareKeyboard
[BaseDriver] Session created with session id: d73a512f-4e8e-4184-825b-36219ec75f07
[UiAutomator2] Starting 'com.android.calculator2' directly on the device
[ADB] Found 0 'build-tools' folders under '/usr/local/share/android-sdk' (newest first):
[ADB] Using 'adb' from '/usr/local/share/android-sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] Connected devices: [{"udid":"HA12CP32","state":"device"}]
[AndroidDriver] Using device: HA12CP32
[ADB] Using 'adb' from '/usr/local/share/android-sdk/platform-tools/adb'
[ADB] Setting device id to HA12CP32
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 28
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 9
[ADB] Device API level: 28
[UiAutomator2] Relaxing hidden api policy
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell settings put global hidden_api_policy_pre_p_apps 1'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell settings put global hidden_api_policy_p_apps 1'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell settings put global hidden_api_policy 1'
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 wait-for-device'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell dumpsys package io.appium.settings'
[ADB] Using 'apkanalyzer' from '/usr/local/share/android-sdk/tools/bin/apkanalyzer'
[ADB] Starting '/usr/local/share/android-sdk/tools/bin/apkanalyzer' with args ["manifest","print","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk"]
[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Command '/usr/local/share/android-sdk/tools/bin/apkanalyzer manifest print /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' exited with code 1
[ADB] Using 'aapt' from '/usr/local/share/android-sdk/platform-tools/aapt'
[ADB] The version code of the installed 'io.appium.settings' is greater than the application version code (26 > 19)
[ADB] There is no need to downgrade 'io.appium.settings'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell 'pgrep --help; echo $?''
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell pgrep -f io\\.appium\\.settings'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell dumpsys package io.appium.uiautomator2.server'
[ADB] Starting '/usr/local/share/android-sdk/tools/bin/apkanalyzer' with args ["manifest","print","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk"]
[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Command '/usr/local/share/android-sdk/tools/bin/apkanalyzer manifest print /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk' exited with code 1
[ADB] The version code of the installed 'io.appium.uiautomator2.server' is greater than the application version code (48 > 41)
[UiAutomator2] io.appium.uiautomator2.server installation state: newerVersionInstalled
[ADB] Checking app cert for /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk
[ADB] Cannot use apksigner tool for signature verification. Original error: Could not find 'apksigner' in ["/usr/local/share/android-sdk/platform-tools/apksigner","/usr/local/share/android-sdk/emulator/apksigner","/usr/local/share/android-sdk/tools/apksigner","/usr/local/share/android-sdk/tools/bin/apksigner"]. Do you have Android Build Tools installed at '/usr/local/share/android-sdk'?
[ADB] Defaulting to verify.jar
[ADB] '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk' is not signed with debug cert
[ADB] Signing '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk' with default cert
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Could not find 'apksigner' in ["/usr/local/share/android-sdk/platform-tools/apksigner","/usr/local/share/android-sdk/emulator/apksigner","/usr/local/share/android-sdk/tools/apksigner","/usr/local/share/android-sdk/tools/bin/apksigner"]. Do you have Android Build Tools installed at '/usr/local/share/android-sdk'?
[ADB] Resigning apk.
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell am force-stop com.android.calculator2'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell settings delete global hidden_api_policy_pre_p_apps'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell settings delete global hidden_api_policy_p_apps'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s HA12CP32 shell settings delete global hidden_api_policy'
[BaseDriver] Event 'newSessionStarted' logged at 1584560267350 (12:37:47 GMT-0700 (PDT))
[MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error spawn ENOTDIR
[MJSONWP]     at ADB.signWithDefaultCert (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:125:13)
[HTTP] <-- POST /wd/hub/session 500 3382 ms - 206
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 4 ms - 57
[HTTP]

**Comment by KazuCocoa** [comment]
> [MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error spawn ENOTDIR

You failed to sign apks properly.

>  [ADB] Cannot use apksigner tool for signature verification. Original error: Could not find 'apksigner' in ["/usr/local/share/android-sdk/platform-tools/apksigner","/usr/local/share/android-sdk/emulator/apksigner","/usr/local/share/android-sdk/tools/apksigner","/usr/local/share/android-sdk/tools/bin/apksigner"]. Do you have Android Build Tools installed at '/usr/local/share/android-sdk'?

Where did you install android build-tools? In most case, `apksigner` is in the directory.
e.g. `/Users/kazu/Library/Android/sdk/build-tools/28.0.3/`
If your environment has no build tools, you probably should build Android SDK again.

**Comment by yaswanth2216** [comment]
This is where my build tools is
/Users/xxxx/Library/Android/sdk/build-tools/29.0.3/
but still i am unable to open Appium Desktop...
able to run the test through intelliJ via appium (terminal)

but i want to inspect elements and unable to open uiautomatorviewer as well

**Comment by KazuCocoa** [comment]
hm, but Appium could not find the path correctly.
```
[BaseDriver] Session created with session id: d73a512f-4e8e-4184-825b-36219ec75f07
[UiAutomator2] Starting 'com.android.calculator2' directly on the device
[ADB] Found 0 'build-tools' folders under '/usr/local/share/android-sdk' (newest first):
```

What the output of `echo $ANDROID_HOME`?
A possible case is InteliJ has its environment variable locally, but you do not have system-wide one. You can set the variable in _Edit Configuration_ only for Appium desktop.

**Comment by KazuCocoa** [comment]
If the cause is environment variables stuff, below may help.
https://github.com/appium/java-client/blob/ce942a6cf58bbd35804c196c5360c4ffa743541e/docs/environment.md#appium-environment-troubleshooting
