### ISSUE TITLE
Highlight selected elements on Inpector

### ISSUE THREAD

**Issue by muratme** [appium/appium-desktop#13]
@jlipps It is a very nice GUI but while i inpect my app. It does not highlight selected element on inspector screen. It is someting that i am missing ?

**Comment by jlipps** [comment]
@muratme how are you expecting that it will work? The way it works now is that when you mouseover an element in the inspector, it will draw a box around it. It does not know anything about what you might be doing with the simulator or device directly.

**Comment by muratme** [comment]
@jlipps i mean i  does not draw that box you mentioned around element.
<img width="1201" alt="screen shot 2016-12-28 at 09 43 41" src="https://cloud.githubusercontent.com/assets/5227443/21515588/3728c2f0-cce2-11e6-8f50-b9968deab957.png">

**Comment by dpgraham** [comment]
What happens when you highlight your mouse over the screenshot page? Is it showing the yellow highlighter box?

Also, have you tried refreshing the source? Sometimes the source becomes stale.

**Comment by muratme** [comment]
@dpgraham it does not show yellow box, and i tried to refresh source but notting changed.

**Comment by oreogithub** [comment]
@dpgraham How did you get this inspector? Can you tell how to get that?

**Comment by oreogithub** [comment]
@muratme That picture about inspector, how did you find it? I have looking for this feature for days. Could you tell how to get that?

**Comment by dpgraham** [comment]
It's a new inspector. We haven't released it yet but if you go to https://github.com/appium/appium-desktop there's instructions on the readme how to build it.

**Comment by oreogithub** [comment]
@dpgraham Thank you for telling me. i will keep my concern about your workings.

**Comment by dpgraham** [comment]
I couldn't reproduce this. If it still is happening in master branch, let me know and I can revisit this.
