### ISSUE TITLE
Not able to invoke FindElementByAndroidUIAutomator

### ISSUE THREAD

**Issue by akash-ui** [appium/appium-desktop#1306]
##Appium

                public static AndroidDriver driver;

                  String currentWorkinDirectory = System.getProperty("user.dir");
		String appName = "/application.apk";
		String newPathToAPK = currentWorkinDirectory + appName;
		System.out.println(newPathToAPK);
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "one");
		capabilities.setCapability(MobileCapabilityType.APP, newPathToAPK);
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
		System.out.println(newPathToAPK);

		driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

		driver.findElementByXPath("//android.widget.TextView[@text='Preference']").click();

So my code is working, however it is not detecting
I am trying to Invoke this FindElementByAndroidUIAutomator

Both below are not available
driver.findElementByAndroidUIAutomator()
or 
driver.findElement(By.AndroidUIAutomator())

**Comment by KazuCocoa** [comment]
What the meaning of _not available_?
Appium server returned an error or Java client issue?

**Comment by KazuCocoa** [comment]
If the cause was Java client's method issue, it is Java client issue.
If no element returned, perhaps you should make sure what element/s is/are available in the view
