### ISSUE TITLE
Error Message : "An unknown server-side occurred while processing the command. Original error : The instrumentation process cannot be initialized. Make sure  the application under test does not crash and investigate the logcat output.

### ISSUE THREAD

**Issue by weh2017** [appium/appium-desktop#1315]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## I have encountered the error message below after I started the session button and my script wasn't able to run 
 See error message below : 

**Error Message : "An unknown server-side occurred while processing the command. Original error : The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
_Replace this section with a description of your issue_**

- I've tried running the appium from the command line and it works fine

- I am running Appium Desktop version _1.15.1_.
- I am on 
    - [* ] Windows

**Comment by KazuCocoa** [comment]
Did you check the logcat?
And please attach the full log as gist.

**Comment by weh2017** [comment]
Hi,

Issue has been resolved on its own, I've just Stop and Start appium server
several times until issue is resolved.


Thanks,
Ruel

**Comment by paulson369** [comment]
It was working perfectly, but today i am getting this error message (Failed to create session. An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.).
Please help me.
