### ISSUE TITLE
Vertical scrolling doesn't work on app source viewer

### ISSUE THREAD

**Issue by tiecongli** [appium/appium-desktop#1316]
## The problem

I have a long list of elements on app source viewer. I realize the horizontal scrolling works but NOT the vertical scrolling. Vertical scrolling is broken.  

## Environment

- I am running Appium Desktop version 1.170.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by VitorJeremias** [comment]
I have the same issue. Instead of scrolling down the elements, it scrolls all the app screen, even hiding the top menu. Mac v1.17 as well.

**Comment by alexnot95** [comment]
The same issue for me. Mac v1.17
