### ISSUE TITLE
Scroll is not working in Source panel in Appium Desktop

### ISSUE THREAD

**Issue by deepakarorawins** [appium/appium-desktop#1328]
## Appium Desktop

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_When we have high tree of elements than source panel is not scrollable and we are not able to see elements node below the visible area of the panel._

## Environment

- I am running Appium Desktop version _1.17.0_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
fixed in https://github.com/appium/appium-desktop/pull/1327
