### ISSUE TITLE
Unable to start a new session with Appium desktop

### ISSUE THREAD

**Issue by Katipalli** [appium/appium-desktop#133]
XCODE version: 8.2

JSON Representation:

{
  "platformName": "iOS",
  "udid": "XXXXXXXX",
  "bundleId": "XXXXXXX",
  "deviceName": "iPhone 6",
  "platformVersion": "10.0.1",
  "automationName": "XCUITest"
}

I am trying to start a new session with real device on MAC, but seems like it is looking for simulator. any help is appricaited.

Error Log:

[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' exited with code 1: xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphonesimulator'

**Comment by jlipps** [comment]
yes, the simulator is required. have you opened up xcode and installed the additional software that often must be installed?

alternatively, try "10.0" as the platformversion instead of 10.0.1.

**Comment by Katipalli** [comment]
Hello,

I am not planning to use simulator, connected a real device to MAC, isn't not work with devices?
I also tried 10.0 as platform version, but did not help

Thank you

**Comment by jlipps** [comment]
You still need the iphone simulator sdk from xcode. This is not an appium desktop issue; this is an appium setup issue. Please ask for help on the appium forums after reading the setup docs.
