### ISSUE TITLE
Could not Connect to Server

### ISSUE THREAD

**Issue by Nish0106** [appium/appium-desktop#1338]
Facing the below issue while trying to launch App in UIA2

Details:

OS   -  Windows10
Appium version -  tried in both 1.8 and 1.15
Mobile   -  OPPO F3
Android Version -  V6

Please find the attached file for the error!

![Server_notConnected](https://user-images.githubusercontent.com/63442145/79131619-7e0d0300-7dc6-11ea-94c8-69eac4132e2f.PNG)

Please suggests to fix the issue

**Comment by KazuCocoa** [comment]
Please attach the server log as GIST

**Comment by Nish0106** [comment]
Hi,
Please find the Server log file  for your reference

[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4474733/appium-server-logs.txt)


Thanks,
Nishar Ahamed

**Comment by KazuCocoa** [comment]
1.8.1 is too old. Could you try 1.15 instead?

The error message means Appium desktop failed to connect to your local Appium server.
Please make sure you environment can resolve `http://localhost:4723` (by default).
Possible case is your environment could not resolve `localhost` properly.

**Comment by Nish0106** [comment]
Hi,

Previously I used to have 1.15 in which I faced the same issue hence I
downgraded to 1.8

I will try to resolve the port issue and let you know the status


Thanks,
Nishar Ahamed

**Comment by Nish0106** [comment]
Hi,
I am facing the same issue with 1.15 also

I am unable to execute the test cases and completely stuck due to this

Please suggests to fix the issue at the earliest

PFA log file for your reference
[appium-server-logs_v1.15.txt](https://github.com/appium/appium-desktop/files/4479303/appium-server-logs_v1.15.txt)

**Comment by KazuCocoa** [comment]
What happen when you open http://localhost:4723/ on the browser after starting Appium server on the desktop app?

**Comment by Nish0106** [comment]
Hi,

I didn test that but by setting it to the automatic server mode I am able
to start the server and able to execute test case

Thank you,
Nishar Ahamed

**Comment by Nish0106** [comment]
HI,
The above issue can be resolved by selecting the "Automatic server" at the top of the Appium UI 
Hence I am closing this issue

Thank you for your support
