### ISSUE TITLE
Could not find devices, restarting adb server

### ISSUE THREAD

**Issue by gosherry** [appium/appium-desktop#1339]
## Appium Desktop?

[info] [35m[Appium][39m Welcome to Appium v1.17.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m23 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.xfc.MainActivity","appPackage":"com.xfc","deviceName":"GBGDU19926003932","platformName":"Android","platformVersion":"9.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.xfc.MainActivity","appPackage":"com.xfc","deviceName":"GBGDU19926003932","platformName":"Android","platformVersion":"9.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1586932291405 (14:31:31 GMT+0800 (中国标准时间))
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m 
[info] [35m[Appium][39m Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.44.2) session
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "appActivity": "com.xfc.MainActivity",
[debug] [35m[BaseDriver][39m   "appPackage": "com.xfc",
[debug] [35m[BaseDriver][39m   "deviceName": "GBGDU19926003932",
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "platformVersion": "9.0",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: 2a2eca49-d0d2-418e-b08f-397e43fee7a1
[info] [35m[UiAutomator2][39m Starting 'com.xfc' directly on the device[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1586932314606 (14:31:54 GMT+0800 (中国标准时间))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not find a connected Android device in 22866ms.
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:211:13)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:18)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at ADB.getDevicesWithRetry (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:226:10)
[debug] [35m[MJSONWP][39m     at Object.getDeviceInfoFromCaps (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:180:19)
[debug] [35m[MJSONWP][39m     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:290:26)
[debug] [35m[MJSONWP][39m     at AndroidUiautomator2Driver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:212:7)
[debug] [35m[MJSONWP][39m     at AppiumDriver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:358:35)
[debug] [35m[MJSONWP][39m Destroying socket connection
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m23300 ms - 190[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m2 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.xfc.MainActivity","appPackage":"com.xfc","deviceName":"GBGDU19926003932","platformName":"Android","platformVersion":"9.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.xfc.MainActivity","appPackage":"com.xfc","deviceName":"GBGDU19926003932","platformName":"Android","platformVersion":"9.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1586932391722 (14:33:11 GMT+0800 (中国标准时间))
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m 
[info] [35m[Appium][39m Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.44.2) session
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "appActivity": "com.xfc.MainActivity",
[debug] [35m[BaseDriver][39m   "appPackage": "com.xfc",
[debug] [35m[BaseDriver][39m   "deviceName": "GBGDU19926003932",
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "platformVersion": "9.0",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: 471f041d-4890-470e-a6b8-62af507eab31
[info] [35m[UiAutomator2][39m Starting 'com.xfc' directly on the device[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m Could not find devices, restarting adb server...
[debug] [35m[ADB][39m Restarting adb
[debug] [35m[ADB][39m Killing adb server on port '5037'
[debug] [35m[ADB][39m Running 'C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -P 5037 kill-server'[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1586932414207 (14:33:34 GMT+0800 (中国标准时间))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not find a connected Android device in 22468ms.
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:211:13)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:18)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
[debug] [35m[MJSONWP][39m     at ADB.getDevicesWithRetry (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:226:10)
[debug] [35m[MJSONWP][39m     at Object.getDeviceInfoFromCaps (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:180:19)
[debug] [35m[MJSONWP][39m     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:290:26)
[debug] [35m[MJSONWP][39m     at AndroidUiautomator2Driver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:212:7)
[debug] [35m[MJSONWP][39m     at AppiumDriver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:358:35)
[debug] [35m[MJSONWP][39m Destroying socket connection
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m22498 ms - 190[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m1 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m

But when I run adb devices，it could find my phone
## Environment

- I am running Appium Desktop version _1.17_.
- I am on:
    Windows

**Comment by KazuCocoa** [comment]
> it could find my phone

With below command?
`C:\appium1\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe devices`

**Comment by KazuCocoa** [comment]
I guess the cause was adb command on Windows. Please try out different adb versions..
