### ISSUE TITLE
is:issue is:open IOS Tablet The Appium Desktop v1.17 no objects are being identified and actions are not performed on native app

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium-desktop#1341]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Appium Desktop v1.17 IOS Tablet no objects are being identified and actions are not performed on native app

## Environment
- IOS 13.4.1
- I am running Appium Desktop version _<1.17.0>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Please attach the full server log as GIST

**Comment by KazuCocoa** [comment]
No much info to dig
