### ISSUE TITLE
Original error: Could not sign with default certificate. An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by Nishant-Taksande** [appium/appium-desktop#1343]
## Appium or Appium Desktop?
Appium

## The problem
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/bin/java' not found. Is it installed?

**Appium locates JAVA_HOME for signing as**
'/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/bin/java' not found. Is it installed?

**Whereas JAVA_HOME is set to**
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set

## Environment
- I am running Appium version _<1.17.0>_.
- I am on (pick one):
    - [Y] Mac

**Comment by KazuCocoa** [comment]
Did you set java home in 'Edit Configurations'?
![image](https://user-images.githubusercontent.com/5511591/79678465-e4ff4180-8236-11ea-8520-35c17e97d686.png)

**Comment by KazuCocoa** [comment]
`/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home` is correct.
The binary should be `/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java`

**Comment by Nishant-Taksande** [comment]
@KazuCocoa 
i am not sure if this was a path related issue.
updated to appium@1.17.1-beta.0, 
it works fine now

**Comment by KazuCocoa** [comment]
Thanks.

Hm...
I have no idea why it was resolved... I guess the root cause was JAVA_HOME path form AD app...
