### ISSUE TITLE
Appium can't initiate a chrome based session on the real device

### ISSUE THREAD

**Issue by satymaju** [appium/appium-desktop#1345]
## The problem/the log :
[Instrumentation] 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:287)
[Instrumentation] The process has exited with code 1
[UiAutomator2] Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[UiAutomator2]     at Object.wrappedLogger.errorAndThrow (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:79:13)
[UiAutomator2]     at UiAutomator2Server.errorAndThrow [as startSession] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:227:13)
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\satymaju\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ce061606a21ebe1203 forward --remove tcp\:8200'
[BaseDriver] Event 'newSessionStarted' logged at 1587309856227 (20:54:16 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[W3C]     at Object.wrappedLogger.errorAndThrow (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:79:13)
[W3C]     at UiAutomator2Server.errorAndThrow [as startSession] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:227:13)
[HTTP] <-- POST /wd/hub/session 500 36970 ms - 906

## Environment

- I am running Appium Desktop version _<v1.15.1>_.
- I am on (pick one):
    - [ ] Windows

**Comment by satymaju** [comment]
Error message from robot framework : 

WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.

**Comment by KazuCocoa** [comment]
Did you check the logcat?

**Comment by KazuCocoa** [comment]
It seems the logcat was necessary, but no much info for now.

**Comment by satymaju** [comment]
The problem that I analysed later, was that, UIAutomator2 was already installed in the mobile device when I initiated appium execution from a desktop earlier.
Later when I was trying to execute again on the same mobile device but from a different desktop, at that point appium desktop was trying to reinstall UIAutomator2 in the device, but since it was already present it was having problem.

Some solution was : to delete UIAutomator2 from the device and then try.
My Solution (not the best, but worked in distress) : Just tried with UIAutomator1 instead..

Please analyze from above and let me know if you think otherwise

Regards,
Satyaki

**Comment by KazuCocoa** [comment]
Please attach the full log and the logcat.
The attached log was very limited to understand the situation correctly.
