### ISSUE TITLE
how to ready Xpath for Element - //XCUIElementTypeStaticText[@name=""]; ??

### ISSUE THREAD

**Issue by ashgupta2020** [appium/appium-desktop#1346]
Hi all 
I have Native iOS app that I am testing and I have a **+** on the screen to add  new employee. 

I am able to generate the xpath to find this element in Android. 
However, when I inspect this app on iPhone 11 using appium studio, Xpath I am getting for this is 

//XCUIElementTypeStaticText[@name=""];

XML from Appium Inspect 
                            <XCUIElementTypeLink type="XCUIElementTypeLink" name="" label="" enabled="true" visible="true" x="329" y="49" width="26" height="33">
                              <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="" name="" label="" enabled="true" visible="true" x="329" y="49" width="26" height="33"/>
                            </XCUIElementTypeLink>

How can I generate readable Xpath for this attribute as I not able to ready the special character in my test scripts. 

See attached screen shots. Any help will be appreciated 
![Add_Btn1](https://user-images.githubusercontent.com/64055060/79825105-70193c80-83db-11ea-8d90-08df0844a4da.PNG)
![Add_Btn2](https://user-images.githubusercontent.com/64055060/79825107-714a6980-83db-11ea-8b9d-d62993e0d760.PNG)

## Environment

* Appium version (or git revision) that exhibits the issue: V1.15.1

* Mobile platform/version under test: iphone 11 pro
* Real device or emulator/simulator: Real device on Browerstack

**Comment by KazuCocoa** [comment]
How about selecting it in the source tree?

**Comment by mykola-mokhnach** [comment]
@KazuCocoa I assume the issue here is that AD does not properly handle Unicode characters like smiles in the source XML

**Comment by KazuCocoa** [comment]
The latest master may have the fix
