### ISSUE TITLE
How to use Appium 1.6.4 GUI on mac

### ISSUE THREAD

**Issue by dadityad** [appium/appium-desktop#136]
i have successfully used appium 1.5.3 but get confused with most awaited GUI build 1.6.4 how to launch the specific application on ios simulator

**Comment by jlipps** [comment]
@dadityad It's all explained in the README for this repo; what is not working for you?

**Comment by dadityad** [comment]
Thanks @jlipps for reply i was stuck on "automationName" and "deviceName" compare with Desired Capabilities screenshot in README
And currently it shows following error 
"Encountered internal error running command: Error: Simulator is not booted after 120 seconds"
ping me if you required complete log

**Comment by dem0n0cracy** [comment]
{
  "deviceName": "iPhone 6",
  "platformName": "iOS",
  "platformVersion": "10.2",
  "automationName": "XCUITest",
  "wdaLocalPort": 8100,
  "scaleFactor": "0.5",
  "noReset": "false",
  "fullReset": "false",
  "app": "/Users/yourAppName.app",
  "calendarFormat": "gregorian",
  "sendKeyStrategy": "oneByOne"
}

I individually added these  to the Desired Capabilities then Saved them. Now I can 'Start Session' and it runs the app in the simulator and opens a new screen with the Inspector where it loads the elements.

**Comment by jlipps** [comment]
@dadityad if you're running into problems starting a session like that, it's probably not an appium desktop issue. I'd raise your issue with full logs at the appium repo.
