### ISSUE TITLE
Unable to scroll down app source in Appium desktop 1.17.0

### ISSUE THREAD

**Issue by tanmoysahat** [appium/appium-desktop#1373]
In Appium desktop inspector window when I open up the complete source, the app inspector window doesn't show me the vertical or horizontal scroll bar.

please find the below attachment.

![image](https://user-images.githubusercontent.com/27301604/80812938-9f535900-8be6-11ea-9794-e715103e539b.png)

**Comment by KazuCocoa** [comment]
Was it with 1.17.0 pre released one?

Then, it was fixed in https://github.com/appium/appium-desktop/pull/1327 . It is available in master branch for now

**Comment by NikeX** [comment]
When this fix is expected to be released? This is a big blocker now.

**Comment by KazuCocoa** [comment]
We pre released https://github.com/appium/appium-desktop/releases/tag/v1.17.1

**Comment by NikeX** [comment]
The scroll in the app tree is working well. Also in 1.17.0 there was a small issue with selecting the capabilities, which is also not present in 1.17.1. 
Thank you.

**Comment by Vgalla376** [comment]
I still this issue in the latest version

**Comment by jlipps** [comment]
you should not be using appium desktop's inspector anymore, it's several years out of date. the new inspector is at https://github.com/appium/appium-inspector
