### ISSUE TITLE
Not able to run ./Scripts/bootstrap.sh -d in terminal

### ISSUE THREAD

**Issue by Pankajpatel03** [appium/appium-desktop#1375]
## Environment

* Appium version : 1.51.1
* Desktop OS/version : MacBook Pro Catalina

##WedDriverAgent Location

/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent

## Details
I am running below command in the terminal
./Scripts/bootstrap.sh -d

## Getting error 
zsh: no such file or directory: ./Scripts/bootstrap.sh

**Comment by KazuCocoa** [comment]
Did the file in appium-webdriveragent
I wondered some node_modules were missing

**Comment by Pankajpatel03** [comment]
@KazuCocoa 
Yes there is
/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent

**Comment by KazuCocoa** [comment]
Then, could you share the appium log?

**Comment by rahul-8901** [comment]
restart the system
**mkdir -p Resources/WebDriverAgent.bundle**
run this command inside the folder 
and then try running  **./Scripts/bootstrap.sh -d**
this should work

check your path correctly this is my path for appium desktop
**/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent**

**Comment by Pankajpatel03** [comment]
@rahul-8901 
Thanks 
my path is correct and have tried with your solution but still no luck with it.
getting same error

**Comment by KazuCocoa** [comment]
mm, can you launch the remote server?
https://github.com/appium/appium-desktop#connect-to-local-appium-server (installed as no root user)

I wondered this happens in `/Applications/Appium.app/`.
For example, no write permission in the build process.

**Comment by KazuCocoa** [comment]
Appium 1.20 beta already dropped carthage stuff

**Comment by balaji-githubstore** [comment]
Give the complete path and try, carthage bootstrap --no-use-binaries
cp Cartfile.resolved Carthage
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Scripts/bootstrap.sh -d

**Comment by sandhyaVijaykumar6** [comment]
Hi am getting this error when am trying to launch basic capability code for IOS Apps... not sure on what am missing on:
W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1
[W3C]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)
[HTTP] <-- POST /wd/hub/session 500 37061 ms - 894

**Comment by KazuCocoa** [comment]
I guess the case was permission stuff by the OS against the route.
Probably newer versions can avoid the issue...

If you'd like to attach to an appium process using this inspector feature, you also can try out https://github.com/appium/appium-inspector and https://github.com/appium/appium-inspector#connecting-to-a-local-server-from-the-browser-inspector-cors
