### ISSUE TITLE
Implement record and playback test functionality?

### ISSUE THREAD

**Issue by kutran** [appium/appium-desktop#138]
Where can I find the record and playback buttons?

## Environment

- I am running Appium Desktop version 1.0.0.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by daniele81** [comment]
please , i need this features

**Comment by dpgraham** [comment]
We don't have these features yet. Depending on the demand for it we could move it up as a higher priority feature addition, or if somebody out there makes a pull-request we'd be happy to move it up the queue.

**Comment by bridgewaterrobbie** [comment]
@dpgraham 
Where can I find the old appium desktop? I need to use this and one other feature of the old inspector, and I overwrote it while installing this new one. Thanks

**Comment by JasonArm** [comment]
I'm using 1.0.2-beta.2
I'm on Windows.
The old Inspector (on Mac) had some really good functions for writing tests.  It would be great if those were available for Windows in the new version. Please.

**Comment by dpgraham** [comment]
@JasonArm which features were in the old Inspector that aren't in the new Appium Desktop that you liked using? We're going to assess which features we should add to the new Desktop based on popular demand.

**Comment by thiemf** [comment]
please add the record & playback features

**Comment by ecampii** [comment]
yes please.

**Comment by amarnathrayudu** [comment]
Yes ... at least in case of getting the co-ordinates for swipe actions.

**Comment by dpgraham** [comment]
@amarnathrayudu Can you elaborate on that one? Which feature gets the coordinates of swipe actions?

**Comment by amarnathrayudu** [comment]
@dpgraham ,
In the previous appium IDE, we used to have record option that captures the steps and the coordinates for the actions like swipe. Now it is hard to get the coordinates without record option.
It would be great if we have the option added.

**Comment by dpgraham** [comment]
@amarnathrayudu So the previous IDE had a 'swipe' functionality?

**Comment by bridgewaterrobbie** [comment]
For me the biggest things were:
The ability to have a locator suggested that uses XPATH, but uses ID's and such where possible to create the shortest possible locator in XPATH

The ability to have some code that is essentially ready to move into an IDE

The ability to SEARCH for a locator to verify my modification is accurate 

Thanks

**Comment by amarnathrayudu** [comment]
@dpgraham, 
Actually previous IDE used to record our actions and used to provide the code including coordinates.
<img width="664" alt="appium-inspector" src="https://user-images.githubusercontent.com/4190694/27094312-8c348c56-501e-11e7-99dd-e360b18d81d7.png">

**Comment by padmakarsrinivas** [comment]
Yes please, We need recorder for us to use swipe feature.

**Comment by jlipps** [comment]
this has been implemented and is in master. the swipe method is a different feature altogether. as is playback; not sure if we are planning on implementing that at all. code generation of actions taken with appium desktop was always the main goal.

**Comment by amarnathrayudu** [comment]
Thanks a ton @dpgraham and @jlipps 👍
