### ISSUE TITLE
[Qt] appium-desktop shuts down xscreensaver?!

### ISSUE THREAD

**Issue by 3id010nCD** [appium/appium-desktop#1387]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Something strange happens when I'm starting appium-desktop (appium cli is ok, i.e. there is no such output and it's not shutting down xscreensaver daemon):
```
 ~/Applications >>>  ./Appium-linux-1.17.0_988604e59967803bee91ec0d7af22a38.AppImage
 qt5ct: using qt5ct plugin
 [3] 85359
 [4] 85360
 [3]  - done       xscreensaver-command -exit
 (node:85314) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rename '/home/user/.config/appium-desktop/Settings-tmp' -> '/home/user/.config/appium-desktop/Settings'
 (node:85314) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rename '/home/user/.config/appium-desktop/Settings-tmp' -> '/home/user/.config/appium-desktop/Settings'
 (node:85314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:85314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:85314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 (node:85314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Especially this line bothers me: ` [3]  - done       xscreensaver-command -exit`
Why is that? Why appium-desktop supposed to conflict with xscreensaver or anyhow to interact with it?!

## Environment

- I am running Appium Desktop version 1.17.0.
- I am on (pick one):
    - Manjaro Linux

**Comment by KazuCocoa** [comment]
Thanks. I have no idea about the behaviour for now.
AppiumDesktop does not have a feature to handle screen saver, afaik.

I haven't used this app on Linux well (only a few times on Ubuntu), but no such issue then.
QT stuff in Electron is relevant? (just considering...)

**Comment by 3id010nCD** [comment]
[Screen video of this issue got worse](https://www.screencast.com/t/HRIteZu9CK4).  
Now it's just not started and keeps cloning/forking itself (notice how fast RAM is consumed on the video)

**Comment by 3id010nCD** [comment]
Apparently this is qt5ct plugin related bug, because CLI version of Appium works properly/correctly. This bug (when appium-desktop stopped working and started to clone itself) first time showed up after last Manjato update. Qt packages that were updated:
```
poppler-qt5-0.88.0-1
qt5-base-5.14.2-2  
qt5-location-5.14.2-2
qt5-webengine-5.14.2-3
qt5-webkit-5.212.0alpha4-4
```
[List of all installed Qt-packages and qt5ct package version](https://i.vgy.me/peljXL.jpg)

**Comment by KazuCocoa** [comment]
Ah, thanks for the investigation

**Comment by 3id010nCD** [comment]
how do I inspect Android application without appium-desktop's inspector?

**Comment by KazuCocoa** [comment]
So far, https://developer.android.com/studio/profile/hierarchy-viewer or Android Studio's layout viewer
