### ISSUE TITLE
Error: Failed to create a session.

### ISSUE THREAD

**Issue by ArjitRout** [appium/appium-desktop#1393]
@wdio/runner: Error: Failed to create a session.
An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-60356164-FA2E-4500-9B9C-528257DADBD6-iOS', device type id 'iOS' and runtime id 'com.apple.CoreSimulator.SimRuntime.iOS-13-4-1'. Reason: 'simctl error running 'create': Invalid device type: iOS'

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Please attach the full log.
It seems your machine does not have an ability to create a simulator, iOS 13.4.1 base.

**Comment by KazuCocoa** [comment]
I assume your environment has no iOS 13.4.1 instance. Updating your Xcode environment or set proper one may help
