### ISSUE TITLE
Missing folder in MAC

### ISSUE THREAD

**Issue by marcogrellagft** [appium/appium-desktop#1397]
I've installed Appium on my mac.
When i use command on terminal
$ cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent” 
i've error
-bash: cd: /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/cWebDriverAgent”: No such file or directory![image](https://user-images.githubusercontent.com/38132290/82458658-3fe6bb80-9ab7-11ea-8656-5d336f105c76.png).
The folder appium-xcuitest-driver doesn't exist

$ appium --version
1.17.1

I've missing something?

**Comment by KazuCocoa** [comment]
The missing path was expected since the file structure has been changed.
You probably can find `appium-webdriveragent` instead
