### ISSUE TITLE
Feature request: Add auto session connection if there is only one session 

### ISSUE THREAD

**Issue by slipy12** [appium/appium-desktop#140]
This could be auto if the input of the ID is empty, or another button under it for auto-attachment.

A lot of times is needed to quick access to the inspector in order to fix test errors.
This proposal is based in that I actually love the new desktop app but I'm still using the old one most of times.
I run appium server from CL in background so the session ID is invisible for me.

**Comment by dpgraham** [comment]
Interesting idea. Maybe in the 'Create New Session' dialog in the 'Attach to Existing Session' feature and the user can select an existing session instead of having to input the session ID?

**Comment by jlipps** [comment]
Yeah, probably we could poll /status to see if there are current sessions, or if it's running in appium desktop we'd know it already and could pre-populate?

**Comment by lavi-xu** [comment]
FYI.

On Appinpu.dot.app 1.5.3, there is a option called "prelaunch app", and it looks for existing session to start.

**Comment by jlipps** [comment]
@lavi-xu prelaunch no longer exists in appium. But you can attach to an existing session with a session id in the current app.

**Comment by lavi-xu** [comment]
I am not sure why we need this session option. From what I see we cannot create >=2 sessions for a application.

P.S.
I added few lines in selenium to either create new session if None of found, or use existed session for starting connection.

So my point is that there is NO need for session selection.

B.R.
