### ISSUE TITLE
v1.17.1 :: '/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java' not found on macOS Catalina v.10.15.4 :: Android v11::

### ISSUE THREAD

**Issue by mariushorvat** [appium/appium-desktop#1402]
## Appium Desktop

- I've run 1.15.1 version and the error is not present.
- It happens when I run on 1.17.1

## The problem

Original error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java' not found. Is it installed?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'KLM', ip: 'x', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_241

## Environment

- I am running Appium Desktop version _<1.17.1>_.
- I am on (pick one):
    - [x] Mac - macOS Catalina v.10.15.4
 
Is there currently a workaround this issues? Thanks!

**Comment by dhtien** [comment]
I solved this issue by removing JAVA_HOME config on start screen of appium desktop app, use default Java home instead. Hope this help

**Comment by mariushorvat** [comment]
> I solved this issue by removing JAVA_HOME config on start screen of appium desktop app, use default Java home instead. Hope this help

Thanks! This worked. Cheers!
