### ISSUE TITLE
Why appium automatically selects the first device in the emulator list instead of the devices specified by caps？

### ISSUE THREAD

**Issue by mabeijing** [appium/appium-desktop#1407]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

## The problem
Why appium automatically selects the first device in the emulator list instead of the devices specified by caps？

show log
[Appium] Appium v1.17.1 creating new AndroidUiautomator2Driver (v1.44.2) session
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "Android",
[BaseDriver]     "appium:platformVersion": "7.1.2",
[BaseDriver]     "appium:deviceName": "127.0.0.1:21553",
[BaseDriver]     "appium:uuid": "127.0.0.1:21553",
[BaseDriver]     "appium:appPackage": "com.tiema.zhwl_android",
[BaseDriver]     "appium:appActivity": "com.tiema.zhwl_android.MainActivity",
[BaseDriver]     "appium:chromedriverExecutableDir": "C:\\chormedriver\\2.38",
[BaseDriver]     "appium:noReset": true
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   uuid
[BaseDriver] Session created with session id: 938d9904-8cbc-47a2-a288-a59f95fa0c2b
[UiAutomator2] Starting 'com.tiema.zhwl_android' directly on the device
[ADB] Using 'adb.exe' from 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] Connected devices: [{"udid":"127.0.0.1:21513","state":"device"},{"udid":"127.0.0.1:21553","state":"device"}]
[AndroidDriver] Looking for a device with Android '7.1.2'
[ADB] Setting device id to 127.0.0.1:21513
[ADB] Getting device platform version
[ADB] Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:21513 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.1.2
[AndroidDriver] Using device: 127.0.0.1:21513
## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ * ] Windows
    - [ ] Linux

**Comment by mykola-mokhnach** [comment]
Because of 

> [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
> [BaseDriver] uuid

The correct cap name is `udid`
