### ISSUE TITLE
Sendkeys inserting characters which are not allowed to enter manually in edit box.

### ISSUE THREAD

**Issue by PrajeethAnandDev** [appium/appium-desktop#1409]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In some text fields user is not allowed to manually enter some characters, for example some field only accept number, when users click editbox, only number pad is displayed. So, not allowing the user to enter any other characters. But, using Sendkeys() we are able enter any values.
So, we cannot use this for field validations.

## Environment

- I am running Appium Desktop version _1.17.1_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Appium interacts with elements via UIAutomator2 or Espresso by Android framework.
So, I think Android framework works so. You can try out espresso driver, too.

e.g. 
uia2 types texts via https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#ACTION_SET_TEXT
espresso driver is via https://developer.android.com/reference/androidx/test/espresso/action/ViewActions#replaceText(java.lang.String)

If you want to verify the element's attribute (for example. if the element has `clickable`), you can get the value via https://appium.io/docs/en/commands/element/attributes/attribute/

**Comment by PrajeethAnandDev** [comment]
> Appium interacts with elements via UIAutomator2 or Espresso by Android framework.
> So, I think Android framework works so. You can try out espresso driver, too.
> 
> e.g.
> uia2 types texts via https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#ACTION_SET_TEXT
> espresso driver is via https://developer.android.com/reference/androidx/test/espresso/action/ViewActions#replaceText(java.lang.String)
> 
> If you want to verify the element's attribute (for example. if the element has `clickable`), you can get the value via https://appium.io/docs/en/commands/element/attributes/attribute/

This was working fine in older version of appium,
See the below example.
Consider contacts app where in mobile number field user is allowed to enter only numerical value and also only number pad is displayed(it's there is no option for user to manually enter the alphabets).
See the below image of Appium 1.10.0 when user uses sendkeys to send characters with number only numbers gets entered.
![1 10 1](https://user-images.githubusercontent.com/65868562/84034181-9d37a380-a9b7-11ea-86b4-4395962995d1.PNG)


See the below of Appium 1.17.1-1 when user uses sendkeys to send characters with number everything gets entered.
![1 17 1-1](https://user-images.githubusercontent.com/65868562/84034310-ca845180-a9b7-11ea-95d8-52af75b66050.PNG)

This is impacting large set of test cases which are related to field level validation, please help

**Comment by KazuCocoa** [comment]
This area?
The below was by 1.10.0 with UIA2. I could enter alphabet as sendKeys.
I wondered you meant UIA1 vs UIA2. If so, they were different technically. So the root cause is probably the Android framework side.

<img src=https://user-images.githubusercontent.com/5511591/84040177-447b0180-a9dd-11ea-97bc-248c4589fd8e.png width=300>

**Comment by PrajeethAnandDev** [comment]
> This area?
> The below was by Appium 1.10.0 with UIA2. I could enter alphabet as sendKeys.
> I wondered you meant UIA1 vs UIA2. If so, they were different technically. So the root cause was probably the Android framework side. (old uiautomator vs newer uiautomator)
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/5511591/84040177-447b0180-a9dd-11ea-97bc-248c4589fd8e.png">

May be you right, is there any workaround? So that I can simulate manual entry?

**Comment by PrajeethAnandDev** [comment]
> This area?
> The below was by Appium 1.10.0 with UIA2. I could enter alphabet as sendKeys.
> I wondered you meant UIA1 vs UIA2. If so, they were different technically. So the root cause was probably the Android framework side. (old uiautomator vs newer uiautomator)
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/5511591/84040177-447b0180-a9dd-11ea-97bc-248c4589fd8e.png">

Yes, this is related to uiautomator, this happens in UIA2, Can do something resolve this issue in future releases?

**Comment by KazuCocoa** [comment]
I have no idea for now since Appium refers to methods by Android. If we find methods to achieve it, we'll be able to add it, probably.
https://github.com/appium/appium-desktop/issues/1409#issuecomment-638559909

How about using espresso driver?

**Comment by KazuCocoa** [comment]
Close since this is not AD issue, but it is happy to find any workarounds...
