### ISSUE TITLE
Could not start session, when starting appium inspector 

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium-desktop#1410]
## Appium or Appium Desktop?

Unable to start inspector session for browser stack 
i had to downgrade again to .17.0 to make it work

## The problem

unable to start appium inspector due to the following error 

![appium](https://user-images.githubusercontent.com/32042806/83665088-443cc980-a5cb-11ea-82f3-ca0aecca0012.png)

## Environment

- I am running Appium Desktop version _<1.17.1>_.
- I am on (pick one):
    - [ ] Linux

**Comment by KazuCocoa** [comment]
> i had to downgrade again to .17.0 to make it work

Is this Appium Desktop version?
I thought something error returned from their appium instance.

**Comment by Amrkamel1** [comment]
> > i had to downgrade again to .17.0 to make it work
> 
> Is this Appium Desktop version?
> I thought something error returned from their appium instance.

Yes appium desk top version 1.17.1

Through error right away after u start inpection

It works on 1.17.0

**Comment by Amrkamel1** [comment]
Good that you figured it out will be waiting for the fix

**Comment by KazuCocoa** [comment]
@Amrkamel1 Could you try out https://github.com/appium/appium-desktop/releases/tag/v1.17.1-1 ?

**Comment by Amrkamel1** [comment]
> @Amrkamel1 Could you try out https://github.com/appium/appium-desktop/releases/tag/v1.17.1-1 ?

i will and get back to you

**Comment by KazuCocoa** [comment]
Let me know if the 1.17.1-1 binary also does not work

**Comment by Amrkamel1** [comment]
> Let me know if the 1.17.1-1 binary also does not work
it works fine now thanks

**Comment by JayasriPV** [comment]
I am using mac and installed latest version of appium desktop 1.17.1-1 still facing the issue

**Comment by 201905270246** [comment]
@KazuCocoa 

> Let me know if the 1.17.1-1 binary also does not work
yes, doesn't work.

mac 10.15
appium desktop 1.17.1-1

**Comment by KazuCocoa** [comment]
It is appreciated debug more since I tested with my personal account before. Then, it had no issue about HTTP or HTTPS. Maybe your case was a different situation.

**Comment by IsaacDempsey** [comment]
Updating to the latest version of appium desktop 1.17.1-1 fixed this issue for me also.

**Comment by MyatNoeWai** [comment]
I have the same error on Appium Desktop.

The problem
- unable to start appium inspector and get "could not start session" error.
- I use Appium Desktop version (1.17.1)
- Do I need Xcode to integrate headspin and Appium Desktop or
- Do I need to upload an app's sdk to Appium Desktop?
- Is there any link that explain details about how to integrate HeadSpin and Appium Desktop?

**Comment by KazuCocoa** [comment]
@MyatNoeWai
Basically, each vendor has their way, so you should ask them first.
Could you send an email to kazu@headspin.io ? I can help you.
