### ISSUE TITLE
Impossible to connect to TestObject from inspector

### ISSUE THREAD

**Issue by Biloleg** [appium/appium-desktop#1411]
Appium Desktop

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I get an error message: "Error Could not start session" when try to connect to TestObject from inspector.
Doesn't have any problem with connection on 1.17.0

## Environment

- I am running Appium Desktop version 1.17.1.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you try out https://github.com/appium/appium-desktop/releases/tag/v1.17.1-1 ?
I think the cause is the same as https://github.com/appium/appium-desktop/issues/1410
