### ISSUE TITLE
JavaScript error when starting with no internet

### ISSUE THREAD

**Issue by DGandalf** [appium/appium-desktop#1421]
Appium Desktop Problem

Only reproducable with Appium Desktop.

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I start the Appium Desktop without an Internet connection I allways get this error message during startup op the App.
"A JavaScript error occured in the main process
Uncaught exception: 
Range Error [ERR_OUT_OF_RANGE]: The value "err" is out of range. It must be a negative integer. Received 536870212
at Object.getSystemErrorName (util.js:220:11)
at exceptionWithHostPort(internal/errors.js:484:21)
at internalConnect(net.js:835:16)
at defaultTriggerAsyncIdScope(internal/async_hooks.js:301:12)
at GetAddrInfoReqWrap.emitLockup [as callback](net.js:978:9)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)

After clicking on OK Appium works well with no further error messages

## Environment

- I am running Appium Desktop version 17.1.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Please try out the latest appium-inspector https://github.com/appium/appium-inspector once...
