### ISSUE TITLE
Unable to run RF script in Appium 1.1.17-1

### ISSUE THREAD

**Issue by spartha1** [appium/appium-desktop#1423]
## The problem

Currently i am unable to run RF script in 1.1.17-1 Appium Desktop client

## Environment

* Appium version (or git revision) that exhibits the issue:1.1.17-1
* Last Appium version that did not exhibit the issue (if applicable):1.1.15
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): 12.16.3
* Npm or Yarn package manager:6.14.4
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Pixel 
* Appium CLI or Appium.app|exe:1.1.17-1
* Pycharm : PyCharm 2020.1.1 (Community Edition)

## Details

After updating to latest Appium Desktop Client, unable to run RF script via Pycharm
I downgraded Appium Desktop Cilent 1.1.15

## Link to Appium logs

Unable to generate log since server didn't start

**Comment by KazuCocoa** [comment]
Thanks, hm.
I could not reproduce it on macOS 10.15.5, so I probably cannot help.

You can build this app on your local as https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md#doing-development
If the issue is something your environment specific one, it may help

**Comment by spartha1** [comment]
Hi 
I wasn't able to install web driver into iphone
So i downgrade to 1.1.15
I was re-run the test

**Comment by KazuCocoa** [comment]
Do you mean you could lunch Appium server unlike https://github.com/appium/appium-desktop/issues/1423#issuecomment-642090857 , but failed the installation process in WebDriverAgent build?
So, the issue changed.

**Comment by spartha1** [comment]
Yes correct
1.1.15 I was able to install webdriveragent from /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent
I don't see appium-webdriveragent folder in 1.17.1-1

**Comment by KazuCocoa** [comment]
Okay, then, please create a new issue with the full server log.

btw, the webdriveragent directory may be in:
```
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/
```

**Comment by spartha1** [comment]
@KazuCocoa it wasn't there when i upgraded to 1.1.17-1

**Comment by KazuCocoa** [comment]
hm, I could not reproduce it on macOS 10.14 and 10.15 on my local.
How about removing the old one once and move the new package from `.dmg`?
I confirmed the directory was in the Appium.app 1.17.1-1 package in `.dmg`. So, something happened when you upgrade the package, I guess.
