### ISSUE TITLE
Unable to inspect UWP app elements using Appium Desktop - 1.17.1 Inspector

### ISSUE THREAD

**Issue by krevathi1912** [appium/appium-desktop#1424]
## The problem

UWP app elements are not recognized by Inspector in Appium Desktop-1.17.1. Launched the Calculator app using appium desktop, tried to inspect the elements, but unable to click on elements in the inspector

## Environment

Appium Desktop - 1.17.1
OS: Windows 10

**Comment by KazuCocoa** [comment]
Could you attach the full log as GIST?
I think some action endpoints such as click to an element/coordinate by AD did not work on WinAppDriver layer.

**Comment by pattanayakpurna189** [comment]
Hi Currently we are also using below environment, and facing a issue like appium is unable to display all the nodes in the app source code. meaning it is only able to display the parent nodes most of the cases its not able to display the child nodes in the app source code, again when we had a discusion with the developer we came to know about this issue. Please look in to this.
Appium Desktop - 1.17.1
OS: Windows 10

**Comment by ova2** [comment]
We have the same problem with the Appium v1.18.3. If we load an ipa file from the file system, is everything ok - we can inspect elements. But if we load the app from the BrowserStack, no child elements are selected and highlighted. I can only see the top elements. It seems to be the wrong structure / wrong page.

The same, if we access the app on BrowserStack programmatically by java-client. If I call `getPageSource()` by Appium driver, the same wrong page structure with only top level elements is shown. Is it a big in the Appium?

Here some screenshots.

![appium_browser_stack1](https://user-images.githubusercontent.com/767334/102673414-59a6c900-4194-11eb-8e7d-5f1e90be67dd.PNG)
![appium_browser_stack2](https://user-images.githubusercontent.com/767334/102673423-60354080-4194-11eb-8af4-90d3490dc34e.PNG)

Related (probably the same) issue: https://github.com/appium/appium-desktop/issues/1525

**Comment by KazuCocoa** [comment]
Probably this was WAD related thing
