### ISSUE TITLE
There is impossible to send text or clear value in the ExtendedTextBox 

### ISSUE THREAD

**Issue by erohinalexey** [appium/appium-desktop#1425]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

There is impossible to send text or clear value in the ExtendedTextBox.

There are few fields in our application with ExtendedTextBox class type. It looks like as usual text field, but performs some specific functions.
ClassName: ExtendedTextBox
ControlType: ControlType.Custom

This ExtendedTextBox contains internal form with not defined ClassName.
I can successfully find both of them:
External form:
`winDriver.findElementByAccessibilityId("formName");`
Internal form:
`winDriver.findElement(By.xpath(".//*[@AutomationId='#formName']//*[@ClassName='']"))`

But, I cannot use methods senKeys() or clear() for type or clear text.
How can work with ExtendedTextBox?

[log.txt](https://github.com/appium/appium-desktop/files/4771173/log.txt)

## Environment

- I am running Appium Desktop version v1.17.1-1.
- I am on (pick one):
    - [ ] Mac
    - [+] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you create an issue in https://github.com/Microsoft/WinAppDriver ?
It looks Windows or WinAppDriver side matter
