### ISSUE TITLE
Appium version string breaks most package automation in Python PEP-0440

### ISSUE THREAD

**Issue by Honestpuck** [appium/appium-desktop#1428]
## The problem

On June 9 Appium released a version of Appium for the Mac that had a version string of "1.17.1-1" and that version string causes problems with package automation systems, principally AutoPkg, which fails with "Processor: PkgCreator: Error: Invalid version component "1-1"

## Environment

* Appium version: 1.17.1-1
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: macOS 10.15.6

## Details

If you use automation to build packages you rely on software behaving in reliable and standard ways. The latest version of Appium for Mac uses a highly non-standard way of describing it's version by adding "-1" to the end rather than making it "1.17.2" or "1.17.1.1", either of which would not break established practice.

**Comment by KazuCocoa** [comment]
I think you're talking about AppiumDesktop.
We did not want to bump the patch version to 1.7.2 to fit Appium CLI versioning, so added `-1` like `-beta` we did before ( It's probably handled as pre stuff https://semver.org/ )

Node semver library parsed as below. 1.17.1.1 did not work.

What version system are you using?

```javascript
> s.parse('1.17.1-1')
SemVer {
  options: { loose: false, includePrerelease: false },
  loose: false,
  includePrerelease: false,
  raw: '1.17.1-1',
  major: 1,
  minor: 17,
  patch: 1,
  prerelease: [ 1 ],
  build: [],
  version: '1.17.1-1' }
```

```python
 semver.parse('1.17.1-1')
{'major': 1, 'prerelease': '1', 'build': None, 'minor': 17, 'patch': 1}
```

```ruby
v = Gem::Version.new('1.17.1-1')
=> Gem::Version.new("1.17.1.pre.1")
```

**Comment by Honestpuck** [comment]
It appears the software I'm using is assuming PEP-0440 compliance rather than semantic versioning. I'm still trying to find the exact call that gives the error.

**Comment by KazuCocoa** [comment]
Ah, Python PEP-0440..
Appium (especially NodeJS based modules) follows SemVer https://github.com/appium/appium/blob/4785026e65cd5b96929895b7d1cd5f1e2cff0b32/docs/en/contributing-to-appium/developers-overview.md#releasing , so it could happen...

**Comment by Honestpuck** [comment]
I'm also chasing it from the other end to get the package building software to work with SemVer.

I just spent an hour making my code work properly with it so that's done. :)
