### ISSUE TITLE
iOS Safari testing setup

### ISSUE THREAD

**Issue by automationIntern** [appium/appium-desktop#143]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I've been running tests on real iOS devices using Appium 1.6.4 for a bit now, and am somewhat comfortable running the server. I'm trying to run browser tests on iOS 10, and was curious what kind of set up needs to happen in order to run tests on Safari using the new appium-desktop client? I've already installed SafariLauncher on the devices I intend to use, web driver agent and ios debug proxy on the machine I'm running the server on. 

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Since Appium Desktop does not support webview contexts or html source, there's really little point in using the inspector for safari. If you want to inspect a website in safari, just use the debug tools by connecting from safari on your desktop.
