### ISSUE TITLE
win10双击不显示窗口

### ISSUE THREAD

**Issue by hello555word** [appium/appium-desktop#1436]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you give us more information such as the app version etc

**Comment by hello555word** [comment]
所有的appiumdesktop都试过了，都双击没有服务窗口，我的电脑是win10，64位，英特尔4带，8g内存，，我在ctrl+alt+. 服务任务栏显示他在运行，就是没有窗口

**Comment by hello555word** [comment]
win10,64位，8G，这所有的版本都不弹出服务窗口

**Comment by KazuCocoa** [comment]
Thanks, but hm, it seems strange.
I was able to run this app on Windows 10 machine.
Do you have a chance to render directly?
I mean follow https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md#renderer and try to render.

**Comment by KevinChan168** [comment]
牛逼，中文都能看懂

**Comment by KazuCocoa** [comment]
Please try out the latest https://github.com/appium/appium-inspector
