### ISSUE TITLE
Crashed and started over

### ISSUE THREAD

**Issue by bkuhn247** [appium/appium-desktop#1437]
While listening to perspectives of Randy Musallam after the first question I answered yes using my voice. Once I answered the program crashed to the home screen and then when I started playing the audio again I kept lowering my volume to 0 no matter how many times I turned it up

**Comment by KazuCocoa** [comment]
Please fill the issue template in

**Comment by KazuCocoa** [comment]
Is this iOS simulator or Android emulator stuff?
AD itself does not have such audio or voice stuff, but Simulators/Emulators may affect audio etc. Then, you need to modify their settings by yourself.
