### ISSUE TITLE
Unable to launch the iOS app in iPhone via appium-desktop

### ISSUE THREAD

**Issue by Arjunkalidas** [appium/appium-desktop#144]
I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am unable to launch the app in my iPhone through Appium-desktop. Please find the gist link below.
I have ideviceinstaller installed and it is working fine. I am able to install the app with ideviceinstaller and ios-deploy tool as well. But it fails with appium.

## Environment

- I am running Appium Desktop version _1.0.0_.
- I am on (pick one):
    - [ ] Mac 10.12.3

Log:
https://gist.github.com/Arjunkalidas/050dc299d76e47fc62e47ee34ab13667

**Comment by WaFeIS7** [comment]
I have the problem(

**Comment by jlipps** [comment]
@Arjunkalidas does it work in Appium (when you're not using Appium Desktop)?

**Comment by jlipps** [comment]
If so, can you provide the successful log as well

**Comment by dilsreccse** [comment]
@jlipps Do we need WebDriverAgent in Appium Desktop version 1.0.0 to automate real device ?

**Comment by Arjunkalidas** [comment]
Hi @jlipps I figured out the reason, I was able to launch the app from my IDE via code, by adding two params as Desired Capabilities:

capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("xcodeOrgId", "***********");

Only when I added these capabilities, was I able to launch both via code and Appium-desktop.
This article helped me actually - https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md 

So does this imply, you cannot automate an app downloaded from AppStore directly? Because our app is in AppStore and I am trying out downloading the app and picking the ipa from iTunes library in Mac and using for Appium. Can't I download a random app from Appstore and sign it with my developer provisioning profile and use for Appium?

**Comment by Arjunkalidas** [comment]
@jlipps can you please respond to my comment. Thanks in advance!

**Comment by imurchie** [comment]
You cannot test an app downloaded from the iOS/Apple app store. Apple requires that the app being automated be signed with a developer certificate.

The main force of the philosophy is that there is nothing compiled into the app, no instrumentation of the app under test, no moving parts added to it in order to automate.

If Apple would ever make testing a full-fledged part of the app development workflow, then we could move farther forward in _actually_ testing the app users will use.

**Comment by Arjunkalidas** [comment]
@imurchie Thank you for your response. I understand it now.
