### ISSUE TITLE
Start Appium server headless

### ISSUE THREAD

**Issue by beutlich** [appium/appium-desktop#1441]
## Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I need an option to start Appium Server directly via Appium Desktop without the requirement to press the "Start Server" button of the Appium Desktop GUI. Basically, it is this old issue reported at https://discuss.appium.io/t/how-to-launch-windows-appium-1-6-4-server-from-command-line/16804. I do not have NodeJS installed.

## Environment

- I am running Appium Desktop version 1.17.0.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
So far, Appium Desktop is designed to launch via GUI.
We're happy to have a PR, but basically we'd recommend using appium via npm for non-gui one.

**Comment by beutlich** [comment]
Thanks for replying.

> We're happy to have a PR

Can you  please share which PR. Thanks again.

**Comment by jlipps** [comment]
Yes, if your goal is to launch appium from the command line, then just use the command line version of Appium. You could probably find a way to use docker or otherwise bundle node together into a single executable if you wanted.

**Comment by KazuCocoa** [comment]
I mean we're happy to review pr meanwhile our basic design in this repository is for GUI use.
