### ISSUE TITLE
v1.17.1-1 causes IOS Native Tablet app to perform slowly and sometime app freezes occur

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium-desktop#1442]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Issue is specific to IOS Tablet
v1.17.1-1 causes IOS Native Tablet app to perform slowly and sometime app freezes occur

## Environment
MACOS Catilina 10.15.4 
IOS : 12.1
Appium Desktop v1.17.1-1

- I am running Appium Desktop version _<1.17.1-1>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you share the full Appium server log?
With `showXcodeLog` and `showIOSLog` capability also are also helpful.

**Comment by yadavsvmx** [comment]
[1.17.1 Tablet issues appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4849625/1.17.1.Tablet.issues.appium-server-logs.txt)

Added logs @KazuCocoa

**Comment by yadavsvmx** [comment]
@KazuCocoa most common issue seems to be this too.

 org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

**Comment by KazuCocoa** [comment]
Thanks.
Could you tell us which action was typically slow?
I found tap by 'perform', but they seemed had no slowness.
`--log-timestamp` as Appium server's argument is also helpful to check the timestamp.


Socket hang up also need to take a look more.
Potentially, if it did not happen on iOS, the cause is probably XCTest framework/Xcodebuild side.

**Comment by yadavsvmx** [comment]
The first action after the page is fully rendered by the native app, at that point only on the tablet it frezzes.

One observation is, if I manually tap else where it begins to work before the first action, else if I don't do this no action is performed via appium click(). As a work around i use a tap() based on some random coordinates before the first click() is called

**Comment by KazuCocoa** [comment]
Then, I assume the root cause of the tap is XCTest framework.
Internally, Appium calls XCTest framework's API. So, XCTest framework may have an issue to handle the case. Only Apple can fix it. Appium providers coordinate based tap action, so it could be a workaround as you did.
