### ISSUE TITLE
how to clean uninstall appium desktop

### ISSUE THREAD

**Issue by ps1logi** [appium/appium-desktop#1445]
## Appium Desktop?

How to do clean uninstallation of appium desktop with it dependency in mac 

## Environment

- I am running Appium Desktop version _1.15.1_.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
`/Application/Appium.app` and `~/Library/Caches/io.appium.desktop*` (if you want to remove cache, too)
