### ISSUE TITLE
Cannot start Appium Inspector Session - {"Error":"InvalidService","Request":"StartService","Service":"com.apple.mobile.installation_proxy"}

### ISSUE THREAD

**Issue by baopn97** [appium/appium-desktop#1447]
## The problem
This issue is occured when i'm using semi-tethered device, not happend on non-jailbreak device. 

## Environment

- I am running Appium Desktop version v1.17.1
- I am on (pick one):
    - [X] [Mac]
- Mac OS 10.15.3
- Appium desired capabilities:
```
{
  "platformVersion": "13.3.1",
  "deviceName": "iPhone 5 SE",
  "platformName": "iOS",
  "bundleId": "**",
  "udid": "**",
  "automationName": "XCUITest"
}

```
- Device: iPhone 5 SE semi-tethered (jailbreak)
- Appium logs: 
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4874458/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
Could you set `showXcodeLog` and `showIOSLog` capabilities to get the log and share it?

**Comment by baopn97** [comment]
> showIOSLog
Can you please verify this?
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4874648/appium-server-logs.txt)

**Comment by baopn97** [comment]
@KazuCocoa 
Here's the log after adding `showXcodeLog` and `showIOSLog` parameters to `true`
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4874653/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
I haven't seen the error, but it looks `com.apple.mobile.installation_proxy` did not work? on your device.
Probably reboot the device or re-connect the device to the machine may help.

Appium needs the service to manage apps over usbmuxd. In general, the service is available to communicate with iTunes.
Can your device work with iTunes, xcodebuild etc?

```
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1593939334423 (15:55:34 GMT+0700 (Indochina Time))[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE trustd[124] <Notice>: cert[0]: MissingIntermediate =(leaf)[force]> 0
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE trustd[124] <Notice>: cert[0]: NonEmptySubject =(path)[]> 0
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE lockdownd[78] <Notice>: handle_start_service: <private>
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE lockdownd[78] <Notice>: MAEGate_GetBrickState: <private>
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE lockdownd[78] <Notice>: spawn_service_agent: <private>
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE lockdownd[78] <Notice>: spawn_and_handle_checkin: <private>
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE lockdownd[78] <Notice>: handle_start_service: <private>
[info] [35m[IOSDeviceLog][39m Jul  5 15:55:34 iPhone-5-SE lockdownd[78] <Notice>: set_response_error: <private>
[error] [35m[XCUITest][39m {}
[info] [35m[DevCon Factory][39m Releasing connections for 8aa396f6fd4b0271539e7dd95194c4e083b3319d device on any port number
[info] [35m[DevCon Factory][39m No cached connections have been found
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1593939334724 (15:55:34 GMT+0700 (Indochina Time))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.mobile.installation_proxy"}
[debug] [35m[MJSONWP][39m     at Lockdown.startService (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-device/lib/lockdown/
```

**Comment by baopn97** [comment]
Hi @KazuCocoa ,
I've tried to connect with Itunes and device works fine, buy when i open Xcode => Window => Devices and Simulators, Xcode show that "Failed to start remote service on device."
Is this because of this device is "bypass icloud" or "semi-tethered" ? 

Full logs:
Details

Failed to start remote service on device.
Domain: com.apple.dtdevicekit
Code: 811
Recovery Suggestion: Please check your connection to your device.
User Info: {
    DVTRadarComponentKey = 261622;
}
--
The service could not be started on the device.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653091
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800005D)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012475881a DTDKCreateNSErrorFromAMDErrorCode + 233
	1   DTDeviceKitBase                     0x000000012476a161 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 564
	2   DTDeviceKitBase                     0x0000000124769829 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	3   DTDeviceKitBase                     0x000000012475adf9 __DTDKExecuteInSession_block_invoke_2 + 35
	4   DTDeviceKitBase                     0x000000012475a209 __DTDKExecuteWithConnection_block_invoke_2 + 473
	5   DTDeviceKitBase                     0x000000012475a007 __DTDKExecuteWithConnection_block_invoke + 106
	6   libdispatch.dylib                   0x00007fff6652750e _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007fff66533567 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	8   DVTFoundation                       0x000000010a8c2368 DVTDispatchBarrierSync + 208
	9   DVTFoundation                       0x000000010a898cc3 -[DVTDispatchLock performLockedBlock:] + 64
	10  DTDeviceKitBase                     0x0000000124759f08 DTDKExecuteWithConnection + 226
	11  DTDeviceKitBase                     0x000000012475ac63 DTDKExecuteInSession + 376
	12  DTDeviceKitBase                     0x000000012476966a __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 131
	13  DVTFoundation                       0x000000010a8bf7f4 __DVT_CALLING_CLIENT_BLOCK__ + 7
	14  DVTFoundation                       0x000000010a8c1436 __DVTDispatchAsync_block_invoke + 1194
	15  libdispatch.dylib                   0x00007fff66526583 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff6652750e _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff6652cace _dispatch_lane_serial_drain + 597
	18  libdispatch.dylib                   0x00007fff6652d485 _dispatch_lane_invoke + 414
	19  libdispatch.dylib                   0x00007fff66536a9e _dispatch_workloop_worker_thread + 598
	20  libsystem_pthread.dylib             0x00007fff667816fc _pthread_wqthread + 290
	21  libsystem_pthread.dylib             0x00007fff66780827 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.3 (Build 19D76)
Xcode 11.5 (16139)

**Comment by KazuCocoa** [comment]
> Xcode show that "Failed to start remote service on device."

Hm, it could be the reason.

> Is this because of this device is "bypass icloud" or "semi-tethered" ?

I haven't applied jailbreak, but they could be...
Both signed in and signed out from iCloud cases had no issue on my machine.
macOS and Xcode versions were the same.

**Comment by baopn97** [comment]
@KazuCocoa  tested on iPhone 5 SE ios 12.2 and Xcode works like a charm, probably noted as Appium cannot work with Jaibreak  device?

**Comment by KazuCocoa** [comment]
Thanks for your confirmation.

Yes, it makes sense. Will address it in https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/
