### ISSUE TITLE
Another issue regarding opening app

### ISSUE THREAD

**Issue by jbuoncri1** [appium/appium-desktop#145]
## Appium or Appium Desktop?
Appium Desktop

## The problem

Whenever I try and start my the desktop app I get this error pop up: 
_An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1_

## Environment

- I am running Appium Desktop version 1.0.0 desktop app.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

Logs: https://gist.github.com/jbuoncri1/0cc0ceb1f5a97c01bae218883de0142e

**Comment by imurchie** [comment]
```
[XCUITest] Failed to write to /private/var/folders/b0/wf1ymj0j34dfmmwxftr6vmz80000gp/T/AppTranslocation/91BFE2B0-50F2-40E3-9B1D-D1F76AE43AE3/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/b0/wf1ymj0j34dfmmwxftr6vmz80000gp/T/AppTranslocation/91BFE2B0-50F2-40E3-9B1D-D1F76AE43AE3/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7ffe00e5f380 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}
```

Are you running the app from the `dmg`?

**Comment by jbuoncri1** [comment]
Thank you @imurchie. I was using the direct `app` file from the site, but I downloaded the `dmg` file instead and installed it. Working now!

**Comment by ameyparab85** [comment]
move Appium.app to Applications if you on a Mac
