### ISSUE TITLE
the element cannot send keys and tap

### ISSUE THREAD

**Issue by MarcSteven** [appium/appium-desktop#1463]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I use it to inspect the element about iOS clients, but at present, I always met the weird issue.
The element cannot interact, and some elements cannot send keys to interact,

## Environment
Mac os

- I am running Appium Desktop version _<1.17.1>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by MarcSteven** [comment]
The issue looks like that as below:
[element is not invalid](https://sqa.stackexchange.com/questions/34992/getting-invalid-element-state-exception)
[invalid element state](https://stackoverflow.com/questions/25177263/selenium-invalid-element-state-element-is-not-currently-interactable-and-may-no)

**Comment by KazuCocoa** [comment]
Could the element accept command by other bindings?
I wondered other bindings also could not interest with them.

**Comment by MarcSteven** [comment]
I tried, but failed to make it work @KazuCocoa

**Comment by KazuCocoa** [comment]
Then, could you share the page_source and the appium log with `showiOSLog` capability?
It seems XCTest layer by Apple had an issue. Then, nothing can do in Appium side.

**Comment by MarcSteven** [comment]
Possible,  closed it
