### ISSUE TITLE
Cannot read lengthy xpath/resource-id or Cannot resize the window

### ISSUE THREAD

**Issue by alphachaithaya** [appium/appium-desktop#1464]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Whenever I inspect any element using appium inspector the length element locators go outside the bounds of the appium screen, at this time I can't read full locator. If I try to resize the window that also not happening

## Environment

- I am running Appium Desktop version _<1.15.1>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [x] Linux

**Comment by KazuCocoa** [comment]
Do you mean you cannot scroll horizontally?
The scroll worked on Windows and macOS, but I haven't tested well on Linux. So, potentially it could happen if electron had such scroll issue on Linux.

**Comment by alphachaithaya** [comment]
I updated the Appium App Image from 1.15.1 to 1.17.1 and now the horizontal scroll working fine. I might be the problem with the Linux environment that I am using
