### ISSUE TITLE
Can't install Appium desktop on win10

### ISSUE THREAD

**Issue by KurganovID** [appium/appium-desktop#1465]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [х] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I can't install appium desktop. After downloading exe file, when I trying to start it, nothing happen. 

## Environment

- I am running Appium Desktop version _<1.17.1-1>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you share your machine info more?
For now, 32 bit machine does not work. (1.18.0 will provides an installer for 32 bit env)

**Comment by KurganovID** [comment]
Windows 10 Home x64.

**Comment by KurganovID** [comment]
Solve this issue. Run installer in capability mode with win8
