### ISSUE TITLE
 Failed  to launch app :Original error: Activity name '.XX' used to start the app doesn't exist or cannot be launched! 

### ISSUE THREAD

**Issue by sunxiaowen** [appium/appium-desktop#1469]
##Appium Desktop

## The problem
Error content：
An unknown server-side error occurred while processing the command. Original error: Cannot start the '[package name]' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.[launchable-activity]' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
Comment:
I'm sure that the package name and launchable-activity are right，and i have used adb command to start the app successfully

## Environment
- I am running Appium Desktop version _1.17.1-1
- I am on Mac10.14.6 Mojave

**Comment by KazuCocoa** [comment]
- Did you set appWaitActivity properly? Some apps show splash screen (for example) after launching `.Main` activity. If your app has such a trick, the `appWaitActivity` may help.
- How about adding `appWaitForLaunch: false` capability? By default Appium set `-W` flag, but some apps do not become ready for Android framework by the flag.

The full appium server log may help to understand the cause.

**Comment by sunxiaowen** [comment]
Thanks a lot! i add the two parameter ,try many times（it's strange） ,at last ,successed
