### ISSUE TITLE
Appium desktop is not showing newly installed appium version

### ISSUE THREAD

**Issue by arrk-shch** [appium/appium-desktop#147]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium desktop is not showing newly installed appium version (Appium v1.6.5-beta)
I have updated appium from command prompt. If I execute 'appium' command from command prompt then appium server starts with correct version
[Appium] Welcome to Appium v1.6.5-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

But when I launch appium desktop then it show button as "Start server v1.6.4". If I click on it then 
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

## Environment

- I am running Appium Desktop version appium-desktop-1.0.0.
- I am on (pick one):
    - [x] Mac

**Comment by dpgraham** [comment]
Appium Desktop doesn't use the globally installed version of appium, it bundles appium with the UI, hence the discrepancy.

If you wish to use 1.6.5-beta with Appium Desktop, follow the directions provided in this thread: https://github.com/appium/appium-desktop/issues/116
