### ISSUE TITLE
appium-uiautomator2-server-debug-androidTest.apk fails to install on my Android OS 10 device with stream install

### ISSUE THREAD

**Issue by DanielDanielyan** [appium/appium-desktop#1478]
## Appium or Appium Desktop?

I am using Appium Desktop
 
## The problem
appium-uiautomator2-server-debug-androidTest.apk fails to install on my Android OS 10 device seems to be related to streamed Installs, other OS versions work fine for me

Notice here the appium-uiautomator2-server-v4.5.5.apk gets installed without issue
`
[UiAutomator2] Server packages are going to be (re)installed
[ADB] Running '/<PATH>/Library/Android/sdk/platform-tools/adb -P <PORT> -s <Device-ID> features'
[ADB] The application at '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running '/<PATH>/Library/Android/sdk/platform-tools/adb -P <PORT> -s <Device-ID> install -r /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.5.5.apk'
[ADB] The installation of 'appium-uiautomator2-server-v4.5.5.apk' took 1347ms
[ADB] Install command stdout: Performing Streamed Install
[ADB] Success
`

But when it tries to install the appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
 it fails because of stream install

`
[ADB] The application at '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running '/<PATH>/Library/Android/sdk/platform-tools/adb -P <PORT> -s <Device-ID> install -r /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[ADB] The installation of 'appium-uiautomator2-server-debug-androidTest.apk' took 43ms
[ADB] Install command stdout: Serving...
[ADB] Performing Incremental Install
[ADB] Unknown command: install-incremental
[ADB] Install command complete in 23 ms
`

 because of that Appium eventually fails out after it cannot run io.appium.uiautomator2.server.test
`
[UiAutomator2] Unable to find instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner': The instrumentation target is not listed by Package Manager
UiAutomator2] Available targets:
[UiAutomator2]     com.genius.android/androidx.test.runner.AndroidJUnitRunner (target=com.genius.android)
[UiAutomator2]     com.microsoft.office.officehubhl/android.test.InstrumentationTestRunner (target=com.microsoft.office.msohttp.tests)
`

## Environment

These are the Capabilities im using 
{
  "platformName": "Android",
  "replace": false,
  "noIncremental": true,
  "platformVersion": "10",
  "deviceName": "S10",
  "automationName": "UiAutomator2",
  "app": "App Name"
}

App Version: 1.17.1-1
Electron: 7.2.4
Node.js: 12.8.1
Mac: 10.15.5

**Comment by KazuCocoa** [comment]
Appium 1.18.0 has https://github.com/appium/appium-uiautomator2-driver/pull/399
Probably it could solve it..

You can try it out with https://github.com/appium/appium-desktop/releases/tag/v1.18.0-beta.1 or https://github.com/appium/appium-desktop#connect-to-local-appium-server with Appium 1.18.0

**Comment by DanielDanielyan** [comment]
@KazuCocoa - that worked TY
