### ISSUE TITLE
FR: Middle pane in inspector cannot be enlarged(gracefully) or scrolled horizontally

### ISSUE THREAD

**Issue by dem0n0cracy** [appium/appium-desktop#148]
## Appium Desktop - Feature Request (FR)
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The middle Pane of Appium-desktop inspector can have many elements. I've already said we need a collapse all and open all, but we also need a horizontal scroller so that we can see elemnts that go off the page. One way to fix this is to simply enlarge the appium inspector screen, but this causes the selected box to not update based on the new size of the appium inspector screen. Other ways to solve it is to lock the size of the simulator on the left, and lock the size of the Selected Element on the right, but make the middle pane bigger as you enlarge the inspector. But mostly, a horizontal scroller on the bottom would be fantastic. 
![inspectorresizebugs](https://cloud.githubusercontent.com/assets/5766824/25139311/e127e412-242a-11e7-9627-e6effcf989cf.gif)

## Environment
- I am running Appium Desktop version 1.0.0
- I am on (pick one):
    - [x ] Mac - Sierra 10.12.4

**Comment by dpgraham** [comment]
Agreed, this needs to be fixed. Added it to our backlog now

**Comment by jlipps** [comment]
There is actually a horizontal scrollbar, it's just invisible. Right now it's only usable via a horizontal swipe on a trackpad (which may not be available on all systems, or with an attached mouse for example).

**Comment by dpgraham** [comment]
I think we should make it so that it flows to the next line instead of being clipped (that's what Chrome DevTools does).

**Comment by jlipps** [comment]
Yeah I like that idea.

**Comment by dem0n0cracy** [comment]
Ah, yes I use a mouse almost always, but just confirmed that it does indeed work with the trackpad. I would really like it though if you could stretch out the inspector and lock the size of the simulator view.
