### ISSUE TITLE
unable to recognize wkwebview element by appium injector

### ISSUE THREAD

**Issue by 13817458995** [appium/appium-desktop#1485]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13.5.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:
 
There is no related log.
![WechatIMG6](https://user-images.githubusercontent.com/32864246/88196097-62da4b00-cc73-11ea-95c7-bfa809091d89.jpeg)

**Comment by KazuCocoa** [comment]
How about the result of page source command directly?
I mean the result of http://appium.io/docs/en/commands/session/source/

**Comment by 13817458995** [comment]
Same as appium inspector

Best Regards,
Cecelia Zhang

**Comment by 13817458995** [comment]
Pagesource:

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name=“XXX 2.0-SIT" label=“XXX 2.0-SIT" enabled="true" visible="true" x="0" y="0" width="834" height="1112">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="1112" height="834">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1112" height="834">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="1112" height="20"/>
      <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" visible="true" x="0" y="0" width="1112" height="834">
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="98%" name="垂直滚动条, 3页" label="垂直滚动条, 3页" enabled="true" visible="true" x="1079" y="20" width="30" height="814"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="0%" name="水平滚动条, 1页" label="水平滚动条, 1页" enabled="true" visible="true" x="0" y="801" width="1112" height="30"/>
      </XCUIElementTypeScrollView>
      <XCUIElementTypeWebView type="XCUIElementTypeWebView" enabled="true" visible="true" x="0" y="20" width="1112" height="814">
        <XCUIElementTypeWebView type="XCUIElementTypeWebView" enabled="true" visible="true" x="0" y="20" width="1112" height="814">
          <XCUIElementTypeWebView type="XCUIElementTypeWebView" enabled="true" visible="false" x="0" y="20" width="1112" height="814"/>
          <XCUIElementTypeOther type="XCUIElementTypeOther" value="0%" name="垂直滚动条, 1页" label="垂直滚动条, 1页" enabled="true" visible="false" x="1079" y="20" width="30" height="814"/>
          <XCUIElementTypeOther type="XCUIElementTypeOther" value="0%" name="水平滚动条, 1页" label="水平滚动条, 1页" enabled="true" visible="true" x="0" y="801" width="1112" height="30"/>
        </XCUIElementTypeWebView>
      </XCUIElementTypeWebView>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="1112" height="834">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="1112" height="834">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="1112" height="834"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="834" width="1112" height="353"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

**Comment by 13817458995** [comment]
The issue is not happened in iOS 12.4.6

**Comment by KazuCocoa** [comment]
Then, please try out 1.17.1 once.

The result of element tree strongly depends on iOS and XCTest framework versions by Apple.
So, if the issue on iOS 13 happened with Appium 1.17.1 with both native and webview contexts, potentially Apple's XCTest or Safari inspector have issues

**Comment by 13817458995** [comment]
Same on 1.17.1. And unable to switch to web view context in release package

Best Regards,
Cecelia Zhang

**Comment by KazuCocoa** [comment]
Can the WebView access via macOS Safari's inspector?
If no, I don't think Appium access to the element, unfortunately, since Appium communicates with WebView over Web inspector. Only Apple knows the differences between iOS 13 and 12, so no one can say their behaviour is the same.

**Comment by KazuCocoa** [comment]
If the WebView was not accessible via macOS Safar's inspector, technically cannot access the WebView via web context.
e.g. https://github.com/react-native-webview/react-native-webview/blob/master/docs/Debugging.md
Sometimes XCTest framework can recognise Web elements, but it depends on App.
