### ISSUE TITLE
Where is the search field for now?

### ISSUE THREAD

**Issue by zhen639** [appium/appium-desktop#149]
## The problem
Is there no search field anymore? In the 0.x.x version, I can search element by name/tag/etc. However, hardly find that functionality for now...

## Environment

- I am running Appium Desktop version _<1.0.0>_.
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
This is a different application from what you're talking about. The old Appium UI is unsupported, and this UI doesn't currently have a 'Search' feature.

We'll look into adding that as a feature in the future though. A few people have asked for it.
