### ISSUE TITLE
Crash observed when click of elemnet of screenshot in inspector 

### ISSUE THREAD

**Issue by DarshanKamble** [appium/appium-desktop#1491]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When i am try to select element from screenshot of inspector that time its crashed .

## Environment

- I am running Appium Desktop version _<1.18.0 beat1>_.
- I am on (pick one):
    - [ ] Mac
    - [YES] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you try out the latest master?
A few fixes in current master after beta1

**Comment by KazuCocoa** [comment]
Please try out latest https://github.com/appium/appium-inspector
