### ISSUE TITLE
PATH selection for APP while setting desired capabilities its not working from 1.16.0/1.17.0/1.18.0 beat1

### ISSUE THREAD

**Issue by DarshanKamble** [appium/appium-desktop#1492]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

PATH selection for APP while setting desired capabilities its not working from 1.16.0/1.17.0/1.18.0 beat1

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Do you mean `app` capability as a local path?
Could you share the full server log?

**Comment by yuowo** [comment]
In Appium Desktop, when the Desired Capabilities add type is filepath, click value and select the file and open it, but it does not seem to take effect
macOS：10.15.6

```
[Appium] Welcome to Appium v1.18.0
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40
[HTTP] 
```

**Comment by KazuCocoa** [comment]
I see. probably `filpath` item does not work

**Comment by DarshanKamble** [comment]
YES, its observed on both window system and Mac also
For More Reference  screenshots attached


*Thanks,*
*Darshan Kamble*
Software Developer
Balaji Software
+91-22-42642018
darshan.kamble@balajisoftware.com
