### ISSUE TITLE
CRASH on Firebase click pointer | iOS ubuntu 18.04  

### ISSUE THREAD

**Issue by vashisth00** [appium/appium-desktop#1496]
2020-07-22 15:37:37.268 xcodebuild[36470:2107568] [MT] IDETestOperationsObserverDebug: (13F27CD0-0A99-4405-85CB-51443AE421BA) Finished requesting crash reports. Continuing with testing.
2020-07-22 15:37:38.768111+0200 WebDriverAgentRunner-Runner[36477:2108083] Running tests...
Test Suite 'All tests' started at 2020-07-22 15:37:39.201
Test Suite 'WebDriverAgentLib.framework' started at 2020-07-22 15:37:39.202
Test Suite 'WebDriverAgentLib.framework' passed at 2020-07-22 15:37:39.203.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-07-22 15:37:39.203
Test Suite 'UITestingUITests' started at 2020-07-22 15:37:39.203
Test Case '-[UITestingUITests testRunner]' started.
t = 0.00s Start Test at 2020-07-22 15:37:39.236

**Comment by KazuCocoa** [comment]
Could you attach the Appium server log?

**Comment by KazuCocoa** [comment]
No appium server log was difficult to detect the cause.
showIOSLog and showXcodeLog also help us.
