### ISSUE TITLE
How to run Appium desktop for iOS devices running iOS10.3.1?

### ISSUE THREAD

**Issue by ttwee** [appium/appium-desktop#150]
## The problem

When i attempt to start a new session on Appium Desktop connected to iOS devices running iOS10.3.1 the following error is triggered:

"An unknown server-side error occurred while processing the command. Original error: Sdk '10.3.1' was not in list of simctl sdks"

I ran the terminal command "xcrun simctl list" and found that only simulators up to 10.3 are listed.  Apple doesn't seem to have a 10.3.1 simulator for download, how can i resolve this issue and start a new session from Appium Desktop to my iPhone successfully?

## Environment

- I am running Appium Desktop version _<1.0.0>_.
- I am on (pick one):
    - Mac
- Xcode 8.3.2
- iPhone running iOS10.3.1
- Appium version 1.6.4

**Comment by dpgraham** [comment]
It looks like Xcode 8.3.2 doesn't support iOS 10.3.1 yet. This is an Apple issue, and we'll just have to wait until they release a new version of xcode that supports 10.3.1 and use 10.3 until then.
