### ISSUE TITLE
Can't attach to the session, the button looks active but unresponsive

### ISSUE THREAD

**Issue by n3gbx** [appium/appium-desktop#1505]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Can't attach to existent session by clicking on corresponding button: the session is detected successfully, but clicking the **'Attach to Session'** button doesn't do anything.

## Environment

- I am running Appium Desktop version 1.18.0.
- I am on:
    - [ ] Mac
    - [ ] Windows
    - [x] Linux (Ubuntu 18.04.4)

**Comment by priyankshah217** [comment]
@n3gbx I am also facing the same issue, but on mac.

**Comment by alex85vol** [comment]
Yeap, the same issue on mac

**Comment by bhanteem** [comment]
I came on here to post the same issue. I ended up going back to 1.17.1 because of this.You can see the server isn't detecting the "Attach to session" button, because nothing happens on the server side when you click the button.

**Comment by KazuCocoa** [comment]
You can try out https://github.com/appium/appium-desktop/releases/tag/v1.18.0-1

**Comment by samarendras** [comment]
I am still facing issue looks like appium is not responding means it's not doing any action.

**Comment by samarendras** [comment]
Simple it's navigating to the url but not doing any action in chrome when it's connected wifi.

**Comment by KazuCocoa** [comment]
Are you talking about 'attack to an existing session' stuff?
If no, please create a new issue with logs.

**Comment by samarendras** [comment]
I have created new issues with logs.Please help me out @KazuCocoa .

**Comment by NSDinesh** [comment]
Hi,
Still I am facing this issue
Approach 1 followed:
1.) Ran script in TestObject(Real device automation)
2.) Selected TestObject tab from Appium Desktop
3.) Provided the TestObject API key and selected the DataCentre
4.) Selected the Attach to Session
5.) Selected the dropdown - No session details populated
6.) Tried adding the session id manually. 'Attach to Session' button remains in disabled state 
Note: On selecting refresh or clicking enter after providing session id - In both case session id getting removed and  'Attach to Session' button remains in disabled state 

![image](https://user-images.githubusercontent.com/34602860/90029517-93dcf700-dcd8-11ea-85ce-a0df7c905975.png)

**Comment by KazuCocoa** [comment]
Your issue is probably https://github.com/appium/appium-desktop/issues/1344
This issue was not typing by hand

**Comment by NSDinesh** [comment]
@KazuCocoa 
Is this issue fixed as part of 1.18.0-1? Because I couldn't perform attach to session . I could not see any session id in the dropdown, so I tried with manually providing it, but still in this case the added session id getting removed, when try to do next action

**Comment by KazuCocoa** [comment]
If no session ids hadn't been appeared, probably AD got no ids or the request filed

**Comment by zied-eb** [comment]
Hi,
Any news about this issue?

Reproduced it with:
AD 1.20.0 using TestObject

Current behavior:
- No session displayed on the list (even when there is an active one running)
- Manually entered session Id is not recognized either

**Comment by KazuCocoa** [comment]
The reason is currently the section depends on the response of https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessions

Your case is a different situation. I forgot which issue though...

**Comment by kamyathakral** [comment]
Is this issue fixed? Because I'm still facing the same issue for IOS. Not able to attach to an existing session. I don't see the session ID when refreshed and when I enter anything manually it gets erased.
Using version - 2022.1.2

**Comment by KazuCocoa** [comment]
What about the response of `wd/hub/sessions` endpoint?
Appium Desktop gets the list of active sessions by the endpoint to show them.

**Comment by kamyathakral** [comment]
Not getting anything sessions for this as well

**Comment by KazuCocoa** [comment]
Then, current implementation does not work.
Btw, is it local appium server?

https://github.com/appium/appium-inspector needs to add it. (manually type session id)
