### ISSUE TITLE
unable to start screen streaming on android

### ISSUE THREAD

**Issue by jhachandan1994** [appium/appium-desktop#1507]
I am using appium latest appium 1.18. in documentation there is a mjpegServerPort capability that can be used to start mjpeg screen stream. but i am unable to get anything on this port after providing the mjpegserverport capability i am using appium python client. need help to get screen stream from android using appium

**Comment by KazuCocoa** [comment]
Could you share the log?
For now, `mjpegScreenshotUrl = 'http://localhost:9100'` and `mjpegServerPort = 9100` may work.

https://appium.io/docs/en/writing-running-appium/caps/

> with mjpegScreenshotUrl

**Comment by jhachandan1994** [comment]
Thanks it's working properly now. the problem was that i was using appium desktop and somwhow appium desktop was unable to locate mjpeg-consumer library hence i was getting the error. i installed appium from npm and now it is working properly.

**Comment by KazuCocoa** [comment]
ah, got it
