### ISSUE TITLE
org.openqa.selenium.InvalidArgumentException

### ISSUE THREAD

**Issue by xiamu001** [appium/appium-desktop#1511]
## Appium or Appium Desktop?
    Appium 
Java调用的时候出现这个错误 ，appium 获取的实际高度和宽度和手机的分辨率不一致导致我在用坐标去点击屏幕的时候出现错误。高度和宽度是否能设置成实际的分辨率？
action.tap(PointOption.point(405, 1530).perform();
deviceScreenSize=720x1600, 
org.openqa.selenium.InvalidArgumentException: Coordinate [x=405.0, y=1530.0] is outside of element rect: [0,0][720,1449]

**Comment by KazuCocoa** [comment]
You should set the point in the range of `[0,0][720,1449]`
The value is probably https://github.com/appium/appium-uiautomator2-server/blob/c0d2d45740a2f9d05cf0e6c3b7b1a19e2f85d1b1/app/src/main/java/io/appium/uiautomator2/utils/PositionHelper.java#L71 . It gets screen size by Android framework.

Was around _1449_ not good for your purpose?

**Comment by KazuCocoa** [comment]
Please report this in appium repository if the issue is still happening. (and after adjust the coordinate.)
