### ISSUE TITLE
Appium Mac code sign and notarization

### ISSUE THREAD

**Issue by Cancos** [appium/appium-desktop#1514]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Due to the recent update for Catalina, Appium Desktop doesn't seem to follow the guidelines Apple enforces:

https://developer.apple.com/news/?id=10032019a

We have a third-party company that enforces this requirement as part of a security check, but are wondering if this is something that will be included in future versions of Appium Desktop. Otherwise, we will most likely be forced to look for a different solution.

The way I checked if it passes the following test for the following .dmg files, I execute the following:
Notarization Check:
`spctl -a -vvv -t install INSERT_PATH_TO_DMG`

Codesigning Check:
`codesign -dv INSERT_PATH_TO_DMG`

Please let me know if there will be an update to the upcoming versions.

Thanks!

## Environment

- I am running Appium Desktop version v1.17.1-1.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Deprecate of https://github.com/appium/appium-desktop/issues/1207

**Comment by ashirvadgupta** [comment]
Any update on this issue?

**Comment by KazuCocoa** [comment]
We currently do not have a paid account so do as https://github.com/appium/appium-desktop/issues/1217#issuecomment-927588582.
We'll re-work for this when we must manage a paid account. (then, we should consider how/who will be responsible for it.)
