### ISSUE TITLE
The Sauce Labs tab is pointing toward the wrong endpoint for the US datacenter

### ISSUE THREAD

**Issue by thrakc3001** [appium/appium-desktop#1519]
## Appium or Appium Desktop?
I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
The Sauce Labs tab is pointing toward the wrong endpoint for the US.
This was a recent change for Sauce Labs.

The new US endpoint is:
https://ondemand.us-west-1.saucelabs.com/wd/hub

## Environment
- I am running Appium Desktop version 1.18.0.
- I am on a Mac

**Comment by KazuCocoa** [comment]
Could you check https://github.com/appium/appium-desktop/pull/1520 ?

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium-desktop/pull/1532/files fixes this
