### ISSUE TITLE
Add generic server-flags input fields to 'Advanced' tab

### ISSUE THREAD

**Issue by CathyKong** [appium/appium-desktop#152]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
1)i find that when i use appium to start an app of android ,it will clear app data so the app will be logout.
2)i want to see if the server flag --no-reset can solve the problem.
3)then i try use "appium --no-reset" to start the appium server,but it can not start the appium server automatically
so i want to know how can i use the server flags with appium-desktop, or how can i start an app without 
clear it's app data. I do not want it logout.
![image](https://cloud.githubusercontent.com/assets/27750558/25170616/cbbe692c-251d-11e7-9917-41ff328b4311.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
The 'Advanced' tab has some server flag options, unfortunately 'no reset' isn't one of the available options so we'll have to add that in a future version.

In the meantime, you can just run the command line version of appium

```
npm install -g appium
appium
```

And then following these directions, you can run a session: https://github.com/appium/appium-desktop/issues/116

**Comment by CathyKong** [comment]
i download the command line version,and it worked.

**Comment by dpgraham** [comment]
Okay great!

**Comment by jlipps** [comment]
`--no-reset` is deprecated as a server flag. It will be removed in future server versions and is intentionally not included in Appium Desktop. The appropriate way to use this functionality is to pass the `noReset` capability with your desired capabilities, with a value of `true`.
