### ISSUE TITLE
EnableMultiWindows capability only shows the bottom system UI only in Appium inspector

### ISSUE THREAD

**Issue by TracGuy** [appium/appium-desktop#1529]
This is regression from version 16.x. 

Previously when "enableMultiWindows" capability is added, all windows including active and inactive ones are shown in the page source. Starting from version 17 and onward, only bottom system UI that contains back button is displayed in the page source. The following is the complete settings I used which worked in version 16 but not the later versions. You can only check the attached screenshot that shows only the information of bottom system UI is displayed in page source not any other elements.

{
  "platformName": "Android",
  "deviceName": "-",
  "appPackage": "com.lge.launcher3",
  "appActivity": "com.lge.launcher3.AllAppsLauncherExtension",
  "automationName": "UiAutomator2",
  "enableMultiWindows": true,
  "noReset": true
}
![appium](https://user-images.githubusercontent.com/70233399/91218935-d8f52600-e6e7-11ea-89da-7a6dd2ff9689.png)

**Comment by jackyxiao126** [comment]
I have a same question, is anybody knows?

**Comment by pipawoz** [comment]
Same issue with 1.18.3

**Comment by mikalaikarol** [comment]
Looking for the answer for this one as well

**Comment by JazzMario** [comment]
We experimented with the same issue but when we set flag WindowManagerFlags.NotFocusable for android application everything became catchable again! :)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/issues/1529#issuecomment-834375722 thanks for the hint

**Comment by harshmishra19898** [comment]
> We experimented with the same issue but when we set flag WindowManagerFlags.NotFocusable for android application everything became catchable again! :)

Hi do you mean this change  WindowManagerFlags.NotFocusable for android application has to be from developer side?Please let me know.
