### ISSUE TITLE
python how to get toast 

### ISSUE THREAD

**Issue by gey7007** [appium/appium-desktop#153]
## The problem
I user this way,but get toast failed.
------------------------------------------------
from appium import webdriver
desired_caps['automationName'] = 'Uiautomator2'
.....
WebDriverWait(driver,10).until(expected_conditions.visibility_of_element_located((By.XPATH,'//*[test()="my toast msg"]')))
--------------------------------------------------
## Environment
Windows  appium-desktop1.0+python2.7+selenium3.3+Appium-Python-Client (0.24)

**Comment by lavi-xu** [comment]
I could be a appium bug.
I think you can use like way to avoid:
'//*[@name="my toast msg"]'
or
'//*[@value="my toast msg"]'

**Comment by jlipps** [comment]
This is not an Appium Desktop issue.
