### ISSUE TITLE
Appium Desktop : Fails to find elements using driver.findelement method while element is identifiable via UI automator tool

### ISSUE THREAD

**Issue by Anoopsimon90** [appium/appium-desktop#154]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
You need to provide more details

**Comment by Anoopsimon90** [comment]
Hi The issue is that , When I run Test using Appium Desktop , driver tries to find an element using Xpath
: //android.widget.EditText[@text='Card Number'] and the script then waits for ever.
You can see the screenshot of Appium Server log below:
![image](https://cloud.githubusercontent.com/assets/23075117/25262568/3dc57d4c-269c-11e7-9369-ee1fee06ecb1.png)

This Element is visible on the page, as in the property of this element per UI Automator viewer shows that this element is 'Clickable' , 'focusable' , 'enabled' . Please refer the screenshot.

![image](https://cloud.githubusercontent.com/assets/23075117/25262673/df0895a4-269c-11e7-8d5a-d10d0cd02425.png)

I am assuming that this is due to the node js wrapped with Appium Desktop latest version. Could you please help with this.

**Comment by dpgraham** [comment]
Have you tried other types of locators?

Also, you can check the contents of the page source to verify it's presence.

**Comment by jlipps** [comment]
FWIW this doesn't seem like an Appium Desktop issue, but something that should be handled on the main Appium issue tracker.
