### ISSUE TITLE
Unable to inspect Mac desktop application using Appium Desktop 

### ISSUE THREAD

**Issue by ranjanashish00** [appium/appium-desktop#1546]
Hi Guys,

I am facing an issue with Appium Desktop Application where I not able to inspect Mac Application.

## The problem

Unable to inspect Mac desktop application using Appium Desktop

## Environment

- I am running Appium Desktop version _1.18.0_.
- I am on Mac: macOS Catalina version 10.15.6

## Issue
When inspecting application, Appium Desktop captures complete Mac screen along with Appium Desktop screen too instead of capturing only application screen.

Let me know if any more details needed.
Thanks.

**Comment by KazuCocoa** [comment]
Do you mean you want to capture only a window?
The entire screen is by design of mac os driver.

**Comment by ranjanashish00** [comment]
@KazuCocoa 
I have set all desktop capabilities. Upon starting session, it captures my Desktop, Appium Destop screen and my app(basically what ever screen is surfacing, it captures) instead of capturing my application screen. 

> Do you mean you want to capture only a window?

I want to capture only my application screen(Mac native application)

> The entire screen is by design of mac os driver.

Still I am not able to inspect any element on Appium Desktop.

**Comment by ranjanashish00** [comment]
@KazuCocoa Need a rescue here.

So, all the setup is done as explained in https://github.com/appium/appium-for-mac

I am trying to execute an example code.
https://gist.github.com/ranjanashish00/46dc0a248553a45b9aac65b95f63d3ba

If possible can you let me know what am I missing here.

**Comment by KazuCocoa** [comment]
If you downloaded the latest appium-for-mac from the GitHub release page, that is everything.
Potentially someone should improve the app for newer OS versions.

**Comment by ranjanashish00** [comment]
I have latest appium-for-mac version(v0.4.1) downloaded from https://github.com/appium/appium-for-mac/releases/tag/v0.4.1.

> Potentially someone should improve the app for newer OS versions.

Is it not compatible with macOS Catalina version 10.15.6?
And so, it is throwing the noSuchElementException.

**Comment by KazuCocoa** [comment]
Potentially, yes.
We maintained a bit for existing drivers, but haven't maintained well like iOS and Android because of our limited voluntary work.
We're always welcome persons to help the project.

**Comment by ranjanashish00** [comment]
Great. 
Always happy to help.
Request you to please pass me the documents/article, with which I can start.

Thank you @KazuCocoa

**Comment by KazuCocoa** [comment]
Afaik, only https://github.com/appium/appium-for-mac
https://github.com/appium/appium-for-mac/blob/master/.github/workflows/release.yml#L16 may help to see how to build the app.

https://github.com/appium/appium-mac-driver is a driver for the AppiumForMap.app.

**Comment by ranjanashish00** [comment]
Thank you @KazuCocoa 
I will start with this.

**Comment by KazuCocoa** [comment]
We no longer maintain appium-mac-driver (as a core team)
https://github.com/appium/appium-inspector/issues/26 is for mac2-driver.
