### ISSUE TITLE
Unable to start inspector on win10

### ISSUE THREAD

**Issue by KevinChan168** [appium/appium-desktop#1558]
## Appium or Appium Desktop?
 Appium Desktop 

## The problem

start the server, then start inspector, it indicated couldn't connect to server

## Environment

- I am running Appium Desktop version _<1.18.0-2>_.
- I am on (pick one):
 Windows10

1. start apppium
2.click 'start server v1.18.0'
3.click 'start inspector session' on the right up corner
4.fill in the desired capabilities then click 'start session'

a popup windows show:  "Could not connect to server;are you sure it's running"

**Comment by KevinChan168** [comment]
![cadb86022ba91f73aeb99d9327cad4bd41363806](https://user-images.githubusercontent.com/13655147/92459817-bb50b200-f1f9-11ea-8552-7289c864a52c.png)
This is the screenshot , please help, thanks

**Comment by KazuCocoa** [comment]
What the result of `http://127.0.0.1:4723` via a browser after starting your appium server?
`The URL '/' did not map to a valid resource` message should appear then.
If no, your local network environment hasn't been set.

**Comment by KevinChan168** [comment]
> What the result of `http://127.0.0.1:4723` via a browser after starting your appium server?
> `The URL '/' did not map to a valid resource` message should appear then.
> If no, your local network environment hasn't been set.

![image](https://user-images.githubusercontent.com/13655147/92471158-0bd00b80-f20a-11ea-824c-b404501fa8fa.png)

**Comment by KazuCocoa** [comment]
How to configure your capabilities? Below is the default configuration. Then, AD sends requests to `http://localhost:4723`. If only `http://127.0.0.1:4723` worked on your env, you can select _Custom Server_ tab.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/5511591/92474733-4be9bb00-f217-11ea-8017-b42bf6477035.png">

**Comment by KevinChan168** [comment]
> http://localhost:4723

It is weird when I restart win10 and localhost:4723 works
