### ISSUE TITLE
Webview in WeChat can't be viewed by Appium inspector

### ISSUE THREAD

**Issue by Jesse1321** [appium/appium-desktop#1564]
## The problem

in WeChat, turn on webview by accessing this URL http://debugmm.qq.com/?forcex5=true, then navigate to http://debugx5.qq.com
open Appium inspector to view the page, a spinner is always thinking there.

## Environment
<img width="1083" alt="Screenshot_2020-09-16 15 13 53_t0KKbC" src="https://user-images.githubusercontent.com/25789050/93304444-9975b180-f82f-11ea-85ee-2aaa1ec6a4ac.png">
<img width="1081" alt="Screenshot_2020-09-16 15 16 57_IouhH4" src="https://user-images.githubusercontent.com/25789050/93304492-b1e5cc00-f82f-11ea-8625-e74f42be56d8.png">

- I am running Appium Desktop version _<1.18.0-2>_.
- I am on (pick one):
    - [X ] Mac
![Screenshot_2020-09-16-15-17-42-160_com tencent mm](https://user-images.githubusercontent.com/25789050/93304652-ece7ff80-f82f-11ea-8b33-caa392a8348f.jpg)

**Comment by Jesse1321** [comment]
![IMG_20200916_152455](https://user-images.githubusercontent.com/25789050/93306045-ed819580-f831-11ea-977e-1ef7cb6dd722.jpg)

I also turned on TBS inspector options.

**Comment by KazuCocoa** [comment]
How about changing contexts via `Actions`?

**Comment by Jesse1321** [comment]
> How about changing contexts via `Actions`?

I did not try this. i reverted back WeChat to version 7.0.17, then it is working fine.
