### ISSUE TITLE
Unable to run Appium server - IPBlocked due to invalid server IP http://localhost:4723/wd/hub/session

### ISSUE THREAD

**Issue by harivenkatesh-id** [appium/appium-desktop#1565]
## The problem
I have installed appium desktop app in my Mac(10.13.6). My desired capabilities look as below
{
  "app": "/Users/Apps/App.ipa",
  "deviceName": "iPhone X",
  "platformName": "iOS",
  "noReset": true,
  "platformVersion": "12.1",
  "automationName": "XCUITest",
  "udid": "*******",
  "xcodeOrgId": "**********",
  "xcodeSigningId": "iPhone Developer"
}

I tried running the server from automatic server mode i.e localhost and in custom server mode as well. But i'm getting below **error** 
Blocked due to invalid server IPBlocked due to invalid server IP http://localhost:4723/wd/hub/session

## Environment

- I am running Appium Desktop version _<1.15.1>_.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Are you using security tool?
It looks the tool blocks local network access. You should allow the path on your environment.
