### ISSUE TITLE
Unable to launch appium desktop on Mac Catalina

### ISSUE THREAD

**Issue by jineshqa** [appium/appium-desktop#1568]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When trying to launch appium desktop, alert says `The application “Appium.app" can’t be opened.`, when I checked console on Mac the message is 

`Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/xxxx/Downloads/Appium.app/Contents/, NSFilePath=/Users/xxxx/Downloads/Appium.app/Contents/PlugIns, NSUnderlyingError=0x7fb6bf21ed90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

## Environment

- I am running Appium Desktop version _18.2_.
- I am on (pick one):
    - [X ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jineshqa** [comment]
@KazuCocoa this looks like new error and incorrect packaging issue. Could be a quick fix.

**Comment by jineshqa** [comment]
Something I just realized, I downloaded the zip file instead of dmg from here https://github.com/appium/appium-desktop/releases/download/v1.18.0-2/Appium-1.18.0-2-mac.zip

**Comment by KazuCocoa** [comment]
I guess electron package system pushed dmg internal. Please use dmg for macOS, basically

**Comment by jineshqa** [comment]
Sure.

**Comment by KazuCocoa** [comment]
Thanks.
Will stop creating such zip if we can
