### ISSUE TITLE
 Appium Desktop 1.18.0-2 sendKeys does not work on IOS simulator, works fine on 1.17.1-1

### ISSUE THREAD

**Issue by Jesse1321** [appium/appium-desktop#1569]
## The problem
when trying to sendKeys to an input box on iPad simulator, below error occurred.

org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "'Other' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus" UserInfo={NSLocalizedDescription='Other' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus}
     
when i downgrade to v1.17.1-1, it works fine again.

## Environment

- I am running Appium Desktop version _<1.18.0-2>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Potentially https://github.com/appium/WebDriverAgent/pull/379 could be related.
You can try out the current `appium@beta` as https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Comment by Viku21** [comment]
The problem still exists with appium@beta on iOS 14.0, however, this works fine with iOS 13.5.

**Comment by KazuCocoa** [comment]
Please attach the full Appium log with `showIOSLog` to observe the behaviour.

**Comment by Viku21** [comment]
> Please attach the full Appium log with `showIOSLog` to observe the behaviour.

[SendKeys_issue_iOS14.0.txt](https://github.com/appium/appium-desktop/files/5290473/SendKeys_issue_iOS14.0.txt)
I'm trying to send "Test" to User ID TextField.

**Comment by Viku21** [comment]
@KazuCocoa, Did you get a chance to look into logs.

**Comment by KazuCocoa** [comment]
Potentially https://github.com/appium/WebDriverAgent/pull/379 may be relevant

**Comment by KazuCocoa** [comment]
Please try out the latest version. (that has the 379 and other fixes)
