### ISSUE TITLE
Failed to launch com.xxxxapp.trainers application","sessionId":"220E5784-2B0F-4888-951A-4D93B8F42FDB","status":13}

### ISSUE THREAD

**Issue by chennareddy08** [appium/appium-desktop#157]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Failed to launch com.xxxxapp.trainers application","sessionId":"220E5784-2B0F-4888-951A-4D93B8F42FDB","status":13}
_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _1.0(V1.6.4)
- I am on (pick one):MAC
    -
Logs:

Logs:
https://gist.github.com/chennareddy08/1404e4fa80e09daca82a495061648f42

**Comment by imurchie** [comment]
Zip files are fine. They get unzipped and the app inside gets installed. Which seems to happen fine according to the logs.

Does this app launch on the simulator manually? After Appium has launched it, can you open it yourself?

**Comment by chennareddy08** [comment]
After Appium in installed on device ,i am not able to launch manually ,app open and closed immediately ,but for real device working fine,i am facing this issue with only on simulator,Even i tried uninstalling and installing WDA ,putting  'useNewWDA':'true' no luck

**Comment by imurchie** [comment]
The app has something wrong with it on the simulator, then. You can either look in the simulator logs to see if anything comes up, or turn on device logging with `showIOSLog` capability set to `true`.

**Comment by crhoads1024** [comment]
@imurchie I've a similar yet slightly different issue.
Appium will throw the cant launch status 13 error on physical device and simulator.

**Manually Launch App:**
Successful - on physical device 
Unsuccessful - on iOS simulator

Same apps im trying to launch now ran just a couple weeks ago on both platforms.

**Automatic code signing is configured** and applied to WDA.proj in xcode with the capabilities set for real device server caps with the following values: 
"xcodeOrgId": "Company_OrgId_Num",
  "xcodeSigningId": "Company_Team_ID"

**useNewWDA set to true**

**Observed Behavior on real device:**
WDA is installed on real device
App is installed on REAL DEVICE 
Neither WDA or App attempt to open on real device like they do on simulator.
Then this error is found in the logs.
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.qsrsoft.portalapp application","sessionId":"158E23C6-4490-4DFA-8F11-E5818431D474","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...

**Observed behavior on simulated device:**
WDA is installed then launches and closes immediately. 
Then the app is launched and closes immediately.
Logs show same error as noted with the real iOS device - cant launch app, status 13 retrying WDA...

Machine Config:
Mac Book Pro: OSX 10.3.2
Xcode: 9.2
Appium Server: 1.7.2
iOS Sim: 11.2
UDID: 5A4A7D7B-0D5B-4CB4-BBD2-5F1E9E87B2DF
iOS Physical Device: iPhone 6s Plus - 11.2

Physical Device Launch Failure Log:
https://gist.github.com/crhoads1024/24c8edb9574db4a7ede2875338db865f

Simulator Device Launch Failure Log:
https://gist.github.com/crhoads1024/04fb7f128b762462b83ab2949d96c62b

**Comment by michelle-chiang** [comment]
@crhoads1024 @AlexTolok Did you find a resolution? Seeing a similar problem running Appium tests on an AWS DeviceFarm real iOS device.
