### ISSUE TITLE
Appium not able to get the Wechat mini program page source

### ISSUE THREAD

**Issue by BenCao2018** [appium/appium-desktop#1574]
When trying to get page source on Wechat mini program on Android devices, it timed out. Here is the error logs:

`[MJSONWP (5ddd1a8c)]     at JWProxy.proxy (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:213:13)
[W3C] Matched W3C error code 'unknown error' to UnknownError
[HTTP] <-- GET /wd/hub/session/5ddd1a8c-b45d-4505-906e-4932fe5020e6/source 500 15567 ms - 244
[HTTP] 
[WD Proxy] Got response with status 200: {"sessionId":"dd1cd7a1-4ed4-4c63-86c4-dbd6b2f9e60b","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAkkCAYAAAD508+vAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAACAASURBVHic7N15fFT1vT\/+1+ec2SfrJEAgAwElILviAi4gaG0Fd0VbW7XLbdV6r1p\/\nt7X2am8X22rbb29duone20W7uuECqCjBBQ2KIkEQCQKBSSCEJCSZfeacz++PWTKTTJKZyWQZeD0f\nD83kzJlzPmSZzHnN+\/P+CLc3IEFERERERERElMeUkR4AEREREREREdFgMeAgIiIiIiIiorzHgIOI\niIiIiIiI8h4DDiIiIiIiIiLKeww4iIiIiIiIiCjvMeAgIiIiIiIiorzHgIOIiIiIiIiI8h4DDiIi\nIiIiIiLKeww4iIiIiIiIiCjvMeAgIiIiIiIiorzHgIOIiIiIiIiI8h4DDiIiIiIiIiLKeww4iIiI\niIiIiCjvMeAgIiIiIiIiorzHgIOIiIiIiIiI8h4DDiIiIiIiIiLKeww4iIiIiIiIiCjvMeAgIiIi\nIiIiorzHgIOIiIiIiIiI8h4DDiIiIiIiIiLKe4aRHsBosbu+Pu19LVYrnE7nEI7mWCIhtC4YGv8C\ndefPoAo\/ZEAHdAmhAFrIBG3OXQhVfQ0wlgAQIz1g6sPVn7kMR5qbIQAIiPh3SiT8hx7bkeI2AMgU\nt2X0\/zJ6O3G7jG4vHzcOT7763OD\/MURERERp8Hq9aGpsRP3u9K8VYqqnVmNCZSVsNtsQjIyIUjnu\nA441a1bjpTVrMn7cl667DgsWnjkEIxqYy+VCe3sbXC4XAMDn9cLlcqGsrAyOsjIAgMPhQJmjDFOr\nq0dkjICEqf4\/oLqehAxFAg3oEpouI1esOoCwBPQA1A9+CGXzD6AA0E64EsEz\/oyRDjqCwSDWrXsF\nUkp89rOfg8lkGtHx...
[WD Proxy] Matched '/wd/hub/session/5ddd1a8c-b45d-4505-906e-4932fe5020e6/window/current/size' to command name 'getWindowSize'
[WD Proxy] Proxying [GET /wd/hub/session/5ddd1a8c-b45d-4505-906e-4932fe5020e6/window/current/size] to [GET http://localhost:8200/wd/hub/session/dd1cd7a1-4ed4-4c63-86c4-dbd6b2f9e60b/window/current/size] with body: {}
[MJSONWP (5ddd1a8c)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAkkCAYAAAD508+vAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAACAASURBVHic7N15fFT1vT/+1+ec2SfrJEAgAwElILviAi4gaG0Fd0VbW7XLbdV6r1p/\nt7X2am8X22rbb29duone20W7uuECqCjBBQ2KIkEQCQKBSSCEJCSZfeacz++PWTKTTJKZyWQZeD0f\nD83kzJlzPmSZzHnN+/P+CLc3IEFERERERERElMeUkR4AEREREREREdFgMeAgIiIiIiIiorzHgIOI\niIiIiIiI8h4DDiIiIiIiIiLKeww4iIiIiIiIiCjvMeAgIiIiIiIiorzHgIOIiIiIiIiI8h4DDiIi\nIiIiIiLKeww4iIiIiIiIiCjvMeAgIiIiIiIiorzHgIOIiIiIiIiI8h4DDiIiIiIiIiLKeww4iIiI\niIiIiCjvMeAgIiIiIiIiorzHgIOIiIiIiIiI8h4DDiIiIiIiIiLKeww4iIiIiIiIiCjvMeAgIiIi\nIiIiorzHgIOIiIiIiIiI8h4DDiIiIiIiIiLKe4aRHsBosbu+Pu19LVYrnE7nEI7mWCIhtC4YGv8C\ndefPoAo/ZEAHdAmhAFrIBG3OXQhVfQ0wlgAQIz1g6sPVn7kMR5qbIQAIiPh3SiT8hx7bkeI2AMgU\nt2X0/zJ6O3G7jG4vHzcOT7763OD/MURERERp8Hq9aGpsRP3u9K8VYqqnVmNCZSVsNtsQjIyIUjnu\nA441a1bjpTVrMn7cl667DgsWnjkEIxqYy+VCe3sbXC4XAMDn9cLlcqGsrAyOsjIAgMPhQJmjDFOr\nq0dkjICEqf4/oLqehAxFAg3oEpouI1esOoCwBPQA1A9+CGXzD6AA0E64EsEz/oyRDjqCwSDWrXsF\nUkp89rOfg8lkGtHxjAYCwJFDh+PhRneogaRtSPGxL8khRuJt2WubDokx48YN8l9BRERElJ4NNTVY\nu3Y1fF...
[HTTP] <-- GET /wd/hub/session/5ddd1a8c-b45d-4505-906e-4932fe5020e6/screenshot 200 16205 ms - 828480
[HTTP] 
[WD Proxy] Got response with status 200: {"sessionId":"dd1cd7a1-4ed4-4c63-86c4-dbd6b2f9e60b","value":{"height":2139,"width":1080}}
[WD Proxy] Replacing sessionId dd1cd7a1-4ed4-4c63-86c4-dbd6b2f9e60b with 5ddd1a8c-b45d-4505-906e-4932fe5020e6
[HTTP] <-- GET /wd/hub/session/5ddd1a8c-b45d-4505-906e-4932fe5020e6/window/current/size 200 16327 ms - 100`

Tried with python scripts with Appium, here is the error:
_selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Timed out after 10000 milliseconds waiting for root AccessibilityNodeInfo_

## Environment

- I am running Appium Desktop version _<1.18>_.
- I am on (pick one):
    - [x] Windows
    - [x] Linux

**Comment by KazuCocoa** [comment]
What happens when you manually increate the timeout in https://github.com/appium/appium-uiautomator2-server/blob/c534718535d9541592087e489adad220e15d46b0/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L33 ?

**Comment by ctoops** [comment]
Hi, @KazuCocoa encounter the same issue, set AX_ROOT_RETRIEVAL_TIMEOUT_MS as 100000, and rebuild apks, after entering WeChat mini-program, still not get page source, here is the log.
https://gist.github.com/ctoops/abac60b1ba2fc1efb7686e2507462f8a

**Comment by KazuCocoa** [comment]
The root issue is probably their app side (or Android accessibility stuff).
Or some timeout potentially help (but I have no good idea)
http://appium.io/docs/en/advanced-concepts/settings/index.html

**Comment by wangbo0105** [comment]
according to debug ,I get  
 (make sure the app has its WebView/WebLayer configured for debugging)
i think wechat close WebView/WebLayer configured for debugging

**Comment by yuantYT** [comment]
Hello wangbo, is this issue fixed now?  I met the same issue when I do Wechat mini program automation test.  really appreciated if you can reply me.

**Comment by sayidkongtao** [comment]
I try it with Android 10/Android5.1.0/Android 8 with wechat version 7.0.22.
Only success to switch webview with Android 8.
[appium.log](https://github.com/appium/appium-desktop/files/5846730/appium.log)

**Comment by Jiurong-Yang** [comment]
Verified that this isn't an appium problem. By the time the mini program launches it is in a webview, and trying to get page_source on native_app will fail. 

https://www.cnblogs.com/erchun/p/13335723.html
This is the thread that gives the solution, the one difference is that I used the chromedriver that is specified in the chrome://inspect/#devices page. Which for wechat 8.0.2 is chromedriver version 77.0.3865.40

**Comment by jiyegui** [comment]
> 已验证这不是 appium 问题。当小程序启动时它在一个 webview 中，并且试图在 native_app 上获取 page_source 将失败。
> 
> https://www.cnblogs.com/erchun/p/13335723.html
> 这是给出解决方案的线程，不同之处在于我使用了chrome://inspect/#devices页面中指定的chromedriver。微信 8.0.2 是 chromedriver 版本 77.0.3865.40

大佬你好，请问微信 8.0.2 ，chromedriver版本找77.0的吗

**Comment by yicm** [comment]
@jiyegui  用微信打开这个链接就知道了 http://httpbin.org/user-agent
