### ISSUE TITLE
Appium desktop by appium v1.6.4 Mac Sierra and IOS 10.3 got Error "EnotFound"

### ISSUE THREAD

**Issue by Netardent** [appium/appium-desktop#158]
## The problem
I tried to install and Test by Appium Desktop on Mac osx version Xcode 8.3 and IOS 10.3. So i have installed Appium 1.6.4 and I've installed node and all pre requirement which need for Appium.

![1](https://cloud.githubusercontent.com/assets/9458718/25333374/2dff86d6-28ff-11e7-8a13-f93a960aa7a4.png)

Here is Appium Doctor output which have no error for IOS test!

![2](https://cloud.githubusercontent.com/assets/9458718/25333375/307a9fae-28ff-11e7-9657-0ca31a32c97d.png)

The output of Appium desktop, ENotFound Error.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):1.6.3
* Desktop OS/version used to run Appium:MAC Os Sierra
* Node.js version (unless using Appium.app|exe):7.9.0
* Real device or emulator/simulator:IOS 10.3 Simulator
* Appium CLI or Appium.app|exe:Appium Desktop

## Link to Appium logs
No log in appium log page

**Comment by dpgraham** [comment]
Closing as duplicate: https://github.com/appium/appium/issues/8314
