### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134

### ISSUE THREAD

**Issue by jtappi** [appium/appium-desktop#159]
**Appium Desktop**

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

PROBLEM:
Unable to Start New Session successfully.  Appium-Desktop launches and starts without any problems.  However, When i try to Start a New Session and the tests tries to run, it fails with the following error:
'Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134'

*I tried downloading the latest version of the WebDriver from Facebook however Appium-Desktop freezes.  
*I tried building the WebDriverAgent from the Appium-Desktop folder however, the build fails with the following message: Lexical or PReprocessor Issue: 'RoutingHTTPServer/RoutingConnection.h' file not found FBWebServer.m

## Environment

- I am running Appium Desktop version _<1.0>_.dmg
- I am on (pick one):
    - [X] Mac (10.12.4 Sierra)
    - [ ] Windows
    - [ ] Linux

I am testing against an iOS Simulator (6s, 6s Plus, 7)

Link to Error Log: https://gist.github.com/jtappi/23d4da67e690e27aed2b6116be914f86

**Comment by imurchie** [comment]
What version of Carthage are you using?

Can you do the following:
```
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

./Scripts/bootstrap.sh -d
```

**Comment by jtappi** [comment]
hmmm.  I thought i was using the latest version of carthage as I had installed it just a few weeks ago.  However, here are the results from your instructions above.

Fetching dependencies
dyld: Symbol not found: __TMV6Result8AnyError
  Referenced from: /usr/local/Cellar/carthage/0.20.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
 in /usr/local/Cellar/carthage/0.20.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
./Scripts/bootstrap.sh: line 45: 13829 Abort trap: 6           carthage bootstrap $USE_SSH

**Comment by imurchie** [comment]
https://github.com/Carthage/Carthage/issues/1044

**Comment by jtappi** [comment]
Thanks @imurchie, I'll give some of those suggestions a try

**Comment by jtappi** [comment]
Thanks again @imurchie, Appium Desktop is now working!
I followed the instructions at [https://github.com/Carthage/Carthage/issues/1044](url) suggested by @onmyway1233

RESOLUTION:
1. brew rm carthage 
2. https://github.com/Carthage/Carthage/releases (Download and install)
