### ISSUE TITLE
Keyboard not visible, and visible on simulator

### ISSUE THREAD

**Issue by aluckin3** [appium/appium-desktop#1594]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Using appium desktop i can't see keyboard, but simulator shows that keyboard.

## Environment

- I am running Appium Desktop version 1.18.3.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

Screenshot: https://ibb.co/5WPt2Kj

**Comment by KazuCocoa** [comment]
Was it interacting with a secure text field? It is a limitation by Apple.
