### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by halkeye** [appium/appium-desktop#16]
When doing an npm install, a couple deprecated warnings show up

* [ ] npm WARN deprecated node-uuid@1.4.7: use uuid module instead
* [ ] npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron

**Comment by imurchie** [comment]
The second we can do something about. The first is in a subdependency, and one instance in an unmaintained one (`mksnapshot`), so probably more difficult.

**Comment by dpgraham** [comment]
I renamed 'electron-prebuilt' to 'electron' and it broke the build. I may revisit this later.
