### ISSUE TITLE
Hello! XCUITest does not support'press-wait-moveTo-wait-moveTo-wait-moveTo-release'this kind of complex gestures operation, the next version will be repaired?

### ISSUE THREAD

**Issue by fanheng0921** [appium/appium-desktop#160]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by imurchie** [comment]
Apple has not given any way to automate such _ad hoc_ gestures. Until they do, Appium cannot support them.

The available gestures are documented here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md
