### ISSUE TITLE
Cannot enter values into EditText,prompt:Call to 'sendKeys' failed

### ISSUE THREAD

**Issue by danzi516** [appium/appium-desktop#1605]
My environment：Appium-desktop 1.19.0、node:v12.19.0
![image](https://user-images.githubusercontent.com/3423101/97690501-05f2fa00-1ad8-11eb-88c6-38d6fe8418dd.png)
When setting the value to EditText, the prompt Call to 'sendKeys' failed
Please take a look at it for me. Thank you
Below is the service log

**appium-server:**
[HTTP] {"text":"1"}
[W3C (6ba03010)] Calling AppiumDriver.setValue() with args: ["1","8ca0a331-1dd3-456e-acde-485d415a53bd","6ba03010-a16d-4343-97b2-d0726970e21d"]
[WD Proxy] Matched '/element/8ca0a331-1dd3-456e-acde-485d415a53bd/value' to command name 'setValue'
[Protocol Converter] Added 'value' property ["1"] to 'setValue' request body
[WD Proxy] Proxying [POST /element/8ca0a331-1dd3-456e-acde-485d415a53bd/value] to [POST http://127.0.0.1:8205/wd/hub/session/2c73e285-f44d-488e-bb80-2732ca0cbd42/element/8ca0a331-1dd3-456e-acde-485d415a53bd/value] with body: {"elementId":"8ca0a331-1dd3-456e-acde-485d415a53bd","text":"1","replace":false,"value":["1"]}
[WD Proxy] Got response with status 400: {"sessionId":"2c73e285-f44d-488e-bb80-2732ca0cbd42","value":{"error":"invalid element state","message":"Cannot set the element to '1'. Did you interact with the correct element?","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to '1'. Did you interact with the correct element?\n\tat io.appium.uiautomator2.handler.SendKeysToElement.setText(SendKeysToElement.java:88)\n\tat io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:119)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.Abs...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[W3C (6ba03010)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to '1'. Did you interact with the correct element?
[W3C (6ba03010)] 	at io.appium.uiautomator2.handler.SendKeysToElement.setText(SendKeysToElement.java:88)
[W3C (6ba03010)] 	at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:119)
[W3C (6ba03010)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[W3C (6ba03010)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)
[W3C (6ba03010)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)
[W3C (6ba03010)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[W3C (6ba03010)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[W3C (6ba03010)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[W3C (6ba03010)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[W3C (6ba03010)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[W3C (6ba03010)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[W3C (6ba03010)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[W3C (6ba03010)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[W3C (6ba03010)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[W3C (6ba03010)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[W3C (6ba03010)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[W3C (6ba03010)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[W3C (6ba03010)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
[W3C (6ba03010)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
[W3C (6ba03010)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[W3C (6ba03010)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[W3C (6ba03010)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[W3C (6ba03010)] 	at java.lang.Thread.run(Thread.java:818)
[W3C (6ba03010)] 
[HTTP] <-- POST /wd/hub/session/6ba03010-a16d-4343-97b2-d0726970e21d/element/8ca0a331-1dd3-456e-acde-485d415a53bd/value 400 63 ms - 3877

**Start the way：**
{
  "automationName": "UiAutomator2",
  "platformName": "Android",
  "platformVersion": "6.0.1",
  "deviceName": "127.0.0.1:7555",
  "appPackage": "com.jiaparts.dsy",
  "appActivity": "com.jiaparts.dsy.ui.StartActivity"
}

**Comment by KazuCocoa** [comment]
What was the element's attributes?

**Comment by danzi516** [comment]
> What was the element's attributes?
hello，The attribute is ‘android.widget.EditText‘

**Comment by KazuCocoa** [comment]
I meant attributes like clickable etc usually you can get them via https://appium.io/docs/en/commands/element/attributes/attribute/

**Comment by danzi516** [comment]
Hello attributes are shown below

![QQ截图20201102085913](https://user-images.githubusercontent.com/3423101/97820538-9d7b6700-1ce9-11eb-80d7-7ffd1e534047.png)

**Comment by KazuCocoa** [comment]
Thanks.

It seems Android framework failed to set the value
https://github.com/appium/appium-uiautomator2-server/blob/660d65b5b16c7f0c0794c636e5210efeca0e06a7/app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java#L87-L90

How about to click the element and make it focused or selected before send keys?
(Whether this works also depends on Android framework though)

As an alternative, you also can try to send texts to the element via press keycode in Actions if the element is focused.
The press keycode sends a value via adb command.

**Comment by ravireddy07** [comment]
I'm highlighting the EditText Widget and trying to enter the Text, But is throwing the Error `Cannot set the element to 'Test'. Did you interact with the correct element?`

This is what i'm using:

`
  Actions a = new Actions(getDriver());
  getDriver().findElementsByClassName("//android.widget.EditText");
  a.sendKeys("Test");
  `
