### ISSUE TITLE
unable to use sendkeys in iPhone simulator 

### ISSUE THREAD

**Issue by Ashwiniyp** [appium/appium-desktop#1606]
Error : 
[element.sendKeys("abc")] Error response status: 12, InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}

Getting above error while trying to sendkey in iPhone simulator , 
Using appium 1.17.0 desktop version .

**Comment by KazuCocoa** [comment]
Could you attach the full Appium log?
A possible fix is https://github.com/appium/WebDriverAgent/pull/379
It will be in 1.19.0
