### ISSUE TITLE
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework

### ISSUE THREAD

**Issue by llliuyx** [appium/appium-desktop#1607]
## The problem

Appium failed to start on Mac 10.15.5 , the details shows:

xxxxxx•~» /Users/xxxxxx/Downloads/Appium.app/Contents/MacOS/Appium
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/xxxxxx/Downloads/Appium.app/Contents/MacOS/Appium
  Reason: no suitable image found.  Did find:
	/Users/xxxxxx/Downloads/Appium.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Users/xxxxxx/Downloads/Appium.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
[1]    14123 abort      /Users/xxxxxx/Downloads/Appium.app/Contents/MacOS/Appium

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.18.3 & Appium 1.19.0-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  Mac 10.15.5 
* Node.js version (unless using Appium.app|exe): v12.19.0
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Appium.app

**Comment by KazuCocoa** [comment]
mm, please try out latest Appium-Server-GUI-mac-1.22.0.dmg ...
Potentially it was by zip file's one...
