### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

### ISSUE THREAD

**Issue by apn6125** [appium/appium-desktop#161]
## Appium Desktop?

My ANDROID_HOME variable is set, 
--------

- Anupam-Patil:~$ appium-doctor 
- info AppiumDoctor ### Diagnostic starting ###
- (node:11360) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
- info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
- info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
- info AppiumDoctor  ✔ DevToolsSecurity is enabled.
- info AppiumDoctor  ✔ The Authorization DB is set up properly.
- info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
- info AppiumDoctor  ✔ HOME is set to: /Users/apn6125
- info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/apn6125/Library/Android/android-sdks
- info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
- info AppiumDoctor  ✔ adb exists at: /Users/apn6125/Library/Android/android-sdks/platform-tools/adb
- info AppiumDoctor  ✔ android exists at: /Users/apn6125/Library/Android/android-sdks/tools/android
- info AppiumDoctor  ✔ emulator exists at: /Users/apn6125/Library/Android/android-sdks/tools/emulator
- WARN AppiumDoctor  ✖ Bin directory for $JAVA_HOME is not set
- info AppiumDoctor ### Diagnostic completed, one fix needed. ###
- info AppiumDoctor 
- info AppiumDoctor ### Manual Fixes Needed ###
- info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
- WARN AppiumDoctor - Add '$JAVA_HOME/bin' to your PATH environment
- info AppiumDoctor ###
- info AppiumDoctor 
- info AppiumDoctor Bye, run appium-doctor again when all manual fixes have been applied!
- info AppiumDoctor 

----------

## The problem
When I am launching Appium new GUI and running some program, it’s giving me error as below in GUI console- 

[MJSONWP] Encountered internal error running command: Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

<img width="894" alt="screen shot 2017-04-28 at 11 15 19 pm" src="https://cloud.githubusercontent.com/assets/19683739/25540436/9d67a14a-2c68-11e7-8345-049b3d10c072.png">

## Environment

- I am running Appium Desktop New GUI Version 1.0.0 (1.0.0)
- I am on :
    - [ ] Mac

**Comment by jlipps** [comment]
According to the doctor it looks like it's not set. How do you think you have it set?

**Comment by webmagit** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17106847/26186986/492c9916-3bd9-11e7-9a7d-6ca2acd30128.png)

[ ] ANDROID_HOME is set
[ ] adb also detected

Problem: Could not find adb

<img width="991" alt="screenshot" src="https://cloud.githubusercontent.com/assets/17106847/26187074/aa42d67a-3bd9-11e7-9ed8-f001551070b6.png">

**Comment by jlipps** [comment]
thanks for that @webmagit. will close here unless further evidence of a bug arises.
