### ISSUE TITLE
[Appium-Desktop 1.17] How to close appium settings and unlock app every time you start an automated test

### ISSUE THREAD

**Issue by JackToby** [appium/appium-desktop#1610]
## The problem

when i start an automated test by appium,the device that It indicates that appium settings and unlock need to be installed

## Environment

- I am running Appium Desktop version 1.17
- I am on (pick one):
    - [ ] Mac
    -  Windows 10 pro

**Comment by KazuCocoa** [comment]
Do you want to skip them?
`skipDeviceInitialization` capability https://appium.io/docs/en/writing-running-appium/caps/ may help then.

Appium forum is more proper for ask such questions
