### ISSUE TITLE
My appium is not starting server and returning this statement. Kindly have a look at the attached screenshot. Need help

### ISSUE THREAD

**Issue by waqaranwar1** [appium/appium-desktop#1612]
## Screenshot
![Clipboard - November 4, 2020 12_19 PM](https://user-images.githubusercontent.com/64527157/98085247-dc9ee900-1e9e-11eb-847c-1ecb39f9aeeb.png)

**Comment by waqaranwar1** [comment]
i found out the issue i have not provided the Path = Android home and java home paths

**Comment by KazuCocoa** [comment]
You can check if your environment paths via appium-doctor at least.
http://appium.io/docs/en/about-appium/getting-started/#verifying-the-installation

**Comment by waqaranwar1** [comment]
Yes Thanks for your suggestion. It is resolved.
