### ISSUE TITLE
Could not load a driver for automationName 'XCUITest' and platformName 'ios'. Please verify your Appium installation

### ISSUE THREAD

**Issue by RT715** [appium/appium-desktop#1616]
## The problem

Hi folks! I keep facing that issue above when i try to run a test on the real iOS device. Even when i try to start inspector session in desktop appium i collide with the same issue. In appium logs i found out this: **Cannot find module 'appium-xcuitest-driver'** maybe that the issue i need to fix but i have this particular module... Ive downloaded WDA from appium repository, put it into the appium-xcuitest-driver derictory, did the bootstrap command, built WDA on my device... Googling this problem leads me to nowhere.

## Environment

* Appium version - v1.18.3
* Desktop OS - Catalina 10.15.7
* Node.js version - v14.13.1
* Npm - 6.14.8
* Mobile platform - iOS
* Real device or emulator/simulator - iPhone SE 2020

## Details

**My Kotlin test code:**
https://gist.github.com/RT715/ced170f5e6b1e054888cbc20ff6a17dd

## Link to Appium logs
https://gist.github.com/RT715/82de73d5e32cf721c1cbe35ebfa5073c

**Comment by KazuCocoa** [comment]
Could you share the list of directories in `/Applications/Appium.app/Contents/Resources/app/node_modules/appium` without modules you put manually?

**Comment by RT715** [comment]
Here you go https://drive.google.com/file/d/13OP4r10pSrI0le8aK_ipaERO7JwHojPT/view?usp=sharing

**Comment by RT715** [comment]
Getting a new error in appium logs https://gist.github.com/RT715/9d8a318336462b6d4e1fbb4553c9305a

**Comment by KazuCocoa** [comment]
Thanks.
Hm, it has appium-xcuitest-driver in appium module, so I think `appium` module can refer to the module...

**Comment by RT715** [comment]
So what do i do? Maybe i just delete this module from /Applications/Appium.app/Contents/Resources/app/node_modules ?
After appium installation i didn't do anything in this directory.

**Comment by KazuCocoa** [comment]
Afaik, 1) remove entire `Appium.app`, 2) move Appium.app in dmg to `/Applications` is fine to clean Appium.app.
Removing files in the module by yourself might cause something wrong dependencies.
(e.g. runs `npm install` in some modules in `node_modules` could break some dependencies)

**Comment by RT715** [comment]
@KazuCocoa Ive been trying to figure out what the problem is for a week and just simple reinstallation help =) That you man very much! I appreciate it!
