### ISSUE TITLE
macOS Big Sur

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-desktop#1617]
We should test AD on macOS Big Sur/Silicon.
So far, we do not have the machine so labeled as `help wanted`.

**Comment by abhijithshaji** [comment]
![image](https://user-images.githubusercontent.com/55432727/99509134-683e6c80-29ab-11eb-8ec2-d6ce2bc04741.png)

Unable to install Appium.app (1.18.3)
Platform: Macbook 2017 Intel / Big Sur 11.0.1

**Comment by KazuCocoa** [comment]
Yes, https://github.com/appium/appium-desktop/issues/1217 is a related issue.

**Comment by abhijithshaji** [comment]
Installing via ```.dmg``` instead of ```.zip``` solved this problem.

**Comment by KazuCocoa** [comment]
I tested a bit on M1 macOS env as well.
No blocking issues were there.
