### ISSUE TITLE
Do not show WebView which is in the result of CDP list, but it does not have the same process id with the app under test

### ISSUE THREAD

**Issue by ChaseSkywalker** [appium/appium-desktop#1618]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I can`t get webview in my test case code when using appium-desktop-1.18.2 and 1.18.3,whatever the android version is.
I`m sure the webview debug mode is turned on and I can see webview in the chrome-inspect...
it works fine when using appium-desktop-1.15.1

![image](https://user-images.githubusercontent.com/62996413/99040059-6ba8b100-25c3-11eb-86f1-730da96bc03e.png)

this is the log in appium-desktop-1.18.2(same as 1.18.3)
[appium-server-logs-1.18.2.txt](https://github.com/appium/appium-desktop/files/5535276/appium-server-logs-1.18.2.txt)

and this is the log in appium-desktop-1.15.1
[appium-server-logs_1.15.1.txt](https://github.com/appium/appium-desktop/files/5535278/appium-server-logs_1.15.1.txt)

i think the problem is this
![image](https://user-images.githubusercontent.com/62996413/99039815-fd63ee80-25c2-11eb-8a33-60dafeda5bc9.png)

## Environment

- I am running Appium Desktop version _<1.18.2>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
What about enabling the blow's capabilities?
```
[debug] [35m[AndroidDriver][39m Parsed 1 active devtools socket: ["@webview_devtools_remote_20803"]
[info] [35m[AndroidDriver][39m Not checking whether webviews have active pages; use the 'ensureWebviewsHavePages' cap to turn this check on
[info] [35m[AndroidDriver][39m Not collecting web view details. Details collection might help to make Chromedriver initialization more precise. Use the 'enableWebviewDetailsCollection' cap to turn it on
[debug] [35m[AndroidDriver][39m WEBVIEW_20803 mapped to pid 20803
```

**Comment by ChaseSkywalker** [comment]
> enableWebviewDetailsCollection

![image](https://user-images.githubusercontent.com/62996413/99141543-4da48480-2687-11eb-8bf4-6cadc00217c3.png)

still the same

**Comment by KazuCocoa** [comment]
I found your attached one (1.15.1) had `_unknown` suffix. I guess the previous implementation handled WebView without ensuring the process as `_unknown`.

For now, Appium only handles WebView which is actually the app under test's one by the process id.
https://github.com/appium/appium-android-driver/blob/2d1fef07bcdeede4793daa7e11618d82ac19af16/lib/webview-helpers.js#L278-L291


A way is probably relax the check. Then, maybe the behaviour will get back to the previous one.
https://github.com/appium/appium-android-driver/blob/2d1fef07bcdeede4793daa7e11618d82ac19af16/lib/webview-helpers.js#L394-L395

What the result of the below URL when you open the web view?
`localPort` is `8200` in your attached log case (1.18.2). It should be JSON format.
`http://127.0.0.1:${localPort}/json/list`

**Comment by ChaseSkywalker** [comment]
@KazuCocoa this is the result

{
    "sessionId": null,
    "value": {
        "error": "unknown command",
        "message": "The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource",
        "stacktrace": "io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:764)\n"
    }
}

**Comment by KazuCocoa** [comment]
Oh, probably `10900` or one of between `10900` to `11000` as the localhost.
`const DEVTOOLS_PORTS_RANGE = [10900, 11000];` https://github.com/appium/appium-android-driver/blob/2d1fef07bcdeede4793daa7e11618d82ac19af16/lib/webview-helpers.js#L20

I'd like to check the response of `/json/list` by the chromedriver.

**Comment by ChaseSkywalker** [comment]
here is what i got

![image](https://user-images.githubusercontent.com/62996413/99237477-7c5f5e00-2833-11eb-89f2-7126c3fd46a4.png)

basically the same as what`s in chrome://inspect/#devices

**Comment by ChaseSkywalker** [comment]
> A way is probably relax the check. Then, maybe the behaviour will get back to the previous 

i define pkg as 'unknown', then it works fine now...
but i think that`s just kind of solve the problem,right?

**Comment by KazuCocoa** [comment]
Probably if it worked.
Then, the WebView did not have the same process id with the app under test. Although I don't know the reason was by design by Android OS (and depends on their versions ect) or manufacture stuff.


We probably can add a capability to `allowUnknwnWebView` etc for it.

**Comment by ChaseSkywalker** [comment]
thank u for the help 👍

**Comment by KazuCocoa** [comment]
@ChaseSkywalker How about https://github.com/appium/appium-android-driver/pull/670 ?
(If you could apply the PR on your local...)

Then, web view name like `WebView_{pid}` remains in the list of contexts. (Not replace the name as 'unknown')

**Comment by KazuCocoa** [comment]
What about using `appium@1.19.0`?
You can connect to the local appium server as https://github.com/appium/appium-desktop#connect-to-local-appium-server if you want to inspect it via AD.

**Comment by ChaseSkywalker** [comment]
oh~didn`t notice that there is a 1.19.0beta...
upgrade to 1.19 and it gets the webview now
thanks @KazuCocoa @mykola-mokhnach

**Comment by KazuCocoa** [comment]
Glad to hear it. Thanks for checking 👍
