### ISSUE TITLE
Error while saving Presets for Appium Desktop v 1.0.0 on Windows 7

### ISSUE THREAD

**Issue by anish10110** [appium/appium-desktop#162]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Not able to Save presets in Appium Desktop.

Steps to Reproduce:
1. Opened Appium Desktop (v 1.0.0) on Windows 7
2. Navigated to Advanced tab
3. Entered 'Server Address' as 127.0.0.1, 'Server Port' as 4723 and ticked 'Allow Session Override' session
4. Clicked 'Save as Preset...' button
5. Entered Preset name and clicked on 'Save' button but got the below error - 'There was a popup saving preset...'

![image](https://cloud.githubusercontent.com/assets/8146449/25604641/58de0914-2f48-11e7-9699-2844c86654ff.png)

## Environment

- I am running Appium Desktop version _1.0.0_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Thanks for reporting this

**Comment by jlipps** [comment]
Could it be the case of an old settings file somehow?

**Comment by dpgraham** [comment]
Yeah, I"m pretty sure it is.

I just need to find where the settings file is saved on Windows.

**Comment by dpgraham** [comment]
@anish10110 Can you try deleting the Settings file and then restarting the app. The settings file file should be located at:

`C:\Users\<username>\AppData\Roaming\appium-desktop`

Let me know if that doesn't work and I'll re-open the ticket.

**Comment by anish10110** [comment]
@dpgraham @jlipps Thanks for your help. It worked after I deleted the settings file.
