### ISSUE TITLE
appium-desktop-1.18.3 can't inspect the notepad.exe elements, but appium-desktop-1.15.1 can inspect 

### ISSUE THREAD

**Issue by cxx520** [appium/appium-desktop#1621]
## Appium or Appium Desktop?
AppiumDesktop
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

appium-desktop-1.18.3 can't inspect the notepad.exe elements, but appium-desktop-1.15.1 can inspect.
![2F508C09-4944-4440-AB0F-EDB8DF71C259](https://user-images.githubusercontent.com/74540978/99249840-b174ac00-2845-11eb-8b88-d58fcc87577c.png)
![63D1668D-35B1-454a-934A-866A1802742C](https://user-images.githubusercontent.com/74540978/99249855-b9cce700-2845-11eb-8285-3a74dc220a4b.png)

## Environment

- I am running Appium Desktop version _<1.18.3>_.
- I am on (pick one):
    - [ ] Mac
    - [√] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you share the both Appium logs? I wonder they have different WAD. Then, WinAppDriver's GitHub is the proper place to report it.

**Comment by cxx520** [comment]
> Could you share the both Appium logs? I wonder they have different WAD. Then, WinAppDriver's GitHub is the proper place to report it.
The logs
[appium-desktop1.15.1log.txt](https://github.com/appium/appium-desktop/files/5550623/appium-desktop1.15.1log.txt)
[appium-desktop1.18.3log.txt](https://github.com/appium/appium-desktop/files/5550624/appium-desktop1.18.3log.txt)

**Comment by KazuCocoa** [comment]
I was not able to see all of content, but I think you should report to WAD repo since the same `/source` returned different content size. It means WAD returned different structure to the `/source` endpoint.

```
HTTP/1.1 200 OK
Content-Length: 15155
Content-Type: application/json

{"sessionId":"39D59E78-14B6-44AE-911B-5996AF9324F8","status":0,"value":"<?xml version=\"1.0\" encoding=\"utf-16\"?><Window AcceleratorKey=\"\" AccessKey=\"\" AutomationId=\"\" ClassName=\"Notepad\" FrameworkId=\"Win32\" HasKeyboardFocus=\"False\" HelpText=\"\" IsContentElement=\"True\" IsControlElement=\"True\" IsEnabled=\"True\" IsKeyboardFocusable=\"True\" IsOffscreen=\"False\" IsPassword=\"False\" IsRequiredForForm=\"False\" ItemSt [...]
```

```
HTTP/1.1 200 OK
Content-Length: 15189
Content-Type: application/json

{"sessionId":"BADC0439-704C-4FCE-96BE-F4798C4B6034","status":0,"value":"<?xml version=\"1.0\" encoding=\"utf-16\"?><Window AcceleratorKey=\"\" AccessKey=\"\" AutomationId=\"\" ClassName=\"Notepad\" FrameworkId=\"Win32\" HasKeyboardFocus=\"False\" HelpText=\"\" IsContentElement=\"True\" IsControlElement=\"True\" IsEnabled=\"True\" IsKeyboardFocusable=\"True\" IsOffscreen=\"False\" IsPassword=\"False\" IsRequiredForForm=\"False\" ItemSt [...]
```
