### ISSUE TITLE
Can't find element by id

### ISSUE THREAD

**Issue by ctrickler** [appium/appium-desktop#1635]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Using Appium 1.18.X (or 1.19 beta) can't find element by id. I downgraded to an earlier version we have running on another desktop (Appium 1.12.0) and it can successfully find element.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you share the full log?
It looks like appium itself rather than appium desktop specific. Then, please create an issue in https://github.com/appium/appium with filling the template

**Comment by KazuCocoa** [comment]
needed the log
