### ISSUE TITLE
Blank menu in Appium menu

### ISSUE THREAD

**Issue by zaphodikus** [appium/appium-desktop#1636]
## Appium or Appium Desktop?

Appium manager app
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Still staring at this issue https://github.com/appium/appium-desktop/issues/1061
https://imgur.com/a/tNmidgq
The Appium GUI has a blank menu item in te view menu - it's been like that for about a year now across updates. Windows10.

## Environment

- I am running Appium Desktop version 1.15.1 .
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
v1.15.1 did not have the fix. Newer ones have it
