### ISSUE TITLE
Appium Memory leak during test

### ISSUE THREAD

**Issue by BanChengClub** [appium/appium-desktop#1649]
## The problem

Run the desktop version of Appium on MacOS, test the web page on iOS Safari browser, Appium itself crashed during the test。

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1 / 1.18.3 / 1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina Version 10.15.5
* Node.js version (unless using Appium.app|exe):  v14.5.0
* Npm or Yarn package manager: npm 6.14.5
* Mobile platform/version under test: iOS 13.6.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

Run the desktop version of Appium(1.17.1 or 1.18.3 or 1.19.1) on MacOS,When i test the web page on iOS Safari browser, Appium itself crashed during the test。
Appium 1.17.1 and 1.18.3 will crash and exit about 1.5 hours after the test starts, and Appium 1.19.1 will pop and exit about 1 hour after the test starts.

## Link to Appium logs

https://gist.github.com/BanChengClub/e6d9b898d057779b1e18669f3d6dab8d

## Code To desired_capabilities
`desired_caps = {
            'platformName': 'iOS',
            'platformVersion': '13.6.1',
            'deviceName': iOS_Name,
            'browserName': Safari,
            'browserVersion': ,
            'newCommandTimeout': 360000,
            'detach': True,
            'orientation': RunEnv.mobile_orientation,
            'udid': udid,
            'noReset':True,
            'useNewWDA':False
        }`

**Comment by BanChengClub** [comment]
Use Appium Version v1.20.0-beta.0 ,After the test starts, Appium will increase its memory usage from 200M to 2G in about two and a half hours.

**Comment by KazuCocoa** [comment]
Please try out the latest appium. https://github.com/appium/appium/blob/master/CHANGELOG.md
If such leak still appears, please report it in https://github.com/appium/appium
