### ISSUE TITLE
ios cannot find webview sometimes

### ISSUE THREAD

**Issue by xhongyan** [appium/appium-desktop#1650]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

## The problem
Sometimes cannot find webview successful.
The first time I ran testcase with switching to webview successful , but not occur "The connection has been closed"  on appium log.,  I run testcase the second ,it failed

log:
 Calling AppiumDriver.getContexts() with args: ["c3438bec-e3de-482d-bd1d-3d04416f6c1e"]
[XCUITest] Executing command 'getContexts'
[XCUITest] Getting list of available contexts
[iOS] Retrieving contexts and views
[XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 8.13.1
[RemoteDebugger] useNewSafari --> false
[RemoteDebugger] Checking which communication style to use (non-Safari on platform version '12.3')
[RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using Target-based communication
[RemoteDebugger] Sending connection key request
[RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0): 'setConnectionKey'
[RemoteDebugger] Sending to Web Inspector took 2ms
[RemoteDebugger] Sending connection key request
[RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 2): 'setConnectionKey'
[RemoteDebugger] Sending to Web Inspector took 1ms
[RemoteDebugger] Selecting application
[RemoteDebugger] No applications currently connected.
[XCUITest] No web frames found.
[RemoteDebugger] Received connected applications list: PID:580, PID:585, PID:579, PID:584, PID:65
[RemoteDebugger] Received connected driver list: {}
[W3C (c3438bec)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

 capabilities:
    platformName: iOS
    platformVersion: 12.3.2
    automationName: XCUITest
    unicodeKeyboard: true
    deviceName: '91e5f6a7109f561627b79941fd78cb3a834d029b'
    udid: '91e5f6a7109f561627b79941fd78cb3a834d029b'
    resetKeyboard: true
    noReset: true
    bundleId: tuhu.cn.main
    startIWDP: true
    sessionOverride: true

## Environment

- I am running Appium Desktop version 1.18.3
- I am on Mac

**Comment by KazuCocoa** [comment]
Appium gests WebView stuff via iOS's WebInspector. So, in this case, probably WebInspector needs more time to get all webviews sometimes.

You can relax timeout to check WebViews increasing `webviewConnectTimeout` capability. Defaults to zero to minimise the wait time. https://github.com/appium/appium-xcuitest-driver
Or you can define a method to ask get contexts a couple of times with 1 sec interval for example. It also may help.

**Comment by xhongyan** [comment]
Thank you very much,    I have already solved it by your way.
