### ISSUE TITLE
Not able to get elements in the list for iOS using appium inspeter 

### ISSUE THREAD

**Issue by samkit-jain-art** [appium/appium-desktop#1654]
Hi, 
I am not able to get elements of a table view in iOS app using Appium inspector when there are more than 100 records and it's working fine when we load table view with 50 or 60 records, please suggest how can I get elements in Appium inspector when there are more than 100 records in the table view.
<img width="1078" alt="Screenshot 2020-12-21 at 10 35 02 PM" src="https://user-images.githubusercontent.com/59309809/102802581-e17f1400-43dc-11eb-8a70-0bca3afdb554.png">
Environment
{
  "platformName": "iOS",
  "platformVersion": "13.7",
  "deviceName": "iPhone Simulator",
  "automationName": "XCUITest",
  }
Appium version = App Version 1.18.2

I have attached screenshot for the same

**Comment by KazuCocoa** [comment]
>  it's working fine when we load table view with 50 or 60 records

Then, probably `snapshotMaxDepth` may help.
https://appium.io/docs/en/advanced-concepts/settings/

You can set it via capabilities or AD also has an action to set settings.
https://appium.io/docs/en/writing-running-appium/caps/#update-settings

**Comment by samkit-jain-art** [comment]
I added capability ("snapshotMaxDepth": "40") but still i am getting same issue 
<img width="1074" alt="Screenshot 2020-12-22 at 10 27 26 AM" src="https://user-images.githubusercontent.com/59309809/102850828-5172b600-4440-11eb-871c-bf1d411bac24.png">
<img width="1072" alt="Screenshot 2020-12-22 at 10 23 57 AM" src="https://user-images.githubusercontent.com/59309809/102850834-56376a00-4440-11eb-9dfe-e9749e03ca1e.png">

I have attached screenshot for the same

**Comment by KazuCocoa** [comment]
What about increasing value?
The default value is 50. 

> not able to get elements of a table view in iOS app using Appium inspector when there are more than 100 records
> it's working fine when we load table view with 50 or 60 records

So, the preference is the only idea from my side.

**Comment by samkit-jain-art** [comment]
I tried with the different value like 20,50,100,200 but got the same issue.

**Comment by KazuCocoa** [comment]
What the result of `mobile:source` as `{format: 'description'}`?
https://appium.io/docs/en/commands/mobile-command/
If this command also had elements partially, XCTest framework itself has an issue. Then, you can report it to Apple.

Or another idea is `snapshotTimeout` with `snapshotMaxDepth`. If getting elements recursively took more time to complete, then the timeout may help.
https://appium.io/docs/en/advanced-concepts/settings/

**Comment by samkit-jain-art** [comment]
I tried all these thing but it's not helped me. Also I want to let you know a scenario below:
I am not getting any element for store list screen but when I filter through store name then get elements in the list for filter store. Initially, I thought Appium is not able to load all elements in the list due to a large number of data so I discussed with developer and he told me he is using pagination (load data per page)so I think this issue is not related to a large number of data.

**Comment by KazuCocoa** [comment]
> I tried all these thing but it's not helped me.

I see. Thanks for checking.

Afaik, if these elements did not appear in `{format: 'description'}`, they are not able to get via XCTest framework.
It returns us vanilla XCTest information. Apple only can fix it, unfortunately.

**Comment by samkit-jain-art** [comment]
platformName": "iOS",
  "platformVersion": "13.0",
  "deviceName": "iPhone Simulator",
  "automationName": "XCUITest",
  "app": "/Users/sunnykumrawat/Desktop/AMCI/AMCI.app",
  "ignoreUnimportantViews": true,
  "shouldUseCompactResponses": true,
  "mobile:source": "format: 'xml', excludedAttributes: ['visible']",
  "snapshotMaxDepth": 10000,
  "snapshotTimeout": 1000

I have set this type of Desired Capabilities but still element is not found.. can you please help me

**Comment by kirannkfmc** [comment]
@samkit-jain-art Did you find solution to this problem?

**Comment by samkit-jain-art** [comment]
No I am not able to find element

**Comment by samkit-jain-art** [comment]
Do you have any solution for that
