### ISSUE TITLE
Not Able to Launch Appium Desktop on Big Sur (version 11.1)

### ISSUE THREAD

**Issue by vikrant-github** [appium/appium-desktop#1655]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I'm not able to launch Appium Desktop and this is the error I'm getting on my macbook pro

You do not have permission to open the application “Appium”.
Contact your computer or network administrator for assistance.

I've checked the permissions too however everything seems good
Tried two versions and this is the one which I'm having presently :Appium-1.18.3-mac

## Environment

- I am running Appium Desktop version _<Appium-1.18.3-mac
<img width="295" alt="102876084-bdd6c080-4412-11eb-89ad-756245cfeda4" src="https://user-images.githubusercontent.com/33674426/102917759-bbe12180-4453-11eb-9d93-5d01b3727169.png">
<img width="272" alt="102876075-bb746680-4412-11eb-8aa1-d644ca4b2af2" src="https://user-images.githubusercontent.com/33674426/102917761-bdaae500-4453-11eb-90d2-11b28f1aceea.png">

>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by vikrant-github** [comment]
I'm not able to launch Appium Desktop and this is the error I'm getting on my macbook pro 

You do not have permission to open the application “Appium”.
Contact your computer or network administrator for assistance.

1. I've checked the permissions too however everything seems good
2. Tried two versions and this is the one which I'm having presently :Appium-1.18.3-mac

<img width="272" alt="Screen Shot 2020-12-22 at 5 00 51 AM" src="https://user-images.githubusercontent.com/33674426/102876075-bb746680-4412-11eb-8aa1-d644ca4b2af2.png">
<img width="295" alt="Screen Shot 2020-12-22 at 5 00 25 AM" src="https://user-images.githubusercontent.com/33674426/102876084-bdd6c080-4412-11eb-89ad-756245cfeda4.png">

**Comment by vikrant-github** [comment]
I tried this way to change the permissions
sudo chmod -R 777 /Applications/Appium.app  
sudo chmod -R 755 /Applications/Appium.app  
Result:
“Appium” is damaged and can’t be opened. You should move it to the Trash.

**Comment by vikrant-github** [comment]
Earlier I downloaded the zip file and was having the above issues. I've downloaded image file this time and the error is as follows-
“Appium” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by KazuCocoa** [comment]
Did you tried https://github.com/appium/appium-desktop/issues/1617#issuecomment-729545173 out?

**Comment by vikrant-github** [comment]
Thanks. Actually I was checking the issues however my search keywords were different. I was able to resolve my issue yesterday by executing the same command which is mentioned in #1617 (comment)

**Comment by tiffariel** [comment]
I'm having this issue  on the newest build, I changed the permissions to read & write but it's still not allowing me to open the application
