### ISSUE TITLE
My app is crashing when launching the app after I upgraded to Xcode 12.3 and iOS 14.3.It launches and restarts and continue doing that

### ISSUE THREAD

**Issue by tzdaniel9** [appium/appium-desktop#1669]
Here are the logs:

[Appium] Welcome to Appium v1.18.3
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"com.wawmuzik.app.testing","automationName":"XCUITest","deviceName":"iPhone 12 Pro Max","platformName":"iOS","platformVersion":"14.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.wawmuzik.app.testing","automationName":"XCUITest","deviceName":"iPhone 12 Pro Max","platformName":"iOS","platformVersion":"14.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1610450184410 (13:16:24 GMT+0200 (South Africa Standard Time))
[Appium] Appium v1.18.3 creating new XCUITestDriver (v3.29.0) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "com.wawmuzik.app.testing",
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "deviceName": "iPhone 12 Pro Max",
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "platformVersion": "14.3",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: 805b2b19-cee3-4b4b-b66a-ab5939f76adc
[XCUITest] Current user: 'dany'
[XCUITest] iOS SDK Version set to '14.3'
[iOSSim] Constructing iOS simulator for Xcode version 12.3 with udid 'C7A58530-A78A-4E00-AD3D-B9965753C8B8'
[XCUITest] Determining device to run tests on: udid: 'C7A58530-A78A-4E00-AD3D-B9965753C8B8', real device: false
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1610450188430 (13:16:28 GMT+0200 (South Africa Standard Time))
[XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[BaseDriver] Event 'appConfigured' logged at 1610450188431 (13:16:28 GMT+0200 (South Africa Standard Time))
[BaseDriver] Event 'resetStarted' logged at 1610450188431 (13:16:28 GMT+0200 (South Africa Standard Time))
[simctl] Error running 'terminate': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to lookup in current state: Shutdown
[iOSSim] Cleaning app data files for '', 'com.wawmuzik.app.testing'
[iOSSim] Checking whether simulator has been run before: yes
[iOSSim] Building bundle path map
[Support] Plist file '/Users/dany/Library/Developer/CoreSimulator/Devices/C7A58530-A78A-4E00-AD3D-B9965753C8B8/data/Containers/Data/Application/2EBAF150-E48A-4559-BB2B-20E72770B91A/.com.apple.mobile_container_manager.metadata.plist' does not exist. Returning an empty plist.
[iOSSim] Could not find app directories to delete. It is probably not installed
[BaseDriver] Event 'resetComplete' logged at 1610450188809 (13:16:28 GMT+0200 (South Africa Standard Time))
[WebDriverAgent] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Continuing without capturing device logs: iOS Simulator with udid 'C7A58530-A78A-4E00-AD3D-B9965753C8B8' is not running
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOS] Setting did not need to be updated
[iOSSim] Setting preferences of C7A58530-A78A-4E00-AD3D-B9965753C8B8 Simulator to {"ConnectHardwareKeyboard":true}
[iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Updated C7A58530-A78A-4E00-AD3D-B9965753C8B8 Simulator preferences at '/Users/dany/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"C7A58530-A78A-4E00-AD3D-B9965753C8B8":{"ConnectHardwareKeyboard":true}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID C7A58530-A78A-4E00-AD3D-B9965753C8B8 -RotateWindowWhenSignaledByGuest 1 -ConnectHardwareKeyboard 1 -PasteboardAutomaticSync 0
[iOSSim] Booting Simulator with UDID 'C7A58530-A78A-4E00-AD3D-B9965753C8B8'...
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/dany/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/dany/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[simctl] Error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to boot device in current state: Booted
[simctl] Error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to boot device in current state: Booted
[simctl] Error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to boot device in current state: Booted
[iOSSim] Error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
[iOSSim] Unable to boot device in current state: Booted
[iOSSim] Simulator with UDID C7A58530-A78A-4E00-AD3D-B9965753C8B8 booted in 10.315s
[BaseDriver] Event 'simStarted' logged at 1610450199252 (13:16:39 GMT+0200 (South Africa Standard Time))
[IOSSimulatorLog] Starting log capture for iOS Simulator with udid 'C7A58530-A78A-4E00-AD3D-B9965753C8B8' using simctl
[BaseDriver] Event 'logCaptureStarted' logged at 1610450199854 (13:16:39 GMT+0200 (South Africa Standard Time))
[WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device C7A58530-A78A-4E00-AD3D-B9965753C8B8 on local port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for C7A58530-A78A-4E00-AD3D-B9965753C8B8:8100
[XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WebDriverAgent] WDA is not listening at 'http://127.0.0.1:8100/'
[WebDriverAgent] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1610450200209 (13:16:40 GMT+0200 (South Africa Standard Time))
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[WebDriverAgent] Killing running processes 'xcodebuild.*C7A58530-A78A-4E00-AD3D-B9965753C8B8, C7A58530-A78A-4E00-AD3D-B9965753C8B8.*XCTRunner, xctest.*C7A58530-A78A-4E00-AD3D-B9965753C8B8' for the device C7A58530-A78A-4E00-AD3D-B9965753C8B8...
[WebDriverAgent] 'pgrep -if xcodebuild.*C7A58530-A78A-4E00-AD3D-B9965753C8B8' didn't detect any matching processes. Return code: 1
[WebDriverAgent] 'pgrep -if C7A58530-A78A-4E00-AD3D-B9965753C8B8.*XCTRunner' didn't detect any matching processes. Return code: 1
[WebDriverAgent] 'pgrep -if xctest.*C7A58530-A78A-4E00-AD3D-B9965753C8B8' didn't detect any matching processes. Return code: 1
[WebDriverAgent] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/dany/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp -destination id=C7A58530-A78A-4E00-AD3D-B9965753C8B8 IPHONEOS_DEPLOYMENT_TARGET=14.3 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[WebDriverAgent] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WebDriverAgent] Log file for xcodebuild test: /Users/dany/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.01.12_13-16-42-+0200.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-BCF7B9F6-26EC-4F6F-8DEB-9A3D7EB18F7A/WebDriverAgentRunner-66C51D47-85F2-4F21-9F59-7BD282A35525/Session-WebDriverAgentRunner-2021-01-12_131644-k3Y7Gk.log
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.0","version":"14.3"},"ios":{"simulatorVersion":"14.3","ip":"192.168.8.3"},"ready":true,"build":{"upgradedAt":"1605699701738","time":"Dec 29 2020 14:01:15","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[WebDriverAgent] WebDriverAgent information:
[WebDriverAgent] {
[WebDriverAgent]   "message": "WebDriverAgent is ready to accept commands",
[WebDriverAgent]   "state": "success",
[WebDriverAgent]   "os": {
[WebDriverAgent]     "testmanagerdVersion": 28,
[WebDriverAgent]     "name": "iOS",
[WebDriverAgent]     "sdkVersion": "14.0",
[WebDriverAgent]     "version": "14.3"
[WebDriverAgent]   },
[WebDriverAgent]   "ios": {
[WebDriverAgent]     "simulatorVersion": "14.3",
[WebDriverAgent]     "ip": "192.168.8.3"
[WebDriverAgent]   },
[WebDriverAgent]   "ready": true,
[WebDriverAgent]   "build": {
[WebDriverAgent]     "upgradedAt": "1605699701738",
[WebDriverAgent]     "time": "Dec 29 2020 14:01:15",
[WebDriverAgent]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[WebDriverAgent]   }
[WebDriverAgent] }
[WebDriverAgent] WebDriverAgent successfully started after 7975ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450208255 (13:16:48 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450225233 (13:17:05 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450244150 (13:17:24 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450263754 (13:17:43 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450284431 (13:18:04 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450303780 (13:18:23 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450322514 (13:18:42 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450342138 (13:19:02 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450361356 (13:19:21 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20420797 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x0000000105ded0b3 -[FBSession activeApplication] + 675\n\t4   WebDriverAgentLib                   0x0000000105dfa4fa +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x0000000105dfa3c9 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x0000000105df72b6 +[FBSessionCommands handleCreateSession:] + 2918\n\t7   WebDriverAgentLib                   0x0000000105dc8736 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                 ...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1610450380457 (13:19:40 GMT+0200 (South Africa Standard Time))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wawmuzik.app.testing","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}

**Comment by KazuCocoa** [comment]
Please try with appium 1.20.0 for Xcode 12.3.

> The application under test with bundle id 'com.wawmuzik.app.testing' is not running, possibly crashed

It means the app's process has been stopped as XCTest framework. You should dig the cause in your side first.

**Comment by tzdaniel9** [comment]
[IOS_SYSLOG_ROW] 2021-01-13 11:11:27.457 Df backboardd[20784:cb5f6] [com.apple.BackBoard:EventDelivery] new deferring rules for pid:20781: [
[IOSSimulatorLog] [IOS_SYSLOG_ROW]      ->  reason: "2-deferDiscrete: systemGestures",
[IOSSimulatorLog] [IOS_SYSLOG_ROW]      ->  reason: "60-deferDiscrete: Key Window event focus deferral"
[IOSSimulatorLog] [IOS_SYSLOG_ROW] ]
[IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-01-13 11:11:27.457 Df testmanagerd[20921:c3b6d] [com.apple.dt.xctest:Default] Handling kAXUserTestingNotification from AX element pid: 20781, elementOrHash.elementID: 0.1 (0x7fd3be40cf10)
[IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-01-13 11:11:27.457 Df testmanagerd[20921:c3b6d] [com.apple.dt.xctest:Default] Got user testing notification with payload {
[IOSSimulatorLog] [IOS_SYSLOG_ROW]     controllerClass = SBMainSwitcherViewController;
[IOSSimulatorLog] [IOS_SYSLOG_ROW]     event = ViewDidDisappear;
[IOSSimulatorLog] [IOS_SYSLOG_ROW] }
[IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-01-13 11:11:27.457 Df backboardd[20784:cb5f6] [com.apple.BackBoard:EventDelivery] new resolutions for pid:20781 (
[IOSSimulatorLog] [IOS_SYSLOG_ROW]     ,
[IOSSimulatorLog] [IOS_SYSLOG_ROW]     ,
[IOSSimulatorLog] [IOS_SYSLOG_ROW]
[IOSSimulatorLog] [IOS_SYSLOG_ROW] )



So if i log with iOS logs i get this
