### ISSUE TITLE
Infinite Loading when creating new session

### ISSUE THREAD

**Issue by NC17media** [appium/appium-desktop#1675]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I can't seem to get past an issue where when starting a session for an emulated Android Pixel 4, the window remains in a state of loading with the app source stating 'Gathering initial app source...'.

I have tried starting the appium server from terminal and creating a new session in the desktop app but still running into this issue.

![Screenshot 2021-01-19 at 20 40 48](https://user-images.githubusercontent.com/30310423/105090683-9ff28f00-5a96-11eb-88ae-d03a5451ab08.png)

## Environment

- I am running Appium Desktop version _1.20.1_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by HGzhao** [comment]
I'm using a real phone(TNY-AL00) with Android 10, and I'm experiencing the same problem:  Infinite Loading


# Environment
I am running Appium Desktop version **1.20.2**.
I am on (pick one):
- [ ] Mac
- [x] Windows  -  Win10  20H2    10.0.19042.867
- [ ] Linux

**Comment by KazuCocoa** [comment]
Could you try out https://github.com/appium/appium-inspector once?
If the issue still occurs on the inspector, it is appreciated to let us know on the inspecotor issue.
