### ISSUE TITLE
How to build Latest Appium Desktop code

### ISSUE THREAD

**Issue by Nobleraj** [appium/appium-desktop#1676]
Hi Team,

For 2 days I've been building the Appium latest package as an executable file. But, in the latest Appium release, you have split server and inspector code separately.

It's quite hard to make the connection between the server and inspector.

In the previous release, version - 1.18.0.

you guys handled the server and inspector code  in a single package. So i can make the Appium dev and production build.

In the latest release, version - 1.19.0-beta.0 

Can't make the dev and production build.

Please help me, how could I make dev and production build in the latest release.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md#setting-up may help to build the current master in your local.

Btw, our released versions https://github.com/appium/appium-desktop/releases are still old (one package) format
