### ISSUE TITLE
[Unknown server side exception occur]Webdriver exception is coming when we try to interact with webview element

### ISSUE THREAD

**Issue by saurabhbhandari12** [appium/appium-desktop#1678]
**Environment**
Appium version (or git revision) that exhibits the issue:v1.20
Last Appium version that did not exhibit the issue (if applicable):v1.15
Desktop OS/version used to run Appium: Ubuntu
Node.js version (unless using Appium.app|exe):v15.5.0
Npm or Yarn package manager:6.14.10
Mobile platform/version under test:Android 10
Real device or emulator/simulator:emulators
Appium CLI or Appium.app|exe:Appium CLI
java - 11
**Details**
We are facing webdriver exception  whenever i am trying to interact with webview element after switching from native to webview

**Link to Appium logs -**https://gist.github.com/saurabhbhandari12/188ea94c33c5abd28aa7b0c10cb13c1e

**Comment by KazuCocoa** [comment]
How about the logcat?
