### ISSUE TITLE
Cannot start a session

### ISSUE THREAD

**Issue by hqfking** [appium/appium-desktop#168]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I cannot start a session with Appium Desktop.   

I installed carthage (0.22.0) in /usr/local/bin/.  However, when I try to start a session with Appium desktop, it says the carthage is not found.  

Then it failed when building the WebDriveAgent project.  However, I can run the same command in the terminal which succeeded without any problem.  

Here is the log: 
[startSessionInGUI.pdf](https://github.com/appium/appium/files/970817/startSessionInGUI.pdf)

Here is the log from running it in terminal:
[runWebDriveInTerminal.pdf]
(https://github.com/appium/appium/files/970823/runWebDriveInTerminal.pdf)

## Environment

- I am running Appium Desktop version 1.0.0.
- Xcode 8.3.2
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
What shell are you using? Appium Desktop picks up PATHs from .bashrc, and .bash_profile, but not most other shells.

**Comment by hqfking** [comment]
Thanks. 
I am using tcsh. Let me double check the .bashrc and .bash_profile PATH

**Comment by hqfking** [comment]
the output of the 'echo $PATH' in bash is as following:
bash-3.2$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/hub/share/bin:/apache-maven-3.1.1/bin:/usr/local/bin:/usr/bin

It has /usr/local/bin in the path.  And the carthage is in it

**Comment by hqfking** [comment]
Here is the list in /usr/local/bin:

ash-3.2$ cd /usr/local/bin
bash-3.2$ ls -a
.		automake	cvs		jamf		p4d
..		automake-1.15	distcc		jamfAgent	perl
aclocal		autoreconf	distccd		ksh		pkg-config
aclocal-1.15	autoscan	distccmon-text	lmcrypt80d	plistutil
asn1Coding	autoupdate	glibtool	lsdistcc	rcs
asn1Decoding	bash		glibtoolize	make		rlog
asn1Parser	brew		gmake		mw		sbsetup
autoconf	carthage	ifnames		node		tcsh
autoheader	ci		ios-deploy	npm
autom4te	co		iproxy		p4

**Comment by jlipps** [comment]
hmm. what if you:

```
echo "export PATH=\"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/hub/share/bin:/apache-maven-3.1.1/bin:/usr/local/bin:/usr/bin\"" >> ~/.bashrc
```

and then restart appium?

**Comment by hqfking** [comment]
I created the .bashrc file but the behavior is the same. It still says that it cannot find carthage. 

BTW, where do I need to put this .bashrc?  I put it in my home ~ directory which is a network home directory.

**Comment by jlipps** [comment]
Hmm, I did some looking and put up a PR that might help...

**Comment by hqfking** [comment]
The PR you put up seems failed some build. Not really sure what I need to do at this moment. So I just need to wait for the next release?
