### ISSUE TITLE
Keypad is not popping up when trying to using sendkeys in Saucelabs iPad real device Ios using Appium desktop

### ISSUE THREAD

**Issue by rahul6778** [appium/appium-desktop#1684]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I have a native app where i am trying to enter into input fields such as 'username' and 'password'. Now this is working fine for ios versions like 12.4 or 12.4.8 but with versions like 13.2 and 14 I'm able to enter into username field but not into password field. What i observed it that Keypad is popping up on entering username when using sendKeys from Appium desktop or by using automation code but it is not popping up when trying to enter password due to which it maybe not able to enter the text then and this issue is coming in versions 13.2 and 14 like >13 versions. Is this some issue that persist in versions >13 where the keypad wont popup for textfields or any solution is there for this?

## Environment

- I am running Appium Desktop version _1.19.1 and 1.18.3
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you ask for SauceLabs' support team if it was in their environment?

It seems iOS 13+ has different behavior for the SecureTextField, personally tho.

**Comment by wswebcreation** [comment]
@rahul6778 and @KazuCocoa 

As of iOS 13 secure fields can't be _streamed_, restricted by Apple itself. You can still send data to the field, the keyboard is just not shown anymore due to recording the input which is not allowed

**Comment by rahul6778** [comment]
@wswebcreation
The textfields both username and password are of type XCUIElementTypeOther but problem is coming only in the password field not getting input for ios 13 while working fine for ios 12

**Comment by wswebcreation** [comment]
@rahul6778 

Are you connecting to Simulators or real devices?

**Comment by rahul6778** [comment]
@wswebcreation -- real devices -iPad from Saucelabs

**Comment by wswebcreation** [comment]
@rahul6778 

But are you able to select the element and set a value?

**Comment by wswebcreation** [comment]
Example

**Username field in Sauce Labs**
![image](https://user-images.githubusercontent.com/11979740/107254018-2fa4b100-6a37-11eb-8a68-de070137b6e6.png)

**Username field in Appium Desktop**
![image](https://user-images.githubusercontent.com/11979740/107254055-38958280-6a37-11eb-89ff-af51ca9aeec0.png)

**securePassword-field in Sauce Labs**
![image](https://user-images.githubusercontent.com/11979740/107254244-6aa6e480-6a37-11eb-8b17-49555c603241.png)

**securepassword-field in Sauce after submitting the data**
![image](https://user-images.githubusercontent.com/11979740/107254408-932ede80-6a37-11eb-8d7d-8f1ac9ce5537.png)

**securepassword-field in Appium Desktop after "Send Keys"**
![image](https://user-images.githubusercontent.com/11979740/107254509-ac378f80-6a37-11eb-9b88-916a4904c2ba.png)

So it looks like it works, only you don't see the keyboard in the video/Appium Desktop due to Apple Security

**Comment by rahul6778** [comment]
@wswebcreation - I have tried swaglabs earlier and on i was successfull in entering both user and password for this app. I m trying in a different native app in real device. Also keyboard in appium desktop i m seeing in case of entering the username but it isnt coming in case of password.Also in saucelabs logs i see the response as 200 both for username and password.

Regarding the selection of the element i m using xpath  for username and password and appium desktop is successfully highlighting it and then for entering username keypad comes up and then text is entered but for password keypad goes away.

**Comment by wswebcreation** [comment]
Then please file a ticket with all information with the support team of Sauce Labs

**Comment by rahul6778** [comment]
@wswebcreation sure i will and do you know if its possible to enable/disable 'third party authentication'  for an app by going to Settings in ios device by appium code or this has to be done manually only?
