### ISSUE TITLE
i have some question in Wda

### ISSUE THREAD

**Issue by TesterQiao** [appium/appium-desktop#169]
Mac  appium1.6.4  real device IOS10.2
Every time i start appium,wda will setup  in  real ios device ,and sometime appear socket up,	
Can not be installed every time？

Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body

**Comment by imurchie** [comment]
You can build and install and start yourself, and use the `webDriverAgentUrl` capability to specify where it is running.
