### ISSUE TITLE
Does WebDriverAgentRunner-Runner work on Apple Silicon ?

### ISSUE THREAD

**Issue by angelmic** [appium/appium-desktop#1698]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

WebDriverAgentRunner-Runner can't run on Apple Silicon

```
WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (75832) encountered an error (Failed to load the test bundle. If you believe this error represents a bug, please attach the result bundle at /Users/richard/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.17_11-58-30-+0800.xcresult. (Underlying Error: 無法載入套件「WebDriverAgentRunner」，因為此套件沒有目前架構的版本。. 請試著安裝此套件的通用版本。. dlopen_preflight(/Users/richard/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
	/Users/richard/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture))
** TEST EXECUTE FAILED **
```

Please Help.

## Environment

- I am running Appium Desktop version _1.20.2_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you share the full appium server log with `appium:showXcodeLog`?
It seems your environment failed to build the module.

My M1 macOS env worked before, but potentially other environments could have an issue.

**Comment by fida10** [comment]
https://github.com/appium/appium/issues/15119

I believe I am having the same issue

**Comment by fida10** [comment]
This ended up solving my issue, maybe it will work for you too. It was the M1 chip for me in the end, you just need to turn off the "Build Active Architecture Only" setting in Xcode.

https://github.com/appium/java-client/issues/1444#issuecomment-781078298

**Comment by KazuCocoa** [comment]
Thanks.
Hm..
 The preference was `YES` in a new project. My M1 macOS (NodeJS 12, Xcode 12.4 and Ruby env) case also worked with the current preference, so we need more cases if we should set the preference as `no` by default in WDA.

**Comment by angelmic** [comment]
> Could you share the full appium server log with `appium:showXcodeLog`?

Excuse me. How do I set this argument in appium-desktop ?

**Comment by angelmic** [comment]
@fida10  Thanks, this workaround works for me.

**Comment by KazuCocoa** [comment]
It is capabilities > How do I set this argument in appium-desktop ?
https://github.com/appium/appium-xcuitest-driver#capabilities
