### ISSUE TITLE
How to use Appium Inspector in Appium1.6.4

### ISSUE THREAD

**Issue by santhosh12992** [appium/appium-desktop#170]
Appium Desktop - 1.6.4:

I have installed appium desktop in my mac machine(OS10.12) two days back. I am not able to figure out how to use the Appium Inspector.

I have right clicked on my Appium GUI screen after starting the appium server and clicked Inspect Element and i got a screen similar to developer tools in chrome.

Now the issue is, within the Inspector I am getting my Appium server logs instead of my emulator screen. Kindly help me.

## Environment

- I am running Appium Desktop version _<1.6.4
![screen shot 2017-05-04 at 5 54 51 pm](https://cloud.githubusercontent.com/assets/23401123/25703339/d22c36be-30f2-11e7-9b46-399d1c402a1e.png)
>_.
- I am on (pick one):
    - [ ] Mac

**Comment by jlipps** [comment]
You found the Chrome inspector of Appium Desktop itself, which is not the Appium Inspector. To access the Appium Inspector, follow the instructions in the README. Essentially, with a server running, click "New Session", then go through the process of setting up your capabilities and starting a session. When it's launched the Appium Inspector window will appear.
