### ISSUE TITLE
[Appium 1.19.1] Issue with autoGrantPermissions capability

### ISSUE THREAD

**Issue by robertosalemi** [appium/appium-desktop#1700]
Hi!
I have a problem with autoGrantPermissions capability.
If I set it to **true**, I receive the error:
`[W3C] Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
[MJSONWP (9e14c4e1)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?`

If I set it to **false**, after the application start I see the popups
* to allow the app to access to photo, file, etc...
* to allow to registry call
etc...
These popups are shown every time that Appium open the app and not only one first time.

The problem is that if, through Appium, I tap confium button of these popup, the view beetwen tablet and appium are not syncronized, until appium lock the screen.

## Environment
Appium 1.19.1
Windows 8.1
Node.js 14.15.1
Android 9
Real device

I hope give you all information! ;)

**Comment by robertosalemi** [comment]
I referer to thise message:
<a href="https://ibb.co/sRy4kRc"><img src="https://i.ibb.co/2hgrmhR/Cattura.jpg" alt="Cattura" border="0"></a>

The tap on the first works, when I tap on the second message the device goes on, appium no ...

I don't understand why, this a piece of log about the error:
[log.txt](https://github.com/appium/appium-desktop/files/6022827/log.txt)

**Comment by KazuCocoa** [comment]
Can the view capture via https://adbshell.com/commands/adb-shell-screencap ?

**Comment by robertosalemi** [comment]
> Can the view capture via https://adbshell.com/commands/adb-shell-screencap ?

No, the command generate a corrupt file.
I tried to do a manually screenshot, but this operation is blocked by developer.

For this reason, Appium Desktop doesn't work!

There another way to inspect app code to use with Selenium?

Thank you very much for good support!

**Comment by KazuCocoa** [comment]
Thanks.
Then, the page (view?) has an issue to get a screenshot...
AD is designed to work with a page source and the screenshot's mapping, so current behaviour is expected because of the screenshot error.

As a workaround, you can go through the screenshot error view by hand and click reload button addressed in https://github.com/appium/appium-desktop/issues/1700#issuecomment-783122077 on the next view.
Then, AD captures the current view and the page source.

---

I usually use https://github.com/appium/ruby_console to inspect an app interactively.

**Comment by robertosalemi** [comment]
Hi!
Today the developer released a version of the app without blocking screenshots.
Appium Desktop now works perfectly.

Thanks for your support and patience! :)
