### ISSUE TITLE
WebDriverAgent build in XCode is successful but when Product>>Test is done it fails without any error

### ISSUE THREAD

**Issue by MonalisaSB** [appium/appium-desktop#1705]
## Appium or Appium Desktop?
There are 2 issue being encountered here.
1. WebDriverAgent test via XCode
2. Appium Inspector session not created via Appium Desktop 

## The problem
Issue 1:
WDA is set with all correct team and signing capabilities. When I build the WDA it is successful but when I perform Product-->Test, build gets successful, WDA is installed on real device but Test fails without showing any error.
When I execute my test scripts, it fails with error: "Original error: Failed to receive any data within the timeout: 5000". This issue is happening only after iOS upgrade to 14.4 version. All the required bootstrap dependencies are up to date as well.

Issue 2:
When I am trying to create Appium Inspector session in Appium Desktop getting the same error "Original error: Failed to receive any data within the timeout: 5000". and session is not created.
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/6023024/appium-server-logs.txt)
![Appium Desktop Error](https://user-images.githubusercontent.com/48469700/108730482-9656be00-7551-11eb-8fb6-b83e17288a54.png)

Please help me to resolve this issue. I have trying upgrading Appium version to 1.20.2 but getting same error. 

## Environment
- I am running Appium Desktop version 1.20.0-beta.0
- I am on 
    - Mac -macOS Catalina version 10.15.7
    - iOS - Real Device, iPhone XR Version 14.4
    - Appium version via npm 1.20.0
    - XCode Version 12.4

**Comment by KazuCocoa** [comment]
What about the Appium server log with `'appium:showIOSLog': true`  and `'appium:showXcodeLog': true`?

Potentially it is similar to https://github.com/appium/appium/issues/15122 
If it was IDE connection stuff, i guess the root is Xcode private later (so only Apple can fix it)

**Comment by MonalisaSB** [comment]
As asked I added the capabilities in Appium Desktop and attaching the logs
[appium-server-logs_1.txt](https://github.com/appium/appium-desktop/files/6028671/appium-server-logs_1.txt)

In Xcode today I saw below error as well. I tried changing cable, restarting both mac and iPhone but no change in issue, Still unable to execute scripts.
![Device_Connection_Error](https://user-images.githubusercontent.com/48469700/108839040-80510800-75fa-11eb-9a1a-b3985ce6cca8.png)

I do not see this to be IDE issue as Appium Inspector is also unable to create sessions for object spying. Please provide some solution to this issue as it is blocking execution of automation suite.

**Comment by KazuCocoa** [comment]
Probably you should ask the device issue to Apple...
I haven't seen such issues, so no good advice i have, unfortunately.

Potentially, uncheck the connect via network improve the behaviour. It sometimes made my local device connection unstable before.
