### ISSUE TITLE
Add a user-agent to all the requests being sent via Appium Desktop

### ISSUE THREAD

**Issue by huzaifaiftikhar** [appium/appium-desktop#1708]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
1. Currently, whenever a command/request is hit via Appium Desktop the user-agent is logged as `admc/wd/x.y.z`, this happens because we use the [admc](https://github.com/admc/wd) library for sending commands (excluding the master branch where we have started using [web2driver](https://github.com/projectxyzio/web2driver) as well)
2. Since admc can be used by other apps as well and is not just specific to Appium Desktop, therefore, the cloud providers are unable to identify by looking at the user-agent that whether the requests are coming from Appium Desktop or not.
3. As good practice and as per [RFC 7231](http://svn.tools.ietf.org/svn/wg/httpbis/specs/rfc7231.html#header.user-agent), an app should send a User-Agent, therefore, we should include a user-agent in all the request that we send via Appium Desktop. Ideally the user-agent should contain the name of the App and the version as well that makes it look something like this, `Appium Desktop - v1.20.2`
4. Found a similar issue - https://github.com/appium/appium/issues/4065

**Proposed Solution**
Since we use various libraries like admc/wd, request, etc. for sending HTTP requests, therefore, we can override the NodeJS' base modules such as [NET](https://nodejs.org/api/net.html) & [HTTP](https://nodejs.org/api/http.html) modules and extend these modules to add the extra header i.e. a user-agent for all the requests that we make via Appium Desktop.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
yes.

Probably current master has like `appium-desktop/version` but wd base was `admc/wd/` for now.

**Comment by huzaifaiftikhar** [comment]
@KazuCocoa Shouldn't we make similar changes to the master branch as well? The issue is still present in the master branch. I had also commented the same on the PR https://github.com/appium/appium-desktop/pull/1716#issuecomment-791646519

**Comment by KazuCocoa** [comment]
Current new one has like `appium-inspector/2.0.0-beta.0` as part of UA since the inspector part is called as `inspector` in the current master. It had no `adam/wd` in the UA.

e.g:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) appium-inspector/2.0.0-beta.0 Chrome/78.0.3904.130 Electron/7.3.3 Safari/537.36,
```

**Comment by huzaifaiftikhar** [comment]
I thought we could use the same UA for all the releases for consistency but this looks fine as well.

**Comment by KazuCocoa** [comment]
Ok, then, appium-inspector is proper one, since adding UA in the old one was after splitting one desktop app into the server part and the inspector part (and tweaked them).
Let me tweak it in 1.20 branch later.
