### ISSUE TITLE
Could not start session, when starting appium inspector

### ISSUE THREAD

**Issue by NayanaGopinath** [appium/appium-desktop#1709]
## Appium or Appium Desktop?
Unable to start inspector session ,tried using Automatic server ,Custom Server

## The problem

unable to start appium inspector due to the following error for android emulator of version 10

<img width="1053" alt="Screenshot 2021-02-26 at 4 48 21 PM" src="https://user-images.githubusercontent.com/79698266/109293909-73c6ec80-7852-11eb-8040-ec7249dc6732.png">

The desired capabilities provided
{
  "deviceName": ,
  "platformName": ,
  "appPackage": "",
  "automationName": "",
  "appActivity": ""
}
## Environment

- I am running Appium Desktop version _1.20.2
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Please attach the full Appium log as GitHub GIST

**Comment by NayanaGopinath** [comment]
> Please attach the full Appium log as GitHub GIST

There is no log generated
`[Appium] Welcome to Appium v1.20.2
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723`

**Comment by KazuCocoa** [comment]
Do you have any proxies/security preferences on your machine?

Generally, AD sends a request to `http://lcalhost:4723`, but perhaps the request did not reach to the appium server.
No new log means your request was proxies to somewhere.

**Comment by KazuCocoa** [comment]
It seems local network or proxy blocked the request.
