### ISSUE TITLE
Error: Could not find zipalign Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

### ISSUE THREAD

**Issue by alvy54** [appium/appium-desktop#171]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When automationName is set to uiautomator2 in capabilities, I am getting:
`An unknown server-side error occurred while processing the command. Original error: Could not find zipalign Please set the ANDROID_HOME environment variable with the Android SDK root directory path. (Selenium::WebDriver::Error::UnknownError)`

However, if I start appium from the command line and not through Appium Desktop I don't get the error.

Here is what I see from Appium Desktop's server log:
```
[ADB] Checking whether zipalign is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for zipalign.
[ADB] Error: Could not find zipalign Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at ADB.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:86:9)
```

Running appium-doctor shows:
```
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 7.9.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/alvin.fajardo
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/alvin.fajardo/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/alvin.fajardo/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/alvin.fajardo/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/alvin.fajardo/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

## Environment

- I am running Appium Desktop version 1.0.0.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Please read [this part of the readme](https://github.com/appium/appium-desktop/blob/master/README.md#appium-cant-detect-environment-variables-on-mac) and report back if it doesn't resolve your issue, and I'll reopen.

**Comment by alvy54** [comment]
Hi @jlipps, I installed shell-env per the readme but I am still getting the same error.  I verified that it is installed properly and returning my environment variables via:
```
const shellEnv = require('shell-env');
console.log(shellEnv.sync());
```

When I built the app locally and ran it in non-development mode the error doesn't show up though.

**Comment by jlipps** [comment]
@alvy54 you don't need to install shell-env. shell-env is already included in Appium Desktop. You just need to make sure that JAVA_HOME is exported in one of the shell files that shell-env picks up.

**Comment by swamigb** [comment]
Make sure you add build-tools into your path.
You bashrc  file should look something like below.
________________________________________________
ANDROID_SDK_ROOT=$HOME/Android/Sdk
PATH=$PATH:$ANDROID_SDK_ROOT/tools
PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
PATH=$PATH:$ANDROID_SDK_ROOT/emulator
PATH=$PATH:$ANDROID_SDK_ROOT/build-tools:$ANDROID_SDK_ROOT/build-tools/29.0.3

export $PATH
