### ISSUE TITLE
EnableMultiWindows capability only shows the bottom system UI only in Appium inspector

### ISSUE THREAD

**Issue by jackyxiao126** [appium/appium-desktop#1728]
Appium Desktop

How to switch window on Appium Desktop? Currently, only system Menu can be obtained,  I can't inspector the correct window on Appium Desktop source page.

![image](https://user-images.githubusercontent.com/22311094/110570491-ead47d00-8190-11eb-84dd-376d7e338961.png)

**Comment by KazuCocoa** [comment]
Could you share the full appium server log?

`enableMultiWindows` is defined as settings API https://github.com/appium/appium-uiautomator2-driver#settings-api , so you should specify it as `"[settings]enableMultiWindows": true,` when you add it in capabilities.
https://appium.io/docs/en/writing-running-appium/caps/#update-settings
If you set it, how about the result of [page source](http://appium.io/docs/en/commands/session/source/)?

**Comment by KazuCocoa** [comment]
If the above setting was enabled, but these elements were not shown, then I think they are not available via Android's accessibility node. Then, Appium cannot do anything, unfortunately.

**Comment by KazuCocoa** [comment]
the above comment was misreading.
https://github.com/appium/appium-desktop/issues/1529#issuecomment-834375722 probably helps
