### ISSUE TITLE
The current pre-release 1.20.2-2 has code changes from the master branch

### ISSUE THREAD

**Issue by huzaifaiftikhar** [appium/appium-desktop#1755]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
The current pre-release tag i.e. [1.20.2-2](https://github.com/appium/appium-desktop/releases/tag/v1.20.2-2) has code [changes from the master branch](https://github.com/appium/appium-desktop/compare/v1.20.2-1...v1.20.2-2) instead of the [1.20 branch](https://github.com/appium/appium-desktop/tree/1.20). We should fix the pre-release tag so that it points to the correct commit i.e. https://github.com/appium/appium-desktop/commit/ed91dfb543902a8ff2e5f6878159f4739dea5d1d.

The correct code differences between the 1.20.2-1 & 1.20.2-2 pre-releases should be [these](https://github.com/appium/appium-desktop/compare/v1.20.2-1...1.20.2-2).

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by huzaifaiftikhar** [comment]
@KazuCocoa or @jlipps Can you please take a look at this?

**Comment by KazuCocoa** [comment]
Thanks. yes, https://github.com/appium/appium-desktop/commits/1.20.2-2 must be the expected one. `v1.20.2-2` was a wrong tag. Will modify them.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.20.2-3 should be fine.
