### ISSUE TITLE
Appium Desktop with Appium Beta

### ISSUE THREAD

**Issue by simonsymhoven** [appium/appium-desktop#1762]
## Appium or Appium Desktop?

Don't know. I think both?

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I installed appium@beta with `npm install -g appium@beta` and I am able to use the Appium cli with the Xcode beta version and my iOS beta devices. I also installed the latest software of Appium-desktop. If i use the appium-desktop software i can connect to the device but there occurs an error „unrecognized selector sent to instance“ which is fixed in the appium@beta software. So how can i connect appium-desktop with the appium@beta software? Has appium-desktop its own internal appium or am i able to reference the beta version somehow? Can I change the version of underlying appium to the beta version or how can i fix this issue for appium-desktop? 

## Environment

- I am running Appium Desktop version 1.20.2.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Did you connect to you `appium@beta` as https://github.com/appium/appium-desktop#connect-to-local-appium-server ?
If yes, could you explain more about how you launched Appium Desktop and launched the inspector?

**Comment by simonsymhoven** [comment]
I am not able to connect with the appium desktop launcher to an existing appium server or is this possible? In the docs i read that is possible to connect to an existing session with a device, but thats not that what want to do. 

Nevermind, i fixed this issue by replacing the internal appium folder of appium desktop:

```
/Applications/Appium/Contents/Resources/app/node_modules/appium
```

With the one of the appium@beta installation:

```
/usr/local/lib/node_modules/appium
```

Now can i start appium desktop with an appium@beta software and add session via the appium desktop launcher. 

Thanks a lot!

**Comment by nerminezar** [comment]
@simonsymhoven i was stuck like you , and i did ur solution finally it worked , nice hack ;)

**Comment by KazuCocoa** [comment]
I think you moved `appium@beta` outside Appium Desktop to inside Appium Desktop.
`/usr/local/lib/node_modules/appium` also can run independently from Appium Desktop, so you also could run appium with `appium` command without Appium Desktop. (it was not to attach to an existing session). Then, you was able to establish a session using Appium Desktop's inspector.

From now on, the inspector part moved to https://github.com/appium/appium-inspector , btw.
