### ISSUE TITLE
iosApp,appium-desktop 无法获取页面的全部元素 

### ISSUE THREAD

**Issue by zhongtai-git** [appium/appium-desktop#1768]
日志：[MJSONWP (bfd25df4)] Calling AppiumDriver.getPageSource() with args: ["bfd25df4-4387-4317-874b-ff205a3ec080"]
[XCUITest] Executing command 'getPageSource'
[WD Proxy] Matched '/source' to command name 'getPageSource'
只能获取到部分元素
![affcf121-e995-45e3-bfb2-394b6dba1aa7](https://user-images.githubusercontent.com/60092975/114534479-9afe3f80-9c81-11eb-9148-990385349561.jpg)

**Comment by zhongtai-git** [comment]
只获取到了绿色和红色 view 的元素，粉色 view 元素没有获取到，这个页面比较复杂，怎么获取到全部的元素？有什么好的解决方案吗？

**Comment by KazuCocoa** [comment]
Could you fill in the issue template such as the AD version etc?
It is helpful to translate them in English (with some translation apps are enough)

**Comment by zhongtai-git** [comment]
> 您可以填写问题模板，例如AD版本等吗？
> 用英语翻译它们很有帮助（使用一些翻译应用程序就足够了）

appium-desktop  version:1.19.1

经过多次测试，页面滑动到指定位置，元素（之前没有加载出来的元素）是可以加载到的。今天重新跟开发对了一下，首页进入页面，绿色层级是覆盖全部，只有下拉到指定的位置，绿色层级才会覆盖部分屏幕，所有元素（之前没有加载出来的元素）是可以加载到的。这就解释通了，appium 只能拉去到最上层的元素，这个问题有什么优化方案吗？
首次进入首页
![1](https://user-images.githubusercontent.com/60092975/114647449-aef08280-9d0f-11eb-9ac6-14de49642be4.png)
滑动到指定位置
![2](https://user-images.githubusercontent.com/60092975/114647475-bd3e9e80-9d0f-11eb-99ab-cbdac4ba136a.png)

**Comment by KazuCocoa** [comment]
Please create a new issue in appium-inspector. Then, it is appreciated to describe in English (with any translator like google translator is enough)
