### ISSUE TITLE
get_screenshot_as_file(self, filename)截图会被拉伸

### ISSUE THREAD

**Issue by hexiaolong-coco** [appium/appium-desktop#1770]
![dependAsset](https://user-images.githubusercontent.com/57431480/115225201-65090180-a140-11eb-8607-690b62bb256c.png)
![CoreJsTest](https://user-images.githubusercontent.com/57431480/115225392-98e42700-a140-11eb-91bc-bbca9485a8e3.png)
![layout-basic-horizontal](https://user-images.githubusercontent.com/57431480/115225466-b0231480-a140-11eb-8a1f-9b43c00c7f1f.png)

## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by hexiaolong-coco** [comment]
[appium.txt](https://github.com/appium/appium-desktop/files/6340128/appium.txt)
![737fc4fb-3457-482b-91fd-ce70aa52da92](https://user-images.githubusercontent.com/57431480/115327241-29fae280-a1c1-11eb-9a01-cbe869d75bc1.jpg)
![企业微信截图_e574a3d8-52a0-4df1-9dab-d36fa87449b0](https://user-images.githubusercontent.com/57431480/115327245-2b2c0f80-a1c1-11eb-9140-5f5ad9da9d48.png)

**Comment by hexiaolong-coco** [comment]
[appium.txt](https://github.com/appium/appium-desktop/files/6340135/appium.txt)

**Comment by hexiaolong-coco** [comment]
![image](https://user-images.githubusercontent.com/57431480/115328465-3e3fdf00-a1c3-11eb-8c99-96afa20fe43f.png)
![image](https://user-images.githubusercontent.com/57431480/115328509-50ba1880-a1c3-11eb-9405-c39ba41d29f9.png)

![image](https://user-images.githubusercontent.com/57431480/115328538-57489000-a1c3-11eb-80ee-a1c0db96adc2.png)
![image](https://user-images.githubusercontent.com/57431480/115328565-5dd70780-a1c3-11eb-9cb7-8ce400f42574.png)

**Comment by KazuCocoa** [comment]
Thanks.
It seems you should use `screenshotOrientation` https://github.com/appium/appium-xcuitest-driver#settings-api to enforce the orientation. The root cause is XCTest (by Apple) returned portrait orientation information while the device is landscape. This situation can occur, so we provide the settings API.
(I heard this issue happened frequently in gaming apps)

**Comment by hexiaolong-coco** [comment]
I hava try to enforce the orientation. But it's helpless.

**Comment by hexiaolong-coco** [comment]
![Uploading image.png…]()
How can I use this API?

**Comment by KazuCocoa** [comment]
The link as a link to https://appium.io/docs/en/advanced-concepts/settings/ and https://appium.io/docs/en/commands/session/settings/update-settings/index.html

**Comment by hexiaolong-coco** [comment]
![image](https://user-images.githubusercontent.com/57431480/115358683-7d385980-a1f0-11eb-8182-cc9a3ba56561.png)
Like this?

**Comment by KazuCocoa** [comment]
Yes. The 'auto' did not work in your case, so you should specify the orientation.

**Comment by hexiaolong-coco** [comment]
My problem has resolved perfectly，thank you very much!!!
