### ISSUE TITLE
QQ和UC浏览器的横竖屏旋转不生效

### ISSUE THREAD

**Issue by hexiaolong-coco** [appium/appium-desktop#1772]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux
![image](https://user-images.githubusercontent.com/57431480/115806275-0c27ba80-a419-11eb-9aae-9ca590d0ac55.png)
![image](https://user-images.githubusercontent.com/57431480/115806311-1b0e6d00-a419-11eb-9770-a2ac93a92b95.png)
UC和QQ浏览器，设置横竖屏不生效

**Comment by KazuCocoa** [comment]
- Please update the title in English. (Translation tools are ok)
- Please attache the full appium log. Then, could you call `driver.orientation` after the changing orientation command?


https://developer.android.com/reference/android/app/UiAutomation#setRotation(int) is the end in Appium/UIA2 side, so the cause could be Android framework side. (Then, nothing can do in Appium)

**Comment by KazuCocoa** [comment]
As Appium, it calls Android API to set the orientation. So, I guess the app under, the device or Android API did not work well.
Logcat might help to check if the root cause is if Android API.
