### ISSUE TITLE
Unable to Start Session. Throws error Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\manis\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s f8ff6a4e install -g 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1

### ISSUE THREAD

**Issue by coder-cell** [appium/appium-desktop#1774]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

Log:
_Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\manis\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s f8ff6a4e install -g 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'' exited with code 1_

**Comment by coder-cell** [comment]
Issue resolved.
Enabled security setting and allow install option through USB debugging.

**Comment by kopax-polyconseil** [comment]
how do you do that ?
