### ISSUE TITLE
Appium desktop run on Mac OS Big Sur 11.3.1 with Xcode12.5 get app source fail

### ISSUE THREAD

**Issue by pxrgod** [appium/appium-desktop#1784]
## Appium or Appium Desktop?
Appium Desktop

## The problem
when I change my macOS to 11.3.1, I find one problem: Appium desktop can start app, but can not get screenshot from app
and create one error:
[debug] [35m[XCUITest][39m Executing command 'getScreenshot'
[debug] [35m[XCUITest][39m Taking screenshot with WDA
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/92DC0823-B5E4-47E0-BA65-388CABAC3F6F/screenshot] with no body
[info] [35m[WD Proxy][39m Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2835f5180","traceback":"(\n\t0   CoreFoundation                      0x00000001b1d1e5c0 472C9193-115D-34CD-AD1D-0E7E091C9432 + 1185216\n\t1   libobjc.A.dylib                     0x00000001c5d9842c objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001b1c28a2c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 178732\n\t3   CoreFoundation                      0x00000001b1d21130 472C9193-115D-34CD-AD1D-0E7E091C9432 + 1196336\n\t4   CoreFoundation                      0x00000001b1d23420 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x000000010770b944 -[XCUIDevice(FBHelpers) fb_rawScreenshotWithQuality:error:] + 156\n\t6   WebDriverAgentLib                   0x000000010770b810 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 88\n\t7   WebDriverAgentLib                   0x00000001076ab358 +[FBScreenshotCommands handleGetScreenshot:] + 1...
[debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
[warn] [35m[XCUITest][39m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2835f5180

## Environment
- I am running Appium Desktop version _1.20.2
- I am on (pick one):
    - [ ] Mac Big Sur 11.3.1
    - [ ] Xcode 12.5

**Comment by KazuCocoa** [comment]
AD which has Appium 1.21.0 hasn't been pushed yet.

**Comment by pxrgod** [comment]
> AD which has Appium 1.21.0 hasn't been published yet.
> You can try https://github.com/appium/appium-desktop/tree/1.21#connect-to-local-appium-server out to connect to a local appium.

no Appium desktop version available?

**Comment by KazuCocoa** [comment]
Just created a version.
You could try out https://github.com/appium/appium-desktop/releases/tag/v1.21.0
