### ISSUE TITLE
Getting stale connection issue and chrome is getting closed after sometime.

### ISSUE THREAD

**Issue by chaitu516** [appium/appium-desktop#1788]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Getting stale connection issue and chrome is getting closed after sometime.

## Environment

- I am running Appium Desktop version 1.20.2.
- I am on  - [ ] Windows

**Comment by chaitu516** [comment]
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/6460264/appium-server-logs.txt)
here is the logs

**Comment by chaitu516** [comment]
not sure how it was closed, reopening the issue

**Comment by KazuCocoa** [comment]
The attached log is WinAppDriver, so it seems https://github.com/Microsoft/WinAppDriver is proper place rather than here.

**Comment by KazuCocoa** [comment]
Please report it to WAD.
