### ISSUE TITLE
Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by RaviMv08** [appium/appium-desktop#1789]
## Appium Desktop 
An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '192.168.0.103', ip: 'fe80:0:0:0:104d:42e4:1f1:c9b3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.10'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/mallikarjunaravi/Dco..., automationName: XCUITest, browserName: , bundleId: org.usada.dco-dev, databaseEnabled: false, deviceName: MDC-Mobile, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, noReset: true, platform: MAC, platformName: iOS, platformVersion: 14.4.2, takesScreenshot: true, udid: 00008020-000971000268402E, webStorageEnabled: false}
Session ID: e6bef3cf-7315-4ae0-a679-456ede20c779
null  An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '192.168.0.103', ip: 'fe80:0:0:0:104d:42e4:1f1:c9b3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.10'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/mallikarjunaravi/Dco..., automationName: XCUITest, browserName: , bundleId: org.usada.dco-dev, databaseEnabled: false, deviceName: MDC-Mobile, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, noReset: true, platform: MAC, platformName: iOS, platformVersion: 14.4.2, takesScreenshot: true, udid: 00008020-000971000268402E, webStorageEnabled: false}
Session ID: e6bef3cf-7315-4ae0-a679-456ede20c779
masterMobile.CaseFailedException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '192.168.0.103', ip: 'fe80:0:0:0:104d:42e4:1f1:c9b3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.10'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/mallikarjunaravi/Dco..., automationName: XCUITest, browserName: , bundleId: org.usada.dco-dev, databaseEnabled: false, deviceName: MDC-Mobile, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, noReset: true, platform: MAC, platformName: iOS, platformVersion: 14.4.2, takesScreenshot: true, udid: 00008020-000971000268402E, webStorageEnabled: false}
Session ID: e6bef3cf-7315-4ae0-a679-456ede20c779
at bsn.BSN_DCO_AR.assert_athlete_information_positive_data(BSN_DCO_AR.java:1394)
	at tsd.TSD_Field_Validation_UAR.verify_Field_All_In_Athlete_Information(TSD_Field_Validation_UAR.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem is 
im running pipeline in azure devpos frequently getting this error after few min orignal error Soctket hang up

_Replace this section with a description of your issue_

## Environment
mac big sur 11 version 
ipad 3rd gen 14.4.2 version 
xcode 12.1

- I am running Appium Desktop version _<1.20.1>_
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by Thuytien** [comment]
I always got that issue after a few minutes starting Appium
[MJSONWP (4668e692)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[MJSONWP (4668e692)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[MJSONWP (4668e692)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/4668e692-65ec-4d03-b996-d3240d50e45a/screenshot 500 1024 ms - 247

[
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/6471347/appium-server-logs.txt)
](url)

**Comment by KazuCocoa** [comment]
```
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body[debug] [35m[iProxy@95793cc5:8100][39m Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[info] [35m[WD Proxy][39m socket hang up
[debug] [35m[WebDriverAgent][39m WDA is not listening at 'http://127.0.0.1:8100/'
[debug] [35m[WebDriverAgent][39m WDA is currently not running. There is nothing to cache
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
```

This response is weird. Appium/WDA does not have such response.
What server was using `http://127.0.0.1:8100` on your device under test?


btw, when your log also had the below line. It was expected.

```
[info] [35m[WD Proxy][39m socket hang up[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.5","version":"14.5"},"ios":{"ip":"192.168.0.66"},"ready":true,"build":{"upgradedAt":"1620631774000","time":"May 12 2021 15:45:25","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[debug] [35m[WebDriverAgent][39m WebDriverAgent information:
[debug] [35m[WebDriverAgent][39m {
[debug] [35m[WebDriverAgent][39m   "message": "WebDriverAgent is ready to accept commands",
[debug] [35m[WebDriverAgent][39m   "state": "success",
[debug] [35m[WebDriverAgent][39m   "os": {
[debug] [35m[WebDriverAgent][39m     "testmanagerdVersion": 28,
[debug] [35m[WebDriverAgent][39m     "name": "iOS",
[debug] [35m[WebDriverAgent][39m     "sdkVersion": "14.5",
[debug] [35m[WebDriverAgent][39m     "version": "14.5"
[debug] [35m[WebDriverAgent][39m   },
[debug] [35m[WebDriverAgent][39m   "ios": {
[debug] [35m[WebDriverAgent][39m     "ip": "192.168.0.66"
[debug] [35m[WebDriverAgent][39m   },
[debug] [35m[WebDriverAgent][39m   "ready": true,
[debug] [35m[WebDriverAgent][39m   "build": {
[debug] [35m[WebDriverAgent][39m     "upgradedAt": "1620631774000",
[debug] [35m[WebDriverAgent][39m     "time": "May 12 2021 15:45:25",
[debug] [35m[WebDriverAgent][39m     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [35m[WebDriverAgent][39m   }
[debug] [35m[WebDriverAgent][39m }
[debug] [35m[WebDriverAgent][39m WebDriverAgent successfully started after 7737ms
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1620894495972 (15:28:15 GMT+0700 (Indochina Time))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
```

**Comment by Thuytien** [comment]
@KazuCocoa : I think Appium server proxy request to http://127.0.0.1:8100 and that was webdriveragent server

**Comment by KazuCocoa** [comment]
close for the original error had no response
