### ISSUE TITLE
Wont boot simulator on Big sur after update?

### ISSUE THREAD

**Issue by ufm-uk** [appium/appium-desktop#1797]
Appium Desktop

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After an upgrade to big sur the simulator will not work with appium, it simply just stopped working.  

The logs show 

No route found for /session

## Environment

- I am running Appium Desktop version 1.20.2
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
`No route found for /session` is not an error that has anything to do with simulators. Are you sure the url base for your appium server is not `/wd/hub`?

**Comment by ufm-uk** [comment]
Yes the base isnt /wd/hub it seems to be booting the application but bailing out now.  Very strange, it happened all of a sudden too.

**Comment by jlipps** [comment]
Does the simulator run the app manually OK? In my experience upgrading the OS breaks almost all development setups. If the app launches manually just fine but not through Appium, then link to a gist of your Appium logs. Also you say you've verified that things work with Appium from the command line but not Appium desktop, so attaching logs from the working command line run would also be helpful for us to compare.

**Comment by KazuCocoa** [comment]
>  the simulator will not work

Please check if manually simulator can work first.
Appium basically manages simulators via `xcrun simctl` by Apple.
