### ISSUE TITLE
could I launch inspector page and do not start appium server used appium-desktop？

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium-desktop#1798]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ✅] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

**hi, I want to only open the inspector page, and do not start appium server used appium-desktop . How can i do ?**

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [✅ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
You can find `New Session windows` in your menu bar.
![image](https://user-images.githubusercontent.com/5511591/118694915-771ea400-b7c1-11eb-9ec5-9de75862de8b.png)
