### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "terminateApp".

### ISSUE THREAD

**Issue by qqtester** [appium/appium-desktop#1817]
## Appium or Appium Desktop?
Appium
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [no ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I running my test cases on iphone8 12.3
During my cases running, below error output in log:
org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "terminateApp". Only scroll,swipe,pinch,doubleTap,twoFingerTap,touchAndHold,tap,dragFromToForDuration,selectPickerWheelValue,alert,setPasteboard,getPasteboard,source commands are supported. (WARNING: The server did not provide any stacktrace information)

## Environment

- I am running Appium version 1.6.4.
- I am on Mac

**Comment by qqtester** [comment]
Do I need to update the appium version?

**Comment by KazuCocoa** [comment]
Yes. 1.6.4 is so old
