### ISSUE TITLE
Appium desktop v1.21.0 iOS Can not see element in children components

### ISSUE THREAD

**Issue by Thuytien** [appium/appium-desktop#1818]
## The problem

Appium desktop only detects father component including all elements. For example in the screenshot, it's all view and I can not find each elements for iOS but for Android, it can.
Anyone has idea for this issue?

## Environment

- Appium Desktop version v1.21.0.
- Mac: Big Sur 11.3.1
![Screen Shot 2021-05-26 at 9 41 35 AM](https://user-images.githubusercontent.com/6836601/119597826-fb010d80-be0b-11eb-9bb5-d7965e970312.png)

**Comment by jlipps** [comment]
If there is no element(s) underneath the one you have selected, then it looks like this entire view is a single element from the perspective of iOS accessibility. The developers would need to make sure individual sub elements are accessible in order for Appium to see them (and it would be a good idea for accessibility as well).

**Comment by erharshbhatia** [comment]
I am facing similar issue as my screens are build on react native. Is this issue anything to do with react-native?

**Comment by erharshbhatia** [comment]
> ## Appium Desktop
> ## The problem
> Appium desktop only detects father component including all elements. For example in the screenshot, it's all view and I can not find each elements for iOS but for Android, it can.
> Anyone has idea for this issue?
> 
> ## Environment
> * Appium Desktop version v1.21.0.
> * Mac: Big Sur 11.3.1
>   ![Screen Shot 2021-05-26 at 9 41 35 AM](https://user-images.githubusercontent.com/6836601/119597826-fb010d80-be0b-11eb-9bb5-d7965e970312.png)

Are your screens build on react-native?

**Comment by jlipps** [comment]
For react native apps, it's possible to set accessibility incorrectly on parent elements which could cause child elements not to appear in the hierarchy. Read (primarily the end of) this article for more info: https://appiumpro.com/editions/76-testing-react-native-apps-with-appium

**Comment by Thuytien** [comment]
> > ## Appium Desktop
> > ## The problem
> > Appium desktop only detects father component including all elements. For example in the screenshot, it's all view and I can not find each elements for iOS but for Android, it can.
> > Anyone has idea for this issue?
> > ## Environment
> > 
> > * Appium Desktop version v1.21.0.
> > * Mac: Big Sur 11.3.1
> >   ![Screen Shot 2021-05-26 at 9 41 35 AM](https://user-images.githubusercontent.com/6836601/119597826-fb010d80-be0b-11eb-9bb5-d7965e970312.png)
> 
> Are your screens build on react-native?

yes, that build on react native

**Comment by Thuytien** [comment]
> For react native apps, it's possible to set accessibility incorrectly on parent elements which could cause child elements not to appear in the hierarchy. Read (primarily the end of) this article for more info: https://appiumpro.com/editions/76-testing-react-native-apps-with-appium

Thanks, I had read it and sent to my co-worker in dev team. But they still have no idea about that. Btw, do you know why it didn't display text in label attribute? it displayed the same for label and name for iOS element like below:
<img width="1640" alt="Screen Shot 2021-06-03 at 4 36 20 PM" src="https://user-images.githubusercontent.com/6836601/120736236-15c33880-c516-11eb-99a6-feaaa36cdfcc.png">

**Comment by wswebcreation** [comment]
Hi @Thuytien 

Here's an example of the code that you could use to make this work https://github.com/webdriverio/native-demo-app/blob/main/src/config/TestProperties.ts 

The devs can just add this to a touchable component `{...testProperties('your-identifier', true)}>` and all elements will be visible for Appium.

hoper this helps

**Comment by jlipps** [comment]
thanks @wswebcreation !

**Comment by Thuytien** [comment]
@wswebcreation  thank you so much, I'll tell them try that.
