### ISSUE TITLE
Appium desktop doesn't allow to switch between displays

### ISSUE THREAD

**Issue by ania-s** [appium/appium-desktop#1819]
## The problem

If android device has multiple displays it's impossible to capture a screenshot or interact with any other but default display.

## Environment

- I am running Appium Desktop version 1.21.0
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [x] Linux

**Comment by KazuCocoa** [comment]
Perhaps Appium cannot handle treat such situation.

Do you know how to handle them via https://developer.android.com/training/testing/ui-automator, https://developer.android.com/training/testing/espresso or adb command?
Appium's interactions/screenshot depend on them.

We do know how to handle them, so far.

**Comment by KazuCocoa** [comment]
If you find a way to switch the capture target, it will help us to implement it.
