### ISSUE TITLE
How to handle GCM message in Appium

### ISSUE THREAD

**Issue by m-ajitabh** [appium/appium-desktop#182]
## Appium Desktop?

How can we handle GCM message in Appium?

**Comment by dpgraham** [comment]
GCM is unrelated to what Appium does.

Appium is a black-box end-to-end testing framework that automates the user interface independent from your Android source code.

Testing GCM requires Java/JUnit tests. It's more of an integration testing problem then it is an end-to-end testing problem.

**Comment by m-ajitabh** [comment]
Then how do we automate the tests for those app which having GCM messaging
while registration or login?


Thanks
Ajitabh Ranjan
Mob: 9430331985

**Comment by dpgraham** [comment]
The messaging happens within the Java code. It's not part of the UI. I don't know what Appium would need to automate.

**Comment by m-ajitabh** [comment]
The message is showing in the notification part for some seconds, means
it's showing in UI.

Help me out if there is a way to do it in Appium style.

I have an idea about this, but it wont be works as Appium style. It will
comes under Unit test.


Thanks
Ajitabh Ranjan
Mob: 9430331985
