### ISSUE TITLE
couldn't start session error for starting appium inspector

### ISSUE THREAD

**Issue by asurendra41** [appium/appium-desktop#1820]
## The problem
i am trying to create a driver session for inspecting using appium desktop for android( didn't work for iOS as well). after entering desired capabilities and starting the session, i am facing the couldn't start session error popup. attached the error screenshot. tried with different appium desktop versions like 1.19/1.21 but no didn't work.

Please do the neeedful

<img width="1079" alt="Screenshot 2021-05-28 at 17 19 29" src="https://user-images.githubusercontent.com/84512437/120008173-fc346500-bfda-11eb-8b26-ebfe2bba3367.png">

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17 and 1.19 and 1.21
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Os Big sur v11.3.1
* Node.js version (unless using Appium.app|exe): installed latest
* Npm or Yarn package manager: Installed latest
* Mobile platform/version under test: android and ios
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe: appium desktop

**Comment by asurendra41** [comment]
standalone inspector also didn’t work for me. it shows "failed to create session.failed to fetch" error

> Then it is probably an AD issue

what is an AD issue? how to resolve?

**Comment by asurendra41** [comment]
> Have you tried the new standalone inspector? https://github.com/appium/appium-inspector/releases

**Comment by KazuCocoa** [comment]
What response can you see against `http://localhost:4723/` via a browser when the error occurs? 

Probably the below message will appear in the browser.

```
{"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}
```

Then, Appium server launched in the AD have the below log.

```
[HTTP] No route found for /
[HTTP] <-- GET / 404 11 ms - 211
[HTTP] 
[HTTP] <-- GET /favicon.ico 200 1 ms - 1150
[HTTP] 
```

**Comment by asurendra41** [comment]
yes.. as said, getting that log when it launched in browser

**Comment by jlipps** [comment]
try setting your  url base to `/wd/hub`

**Comment by asurendra41** [comment]
> try setting your url base to `/wd/hub`

not working...

**Comment by asurendra41** [comment]
yes ..from command line appium server is running and i could able to launch the app through code.
 but i need appium desktop for inspecting elements

**Comment by jlipps** [comment]
switch to the custom server tab and make sure you enter all the correct server details there?

**Comment by asurendra41** [comment]
tried custom server as well..but didn’t work. i have this below error when i run appium in termial(but server started)

(node:6094) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/appium/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
[Appium] Welcome to Appium v1.21.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by jlipps** [comment]
Try to inspect an element in the inspector window, to get the devtools up. then refresh the inspector, and try to start the session. anything interesting in the console log of the inspector app?

**Comment by asurendra41** [comment]
i didn’t get you.. where is the inspector window? 
i can't open inspector from appium desktop...

**Comment by jlipps** [comment]
the New Session window

**Comment by asurendra41** [comment]
not worked

**Comment by jlipps** [comment]
what was in the console log when you tried to start the session?

**Comment by asurendra41** [comment]
no line printed on console log after clicking start session....

**Comment by asurendra41** [comment]
> What response can you see against `http://localhost:4723/` via a browser when the error occurs?
> 
> Probably the below message will appear in the browser.
> 
> ```
> {"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}
> ```
> 
> Then, Appium server launched in the AD have the below log.
> 
> ```
> [HTTP] No route found for /
> [HTTP] <-- GET / 404 11 ms - 211
> [HTTP] 
> [HTTP] <-- GET /favicon.ico 200 1 ms - 1150
> [HTTP] 
> ```

he got the issue outline, pls help me how to resolve this?

**Comment by jlipps** [comment]
what happens when you try `https://localhost:4723/wd/hub/sessions` in the browser?

**Comment by jlipps** [comment]
> no line printed on console log after clicking start session....

this can't be the case. i mean the console log when you right click on the new session window, click 'inspect', then open up the console in the dev tools. i do not mean the appium server log output.

**Comment by asurendra41** [comment]
getting like this in console of inspect element...

<img width="1078" alt="Screenshot 2021-05-31 at 09 08 06" src="https://user-images.githubusercontent.com/84512437/120154112-ccaa7600-c1ef-11eb-9111-fcf6f0af88c9.png">

**Comment by asurendra41** [comment]
please check below one as well..i think this one may also helps you for investigating,
<img width="1779" alt="Screenshot 2021-05-31 at 09 13 03" src="https://user-images.githubusercontent.com/84512437/120154855-8e618680-c1f0-11eb-900e-07ba39188c49.png">

**Comment by asurendra41** [comment]
just did a work around, downloaded version v1.15.1 and its working fine. i think some problem/defect in latest releases

Thank you

**Comment by KazuCocoa** [comment]
Thanks.
I haven't seen this behavior. Perhaps we need someone's debugging in an environment that happens this behavior...

**Comment by jlipps** [comment]
@asurendra41 there are no actual issues in the console screenshots you showed. i'm interested in anything that shows up AFTER you click "Start Session", when the error popup is displayed in the app

**Comment by kenkl474** [comment]
> What response can you see against `http://localhost:4723/` via a browser when the error occurs?
> 
> Probably the below message will appear in the browser.
> 
> ```
> {"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}
> ```
> 
> Then, Appium server launched in the AD have the below log.
> 
> ```
> [HTTP] No route found for /
> [HTTP] <-- GET / 404 11 ms - 211
> [HTTP] 
> [HTTP] <-- GET /favicon.ico 200 1 ms - 1150
> [HTTP] 
> ```

I met an error with this case in appium 1.21.0. How can I solve it? I have already updated  chromedriver (ChromeDriver 83.0.4103.39 )with the emulator  chrome version(83.0.4103.106). And also, I added the path  /wd/hub in config part.  
Here is my test.js, 
//import wd from 'wd';
const wd = require('wd');
const Jasmine = require('jasmine');
const jasmine = new Jasmine();
jasmine.DEFAULT_TIMEOUT_INTERVAL = 60000;
const PORT = 4723;

const config = {
    path: '/wd/hub/session',
    platformName: "Android",
    platformVersion: "11",
    deviceName: "emulator-5554",
    app: "/Users/jiwing/Documents/RNTest2/my-app/android/app/my-app-30ceb4934ce942c18260d4fe3290cdea-signed.apk",
    automationName: "UiAutomator2",
    appActivity: "host.exp.exponent.MainActivit",
    appPackage: "com.tutorial.reactnative",
    broswerName: "chrome",
    newCommandTimeout: "400",
    chromedriverExecutable: "/usr/local/bin/chromedriver2"
}; 

const driver = wd.promiseChainRemote('localhost', PORT);

beforeAll(async () => {
    await driver.init(config);
})


test('Test Accessibilty Id', async () => {
    expect(await driver.hasElementByAccessibilityId('email')).toBe(true);
    expect(await driver.hasElementByAccessibilityId('password')).toBe(true);
});

**Comment by jlipps** [comment]
`path` is not a capability. you have to use the `--base-url` server flag

**Comment by MeghaRamprasa** [comment]
Hi @jlipps @KazuCocoa Unfortunately I am facing this issue. Not sure how to resolve this.
`{"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}`

Can you please help me? Awaiting for your response. Thankfully found this thread. Please let me know if any details are required?

appium v 1.22.3
MacOS
MacBook Air (M1, 2020)
Chip Apple M1

All the settings are correct, infact the appium inspector server is started and it has created the screen instance of the emulator.

<img width="1440" alt="Screenshot 2023-01-15 at 12 52 54 AM" src="https://user-images.githubusercontent.com/108040667/212492526-6b426f48-a1d5-46be-9da4-94a6a88fcd90.png">


Thank you,
Megha

**Comment by KazuCocoa** [comment]
Could you create a new issue in the appium-inspector repository with the Appium server log? This original issue is for a new session request while yours are maybe different one
