### ISSUE TITLE
Please help me solve the problem of element ID positioning[nonbug]

### ISSUE THREAD

**Issue by mabeijing** [appium/appium-desktop#1831]
## Appium Desktop

My problem is this,
In android app, some android widget have no ID but it has resource_id(attribute).
I see appium-desktop can recognize it automatically. But I don't know how to achieve it.
please help me,I also want to find out which elements have IDs

## Pictures

How to judge whether an element has an ID attribute
![appium1](https://user-images.githubusercontent.com/48149977/120621304-58dac880-c490-11eb-8244-e715ad5fd809.png)

![appium2](https://user-images.githubusercontent.com/48149977/120621374-655f2100-c490-11eb-961c-5c42dc2ba8cd.png)

## Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - [ ] Mac
    -  Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Perhaps it is timing stuff.. You want to try reload the source once.

**Comment by mabeijing** [comment]
> Perhaps it is timing stuff.. You want to try reload the source once.

not one element.  some element has id and some not

**Comment by mabeijing** [comment]
quit
