### ISSUE TITLE
Can't find the server and inspector foulder and got problems when I was trying to start the appium-desktop from source code

### ISSUE THREAD

**Issue by iloveleejunghyun** [appium/appium-desktop#1847]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [v] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hi, I'd like to develop some new features based on the source code of Appium-desktop. But after I ran "npm install", I didn't find the server and inspector folder. So I can't do the following instructions from https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md 

## Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - [ ] Mac
    - [v] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
The README is not up to date. We have just moved the code into 2 repositories. This repo hosts only the server, and https://github.com/appium/appium-inspector hosts only the inspector.

**Comment by iloveleejunghyun** [comment]
Thank you.
