### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by stephenws** [appium/appium-desktop#185]
## Appium Desktop

I have run same script using Appium CLI and it works Test Case Pass.
Whereas i am trying to execute same test case using Appium Desktop , Test Case gets Failed and got Error " [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65"

In my Device, App is installed but not launched and got above Error.

- [ Yes] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Same test cases gets pass with Appium CLI and Failed with Appium-Desktop
And Got Error " [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65"

## Environment

- I am running Appium Desktop version _<insert version here>_.Version 1.0.0 (1.0.0)
- I am on (pick one): Mac
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

Attaching Log in gist

https://gist.github.com/stephenws/7c9061ee774adc48dc99f0f0a09bda91

**Comment by dpgraham** [comment]
Appium Desktop is bundled with a local version of Appium and requires the same setup that is required with the global version, like code signing.

You'll need to either setup the local version of Appium you're using, or you can follow these steps and use the inspector tool with your globally installed version of Appium:

* Open Appium Desktop
* In the file menu, select Appium > New Session Window
* Choose 'Custom Server' tab and use the host and port of your globally running Appium instance

**Comment by stephenws** [comment]
Hi @dpgraham i have followed steps that you mentioned above but still facing same issue.
I am attaching logs
https://gist.github.com/stephenws/8de9292979a20bfe16ac0b3ec99a8fbb

**Comment by imurchie** [comment]
This is a code signing issue. Please see https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md
