### ISSUE TITLE
Appium inspector for remote Appium server

### ISSUE THREAD

**Issue by kzilber** [appium/appium-desktop#186]
## Appium Desktop

There are two issues (sooner desirable enhancements) with accessing remote appium server with Appium Desktop Inspector:

## The problem

1. You need to start local appium server just to get the interface for opening an inspector session against a remote appium server.
2. New appium desktop is written in Element / JS, so it should be somewhere close to provide Inspector functionality as a web app. It would be very convenient to run Inspector from a browser without any installation necessary.

## Environment
    - [ X] Mac
    - [ X] Windows
    - [X ] Linux

**Comment by jlipps** [comment]
> You need to start local appium server just to get the interface for opening an inspector session against a remote appium server.

No you don't. You can to to File > New Session straight from the server start window, without starting a local server first.

> New appium desktop is written in Element / JS, so it should be somewhere close to provide Inspector functionality as a web app. It would be very convenient to run Inspector from a browser without any installation necessary.

Unfortunately this won't work. Web inspectors like Chrome's inspector are powered by the remote debug protocol, which is something only browsers support (not native app automation frameworks). So there's no way for Appium to expose something like this. That is why we have to implement our own inspector.
