### ISSUE TITLE
Sess stop

### ISSUE THREAD

**Issue by john334596** [appium/appium-desktop#1863]
## Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
]

## Environment

- I am running Appium Desktop version _<1.6.1>_.
- I am on (pick one): Windows
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
- Did you attached to the device on SauceLabs from Appium Desktop, or attached to the local device embedded to Appium Desktop?
- What did Appium version run on the SauceLabs environment?

**Comment by john334596** [comment]
I am using Suacelabs real device.I digged a bit more into this part and found below things from Appium logs file that is generating against my test in saucelabs:

1. As i have mentioned i have this XCUIElementTypeTabBar at the bottom in which multiple elements/tabs are present. Now i tried with other tabs/elements and they are getting opened in appium desktop but just for one tab it is getting terminated. In my logs I see that it says  "message" :[Appium] Closing session , cause was 'Appium did not get any response from getPageSource command in 60000 ms' while for rest of the elements which are working getpagesource returns some xml data.

This page for which appium is getting terminated has lots of data comparatively than other pages. Can this be the reason of getting terminated ? I tried to override commandTimeouts capability from 60000 ms to 180000 ms but it is not overiding it neither newcommandtimeout is working.

Please let me know your thoughts on above.

**Comment by KazuCocoa** [comment]
Could you share the appium log?
I see your situation, but I don't know of the exact appium server log to track various information about the session/situation.

**Comment by john334596** [comment]
it worked after reducing the amount of data that was in that page. But can you tell me how can i increase the wait time in case page is quite huge and have many elements for appium desktop to process?
I have tried--- commandTimeouts but it is not getting overridden with the new value and defaulting to 60000 ms then i tried newcommandtimeout but it dint work too

**Comment by KazuCocoa** [comment]
What about `customSnapshotTimeout` https://github.com/appium/appium-xcuitest-driver#settings-api ?
