### ISSUE TITLE
set setting on c#

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium-desktop#1864]
Appium 1.21.0. Windows. c#

I use FindElementsByImage method, but get not similar elements.

How can I change ImageMatchThreshold?

**Comment by KazuCocoa** [comment]
You can configure settings like https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/test/integration/Android/SettingTest.cs#L56

**Comment by KazuCocoa** [comment]
i've created a PR to add an example in our documentation https://github.com/appium/appium/pull/15656
