### ISSUE TITLE
Appium setup failed for mac os BigSur verison 11.4

### ISSUE THREAD

**Issue by JPsurj1a01** [appium/appium-desktop#1869]
## Appium or Appium Desktop?

I am reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. The apppium-desktop is not compatible for Mac OS Verison 11.4 BigSur.
<img width="253" alt="Screenshot 2021-07-26 at 2 30 17 PM" src="https://user-images.githubusercontent.com/37236683/126988830-561cbc38-98af-4d42-aaee-d30005b5fddd.png">

## The problem

_Appium Desktop is not working for Mac OS Big Sur Version 11.4_

## Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - [x] Mac

**Comment by KazuCocoa** [comment]
Perhaps it is https://github.com/appium/appium-desktop#cannot-open-appium-desktop
