### ISSUE TITLE
The Appium viewer is not showing the mobile elements with the version 1.21.0

### ISSUE THREAD

**Issue by vega178** [appium/appium-desktop#1871]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason, we require you to have tried your test case with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The Appium CLI  is not showing the mobile elements tree with version 1.21.0

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

![image](https://user-images.githubusercontent.com/15344903/127176832-11d13d44-cb1e-4033-a371-b5be16fb0a1f.png)

![image](https://user-images.githubusercontent.com/15344903/127177985-a52f9d71-6286-43c9-b366-769b1396dc57.png)

**Comment by KazuCocoa** [comment]
> The Appium CLI is not showing the mobile elements tree with version 1.21.0

So, can nothing get the result by https://appium.io/docs/en/commands/session/source/ ?
If so, 1) something error happens in the appium uiautomator2 server or 2) Android OS behaves so.


Could you share the logcat to see the 1) possibility?

**Comment by ljpalaciom** [comment]
I have the same problem using the driver you.i engine driver as the capability automationName.

**Comment by jlipps** [comment]
Are you sure this is an issue with Appium desktop and not Appium in general? Are you sure you're able to see the elements when using the server via a client script?

**Comment by vega178** [comment]
Yep @jlipps , when we execute  driver.getPageSource(); , we can see the tree as aspected but when we trying to reach out to the appium desktop app we are not able to see the tree and its attributes.

**Comment by jlipps** [comment]
And you are running on the same server? Is there any error message in the inspector console log?

**Comment by vega178** [comment]
This is the error that shows in the console log: 

[Appium Destock Console Log.pdf](https://github.com/appium/appium-desktop/files/7017817/Appium.Destock.Console.Log.pdf)

![image](https://user-images.githubusercontent.com/15344903/130146404-bf01f3eb-1efb-4626-ba0b-864c57209f75.png)
![image](https://user-images.githubusercontent.com/15344903/130146458-1a8f6b55-3a61-4e55-9cc3-ce0766258d6f.png)

**Comment by jlipps** [comment]
This looks like an incompatibility between the youi driver and an older version of the inspector's context detection. Please use the most recent version of the inspector: https://github.com/appium/appium-inspector/releases. This version will not automatically look for contexts and should avoid this error.

**Comment by vega178** [comment]
do you mean this one ? 
![image](https://user-images.githubusercontent.com/15344903/130151825-7f287624-5077-4284-96b0-66eddffae217.png)

I can’t open it: 
![image](https://user-images.githubusercontent.com/15344903/130151916-b8d9242f-fb8b-44ba-a3a3-bed42ba0dbc7.png)

**Comment by vega178** [comment]
yep it looks like this already works with this app, thanks!!
