### ISSUE TITLE
Mov not working correctly in andr native

### ISSUE THREAD

**Issue by john334596** [appium/appium-desktop#1872]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

- I am running Appium Desktop version _<insert version here>_1.21.0
- I am on (pick one):Windows
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux
   - IOS version - 11

Is there a way I can stop the scroll to a specific element ?

**Comment by KazuCocoa** [comment]
What about https://github.com/appium/appium-xcuitest-driver#mobile-swipe ?
Or potentially it would be better to write a wrapper to scroll to an arbitrary element with W3C actions.

**Comment by john334596** [comment]
swipe is throwing the following error - an unknown server-side error occured.Original error: Invalid parameter not satisfying: point.x!=INFINITY && point.Y!=INFINITY
Or potentially it would be better to write a wrapper to scroll to an arbitrary element with W3C actions. can you pls elaborate a bit more on this?

**Comment by jlipps** [comment]
For example: https://appiumpro.com/editions/107-designing-a-cross-platform-swipescroll-helper
