### ISSUE TITLE
Feature Request: Allow attaching to running session without first creating a session 

### ISSUE THREAD

**Issue by kevin-roe** [appium/appium-desktop#1873]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I often find myself attaching the desktop tool to an existing session.  But, I hate having to first start a server on port X (which opens the terminal which allows me to open the inspector) so that I can then attach the inspector to a server running on port Y.  It would be nice to be able to to attach to an existing session from the Advanced window before launching a server at all.  

## Environment

- I am running Appium Desktop version _1.20.2_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by sme81** [comment]
You can do this already via file->new inspector session.

Doing this from memory away from laptop so might be different wording but should be the right area without having to run a server via desktop

**Comment by kevin-roe** [comment]
Excellent!  Thanks!

**Comment by jlipps** [comment]
@kevin-roe Appium Inspector is now a standalone app in any case - https://github.com/appium/appium-inspector
