### ISSUE TITLE
Appium can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by nikaswoon** [appium/appium-desktop#1874]
## Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Can't open application right after downloading it for the first time
<img width="421" alt="Screenshot 2021-08-04 at 19 30 09" src="https://user-images.githubusercontent.com/55055584/128219273-f4dfa20d-0173-4272-8dae-dbff452cdeb2.png">

## Environment

- I am running Appium Desktop version _1.21.0_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by sme81** [comment]
Right click and open should do the trick
