### ISSUE TITLE
Appium desktop:in the simulator, my page will stay where it was, with no response

### ISSUE THREAD

**Issue by sunxiaoyu124** [appium/appium-desktop#1881]
## Appium or Appium Desktop?

Appium and Appium Desktop

## The problem

in the simulator, my page will stay where it was, with no response
[Uploading appium-server-logs.txt…]()

## Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - [✅] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Close since the issue was incompleted
