### ISSUE TITLE
Appium Android unknown server-side error

### ISSUE THREAD

**Issue by hearhour** [appium/appium-desktop#1882]
The problem

[W3C (54202cd9)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - Windows

My appium logs 
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/7031030/appium-server-logs.txt)

**Comment by jlipps** [comment]
This seems like an Appium issue, not an Appium Desktop issue. Please report on the main repo and include your adb logcat, since the crash details will be in there. It's likely an issue with your app.
