### ISSUE TITLE
[ Appium Desktop] Appium1.6.4 Encountered internal error running command: Error: incorrect data check at Zlib._handle.onerror

### ISSUE THREAD

**Issue by hjianhui** [appium/appium-desktop#189]
Hi,

I have installed Appium Desktop release version "appium-desktop-1.0.0.dmg" into mac machine, but when I click on start new session  for Android after appium server is running the Appium Inspector window opens but fails to capture the screenshot and popups the error as:

"takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: incorrect data check"

Also getting below error in Appium log
[MJSONWP] Encountered internal error running command: Error: incorrect data check
at Zlib._handle.onerror (zlib.js:370:17)

Please look into this issue.

Thanks,

**Comment by dpgraham** [comment]
Can you test this out using the Appium CLI and verify that it's a problem with Appium Desktop?

**Comment by hjianhui** [comment]
yes, can run it by CLI,  also Appium Desktop can run for IOS,but cannot for Android ,

**Comment by srilakshmi211** [comment]
I am facing this issue on 1.6.3 while trying to screenshot from code using @driver.screenshot("screenshots/ss.png") , screenshot has empty ss.png file.

**Comment by hjianhui** [comment]
@dpgraham  can run it by Appium CLI, i'am sure that  it's a problem with Appium Desktop

**Comment by dpgraham** [comment]
@hjianhui Which Appium CLI version are you running?

**Comment by hjianhui** [comment]
@dpgraham  1.6.3

**Comment by hjianhui** [comment]
@dpgraham  but it has no problem with IOS,  it only do not work with Android when i click start new session

**Comment by hjianhui** [comment]
@dpgraham  also @srilakshmi211 has the same problem with me

**Comment by dpgraham** [comment]
@hjianhui Can you show me the server logs? I'd like to see the context of why screenshot is failing.
