### ISSUE TITLE
"Error: XPath parse error" after updating Appium Desktop

### ISSUE THREAD

**Issue by ChiWhiteSox56** [appium/appium-desktop#190]
## Appium or Appium Desktop?
Appium Desktop

- [ X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I opened Appium Desktop today and was notified that there was an update. I updated Appium Desktop, and on screens that I had no problem inspecting as recently as yesterday, I'm getting the following error:
"Error: XPath parse error"

I do not see this error on all screens.

I wrote a quick Appium test to see if there was a crash when I got to that page, and there was not. Unfortunately, that's the extent of the testing that I was able to do because I don't have any element locators for that page yet. (I ran Appium Desktop to try to work on that.)

Here is what I was able to capture from the Appium logs:
https://gist.github.com/ChiWhiteSox56/fd0ea3c0fbaa3a7e469b9ab863cd3010

Note: I am using the same version of the test app and the same version of Appium (1.6.4) that I've been using for the last two weeks. The only update I made was to Appium Desktop, and it was after that update that I started having this issue.

## Environment

- I am running Appium Desktop version 1.0.1
- I am on (pick one):
    - [ X ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by mwalla210** [comment]
Also experiencing this issue after upgrading to latest Appium desktop on select screens. Coworker who has not updated is not experiencing this issue on the same screens.

**Comment by ChiWhiteSox56** [comment]
@mwalla210  - Have you tried downgrading? I did, and I'm getting errors that I've never seen in Appium desktop, but I have seen this in Appium:

> Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

I did update Carthage, but I doubt that's relevant.

**Comment by dpgraham** [comment]
Thanks for notifying me of this. We made changes to xpath which may be causing these problems.

I'm going to unpublish the v1.0.1 while I work  on a fix for this and recommend that for the time being you just uninstall and reinstall with v1.0.0

@ChiWhiteSox56 Is this error breaking the inspector page altogether?

**Comment by ChiWhiteSox56** [comment]
@dpgraham - The error doesn't affect all pages. The affected pages are more complex than those that are not affected, at least from what I'm seeing. Simple list or grid view - no error. Page with "hamburger menu" and collapsible list items - error.

I installed v 1.0.0 but I'm getting an error here as well. Kind of looks like something is pointing to version 1.0.1, but I'm not sure. Here's the part that I'm talking about:
```
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
```
and 
```
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /private/var/folders/92/2p4l0l3n0bq3nqjvxs_j6xcw0000gn/T/AppTranslocation/11A87385-E133-4F84-B418-EE3B3A96093D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory 
```
And here's a gist of the complete log: 
https://gist.github.com/ChiWhiteSox56/d389f976c7fb69735fc0a397e1ae23b0

**Comment by mwalla210** [comment]
Downgrading worked to fix the error experienced

**Comment by dpgraham** [comment]
Thanks @ChiWhiteSox56. I committed a fix for it and should have the new version out soon.

**Comment by dpgraham** [comment]
@ChiWhiteSox56 We've made a fix in v1.0.1-beta.1

Can you let me know if that error still happens when you upgrade to that version?

**Comment by ChiWhiteSox56** [comment]
@dpgraham - Apologies for seeing your request so late. Looks like another version came out between the time you contacted me and the present. I am not seeing this issue in Version 1.0.2-beta.2.

**Comment by jlipps** [comment]
Excellent, thanks for the update.

**Comment by dpgraham** [comment]
Thanks @ChiWhiteSox56!

**Comment by samsonbarukula** [comment]
Hi, In appium desktop Version 1.2.26 (1.2.6) error could not find element try refreshing the page .... alerts are popping up ... any help pls

**Comment by dpgraham** [comment]
Are you still able to use 'tap' and 'send keys' on the selected elements?

**Comment by samsonbarukula** [comment]
no - still the keys are disabled.  but in sometimes I found it as enabled, but not consistent. any update on this graham ?

**Comment by dpgraham** [comment]
Can you  provide the Appium server logs
