### ISSUE TITLE
not able to use sendkeys on android device

### ISSUE THREAD

**Issue by lakshmank041993** [appium/appium-desktop#1903]
## observed in Appium Desktop and Appium

i was not able to use send keys 
below error is displayed 

```
Call to 'sendKeys' failed
[element.sendKeys("560008")] Error response status: 12, InvalidElementState - An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element). Selenium error: ACTION_SET_PROGRESS has failed on the element 'android.view.accessibility.AccessibilityNodeInfo@96ae; boundsInParent: Rect(59, 9 - 362, 61); boundsInScreen: Rect(75, 42 - 461, 108); packageName: com.freshtohome; className: android.widget.EditText; text: Enter your pincode; error: null; maxTextLength: -1; contentDescription: null; tooltipText: null; viewIdResName: pincode-input-id; checkable: false; checked: false; focusable: true; focused: true; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_NEXT_HTML_ELEMENT - null, AccessibilityAction: ACTION_PREVIOUS_HTML_ELEMENT - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null, AccessibilityAction: ACTION_CONTEXT_CLICK - null, AccessibilityAction: ACTION_NEXT_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_CLEAR_FOCUS - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_CLICK - null, AccessibilityAction: ACTION_SET_PROGRESS - null]'. Did you interact with the correct element?

```

## The problem

not able to use sendkeys on android device

## Environment

- I am running Appium Desktop version _< 1.21.0>_.
- I am on (pick one):
    - [x] Linux

log - 

`[HTTP] 
[HTTP] --> POST /wd/hub/session/cfba3516-0cc6-4917-85a4-d14165efabc2/element/946bf44e-9e61-427e-b80a-53a03b3040f4/value
[HTTP] {"value":["560008"],"text":"560008"}
[MJSONWP (cfba3516)] Calling AppiumDriver.setValue() with args: [["560008"],"946bf44e-9e61-427e-b80a-53a03b3040f4","cfba3516-0cc6-4917-85a4-d14165efabc2"]
[WD Proxy] Matched '/element/946bf44e-9e61-427e-b80a-53a03b3040f4/value' to command name 'setValue'
[Protocol Converter] Added 'value' property ["5","6","0","0","0","8"] to 'setValue' request body
[WD Proxy] Proxying [POST /element/946bf44e-9e61-427e-b80a-53a03b3040f4/value] to [POST http://127.0.0.1:8200/wd/hub/session/d12bd12b-936d-455d-907b-81890af60261/element/946bf44e-9e61-427e-b80a-53a03b3040f4/value] with body: {"elementId":"946bf44e-9e61-427e-b80a-53a03b3040f4","text":"560008","replace":false,"value":["5","6","0","0","0","8"]}
[WD Proxy] Got response with status 400: {"sessionId":"d12bd12b-936d-455d-907b-81890af60261","value":{"error":"invalid element state","message":"ACTION_SET_PROGRESS has failed on the element 'android.view.accessibility.AccessibilityNodeInfo@96ae; boundsInParent: Rect(59, 9 - 362, 61); boundsInScreen: Rect(75, 42 - 461, 108); packageName: com.freshtohome; className: android.widget.EditText; text: Enter your pincode; error: null; maxTextLength: -1; contentDescription: null; tooltipText: null; viewIdResName: pincode-input-id; checkable: false; checked: false; focusable: true; focused: true; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_NEXT_HTML_ELEMENT - null, AccessibilityAction: ACTION_PREVIOUS_HTML_ELEMENT - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null, AccessibilityAction: ACTION_CONTEXT_CLICK - null, AccessibilityAction: ACTION_NEXT_AT_MOVEMENT_GRANULARITY - null...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[MJSONWP (cfba3516)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: ACTION_SET_PROGRESS has failed on the element 'android.view.accessibility.AccessibilityNodeInfo@96ae; boundsInParent: Rect(59, 9 - 362, 61); boundsInScreen: Rect(75, 42 - 461, 108); packageName: com.freshtohome; className: android.widget.EditText; text: Enter your pincode; error: null; maxTextLength: -1; contentDescription: null; tooltipText: null; viewIdResName: pincode-input-id; checkable: false; checked: false; focusable: true; focused: true; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_NEXT_HTML_ELEMENT - null, AccessibilityAction: ACTION_PREVIOUS_HTML_ELEMENT - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null, AccessibilityAction: ACTION_CONTEXT_CLICK - null, AccessibilityAction: ACTION_NEXT_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_CLEAR_FOCUS - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_CLICK - null, AccessibilityAction: ACTION_SET_PROGRESS - null]'. Did you interact with the correct element?
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.core.AxNodeInfoHelper.setProgressValue(AxNodeInfoHelper.java:291)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.utils.ElementHelpers.setProgress(ElementHelpers.java:113)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.model.BaseElement.setProgress(BaseElement.java:155)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.handler.SendKeysToElement.setProgress(SendKeysToElement.java:58)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:111)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)
[MJSONWP (cfba3516)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (cfba3516)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (cfba3516)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[MJSONWP (cfba3516)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[MJSONWP (cfba3516)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[MJSONWP (cfba3516)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (cfba3516)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[MJSONWP (cfba3516)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[MJSONWP (cfba3516)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[MJSONWP (cfba3516)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[MJSONWP (cfba3516)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[MJSONWP (cfba3516)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[MJSONWP (cfba3516)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[MJSONWP (cfba3516)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[MJSONWP (cfba3516)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[MJSONWP (cfba3516)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[MJSONWP (cfba3516)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[MJSONWP (cfba3516)] 	at java.lang.Thread.run(Thread.java:764)
[MJSONWP (cfba3516)] 
[HTTP] <-- POST /wd/hub/session/cfba3516-0cc6-4917-85a4-d14165efabc2/element/946bf44e-9e61-427e-b80a-53a03b3040f4/value 500 87 ms - 1314
[HTTP] `

**Comment by jlipps** [comment]
Is there something which makes you think this is an issue with appium desktop and not appium?

**Comment by lakshmank041993** [comment]
@jlipps  just tried it out now in appium as well , observing same issue

**Comment by jlipps** [comment]
Thanks. That is why we ask people to confirm whether it is an issue with Appium or not. Issues with Appium are not tracked here. This is the repo for the GUI only. Please re-open a new issue at the main Appium repo.
