### ISSUE TITLE
Can i inspect any application installed on my real device?

### ISSUE THREAD

**Issue by mostafa-raafat** [appium/appium-desktop#1907]
I'm new to automation testing 
I want to inspect an app on my iPhone `Twitter` for example is that possible?
My Desired capabilities 
```{
  "automationName": "XCUITest",
  "platformName": "iOS",
  "deviceName": "iPhone 12",
  "platformVersion": "14.8",
  "udid": "-----------------------",
  "xcodeSigningId": "iPhone Developer",
  "xcodeOrgId": "---------",
  "bundleId": "com.test.test"
}
```
I'm getting this error 
<img width="1161" alt="Screenshot 2021-09-16 at 22 29 26" src="https://user-images.githubusercontent.com/43439787/133681518-268ca0c8-6db5-4cbc-8a79-6f76f8636619.png">

**Comment by jlipps** [comment]
This error is unrelated to this repo, and please use the Appium forums to ask questions.
