### ISSUE TITLE
Appium desktop can't start debug mode on ios 15

### ISSUE THREAD

**Issue by golfzaptw** [appium/appium-desktop#1918]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/7275721/appium-server-logs.txt)

## Environment

- I am running Appium Desktop version _<1.21.0>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

## Settings
```json
{
  "automationName": "XCUITest",
  "platformName": "ios",
  "platformVersion": "15.0",
  "deviceName": "iPhone 13 Pro Max",
  "app": "ios-15.app",
  "useNewWDA": true,
  "showXcodeLog": true,
  "updatedWDABundleId": "io.appium.WebDriverAgentRunner",
  "clearSystemFiles": true,
  "autoAcceptAlerts": true
}
```

**Comment by KazuCocoa** [comment]
Please use Appium 1.22.0 for Xcode 13 and iOS 15. https://github.com/appium/appium/releases/tag/v1.22.0
If something screenshot error still happened, please make sure your `DerivedData` has been cleaned once. It might be Xcode's build cache stuff.
