### ISSUE TITLE
Creating a Session using Appium desktop app

### ISSUE THREAD

**Issue by hashika2** [appium/appium-desktop#1921]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason, we require you to have tried your test case with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I start the appium server we couldn't start the session just click the search icon. But I don't know how to do that. They said inspector is now in a separate app. Please any tell anyone how to start the session through the app.  It's agent for me.

## Environment

- I am running Appium Desktop version _v1.22.0_.
- I am on (pick one):
    - [ ] Windows

**Comment by jlipps** [comment]
Simply download the new inspector at https://github.com/appium/appium-inspector/releases/ and run it to get the new session window.

**Comment by hashika2** [comment]
Thanks It's working
