### ISSUE TITLE
No "New session windows" option

### ISSUE THREAD

**Issue by Quartzbell** [appium/appium-desktop#1922]
## The problem
What I expect based on the tutorials floating around in the net:
![image](https://digital.ai/sites/default/files/pictures/experitest/2020/05/image8.png)

What I got:
![image](https://user-images.githubusercontent.com/6446747/136165111-8b5e1ca8-b9c7-46c5-9da8-a29e1206d28b.png)

## Environment
Windows 10

**Comment by KazuCocoa** [comment]
The section is now moved to https://github.com/appium/appium-inspector
https://github.com/appium/appium-desktop/releases/tag/v1.22.0

**Comment by yshnaviganapathi** [comment]
Hi @jlipps , I downloaded the 1.22.0 version of appium. I don't see the appium inspect session. how to inspect the mobile elements on a new appium version.

**Comment by jlipps** [comment]
the inspector is not included in that version of Appium Desktop. you need to download separately as linked in the README
