### ISSUE TITLE
find element\access element really slowly

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium-desktop#1935]
##![2021-11-08_16-51-49](https://user-images.githubusercontent.com/41478386/140763808-4a7a4a93-1505-41fc-9d9a-de5aa839b78d.png)Appium or Appium Desktop?
Appium 
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

on some activities, the search and access to elements takes a![2021-11-08_16-51-49](https://user-images.githubusercontent.com/41478386/140763808-4a7a4a93-1505-41fc-9d9a-de5aa839b78d.png)very long time (more than 10 seconds)

## Environment

- I am running Appium Desktop version 1.22.0.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
how many elements did the endpoint return?

The endpoint is https://developer.android.com/reference/androidx/test/uiautomator/UiDevice#findobjects, so potentially it returned slowly.

https://github.com/appium/appium-uiautomator2-server/blob/cef81e2a9755e103ff5a6fb488938a14ff8a7016/app/src/main/java/io/appium/uiautomator2/handler/FindElements.java#L105-L106

**Comment by atimofeev86** [comment]
1 element as usual .
I got element, then I use Click() and Click() executes slowly too

**Comment by KazuCocoa** [comment]
Mm, a bit confused. The reported one is `/elements` endpoint. It seems it returned over 7 elements in your attached log.

> then I use Click() and Click() executes slowly to

`waitForIdleTimeout` https://github.com/appium/appium-uiautomator2-driver#settings-api may help. Usually, UIA2 waits for the interaction until the application process to be idle. You can make the settings value small to not wait for the idle state forcefully.

**Comment by atimofeev86** [comment]
@KazuCocoa thank you. it's works for me.
