### ISSUE TITLE
The Save Capability Set As function is not effective in Win 10

### ISSUE THREAD

**Issue by zhengjie201667** [appium/appium-desktop#1936]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1. Open the Appium-desktop with default setting.
2. Click the Start Inspector Session button.
3. Input the Desired Capabilities and use the "Save Capability Set As" function
4.
![image](https://user-images.githubusercontent.com/40327326/141644035-ecf392c0-5fc5-44b4-8f5c-8d2ddc3aa7d9.png)
5. When save, the Save Capability Set still show "0"
6. 
![image](https://user-images.githubusercontent.com/40327326/141644052-2df04f1a-bd10-49f6-82ca-9dd51ea53a3b.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Windows 10, when I try in win 7, it succeeds

**Comment by rahmanto1997** [comment]
I am same the problem, please help!!!

**Comment by DonutIceCream** [comment]
> ## Appium or Appium Desktop?
> You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:
> 
> * [ ]  I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue
> 
> ## The problem
> 1. Open the Appium-desktop with default setting.
> 2. Click the Start Inspector Session button.
> 3. Input the Desired Capabilities and use the "Save Capability Set As" function
> 
> ![image](https://user-images.githubusercontent.com/40327326/141644035-ecf392c0-5fc5-44b4-8f5c-8d2ddc3aa7d9.png) 5. When save, the Save Capability Set still show "0" 6. ![image](https://user-images.githubusercontent.com/40327326/141644052-2df04f1a-bd10-49f6-82ca-9dd51ea53a3b.png)
> 
> ## Environment
> * I am running Appium Desktop version .
> * I am on (pick one):
>   
>   * [ ]  Windows 10, when I try in win 7, it succeeds

Problem Solved! Win 10 or Win 11
DELETE folder appium-desktop
 location C:\Users\Asus\AppData\Roaming\appium-desktop

**Comment by zhengjie201667** [comment]
> > ## Appium or Appium Desktop?
> > You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:
> > 
> > * [ ]   I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue
> > 
> > ## The problem
> > 
> > 1. Open the Appium-desktop with default setting.
> > 2. Click the Start Inspector Session button.
> > 3. Input the Desired Capabilities and use the "Save Capability Set As" function
> > 
> > ![image](https://user-images.githubusercontent.com/40327326/141644035-ecf392c0-5fc5-44b4-8f5c-8d2ddc3aa7d9.png) 5. When save, the Save Capability Set still show "0" 6. ![image](https://user-images.githubusercontent.com/40327326/141644052-2df04f1a-bd10-49f6-82ca-9dd51ea53a3b.png)
> > ## Environment
> > 
> > * I am running Appium Desktop version .
> > * I am on (pick one):
> >   
> >   * [ ]   Windows 10, when I try in win 7, it succeeds
> 
> Problem Solved! Win 10 or Win 11 DELETE folder appium-desktop location C:\Users\Asus\AppData\Roaming\appium-desktop

yeah, the problem is solved, much thanks for the support

**Comment by zhengjie201667** [comment]
> I am same the problem, please help!!!

pls see the resolution above
