### ISSUE TITLE
my Appium Desktop NO option【file->Start New Session】

### ISSUE THREAD

**Issue by wwwrookie** [appium/appium-desktop#1938]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Why doesn't my have this option : 【file->Start New Session】
this option no，，why why why ！！！
![image](https://user-images.githubusercontent.com/9474680/142138258-1370ce28-1ac2-4a34-a1f6-daebda4294d2.png)

## Environment

- I am running Appium Desktop version _<1.22.0>_.
- I am on (pick one):
    - [ ] Mac
    - [yes ] Windows11
    - [ ] Linux

**Comment by jlipps** [comment]
As the README explains, the inspector is now a different app. https://github.com/appium/appium-inspector.

**Comment by wwwrookie** [comment]
> As the README explains, the inspector is now a different app. https://github.com/appium/appium-inspector.
okk  thanks ,, i go look

**Comment by sushmaraos** [comment]
how to get the Start New Session can u guide me step by step
