### ISSUE TITLE
我的inspector 没有Automatic Server那些选项栏?

### ISSUE THREAD

**Issue by beiker1415** [appium/appium-desktop#1941]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

![image](https://user-images.githubusercontent.com/40162489/142592142-8cfb264e-b504-4ec7-b8f7-771a119e0940.png)

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [1 ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
You set `Andorid` instead of `Android` as automation name. (typo)
