### ISSUE TITLE
Appium desktop inspector not correct for orientation

### ISSUE THREAD

**Issue by YevheniiaHre** [appium/appium-desktop#1942]
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_When I set up portrait mode and I open inspector, simulator is in proper position (
portrait mode) but inspector shows me landscape mode._

## Environment

- Appium Desktop v.1.22.0
- Mac v.12.0.1
- XCode 13.1

The similar problem was registered in Appium Desktop tickets #211 and #10015

**Comment by jlipps** [comment]
Which inspector are you using? Are you aware this is no longer the repo for the inspector?

**Comment by YevheniiaHre** [comment]
I use Appium Inspector

**Comment by YevheniiaHre** [comment]
Thanks. Then I will recreate the issue in another repo.

**Comment by jlipps** [comment]
https://github.com/appium/appium-inspector/issues/218
