### ISSUE TITLE
Not able to Launch Appium Server GUI 1.22.0 in Mac

### ISSUE THREAD

**Issue by narasimhanukala** [appium/appium-desktop#1947]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am unable to Launch Appium Server GUI 1.22.0 in my Mac BigSur 11.6.1. it doesn't appear in Security & Privacy to allow it anyway like earlier versions, where earlier version i used accept under Security & Privacy

## Environment

I am running Appium Server GUI 1.22.0
- I am on (pick one):
    -
<img width="390" alt="Screenshot 2021-12-15 at 4 16 37 PM" src="https://user-images.githubusercontent.com/45284113/146173417-21cb2dfe-e37b-4701-abbe-fd60afec3425.png">
Mac BigSur 11.6.1

**Comment by jlipps** [comment]
Check the [readme](https://github.com/appium/appium-desktop#installing-on-macos)
