### ISSUE TITLE
appium desktop client is not launching on macOS Catalina version 10.15.7

### ISSUE THREAD

**Issue by aarunsharma** [appium/appium-desktop#1950]
![image](https://user-images.githubusercontent.com/44783702/147239981-9b0cbc11-3a12-4df3-bceb-5f35f81e971a.png)
#Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_appium desktop client is not launching on macOS Catalina version 10.15.7_

## Environment

- I am running Appium server GUI Desktop version _<1.22.0>_.
- I am on (pick one):
    - [ ] Mac

**Comment by aarunsharma** [comment]
I found the solution https://stackoverflow.com/questions/68157955/appium-can-t-be-opened-because-apple-cannot-check-it-for-malicious-software

**Comment by KazuCocoa** [comment]
We addressed this case in https://github.com/appium/appium-desktop#installing-on-macos as well
