### ISSUE TITLE
Appium Inspector time out with Appium Server message - Starting apksigner: /usr/bin/java -Xmx1024M -Xss1m -jar /Users/user/Library/Android/sdk/build-tools/32.0.0/lib/apksigner.jar verify --print-certs '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.24.0.apk'

### ISSUE THREAD

**Issue by robert-cui1** [appium/appium-desktop#1963]
## Appium or Appium Desktop?

When trying to run through CLI, I got error - Could not connect to server; are you sure it's running? If you are using the browser version, also ensure your Appium server has been started with --allow-cors. I actually tried to start Calendar app with following caps:
{
  "platformName": "Android",
  "appium:platformVersion": "11.0",
  "appium:deviceName": "emulator-5554",
  "appium:appPackage": "com.android.calendar"
}

## The problem

I use Android AVD to run an emulator and try to use Appium Inspector to connect to the emulator

## Environment

- I am running Appium Desktop version _<1.22>_.
- I am on (pick one):
    - [Y] Mac
    - [ ] Windows
    - [ ] Linux
- Appium Inspector App Version 2021.12.2
Remote Host - 127.0.0.1
Remote Port - 4273
Allow Session Override - true
Relaxed Security - True

**Comment by robert-cui1** [comment]
user sudo to start the server UI not solve the problem

**Comment by jlipps** [comment]
Does the most recent Appium CLI version have the same problem? I.e., don't use Appium Desktop. Use the CLI version of Appium and connect to it with the inspector.

**Comment by robert-cui1** [comment]
When running through CLI, from Inspector, I got:
Could not connect to server; are you sure it's running? If you are using the browser version, also ensure your Appium server has been started with --allow-cors.
Here is the command line info:
appium -a 127.0.0.1 -p 4273 --allow-cors
[Appium] Welcome to Appium v1.22.2
[Appium] Non-default server args:
[Appium]   allowCors: true
[Appium]   address: 127.0.0.1
[Appium]   port: 4273
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on 127.0.0.1:4273

From Inspector side, remote host and remote port are 127.0.0.1:4273
emulator is on
caps are:
{
  "platformName": "Android",
  "appium:platformVersion": "11.0",
  "appium:deviceName": "emulator-5554",
  "appium:appPackage": "com.android.calendar"
}
Thanks for your help:)

**Comment by jlipps** [comment]
OK. What is the connection information you are using in the Inspector? And is there a reason you are explicitly stating an address of `127.0.0.1`? And did you read the [important note at the top of the README](https://github.com/appium/appium-inspector/#important-migration-notes) about path information?

**Comment by robert-cui1** [comment]
Inspector connection info:
Remote host: 127.0.0.1
Remote port: 4723
Remote path: /wd/hub/
SSL: unchecked
Allow Unauthorized Certificates: unchecked
Use Proxy: unchecked

There's no specific reason why I use 127.0.0.1, it's just the default local host IP. Is there a difference between 0.0.0.0 and 127.0.0.1 from point of view of Appium Server and Inspector?

I went through README a while ago when I installed it

Thanks:)

**Comment by superew** [comment]
> Inspector connection info: Remote host: 127.0.0.1 Remote port: 4723 Remote path: /wd/hub/ SSL: unchecked Allow Unauthorized Certificates: unchecked Use Proxy: unchecked
> 
> There's no specific reason why I use 127.0.0.1, it's just the default local host IP. Is there a difference between 0.0.0.0 and 127.0.0.1 from point of view of Appium Server and Inspector?
> 
> I went through README a while ago when I installed it
> 
> Thanks:)

Have you solve the issue? I got and stuck on this issue. Please help :(

**Comment by jlipps** [comment]
> There's no specific reason why I use 127.0.0.1, it's just the default local host IP. Is there a difference between 0.0.0.0 and 127.0.0.1 from point of view of Appium Server and Inspector?

0.0.0.0 means all interfaces, 127.0.0.1 means only the one. It would be better to start appium with just `appium --allow-cors`. What happens when you do that?

**Comment by superew** [comment]
> > There's no specific reason why I use 127.0.0.1, it's just the default local host IP. Is there a difference between 0.0.0.0 and 127.0.0.1 from point of view of Appium Server and Inspector?
> 
> 0.0.0.0 means all interfaces, 127.0.0.1 means only the one. It would be better to start appium with just `appium --allow-cors`. What happens when you do that?

I got the same issue when start appium with '--allow-cors' or without it
![image](https://user-images.githubusercontent.com/19278248/167069974-79e5c2e6-5bf5-4858-9752-34e59104df16.png)

Around 2-3 months ago I can run Appium Inspector normally, but I don't know why after few days, I got this issue until now

I'm using Windows 11
Appium: 1.22.3
Appium Inspector: 2022.5.1

**Comment by jlipps** [comment]
1. what is the exact command you are using to start the appium server? what is the output when you run that command?
2. you should never include http:// in your 'remote host'
3. you should never try to access the host `0.0.0.0`. if you're trying to access localhost, then use `localhost` or `127.0.0.1`

**Comment by superew** [comment]
> 1. what is the exact command you are using to start the appium server? what is the output when you run that command?
> 2. you should never include http:// in your 'remote host'
> 3. you should never try to access the host `0.0.0.0`. if you're trying to access localhost, then use `localhost` or `127.0.0.1`

Hi, thank you so much, I can connect now after remove http:// and use 127.0.0.1 as #2 and #3.
Thank you and have a nice day
