### ISSUE TITLE
Appium 1.6.4 don't have a icon in Application of Mac book?

### ISSUE THREAD

**Issue by ZhaoMoMo** [appium/appium-desktop#197]
## The problem

The first problem: I installed appium 1.6.4, not appium desktop, on my Mac book by the command of "npm install -g appium". And the version of it is 1.6.4. But I can't find a icon in "launched" or "Application".Also I can't get the appium window to see the log and do any settings.Is appium 1.6.4 can only running in the terminal window?How can I get the icon?

The second problem: About the Appium desktop, I try to download the Appium-desktop.dmg for several times and all filed. I am in china, do you have any good method for me to get it?

Many thanks!

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [√] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Command line Appium only works via the terminal. Appium Desktop is downloaded through GitHub and then installed as the dmg/exe/AppImage.

Are you able to download anything from Github or is it just the Appium download that fails?

**Comment by ZhaoMoMo** [comment]
I had download the program "sample code" from Github successfully several days before. but the appium desktop can't be download.

**Comment by dpgraham** [comment]
Try checking out the repository and then build the binary using `npm run package`
