### ISSUE TITLE
Appium Desktop support on M1

### ISSUE THREAD

**Issue by andrealim11** [appium/appium-desktop#1980]
## Appium or Appium Desktop?

<img width="548" alt="rosetta" src="https://user-images.githubusercontent.com/50358932/153767236-214c95af-0145-48bf-8acf-caec4c8e3c31.png">

- [V ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

do I must install rosetta to open appium desktop? or there is any other way to do it ? 

## Environment

- I am running Appium Desktop version 1.22.0
- I am on :
    - MacOS Monterey 12.2
    - M1 Chip

**Comment by KazuCocoa** [comment]
Probably it needs electron 11. https://www.electronjs.org/blog/electron-11-0

**Comment by jlipps** [comment]
You probably want rosetta anyway. Did you try it? It's probably still possible to run existing AD under Rosetta.

**Comment by boneskull** [comment]
I'll see if an electron upgrade is straightforward as part of my work on #1870

**Comment by andrealim11** [comment]
in the end i'm using rosetta to open the appium GUI
