### ISSUE TITLE
The Android SDK root folder '--allow-cors' does not exist on the local file system

### ISSUE THREAD

**Issue by rajajhaj** [appium/appium-desktop#1986]
Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

<img width="471" alt="Screen Shot 2022-03-01 at 12 52 48 PM" src="https://user-images.githubusercontent.com/94397300/156230493-e5b8033c-db05-4412-956a-c619258b0107.png">
I have enabled `--allow-cors` within advanced settings and within edit configurations for both Android_Home & Java_Home. 

## Environment

- I am running Appium Desktop version 1.21.0.
- I am on (pick one):
    - [ ] Mac

**Comment by rajajhaj** [comment]
@jlipps Apologies for lack of info and late reply, I hope these screenshots are what you're looking for ?
<img width="558" alt="Screen Shot 2022-03-02 at 10 06 27 AM" src="https://user-images.githubusercontent.com/94397300/156388583-129af476-06dd-428f-a94e-364963f50219.png">
<img width="1276" alt="Screen Shot 2022-03-02 at 10 06 46 AM" src="https://user-images.githubusercontent.com/94397300/156388631-f9dd7af7-3d56-40d4-8cc7-115a986c94b1.png">

**Comment by jlipps** [comment]
i think you have misunderstood the configuration window. You are supposed to put paths in there, to set the values of JAVA_HOME and ANDROID_HOME. `--allow-cors` should definitely not be in either of those fields.
