### ISSUE TITLE
Appium not able to Capture snapshot after app launch 

### ISSUE THREAD

**Issue by Adil-Alef** [appium/appium-desktop#2001]
## After I launch the iOS .app file from Appium, Appium not able to capture the snapshot nor able to gather app source

Below is the Appium  log @KazuCocoa 

`[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.alefed.arabitsdev","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"value":{"sessionId":"8A9B8A8D-7571-488F-9A51-83538EC09886","capabilities":{"device":"iphone","browserName":"Arabits - Dev","sdkVersion":"15.4","CFBundleIdentifier":"com.alefed.arabitsdev"}},"sessionId":"8A9B8A8D-7571-488F-9A51-83538EC09886"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[BaseDriver] Event 'wdaSessionStarted' logged at 1648579236494 (00:10:36 GMT+0530 (India Standard Time))
[BaseDriver] Event 'wdaStarted' logged at 1648579236495 (00:10:36 GMT+0530 (India Standard Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1648579236495 (00:10:36 GMT+0530 (India Standard Time))
[BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[Appium] New XCUITestDriver session created successfully, session bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1648579236496 (00:10:36 GMT+0530 (India Standard Time))
[W3C (bfe5a64d)] Cached the protocol value 'W3C' for the new session bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5
[W3C (bfe5a64d)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","platformVersion":"15.4","deviceName":"iPhone 11","automationName":"XCUITest","app":"/Users/adilraza/Desktop/saale-ios-ask-curio-arabic copy.app","noReset":false,"includeSafariInWebviews":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"udid":"7FE06F38-AE5D-46BD-A423-D6BE762F7952"}}
[HTTP] <-- POST /wd/hub/session 200 20706 ms - 591
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/screenshot
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getScreenshot() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/8A9B8A8D-7571-488F-9A51-83538EC09886/screenshot] with no body
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[WD Proxy] Got response with status 500: {"value":{"error":"unable to capture screen","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Cannot take a screenshot within 20000 ms timeout\" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}","traceback":""},"sessionId":"8A9B8A8D-7571-488F-9A51-83538EC09886"}
[W3C] Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
[XCUITest] Error getting screenshot: Error Domain=com.facebook.WebDriverAgent Code=1 "Cannot take a screenshot within 20000 ms timeout" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}
[XCUITest] Falling back to 'simctl io screenshot' API
[W3C (bfe5a64d)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAzwAAAcACAYAAAAVAUYrAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAADPKADAAQAAAABAAAHAAAAAAAYjVEBAABAAElEQVR4Aey9WdftyFn4pzP2OT25u223wW7PxsYDNgab4Z+wMBgnK7CScJMLf4/c5TaX+SwsVrghTMtgFoEFOLYBGxu3h/aEabvn7tPDGaJHemvvklRVqipVSVXST2e9Z0tVz/irklTP1n73e+nzn//8vYYNAhCAAAQgAAEIQAACEIDADglc3mFOpAQBCEAAAhCAAAQgAAEIQKAjQMHDRIAABCAAAQhAAAIQgAAEdkuAgme3Q0tiEIAABCAAAQhAAAIQgAAFD3MAAhCAAAQgAAEIQAACENgtAQqe3Q4tiUEAAhCAAAQgAAEIQAACFDzMAQhAAAIQgAAEIAABCEBgtwQoeHY7tCQGAQhAAAIQgAAEIAABCFDwMAcgAAEIQAACEIAABCAAgd0SoODZ7dCSGAQgAAEIQAACEIAABCBAwcMcgAAEIAABCEAAAhCAAAR2S4CCZ7dDS2IQgAAEIAABCEAAAhCAAAUPcwACEIAABCAAAQhAAAIQ2C0BCp7dDi2JQQACEIAABCAAAQhAAAIUPMwBCEAAAhCAAAQgAAEIQGC3BCh4dju0JAYBCEAAAhCAAAQgAAEIUPAwByAAAQhAAAIQgAAEIACB3RKg4Nnt0JIYBCAAAQhAAAIQgAAEIEDBwxyAAAQgAAEIQAACEIAABHZLgIJnt0NLYhCAAAQgAAEIQAACEIAABQ9zAAIQgAAEIAABCEAAAhDYLQEKnt0OLYlBAAIQgAAEIAABCEAAAhQ8zAEIQAACEIAABCAAAQhAYLcEKHh2O7QkBgEIQAACEIAABCAAAQhQ8DAHIAABCEAAAhCAAAQgAIHdEqDg2e3QkhgEIAABCEAAAhCA...
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/screenshot 200 20485 ms - 210532
[HTTP] 
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 200 15986 ms - 42
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 3 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/window/rect
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getWindowRect() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getWindowRect'
[WD Proxy] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/8A9B8A8D-7571-488F-9A51-83538EC09886/window/size] with no body
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[W3C (bfe5a64d)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
[W3C (bfe5a64d)]     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[W3C (bfe5a64d)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/window/rect 500 123 ms - 683
[HTTP] 
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 12 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 2 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/source
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getPageSource() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getPageSource'
[WD Proxy] Matched '/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /source] to [GET http://127.0.0.1:8100/session/8A9B8A8D-7571-488F-9A51-83538EC09886/source] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[W3C (bfe5a64d)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
[W3C (bfe5a64d)]     at JWProxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[W3C (bfe5a64d)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/source 500 18 ms - 683
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 2 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 4 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts
[HTTP] {}
[W3C (bfe5a64d)] Calling AppiumDriver.getTimeouts() with args: ["bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5"]
[XCUITest] Executing command 'getTimeouts'
[W3C (bfe5a64d)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/bfe5a64d-fcf5-4f8c-aeac-a859615bb1e5/timeouts 304 1 ms - -`

Screenshot:
<img width="1440" alt="Screen Shot 2022-03-30 at 12 18 47 AM" src="https://user-images.githubusercontent.com/98915643/160684918-d16607ae-1222-43f4-bc4c-7037213b817f.png">

## Environment

- I am running Appium Desktop version _<1.22.0>_.
- I am on:
    - [ ] Mac M1 Chip

**Comment by jlipps** [comment]
This issue doesn't seem to be related to the Inspector. You should look at the iOS system log to see what is going on.

**Comment by KazuCocoa** [comment]
> "platformVersion":"15.4"

Please use appium 1.22.3 if you used xcode 13.3
https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-1223-from-1222
