### ISSUE TITLE
sendKeys and set_value in element datepicker are not working 

### ISSUE THREAD

**Issue by wsfcsk** [appium/appium-desktop#2008]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ * ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hi , I tried to use  python-client to find the datepicker element in IOS simulator , the datepicker (month , year )could be found , but the action "sendkeys" and "set_value" are not working , and there is no exception or error found during the operation 
here is my code :

datepicker = element.driver.find_element_by_ios_class_chain("""**/XCUIElementTypePickerWheel[`value == "April"`]""")

the element could be found , but sendkeys are not working , I used the latest appium desktop version 1.22.2

## Environment

- I am running Appium Desktop version _1.22.2_.
- I am on (pick one):
    - [ * ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you share the appium log?

The endpoint is https://developer.apple.com/documentation/xctest/xcuielement/1618672-adjusttopickerwheelvalue?language=objc by Apple as https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBElementCommands.m#L198
Thus, it could be potentially by XCTest internal issue.

**Comment by wsfcsk** [comment]
hi. , here is the log , seems no error found :

======
HTTP] <-- POST /wd/hub/session/b06fd4e6-f9eb-4370-816f-7246b5b4a958/element 200 3421 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/b06fd4e6-f9eb-4370-816f-7246b5b4a958/element/F9000000-0000-0000-838A-000000000000/value
[HTTP] {"text":"June","value":["J","u","n","e"],"id":"F9000000-0000-0000-838A-000000000000"}
[W3C (b06fd4e6)] Calling AppiumDriver.setValue() with args: [["J","u","n","e"],"F9000000-0000-0000-838A-000000000000","b06fd4e6-f9eb-4370-816f-7246b5b4a958"]
[XCUITest] Executing command 'setValue'
[WD Proxy] Matched '/element/F9000000-0000-0000-838A-000000000000/value' to command name 'setValue'
[Protocol Converter] Added 'text' property "June" to 'setValue' request body
[WD Proxy] Proxying [POST /element/F9000000-0000-0000-838A-000000000000/value] to [POST http://127.0.0.1:8100/session/7167501B-1015-4B72-BE9A-F0D990CC31C5/element/F9000000-0000-0000-838A-000000000000/value] with body: {"value":["J","u","n","e"],"text":"June"}
[WD Proxy] Got response with status 200: {"value":null,"sessionId":"7167501B-1015-4B72-BE9A-F0D990CC31C5"}
[W3C (b06fd4e6)] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/b06fd4e6-f9eb-4370-816f-7246b5b4a958/element/F9000000-0000-0000-838A-000000000000/value 200 387 ms - 14
[HTTP] ===============================

**Comment by wsfcsk** [comment]
And I checked anther datepicker which sendkeys function is working ,seems the log is pretty much the same 
=====================================================
[["F","e","b","r","u","a","r","y"],"1F0A0000-0000-0000-F38E-000000000000","6310831c-ab88-4e07-8322-2128a87a26e3"]
[XCUITest] Executing command 'setValue'
[WD Proxy] Matched '/element/1F0A0000-0000-0000-F38E-000000000000/value' to command name 'setValue'
[Protocol Converter] Added 'text' property "February" to 'setValue' request body
[WD Proxy] Proxying [POST /element/1F0A0000-0000-0000-F38E-000000000000/value] to [POST http://127.0.0.1:8100/session/24E5AFC4-1F18-44EC-917F-612F2AD5D727/element/1F0A0000-0000-0000-F38E-000000000000/value] with body: {"value":["F","e","b","r","u","a","r","y"],"text":"February"}
[WD Proxy] Got response with status 200: {"value":null,"sessionId":"24E5AFC4-1F18-44EC-917F-612F2AD5D727"}
===========================

**Comment by KazuCocoa** [comment]
> And I checked anther datepicker which sendkeys function is working ,seems the log is pretty much the same

Then, Appium worked correctly but how it worked depending on XCTest by Apple.

**Comment by wsfcsk** [comment]
Hi  
I found this may help :https://appium.io/docs/en/writing-running-appium/tutorial/swipe/ios-picker-wheels-mobile/

but I used python , could you provide the python way of this workaround ?

**Comment by KazuCocoa** [comment]
It is a mobile command. https://github.com/appium/appium-xcuitest-driver#mobile-selectpickerwheelvalue-1
As https://appium.io/docs/en/commands/mobile-command/ , you can call it like `self.driver.execute_script("mobile: scroll", {'direction': 'down'})`.

The picker one will be like `execute_script("mobile: selectPickerWheelValue", {'elementId': e.id, 'order': 'next'})`

**Comment by wsfcsk** [comment]
thanks ! I will try and get back to you

**Comment by wsfcsk** [comment]
Hi  
thanks , it's working , here is my code ,anyone who met this issue could be refer to :

monthDatePicker = element.find((AppiumBy.XPATH, '//XCUIElementTypeOther[@name="view.OpportunityFormViewController"]/XCUIElementTypeTable/XCUIElementTypeCell[6]/XCUIElementTypePicker/XCUIElementTypePickerWheel[1]'))


pid = monthDatePicker.id
scroll = {"order":"next","offset": "0.1","element":pid}

while True:
	element.driver.execute_script("mobile: selectPickerWheelValue",scroll)
	text = monthDatePicker.text
	#element.Sleep(1)
	if text == "March":
		break
