### ISSUE TITLE
Include latest version of WinAppDriver in Appium Desktop

### ISSUE THREAD

**Issue by gouthamsam** [appium/appium-desktop#201]
https://github.com/Microsoft/WinAppDriver/releases/download/v0.9-beta/WindowsApplicationDriver.msi

Cannot handle screenshots correctly with the version 0.7-beta.

**Comment by jlipps** [comment]
WinAppDriver is bundled with Appium, and Appium is bundled with Appium Desktop. We don't (yet) release different versions of different drivers separately. Once Appium 1.6.5 is published, it will have the latest WinAppDriver. Then we will make a new release of Appium Desktop which contains Appium 1.6.5.
