### ISSUE TITLE
Update Espresso driver to 1.46.0

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium-desktop#2015]
Appium Desktop

## The problem

Espresso driver has implemented a new feature to support Jetpack Compose from release 1.46.0, but the last release of Appium Desktop is still using 1.45.3.

Is it planned to upgrade the version of the driver for the next release ?

Thank you

## Environment

- I am running Appium Desktop version _1.22.2
- I am on Mac

**Comment by jlipps** [comment]
There aren't plans to continue supporting Appium 1.x in Appium Desktop, but if someone wants to update Appium 1.x to latest in this repo and verify it works, I'm happy to merge.

Our recommendation to get the latest drivers is to use Appium 2 from the command line. Now that the Inspector is decoupled from Appium Desktop, it's unlikely Appium Desktop Server will see much investment in the short term.

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @jlipps,

We can change to use the command line option. I have tried to install it as the web page suggests:

`
> brew install node      # get node.js
> npm install -g appium  # get appium
> npm install wd         # get appium client
> appium &               # start appium`

But the running version is still v1.22... Should we install the Appium 2.0 following other instructions ?

**Comment by jlipps** [comment]
The guide for migrating from 1 to 2 is here right now: https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md. Basically you just need to `npm install appium@next` to get 2.0. 

our website is incredibly outdated and will be updated with the release of 2.0.

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @jlipps, I'll try to use Appium 2.0 with the documentation.

Thank you for the information
