### ISSUE TITLE
"Ghost" test runs happening randomly when inspecting with desktop

### ISSUE THREAD

**Issue by reuningATL** [appium/appium-desktop#203]
Just seeing if anyone else was having this problem. Sometimes I'll be inspecting my app and all of a sudden, the appium server will start a test run. I usually launch from eclipse or a chron job that runs a jar so I don't know how it is running. Not a critical problem but can be annoying after a while.

**Comment by jlipps** [comment]
This would be a problem with whatever else on your system is attempting to run an appium test. If you are running tests via cron that is likely it. (Also, probably not a good idea to run tests via cron, or if you must, don't use appium desktop on the same machine).
