### ISSUE TITLE
Execute the API to obtain the memory infomation and throw an exception

### ISSUE THREAD

**Issue by 252694995** [appium/appium-desktop#2032]
## The problem

This is Python code to get memory information ：
![1651049359(1)](https://user-images.githubusercontent.com/67477052/165480024-7c3d307d-920a-45c7-b64a-1cf112cd3776.png)

This is the appium error log：
![8d9cc31bceab8c900a5e74d4a8edf77](https://user-images.githubusercontent.com/67477052/165480384-8c5689f0-9852-4d26-aedf-5fd6471d897e.png)

## Environment
Appium-v1.22.3
Android11
Windows10

**Comment by jlipps** [comment]
It seems this issue is not related to appium-desktop but to Appium. Can you please submit an issue there instead. And of course you will need to first check with the latest version of Appium (2.0-beta) and the latest version of the UiAutomator2 driver.
