### ISSUE TITLE
Failed to create session

### ISSUE THREAD

**Issue by brandkzafiro** [appium/appium-desktop#2036]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

It occur in both, Appium and Appium desktop

## The problem

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up.

Could connect to my emulator android from Appium inspector.

Appium Inspector:

> {
  "platformName": "Android",
  "appium:platformVersion": "12.0",
  "appium:deviceName": "Pixel 3a API 31",
  "appium:automationName": "UiAutomator2",
  "appium:appPackage": "com.sylndrpro",
  "appium:appActivity": "com.sylndrpro.MainActivity",
  "appium:udid": "emulator-5554"
}

An the logs for Appium Desktop:
> [info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.22.3
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   port: 4724
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4724[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12.0","appium:deviceName":"Pixel 3a API 31","appium:automationName":"UiAutomator2","appium:appPackage":"com.sylndrpro","appium:appActivity":"com.sylndrpro.MainActivity","appium:udid":"emulator-5554","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"12.0","appium:deviceName":"Pixel 3a API 31","appium:automationName":"UiAutomator2","appium:appPackage":"com.sylndrpro","appium:appActivity":"com.sylndrpro.MainActivity","appium:udid":"emulator-5554","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"12.0","appium:deviceName":"Pixel 3a API 31","appium:automationName":"UiAutomator2","appium:appPackage":"com.sylndrpro","appium:appActivity":"com.sylndrpro.MainActivity","appium:udid":"emulator-5554","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12.0","appium:deviceName":"Pixel 3a API 31","appium:automationName":"UiAutomator2","appium:appPackage":"com.sylndrpro","appium:appActivity":"com.sylndrpro.MainActivity","appium:udid":"emulator-5554","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1651759027528 (08:57:07 GMT-0500 (hora estándar de Colombia))
[info] [35m[Appium][39m Appium v1.22.3 creating new AndroidUiautomator2Driver (v1.70.1) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "Android",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "12.0",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "Pixel 3a API 31",
[debug] [35m[BaseDriver][39m     "appium:automationName": "UiAutomator2",
[debug] [35m[BaseDriver][39m     "appium:appPackage": "com.sylndrpro",
[debug] [35m[BaseDriver][39m     "appium:appActivity": "com.sylndrpro.MainActivity",
[debug] [35m[BaseDriver][39m     "appium:udid": "emulator-5554",
[debug] [35m[BaseDriver][39m     "appium:ensureWebviewsHavePages": true,
[debug] [35m[BaseDriver][39m     "appium:nativeWebScreenshot": true,
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": 3600,
[debug] [35m[BaseDriver][39m     "appium:connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   connectHardwareKeyboard
[info] [35m[BaseDriver][39m Session created with session id: 1d401265-d969-41c0-9e34-6ca5975ca201
[info] [35m[UiAutomator2][39m Starting 'com.sylndrpro' directly on the device
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices[debug] [35m[ADB][39m Connected devices: [{"udid":"emulator-5554","state":"device"}]
[info] [35m[AndroidDriver][39m Using device: emulator-5554
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'[debug] [35m[ADB][39m Setting device id to emulator-5554
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 31
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m 'io.appium.settings' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [35m[ADB][39m The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.4.0' >= '3.4.0')
[debug] [35m[ADB][39m There is no need to install/upgrade 'C:\Users\branz\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Getting IDs of all 'io.appium.settings' processes
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'[debug] [35m[AndroidDriver][39m io.appium.settings is already running. There is no need to reset its permissions.
[debug] [35m[Logcat][39m Starting logs capture with command: C:\\Users\\branz\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 logcat -v threadtime[debug] [35m[UiAutomator2][39m Forwarding UiAutomator2 Server port 6790 to local port 8200[debug] [35m[ADB][39m Forwarding system: 8200 to device: 6790
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp:8200 tcp:6790'
[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'[debug] [35m[ADB][39m 'io.appium.uiautomator2.server' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.uiautomator2.server'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'[debug] [35m[ADB][39m The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.27.0' >= '4.27.0')
[debug] [35m[UiAutomator2][39m io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [35m[ADB][39m Checking app cert for C:\Users\branz\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk
[debug] [35m[ADB][39m Using the previously cached signature entry for 'appium-uiautomator2-server-v4.27.0.apk'
[debug] [35m[ADB][39m sha256 hash did match for 'appium-uiautomator2-server-v4.27.0.apk'
[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server.test
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'[debug] [35m[ADB][39m 'io.appium.uiautomator2.server.test' is installed
[debug] [35m[ADB][39m Checking app cert for C:\Users\branz\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [35m[ADB][39m Using the previously cached signature entry for 'appium-uiautomator2-server-debug-androidTest.apk'
[debug] [35m[ADB][39m sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[info] [35m[UiAutomator2][39m Server packages are not going to be (re)installed
[debug] [35m[UiAutomator2][39m Waiting up to 30000ms for services to be available
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list instrumentation'
[debug] [35m[UiAutomator2][39m Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[info] [35m[ADB][39m Adding packages ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to Doze whitelist
[debug] [35m[ADB][39m Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server.test",";"]]
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server.test ;'[debug] [35m[UiAutomator2][39m No app capability. Assuming it is already on the device
[debug] [35m[ADB][39m Getting install status for com.sylndrpro
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.sylndrpro'[debug] [35m[ADB][39m 'com.sylndrpro' is installed
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.sylndrpro'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm clear com.sylndrpro'[debug] [35m[AndroidDriver][39m Performed fast reset on the installed 'com.sylndrpro' application (stop and clear)
[debug] [35m[UiAutomator2][39m Performing shallow cleanup of automation leftovers[debug] [35m[UiAutomator2][39m No obsolete sessions have been detected
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server.test'[info] [35m[UiAutomator2][39m Starting UIAutomator2 server 4.27.0
[info] [35m[UiAutomator2][39m Using UIAutomator2 server from 'C:\Users\branz\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk' and test from 'C:\Users\branz\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[info] [35m[UiAutomator2][39m Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [35m[ADB][39m Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"None","value":{"message":"UiAutomator2 Server is ready to accept commands","ready":true}}
[debug] [35m[UiAutomator2][39m The initialization of the instrumentation process took 104ms
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8200/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"12.0","deviceName":"Pixel 3a API 31","automationName":"UiAutomator2","appPackage":"com.sylndrpro","appActivity":"com.sylndrpro.MainActivity","udid":"emulator-5554","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true},"platformName":"Android","platformVersion":"12.0","deviceName":"emulator-5554","automationName":"UiAutomator2","appPackage":"com.sylndrpro","appActivity":"com.sylndrpro.MainActivity","udid":"emulator-5554","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"deviceUDID":"emulator-5554"}],"alwaysMatch":{}}}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"2ef3108f-9088-45d6-b296-b34354dbefb0","value":{"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"12.0","deviceName":"Pixel 3a API 31","automationName":"UiAutomator2","appPackage":"com.sylndrpro","appActivity":"com.sylndrpro.MainActivity","udid":"emulator-5554","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true},"platformName":"Android","platformVersion":"12.0","deviceName":"emulator-5554","automationName":"UiAutomator2","appPackage":"com.sylndrpro","appActivity":"com.sylndrpro.MainActivity","udid":"emulator-5554","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"deviceUDID":"emulator-5554"}],"alwaysMatch":{}},"sessionId":"2ef3108f-9088-45d6-...
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'W3C'
[debug] [35m[WD Proxy][39m Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8200/wd/hub/session/2ef3108f-9088-45d6-b296-b34354dbefb0/appium/device/info] with no body[info] [35m[AndroidDriver][39m Screen already unlocked, doing nothing
[info] [35m[UiAutomator2][39m Starting 'com.sylndrpro/com.sylndrpro.MainActivity and waiting for 'com.sylndrpro/com.sylndrpro.MainActivity'
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.sylndrpro/com.sylndrpro.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0[debug] [35m[Instrumentation][39m The process has exited with code 0[debug] [35m[WD Proxy][39m Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8200/wd/hub/session/2ef3108f-9088-45d6-b296-b34354dbefb0/appium/device/pixel_ratio] with no body
[info] [35m[WD Proxy][39m socket hang up
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[WD Proxy][39m Matched '/' to command name 'deleteSession'
[debug] [35m[WD Proxy][39m Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/2ef3108f-9088-45d6-b296-b34354dbefb0] with no body
[info] [35m[WD Proxy][39m socket hang up
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.sylndrpro'[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:8200'[info] [35m[UiAutomator2][39m Restoring hidden api policy to the device default configuration
[debug] [35m[ADB][39m Running 'C:\Users\branz\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1651759039691 (08:57:19 GMT-0500 (hora estándar de Colombia))
[debug] [35m[W3C][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[W3C][39m     at UIA2Proxy.command (C:\Users\branz\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
[debug] [35m[W3C][39m     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m12175 ms - 669[39m
[info] [35m[HTTP][39m [90m[39m[debug] [35m[Instrumentation][39m io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:

## Environment

- I am running Appium Desktop version _1.22.3_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
If the error also occurs in appium, then it's not related to appium desktop and should not be reported here.
