### ISSUE TITLE
Error while saving Presets for Appium Desktop on Sierra

### ISSUE THREAD

**Issue by iquicktest** [appium/appium-desktop#204]
## Appium or Appium Desktop?
Appium Desktop

- [v] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
when I try to save caps set, nothing happen, and I still cannot see any set from Saved cap sets.

## Environment

- I am running Appium Desktop version _1.0.2_beta2_.
- I am on (pick one):
    - [v] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
can you delete your `~/Library/Application Support/appium-desktop` folder and try again?

**Comment by iquicktest** [comment]
it works. thanks @jlipps
