### ISSUE TITLE
[debug] [W3C] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

### ISSUE THREAD

**Issue by denizbabayaka** [appium/appium-desktop#2042]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

While running several test cases some of them suddenly fails with error creating session.

## Environment

- I am running Appium Desktop version _<1.22.3>_.
- I am on ( Windows):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Did you verify that the issue doesn't occur with Appium and only with Appium Desktop?

**Comment by denizbabayaka** [comment]
I am new to Appium and i am using Eclipse to run the code  and my Emulator is running in Android Studio  ,when I run the test from the chrome browser I face this issue

**Comment by denizbabayaka** [comment]
I am new to Appium and i am using Eclipse to run the code and my Emulator
is running in Android Studio ,when I run the test from the chrome browser I
face this issue

**Comment by jlipps** [comment]
(a) try running with Appium from the command line. Appium Desktop is a wrapper around it and if you want to know if there is an issue, it's more helpful to go direct to the source
(b) if you still encounter an issue, follow the issue template when reporting an issue at https://github.com/appium/appium, including sending in your full server logs.
