### ISSUE TITLE
Unable to link，help me

### ISSUE THREAD

**Issue by jiang-xin9** [appium/appium-desktop#2043]
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.netease.cloudmusic' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\androidsdk\\platform-tools\\adb.exe -P 5037 -s 181QGEYN227MN shell am start -W -n com.netease.cloudmusic/com.netease.cloudmusic.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 4294967295'; Command output: Exception occurred while executing 'start': java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.netease.cloudmusic/.activity.MainActivity } from null (pid=9684, uid=2000) not exported from uid 10214

**Comment by jiang-xin9** [comment]
![图片](https://user-images.githubusercontent.com/82875017/168947652-683e1015-466c-49e0-88f3-17e64b56c4df.png)

**Comment by jlipps** [comment]
this isn't an issue with appium desktop. it's either an issue with appium or with your app. i'd ask for help in the appium forums and create an issue at the appium repo if you think it's a bug.

**Comment by jlipps** [comment]
then please fill out a full report at appium/appium using the provided issue template and sharing all the requested details. without them it will be impossible to help.
