### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by Harish8260** [appium/appium-desktop#205]
## Appium Desktop

Installed Appium 1.0.2-beta.2 Desktop using DMG file in MacOS and Appium Server is v1.6.4.
-Run Appium Server in CommandLine and in Appium Desktop set the Desired Capabilities as follows:
{
  "platformName": "iOS",
  "platformVersion": "10.3.1",
  "app": "/Users/dharmendra/Desktop/mac/ViolaCard.ipa",
  "noReset": true,
  "udid": "3f63da7abc066fc1d9cba20bcaa1982093c341ff",
  "deviceName": "iPhone 6s+"
}

-Set the custom 127.0.0.1:4723
-Started the Session
WebDriver Agent is installed and automatically deleted while running the session and displaying the error as in the screenshot

## Environment

- I am running Appium Desktop version _1.0.2-beta.2.
- I am on (pick one):Mac
  

#Appium Full Log

[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/dharmendra/Desktop/mac/ViolaCard.ipa","deviceName":"iPhone 6s+","noReset":true,"platformName":"iOS","platformVersion":"10.3.1","udid":"3f63da7abc066fc1d9cba20bcaa1982093c341ff","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/dharmendra/Desktop/mac/ViolaCard.ipa","deviceName":"iPhone 6s+","noReset":true,"platformName":"iOS","platformVersion":"10.3.1","udid":"3f63da7abc066fc1d9cba20bcaa1982093c341ff","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1495517891867 (11:08:11 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/dharmendra/Desktop/mac/ViolaCard.ipa'
[Appium]   deviceName: 'iPhone 6s+'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3.1'
[Appium]   udid: '3f63da7abc066fc1d9cba20bcaa1982093c341ff'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: 765864bb-bfd3-4a1d-ab29-c0b270aa5b83
[debug] [XCUITest] Xcode version set to '8.3.1' (tools v8.3.0.0.1.1490382677)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1495517892027 (11:08:12 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 3f63da7abc066fc1d9cba20bcaa1982093c341ff
[debug] [XCUITest] Creating iDevice object with udid '3f63da7abc066fc1d9cba20bcaa1982093c341ff'
[XCUITest] Determining device to run tests on: udid: '3f63da7abc066fc1d9cba20bcaa1982093c341ff', real device: true
[BaseDriver] Using local app '/Users/dharmendra/Desktop/mac/ViolaCard.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/2b/rvk9h2v15msfvf7zdps7xym80000gn/T/2017423-1927-12rodgo.nygsowp14i/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/2b/rvk9h2v15msfvf7zdps7xym80000gn/T/2017423-1927-12rodgo.nygsowp14i/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/2b/rvk9h2v15msfvf7zdps7xym80000gn/T/2017423-1927-12rodgo.nygsowp14i/Payload/ViolaCard.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1495517893160 (11:08:13 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/2b/rvk9h2v15msfvf7zdps7xym80000gn/T/2017423-1927-12rodgo.nygsowp14i/Payload/ViolaCard.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/2b/rvk9h2v15msfvf7zdps7xym80000gn/T/2017423-1927-12rodgo.nygsowp14i/Payload/ViolaCard.app': 'eu.vwallet.ViolaCard'
[debug] [BaseDriver] Event 'resetStarted' logged at 1495517893180 (11:08:13 GMT+0530 (IST))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1495517893181 (11:08:13 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1495517893377 (11:08:13 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] App 'eu.vwallet.ViolaCard' is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1495517893551 (11:08:13 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1495517893553 (11:08:13 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=3f63da7abc066fc1d9cba20bcaa1982093c341ff -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/dharmendra/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/B2DC2C3F-CFC0-4708-BD02-B588499C5FDF/Session-WebDriverAgentRunner-2017-05-23_110820-HEDluZ.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-05-23 11:08:24.570 xcodebuild[1962:40952] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-05-23 11:07:39.295584+0530 XCTRunner[1277:557911] Running tests...
[Xcode] 2017-05-23 11:07:39.307011+0530 XCTRunner[1277:557911] The bundle “WebDriverAgentRunner” couldn’t be loaded because it doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.
[Xcode] 2017-05-23 11:07:39.307522+0530 XCTRunner[1277:557911] (dlopen_preflight(/var/containers/Bundle/Application/DAD40737-B303-456D-A662-C4247097D8EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
[Xcode] 	/var/containers/Bundle/Application/DAD40737-B303-456D-A662-C4247097D8EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture
[Xcode] 	/private/var/containers/Bundle/Application/DAD40737-B303-456D-A662-C4247097D8EE/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture)
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1495517904616 (11:08:24 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 1960)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1495517914917 (11:08:34 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=3f63da7abc066fc1d9cba20bcaa1982093c341ff -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/dharmendra/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/8BA9847C-3E96-41BC-9B67-74B85C746A58/Session-WebDriverAgentRunner-2017-05-23_110841-zHuctE.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-05-23 11:08:46.364 xcodebuild[1995:41208] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-05-23 11:08:01.091887+0530 XCTRunner[1281:558244] Running tests...
[Xcode] 2017-05-23 11:08:01.101502+0530 XCTRunner[1281:558244] The bundle “WebDriverAgentRunner” couldn’t be loaded because it doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.
[Xcode] 2017-05-23 11:08:01.101610+0530 XCTRunner[1281:558244] (dlopen_preflight(/var/containers/Bundle/Application/4F303A45-1D20-4296-B10B-61A43FD58D2B/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
[Xcode] 	/var/containers/Bundle/Application/4F303A45-1D20-4296-B10B-61A43FD58D2B/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture
[Xcode] 	/private/var/containers/Bundle/Application/4F303A45-1D20-4296-B10B-61A43FD58D2B/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture)
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1495517926399 (11:08:46 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 1993)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 44761 ms - 230

**Comment by Harish8260** [comment]
Could anyone help me with detailed steps

**Comment by yogeshthanvi** [comment]
I am facing the same issue

**Comment by jlipps** [comment]
This is not an Appium desktop issue. Please re-ask on the Appium repo.
