### ISSUE TITLE
iOS elements are not detecting for react native app. Android working fine

### ISSUE THREAD

**Issue by anupamhore** [appium/appium-desktop#2058]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

iOS elements are not getting detected for our automation. We have a react native application. The same is working fine in Android. 
The attributes which we used in the UI elements are **accessibilityLabel** and **testID**.  Even though we are unable to detect the elements for iOS in appium
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/17607476/173990242-4af6502a-ff52-4582-9ef1-1e71dfad740b.png)

## Environment

- I am running Appium Desktop version 1.22.3
- I am running on  Windows

**Comment by wswebcreation** [comment]
Hi @anupamhore 

There are a few things, but first comes first. The screenshot you share is from Appium Inspector, which is the GUI version of Appium. You submitting an issue on Appium Desktop, this project, which is only the server. The Inspector project can be found here https://github.com/appium/appium-inspector/issues

Secondly, this is not related to Appium Inspector but to the combination of Appium and React Native, so this issue needs to be filed on the Appium project.

Last but not least, React Native behaves differently for iOS as it does for Android. React Native has elements that are accessible. By default, all touchable elements are accessible. This indicates that the view is an accessibility element. When an element is an accessibility element, it groups its children into a single selectable component, see also https://reactnative.dev/docs/accessibility.
It can also depend on the navigation that you/your developers are using, see https://github.com/appium/appium/issues/14825

**How to overcome:**
- you can try to adjust the `customSnapshotTimeout` and or `snapshotMaxDepth`, see https://github.com/appium/appium-xcuitest-driver. Sometimes it takes to long to build up the tree and by adjusting these values you might give Appium more time to translate the tree
- You can check with the devs if there are accessible elements in your app and ask them to disable the property on those elements so React Native will return all children to Appium

Hope this helps

@jlipps / @KazuCocoa can you close this issue?

**Comment by KazuCocoa** [comment]
thank you!
