### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65     at XCUITestDriver.quitAndUninstall$ 

### ISSUE THREAD

**Issue by yogeshthanvi** [appium/appium-desktop#206]
Summary : 
I am new to Appium desktop and while running my session i facing the issue where the web driver agent  is unable to launch . I have checked on various similar issues posted on forums or git and also tried the solution but got no success 

Configurations : 
The Defined Capabilities 

{
  "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "9.3.5",
  "deviceName": "iPhone",
  "app": "/path/to/app.ipa",
  "udid": "xxxx....xxx",
  "updatedWDABundleId": "io.mynt.GreatersTest",
  "xcodeOrgId": "xxxxxxxxxx",
  "xcodeSigningId": "iPhone Developer",
  "showXcodeLog": true,
  "useNewWDA": true
}

Environment : 
 Mac OS Sierra version 10.12.5 (16F73)
Xcode Version 8.3.2 (8E2002)

Attachments : 
The Log files you can see on the below link 
https://gist.github.com/yogeshthanvi/db23ab8a0e95c61e76a8b1a9584f998e

Tried Solutions : 
The Solutions already tried 
1. Rebooting the device 
2. Create a provisioning and signing certificate but i doubt i have done it proper i, if any one can help on this also it would be great 

Let me know if anything i missed out in describing the problem

**Comment by jlipps** [comment]
This issue should be discussed at the appium repo, not the appium desktop repo.
