### ISSUE TITLE
Can't find Chinese element?

### ISSUE THREAD

**Issue by gey7007** [appium/appium-desktop#207]
Env: Appium Desktop1.6.4+Windows+python2.7
-----------------------------------------------------------------------
...
desired_caps['automationName'] = 'Uiautomator2'
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '5.1'
desired_caps['deviceName'] = '192.168.19.101:5555'
...
try:
 el=WebDriverWait(driver,10,0.5).until(EC.presence_of_element_located((By.XPATH,".//[contains(@text,u'中文')]")))
 print el
except:
 print "FAILED"
------------------------------------------------------------------------
Result:
<appium.webdriver.webelement.WebElement (session="248f9140-102b-40e0-8025-44f2e96a0fc0", element="dc73f800-9db3-4d9a-ad4f-70f3450286b0")>
===========================================
Question :APP don't exist ‘中文’,it should is "FAILED",but no.

**Comment by jlipps** [comment]
@gey7007 does this work with appium command line?

**Comment by gey7007** [comment]
pycharm run script, ruturn  above result.

**Comment by jlipps** [comment]
ok i am going to close this here, since the issue you are encountering is not specific to appium desktop. it has to do with appium itself. please re-ask at the appium/appium repo.
