### ISSUE TITLE
FAILURE: org.openqa.selenium.SessionNotCreatedException:  Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: Authorization required

### ISSUE THREAD

**Issue by polianaysato** [appium/appium-desktop#2073]
I am running the below command that gives the following error. Please, could anyone help me in resolving this issue? I need to run full end to end tests using browserstack and selenium, but can't figure out how to solve the problem. Thanks

mvn clean test -q -e -Dsurefire.suiteXmlFiles=browserstack-testng.xml

org.openqa.selenium.SessionNotCreatedException: 
Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: Authorization required
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XXXXXX', ip: 'XXXXXXX', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.4', java.version: '11.0.15'
Driver info: driver.version: AndroidDriver
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: Authorization required
Caused by: org.openqa.selenium.json.JsonException: 
Unable to determine type from: A. Last 1 characters read: A
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XXXXXXX', ip: 'XXXXXXXXXX', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.4', java.version: '11.0.15'
Driver info: driver.version: AndroidDriver

**Comment by jlipps** [comment]
This does not appear to have anything to do with Appium Desktop. Report the issue to BrowserStack instead.
