### ISSUE TITLE
Getting Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\300895\AppData\Local\Temp\2\2022620-7972-fc5ofd.a73he\appium-uiautomator2-server-v4.27.0.apk'. Original error: The 'java.exe' binary could not be found neither in PATH nor under JAVA_HOME (C:\Program Files\Java\jdk1.8.0_331\bin\bin)

### ISSUE THREAD

**Issue by DaisyBakiyashri** [appium/appium-desktop#2081]
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.22.2
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"C:\\Users\\userid\\Documents\\automation/src/test/resources/apps/appPackagerain-debug.apk","appActivity":"appPackagegib.appPackage.appPackagerain","appPackage":"appPackagegib.appPackage","platformVersion":"10","automationName":"Appium","platformName":"Android","udid":"DUM0219910001318","deviceName":"HUAWEI P30 PRO"},"capabilities":{"firstMatch":[{"appium:app":"C:\\Users\\userid\\Documents\\automation/src/test/resources/apps/appPackagerain-debug.apk","appium:appActivity":"appPackagegib.appPackage.appPackagerain","appium:appPackage":"appPackagegib.appPackage","appium:automationName":"Appium","appium:deviceName":"HUAWEI P30 PRO","platformName":"android","appium:platformVersion":"10","appium:udid":"DUM0219910001318"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\userid\\Documents\\automation/src/test/resources/apps/appPackagerain-debug.apk","appActivity":"appPackagegib.appPackage.appPackagerain","appPackage":"appPackagegib.appPackage","platformVersion":"10","automationName":"Appium","platformName":"Android","udid":"DUM0219910001318","deviceName":"HUAWEI P30 PRO"},null,{"firstMatch":[{"appium:app":"C:\\Users\\userid\\Documents\\automation/src/test/resources/apps/appPackagerain-debug.apk","appium:appActivity":"appPackagegib.appPackage.appPackagerain","appium:appPackage":"appPackagegib.appPackage","appium:automationName":"Appium","appium:deviceName":"HUAWEI P30 PRO","platformName":"android","appium:platformVersion":"10","appium:udid":"DUM0219910001318"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1658312970081 (13:29:30 GMT+0300 (Arabian Standard Time))
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m 
[info] [35m[Appium][39m Appium v1.22.2 creating new AndroidUiautomator2Driver (v1.70.1) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "android",
[debug] [35m[BaseDriver][39m     "appium:app": "C:\\Users\\userid\\Documents\\automation/src/test/resources/apps/appPackagerain-debug.apk",
[debug] [35m[BaseDriver][39m     "appium:appActivity": "appPackagegib.appPackage.appPackagerain",
[debug] [35m[BaseDriver][39m     "appium:appPackage": "appPackagegib.appPackage",
[debug] [35m[BaseDriver][39m     "appium:automationName": "Appium",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "HUAWEI P30 PRO",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "10",
[debug] [35m[BaseDriver][39m     "appium:udid": "DUM0219910001318"
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[info] [35m[BaseDriver][39m Session created with session id: 553c98da-11d3-4c39-a26b-c3d8fe5f8596
[info] [35m[BaseDriver][39m Using local app 'C:\Users\userid\Documents\automation/src/test/resources/apps/appPackagerain-debug.apk'
[debug] [35m[UiAutomator2][39m Checking whether app is actually present
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices[debug] [35m[ADB][39m Connected devices: [{"udid":"DUM0219910001318","state":"device"}]
[info] [35m[AndroidDriver][39m Using device: DUM0219910001318
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[debug] [35m[ADB][39m Setting device id to DUM0219910001318
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 29
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 10
[debug] [35m[ADB][39m Device API level: 29
[info] [35m[UiAutomator2][39m Relaxing hidden api policy
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 wait-for-device'[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell echo ping'
[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m 'io.appium.settings' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.4.0' >= '3.4.0')
[debug] [35m[ADB][39m There is no need to install/upgrade 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Getting IDs of all 'io.appium.settings' processes
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell 'pgrep --help; echo $?''[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'[debug] [35m[AndroidDriver][39m io.appium.settings is already running. There is no need to reset its permissions.
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell appops set io.appium.settings android:mock_location allow'[debug] [35m[Logcat][39m Starting logs capture with command: C:\\Users\\userid\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s DUM0219910001318 logcat -v threadtime[debug] [35m[UiAutomator2][39m Forwarding UiAutomator2 Server port 6790 to local port 8200[debug] [35m[ADB][39m Forwarding system: 8200 to device: 6790
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 forward tcp:8200 tcp:6790'
[info] [35m[UiAutomator2][39m Server package at 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk' is not writeable. Will copy it into the temporary location at 'C:\Users\userid\AppData\Local\Temp\2\2022620-7972-fc5ofd.a73he' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[info] [35m[UiAutomator2][39m Server package at 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Will copy it into the temporary location at 'C:\Users\userid\AppData\Local\Temp\2\2022620-7972-fc5ofd.a73he' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell dumpsys package io.appium.uiautomator2.server'[debug] [35m[ADB][39m 'io.appium.uiautomator2.server' is not installed
[debug] [35m[ADB][39m App 'C:\Users\userid\AppData\Local\Temp\2\2022620-7972-fc5ofd.a73he\appium-uiautomator2-server-v4.27.0.apk' is not installed
[debug] [35m[UiAutomator2][39m io.appium.uiautomator2.server installation state: notInstalled
[debug] [35m[ADB][39m Checking app cert for C:\Users\userid\AppData\Local\Temp\2\2022620-7972-fc5ofd.a73he\appium-uiautomator2-server-v4.27.0.apk
[info] [35m[ADB][39m Using 'apksigner.jar' from 'C:\Users\userid\AppData\Local\Android\Sdk\build-tools\32.1.0-rc1\lib\apksigner.jar'
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[WD Proxy][39m Matched '/' to command name 'deleteSession'
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell am force-stop appPackagegib.appPackage'[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 forward --remove tcp:8200'
[info] [35m[UiAutomator2][39m Restoring hidden api policy to the device default configuration
[debug] [35m[ADB][39m Running 'C:\Users\userid\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DUM0219910001318 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1658312975131 (13:29:35 GMT+0300 (Arabian Standard Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\userid\AppData\Local\Temp\2\2022620-7972-fc5ofd.a73he\appium-uiautomator2-server-v4.27.0.apk'. Original error: The 'java.exe' binary could not be found neither in PATH nor under JAVA_HOME (C:\Program Files\Java\jdk1.8.0_331\bin\bin)
[debug] [35m[W3C][39m     at ADB.checkApkCert (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:306:11)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m5052 ms - 1159[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by jlipps** [comment]
This is not an issue with appium desktop. Furthermore, the error in the log shows you what is wrong (you have an incorrect JAVA_HOME).
