### ISSUE TITLE
Facing unexpected token issue while saving desired capabilities for Android on appium

### ISSUE THREAD

**Issue by avesha14** [appium/appium-desktop#2083]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

<img width="1257" alt="Screenshot 2022-07-26 at 7 04 35 PM" src="https://user-images.githubusercontent.com/106554249/181019120-90d643ab-fa32-4aba-9e39-6b79c1ee91dc.png">

**Comment by avesha14** [comment]
May I know the solution for above issue?

**Comment by jlipps** [comment]
looks like you're using typographers quotes instead of regular quotes (maybe you copied and pasted from some other source). typographers quotes are not valid json.

**Comment by avesha14** [comment]
@jlipps I haven't copied from any source even if I tried another quotes , same issue is occurring.
<img width="1251" alt="Screenshot 2022-07-27 at 2 10 27 PM" src="https://user-images.githubusercontent.com/106554249/181202761-255ccc3d-d281-4aba-ba1a-ba7080c0d382.png">

**Comment by jlipps** [comment]
those are two single quotes next to each other, rather than a double quote.  it's still not valid JSON.
