### ISSUE TITLE
XCTAutomationSupport.framework error with XCode 14.0 Beta 6

### ISSUE THREAD

**Issue by DGandalf** [appium/appium-desktop#2092]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Dynamic Compile of WebdriverAgentLib fails when compiling with XCode 14.0 Beta 6

## Environment

- I am running Appium Desktop version v1.22.3-4.
- I am on (pick one):
    - [ X] Mac
    - [ ] Windows
    - [ ] Linux

The compilation of the WebdriverAgentLib runs with no error with 13.4.1 when switching to Xcode 14.0 Beta 6 for Testing with a real device with iOS 16.0 Beta 7 i ran in following error 

error build: Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

I double checked the path, the framework file exists (sic). XCode says that everything is fine with the profiles and signing certificates...

Hints or suggestions would be great!

Kind regards
DGandalf

**Comment by jlipps** [comment]
this is not an issue with appium desktop. if you believe it's a bug please raise it at the xcuitest driver repo or the main appium repo.
