### ISSUE TITLE
feature request：choice install folder when install appium-desktop

### ISSUE THREAD

**Issue by itsgoodtobebad** [appium/appium-desktop#210]
Because i have no enough disk space in disk C, can i install appium-desktop to other disk?
Can some good guy add a new feature to select install folder during installation?

thanks a lot.

**Comment by dpgraham** [comment]
The install process is controlled by electron-builder (https://github.com/electron-userland/electron-builder)

I would look into how Windows does installations to see if there's a way to do it through the OS.
