### ISSUE TITLE
Does APPIUM not support Selenium4.x?

### ISSUE THREAD

**Issue by ClaudeJiang** [appium/appium-desktop#2101]
I wrote a json file  below:
{
  "capabilities": [
    {
      "deviceName": "emulator-5556",
      "version": "12",
      "maxInstances": 1,
      "platform": "ANDROID",
      "browserName": ""
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://127.0.0.1:4724/wd/hub",
    "host": "127.0.0.1",
    "port": 4724,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "127.0.0.1",
    "hubProtocol": "http"
  }
}

But I can't successfully register the node of Selenium grid4.4's hub.
The error is: An attempt to register with the grid was unsuccessful: Request failed with status code 404

**Comment by jlipps** [comment]
This is not an Appium Desktop issue. Please try with latest Appium CLI and report an issue at the main Appium repo if you encounter one in the latest version.
