### ISSUE TITLE
GPU process isn't usable

### ISSUE THREAD

**Issue by theyoz** [appium/appium-desktop#2103]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I run the linux app image I get

```
(node:48723) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[48723:0913/151800.578365:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Illegal instruction (core dumped)

```

## Environment

- I am running Appium Desktop version 1.22.3-4.
- I am on (pick one):
    - [ ] Linux
Linux g14 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by jlipps** [comment]
I would suggest not using this project and using the Appium CLI instead in conjunction with Appium Inspector. We don't have any insight into how the linux image is built.
