### ISSUE TITLE
@jlipps

### ISSUE THREAD

**Issue by dapshad** [appium/appium-desktop#2107]
@jlipps, hope you are good? Please can you help? I am facing this issue since 2 days now: Appium inspector not starting up and on my cmd line , adb devices, it shows me my list of device. Not sure why i keep getting this error.
![image](https://user-images.githubusercontent.com/109827129/190394929-75226b12-ef1c-46aa-a9f3-19c359518dda.png)
![image](https://user-images.githubusercontent.com/109827129/190395013-5aab35b5-20f4-4f74-8033-686e5d80c9e7.png)

![image](https://user-images.githubusercontent.com/109827129/190395078-abdcd7ba-9170-4b9c-9ba2-4bd9f7f3c5a5.png)

@jlipps , i removed my apk file from the list od my capabilities and it has worked but how do i then get to install the apk files again?

**Comment by KazuCocoa** [comment]
The error itself is the apk is not good for the emulator. It is more apk building stuff rather than Appium related.
https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk

**Comment by dapshad** [comment]
> The error itself is the apk is not good for the emulator. It is more apk building stuff rather than Appium related. https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk

So, what do you suggest? Do you have a link to where i can download the apk that will work with the Emulator?

**Comment by KazuCocoa** [comment]
You should build your test apk for the x86 architecture and set it for `appium:app`. I guess your app was built for arm, which works on real devices but not for emulators.
https://developer.android.com/ndk/guides/abis
