### ISSUE TITLE
The problem - Failed to create session

### ISSUE THREAD

**Issue by Ashutosh4291** [appium/appium-desktop#2109]
## Appium

![gi](https://user-images.githubusercontent.com/109640637/190939327-24274e4e-42a7-40e3-bfe3-5215a5bcee42.png)

- [ ] I 

## The problem - Failed to create session
Failed to create session.

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

## Environment
![gi](https://user-images.githubusercontent.com/109640637/190939239-8a8b141d-757a-460a-88d2-2cbdf3747551.png)

- I am running Appium Desktop version _<2.0.0-beta.44>_.
- I am on (pick one):
- 
    - [ ] Windows

**Comment by Ashutosh4291** [comment]
Pleasse help

**Comment by jlipps** [comment]
this is not appium desktop. if you want to raise an issue for the inspector, do so at the inspector repo after having read the readme.
