### ISSUE TITLE
Appium desktop inspector not correct for orientation

### ISSUE THREAD

**Issue by GeeChao** [appium/appium-desktop#211]
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Currently testing an app that is only supported in landscape view, the appium inspector is incorrect when viewing the app.

e.g. when it the app is opened and showing correctly on the simulator, in the inspector it is rotated clockwise once so the bottom of the app is on the left side. No matter how I try to rotate the app on the simulator, it is always incorrect on the Appium inspector

## Environment

- I am running Appium Desktop version 1.0.2-beta.2
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Can you provide screenshots and server logs?

**Comment by GeeChao** [comment]
Please see attached:

There doesn't seem to be anything in the appium server logs as nothing really happens. 
My Appium desktop desired capabilities:
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPad Air",
  "browserName": "",
  "app": "/Users/machan/WebstormProjects/myticketingtest/apps/myticketing_ui.app/"
}

It still locates the elements etc. although it's just a huge pain using the preview inspector as I can't actually click on any of the elements on the screen properly as it's all aligned completely incorrectly and not what's shown on the screen. 

[appiumserverlog.txt](https://github.com/appium/appium-desktop/files/1056587/appiumserverlog.txt)

![2017-06-07_0951](https://user-images.githubusercontent.com/11953307/26856631-3e1ee4ae-4b68-11e7-8f20-f85013797106.png)

**Comment by dpgraham** [comment]
Yeah, this looks like a bug in Desktop.

A couple questions
* Is it only correct when you're in landscape mode? 
* Is it in landscape mode when the session begins or did you change it to landscape mode?

**Comment by GeeChao** [comment]
Hi, thanks for the quick reply.

It-  is never correct in any mode, if I change the orientation, it is always incorrect in the Appium inspector.

- The session begins like how I showed in the screenshot: It is landscape in the IOS device and it shows correctly, however in the Appium inspector, it is portrait mode but rotated counter-clockwise 90 degrees as shown above.

**Comment by dpgraham** [comment]
So it's always the opposite orientation of what you expect?

**Comment by GeeChao** [comment]
Yes it's never the correct orientation, no matter how I change it on the Simulator then press Refresh on the Appium Inspector.

**Comment by dpgraham** [comment]
Can you provide Appium logs for this? I don't think it's an Appium Desktop issue but rather an issue with appium xcui or webdriveragent.

**Comment by GeeChao** [comment]
Is the appium server log not what you were looking for that I attached previously?

Or did you want the iOS Simulator system log.

**Comment by dpgraham** [comment]
Closing this as an Appium issue and not an Appium Desktop issue. Try with latest version.
