### ISSUE TITLE
Failed to create session. An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability

### ISSUE THREAD

**Issue by ctwillson** [appium/appium-desktop#2110]
## Appium or Appium Desktop?

Appium Desktop

## The problem

[UiAutomator2] The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\20262031\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 218f092a shell am force-stop com.xtc.i3launcher'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201 
[ADB] Running 'C:\Users\20262031\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 218f092a forward --remove tcp:8201'
[BaseDriver] Event 'newSessionStarted' logged at 1663763788530 (20:36:28 GMT+0800 (中国标准时间))
[W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability
[W3C]     at Object.errorAndThrow (C:\Users\20262031\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:94:35)
[W3C]     at UiAutomator2Server.startSession (C:\Users\20262031\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:236:15)
[W3C]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\20262031\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:416:5)
[W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\20262031\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:229:7)
[W3C]     at AppiumDriver.createSession (C:\Users\20262031\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\lib\appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 59449 ms - 1141
## Environment

- I am on (pick one):
    - [ ] Windows

**Comment by jlipps** [comment]
this is not an issue with appium desktop. please report at appium if you think this is a bug and include all relevant logs (e.g. logcat as the error indicates)
