### ISSUE TITLE
The latest appium-desktop v1.1.0-beta.1 uses the server 1.6.4 not 1.6.5 as expected 

### ISSUE THREAD

**Issue by livastar** [appium/appium-desktop#212]
## Appium Desktop version : v1.1.0-beta.1

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by poorvikamahesh** [comment]
Same here. I installed the v1.1.0-beta.1 version for Mac.
But it still points to appium server 1.6.4 

<img width="655" alt="screen shot 2017-06-09 at 7 53 51 pm" src="https://user-images.githubusercontent.com/10269471/26979715-667d4c9c-4d4d-11e7-8574-56f0f620c784.png">

**Comment by jlipps** [comment]
what could have happened here, dan? did we forget to `rm -rf` node_modules and reinstall before publishing?

**Comment by leolvicario** [comment]
Same here....

**Comment by poorvikamahesh** [comment]
@jlipps Any idea when this will be fixed??

**Comment by dpgraham** [comment]
New beta published. Problem resolved.

The issue was that when I had packaged the build it had an old version of Appium in node_modules.

**Comment by poorvikamahesh** [comment]
@dpgraham Thanks

**Comment by dpgraham** [comment]
No problem. Thanks you and @livastar for reporting the issue to me.
