### ISSUE TITLE
Alternative for WinAppDriver for Appium Desktop?

### ISSUE THREAD

**Issue by csa0911** [appium/appium-desktop#2121]
WinAppDriver hasnt been updated since last 2020. It seems they have stopped support: https://github.com/microsoft/WinAppDriver/issues/1550

Is there an alternative to WinAppDriver library that can connect to Appium for windows desktop apps (WPF) ?

Thank you

**Comment by jlipps** [comment]
the appium desktop repo is not the place to discuss winappdriver, as the two tools are unrelated. it seems you already have the thread on the winappdriver repo which is the appropriate place to ask this kind of question.

but to answer it here anyway: i have no idea.
