### ISSUE TITLE
Support version confirmation and error help

### ISSUE THREAD

**Issue by GHMOBILEMARCH** [appium/appium-desktop#2124]
Hello developers,

I would like to ask a question about the latest Android 11 version currently supported by appium.

Here are the errors I get when I run the script:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk'. Original error: java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by KazuCocoa** [comment]
https://stackoverflow.com/questions/60441090/apksignertool-issue-with-java-version

It is your installed Android tools and Java runtime version issue rather than Appium.

**Comment by GHMOBILEMARCH** [comment]
thanks bro；
