### ISSUE TITLE
UiAutomator exited unexpectedly with code 0, signal null in more than android version 10

### ISSUE THREAD

**Issue by divyansr** [appium/appium-desktop#2125]
## The problem

Getting error UiAutomator exited unexpectedly with code 0, signal null in more than android version 10. Moving state to stopped.
Earlier i was using my device which having android version 10, and there were no problem at all with appium desktop version v1.9.1.
But now i switched my android version to 11, with the same appium desktop version, here i couldn't able to launch the app itself .In appium server logs getting below error.

[error] [35m[UiAutomator][39m UiAutomator exited unexpectedly with code 0, signal null
[debug] [35m[UiAutomator][39m Moving to state 'stopped'.

## Environment

- I am running Appium Desktop version _v1.9.1_.
- I am on (pick one):
    - [ ] Mac
    - [ Y] Windows
    - [ ] Linux

Appium Desktop server logs are below.

[info] [35m[Appium][39m Welcome to Appium v1.9.1
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appPackage":"com.netflix.mediaclient","appActivity":"com.netflix.mediaclient.ui.launch.UIWebViewActivity","noReset":true,"newCommandTimeout":3600,"automationName":"Appium","udid":"dbdb8f3f","platformName":"Android","deviceName":"Redmi","version":"11 RKQ1.211001.001"}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appPackage":"com.netflix.mediaclient","appActivity":"com.netflix.mediaclient.ui.launch.UIWebViewActivity","noReset":true,"newCommandTimeout":3600,"automationName":"Appium","udid":"dbdb8f3f","platformName":"Android","deviceName":"Redmi","version":"11 RKQ1.211001.001"},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1665555503630 (11:48:23 GMT+0530 (India Standard Time))
[info] [35m[Appium][39m Creating new AndroidDriver (v4.1.1) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   appPackage: com.netflix.mediaclient
[info] [35m[Appium][39m   appActivity: com.netflix.mediaclient.ui.launch.UIWebViewActivity
[info] [35m[Appium][39m   noReset: true
[info] [35m[Appium][39m   newCommandTimeout: 3600
[info] [35m[Appium][39m   automationName: Appium
[info] [35m[Appium][39m   udid: dbdb8f3f
[info] [35m[Appium][39m   platformName: Android
[info] [35m[Appium][39m   deviceName: Redmi
[info] [35m[Appium][39m   version: 11 RKQ1.211001.001
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"appPackage":"com.netflix....
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: version.
[info] [35m[BaseDriver][39m Session created with session id: c53c79ff-5c88-4fe9-9f87-4540b0b0804a
[info] [35m[AndroidDriver][39m Java version is: 1.8.0_281
[info] [35m[ADB][39m Checking whether adb is present
[info] [35m[ADB][39m Found 1 'build-tools' folders under 'C:\Users\divyansr\AppData\Local\Android\Sdk' (newest first):
[info] [35m[ADB][39m     C:/Users/divyansr/AppData/Local/Android/Sdk/build-tools/30.0.3
[info] [35m[ADB][39m Using adb.exe from C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: dbdb8f3f
[debug] [35m[ADB][39m Setting device id to dbdb8f3f
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell getprop ro.build.version.sdk'
[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 30
[debug] [35m[ADB][39m Device API level: 30
[warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[AndroidDriver][39m App file was not listed, instead we're going to run com.netflix.mediaclient directly on the device
[debug] [35m[AndroidDriver][39m Checking whether package is present on the device
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell pm list packages com.netflix.mediaclient'
[info] [35m[AndroidDriver][39m Starting Android session
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f wait-for-device'
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell echo ping'
[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell pm list packages io.appium.settings'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell dumpsys package io.appium.settings'
[info] [35m[ADB][39m Checking whether aapt is present
[info] [35m[ADB][39m Using aapt.exe from C:\Users\divyansr\AppData\Local\Android\Sdk\build-tools\30.0.3\aapt.exe
[debug] [35m[ADB][39m The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell ps'
[debug] [35m[ADB][39m Device API level: 30
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [35m[ADB][39m Device API level: 30
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell appops set io.appium.settings android\:mock_location allow'
[warn] [35m[AndroidDriver][39m setDeviceLanguageCountry requires language or country.
[warn] [35m[AndroidDriver][39m Got language: 'undefined' and country: 'undefined'
[debug] [35m[Logcat][39m Starting logcat capture
[debug] [35m[AndroidDriver][39m Pushing unlock helper app to device...
[debug] [35m[ADB][39m Getting install status for io.appium.unlock
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell pm list packages io.appium.unlock'
[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.unlock'
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell dumpsys package io.appium.unlock'
[debug] [35m[ADB][39m The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 11
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell wm size'
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell getprop ro.product.model'
[debug] [35m[ADB][39m Current device property 'ro.product.model': 2201117TI
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell getprop ro.product.manufacturer'
[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Xiaomi
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[AndroidDriver][39m No app capability. Assuming it is already on the device
[debug] [35m[AndroidBootstrap][39m Watching for bootstrap disconnect
[debug] [35m[ADB][39m Forwarding system: 4724 to device: 4724
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f forward tcp\:4724 tcp\:4724'
[debug] [35m[UiAutomator][39m Starting UiAutomator
[debug] [35m[UiAutomator][39m Moving to state 'starting'
[debug] [35m[UiAutomator][39m Parsing uiautomator jar
[debug] [35m[UiAutomator][39m Found jar name: 'AppiumBootstrap.jar'
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f push C\:\\Users\\divyansr\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[debug] [35m[ADB][39m Attempting to kill all uiautomator processes
[debug] [35m[ADB][39m Getting all processes with uiautomator
[debug] [35m[ADB][39m Running 'C:\Users\divyansr\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s dbdb8f3f shell ps'
[info] [35m[ADB][39m No uiautomator process found to kill, continuing...
[debug] [35m[UiAutomator][39m Starting UIAutomator
[debug] [35m[ADB][39m Creating ADB subprocess with args: ["-P",5037,"-s","dbdb8f3f","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.netflix.mediaclient","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
							Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.google.android.youtube","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[error] [35m[UiAutomator][39m UiAutomator exited unexpectedly with code 0, signal null
[debug] [35m[UiAutomator][39m Moving to state 'stopped'

Is this the issue related to appium version? Any help would be much appreciated.

**Comment by KazuCocoa** [comment]
Could be. We recommend UIA2 driver for Android 6+, https://github.com/appium/appium-uiautomator2-driver/#requirements , so potentially the old version does not work with newer Android OS versions

**Comment by divyansr** [comment]
Thanks you very much KazuCocoa, issue got resolved.
