### ISSUE TITLE
Appium inspector throws error on starting session - xcodebuild failed with code 65

### ISSUE THREAD

**Issue by Nima-QA** [appium/appium-desktop#2131]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Getting below error on starting session on Appium inspector:
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message:

Appium Server GUI - latest
Appium Inspector version: App Version: 2022.11.1
Mac: Ventura 13.0.1
Xcode: Version 14.1 (14B47b)
Simulator: iOS 16.1

## Environment

- I am running Appium Desktop version _Appium Server GUI_.
- I am on (pick one):
    - [ X] Mac
    - [ ] Windows
    - [ ] Linux
![Screenshot at Nov 30 10-30-50](https://user-images.githubusercontent.com/119481802/204734359-ca34d988-1f8c-416c-871b-d35dbe8a7ff0.png)

**Comment by jlipps** [comment]
Appium Desktop is not supported. The inspector has moved to a different repo. And the error you are seeing has nothing to do with the inspector. Please search the main appium repo for issues relating to this error message. Likely you need to upgrade appium and the xcuitest driver to the latest versions.
