### ISSUE TITLE
Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation

### ISSUE THREAD

**Issue by bellgrllsajian** [appium/appium-desktop#2136]
## Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

WebDriverAgent runs successfully, but the inspector fails to create a session

## Environment

- I am running Appium Desktop version _<1.22.3-4>_.
- I am on (pick one):
    - [x] MacOS 12.6.1 (21G217)
    - [x] node v14.19.3
    - [x] npm 6.14.17
    - [x] Xcode 14.1

## It looks like the necessary plugins are already installed

apeman@apemandeMacBook-Pro WebDriverAgent % appium-doctor --ios
WARN AppiumDoctor [Deprecated] Please use appium-doctor installed with "npm install @appium/doctor --location=global"
info AppiumDoctor Appium Doctor v.1.16.2
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 14.19.3
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.38.0
info AppiumDoctor  ✔ HOME is set to: /Users/apeman
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
info AppiumDoctor  ✔ ffmpeg is installed at: /usr/local/bin/ffmpeg. ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
info AppiumDoctor  ✔ mjpeg-consumer is installed at: /usr/local/lib. Installed version is: 2.0.0
info AppiumDoctor  ✔ set-simulator-location is installed
info AppiumDoctor  ✔ idb and idb_companion are installed
info AppiumDoctor  ✔ applesimutils is installed at: /usr/local/bin/applesimutils. Installed versions are: applesimutils 0.9.8
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.12.1
info AppiumDoctor ### Diagnostic for optional dependencies completed, one fix possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: http://appium.io/docs/en/writing-running-appium/image-comparison/
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

## I have tried installing opencv4nodejs with command：npm install --save opencv4nodejs，
But the following error occurred, so I gave up the installation

[ 80%] Linking CXX shared library ../../lib/libopencv_dnn.dylib
[ 80%] Built target opencv_dnn
make: *** [all] Error 2
ERR! child process exited with code 2 (for more info, set '--loglevel silly') 
npm WARN enoent ENOENT: no such file or directory, open '/Users/apeman/package.json'
npm WARN apeman No description
npm WARN apeman No repository field.
npm WARN apeman No README data
npm WARN apeman No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv-build@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apeman/.npm/_logs/2022-12-14T09_28_38_694Z-debug.log

## I successfully ran the WebDriverAgent and accessed it in the browser
ServerURLHere->http://169.254.87.212:8100<-ServerURLHere
2022-12-14 14:41:13.956425+0800 WebDriverAgentRunner-Runner[2510:748208] Using singleton test manager

##  Desired Capabilities

{
  "platformName": "iOS",
  "appium:platformVersion": "16.1",
  "appium:app": "com.nooie.home",
  "appium:deviceName": "iPhone",
  "appium:udid": "49953ce7b15043dbb1d9e43ec6e5caa61646c20e",
  "appium:automationName": "XCUITest"
}

## when I start session,I got this error
Error
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation

**Comment by jlipps** [comment]
sorry this project is no longer maintained. please use the latest version of the appium 2 beta cli and create an issue at that repo if the problem persists.

**Comment by bellgrllsajian** [comment]
@jlipps thank you，I will try to use  appium 2 beta cli.
