### ISSUE TITLE
Appium Inspector on a iPhone simulator with iOS 16.2 does not work with Appium Server GUI; works with the command line version of Appium server 

### ISSUE THREAD

**Issue by jonbeacherdomuso** [appium/appium-desktop#2139]
## Appium or Appium Desktop?

Appium Desktop. Specifically, Appium Desktop Server GUI.

"Appium Desktop is an app for Mac, Windows, and Linux which gives you the power of the [Appium](http://appium.io/) automation server in a beautiful and flexible UI. It is basically a graphical interface for the Appium Server."

## The problem

Appium server GUI does not work with Appium inspector on an iOS version 16.2 simulator. I get a build error 65 error, even after I follow all of the correct provisioning steps here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#basic-automatic-configuration

Steps to Reproduce Error:
1. `npm i appium-webdriveragent`
2. Load Appium Server GUI
3. Open Appium Inspector
4. Enter correct device capabilities for IOS
5. app text appPath/appName.app, deviceName text iPhone 14, automationName text XCUITest, platformName text iOS
6. Start Appium Inspector session 

Expect:
7. Appium Inspector to work without error

Actual:
7. Build 65 error code:

"Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message"

Work around:

1. Close and exit Appium server GUI
2.  Install the console version of Appium server via the commands:
3. `npm install --location=global appium@next`
4. `appium driver install xcuitest`
5.   Then, I start Appium server via the terminal / console:
6.  `appium server --base-path=/wd/hub`
8. Open Appium Inspector
9. Enter correct device capabilities for iOS
10. app text appPath/appName.app, deviceName text iPhone 14, automationName text XCUITest, platformName text iOS
11. Start an Appium Inspector session 
12. Appium Inspector works without error

I had to exit Appium server GUI and run via Appium server via console / terminal to get it to work. After executing steps in work around #1-10, then closing Appium server via console, then performing steps in Expect #1-6; I still get the code 65 build error. Thus, it is an Appium Desktop server GUI issue, and not an Appium Inspector, nor a signing issue with WebDriverAgent that is my fault https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#basic-automatic-configuration

## Environment

- I am running Appium Desktop version: v1.22.3-4
- This is most current version as of Jan 9, 2023. I know this by opening Appium Server GUI, clicking "check for updates" and it says "No update is available" , "Appium Desktop is up-to-date"

- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

Mac OS 12.6.1
iOS 16.2 simulator

**Comment by KazuCocoa** [comment]
We've been guiding users to use https://github.com/appium/appium-inspector and appium via `npm` instead 
https://github.com/appium/appium-desktop#please-use-appium-inspector-and-appium-to-inspect-elements-for-appium-20

**Comment by jonbeacherdomuso** [comment]
In my opinion, updating the readme isn't a valid fix, nor completed. Appium Server GUI should include an updated version to throw a better error code other than a generic 65 error if users try to replicate this issue

**Comment by KazuCocoa** [comment]
I understand the opinion, although we've also been guided to use the inspector for Appium 2.0 for a long. (README as well. I've moved to more top today though.)

The error code comes from xcodebuild, so it would be helpful to report it to Apple as well since based on our past experience, one error code does not mean one meaning.

**Comment by jlipps** [comment]
@jonbeacherdomuso the appium server GUI is no longer supported or maintained. we've decided not to upgrade it to be compatible with appium 2. if someone else wants to take on that task, they are free to do so.

**Comment by jonbeacherdomuso** [comment]
Thank you @jlipps for updating the readme today to reflect that Appium Server GUI is no longer maintained. https://github.com/appium/appium-desktop/commit/1dcf3e981e2f0a81756ddf777304aa47b89c695d
