### ISSUE TITLE
  Appium-Server-GUI-linux-1.22.3-4.AppImage is missing libfuse2 

### ISSUE THREAD

**Issue by sadatmirza0** [appium/appium-desktop#2141]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

./Appium-Server-GUI-linux-1.22.3-4.AppImage does not work by default . Error states Fuse missing.
Works on installing libfuse2

## Environment

 - 1.22.3.-4.AppImage

 - Linux ( Ubuntu 22.04.1 LTS)

**Comment by jlipps** [comment]
this project is no longer supported, see the readme
