### ISSUE TITLE
System notifications(locator) are not recognized by inspector

### ISSUE THREAD

**Issue by suvidhapra** [appium/appium-desktop#215]
Appium or Appium Desktop both

I want to click on Allow OR Don't Allow but it seems system notifications are recognized by appium. I am trying to put as much as logs in this issue, please let me know in case of more details required

My issue is occurring when I write the java code and try the appium with java as well. Please fine below my capabilities and test.

  public void setUp() throws Exception{
     // set up appium
        File appDir = new File(System.getProperty("user.dir"), "../../TestPath");
        File app = new File(appDir,"Test.app");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", "iPad Air 2");
        capabilities.setCapability("platformVersion", "10.3");
        capabilities.setCapability("orientation", "LANDSCAPE");
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("app", app.getAbsolutePath());
        driver = new IOSDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    }

    @Test
    public void testLogin() throws Exception{
        Thread.sleep(5000);
        driver.switchTo().alert().accept();
        Thread.sleep(5000);
        driver.findElement(By.name("//XCUIElementTypeButton[@name=\\\"Allow\\\"]")).click();
        driver.findElement(By.xpath("//XCUIElementTypeTextField[@name=\\\"user_name_field\\\"]")).sendKeys("testing");
        driver.findElement(By.xpath("//XCUIElementTypeSecureTextField[@name=\\\"password_field\\\"]")).sendKeys("abcd");
        driver.findElement(By.xpath("//XCUIElementTypeButton[@name=\\\"native_login_button\\\"]")).click();
    }

![screen shot 2017-06-09 at 12 20 00 pm](https://user-images.githubusercontent.com/29312893/26991156-355a61ca-4d0e-11e7-818a-819a55e76858.png)

**Logs from terminal for above java code:**
[XCUITest] Merging WDA caps over Appium caps for session detail response
[debug] [MJSONWP] Responding to client with driver.getSession() result: {"udid":"57B2EB2A-698D-43B3-B52D-E81B0E9D0ACE","app":"Testpath/AppiumTest/../../MobileAutomationPOC/Testing.app","orientation":"LANDSCAPE","platformVersion":"10.3","automationName":"XCUITest","platformName":"iOS","deviceName":"iPad Air 2","device":"ipad","browserName":" ","sdkVersion":"10.3","CFBundleIdentifier":"local.pid.18786"}
[HTTP] <-- GET /wd/hub/session/0223bf81-1172-4fa6-9d98-2c95302f8c30 200 109 ms - 436 
[HTTP] --> POST /wd/hub/session/0223bf81-1172-4fa6-9d98-2c95302f8c30/element {"using":"name","value":"//XCUIElementTypeButton[@name=\\\"Allow\\\"]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["name","//XCUIElementTypeButton[@name=\\\"Allow\\\"]","0223bf81-1172-4fa6-9d98-2c95302f8c30"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/32ED55A9-4CB0-49AA-8616-F6E377725964/element] with body: {"using":"name","value":"//XCUIElementTypeButton[@name=\\\"Allow\\\"]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"name","value":"//XCUIElementTypeButton[@name=\\\"Allow\\\"]","description":"unable to find an element"},"sessionId":"32ED55A9-4CB0-49AA-8616-F6E377725964","status":7}
[HTTP] <-- POST /wd/hub/session/0223bf81-1172-4fa6-9d98-2c95302f8c30/element 500 131 ms - 164 

**Appium Desktop APP:**
I am able to find the element via desktop app but when I am trying to tap the element, it doesn't throw any exception and don't do anything on notification window.

**Below are the logs from Appium inspector Desktop app:**
POST /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/element {"using":"xpath","value":"//XCUIElementTypeButton[@name=\"Allow\"]"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeButton[@name=\"Allow\"]","7f839e7f-74f6-4a25-b744-aec97d0ca338"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/69DDD920-FDDB-4C30-AA82-AF7BCE22402E/element] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name=\"Allow\"]"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"04C56BCB-9B67-4288-9354-17D648FA290B","type":"XCUIElementTypeButton","label":"Allow"},"sessionId":"69DDD920-FDDB-4C30-AA82-AF7BCE22402E","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"04C56BCB-9B67-4288-9354-17D648FA290B","type":"XCUIElementTypeButton","label":"Allow"}
[HTTP] <-- POST /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/element 200 638 ms - 169 
[HTTP] --> POST /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/element/04C56BCB-9B67-4288-9354-17D648FA290B/click {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [POST /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/element/04C56BCB-9B67-4288-9354-17D648FA290B/click] to [POST http://localhost:8100/session/69DDD920-FDDB-4C30-AA82-AF7BCE22402E/element/04C56BCB-9B67-4288-9354-17D648FA290B/click] with body: {}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"04C56BCB-9B67-4288-9354-17D648FA290B","value":"","sessionId":"69DDD920-FDDB-4C30-AA82-AF7BCE22402E"}
[JSONWP Proxy] Replacing sessionId 69DDD920-FDDB-4C30-AA82-AF7BCE22402E with 7f839e7f-74f6-4a25-b744-aec97d0ca338
[HTTP] <-- POST /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/element/04C56BCB-9B67-4288-9354-17D648FA290B/click 200 640 ms - 118 
[HTTP] --> GET /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["7f839e7f-74f6-4a25-b744-aec97d0ca338"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/69DDD920-FDDB-4C30-AA82-AF7BCE22402E/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n    \\n  <\\/XCUIElementTypeWindow>\\n  \\n    
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n    \n  \n  \n    \n  \n  \n    
[HTTP] <-- GET /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/source 200 147 ms - 15102 
[HTTP] --> GET /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["7f839e7f-74f6-4a25-b744-aec97d0ca338"]
[XCUITest] Executing command 'getScreenshot'
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABgAAAAgACAYAAADg0fg2AAAEDWlDQ1BJQ0MgUHJvZmlsZQAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8u...
[HTTP] <-- GET /wd/hub/session/7f839e7f-74f6-4a25-b744-aec97d0ca338/screenshot 200 558 ms - 329162 

This is with system alerts like notification, contacts etc...

- I am running Appium Desktop version _Version 1.1.0-beta.1 (1.1.0-beta.1)_.
- I am on (pick one):
    - [ ] Mac - macOS Sierra Version 10.12.5

**Comment by dpgraham** [comment]
@jlipps Is this a known issue with XCUITest that we can't handle system notifications?

**Comment by jlipps** [comment]
If they don't show up in the source then I guess we can't handle them. Though alerts in general are able to be automated. Either way this doesn't seem like an appium desktop issue.

**Comment by suvidhapra** [comment]
I am able to locate them in source code but when I tab on the element it does nothing. For me it looks like overall appium and appium desktop both are not able to tap/click on the element. Can you please take a look on my logs to guide me, how will I proceed. Thanks!

**Comment by jlipps** [comment]
@suvidhapra you need to re-raise this issue at the Appium repository (https://github.com/appium/appium/issues), since this issue tracker is for issues with the Appium Desktop UI only. When you do raise the issue there, make sure you include a dump of the source xml at that point.
