### ISSUE TITLE
Unsupported MIME type when creating session causes crash

### ISSUE THREAD

**Issue by msmirzazadeh** [appium/appium-desktop#216]
## The problem

getting error from appium when create new ssesion : 

[MJSONWP] Encountered internal error running command: Error: Unsupported MIME type: 
at Jimp.throwError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:82:43)
at Jimp.parseBitmap (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:307:31)
at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:200:29
at FSReqWrap.readFileAfterClose as oncomplete

## Environment

- I am running Appium Desktop version 1.1.0-beta.1
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
Does this break your session altogether or are you just not able to see the screenshot?

I know that we've had issues before where we can't take screenshots.

**Comment by msmirzazadeh** [comment]
it breaks my session.

**Comment by dpgraham** [comment]
Okay, so if you press the 'back' button does it go to the previous page or is totally unrecoverable and you have to exit the session altogether.

I just want to know so these details so we can determine how high priority a fix is.

**Comment by msmirzazadeh** [comment]
its working when i pressed back button

**Comment by dpgraham** [comment]
Can you provide me the Appium logs and perhaps a screenshot of what you see? I want to attempt to re-create the issue so we can put in a fix.

**Comment by msmirzazadeh** [comment]
The server is running
Start New SessionStop Server
[Appium] Welcome to Appium v1.6.4
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 8 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appActivity":"com.roundtableapps.douugh.view.activity.SplashActivity","appPackage":"com.roundtableapps.douugh.dev","deviceName":"5.1 - 2","platformName":"Android","platformVersion":"5.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.roundtableapps.douugh.view.activity.SplashActivity","appPackage":"com.roundtableapps.douugh.dev","deviceName":"5.1 - 2","platformName":"Android","platformVersion":"5.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1497949551416 (13:35:51 GMT+0430 (+0430))
[Appium] Creating new AndroidDriver (v1.17.1) session
[Appium] Capabilities:
[Appium]   appActivity: 'com.roundtableapps.douugh.view.activity.SplashActivity'
[Appium]   appPackage: 'com.roundtableapps.douugh.dev'
[Appium]   deviceName: '5.1 - 2'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '5.1'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[AndroidDriver] AndroidDriver version: 1.17.1
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/administrator/Documents/android-sdk-macosx/platform-tools/adb
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[AndroidDriver] Looking for a device with Android '5.1'
[ADB] Setting device id to 192.168.57.101:5555
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","getprop","ro.build.version.release"]
[AndroidDriver] Using device: 192.168.57.101:5555
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/administrator/Documents/android-sdk-macosx/platform-tools/adb
[ADB] Setting device id to 192.168.57.101:5555
[AndroidDriver] App file was not listed, instead we're going to run com.roundtableapps.douugh.dev directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","pm","list","packages","com.roundtableapps.douugh.dev"]
[AndroidDriver] Starting Android session
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","echo","ping"]
[Logcat] Starting logcat capture
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","pm","list","packages","io.appium.settings"]
[ADB] App is installed
[ADB] Getting package info for io.appium.settings
[ADB] Getting connected devices...
[ADB] Checking whether aapt is present
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","dumpsys","package","io.appium.settings"]
[ADB] Using aapt from /Users/administrator/Documents/android-sdk-macosx/build-tools/22.0.1/aapt
[ADB] Cannot read version codes of /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk and/or io.appium.settings. Assuming correct app version is already installed
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","getprop","ro.build.version.sdk"]
[ADB] Device API level: 22
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","dumpsys","package","io.appium.settings"]
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","install","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Device API level: 22
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","settings","put","secure","mock_location","1"]
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","getprop","ro.build.version.release"]
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","wm","size"]
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","getprop","ro.product.model"]
[ADB] Current device property 'ro.product.model': 5.1 - 2
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","getprop","ro.product.manufacturer"]
[ADB] Current device property 'ro.product.manufacturer': Genymotion
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[AndroidDriver] Running fast reset (stop and clear)
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","am","force-stop","com.roundtableapps.douugh.dev"]
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","pm","clear","com.roundtableapps.douugh.dev"]
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","forward","tcp:4724","tcp:4724"]
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","push","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","192.168.57.101:5555","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.roundtableapps.douugh.dev","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Device API level: 22
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","am","start","-W","-n","com.roundtableapps.douugh.dev/com.roundtableapps.douugh.view.activity.SplashActivity","-S"]
[Appium] New AndroidDriver session created successfully, session 35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1497949557153 (13:35:57 GMT+0430 (+0430))
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appActivity":"com.roundtableapps.douugh.view.activity.SplashActivity","appPackage":"com.roundtableapps.douugh.dev","deviceName":"5.1 - 2","platformName":"Android","platformVersion":"5.1","newCommandTimeout":0,"connectHardwareKeyboard":true},"appActivity":"com.roundtableapps.douugh.view.activity.SplashActivity","appPackage":"com.roundtableapps.douugh.dev","deviceName":"192.168.57.101:5555","platformName":"Android","platformVersion":"5.1","newCommandTimeout":0,"connectHardwareKeyboard":true,"deviceUDID":"192.168.57.101:5555","deviceScreenSize":"800x1280","deviceModel":"5.1 - 2","deviceManufacturer":"Genymotion"}
[HTTP] <-- POST /wd/hub/session 200 5745 ms - 896 
[HTTP] --> POST /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/context {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d"]
[AndroidDriver] Getting a list of available webviews
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","cat","/proc/net/unix"]
[AndroidDriver] Found webviews: []
[AndroidDriver] Available contexts: ["NATIVE_APP"]
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/context 200 48 ms - 76 
[HTTP] --> GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[AndroidBootstrap] [UIAUTO STDOUT] [APPIUM-UIAUTO] [debug] Returning result: {"status":0,"value":"
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] Stream still not complete, waiting
[AndroidBootstrap] [UIAUTO STDOUT] \"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,50][800,1280]\" resource-id=\"android:id\/content\" instance=\"2\"><\/android.widget.RelativeLayout><\/android.widget.FrameLayout><\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/hierarchy>"}[/APPIUM-UIAUTO]
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getPageSource() result: "
[HTTP] <-- GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/source 200 134 ms - 4566 
[HTTP] --> GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d"]
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","pull","/data/local/tmp/screenshot.png","/var/folders/ch/661k5_5s1gvc9chdh6vm0ns80000gn/T/appium117520-1873-2wfkfg.t1sf25u3di.png"]
[MJSONWP] Encountered internal error running command: Error: Unsupported MIME type: 
    at Jimp.throwError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:82:43)
    at Jimp.parseBitmap (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:307:31)
    at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:200:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
[HTTP] <-- GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/screenshot 500 112 ms - 194 
[HTTP] --> GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[AndroidBootstrap] [UIAUTO STDOUT] [APPIUM-UIAUTO] [debug] Returning result: {"status":0,"value":"
[AndroidBootstrap] [UIAUTO STDOUT] \"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,50][800,1280]\" resource-id=\"android:id\/content\" instance=\"2\">
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] Stream still not complete, waiting
[AndroidBootstrap] [UIAUTO STDOUT] ed=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,1184][400,1280]\" resource-id=\"com.roundtableapps.douugh.dev:id\/btn_activity_welcome_login\" instance=\"0\"\/><\/android.widget.LinearLayout><\/android.widget.RelativeLayout><\/android.widget.FrameLayout><\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/hierarchy>"}[/APPIUM-UIAUTO]
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getPageSource() result: "
[HTTP] <-- GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/source 200 13 ms - 5887 
[HTTP] --> GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d"]
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[ADB] Running '/Users/administrator/Documents/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","192.168.57.101:5555","pull","/data/local/tmp/screenshot.png","/var/folders/ch/661k5_5s1gvc9chdh6vm0ns80000gn/T/appium117520-1873-1d4qbaa.5x248fflxr.png"]
[MJSONWP] Encountered internal error running command: Error: Unsupported MIME type: 
    at Jimp.throwError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:82:43)
    at Jimp.parseBitmap (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:307:31)
    at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:200:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
[HTTP] <-- GET /wd/hub/session/35d0a937-f3c4-42f1-a8b6-8d65ff9bc06d/screenshot 500 70 ms - 194 
<img width="624" alt="screen shot 2017-06-20 at 1 36 16 pm" src="https://user-images.githubusercontent.com/26924125/27325433-ad640218-55bd-11e7-9933-3001a1bb6065.png">

**Comment by dpgraham** [comment]
Thanks for this. I don't know that we'll be able to fix the screenshot failure itself but we definitely will be able to make a fix so that it doesn't break your session. It will just show a broken image link in place of where the screenshot should be.
