### ISSUE TITLE
The appium-desktop inspector is working hard on the latest release with v.1.6.5

### ISSUE THREAD

**Issue by livastar** [appium/appium-desktop#221]
## The problem

I've tried to inspect elements in the iOS app, but it's working so slow, in comparison with the previous version.

## Environment

- I am running Appium Desktop version _v.1.6.5_ on Mac

**Comment by jlipps** [comment]
Did you want to report an issue? I don't see anything here except for our issue template.

**Comment by livastar** [comment]
Thanks

**Comment by dpgraham** [comment]
Closing as duplicate. There's another issue that covers this and this should be resolved in the next version.
