### ISSUE TITLE
I can not detect elements in some android activities with Appium

### ISSUE THREAD

**Issue by msmirzazadeh** [appium/appium-desktop#222]
## Appium Desktop

When I want to detect xpath of elements from one of app activities by Appium session the refresh btn is not finishing it's working, Even when I insert elements id's of that page in my java code still appium could not find those elements and do actions by them.
I think this scenario will happen on those activities that developers have call API on them.
am I right?

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
A couple questions
* Are the elements visible in the screenshot?
* Are these native elements or webview elements?

**Comment by msmirzazadeh** [comment]
Screenshot of this page is not appear in session any time, Even after log time from opening it,

**Comment by dpgraham** [comment]
Is this a native app or webview app?

**Comment by msmirzazadeh** [comment]
native

**Comment by dpgraham** [comment]
Can you provide logs and perhaps screenshots to demonstrate the issue to me?
