### ISSUE TITLE
Error message similar to tool tip is not getting recognized

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-desktop#227]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1. Refer to attached screen shot of wordpress sign up page
2. There error message which is similar to tool top dialog doesn't get recognized nor the info icon

## Environment

- I am running Appium Desktop version _<1.1.0-beta.2>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

<img width="1437" alt="screen shot 2017-06-27 at 5 05 26 pm" src="https://user-images.githubusercontent.com/308490/27594850-3e585c68-5b5b-11e7-9320-c7d47afc33c1.png">

**Comment by dpgraham** [comment]
What are the contents of the children of the RelativeLayout?

**Comment by jlipps** [comment]
@vikramvi if it's not recognized by appium then it's not recognized by uiautomator, and there's nothing we can do about that. many custom controls do not have accessibility support and are un-automatable. this is something to bring up with google or your app developer.

**Comment by vikramvi** [comment]
@dpgraham children of RelativeLayot doesn't have anything related to this pop-up.

@jlipps thanks for clarification.
