### ISSUE TITLE
Back, Refresh, Screenshot, Cancel buttons cannot be clicked 

### ISSUE THREAD

**Issue by jashsu** [appium/appium-desktop#228]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In a Ubuntu Desktop 16.04.2 vm, the Back, Refresh, Screenshot, and Cancel buttons cannot be clicked in the appium-desktop GUI. The click is interpreted as a window dragging action.

![img_0452](https://user-images.githubusercontent.com/1680930/27614875-337b967c-5b59-11e7-89f0-363cc5999ed4.JPG)

## Environment

- I am running Appium Desktop version 1.1.0-beta.3.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [X] Linux

**Comment by KaiFTest** [comment]
I have the same issues on Windows 10. The buttons on the inspector cannot be clicked. There isn't even a button to close the window. It is also no longer rezisable. Can it be that it is only working in iOS?
![appium v1 1 0-beta 3 inspector](https://user-images.githubusercontent.com/29565535/27622627-8e874eba-5bd8-11e7-8caf-a98f03a2e042.jpg)

**Comment by DavidDelgado1983** [comment]
I have the same issue.

Windows 10. Working with Android.

**Comment by dpgraham** [comment]
We've reproduced this error.

We'll be pushing out a new version with a patch for this.
