### ISSUE TITLE
Use better locator strategies for recorder (not just XPath)

### ISSUE THREAD

**Issue by jashsu** [appium/appium-desktop#231]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Recorder always uses find_element_by_xpath when there are obviously more efficient and less brittle ways to find the element, including find_element_by_id. In a basic example, my app's login screen had only a single element with resource-id ```login_button```. When I used the recorder and clicked on this button, the following code was generated:

```
el4 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.Button")
el4.click()
```

The current behavior of the record functionality assumes that tap and sendkeys events will be sent to uniquely locatable elements, so an easy enhancement for readability, robustness, and portability is to check if the resource_id is unique in the entire hierarchy and if so, use find_element_by_id instead:

```
>>> el = driver.find_element_by_id('login_button')
>>> el.click()
```

## Environment

- I am running Appium Desktop version 1.1.0-beta.4.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [X] Linux

**Comment by jlipps** [comment]
Yes, we will implement this. It's currently just marked as a `TODO` in the code.

**Comment by arcadius** [comment]
I am new to Appium Desktop.
Currently, I keep changing the recorded code to use ID instead.
So, having this fixed will be very welcome.

Thanks.

**Comment by dpgraham** [comment]
This will be in the next release.
