### ISSUE TITLE
Appium v1.1.0-beta

### ISSUE THREAD

**Issue by nunomir** [appium/appium-desktop#232]
Hey guys. I'm getting an issue with the last appium betas version's: the tool does not detect any automation id or text in the screen at all. With old versions everything works. Someone know what may be happening? (it's a known issue?)

Environment: Windows 10 testing an Android app developed in Xamarin Forms. Tested with Appium v1.1.0-beta1/2/3/4.

Thanks

**Comment by jlipps** [comment]
Is this issue also present with Appium 1.6.5?

**Comment by jlipps** [comment]
@nunomir it's important to try to start a session and find elements with the CLI version of appium. if the issue is present there as well, we know it's an appium issue and not an appium desktop issue. that way we can try to reproduce.
