### ISSUE TITLE
Properties view isn't scrollable

### ISSUE THREAD

**Issue by rosolko** [appium/appium-desktop#236]
## Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unable to access to element properties because property view isn't scrollable.

## Environment

- I am running Appium Desktop version _1.1.0-beta.4_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

## View
<img width="397" alt="screen shot 2017-06-30 at 11 55 33" src="https://user-images.githubusercontent.com/11458319/27728730-a678f5d2-5d8b-11e7-9087-38e56ad3e4dc.png">

**Comment by MithunKudupu** [comment]
A much needed feature for this awesome Appium inspector. Otherwise its great..

**Comment by jlipps** [comment]
Yes, I reproduced this. It might be a regression actually. We'll fix it.
