### ISSUE TITLE
Add ability to check locator 

### ISSUE THREAD

**Issue by rosolko** [appium/appium-desktop#237]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Can you please add ability to check locator in inspector while navigation through app source?_
_For example, I create manually xpath to element and I want to check if I able to find this element with my locator from inspector_

## Environment

- I am running Appium Desktop version _1.1.0-beta.4_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
https://github.com/appium/appium-desktop/issues/202
