### ISSUE TITLE
Appium v1.1.0-.4beta always install app, although I don't add app path to server capabilities

### ISSUE THREAD

**Issue by Bamivani** [appium/appium-desktop#241]
## Appium or Appium Desktop?

Appium Desktop

## The problem

Appium v1.1.0-.4beta always install app

## Environment

- I am running Appium Desktop version v1.1.0-.4beta 
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Can you provide more details.

**Comment by Bamivani** [comment]
Hi dpgraham,
On Appium desktop version 1.4.16.1, I don't check Application Path in Android settings, Appium will open app. (When I log in my app, appium always open home page)

On  Appium v1.1.0-.4beta, I don't add app path to server capabilities, Appium always open Sign up page, it 's the same install new app

**Comment by dpgraham** [comment]
Can you provide screenshots? I still don't think I understand the problem.

**Comment by Bamivani** [comment]
![new](https://user-images.githubusercontent.com/26729836/29347961-5816c6ee-827a-11e7-8c9d-0f3751b5eb93.png)
Hi dpgraham,

Pls get screenshot to see more detail.

When I call open app, but new version always call install new app.

![old](https://user-images.githubusercontent.com/26729836/29347956-51dd9488-827a-11e7-9c0b-2f3d199e1bbe.png)

**Comment by jlipps** [comment]
When you use the latest version of Appium from the command line (not Appium desktop), with the same capabilities, do you see the same behavior?

**Comment by Bamivani** [comment]
Hi jlipps,
The same behavior when I use the latest version of Appium from the command line, with the same capabilities.

Do you have any suggestion for me ?

Thanks

**Comment by jlipps** [comment]
The fact you're experiencing the same behavior means this is not an Appium Desktop issue. I would open an issue at the main Appium repository instead.

**Comment by Bamivani** [comment]
Hi jlipps,
Could you give me issue id at the main Appium repository ?
Thanks,

**Comment by jlipps** [comment]
@Bamivani you need to create a new issue yourself
