### ISSUE TITLE
Add 'proxy' option

### ISSUE THREAD

**Issue by realksullivan** [appium/appium-desktop#242]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When trying to launch a sauce labs session using appium desktop I get Error ENOTFOUND. I believe this may have something to do with being behind my company's firewall. I don't get this issue when I not behind the company Firewall.  Is there a proxy setting in appium desktop that needs to be set? If so how do I set it? 

## Environment

- I am running Appium Desktop version 1.1.0-beta4.
- I am on (pick one):
    - [X] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
@realksullivan are you able to run scripts against sauce labs outside of Appium Desktop?

**Comment by realksullivan** [comment]
yes I able to run scripts with Appium no issues.

**Comment by dpgraham** [comment]
@realksullivan When you run tests from command line, do you have to use any proxy settings?

**Comment by Chakaravarthy** [comment]
@dpgraham I am from @realksullivan Team. Yes we are using the proxcy setting while running from command line ( Sample: --proxy-anyauth --proxy proxy.AAA.BBBB.org:8080)

**Comment by dpgraham** [comment]
We'll need to look into this some more. Proxying obviously works differently on Desktop than it does on command line. It's probably something we need to document.

In the meantime, you can actually use the command line server and still use the Appium inspector.

**Comment by dpgraham** [comment]
Sorry, this was buried in our backlog. Was a workaround ever found for this?

**Comment by llaskin** [comment]
I'm also interested in seeing a fix for it.

**Comment by dpgraham** [comment]
@realksullivan I've implemented this and tested it on my local machine. When you have a chance could you give this a try?

To run it locally you need to clone this repo, checkout the branch `dpgraham-allow-unauthorized` and then run 

```
npm install
npm run dev
```

Under the server selection I added an 'Advanced Settings' collapsible panel where you can specify the proxy.

**Comment by dpgraham** [comment]
@realksullivan Can you try this with the latest version? (1.5.0)
