### ISSUE TITLE
Lowest node in App Source is not expandable

### ISSUE THREAD

**Issue by darina-techery** [appium/appium-desktop#245]
[+] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Lowest tree node in App Source section cannot be expanded, possibly because it is overlayed by navigation buttons. If you manage to move this node upwards, you will be able to click it to expand, but if there are no collapsible nodes before it, you just cannot view its contents.

![image](https://user-images.githubusercontent.com/23314808/28060273-5a37c426-662f-11e7-91ea-13fc525f6df4.png)
The lowest node on screenshot (<android.widget.FrameLayout resource-id-"com.w..."> is affected by the issue described above.

## Environment

- I am running Appium Desktop version 1.1.0-beta.4.
- I am on macOS Sierra, v. 10.12.5

**Comment by dpgraham** [comment]
Thanks @darina-techery. It looks like the lowest node is being obscured behind the scroll buttons. This should be a simple CSS fix.

**Comment by dpgraham** [comment]
Committed to master
