### ISSUE TITLE
Unable to scroll  in Appium Desktop v1.6.5

### ISSUE THREAD

**Issue by garmilw** [appium/appium-desktop#253]
## Appium or Appium Desktop?

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When viewing the objects available in my running application, I am unable to scroll the right hand panel so that I can view the entire elected object definition.   I have verified that I can see all the information if I am using a large monitor.  However, when using a smaller laptop screen, I am unable to see all of the selected object definition.

I have attached a screenshot of this issue.

![image](https://user-images.githubusercontent.com/29234533/28387554-8c70eac0-6c9d-11e7-8946-039b9cfa8074.png)

## Environment

- I am running Appium Desktop version v1.6.5.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
This has been fixed. It will be part of the next release.
