### ISSUE TITLE
Mac Appium Desktop v1.1.0 -> Inspector -> Selected Element area is not scrollable - up and down.

### ISSUE THREAD

**Issue by Pankajshuklaqa** [appium/appium-desktop#254]
Mac Appium Desktop v1.1.0 -> Inspector -> Selected Element area is not scrollable - up and down.

**Comment by dpgraham** [comment]
Which version are you using? Have you tried the latest version?

We made a patch for this recently. If it's still a problem, let me know.

**Comment by Pankajshuklaqa** [comment]
I am using Mac Appium Desktop v1.1.0, this is the latest version which I installed yesterday only.

**Comment by BenjaminFausett** [comment]
I am also having this issue for version 1.1.0

**Comment by dpgraham** [comment]
The patch didn't actually make it into version 1.1.0

I'm publishing v1.1.1 right now. It will be in shortly once the CI is complete.

**Comment by dpgraham** [comment]
Published to v1.1.1
