### ISSUE TITLE
Can't launch HTTPS session via Custom Server page

### ISSUE THREAD

**Issue by LasseHall** [appium/appium-desktop#255]
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Can't launch HTTPS session via Custom Server page. The page allows choosing the port, but the request will always be sent as HTTP. This means that I cannot launch a session towards e.g. TestObject US datacenter, since TestObject allows HTTPS only.

## Environment

- I am running Appium Desktop version 1.1.0.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
I'll add this to our backlog.

**Comment by Anusha07** [comment]
Hi, a

Please suggest do we have any update on this.

Am trying to connect a Appium Server launched in Ubuntu machine from Windows Appium Server but seeing 'ECONNRESET' error.

Could you please check and suggest the steps to configure the connection.

Thanks & Regards

**Comment by dpgraham** [comment]
@Anusha07 are you sure this is the same problem?

**Comment by Anusha07** [comment]
Not exactly, I have raised a different ticket reporting the issue #441. Apologize for the inconvenience caused.
