### ISSUE TITLE
Add a choice between TestObject EU and US datacenters

### ISSUE THREAD

**Issue by LasseHall** [appium/appium-desktop#256]
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

TestObject has a US datacenter nowadays, but the Desktop App page defaults to the old endpoint, which always targets EU datacenter. It will be beneficial to target the US devices depending on user's own location.

Old endpoint targeting EU:
https://appium.testobject.com/wd/hub

The new endpoints for each datacenter are:
https://eu1.appium.testobject.com/wd/hub
https://us1.appium.testobject.com/wd/hub

## Environment

- I am running Appium Desktop version 1.1.0
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
That's a good idea. This should be fairly simple to implement and would have a big benefit. I'll put it on our backlog.
