### ISSUE TITLE
Security Risk Detected: WS.Reputition.1 for appium-desctop-setup-1.1.1

### ISSUE THREAD

**Issue by 1MaJKeL1** [appium/appium-desktop#259]
Hi,
I have trided install the latest version appium-desctop
appium-desktop-Setup-1.1.1.exe on my computer where Symantec protect me 

and result of this is alert line on below screen is any workaround how to solve this without disable Symantec?

![image](https://user-images.githubusercontent.com/30533643/28729227-ff39580a-73cb-11e7-95db-cdc77081518d.png)

**Comment by jlipps** [comment]
Why does Symantec think Appium Desktop is a security risk?

**Comment by dpgraham** [comment]
https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99&tabid=2

I don't think they specifically singled out us out. It's just an algorithm they use that determined AD is a security risk.

**Comment by 1MaJKeL1** [comment]
I don't know, when I try to installed this package always I got this alert
:( may be is some way how do get more detail for investigation do you have
any idea?

28.07.2017 20:45 "Jonathan Lipps" <notifications@github.com> napisał(a):

**Comment by dpgraham** [comment]
Not sure. We'll need to look into how to get it to pass.

Are you able to make an exception for Appium Desktop?

**Comment by irisgaray** [comment]
I added an exception, worked for me.
Open Symantec -> Change settings -> Exceptions

**Comment by 1MaJKeL1** [comment]
Thanks a lot for this info
It works also for me



2017-08-04 14:35 GMT+02:00 irisgaray <notifications@github.com>:

**Comment by dpgraham** [comment]
Thanks for letting us know about this. I'm going to close this ticket because I don't think we'll be able to resolve this.
