### ISSUE TITLE
Add ability to connect to already started server

### ISSUE THREAD

**Issue by rosolko** [appium/appium-desktop#261]
## Appium Desktop
 
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue 

## The problem

As user who start server from code I would like to have ability to connect to started server and attach to session from server.

Server started using code like this:
```java
final AppiumDriverLocalService service = new AppiumServiceBuilder()
            .usingAnyFreePort()
            .withArgument(GeneralServerFlag.LOG_LEVEL, "error")
            .build();
service.start();
```
After I can get _URL_ and _port_ of server.
And then I would like to connect to this custom server from UI and attach to session.

What do you thinks about this feature?
Thanks.

## Environment

- I am running Appium Desktop version _1.1.1_
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
We have that ability already. You can go to `Appium > New Session Window` in the file menu and from there attach to a custom server.

**Comment by rosolko** [comment]
@dpgraham Thanks for reply.

**Comment by dpgraham** [comment]
No problem. We're probably going to add a button on the main screen to start a new session. Going to the file menu isn't very intuitive.
