### ISSUE TITLE
we are unable to download Appium for windows desktop. Download is not working.

### ISSUE THREAD

**Issue by ankitrajput22288** [appium/appium-desktop#264]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Can you provide more details

**Comment by furkanozbay** [comment]
I can't download appium for windows. It is getting stuck at middle of download also download speed is so low

**Comment by dpgraham** [comment]
If it's a problem with downloading I don't think there's anything we can do. Sounds like a network problem or possibly a problem with GitHub Releases.
