### ISSUE TITLE
iOS device can't start session using appium-desktop, and keeps opening new appium-desktop ; while Android works fine

### ISSUE THREAD

**Issue by jiacy** [appium/appium-desktop#270]
- [YES ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

really grateful if any idea could be provided

## The problem

using appium-desktop, I try to inspect iOS real device(by start session); but it keeps loading as below, and opening a lot of new appium-desktop, seems like a Bug 
(By the way, Android using appium-desktop works fine ,   iOS using command-line appium works fine , iOS using old version (appium 1.5.3) works fine)

![image](https://user-images.githubusercontent.com/8677437/29011753-29df1fb0-7b68-11e7-9896-cca07fd92c73.png)

![image](https://user-images.githubusercontent.com/8677437/29011812-abef4278-7b68-11e7-96d5-69712ac7a8b4.png)

desired capabilities as below:
{
  "deviceName": "iPhone 6",
  "udid": "XXXXXXXX",
  "platformName": "iOS",
  "bundleId": "XXXX.XXX",
  "platformVersion": "9.3",
  "autoAcceptAlerts": "true"
}

## Environment

- I am running Appium Desktop version _1.1.1_.
- I am on Mac

**Comment by dpgraham** [comment]
* Can you also try running an iOS session but instead of using the 'Local Server' use a 'Custom Server' and point it to command line Appium?

* What exactly is happening? Is it getting stuck in the loading page and new windows are opening? When you open the other instances of Desktop what do you see?

**Comment by lolotoms** [comment]
Hi,

I think I related the same issue => https://github.com/appium/appium-desktop/issues/286

I tried with different XCode versions and face this issue with XCode 7.3.1. What is your XCode version?

**Comment by lolotoms** [comment]
@dpgraham It works fine if I use custom server

**Comment by dpgraham** [comment]
Does this happen with the latest version?

**Comment by dpgraham** [comment]
Does this happen with the latest version still?

**Comment by lvryasaswi** [comment]
I am running into this issue with Appium-Desktop 1.3.1 (1.3.1) and server is at 1.7.2. It barely works with custom server and almost never works when trying access WebView.

**Comment by bennid** [comment]
I'm also seeing the creation of sessions hanging on a real IOS device, and it ended up being that the app needed to be trusted.  While I was watching the phone, I never saw the popup, but manually trying it showed the "trust" popup..  Once I added the dev / app to the trusted list I was good to go.

**Comment by dpgraham** [comment]
I think this is probably an issue with Electron and not Appium Desktop. Once we upgrade to Electron 2 I'll check back on this.

**Comment by dpgraham** [comment]
If this still happens to anyone let me know and I'll re-open.
