### ISSUE TITLE
Feature Request: Locator supports Xpath, ID and other strategies to locate elements when using inspector. 

### ISSUE THREAD

**Issue by Azuer** [appium/appium-desktop#273]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## Feature Request

I think it's necessary to add a feature which can help to locate elements by Xpath, ID or other strategies when we use Appium - Desktop Inspector, so that we can test the correctness of Xpath (Although not recommended) and find elements easily.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
We support this in our latest version.
