### ISSUE TITLE
Cannot see Recorder button on when iOS native application is launched

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [appium/appium-desktop#274]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [-] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am using Appium to test iOS application. However, I cannot see the recording / recorder button. 
Is there something that has been changed? There is no information (at least I didnt see any) which informs how to turn on this feature

## Environment

- I am running Appium Desktop version _Version 1.1.0-beta.2 (1.1.0-beta.2)_.
- I am on (pick one):
    - [- ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by msan0217** [comment]
Did you create the session with gui after you started the server?
Looks there is no button anymore to invoke the inspector. It starts up automatically after the session is created. 

The issue for me is that I like to interrogate my app by using appium ruby console(arc) and also have access to the inspector at the same time. With the old desktopp gui app, I was able to open the inspector without even starting the server via the gui.

**Comment by dpgraham** [comment]
Can you provide more details and provide a screenshot.

**Comment by rahulkulkarniyahoo** [comment]
@msan0217 no, it was after the server was started. 
@dpgraham, please see attached image.
<img width="938" alt="screenshot 2017-08-11 09_fotor" src="https://user-images.githubusercontent.com/12827411/29209741-01fbce3a-7e88-11e7-9385-7ae62164fbea.png">

**Comment by dpgraham** [comment]
Which version are you using? Which operating system are you using?

**Comment by rahulkulkarniyahoo** [comment]
Hi @dpgraham,
I have mentioned this earlier. 
Anyways, addition mac version below:

I am running Appium Desktop version Version 1.1.0-beta.2 (1.1.0-beta.2).
[- ] Mac Seirra (10.12)

**Comment by rahulkulkarniyahoo** [comment]
I have updated Appium Desktop to Version 1.2.0-beta.1 (1.2.0-beta.1)
This is no longer an issue
