### ISSUE TITLE
Appium do not start the Android session ?

### ISSUE THREAD

**Issue by libin4669** [appium/appium-desktop#275]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

i am using appium  to test android application ,however I cannot start zhe Android session .
It reminds me of the following information：
A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): platformName Android not part of iOS

i set zhe capability is   platformName : Android
## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by jlipps** [comment]
please attach a screenshot of your desired capability object

**Comment by crhoads1024** [comment]
I am receiving the same error using Appium 1.7.1 Desktop on Mac 10.12.6 
Desired Cap Object detail below:

{
  "appiumVersion": "1.7.1",
  "deviceName": "b346be30",
  "deviceOrientation": "portrait",
  "host": "localhost",
  "port": "4444",
  "app": "Users/chrisrhoads/candi/AndroidAppFiles/Chamberlain.apk",
  "automationName": "XCUITest",
  "platformVersion": "5.1.1",
  "platformName": "Android",
  "appActivity": ".MainActivity",
  "appPackage": "com.chamberlain.myq"
}

**Comment by vashetty** [comment]
Hi everyone,

Even I was facing the same issue.

I just changed the "automationName": "XCUITest", to "Test". It started working for me. I believe there is some connection with XCUI for IOS test. We should not use it for android test

**Comment by tgthao** [comment]
Same my Issue but i forgot break from Switch case :(

**Comment by jlipps** [comment]
yes, `automationName` matters. The XCUITest driver only supports iOS. For Android, you can use `UiAutomator2`.
