### ISSUE TITLE
test is halting in between, because of multiple adb.exe process created in the background

### ISSUE THREAD

**Issue by RavindraSHirandagi** [appium/appium-desktop#278]
i am using Appium-desktop v1.6.5 with NOS on windows7 system, test is halting in between because of multiple adb.exe process created in the background, while running test suit

![capture](https://user-images.githubusercontent.com/15608341/29322855-aa860d28-81fc-11e7-9984-d4fa766bcac6.PNG)

Please let me know how to solve this problem, Thanks in advance

**Comment by jlipps** [comment]
And this test runs successfully with Appium from the command line?

**Comment by RavindraSHirandagi** [comment]
Currently this code is working fine when i include uiautomator2. But getting  staleElementException in many test cases.

**Comment by RavindraSHirandagi** [comment]
Please  let me know, how to handle this exception

**Comment by jlipps** [comment]
`StaleElementException` is not an error, it's just telling you that the state of the UI has changed and you need to re-find elements. Refreshing the source should do the trick in Appium Desktop. At any rate, it's not an Appium Desktop error.
