### ISSUE TITLE
While switching on Airplane mode, Wi-Fi won't get disabled in Android 7.0 (SM-T719Y)

### ISSUE THREAD

**Issue by tadesushilgithub** [appium/appium-desktop#279]
## Appium Desktop

- [ ] I have verified that on both Appium and Appium Desktop

## The problem
Wi-Fi network should disabled after enabling the Airplane mode but it won't get disabled. Is any API to disable the Wi-Fi network.
![screenshot_20170823-223218](https://user-images.githubusercontent.com/17309586/29628682-39f1963c-8804-11e7-83ae-92a224efe856.png)

## Environment

- I am running Appium Desktop version : v1.6.5
- I am on:
    - [ ] Windows

**API used (C#):**
AndroidCommandExecutionHelper.SetConection(driver,ConnectionType.AirplaneMode);

**Comment by jlipps** [comment]
This is not related to Appium desktop.
