### ISSUE TITLE
When the inspector captures screen resulting in crash with the tested app

### ISSUE THREAD

**Issue by darkmanno6** [appium/appium-desktop#281]
## Environment：
**Mac**：OSX 10.12.6
**Xcode**：v8.3.3
**Device**：iphone 6s /ios 10.3.3
**appium-desktop**:  v1.1.1
## Step & result:
I used to capture the screen with the ```inspector``` provided by ```appium-desktop```.
While capturing the screen on the page that using the ```iOS BaiduMap SDK v3.3.4``` ，the inspector will make my tested app crashed， And I find that the crash happens on ```BMKRouteSearch  object```.

> iOS BaiduMap SDK v3.3.4 :http://lbsyun.baidu.com/index.php?title=iossdk/sdkiosdev-download

### **Could somebody know this problem？**

**Comment by jlipps** [comment]
Does your test app crash while getting the screenshot with Appium from the command line (i.e., _not_ Appium Desktop?)

**Comment by darkmanno6** [comment]
@jlipps I'm sorry to reply to you now and how can I get the screenshot with Appium from the command line?

**Comment by darkmanno6** [comment]
@dpgraham pls open the issue again.
