### ISSUE TITLE
Launch application in  instrument way

### ISSUE THREAD

**Issue by AnandChaurasia** [appium/appium-desktop#282]
## Appium or Appium Desktop?
- Appium Desktop

## The problem
How we can launch Application in Instrument way, Please see screen show where I am trying to open same application 
1. With Appium desktop: 
       I am not able to see text property( please see screen shot)
2. I have lunched application with License tool (SeeTest): 
      In this case I am able to see Text property ( please see screen shot)

## Environment
- I am running  Appium-desktop-Setup-1.2.0-beta.1.
- I am on (pick one):
    - Windows 10

![appiumdesktopui](https://user-images.githubusercontent.com/21359464/29745672-dd5760e4-8ac1-11e7-98ff-5bdbde453a26.PNG)

![sameapplicationwithlisensetool](https://user-images.githubusercontent.com/21359464/29745675-e271a08a-8ac1-11e7-83eb-d8e085b5f888.PNG)

**Comment by jlipps** [comment]
If you run the source command on Appium command-line (not appium desktop), do you see the appropriate text value or not?

**Comment by AnandChaurasia** [comment]
No text value is not available, but when I am launching application with
seeTest text value is visible. I have attached two images one from appium
desktop and another from seeTest. Please see.

On 28-Aug-2017 7:21 PM, "Jonathan Lipps" <notifications@github.com> wrote:

If you run the source command on Appium command-line (not appium desktop),
do you see the appropriate text value or not?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/appium/appium-desktop/issues/282#issuecomment-325417571>,
or mute the thread

**Comment by jlipps** [comment]
If the text value is not available in Appium, then this is not an Appium Desktop issue. You should open an issue at the main Appium respository.
