### ISSUE TITLE
[Request] For selected element, is that possible to query it in local?

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium-desktop#283]
In current Inspect windows, when user selects any element from tree, appium-desktop will send a request to server to query this element for all information again -- for tap/clear/send keys purpose.

It's kinda slow on walking elements, esp on iOS device.

Could appium-desktop query its information locally since the tree already there ? 
For updating page source, we could have an option to auto-update (disabled by default).

Thanks.

**Comment by jlipps** [comment]
@lavi-xu much information can't be got without querying appium after the element is retrieved. but i agree this makes interacting with the element much slower. my preference would be for the query to happen behind the scenes and just show a little spinner, maybe with some text saying "Getting element details..." in the element window that doesn't prevent interaction. then information is filled out when the query returns.

@dpgraham what do you think.

**Comment by dpgraham** [comment]
Yeah it is a little bit slow. One thing we could do is debounce it so that it doesn't happen every time you hit an element. I don't think we can query it locally though because we don't know if the element has changed.

**Comment by dpgraham** [comment]
I have a fix that will be released next version. It debounces the calls to findElement, hopefully that helps the performance. I tried it locally and it's better than it was before.
