### ISSUE TITLE
Design Edit

### ISSUE THREAD

**Issue by chezluc** [appium/appium-desktop#284]
![screen shot 2017-08-30 at 7 02 44 am](https://user-images.githubusercontent.com/15020730/29876326-4dc4cc40-8d51-11e7-9b5e-e8e7f816f562.png)

Hi Appium team,
I saw the update for this screen - and much preferred the text.  Just my personal opinion. It makes it much clearer what each does with the words.

**Comment by jlipps** [comment]
@chezluc thanks for the feedback. did you see that the text is still present when you hover over the button?

**Comment by chezluc** [comment]
@jlipps I did. I like the directness of the text, at least for Start Session / Inspector. Just thoughts! Thanks!

**Comment by dpgraham** [comment]
Closing this as I don't think we'll get to this.
