### ISSUE TITLE
Appium Desktop Inspector doesn't work with Xcode 7

### ISSUE THREAD

**Issue by lolotoms** [appium/appium-desktop#286]
Hi

I use appium 1.6.5 to run test on iOS 9 with XCode 7. I made this choice because I use many Xpath and I found UIAutomation performances better than XCTest. I have issue when I try to inspect app with appium desktop 1.2.0-beta.3 and older version 1.1. It works fine with the inspector of appium 1.5.3.  I would also like to add that I have this issue only with Appium Desktop, my tests run without issues with appium 1.6.5

## The problem

The inspector never open but each time it fails, a new instance of appium desktop is open. 

## Environment

- I am running Appium Desktop version _1.2.0-beta.3_.
- I am on :
    - [ ] MacOS Sierra 10.12.6
- I am running on iOS 9.3.2
- I use XCode 7.3.1

## Appium log
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1266328/appium-server-logs.txt)

**Comment by lolotoms** [comment]
Hi, 

I just tried to launch appium 1.6.5 by terminal and use this session to open inspector with "custom server" from appium desktop. The inspector opens fine and seems to work.

**Comment by jlipps** [comment]
@lolotoms can you link to a gist of the logs from the successful run so we can compare?

**Comment by lolotoms** [comment]
Hi ,

Thanks for your answer. The successfull run logs are here =>
[Appium_logs.txt](https://github.com/appium/appium-desktop/files/1269488/Appium_logs.txt)

**Comment by lolotoms** [comment]
@jlipps did you find something about that?  I had compare the 2 files and I think a new instance is open when this error occurs :

[debug] [Instruments] [INST STDERR] 2017-09-01 09:41:05.737 instruments[36910:47321482] WebKit Threading Violation - initial use of WebKit from a secondary thread.

**Comment by jlipps** [comment]
@lolotoms i admit to being puzzled here. I can't see any significant difference. The log you mention about the WebKit Threading Violation is not usually a showstopper. In fact it also appears in the successful run's log. Maybe it has to do with instruments not liking being launched from a GUI somehow. I'm not sure. Unfortunately we don't support the old ios driver anymore, but only the XCUITest driver. So the best I can recommend is the workaround you have found: run Appium from the command line and connect via the 'custom server' option. Sorry I don't have any more ideas!

**Comment by lolotoms** [comment]
ok @jlipps . Thanks for your investigation
