### ISSUE TITLE
Inspectors search feature does not highlight elements

### ISSUE THREAD

**Issue by eitzenbe** [appium/appium-desktop#288]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When searching for elements in the inspector using a xpath expression that results in multiple results, its not clear which of the entries in the list box corresponds to which element in the UI. I would appreciate if when clicking/selecting an entry in the list box of the search result dialog, that the corresponding element in the UI panel gets highlighted, so that on eknows which element he is currently selecting

## Environment

- I am running Appium Desktop version _1.2b3_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
That's a known issue. It's a limitation that when you do a search for elements you only get the ID's so we don't know the bounds of the elements and we can't link them to the source.

We're looking at other options, because I agree it would be helpful to see the highlighter rectangles.
