### ISSUE TITLE
Appium Sauce Connect Selenium Relay on Linux

### ISSUE THREAD

**Issue by voor** [appium/appium-desktop#289]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am using the Appium Desktop and attempting to connect to SauceLabs Android Emulator through the Sauce Connect's Selenium Relay.  I'm not sure if or where documentation might exist to walk me through this, and so I'm pretty sure there's a chance this isn't configured properly.

 - I have the Sauce Connect properly running 
 - I have a Sauce Labs manual testing session open, but I am unable to see the test under session id list.
 - The Appium Desktop *does* work for Automatic Server if I run a Genymotion instance that can connect through adb.

![image](https://user-images.githubusercontent.com/1326605/30064502-efa63f94-921f-11e7-8134-f49e7b589c08.png)

Pushing "Start Session" gives me the following:

![image](https://user-images.githubusercontent.com/1326605/30064530-021df428-9220-11e7-868a-4177cdcc45fd.png)

Nothing is displayed in the Appium logs or the terminal logs for Electron.  Nothing is displayed under Network in Electron Developer tools or Console for Electron Developer tools.

## Environment

- I am running Appium Desktop version _commit c0addcc7887e792056777e6d97b91c20cc0f4dee_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [x] Linux (Fedora 25, 4.11.12-200.fc25.x86_64)

**Comment by jlipps** [comment]
Sorry for the lack of logs, we'll have to figure that out. It looks like you have it set up mostly right. The fact that you have a manual session running should be immaterial as Appium Desktop will start its own session. The reason you don't see it in the session id list is that we don't actually poll Sauce Labs for your session ids (it only polls a local server). So if you want to connect to a running session you'll have to paste it in (the session id is the sauce job id).

Your capabilities look god however you'd need a platformVersion (like 5.0). and is your app a URL? local app paths are not supported on sauce.

**Comment by voor** [comment]
Okay, just to be safe, I looked up some other examples of capabilities for Sauce Labs, ended up adding a few more parameters, and this appears to get it working:
```
{
  "browserName": "",
  "appiumVersion": "1.6.5",
  "deviceName": "Android Emulator",
  "deviceOrientation": "landscape",
  "platformVersion": "5.1",
  "platformName": "Android",
  "app": "{removed}",
  "waitforTimeout": 300,
  "commandTimeout": 300
}
```
