### ISSUE TITLE
why waiting for an element did not create code in recorder ?

### ISSUE THREAD

**Issue by msmirzazadeh** [appium/appium-desktop#294]
Appium Desktop

why waiting for an element did not create code line in recorder?
is there any way to capture waiting in session recorder?

**Comment by jlipps** [comment]
What do you mean by "waiting"? Appium Desktop does not have any "wait" feature.

**Comment by msmirzazadeh** [comment]
I mean, It's to be perfect that recorder of Appium Desktop has a controller to add waiting for presenting an element in screen and add the required code to the recorder.
right now users should add such code by them self manualy

**Comment by jlipps** [comment]
@msmirzazadeh yes, that is the intention. Appium Desktop's recorder is not meant to generate robust, production-ready code. It's meant to help you find elements and show what you can do with the API. Adding waits is something that would greatly complicate Appium Desktop's design and fool people into thinking that it is generating high-quality code when it is not. Adding waits manually is the recommended path forward. And _not_ using Appium Desktop's generated code in production is definitely recommended.
