### ISSUE TITLE
Appium-Desktop didn't run - An unknown server-side error occurred while processing the command. Original error: Xcode version 9.0 is not yet supported

### ISSUE THREAD

**Issue by cpt-buzz** [appium/appium-desktop#301]
Appium Desktop issue

## The problem

if i run the Appium-Desktop i get every time the message :"An unknown server-side error occurred while processing the command. Original error: Xcode version 9.0 is not yet supported"

## Environment

- I am running Appium Desktop version 1.2.1.
- I am on (pick one):
    - [X ] Mac

## Capabilities

{
  "platformName": "iOS",
  "platformVersion": "10.0",
  "deviceName": "iPhone Simulator",
  "app": "/Users/XXX.XXXXXX/xxxAPP/XXXXXX",
  "noReset": true
}

[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1320937/appium-server-logs.txt)

**Comment by shreyjade** [comment]
Hi Appium Team,
When i am running appium inspector from Appium Desktop app (version 1.2.1) on Mac, i am getting the same error. I want to inspect iOS elements. When the support for Xcode 9 will be provided? For time being, is there any other way i can inspect iOS elements?
Thanks

**Comment by jlipps** [comment]
You can always use a version of appium that's not included with appium desktop and connect with that. you don't have to use the bundled server for the inspector. for example, appium 1.7 works with xcode 9+.

**Comment by luisromanwp** [comment]
@jlipps I'm having an issue and I'm using Appium 1.7 with latest Appium Desktop and is that I cannot get screenshots from a device with iOS 11 so I cannot inspect my app, is necessary to wait for the next Appium Desktop build or it should work if I'm using Appium 1.7?

**Comment by jlipps** [comment]
if you can't get screenshots using appium 1.7, i would open an issue at the appium issue tracker and follow the prompts there to send in your logs. unless you've proved that getting screenshots works using appium 1.7, but for some reason only fails inside appium desktop.

**Comment by Akulavenkatesh** [comment]
Work around for this - we can inspect elements on Xcode 9 + iOS 11 using Appium Version 1.5.3 (Ara), check the below video

[Solved] Appium Error - Xcode version 9.0 is not yet supported
https://www.youtube.com/watch?v=mGpfjbPsO20

**Comment by jameer4awe** [comment]
I am also facing this issue in below environment. 
Client: iOS 11.0.3 (iPad mini 4)
Appium Desktop: 1.2.6 (1.2.6)
Appium CLI version: 1.7.0-beta
Xcode: Version 9.1 (9B55)
Platform: Mac 10.12.6

I tried running appium server from command line as well as from appium desktop. In both cases either appium inspector not responding or inspector session getting closed without any reason if launched successfully.

**Appium Server logs:**

[debug] [XCUITest] Using Xcode 9.1, so fixing WDA codebase
[debug] [XCUITest] Generating xcode config file for orgId 'S7B98TLXT2' and signingId 'iPhone Developer'
[debug] [XCUITest] Writing xcode config file to /var/folders/dc/38bcsjzn1499y8j772b7pwwr0000gn/T/2017107-90375-1ly2w8a.0wm9/appium-temp.xcconfig
[debug] [XCUITest] Using Xcode configuration file: '/var/folders/dc/38bcsjzn1499y8j772b7pwwr0000gn/T/2017107-90375-1ly2w8a.0wm9/appium-temp.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1b3ef1a663bf6376717e5e839b95de0220c66a5d IPHONEOS_DEPLOYMENT_TARGET=11.0 -xcconfig /var/folders/dc/38bcsjzn1499y8j772b7pwwr0000gn/T/2017107-90375-1ly2w8a.0wm9/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/dc/38bcsjzn1499y8j772b7pwwr0000gn/T/com.apple.dt.XCTest/IDETestRunSession-6F39280E-3030-4FC1-9C91-A721AA54077A/WebDriverAgentRunner-0C4031FC-4914-4FDD-9849-5D48C2428EE7/Session-WebDriverAgentRunner-2017-11-07_164711-gtJqS3.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.0.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.0.3\",\n      \"ip\" : \"10.1.177.168\"\n    },\n    \"build\" : {\n      \"time\" : \"Nov  7 2017 16:47:02\"\n    }\n  },\n  \"sessionId\" : \"2B47C74F-B347-4CC6-90A6-9ED70F102BA3\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '10.1.177.168'
[debug] [XCUITest] WebDriverAgent successfully started after 22830ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1510033639734 (16:47:19 GMT+1100 (AEDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.swm.cwgames","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"853984F7-7A88-45C9-9D22-8A874ED948BB","capabilities":{"device":"ipad","browserName":"Olympics On 7","sdkVersion":"11.0.3","CFBundleIdentifier":"com.swm.cwgames"}},"sessionId":"853984F7-7A88-45C9-9D22-8A874ED948BB","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1510033645852 (16:47:25 GMT+1100 (AEDT))
[debug] [XCUITest] Cannot find a match for DerivedData folder path from lsof. Trying to access logs
[XCUITest] Setting '555' permissions to '/Users/jameerhuilgol/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1510033645920 (16:47:25 GMT+1100 (AEDT))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1510033645921 (16:47:25 GMT+1100 (AEDT))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/853984F7-7A88-45C9-9D22-8A874ED948BB/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"853984F7-7A88-45C9-9D22-8A874ED948BB","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1510033647511 (16:47:27 GMT+1100 (AEDT))
[Appium] New XCUITestDriver session created successfully, session cc04184f-ce23-439f-a96b-6d7134109b8b added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1510033647512 (16:47:27 GMT+1100 (AEDT))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"bundleId":"com.swm.cwgames","deviceName":"iPad mini 4","noreset":"true","platformName":"iOS","platformVersion":"11.0.3","udid":"1b3ef1a663bf6376717e5e839b95de0220c66a5d","xcodeOrgId":"S7B98TLXT2","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}
[HTTP] <-- POST /wd/hub/session 200 40188 ms - 555 
[HTTP] --> POST /wd/hub/session/cc04184f-ce23-439f-a96b-6d7134109b8b/context {"name":"NATIVE_APP"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","cc04184f-ce23-439f-a96b-6d7134109b8b"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'NATIVE_APP'
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/cc04184f-ce23-439f-a96b-6d7134109b8b/context 200 1 ms - 76 
[HTTP] --> GET /wd/hub/session/cc04184f-ce23-439f-a96b-6d7134109b8b/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["cc04184f-ce23-439f-a96b-6d7134109b8b"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/853984F7-7A88-45C9-9D22-8A874ED948BB/source] with no body
