### ISSUE TITLE
Recorder giving incorrect Python code for swipe

### ISSUE THREAD

**Issue by Heathland** [appium/appium-desktop#303]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [n/a] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When using the recorder function of Appium Desktop it generates the following code:
TouchAction(driver)
  .press({x: 192, y: 1062})
  .moveTo({x: 60: y: 61})
  .release()

The moveTo is incorrect and it lacks .preform().
This one however does seem to work:
TouchAction(driver).press({x: 192, y: 1062}).move_to({x: 60: y: 61}).release().preform()

Also, it doesn't include the import for the touchdriver.

## Environment

- I am running Appium Desktop version 1.2.1.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by Heathland** [comment]
Also, the coordinates notation is incorrect.

**Comment by dpgraham** [comment]
Thanks @Heathland! I'll put this in our backlog. I must admit that I didn't have time to test the actual Python code.

**Comment by dpgraham** [comment]
Publishing to 1.2.5
