### ISSUE TITLE
AttributeError: 'module' object has no attribute 'remote'

### ISSUE THREAD

**Issue by lionel-SF** [appium/appium-desktop#306]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1,I using appium-desktop 1.2.1, and xcode8, os10.12.6; 
2,using appium-desktop recording, save as mypython.py file;
3,runing mypython.py by pycharm and I got error:
 **AttributeError: 'module' object has no attribute 'remote'**
traceback details:
driver = webdriver.remote("http://127.0.0.1:4723/wd/hub", caps)
Traceback (most recent call last):  AttributeError: 'module' object has no attribute 'remote'

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [√ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by lionel-SF** [comment]
I made it,
the record had made a mistake here ；driver = webdriver.remote("http://127.0.0.1:4723/wd/hub", caps), **the "remote" should be "Remote";**

**Comment by dpgraham** [comment]
Publishing to 1.2.5

**Comment by hemrajmeena** [comment]
Hey i have an error in log_info("Created for %s", request.remote)
AttributeError: 'Request' object has no attribute 'remote'
while doing webrtc.

**Comment by chethank1990** [comment]
use this
driver =webdriver.WebDriver( 'http://localhost:4723/wd/hub', desired_cap )
