### ISSUE TITLE
[Appium Desktop] Not showing all the accessibility in the Find By, also is label = accessibility? 

### ISSUE THREAD

**Issue by momoDeako** [appium/appium-desktop#307]
Appium Desktop:

After I set up webrunner, then I have appium desktop up and running to check accessibility label for ios. 

After I setup above, I had inspector checking accessibility for our app, I expect to see the same accessibility as in Android version. Our app is written in React Native.

So here are some weird behavior I noticed: 
1: Appium desktop only shows some of the accessibility id in the Find by. When I use voice over to verify, the accessibility labels are there. 

[Appium for ios]
![screen shot 2017-09-27 at 11 35 36 am](https://user-images.githubusercontent.com/30352862/30933864-a06e2cbc-a380-11e7-8e87-df05656a7c6a.png)

[uiautomator for Android, you can see that Home has a accessibility label as the others]
![screen shot 2017-09-27 at 11 36 52 am](https://user-images.githubusercontent.com/30352862/30933898-bf829412-a380-11e7-9c4d-082b18f07b0d.png)

2:  I could not see some of the label yesterday, and when I get to the office, Appium desktop showed me a bit more accessibility labels. But I can still tell, it's not showing me all the accessibility labels. 

3: This might because I haven't found the right doc yet, I noticed that the name and label in the attribute are the same as accessibility id, so I'm wondering if they are suppose to be the same thing?

[You can see name and label and accessibility id are the same, maybe it has something to do with how React Native implement elements]
 
![screen shot 2017-09-27 at 12 33 50 pm](https://user-images.githubusercontent.com/30352862/30933995-0732f694-a381-11e7-860d-70c306b3d2bb.png)

## Environment

- I am running Appium Desktop version _<Version 1.2.2 (1.2.2)>_.
- I am on Mac.
- Appium Desktop runs with Appium 1.6.5, and my laptop has Appium 1.7.0

Also attached some screenshot to help with the explanation.

**Comment by dpgraham** [comment]
`accessibility id` is an Appium convention for locating elements. For iOS we use `name` as an alias for `accessibility id`. For Android we use `content-desc` as an alias for `accessibility id`. 

If an element doesn't have said attribute, you can't locate it using `accessibilityId`.

**Comment by momoDeako** [comment]
@dpgraham  

Hi, Dan! 
Thank you for making things clear for the third part. 
What do you think about the first weird behavior. I know we added accessibility there, I don't understand why I don't see it some times.

**Comment by jlipps** [comment]
@momoDeako because of the way Appium Desktop works, we don't show the 'accessibility id' recommendation if it is not unique. could it be that multiple elements share the same name?

**Comment by momoDeako** [comment]
Hey Jonathan! 

Thank you for the reply. And Sorry for the late reply. 
I just changed bunch of out accessibility id today, and will respond back if I still see any weird behavior.

**Comment by gargvishal** [comment]
@jlipps @momoDeako
I am unable to see Elements ID/Name/XPath or other details using Appium Desktop [1.7.1] Inspector.
OS version: 10.12.6
XCode version: 9.0
Appium Desktop Version: 1.7.1 
Here is the screenshot of what i am seeing, please let me know what other information is required:
<XCUIElementTypeApplication name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeOther name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">
<XCUIElementTypeWindow name="AX error -25205">

**Comment by dpgraham** [comment]
@gargvishal Do you have the latest Appium Desktop? (1.7.1 refers to the version of Appium not Appium Desktop, to see the version of Desktop go to the menu `Appium > About Appium`)

What happens when you try selecting an element?

**Comment by gargvishal** [comment]
@dpgraham Yes, i have latest Appium Desktop (1.2.5).
When i try to select an element , i see the same 'AX error -25205' .

**Comment by sgt00kb** [comment]
@dpgraham  Hi! Appium community! Sorry, I got back to the community so late. Again, I'm going to list several things I noticed, and I will also put my my best assumption on the cause as well. 

Background info: We use react native for our app. 

What happened: 
We uses a library called "react-native-popup-menu" for one of our mane. And I have Appium to press one button that will open another button. First, Appium behave differently on our test machine than my dev machine. (Well.... like environment causing problem is a first day thing.) On my machine, Appium is not able to press the first button(but can see), and Appium can see and press the second one. However, on the test machine, it can't press the second button. 

My guess: environment and how the third party library is developed. 

Notes: when I use Appium Desktop today, Appium didn't show me the second button. (This is on my dev machine.)

**Comment by sgt00kb** [comment]
@gargvishal  Just out of curious, I normally restart my appium desktop when i run into the error you are seeing, would you like to share what happened when you restart? (Refresh never worked for me.)

**Comment by gargvishal** [comment]
@sgt00kb, upon restart i am seeing the same error.
however, i also see below line indefinite times when the app was not launched once:
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body

**Comment by sgt00kb** [comment]
@gargvishal  what do you get when you run `driver.getPageSource()`?

**Comment by gargvishal** [comment]
@sgt00kb 
i got this:
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["39947e02-e933-40b3-a1b3-3b386bdde1bf"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/ECA49E53-30BF-4834-B1C0-02A46F649E05/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n      
[HTTP] <-- GET /wd/hub/session/39947e02-e933-40b3-a1b3-3b386bdde1bf/source 200 1717 ms - 9598 

is it what you are asking for?

**Comment by sgt00kb** [comment]
Yes, can you do a System.out.print() and share the result? (I'm not one of the Appium dev, I can only offer how I handle situation like this at work myself.)

**Comment by gargvishal** [comment]
@sgt00kb 

[Appium GetPageSource.pdf](https://github.com/appium/appium-desktop/files/1417493/Appium.GetPageSource.pdf)

**Comment by sgt00kb** [comment]
Wow...... Okay, this is really bad. Hmm... how about this: https://stackoverflow.com/questions/6878530/ax-error-when-using-accessibility-inspector-for-ios-app/12964677

**Comment by gargvishal** [comment]
@sgt00kb
well, the link that you have shared seems unrelated because the person who logged this mentioned "This error does not seem to cause any side-effects. I can use the app and examine the elements freely. " while in my case i am not able to find the elements.

**Comment by gargvishal** [comment]
@sgt00kb thanks for all your help.

@jlipps @momoDeako @dpgraham @imurchie Any help on this issue will be highly appreciated.

**Comment by gargvishal** [comment]
My issue has been resolved.
Upgraded the IOS version to 11 in IPhone 6 and it works fine. Able to inspect the elements.
The XCode version used is 9.X
Got help from here:
https://github.com/facebook/WebDriverAgent/issues/703
