### ISSUE TITLE
Recorder code is not updated after new command is sent

### ISSUE THREAD

**Issue by dmlemeshko** [appium/appium-desktop#309]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1. Click Start recording 
2. Click `Tap by coordinates`
3. Tap on any UI element in inspector view 
-> valid code sample is displayed
4. Tap on any UI element in inspector view

Actual: old code sample is displayed
Expected: new code sample is displayed

## Environment

- I am running Appium Desktop version _1.2.3_.
- I am on (pick one):
    - [x] Mac Sierra 10.12.6
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
@dmlemeshko Are you saying that tapping the coordinates has no effect on the sample code? So, it just stays the same?

**Comment by dpgraham** [comment]
I'm not able to reproduce this issue. Have you tried with the latest version?

**Comment by dmlemeshko** [comment]
@dpgraham 
Sorry, there is no bug. Since there is no visible scroll in code block I thought that code (`JS WD (Promise)` selected) is not updated
Just checked version **1.2.5** and recorder works perfect
