### ISSUE TITLE
"Save" functionality does not work in JSON Representation field

### ISSUE THREAD

**Issue by ChiWhiteSox56** [appium/appium-desktop#310]
## Appium or Appium Desktop?
Appium Desktop

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The "Save" functionality does not seem to be working when I edit configurations in the JSON Representation instead of in the Desired Capabilities fields.

## Environment

- I am running Appium Desktop version 1.2.3.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
@ChiWhiteSox56 What happens when you press the 'Save' button?

**Comment by dpgraham** [comment]
@ChiWhiteSox56 can you provide me with steps to reproduce this? I don't seem to be having this problem.
