### ISSUE TITLE
Swipe code generator for Python bugs

### ISSUE THREAD

**Issue by jashsu** [appium/appium-desktop#312]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Swipe action Python code generator syntax bugs. Generated this text:

```
TouchAction(driver)
  .press({x: 546, y: 1703})
  .moveTo({x: 0: y: -859})
  .release()
```

In both the .press and .moveTo actions, the dictionaries need quoted keys. On the moveTo, the x and y should be separated by a comma instead of a colon.

## Environment

- I am running Appium Desktop version 1.2.3.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jashsu** [comment]
Actually looking at the definition of press and moveto:

`def press(self, el=None, x=None, y=None):`

The correct syntax should be something like:

```
  .press(x=${x1}, y=${y1}})
  .moveTo(x=${x2}, y=${y2}})
  .release()
```

**Comment by jashsu** [comment]
https://github.com/appium/appium-desktop/pull/313

**Comment by dpgraham** [comment]
Thanks for the fix @jashsu
