### ISSUE TITLE
Appium Desktop 1.2.3 show Appium Version 1.7.0 - release note say it is 1.7.1

### ISSUE THREAD

**Issue by rahulmr** [appium/appium-desktop#315]
## Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop 1.2.3 show Appium Version 1.7.0 while release notes say it is 1.7.1
Please see snaps. 

## Environment

- I am running Appium Desktop version _1.2.3_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux
![image](https://user-images.githubusercontent.com/10260232/31557658-4fe3c038-b067-11e7-8d9b-e6fce2d062d0.png)
![image](https://user-images.githubusercontent.com/10260232/31557721-93ad0572-b067-11e7-8e5b-7dc18b944b0d.png)

**Comment by rahulmr** [comment]
It seems like [package.json](https://github.com/appium/appium-desktop/blob/master/package.json) still have `appium 1.7.0`

**Comment by welnanick** [comment]
Issue is not present on Mac, so it seems to be a windows only issue

**Comment by rahulmr** [comment]
@welnanick That seems unusual. But as I mentioned the package.json also has 1.7.0 as dependencies. So there seems to be a fix needed.

**Comment by dpgraham** [comment]
Fixed by version 1.2.4
