### ISSUE TITLE
Feature Request - Appium Desktop - Ability to switch between webview and native app view from inspector

### ISSUE THREAD

**Issue by kdthomas2121** [appium/appium-desktop#317]
Appium Desktop

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When testing hybrid apps, the inspector is not very useful, as it will only work for the native side of apps, even when setting autowebview to true. If there was a way we could run driver.set_context from the inspector it would be so much more useful.

## Environment

- I am running Appium Desktop version _1.7.1_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
@kdthomas2121 we intentionally don't allow this. You can test webviews by using the Chrome or Safari inspector against sims/emus or real devices. Then you get a much more full-featured inspector than we could ever build in Appium Desktop ourselves.

**Comment by lasterra** [comment]
but with the chrome inspector we cannot record. I agree with you that chrome inspector is better than appium, but, how can we record android webview test cases? i think it is a very powerful feature
