### ISSUE TITLE
Always Include latest version of WinAppDriver in Appium Desktop

### ISSUE THREAD

**Issue by gouthamsam** [appium/appium-desktop#320]
Please include latest version of WinAppDriver.

Thanks

**Comment by dpgraham** [comment]
The next Appium version  will have it.

**Comment by zavvio** [comment]
@dpgraham 

As of appium-desktop release v1.2.7, WinAppDriver is still not installed automatically, nor does it mention which version is needed if missing. (ran the setup exe with both user and admin mode, neither worked.)

Tested separately that "npm -g install appium" run with admin mode of command prompt on windows 10 would install WinAppDriver v0.9 (not the latest version which causes some trouble but at least it installed one).

Any info?
