### ISSUE TITLE
Desired Capabilities Link not working on Appium Desktop

### ISSUE THREAD

**Issue by Nightwing93** [appium/appium-desktop#321]
##Appium or Appium Desktop? - Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does not reproduce on Appium itself:

    [ yes] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hello,
In Appium desktop inspector Desired capabilities link is not working. After clicking the link it'll show 404 page on GitHub.

## Environment

- I am running Appium Desktop version _1.2.4_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Thanks for letting me know! I'll fix that for the next release.

**Comment by dpgraham** [comment]
This will be fixed soon. It won't even require a release, I just need to fix the broken link.

**Comment by Nightwing93** [comment]
Sure Happy to help.
