### ISSUE TITLE
Appium Desktop : After selecting any element the app keeps refreshing

### ISSUE THREAD

**Issue by Shahunks** [appium/appium-desktop#328]
![screen shot 2017-10-24 at 3 38 55 pm](https://user-images.githubusercontent.com/25055088/31937816-42fb7608-b8d3-11e7-834e-6b59a71542a9.png)

## Appium or Appium Desktop? Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ yes] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Selecting any element the app will refresh , unable to copy the locators  
## Environment

- I am running Appium Desktop version _<1.7.1>_. 
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
Can you provide the logs for when you select an element?

The refresh occurs if the element that was selected was stale.

**Comment by Shahunks** [comment]
How to over come Stale elements and click on them?

**Comment by dpgraham** [comment]
I have a fix for that in a PR. I'm getting rid of the auto-refresh feature and I made a fix that tries different selector strategies if the first one doesn't work.

**Comment by dpgraham** [comment]
The fix will be in the next version of A.D. within the next day or so.

**Comment by Shahunks** [comment]
okay thank you
