### ISSUE TITLE
Unlock capabilities failing with Samsung S8 running 7.0.0

### ISSUE THREAD

**Issue by sahilx13** [appium/appium-desktop#329]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ Yes ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unlock capabilities are failing with Samsung S8 running 7.0.0. The error I am getting is "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Screen did not unlock successfully, retrying". When the unlock code will load, the lock screen will pop up but will fail right after that(seems like input numbers/elements are not recognized by the code.). Attaching the server side log.

## Environment

- I am running Appium Desktop version _<1.7.1>_.
- I am on (pick one):
    - [ ] Windows

**Comment by dpgraham** [comment]
Can you open this as an issue in https://github.com/appium/appium/issues and also provide the full appium logs.

**Comment by sahilx13** [comment]
Yes, i have opened an issue #9530 and have attached the appium logs as well.

**Comment by dpgraham** [comment]
I'll close this issue then thanks.
