### ISSUE TITLE
Windows 10 GUI is blank

### ISSUE THREAD

**Issue by hujosh** [appium/appium-desktop#331]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I open Appium (by double-clicking the desktop shortcut) the GUI opens, but it's blank. See the attached image:
![appium](https://user-images.githubusercontent.com/17036601/32027437-c93d7f60-ba34-11e7-9426-a6fa97165d9f.png)

## Environment

- I am running Appium Desktop version _1.2.6_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Has this happened with previous versions?

**Comment by dpgraham** [comment]
And which version of Windows is this?

**Comment by hujosh** [comment]
Hi,

I am running windows 10. It happened with the version before the latest too. I will download prior versions and test them too

**Comment by dpgraham** [comment]
Okay thanks. I'll test it out tomorrow morning. 

Can you also try looking at the devtools?

You can do so by

* Opening the app
* Right clicking and selecting 'Inspect Element' (on any part of the screen)
* Open up the 'console' tab and see if there are any errors

**Comment by dpgraham** [comment]
I can't reproduce this on my Windows machine. Do you know what the exact version of windows you're using?

**Comment by hujosh** [comment]
Hi, sorry i have not had time to do this yet.  

Let me say this. On my work computer, which users windows 10,  I have this problem. On my home computer, which also uses windows 10, i don't have this problem (though i do have another problem, which i will make another issue about).

Work computer specs:
Edition: Windows 10 Pro
Version: 1709
OS build: 16299.19

**Comment by hujosh** [comment]
Hi,
I think this problem is a case of 
https://github.com/electron/electron/issues/10239

Will investigate

**Comment by dpgraham** [comment]
Okay thanks for checking it out. I would suggest trying to download another Electron app to see if the pf9blem persists.

**Comment by dpgraham** [comment]
Okay thanks for checking it out. I would suggest trying to download another Electron app to see if the problem persists.

**Comment by dpgraham** [comment]
@hujosh Is this still a problem for you? I may try updating the version of electron that Appium Desktop uses to see if it fixes this.

**Comment by yodurr** [comment]
I can't repro this.  Trying other electron apps on that machine for the same behavior would be very helpful info.

**Comment by dpgraham** [comment]
@yodurr I can't on my Windows laptop either. I'm pretty sure it's an Electron problem.

**Comment by hujosh** [comment]
Hi it still happens to me. You need to have the windows preview version of windows 10 installed for it to happen.

**Comment by dpgraham** [comment]
@hujosh Have you tried other Electron apps to see if the same problem happens?

**Comment by hujosh** [comment]
ok i will

**Comment by dpgraham** [comment]
I just released a new version 1.3.0 that uses an updated electron version. Can you try with that?

**Comment by hujosh** [comment]
Hi,

I tried it. It is still blank. It's ok. This just affects windows 10 insider builds. It's not a big deal.

**Comment by dpgraham** [comment]
I don't think we'll be able to fix this. We'll keep it up-to-date with new Electron versions and hopefully that fixes it.
