### ISSUE TITLE
Issue with Appium inspector :"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, ,

### ISSUE THREAD

**Issue by chennareddy08** [appium/appium-desktop#333]
#250  Appium Desktop?
Version 1.2.6 (1.2.6)
![screen shot 2017-10-27 at 12 12 45 am](https://user-images.githubusercontent.com/8956347/32071043-ad667e96-baab-11e7-8e21-766ebc34c4a6.png)

![screen shot 2017-10-27 at 12 00 58 am](https://user-images.githubusercontent.com/8956347/32070454-060d6e76-baaa-11e7-92f9-805e05c6b61f.png)
Please refer attached snap

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Could not obtain source: {"cause":{"sessionId":"12509fca-f7ef-4709-a9f3-f238b073943d","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application"}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application","status":13}
## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
Can you provide the Appium logs?

**Comment by chennareddy08** [comment]
please find attached appiumissue.txt in above

**Comment by chennareddy08** [comment]
[appiumissue.txt](https://github.com/appium/appium-desktop/files/1423052/appiumissue.txt)

**Comment by dpgraham** [comment]
Thanks. This isn't an issue with Appium Desktop, but rather an issue with Appium

Can you file a ticket with a [gist](https://gist.github.com) of the Appium logs at https://github.com/appium/appium/issues

**Comment by chennareddy08** [comment]
created separate ticket in appium

**Comment by AwayQuEM** [comment]
This issue occurred while I upgraded to `mac os high sierra`

**Comment by PankajPatil2018** [comment]
Anyone got any solution for this issue? since I am facing the same problem
