### ISSUE TITLE
[1.2.6 only] Alert for "Could not find element..." even page did not change or connection did not lost

### ISSUE THREAD

**Issue by lavi-xu** [appium/appium-desktop#335]
In inspect "App Source" windows, just click more elements, it alerts for "Could not find element. Try refreshing page" very often.

Connection to appium server is stable.  APP page was not changed.

Tested on android and ios, both has this issue.
Back to 1.2.4 never see this issue.

**Comment by lavi-xu** [comment]
All these buttons on all versions are working good.

**Comment by dpgraham** [comment]
So it's incorrectly showing the error

**Comment by samsonbarukula** [comment]
hi Lavi : 1.2.6 appium always shows error: could not find element 
what might be the issue.... can you help

**Comment by vikramvi** [comment]
@samsonbarukula this place is reporting bugs, please ask queries in http://discuss.appium.io/

**Comment by samsonbarukula** [comment]
I have tried with ipad 11.0 real device

**Comment by samsonbarukula** [comment]
ok thank you Vikram

**Comment by ndinoia** [comment]
I'm also getting spammed with these notifications in appium desktop. They keep appearing while I'm trying to browse the UI xml hierarchy tree.
I usually will navigate to a section of the app, hit refresh and then navigate the tree. The notifications keep appearing until the screen is full; I'm not interacting with the AUT, I'm just selecting elements in the app source.

**Comment by ndinoia** [comment]
![screen shot 2017-11-14 at 3 54 31 pm](https://user-images.githubusercontent.com/24900139/32804221-3e430c34-c954-11e7-9e1e-121f3a15a753.png)

**Comment by dpgraham** [comment]
@ndinoia @lavi-xu @samsonbarukula Does one of you have an .apk that I could test this out with? Perhaps one of you has an app available over the Play Store? I'd like to try reproducing this on my side.

**Comment by ndinoia** [comment]
@dpgraham I can reproduce the issue with safari:

1. Go to google.com
2. Refresh page
3. Select elements in the App Source section
4. Scroll down
5. Select more elements

**Comment by dpgraham** [comment]
Perfect. Thanks @ndinoia I'll give that a shot.

**Comment by dpgraham** [comment]
I'm going to get rid of the notification and instead show a message on the right pane just to say when interactions are not available. The notification is admittedly obnoxious.

**Comment by dpgraham** [comment]
Fixed in latest version.
