### ISSUE TITLE
Encountered internal error running command: Error: The desired capabilities must include either an app or a bundleId for iOS

### ISSUE THREAD

**Issue by findmanish** [appium/appium-desktop#336]
getting error when i have passed bundleId correctly.
Here is the code

	final DesiredCapabilities capabilities = new DesiredCapabilities();
     

			capabilities.setCapability("deviceName","iPhone 6s");
			capabilities.setCapability("bundleId", bundleId);
			capabilities.setCapability(CapabilityType.BROWSER_NAME, browser_name);
			capabilities.setCapability("platformName", platformName);
			capabilities.setCapability("UUID", deviceUUID);
			capabilities.setCapability(CapabilityType.VERSION,oSVersion);
			capabilities.setCapability("newCommandTimeout", service_timeout);
			capabilities.setCapability("appPackage", appPackage);
			capabilities.setCapability("appActivity", appActivity);
			
sending these files from config files.

**Comment by dpgraham** [comment]
Is bundleId defined?

**Comment by findmanish** [comment]
yes

**Comment by findmanish** [comment]
Not sure how this got fixed on my end.Uninstalling an reinstalling appium got problem solved.
Closing this
