### ISSUE TITLE
Appium inspector is not launching for iOS-11

### ISSUE THREAD

**Issue by deepakkg88** [appium/appium-desktop#340]
**Appium Desktop** 

**Problem:**
I am getting below error when I try to launch Appium inspector:

ios-deploy[4198:260473] [ !! ] Error 0xe8000067: There was an internal API error. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
’.
[XCUITest] Error: Could not install app: ‘Command ‘ios-deploy --id 9d16aca34aa6c5950e63689b526dbbfcebbe4b47 --bundle /var/folders/77/lc3w5ldx6cg8h6c9ykh00klmwydhgh/T/2017106-4081-lcrduf.4w6cpzxgvi/Payload/JiTriOS.app’ exited with code 253’

**Environment:**
I am using appium desktop 1.2.4,Xcode-9,iOS-11 and iPhone 7 Plus real device.I have tried with appium 1.2.6 as well.

**Comment by vikramvi** [comment]
@deepakkg88  please fill remaining details as per issue template, it will help to debug
