### ISSUE TITLE
Snapshots of appium page and elements

### ISSUE THREAD

**Issue by dkdodson3** [appium/appium-desktop#341]
## Appium Desktop

Not sure if this is the right channel for a feature request.

Would it be possible to take a snapshot or save off what the appium desktop is displaying, the app source, and the data for each element. That way I could go through my app, save each screen, then load each screen into appium desktop and use the data to write tests. 

It takes a long time for me to get to a specific location in my app and then I have to try different things in my code to get the tests working. I do not always know all that I need right up front, but if I could save off the data and load it as needed then I would save a lot more time.

**Comment by dpgraham** [comment]
I don't see us adding a feature that allows you to upload the source XML and screenshot for inspection; but we have talked about a feature where you can download the screenshot and source (see https://github.com/appium/appium-desktop/issues/287)
