### ISSUE TITLE
Option to Highlight element when searching for an element

### ISSUE THREAD

**Issue by dkdodson3** [appium/appium-desktop#342]
## Feature Request

Being able to search for an element is awesome. However when I am doing discovery, I don't necessarily need to tap on it but I need to make sure I am finding the right element. Could you add the option to double click on the element you were searching for and have it highlight the element and take you to the correct location in the xml?

**Comment by dpgraham** [comment]
Yeah that's on our list of future features. I'll track it using this issue.

**Comment by dpgraham** [comment]
Published to 1.2.7

**Comment by qual** [comment]
@dpgraham Is this feature deployed? How to enable highlight element in Native app ?

**Comment by shahul-code** [comment]
@dpgraham Is this feature deployed? How to enable highlight element in Native app ?

**Comment by dpgraham** [comment]
Yes, it's in Appium Desktop. When you search for elements and select one it highlights the element.
