### ISSUE TITLE
Unable to locate locators - Appium inspector

### ISSUE THREAD

**Issue by Nithinundercloud** [appium/appium-desktop#343]
![screen shot 2017-11-15 at 3 11 30 pm](https://user-images.githubusercontent.com/33681012/32829513-4c6ece82-ca18-11e7-81f1-1e610a3c5bba.png)
## Appium or Appium Desktop?
I am using appium v 1.7.1,appium desktop 1.2.6.

## The problem
I am trying to locate the xpath for the elements present in the application but, appium inspector couldn’t able to do it. Below are the elements that was recognised by the inspector :
_<XCUIElementTypeApplication name=\"Apella\">_
\<XCUIElementTypeWindow>
\<XCUIElementTypeOther>
\<XCUIElementTypeOther>
\<XCUIElementTypeWindow>
\<XCUIElementTypeOther>
\<XCUIElementTypeWindow>
\<XCUIElementTypeStatusBar>
\<XCUIElementTypeOther>
\<XCUIElementTypeOther>
\<XCUIElementTypeOther name="No Service">
\<XCUIElementTypeOther name="3 of 3 Wi-Fi bars">
\<XCUIElementTypeOther name="12:23">
\<XCUIElementTypeOther name="100% battery power, Charging">
Note : The .ipa file of the application was built with Xcode 7.2 but with appium i am using Xcode 9, would this be an issue ?
## Environment
iPhone 6 plus (10.3.3)- Real device, Xcode 9.0.1, Mac OS 10.13

- I am running Appium Desktop version _1.2.6_.
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
Does it not show them in the right panel?

**Comment by Nithinundercloud** [comment]
It just shows the details of the status bar on the phone. It's not able to recognise the widgets present on the app. For example in the image attached above the "Next" and "Skip" link was not recognised.

**Comment by dpgraham** [comment]
Is it a Web View? Perhaps you need to change the context.

**Comment by Nithinundercloud** [comment]
Nope this is not a web view. This is an Application but by using Appcelerator Titanium frame work.

**Comment by Nithinundercloud** [comment]
@dpgraham , Did u get a chance to look in to this ? Thanks in advance.

**Comment by dpgraham** [comment]
Yeah, just some questions

* Have you tried refreshing the source? Sometimes the source becomes stale. 
* Does the source show any of your UI components? Or is it just next and skip that are being hidden
* Can you try by using the Appium CLI too and see what happens when you make a call to get the page source on that page? 
* Have you automated Titanium Apps in the past with success?

**Comment by Nithinundercloud** [comment]
- Have you tried refreshing the source? Sometimes the source becomes stale.
        **Yes I tried doing this but, didn't find any success.**
- Does the source show any of your UI components? Or is it just next and skip that are being hidden
     **Nope apart from the details of status bar it didn't  show source of any other UI components related to the application.**
- Can you try by using the Appium CLI too and see what happens when you make a call to get the page source on that page?
     **Tried with Appium CLI it didn't work . The page source i got in my console didn't had the source of UI components. Below is the source.**
`<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name=“app” label=“app” enabled="true" visible="true" x="0" y="0" width="414" height="736">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="414" height="736">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="736">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="736">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="736">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="736">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="186" y="349" width="42" height="38">
              <XCUIElementTypeActivityIndicator type="XCUIElementTypeActivityIndicator" value="1" name="In progress" label="In progress" enabled="true" visible="true" x="186" y="349" width="37" height="38"/>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="414" height="736">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="414" height="736"/>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="414" height="736">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="true" x="0" y="0" width="414" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="414" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="No Service" label="No Service" enabled="true" visible="true" x="6" y="0" width="62" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" visible="true" x="73" y="0" width="13" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Network connection in progress" label="Network connection in progress" enabled="true" visible="true" x="92" y="0" width="10" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="17:10" label="17:10" enabled="true" visible="true" x="194" y="0" width="31" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="82% battery power, Charging" label="82% battery power, Charging" enabled="true" visible="true" x="376" y="0" width="33" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>`
     
- Have you automated Titanium Apps in the past with success?
   **Yes, for the similar application i was able to automate before. The same application for android is working fine, source was able to show the details of the UI component. This is though in windows machine.**

**Comment by dpgraham** [comment]
So it looks like it's potentially a problem with Appium and not the Appium Desktop UI. I suspect that it's an issue with Appium not having access to the contents of the app due to restrictions on the .ipa

Which steps did you follow in the real device setup guide (https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)? Did you try following the Manual steps?

**Comment by Nithinundercloud** [comment]
Yes, i have followed the steps provided in the guide. I was able to launch the sample app IntegrationApp.ipa successfully  with inspector able to obtain the  source of UI components. 

**I am using the .ipa file  built with Xcode 7.2 in my appium project. My appium setup is running on the  latest Xcode 9,signature certificate used by both the Xcode remains same. I am suspecting the mismatch between the Xcode version might be the root cause for this issue. Any thoughts ?**

**Comment by dpgraham** [comment]
It could be. @mykola-mokhnach do you have any idea?

**Comment by mykola-mokhnach** [comment]
It might be the app itself does not declare the elements inside the container as accessible, so then these are not visible to XCTest. Check https://github.com/appium/appium/issues/6517 for more details.

Closed as non Appium-related issue
