### ISSUE TITLE
Appium Desktop: the visible attribute is false for some elements on the IOS11, but it's visible

### ISSUE THREAD

**Issue by michalning** [appium/appium-desktop#345]
##Appium Desktop

I am running tests on the IOS11.0 with Appium,  but some elements can not be found. 
From the Appium desktop with  version1.2.6, I found the visible attribute is false for this elements, actually it's visible and shown on UI. I try to test on IOS10.3,  these elements' visible attribute is true.
it is much more likely that this problem is Appium Desktop issue, it can't be compatible with ISO11.0.

## Environment

- I am running Appium Desktop version _<1.2.6>_.
- I am on (pick one):
    - Mac

**Comment by deepakkg88** [comment]
Hi,
How did you launch inspector?Could you please have a look into below issue.
Thanks in advance
https://github.com/appium/appium-desktop/issues/340

**Comment by ptthuong** [comment]
@michalning is element's type XCUIElementTypeImage?

**Comment by dpgraham** [comment]
This wouldn't be an Appium Desktop issue. Appium Desktop reports the visibility status that Appium provides it.

**Comment by syedmahamood** [comment]
macOS Mojave 10.14.4
Appium Desktop 1.13.0
selenium-java 3.141.59
testng 6.14.3
java-client 6.1.0

iam also facing the same issue, although the element is visible Appium desktop shows false, can any one support on this issue. thanks
