### ISSUE TITLE
Can't spy element on confirmation popup in Chrome 

### ISSUE THREAD

**Issue by KroganUrdnot** [appium/appium-desktop#347]
## Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [V ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After filling the web form, the confirmation popup appears, i'm trying to get id of the "send invitation" button, however, the spy just looking through the popup and bringing the element under it. Taping on location does work but i prefer to get the button id instead, how to focus the spy on popup?

![image](https://user-images.githubusercontent.com/33724851/32897218-a7fdcb38-caed-11e7-8f14-a3fd91430f4e.png)

## Environment

- I am running Appium Desktop version _<1.2.6>_.
- I am on (pick one):
    - [ ] Windows

**Comment by dpgraham** [comment]
Have you tried refreshing the source? The source and what's on the screen isn't always synchronized.

**Comment by KroganUrdnot** [comment]
Sure, i tried many times, the spy just looking on page under the popup

**Comment by dpgraham** [comment]
Is the popup in a webview perhaps?
