### ISSUE TITLE
.clear() is not clearing complete text in text box.Cursor shows on end and suddenly changed to second last charecter,So last two digits of previous text remains same.

### ISSUE THREAD

**Issue by findmanish** [appium/appium-desktop#349]
Appium 1.7
Xcode 9.1
iPhone Simulator 11.1

.clear() is not clearing complete text in text box.Cursor shows on end and suddenly changed to second last charecter.
Tried with Key.CONTROL+"A" bit CONTROL changed to telephone icon
@jlipps @mykola-mokhnach

**Comment by dpgraham** [comment]
@findmanish What happens if you call clear a second time?
