### ISSUE TITLE
Unable to start Inspector session in Appium Desktop 1.2.6 

### ISSUE THREAD

**Issue by paragmangal** [appium/appium-desktop#351]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I started the Appium default server. Started Android emulator with device Nexus_5X_API_24.
Now I want to start an Inspector system with already running server & capabilities as

{
  "platformName": "Android",
  "platformVersion": "7.0",
  "deviceName": "Nexus_5X_API_24:5554",
  "appActivity": ".Settings",
  "appPackage": "com.android.calculator2",
  "name": "Ruby Appium Android example"
  "noReset": true
}

It is giving error every time. Some of the errors are

- Error
An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: activity and pkg is required for launching application

- Error
An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

## Environment

- I am running Appium Desktop version _<1.2.6>_.
- I am on (pick one):
    -  Windows

**Comment by dpgraham** [comment]
Can you provide the Appium server logs?

**Comment by paragmangal** [comment]
Hi @dpgraham 
Thanks for Help :+1:  :smile: 
I was not giving 'appActivity' capability correctly

for calculator it is 'com.android.calculator2.Calculator'

Now it is working absolutely fine.

**Comment by dpgraham** [comment]
@bangyApp Can you open a new issue and provide more details (logs, screenshots, etc...)

**Comment by aditigarg0120** [comment]
I am getting an error - Original error: Could not find package "package name" on the device.
running appium desktop app with emulator -
{
  "deviceName": "Nexus 6P API 28",
  "appPath": "E:\\app-debug.apk",
  "appActivity": "activityname",
  "appPackage": "packagename",
  "platformName": "Android",
  "skipUnlock": true,
  "noReset": false
}

when clicked on start session it is showing package could not be found

appium log - 
[AndroidDriver] Error: Could not find package on the device
[AndroidDriver]     at Object.wrappedLogger.errorAndThrow (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-support\lib\logging.js:78:13)
[AndroidDriver]     at AndroidDriver.checkPackagePresent (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-android-driver\lib\driver.js:377:11)
[AndroidDriver]     at process._tickCallback (internal/process/next_tick.js:68:7)
[AndroidDriver] Shutting down Android driver

Earlier everything was working fine. Suddenly appium stopped working on emulators.
One emulator got crashed between this, have tried with another emulator but no result.

Please help
