### ISSUE TITLE
Error with no description

### ISSUE THREAD

**Issue by Unaserme** [appium/appium-desktop#352]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hello there,

I have upgrade Appium desktop to version 1.2.7.
I have Appium with version 1.7.1.
I have XCode 9.

I recently try (with no success for now), to run appium's action on fastlane, so I have change a lot of things, even re-install Appium
When I run appium-doctor iO, its says everything is fine "AppiumDoctor Everything looks good, bye!"

I run Appium desktop, I start server v1.7.1 (with simple parameters).
"The server is running
[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723"

I try to create a new session window with some capabilities: 
"{
  "platformName": "iOS",
  "deviceName": "iPhone Simulator",
  "platformVersion": "11.0",
  "app": "[path to the app]"
}"

Theses capabilities used to work before.
Now, when I press the "start session" button, I get an "Error: Could not start session" with no log on the server's screen.

I have no idea of what happened, and error is not really helpful.

Is there something I do wrong ?

## Environment

- I am running Appium Desktop version 1.2.7.
- I am on (pick one):
    - [X] Mac

**Comment by dpgraham** [comment]
Sorry for the late response.

The server logs show more detailed info. Are you using a newer XCode that has platformVersion > 11?
