### ISSUE TITLE
Xcode9.1+IOS 11.1.2+APPIUM1.2.7 runtime throws exceptions,'11.1.2'does not exist in the list of simctl SDKs

### ISSUE THREAD

**Issue by chenzheng102** [appium/appium-desktop#353]
Running environment:
1.Xcode 9.1
2.IOS 11.1.2
3.mac 10.12.6
4.appiuappium-desktop 1.2.7

Throw exception:
An unknown server-side error occurred while processing the command. Original error: 11.1,8.4'11.1.2'does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on system: your

I found a lot of information, did not find a good way to solve, trouble God to help answer, thank you

**Comment by imurchie** [comment]
Try just using `11.1` as the `platformVersion`.
