### ISSUE TITLE
appium 1.7.1  cannot work use driver.findElement(By.name())

### ISSUE THREAD

**Issue by jobgirl** [appium/appium-desktop#354]
environment
mac 10.1
ios 11.1
appium 1.7.1
appium-desktop  1.2.7

## The problem

when i use driver.findElement(By.name()).click,always prompt org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

i used the same cases on appium 1.6.5 ,this work fine.but after update,it cannot work.

**Comment by VTINFOJames** [comment]
I am able to use driver.findElementByName().click().

**Comment by dpgraham** [comment]
@jobgirl You need to pass a name string into `By.name()`
