### ISSUE TITLE
Appium IOS responsive web sending driver.clear() unwontedly before send_keys and click methods

### ISSUE THREAD

**Issue by ola-dazn** [appium/appium-desktop#355]
## Description

When I send the send_keys or click commands to a text field, appium sends an unwonted driver.clear() command without this command being in the code!! This causes the scrip to fail. I had to analyse the logs to figure what exactly was going on. This behaviour is very peculiar as it has only just begun, I updated to the latest versions of IOS, Appium and Xcode and still the issues persist. I have tested on both Appium desktop and CLI. I ran the test on android responsive web and the unwonted driver.clear() command is not sent, meaning the issue lies with IOS, or maybe safari browser, who knows? I've included a snipped of the log files below where the first driver.clear() command is sent. There is no driver.clear() commands in the code.

## Environment

- Appium Desktop 1.7.1 
- Appium CLI 1.7.1
- MAC 10.12.6
- IOS 11.1.2

## Log
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":104}'
[debug] [RemoteDebugger] Found handler for message '104'
[debug] [RemoteDebugger] Received result for atom 'get_attribute_value' execution: null
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: null
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5048/attribute/readOnly 200 47 ms - 76 
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5048/clear {"{}":""}
[debug] [MJSONWP] Calling AppiumDriver.clear() with args: ["5048","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'clear'
[debug] [RemoteDebugger] Executing 'clear' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":105}'
[debug] [RemoteDebugger] Found handler for message '105'
[debug] [RemoteDebugger] Received result for atom 'clear' execution: null
[debug] [MJSONWP] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5048/clear 200 104 ms - 76 
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5048/value {"value":["ola.camelot1+1@gmail.com"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["ola.camelot1+1@gmail.com"],"5048","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":106}'
[debug] [RemoteDebugger] Found handler for message '106'
[debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [RemoteDebugger] Executing 'type' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":107}'
[debug] [RemoteDebugger] Found handler for message '107'
[debug] [RemoteDebugger] Received result for atom 'type' execution: null
[debug] [MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5048/value 200 224 ms - 76 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element {"using":"xpath","value":".//input[(not(@type) or (translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"file\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"radio\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"checkbox\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"submit\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"reset\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"image\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"button\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"hidden\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"range\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"color\")) and @name='password']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath",".//input[(not(@type) or (translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"file\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"radio\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"checkbox\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"submit\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"reset\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"image\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"button\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"hidden\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"range\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"color\")) and @name='password']","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1511955100256\"}}"},"wasThrown":false},"id":108}'
[debug] [RemoteDebugger] Found handler for message '108'
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1511955100256"}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5049"}
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element 200 136 ms - 90 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled {}
[debug] [MJSONWP] Calling AppiumDriver.elementEnabled() with args: ["5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'elementEnabled'
[debug] [RemoteDebugger] Executing 'is_enabled' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":true}"},"wasThrown":false},"id":109}'
[debug] [RemoteDebugger] Found handler for message '109'
[debug] [RemoteDebugger] Received result for atom 'is_enabled' execution: true
[debug] [MJSONWP] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled 200 58 ms - 76 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled {}
[debug] [MJSONWP] Calling AppiumDriver.elementEnabled() with args: ["5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'elementEnabled'
[debug] [RemoteDebugger] Executing 'is_enabled' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":true}"},"wasThrown":false},"id":110}'
[debug] [RemoteDebugger] Found handler for message '110'
[debug] [RemoteDebugger] Received result for atom 'is_enabled' execution: true
[debug] [MJSONWP] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled 200 18 ms - 76 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled {}
[debug] [MJSONWP] Calling AppiumDriver.elementEnabled() with args: ["5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'elementEnabled'
[debug] [RemoteDebugger] Executing 'is_enabled' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":true}"},"wasThrown":false},"id":111}'
[debug] [RemoteDebugger] Found handler for message '111'
[debug] [RemoteDebugger] Received result for atom 'is_enabled' execution: true
[debug] [MJSONWP] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled 200 60 ms - 76 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled {}
[debug] [MJSONWP] Calling AppiumDriver.elementEnabled() with args: ["5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'elementEnabled'
[debug] [RemoteDebugger] Executing 'is_enabled' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":true}"},"wasThrown":false},"id":112}'
[debug] [RemoteDebugger] Found handler for message '112'
[debug] [RemoteDebugger] Received result for atom 'is_enabled' execution: true
[debug] [MJSONWP] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/enabled 200 30 ms - 76 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/attribute/readOnly {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["readOnly","5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'getAttribute'
[debug] [RemoteDebugger] Executing 'get_attribute_value' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":113}'
[debug] [RemoteDebugger] Found handler for message '113'
[debug] [RemoteDebugger] Received result for atom 'get_attribute_value' execution: null
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: null
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/attribute/readOnly 200 78 ms - 76 
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/clear {"{}":""}
[debug] [MJSONWP] Calling AppiumDriver.clear() with args: ["5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'clear'
[debug] [RemoteDebugger] Executing 'clear' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":114}'
[debug] [RemoteDebugger] Found handler for message '114'
[debug] [RemoteDebugger] Received result for atom 'clear' execution: null
[debug] [MJSONWP] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/clear 200 101 ms - 76 
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/value {"value":["q1234"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["q1234"],"5049","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":115}'
[debug] [RemoteDebugger] Found handler for message '115'
[debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [RemoteDebugger] Executing 'type' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":116}'
[debug] [RemoteDebugger] Found handler for message '116'
[debug] [RemoteDebugger] Received result for atom 'type' execution: null
[debug] [MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5049/value 200 176 ms - 76 
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element {"using":"xpath","value":".//input[(not(@type) or (translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"file\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"radio\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"checkbox\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"submit\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"reset\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"image\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"button\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"hidden\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"range\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"color\")) and @name='email']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath",".//input[(not(@type) or (translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"file\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"radio\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"checkbox\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"submit\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"reset\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"image\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"button\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"hidden\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"range\" and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')!=\"color\")) and @name='email']","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1511955100255\"}}"},"wasThrown":false},"id":117}'
[debug] [RemoteDebugger] Found handler for message '117'
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1511955100255"}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5050"}
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element 200 92 ms - 90 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5050/enabled {}
[debug] [MJSONWP] Calling AppiumDriver.elementEnabled() with args: ["5050","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'elementEnabled'
[debug] [RemoteDebugger] Executing 'is_enabled' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":true}"},"wasThrown":false},"id":118}'
[debug] [RemoteDebugger] Found handler for message '118'
[debug] [RemoteDebugger] Received result for atom 'is_enabled' execution: true
[debug] [MJSONWP] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5050/enabled 200 41 ms - 76 
[HTTP] --> GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5050/enabled {}
[debug] [MJSONWP] Calling AppiumDriver.elementEnabled() with args: ["5050","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'elementEnabled'
[debug] [RemoteDebugger] Executing 'is_enabled' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":true}"},"wasThrown":false},"id":119}'
[debug] [RemoteDebugger] Found handler for message '119'
[debug] [RemoteDebugger] Received result for atom 'is_enabled' execution: true
[debug] [MJSONWP] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5050/enabled 200 47 ms - 76 
[HTTP] --> POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5050/click {"{}":""}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["5050","05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"},"wasThrown":false},"id":120}'
[debug] [RemoteDebugger] Found handler for message '120'
[debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [MJSONWP] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81/element/5050/click 200 146 ms - 76 
[HTTP] --> DELETE /wd/hub/session/05bd51a3-7994-49ab-80ae-31252ba58b81 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["05bd51a3-7994-49ab-80ae-31252ba58b81"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1511955151552 (11:32:31 GMT+0000 (GMT))
[Appium] Removing session 05bd51a3-7994-49ab-80ae-31252ba58b81 from our master session list
[debug] [JSONWP Proxy] Proxying [DELETE /session/05bd51a3-7994-49ab-80ae-31252ba58b81] to [DELETE http://localhost:8100/session/FF8E9565-3825-4281-8DA0-B152EC5EAF09] with no body

**Comment by ola-dazn** [comment]
Hi @imurchie 

Have you had a chance to look into this issue yet?

**Comment by dpgraham** [comment]
Try again with latest.
