### ISSUE TITLE
Recorded swipe code for wd.js has some errors.

### ISSUE THREAD

**Issue by darceye** [appium/appium-desktop#356]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Platform is android.
The generated swipe code is: 
```js
const wd = require('wd');
const driver = wd.promiseChainRemote("localhost", 4723);
const caps = {"platformName":"android","deviceName":"myphone","app":"C:\\myapp.apk","browserName":""};

async function main () {
  await driver.init(caps);
  await (new TouchAction(driver))
    .press({x: 372, y: 251})
    .moveTo({x: -13: y: -84})
    .release()
    .perform()
  await driver.quit();
}

main().catch(console.log);
```
2 errors in recorded swipe code:
* `moveTo({x: -13: y: -84})` should be `moveTo({x: -13, y: -84})` 
* `await (new TouchAction(driver))` should be `await (new wd.TouchAction(driver))`

## Environment

- I am running Appium Desktop version _v1.7.1_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Thanks for reporting these.
