### ISSUE TITLE
Appium-Desktop Inspector error for location alert

### ISSUE THREAD

**Issue by VTINFOJames** [appium/appium-desktop#357]
Location alert causes inspector to bomb.

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I push the native app to a real device in Xcode. I try to inspect the app with the Appium-Desktop inspector and the utility will display the screen showing the location alert but the page source cannot be retrieved due to the following error:

> App Source
> Could not obtain source: {"cause":{"sessionId":"0403f9fa-f531-42f9-8f09-48287245cd00","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application"}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot get '(null)' source of the current application","status":13}

## Environment

- I am running Appium Desktop version 1.27.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux
Xcode 9.1
IOS 10.3.3 or 11.1 (real device, native app)

**Comment by VTINFOJames** [comment]
The older Appium desktop app inspector would show the location alert (iOS 8, 9).

**Comment by mojojojo94** [comment]
facing similar issue.

**Comment by dpgraham** [comment]
Do either of you have the Appium server logs for this?

**Comment by mojojojo94** [comment]
Yes I have more detailed information, with appium server logs gist over here:
https://github.com/appium/appium-desktop/issues/371

**Comment by VTINFOJames** [comment]
I just tried this again to get the log but it worked this time. I am now on iOS 11.2.1, Mac OS High Sierra (was on Sierra previously) and still using Appium-Desktop 1.2.7.
![ios_location_alert](https://user-images.githubusercontent.com/13648051/34570720-a0a4849e-f13a-11e7-900a-072231311817.jpg)

**Comment by VTINFOJames** [comment]
Actually... There is another change to my environment. I just remembered that I had downloaded the new FacebookWebDriver work around for the getPageSource() timeout issues. See my comments [Here](https://github.com/facebook/WebDriverAgent/issues/711).

**Comment by dpgraham** [comment]
@VTINFOJames Yes, I remember that. That was a major issue for IOS. I'll close this now.
