### ISSUE TITLE
appium version 1.2.7, serverV1.7.1 is force closing, kindly give the solution or ways to fix it

### ISSUE THREAD

**Issue by VegetaSama26** [appium/appium-desktop#360]
## Appium or Appium Desktop?

Appium desktop

- [ Yes] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I was trying to start the appium serverV1.7.1 and the moment i click on start server, appium GUI crashes every time but if i try on older version say 1.4 it works fine. After clicking on start server even without changing any setting appium is force closing. 
Refer the screenshot below
![33620084-e0d833f2-da0c-11e7-8764-36ecfad14fe8](https://user-images.githubusercontent.com/34246012/33643434-184bba22-da65-11e7-8b55-d42885aba534.png)
![33620082-e09e24aa-da0c-11e7-8272-65ee187f2bacds](https://user-images.githubusercontent.com/34246012/33643435-188c8b06-da65-11e7-9d0e-21af301bdc14.png)

## Environment

- I am running Appium Desktop version _<V1.7.1>_.
- I am on (pick one):
    - [ ] Mac
    - [Yes] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
@VegetaSama26 Have you tried with older verisons of Appium Desktop to see if this issue is happening on older versions? Also, can you try opening the application logs, they should be located at `%USERPROFILE%\AppData\Roaming\Appium Desktop\log.log`

**Comment by VegetaSama26** [comment]
@dpgraham i am using older version V1.4.16,1 which is working fine, but when while trying to use "scrollTo" method i was facing error so someone recommends me to use the latest version appium server then u know the problem its getting force close.
The path u have given, %USERPROFILE%\AppData\Roaming\Appium Desktop\log.log, in my desktop no such file is coming, but i did search 'log' in my appium folder and found several files, uploading 1 for same, see if it helps.
[manifest-merger-debug-report.txt](https://github.com/appium/appium-desktop/files/1548710/manifest-merger-debug-report.txt)

**Comment by VegetaSama26** [comment]
@dpgraham sir, kindly give me the solution, my work has been stuck for almost 2 weeks, also sometimes i face this error prior to force close of GUI
![untitled](https://user-images.githubusercontent.com/34246012/34077030-01b16cb4-e31e-11e7-8bbc-5d41eb08bc38.png)

**Comment by dpgraham** [comment]
Try running Appium v1.7.1 from the command line interface instead of from the UI and then start sessions by clicking `File -> New Session Window` and pointing your session to the CLI running instance.

**Comment by zhangjian321** [comment]
I have encountered this problem many times. Don't know what to do

**Comment by dpgraham** [comment]
@zhangjian321 Try running Appium from the command line instead of from Appium Desktop and starting new sessions from the GUI.

**Comment by dpgraham** [comment]
To the people having the issues, can you try looking at the logs: `%USERPROFILE%\AppData\Roaming\<app name>\log.log` (app name should be Appium or Appium Desktop) after a crash occurs?

**Comment by zhangjian321** [comment]
I have tried, but I did't find this log file in the path. @dpgraham

**Comment by dpgraham** [comment]
Let me know if this still happens for anyone and I'll re-open.
