### ISSUE TITLE
Can't inspect popup views on iOS device

### ISSUE THREAD

**Issue by alexsunder** [appium/appium-desktop#362]
Appium Desktop

## The problem

I'm trying to inspect elements with the Appium desktop in an iOS hybrid app. After pressing the Log In button, there is a popup alert is shown. I can't see the Cancel and Continue buttons in the Appium desktop.
<img width="1063" alt="screen shot 2017-12-11 at 14 20 54" src="https://user-images.githubusercontent.com/7252251/33826620-0515a788-de7f-11e7-939a-335cd0d7c422.png">

## Environment
    - [+] Mac
    - [+] Appium desktop 1.2.7
    - [+] iPhone 7, iOS 11

**Comment by dpgraham** [comment]
Have you tried refreshing the source?

**Comment by alexsunder** [comment]
yes sure. still not working. it highlighting the whole screen and I can't navigate to the popup

**Comment by alexsunder** [comment]
and probably this is another thing - it seems that it doesn't switch contexts to inspect webviews (should it switch itself?)

**Comment by dpgraham** [comment]
Appium Desktop doesn't switch contexts.

**Comment by mojojojo94** [comment]
Facing similar issue.

**Comment by damitas** [comment]
This is an ongoing issue for us too.  We managed to work out that all <View> need testIDs and styles need a width and height.

in your screenshot i can see "Ecwid". What we do is find that testID/name then trace down its children Views adding testIDs, widths and heights. 

No idea what the best/common practice is, but this has worked for us so far.

hth

**Comment by sidarakeo** [comment]
I'm also facing can't inspect Popover in the native app too.
