### ISSUE TITLE
Appium 1.7 , Error getting device platform version on android for more than 100+ test cases

### ISSUE THREAD

**Issue by PrasadMadge** [appium/appium-desktop#365]
## The problem
Error getting device platform version on android for more than 100+ test cases executing in parallel?

## Environment

- I am running Appium Desktop version _1.7.1
- I am on (pick one):
    - [ ] Windows
Java client : 5
Android device : 6.0.1 version

`[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.phonepe.app","appActivity":"com.phonepe.app.ui.activity.Navigator_MainActivity","acceptSslCerts":true,"noReset":"true","newCommandTimeout":"1800","platformVersion":"6.0.1","loggingPrefs":{"driver":"SEVERE"},"automationName":"uiautomator2","udid":"df7cc4df","platformName":"Android","deviceName":"Moto","systemPort":"47374"},{},{"desiredCapabilities":{"appPackage":"com.phonepe.app","appActivity":"com.phonepe.app.ui.activity.Navigator_MainActivity","acceptSslCerts":true,"noReset":"true","newCommandTimeout":"1800","platformVersion":"6.0.1","loggingPrefs":{"driver":"SEVERE"},"automationName":"uiautomator2","udid":"df7cc4df","platformName":"Android","deviceName":"Moto","systemPort":"47374"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}]
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [BaseDriver] Event 'newSessionRequested' logged at 1513133474691 (08:21:14 GMT+0530 (India Standard Time))
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium] Capabilities:
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   appPackage: 'com.phonepe.app'
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   appActivity: 'com.phonepe.app.ui.activity.Navigator_MainActivity'
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   acceptSslCerts: true
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   noReset: 'true'
[DEBUG] 2017-12-13 08:21:14,691 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   newCommandTimeout: '1800'
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   platformVersion: '6.0.1'
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   loggingPrefs: { driver: 'SEVERE' }
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   automationName: 'uiautomator2'
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   udid: 'df7cc4df'
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   platformName: 'Android'
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   deviceName: 'Moto'
[DEBUG] 2017-12-13 08:21:14,692 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   systemPort: '47374'
[DEBUG] 2017-12-13 08:21:14,693 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[DEBUG] 2017-12-13 08:21:14,693 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] Capability 'newCommandTimeout' changed from string ('1800') to integer (1800). This may cause unexpected behavior
[DEBUG] 2017-12-13 08:21:14,694 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] The following capabilities were provided, but are not recognized by appium: acceptSslCerts, loggingPrefs, systemPort.
[DEBUG] 2017-12-13 08:21:14,694 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] Session created with session id: 34c4888a-5247-4509-8b15-474073191d8e
[DEBUG] 2017-12-13 08:21:14,695 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [AndroidDriver] Getting Java version
[DEBUG] 2017-12-13 08:21:14,767 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] Java version is: 1.8.0_51
[DEBUG] 2017-12-13 08:21:14,767 com.qklab.appium.Initiator$1 run - APPIUM: 
[DEBUG] 2017-12-13 08:21:14,768 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Checking whether adb is present
[DEBUG] 2017-12-13 08:21:14,769 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Using adb.exe from D:\android-sdk\platform-tools\adb.exe
[DEBUG] 2017-12-13 08:21:14,769 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] Retrieving device list
[DEBUG] 2017-12-13 08:21:14,769 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Trying to find a connected android device
[DEBUG] 2017-12-13 08:21:14,769 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Getting connected devices...
[DEBUG] 2017-12-13 08:21:14,787 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] 2 device(s) connected
[DEBUG] 2017-12-13 08:21:14,787 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] Using device: df7cc4df
[DEBUG] 2017-12-13 08:21:14,787 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Checking whether adb is present
[DEBUG] 2017-12-13 08:21:14,788 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Using adb.exe from D:\android-sdk\platform-tools\adb.exe
[DEBUG] 2017-12-13 08:21:14,788 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Setting device id to df7cc4df
[DEBUG] 2017-12-13 08:21:14,788 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] No app sent in, not parsing package/activity
[DEBUG] 2017-12-13 08:21:14,788 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Getting device platform version
[DEBUG] 2017-12-13 08:21:14,788 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Getting connected devices...
[DEBUG] 2017-12-13 08:21:14,806 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] 2 device(s) connected
[DEBUG] 2017-12-13 08:21:14,806 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","getprop","ro.build.version.release"]
[DEBUG] 2017-12-13 08:21:34,809 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","getprop","ro.build.version.release"]
[DEBUG] 2017-12-13 08:21:54,811 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s df7cc4df shell getprop ro.build.version.release' timed out after 20000ms'; Stderr: ''; Code: 'null'
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:76:9)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at tryCatch (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at <anonymous>
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:  Error: **Error getting device platform version.** Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s df7cc4df shell getprop ro.build.version.release' timed out after 20000ms'; Stderr: ''; Code: 'null'
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:76:9)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at tryCatch (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM:     at <anonymous>
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [UiAutomator2] Deleting UiAutomator2 session
[DEBUG] 2017-12-13 08:21:54,812 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Getting connected devices...
[DEBUG] 2017-12-13 08:21:54,831 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] 2 device(s) connected
[DEBUG] 2017-12-13 08:21:54,831 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","am","force-stop","com.phonepe.app"]
[DEBUG] 2017-12-13 08:22:14,833 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","am","force-stop","com.phonepe.app"]
[DEBUG] 2017-12-13 08:22:30,674 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:47374/wd/hub/status] with no body
[DEBUG] 2017-12-13 08:22:34,836 com.qklab.appium.Initiator$1 run - APPIUM: [UiAutomator2] Unable to force stop app: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s df7cc4df shell am force-stop com.phonepe.app' timed out after 20000ms'; Stderr: ''; Code: 'null'
[DEBUG] 2017-12-13 08:22:34,836 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Removing forwarded port socket connection: 47374 
[DEBUG] 2017-12-13 08:22:34,836 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","forward","--remove","tcp:47374"]
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM: [MJSONWP] Encountered internal error running command: **Error: Error getting device platform version**. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s df7cc4df shell getprop ro.build.version.release' timed out after 20000ms'; Stderr: ''; Code: 'null'
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:76:9)
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at tryCatch (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[DEBUG] 2017-12-13 08:22:34,855 com.qklab.appium.Initiator$1 run - APPIUM:     at <anonymous>
[DEBUG] 2017-12-13 08:22:34,857 com.qklab.appium.Initiator$1 run - APPIUM: [HTTP] <-- POST /wd/hub/session 500 80163 ms - 402 
[DEBUG] 2017-12-13 08:22:35,323 com.qklab.appium.Initiator$1 run - APPIUM: [HTTP] --> GET /wd/hub/status {}
[DEBUG] 2017-12-13 08:22:35,323 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[DEBUG] 2017-12-13 08:22:35,324 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
[DEBUG] 2017-12-13 08:22:35,325 com.qklab.appium.Initiator$1 run - APPIUM: [HTTP] <-- GET /wd/hub/status 200 2 ms - 83 
[DEBUG] 2017-12-13 08:22:35,351 com.qklab.appium.Initiator$1 run - APPIUM: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.phonepe.app","appActivity":"com.phonepe.app.ui.activity.Navigator_MainActivity","acceptSslCerts":true,"noReset":"true","newCommandTimeout":"1800","platformVersion":"6.0.1","loggingPrefs":{"driver":"SEVERE"},"automationName":"uiautomator2","udid":"df7cc4df","platformName":"Android","deviceName":"Moto","systemPort":"47374"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"appPackage":"com.phonepe.app","appActivity":"com.phonepe.app.ui.activity.Navigator_MainActivity","acceptSslCerts":true,"noReset":"true","newCommandTimeout":"1800","platformVersion":"6.0.1","loggingPrefs":{"driver":"SEVERE"},"automationName":"uiautomator2","udid":"df7cc4df","platformName":"Android","deviceName":"Moto","systemPort":"47374"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}}
[DEBUG] 2017-12-13 08:22:35,351 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.phonepe.app","appActivity":"com.phonepe.app.ui.activity.Navigator_MainActivity","acceptSslCerts":true,"noReset":"true","newCommandTimeout":"1800","platformVersion":"6.0.1","loggingPrefs":{"driver":"SEVERE"},"automationName":"uiautomator2","udid":"df7cc4df","platformName":"Android","deviceName":"Moto","systemPort":"47374"},{},{"desiredCapabilities":{"appPackage":"com.phonepe.app","appActivity":"com.phonepe.app.ui.activity.Navigator_MainActivity","acceptSslCerts":true,"noReset":"true","newCommandTimeout":"1800","platformVersion":"6.0.1","loggingPrefs":{"driver":"SEVERE"},"automationName":"uiautomator2","udid":"df7cc4df","platformName":"Android","deviceName":"Moto","systemPort":"47374"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}]
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [BaseDriver] Event 'newSessionRequested' logged at 1513133555353 (08:22:35 GMT+0530 (India Standard Time))
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium] Capabilities:
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   appPackage: 'com.phonepe.app'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   appActivity: 'com.phonepe.app.ui.activity.Navigator_MainActivity'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   acceptSslCerts: true
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   noReset: 'true'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   newCommandTimeout: '1800'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   platformVersion: '6.0.1'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   loggingPrefs: { driver: 'SEVERE' }
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   automationName: 'uiautomator2'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   udid: 'df7cc4df'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   platformName: 'Android'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   deviceName: 'Moto'
[DEBUG] 2017-12-13 08:22:35,352 com.qklab.appium.Initiator$1 run - APPIUM: [Appium]   systemPort: '47374'
[DEBUG] 2017-12-13 08:22:35,353 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[DEBUG] 2017-12-13 08:22:35,353 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] Capability 'newCommandTimeout' changed from string ('1800') to integer (1800). This may cause unexpected behavior
[DEBUG] 2017-12-13 08:22:35,354 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] The following capabilities were provided, but are not recognized by appium: acceptSslCerts, loggingPrefs, systemPort.
[DEBUG] 2017-12-13 08:22:35,354 com.qklab.appium.Initiator$1 run - APPIUM: [BaseDriver] Session created with session id: d51f8b39-823d-40b2-908c-5dffaaf96852
[DEBUG] 2017-12-13 08:22:35,354 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [AndroidDriver] Getting Java version
[DEBUG] 2017-12-13 08:22:35,426 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] Java version is: 1.8.0_51
[DEBUG] 2017-12-13 08:22:35,426 com.qklab.appium.Initiator$1 run - APPIUM: 
[DEBUG] 2017-12-13 08:22:35,426 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Checking whether adb is present
[DEBUG] 2017-12-13 08:22:35,427 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Using adb.exe from D:\android-sdk\platform-tools\adb.exe
[DEBUG] 2017-12-13 08:22:35,427 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] Retrieving device list
[DEBUG] 2017-12-13 08:22:35,427 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Trying to find a connected android device
[DEBUG] 2017-12-13 08:22:35,427 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Getting connected devices...
[DEBUG] 2017-12-13 08:22:35,445 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] 2 device(s) connected
[DEBUG] 2017-12-13 08:22:35,445 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] Using device: df7cc4df
[DEBUG] 2017-12-13 08:22:35,445 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Checking whether adb is present
[DEBUG] 2017-12-13 08:22:35,447 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Using adb.exe from D:\android-sdk\platform-tools\adb.exe
[DEBUG] 2017-12-13 08:22:35,447 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Setting device id to df7cc4df
[DEBUG] 2017-12-13 08:22:35,447 com.qklab.appium.Initiator$1 run - APPIUM: [AndroidDriver] No app sent in, not parsing package/activity
[DEBUG] 2017-12-13 08:22:35,447 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Getting device platform version
[DEBUG] 2017-12-13 08:22:35,447 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Getting connected devices...
[DEBUG] 2017-12-13 08:22:35,465 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] 2 device(s) connected
[DEBUG] 2017-12-13 08:22:35,465 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","getprop","ro.build.version.release"]
[DEBUG] 2017-12-13 08:22:55,467 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","getprop","ro.build.version.release"]
[DEBUG] 2017-12-13 08:23:15,469 com.qklab.appium.Initiator$1 run - APPIUM: [ADB] Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s df7cc4df shell getprop ro.build.version.release' timed out after 20000ms'; Stderr: ''; Code: 'null'
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:76:9)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at tryCatch (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at <anonymous>
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:  Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s df7cc4df shell getprop ro.build.version.release' timed out after 20000ms'; Stderr: ''; Code: 'null'
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at ADB.callee$0$0$ (../../../lib/tools/adb-commands.js:76:9)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at tryCatch (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at GeneratorFunctionPrototype.invoke (D:\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM:     at <anonymous>
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [UiAutomator2] Deleting UiAutomator2 session
[DEBUG] 2017-12-13 08:23:15,470 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Getting connected devices...
[DEBUG] 2017-12-13 08:23:15,489 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] 2 device(s) connected
[DEBUG] 2017-12-13 08:23:15,489 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","am","force-stop","com.phonepe.app"]
[DEBUG] 2017-12-13 08:23:24,466 com.qklab.appium.Initiator$1 run - APPIUM: [debug] [ADB] Running 'D:\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","df7cc4df","shell","am","force-stop","com.phonepe.app"]
[DEBUG] 2017-12-13 08:23:24,469 com.qklab.appium.Initiator$1 run - APPIUM: [Logcat] Logcat terminated with code 3221225786, signal null`

**Comment by dpgraham** [comment]
Can you explain this more? I don't think I understand the issue.

**Comment by dpgraham** [comment]
Closing. Will re-open if more details provided.
