### ISSUE TITLE
Unable to launch App on IOS Real device using appium

### ISSUE THREAD

**Issue by alkaraghav17** [appium/appium-desktop#368]
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1570105/appium-server-logs.txt)
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1570107/appium-server-logs.txt)

[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1570105/appium-server-logs.txt)
Appium Desktop
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "EROFS: read-only file system, mkdir '/private/var/folders/8x/lyq39rgs361_qxtl2qr2xj2c0000gn/T/AppTranslocation/07199593-C214-4A87-8B6A-24016E54BEA0/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ 
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "EROFS: read-only file system, mkdir '/private/var/folders/8x/lyq39rgs361_qxtl2qr2xj2c0000gn/T/AppTranslocation/07199593-C214-4A87-8B6A-24016E54BEA0/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ 

## The problem
Whenever  i'm trying to execute the scripts it showing me this error log 

## Environment

- I am running Appium Desktop version  1.7.1
- I am on Mac 10.12.6
- Using Ios 10.3.3 on iphone 
-Xcode 8.1.1

**Comment by dpgraham** [comment]
Have you successfully run Appium on IOS Real Device using the command line and following the Real Device guide?
