### ISSUE TITLE
How to start appium-desktop in command line & how to run appium-desktop with multiple devices?

### ISSUE THREAD

**Issue by YannickXiong** [appium/appium-desktop#369]
## The problem
I am now using appium + py-client in an autoautomated test projec, while there are 2 probles I don't
know how to resolve.
   a.) who can start appium in a command line, it looks like appium desktop doesn't support command line;
   b.) who can I run appium with multiple devices(emulator devices).

## Environment

- I am on Mac

**Comment by ivanlp-p** [comment]
Hi! You need run a second copy of Appium. For this enter in terminal window 
`copy -n /Applications/Appium.app/`. This will open a second window of Appium. After that you must configure presets for different devices.

**Comment by YannickXiong** [comment]
@ivanlp-p  Thx for your replay.
For appium, I ofen used command "appium -p 4724 -bp 4734 --udid xxx" in my python script, however, for appium-desktop, doesn't support such a command "appium -p 4724 -bp 4734 --xxx", this is my actual qeustion.

**Comment by dpgraham** [comment]
You can set server flags in Appium Desktop. When you open the app click on 'Advanced' tab to see your options.

**Comment by YannickXiong** [comment]
@dpgraham Thx for replaying.
I wanna to start 2 session window in my python scription instead of starting them from the appium-desktop GUI. Do you know how to do it? Thanks a lot.

**Comment by dpgraham** [comment]
Yeah you need to install the appium CLI and run them from two different terminals

```
npm install -g appium
appium
```

**Comment by YannickXiong** [comment]
@dpgraham Thx

**Comment by yizhixiaoxiaogou** [comment]
I set  --log level to error  in Appium desktop. it's does't work. the console prints debug info;
