### ISSUE TITLE
Error message on iOS system popups in Appium Inspector

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium-desktop#371]
## Appium Desktop
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

Probably an Appium issue but I can only see it in the inspector, logs don't through an error nor it does when running just appium but test cases still fail because I cannot touch any OS system popups.

## The problem
Appium Inspector throwing error at iOS system popups, no way to interact with system popups through appium. Cannot automate, all test cases failing. Testing with different iOS versions, still see the same error, tested iOS versions: 9.3, 10.3, 11.0
![screen shot 2017-12-27 at 1 52 13 pm](https://user-images.githubusercontent.com/15100526/34391975-dc848a22-eb0e-11e7-8ee6-49e2cf46d92a.png)

Tried on iOS 11.2, I was not getting an error anymore but I did get this for system popups. It says the element cannot be interacted with, does the appium team have more insight on why a OS system alert cannot be interacted with in appium?
![screen shot 2017-12-27 at 2 15 57 pm](https://user-images.githubusercontent.com/15100526/34392260-a48be8d4-eb10-11e7-8c60-d8a3edbaf340.png)

## Environment
- I am running Appium Desktop version _Version 1.2.7 (1.2.7)_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

Can view Appium Logs here:
https://gist.github.com/mojojojo94/8a0bf3e35800b6ab578ced635e7fe1a2

**Comment by VTINFOJames** [comment]
I just tried this again to get the log but it worked this time. I am now on iOS 11.2.1, Mac OS High Sierra (was on Sierra previously) and still using Appium-Desktop 1.2.7.
![ios_location_alert](https://user-images.githubusercontent.com/13648051/34570620-5457391a-f13a-11e7-95e8-4161ecbe5b66.jpg)

**Comment by mojojojo94** [comment]
Maybe I need to update my mac OS to High Sierra as well, thank you for the info @VTINFOJames!

**Comment by VTINFOJames** [comment]
I was on iOS 11.1 and Xcode 9.1 with Sierra. So it could be any or all of the following: upgrading to High Sierra, upgrading to Xcode 9.2 with corresponding command line tools or upgrading to iOS 11.2.1.

**Comment by VTINFOJames** [comment]
Actually... I just remembered that I had downloaded the new FacebookWebDriver work arounds for the getPageSource() timeout issues [Here](https://github.com/facebook/WebDriverAgent/issues/711)

**Comment by mojojojo94** [comment]
Ok so I tested it out on 9.3, 10.3 and 11.0 and later, works only on iOS 11.0 versions and later. Does not work on iOS 9.X.X and 10.X.X versions. Will appium-desktop team look into this? @dpgraham?

**Comment by dpgraham** [comment]
It wouldn't be an Appium Desktop fix it would have to be an Appium or a WebDriverAgent fix. Is it actually breaking tests that you've written or does it just hinder your user experience.

**Comment by mojojojo94** [comment]
The test are not able to start because appium cannot interact with the iOS system popups.

**Comment by dpgraham** [comment]
Okay, this isn't an Appium Desktop issue then. You'll need to open an issue in github.com/appium/appium or go to discuss.appium.io to get assistance.

**Comment by lolotoms** [comment]
I had the same issue, 
When the popup appeared before the app was launch, I was not able to intercat with it andmy tests failed
When the popup appeared after the app was launch, I was able to interact with it, close it and my tests succed.

Finally I prefered desactivate notifications popups only for my build auto.
