### ISSUE TITLE
Appium Desktop not show Accessibility for all android devices ?

### ISSUE THREAD

**Issue by ios-dev-newbie** [appium/appium-desktop#373]
## Appium or Appium Desktop?

I am using appium desktop version 1.2.7.

## The problem

My Application is developed in cordova. Now I want to automate the UI.
I have developed a Script in Javascript and wanted to use the same script for iOS as well as Android.

But having the problem that Both devices should have same element so that I can find it and automate the Process.

I have used android Samsung edge, Samsung S6 and iPhone 6. For some element in samsung edge I can see the element as Accessibility Id but not able to see it for other element. Also I am not able to see Accessibility Id for any element in Samsung S6.

## Environment

- I am running Appium Desktop version 1.2.7.
- I am on Mac

**Comment by dpgraham** [comment]
If it's in Cordova, you should be switching to a Web Context and using Selenium selectors (CSS, ID, etc...) to be finding elements.
