### ISSUE TITLE
Appium Desktop v1.3.0 - xcodebuild failure

### ISSUE THREAD

**Issue by degamer106** [appium/appium-desktop#378]
## The problem

Just downloaded the latest version 1.3.0 and tried running a script and also launching the Inspector.  In both instances it fails with an xcodebuild error where it can't find this file:

/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h

Appium Desktopo v1.2.7 works without this issue.
Appium v.1.7.2 run via Terminal is also fine.

## Environment

- I am running Appium Desktop version 1.3.0
- I am on (pick one):
    - [x ] Mac (v10.12.16)
    - [ ] Windows
    - [ ] Linux

**Comment by sasasa42** [comment]
It is happening at my end as well

**Comment by showtime25st** [comment]
I have the same problem https://github.com/appium/appium-desktop/issues/379

**Comment by sukruk** [comment]
I have the same problem too.

**Comment by xshuRoadie** [comment]
Same here. Had to downgrade to 1.2.7

**Comment by dpgraham** [comment]
Looking into it right now. I recommend downgrading to 1.2.7 until I resolve this and release 1.3.1

**Comment by dpgraham** [comment]
Alternatively, you can run Appium from the command line and still run sessions pointing to the command line server.

**Comment by dpgraham** [comment]
v1.3.1 is released

It was a build issue. When doing the release locally I was using a newer version of `electron-builder` which seemed to cause problems. It went away when reverting back to the version we were using before. Will need to look into this some more because that could cause problems in the future.
