### ISSUE TITLE
Only .m files after update

### ISSUE THREAD

**Issue by showtime25st** [appium/appium-desktop#379]
## Appium or Appium Desktop?

Hello, dear Sir/Madam!

Today I updated the Appium desktop from 1.2.7 to 1.3.0 and could not compile WebDriverAgent https://monosnap.com/file/NcAmS5sbdVgvmyLmZD2FzVjUvbALCu error was "'FBPredicate.h' file not found". After updating, all the files with extension .h disappeared 
https://monosnap.com/file/LRCNswpoPnyYz6zKNNMGpog74FWeGV

Please help or give advice))

## Environment

- I am running Appium Desktop version _<1.3.0>_.
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
Closing as duplicate of #378
