### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by garie** [appium/appium-desktop#38]
I realize that the README will be updated when this is ready for use, but I'm struggling to figure out how to use it at all. I have it built and running and I get an electron window that looks like chrome developer tools. In the menus (Mac), I do not see any options that actually allow me to do anything like point to my app that is running in the simulator. In the javascript console, I tried using the electron API but `electron` is undefined. I'd like to try using this and make contributions but I don't even understand how it's supposed to work.

To be clear, I'm attempting to use the Inspector. If there's another way I'm supposed to run that, let me know.

I installed and linked appium's npm as indicated and am running the process with `npm run dev` rather than the release version because it would not build for me. I will investigate that issue if I can get it working at all.

**Comment by jlipps** [comment]
Please try downloading a built package from https://github.com/appium/appium-desktop/releases instead. Hopefully it should be more apparent what's going on.
