### ISSUE TITLE
Appium Desktop not catching Appium exceptions

### ISSUE THREAD

**Issue by ios-dev-newbie** [appium/appium-desktop#381]
## Appium or Appium Desktop?

I want to write appium server log at custom location by using appium desktop. How I can acheive that?

## The problem
I have tried to put --log /folderpath/appium.log in a AppiumDesktop -> Advanced -> Logfile path location. But once i put it there appium crashed.

Please help me to get the appium server log in a custom file location.

## Environment

- I am running Appium Desktop version 1.3.0.
- I am on (pick one):
    - Mac OS 10.12.6 
   
![screen shot 2018-01-12 at 4 52 33 pm](https://user-images.githubusercontent.com/35054947/34872975-30714fd8-f7b9-11e7-9667-ebdc3057c3b0.png)
![screen shot 2018-01-12 at 4 47 29 pm](https://user-images.githubusercontent.com/35054947/34872976-3408fc18-f7b9-11e7-9a5f-eb00e94044ea.png)

**Comment by dpgraham** [comment]
Do you mind sharing the logs with me? I'd like to see _why_ it crashed.

**Comment by ios-dev-newbie** [comment]
[info] [Appium] Welcome to Appium v1.7.2
[info] [Appium] Non-default server args:
[info] [Appium]   sessionOverride: true
[info] [Appium]   log: --log /Users/myHome/Log/appium.log
[info] [Appium]   logTimestamp: true
[info] [Appium]   localTimezone: true
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723

After above log appium desktop app crashed.

**Comment by dpgraham** [comment]
Thanks for reporting this. I was able to reproduce it on my side.

I think you need to change `Logfile Path` from `--log /Users/myHome/Log/appium.log` to `/Users/myHome/Log/appium.log`.

What the underlying problem is, though, is that the Appium Desktop UI isn't catching Appium exceptions and then reporting them to the user. Instead, it just throws the exception and the application crashes.

Should be an easy fix. Until then just try the above workaround

**Comment by ArikunthaTamil** [comment]
@dpgraham where can I update the log path?

**Comment by dpgraham** [comment]
@ArikunthaTamil In `Logfile Path` under `General` (see screenshot above)

**Comment by dpgraham** [comment]
Closed as resolved.

**Comment by djangofan** [comment]
Screenshot above is now out of date.  New Appium UI no longer allows you to set log path.  Anyone know why that was removed?
