### ISSUE TITLE
[iOS] Can't receive screen hierarchy via Inspector when UIDataPicker is opened.

### ISSUE THREAD

**Issue by denysvoskovets** [appium/appium-desktop#382]
## The problem
Can't receive screen hierarchy via Inspector when UIDataPicker is opened. After pressing "Take a screenshot" button, Inspector is starting to load without any result for long period of time. 
If I try to take screen hierarchy with closed UIDataPicker -> all works fine.
Thank You

## Environment

- I am running Appium Desktop version _<1.3.1 & 1.2.7>_.
- I am on (pick one): Mac Sierra 10.12.6 

Logs from Appium. 
https://gist.github.com/denysvoskovets/de05f6f6dd87345920a3880f9aedfefd

**Comment by showtime25st** [comment]
I couldn't find any element via inspector, tried to use different strategies.

**Comment by denysvoskovets** [comment]
@showtime25st  For me it works. 
But it doesn't work in described scenario.

**Comment by dpgraham** [comment]
If this is still an issue, I'll re-open.
