### ISSUE TITLE
Appium Desktop not showing UI elements for Ionic Apps

### ISSUE THREAD

**Issue by zac11** [appium/appium-desktop#385]
## Appium or Appium Desktop?

- [Y ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When trying to open Appium Desktop for Ionic Apk, the UI Element locator stucks at the loading screen.

_Replace this section with a description of your issue_

I am trying to automate an ionic apk. To locate the UI Elements, I've installed Appium 1.7.2. However when trying to load the `.apk` with the following capabilities, the UI Element locator screen just gets stuck at the loading screen.

![screen shot 2018-01-14 at 9 10 02 pm](https://user-images.githubusercontent.com/8002297/34918652-0a4b88f4-f97c-11e7-8c1f-015b8625ad34.png)

I have encountered this with multiple ionic apps. One of the example `.apk` can be found here -
https://apkpure.com/constantine-ionic-demo/com.ionicframework.constantine199683

The `.apk` opens perfectly fine in the Emulator, which is the target device in this case.

![screen shot 2018-01-14 at 9 10 17 pm](https://user-images.githubusercontent.com/8002297/34918655-126c79c6-f97c-11e7-95fe-408a84572629.png)

My capabilities are 

`{
  "app": "/Users/zac/Downloads/Demo_ionic.apk",
  "platformName": "Android",
  "platformVersion": "8",
  "deviceName": "Pixel 2 XL"
}`

## Environment

- I am running Appium Desktop version _<1.7.2>_.
- I am on (pick one):
    - [A] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by zac11** [comment]
Closing this issue as I learnt that we view elements are not shown in appointed desktop

**Comment by Shahrukhk999** [comment]
@zac11 can you elaborate your solution?
