### ISSUE TITLE
"Appium has stopped working" on desktop version 1.3.1

### ISSUE THREAD

**Issue by jameseg3** [appium/appium-desktop#391]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

"Appium has stopped working" message after opening appium from desktop and clicking the "Start Server v1.7.2" button. (I've never gotten past this opening screen)

## Environment

- I am running Appium Desktop version 1.3.1.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
@jameseg3 Do you have this problem with old versions of Appium Desktop?

**Comment by jameseg3** [comment]
No I actually got it to work after cleansing my machine of all my node and appium installations including npm. There's just no good message when it fails.
