### ISSUE TITLE
PID 14124 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.****.erp_client'; Code: '1'

### ISSUE THREAD

**Issue by henryyang0820** [appium/appium-desktop#393]
## Appium-desktop

I'm starting session with my Android device (miui9-- customized Android8.0 ). The error log says:

"java.lang.SecurityException: PID 14124 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.****.erp_client'; Code: '1'
"
![12312312](https://user-images.githubusercontent.com/15648964/35324544-ebedb188-00e8-11e8-9b0a-89c5a51bfc00.png)

I'd like to know whether it is my Android systerm's issue or I do it something wrong?

## Environment

- I am running Appium Desktop version _<1.3.1>_.
- I am on (pick one):
 
    - [ ] Windows

Any responses will be appreciate. ThX.

**Comment by mocobk** [comment]
1. open Developer Options
2. enable USB debugging(Security settings)
it's work for me

**Comment by henryyang0820** [comment]
@mocobk

**Comment by henryyang0820** [comment]
@mocobk thx for your reply. They are done, but it doesn't work. I‘ve changed other devices successfuly.

**Comment by Summer-Day** [comment]
How did you fix it?

**Comment by Summer-Day** [comment]
@henryyang0820  how did you fix it ?

**Comment by henryyang0820** [comment]
@Summer-Day I tried every method searched on the internet. They all don't work. so the device was changed and this issue don't appear.

**Comment by MildaGenius** [comment]
I have the same error on Android 9.

In developer settings allows `USB debugging (security settings)`

**Comment by DevHimu** [comment]
I have the same error  , mainly If you are using in Chinese mobile .
Please find the step to resolve the error .

step1: go to setting 
step2: go to developer option
step3: select Debug APP option (here you have to select the debug app from your phone)

**Comment by JuanEstrellaM** [comment]
I have the same error, with my phone (Realme C3), I solved with the following way:
First **Enable Developer Option** second step **enable USB Debugging**
And very important Step:
Step 3. Search for "Disable Permission Monitoring" and Enable it.

**Comment by SharbelOkzan** [comment]
> Step 3. Search for "Disable Permission Monitoring" and Enable it.
This what worked for me, on Realme X device.

thanks @JuanEstrellaM
