### ISSUE TITLE
Cannot change remote host IP address

### ISSUE THREAD

**Issue by moezayed** [appium/appium-desktop#394]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I open the 'New Session' window, the 'Remote Host' IP address is set to 127.0.0.1 and cannot be changed (grayed out).
The port number cannot be changed (grayed out) either, but I don't need to modify it.
I need to set the 'Remote Host' IP address to 0.0.0.0 (and keep port as is: 4723).

## Environment

- I am running Appium Desktop version 1.3.0
- I am on (pick one):
    - [ ] Mac
    - [x] Windows (Virtual Machine)
    - [ ] Linux

**Comment by dpgraham** [comment]
That's surprising. That tab shouldn't ever be greyed out. Are you able to open up the console logs (`right click -> Inspect Element` opens up the DevTools and navigate to `Console`) and share with me what the logs are?

**Comment by moezayed** [comment]
Thanks @dpgraham for the reply.

I do not see any menu/button/link/etc. for 'Inspect Element'.

From the main Appium Desktop window (after starting server), I see on the left: File/View/Help menus, on the right 'Start Inspector Session'/'Get Raw Logs'/'Stop Server' buttons.
The 'Get Raw Logs' simply show server logs (Appium REST http listener started on ...).
When I click on 'Start Session' from 'New Session Window', I get the error msg: 'Could not connect to server, are you sure it is running?'.

On 'New Session Window', Remote Host is set to 127.0.0.1 and Remote Port is set to 4723 (both are grayed out). Appium server is running on local host.
On main Appim Desktop window, Host: 0.0.0.0, Port: 4723

Thanks for any feedback.

**Comment by moezayed** [comment]
Sorry, closed it by mistake.

**Comment by dpgraham** [comment]
Can you post a screenshot?

**Comment by moezayed** [comment]
I was able to get aound the issue by using the 'Automatic Server' tab in the 'New Session' window.
Many thanks for the feedback.
Closing the issue.
