### ISSUE TITLE
[JSONWP Proxy] Got response with status 200: Failed to launch application status: "13" [XCUITest] Failed to create WDA session. Retrying...

### ISSUE THREAD

**Issue by crhoads1024** [appium/appium-desktop#397]
Appium will throw the cant launch status 13 error on physical device and simulator.

Manually Launch App:
Successful - on physical device
Unsuccessful - on iOS simulator

Same apps im trying to launch now ran just a couple weeks ago on both platforms.

Automatic code signing is configured and applied to WDA.proj in xcode with the capabilities set for real device server caps with the following values:
"xcodeOrgId": "Company_OrgId_Num",
"xcodeSigningId": "Company_Team_ID"

useNewWDA set to true

Observed Behavior on real device:
WDA is installed on real device
App is installed on REAL DEVICE
Neither WDA or App attempt to open on real device like they do on simulator.
Then this error is found in the logs.
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.qsrsoft.portalapp application","sessionId":"158E23C6-4490-4DFA-8F11-E5818431D474","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...

**Just this morning** the app launched properly on physical device, twice, here is the log odf the second successful app launch on real device.
https://gist.github.com/crhoads1024/3442464dc5deec73cc99b6016e4110e8

Observed behavior on simulated device:
WDA is installed then launches and closes immediately.
Then the app is launched and closes immediately.
Logs show same error as noted with the real iOS device - cant launch app, status 13 retrying WDA...

Machine Config:
Mac Book Pro: OSX 10.3.2
Xcode: 9.2
Appium Server: 1.7.2
iOS Sim: 11.2
UDID: 5A4A7D7B-0D5B-4CB4-BBD2-5F1E9E87B2DF
iOS Physical Device: iPhone 6s Plus - 11.2

Physical Device Launch Failure Log:
https://gist.github.com/crhoads1024/24c8edb9574db4a7ede2875338db865f

Physical Device Launch, Multiple locator sessions started and ended until ultimately a status 13 is thrown and server has to be relaunched.
https://gist.github.com/crhoads1024/cfab84458e9863c6fe5bda2e70cd3839

Simulator Device Launch Failure Log:
https://gist.github.com/crhoads1024/04fb7f128b762462b83ab2949d96c62b

**Comment by avrahamShutterFly** [comment]
How do you convert the .ipa to .app?

**Comment by crhoads1024** [comment]
@avrahamShutterFly You don't have to, Appium seems to unzip and convert it. 
Just set in your code in the @Before setup method:
File app = new File(System.getProperty("user.dir") + "path to ipa file");

caps.setCapability("app", app.getAbsolutePath());

When launched, Appium takes care of conversion as seen here from my logs:

[BaseDriver] Using local app 'Users/chrisrhoads/projFolder/iOS_Chris_iPhone_AppFiles/testApp.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[info] [BaseDriver] Unzipping local app '/var/folders/17/wvgjzfkd06z_qp2gmzfwfvgh0000gn/T/2018029-1944-ekjseg.bkerw/appium-app.zip'...
[debug] [BaseDriver] Unzipping /var/folders/17/wvgjzfkd06z_qp2gmzfwfvgh0000gn/T/2018029-1944-ekjseg.bkerw/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/17/wvgjzfkd06z_qp2gmzfwfvgh0000gn/T/2018029-1944-ekjseg.bkerw/appium-app.zip[info] [BaseDriver] Unzipped local app to '/var/folders/17/wvgjzfkd06z_qp2gmzfwfvgh0000gn/T/2018029-1944-ekjseg.bkerw/Payload/TestApp.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1517248617245 (11:56:57 GMT-0600 (CST))
[debug] [XCUITest] Checking whether app '/var/folders/17/wvgjzfkd06z_qp2gmzfwfvgh0000gn/T/2018029-1944-ekjseg.bkerw/Payload/TestApp.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/17/wvgjzfkd06z_qp2gmzfwfvgh0000gn/T/2018029-1944-ekjseg.bkerw/Payload/TestApp.app': 'com.rockSoft.TestApp'

**Comment by BShivShankar** [comment]
@avrahamShutterFly you can convert .ipa to .app

-- Open the project in xcode 
-- Run the build from xcode in your real device
-- Once build gets installed in your device
-- Click on File -> Workspace Setting - > above advanced menu - click on path derived data (Right arrow) 
-- Now you will get the window popup displayed with recent folder as Derived Data -> Select appname...-> Bulid -> Products -> Debug-iphoneos-> scroll to find the app (.app) with recent date and time 

-- Copy the app and paste in your comfortable folder like /Users/user/Documents/yourapp.app

**Comment by dpgraham** [comment]
If this is still an issue, let me know.

**Comment by ayushkulshrestha** [comment]
Facing same issue
[WD Proxy] Got response with status 200: {"value":"Failed to launch com.dominosin.olo application","sessionId":"32B39EA0-EB15-437A-B66A-3CB530497F6C","status":13}
[WD Proxy] Got an unexpected response: {"value":"Failed to launch com.dominosin.olo application","sessionId":"32B39EA0-EB15-437A-B66A-3CB530497F6C","status":13}
[MJSONWP] Matched JSONWP error code 13 to UnknownError
