### ISSUE TITLE
Appium Desktop with webhook flag parameter

### ISSUE THREAD

**Issue by TPDias** [appium/appium-desktop#398]
I'd like to get the appium server logs remotely started with appium-desktop.
Is it possible to start the appium-desktop with the webhook flag parameter? I want to get all the server logs automatically with this option.
This option is not available in the advanced flags:
![image](https://user-images.githubusercontent.com/26970971/35574693-69fbf0ce-05d2-11e8-861f-c9bb37f2b75a.png)

If this option is not available, how can I set what server should appium-desktop use?

I am running Appium Desktop version 1.3.1 on Windows.

**Comment by dpgraham** [comment]
You can run the Appium from the command line and then just go to the menu `Appium > New Session Window` and point your session to the local Appium under the `Custom Server` tab.

**Comment by TPDias** [comment]
Thanks, it works.
