### ISSUE TITLE
Appium Desktop Silent Mode Installer

### ISSUE THREAD

**Issue by HackproTm** [appium/appium-desktop#401]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The installation file does not allow using parameters for silent mode installation. For example, it does not allow you to specify the installation path of the application.

## Environment

- I am running Appium Desktop version 1.3.1.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

![image](https://user-images.githubusercontent.com/7819028/35657744-1b22cd4c-06cc-11e8-9406-006855dc6daf.png)

**Comment by dpgraham** [comment]
This is an issue with Electron, it's not something we'd be able to resolve.
