### ISSUE TITLE
Appium Desktop 1.3.2 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yotsubakoiwai** [appium/appium-desktop#404]
## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version 1.3.2 on Appium v1.7.2
- I am on (pick one):
    - [X] Mac (MacOS High Sierra 10.13.3)

## Appium Server Logs
> [Appium] Welcome to Appium v1.7.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone 6s","app":"/Users/doomhammer/Downloads/tableAndPicker.app","automationName":"XCUITest","udid":"8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","deviceName":"iPhone 6s","app":"/Users/doomhammer/Downloads/tableAndPicker.app","automationName":"XCUITest","udid":"8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1517882764684 (10:06:04 GMT+0800 (+08))
[Appium] Creating new XCUITestDriver (v2.67.0) session
[Appium] Capabilities:
[Appium] platformName: iOS
[Appium] deviceName: iPhone 6s
[Appium] app: /Users/doomhammer/Downloads/tableAndPicker.app
[Appium] automationName: XCUITest
[Appium] udid: 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8
[BaseDriver]
[BaseDriver] W3C capabilities [] and MJSONWP desired capabilities were provided
[BaseDriver] Expected W3C "capabilities" to be a JSON Object but was provided with: []
[BaseDriver] Falling back to MJSONWP desired capabilities
[BaseDriver] Session created with session id: bbaebf3d-7bba-4295-a682-a89a9eca9b36
[XCUITest] Current user: 'doomhammer'
[XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[XCUITest] Xcode version set to '9.2' (tools v9.2.0.0.1.1510905681)
[XCUITest] iOS SDK Version set to '11.2'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1517882766389 (10:06:06 GMT+0800 (+08))
[iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid '8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8'
[XCUITest] Determining device to run tests on: udid: '8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8', real device: false
[XCUITest] No platformVersion specified. Using device version: '11.2'
[BaseDriver] Using local app '/Users/doomhammer/Downloads/tableAndPicker.app'
[BaseDriver] Event 'appConfigured' logged at 1517882766890 (10:06:06 GMT+0800 (+08))
[XCUITest] Checking whether app '/Users/doomhammer/Downloads/tableAndPicker.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/doomhammer/Downloads/tableAndPicker.app': 'com.chopsosaurus.tableAndPicker'
[BaseDriver] Event 'resetStarted' logged at 1517882766894 (10:06:06 GMT+0800 (+08))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1517882767172 (10:06:07 GMT+0800 (+08))
[XCUITest] Starting log capture for iOS Simulator with udid '8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8', using 'xcrun simctl spawn 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8 log stream --style compact'
[BaseDriver] Event 'logCaptureStarted' logged at 1517882767700 (10:06:07 GMT+0800 (+08))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOSSim] Matched 1 Simulator cache item for cleanup: /Users/doomhammer/Library/Developer/CoreSimulator/Devices/8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8/data/Library/Caches/com.apple.mobile.installd.staging
[iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}
[iOSSim] Updated 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8 Simulator preferences at '/Users/doomhammer/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":false}
[iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Both Simulator with UDID 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8 and the UI client are currently running
[BaseDriver] Event 'simStarted' logged at 1517882768355 (10:06:08 GMT+0800 (+08))
[XCUITest] Reset requested. Removing app with id 'com.chopsosaurus.tableAndPicker' from the device
[XCUITest] Installing '/Users/doomhammer/Downloads/tableAndPicker.app' on Simulator with UUID '8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1517882771385 (10:06:11 GMT+0800 (+08))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[BaseDriver] Event 'wdaStartAttempted' logged at 1517882771552 (10:06:11 GMT+0800 (+08))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8, iproxy 8100, 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8.*XCTRunner' for the device 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8...
[XCUITest] 'pgrep -nif xcodebuild.*8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8.*XCTRunner' didn't detect any matching processes. Return code: 1
[XCUITest] Using Xcode 9.2, so fixing WDA codebase
[BaseDriver] Event 'wdaStartFailed' logged at 1517882771707 (10:06:11 GMT+0800 (+08))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1517882782915 (10:06:22 GMT+0800 (+08))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8, iproxy 8100, 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8.*XCTRunner' for the device 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8...
[XCUITest] 'pgrep -nif xcodebuild.*8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif 8B321EE6-6CA8-4DE4-B5ED-1F6CEA3DCBD8.*XCTRunner' didn't detect any matching processes. Return code: 1
[XCUITest] Using Xcode 9.2, so fixing WDA codebase
[BaseDriver] Event 'wdaStartFailed' logged at 1517882783036 (10:06:23 GMT+0800 (+08))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:387:13)
at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js100:21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:387:13)
at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js100:21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at
[XCUITest] Not clearing log files. Use clearSystemFiles capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:387:13)
at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js100:21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at
[HTTP] <-- POST /wd/hub/session 500 19568 ms - 384

**Comment by s3ton** [comment]
I have the same issue.
Had to uninstall and install previous version to fix.

**Comment by yotsubakoiwai** [comment]
have uninstall and reinstall the 1.3.2 version but same thing happens.

had to install previous version so I can continue.

does that mean there's an issue with the newer version?

**Comment by klementynka** [comment]
I have the same issue.

**Comment by NataliaCherkashenko** [comment]
I see the same problem. Reinstall doesn't help

**Comment by kirillbilchenko** [comment]
I see the same issue

**Comment by ashwinibaisutrave** [comment]
I am also facing the same issue had to switch back to older versions 

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:387:13)

**Comment by Milker90** [comment]
I see the same issue

**Comment by neopf** [comment]
I see the same issue when runing appium-inspector after I installed the 1.3.2.

**Comment by amitwagle** [comment]
I am also facing the same issue

**Comment by ritxart** [comment]
me too

**Comment by kirillbilchenko** [comment]
the workaround for now, just download or install via npm https://github.com/appium/appium-xcuitest-driver and replace package content with downloaded ones in /Applications/Appium.app/Contents/Resources/app/node_modules/

**Comment by WaFeIS7** [comment]
I have the same issue on mac with appium-desktop-GUI version 1.3.2. I delete it and install the version 1.3.1, it works fine and it is possible to inspect the elements

**Comment by aruna-ainampudi** [comment]
I was also struggling with the same issue when I installed 1.3.2. 
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".

Uninstalled and reinstalled Appium Desktop with 1.3.1. This fixed the issue.

**Comment by aruna-ainampudi** [comment]
was also struggling with the same issue when I installed 1.3.2.
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".

Uninstalled and reinstalled Appium Desktop with 1.3.1. This fixed the issue.

**Comment by aruna-ainampudi** [comment]
was also struggling with the same issue when I installed 1.3.2.
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".

Uninstalled and reinstalled Appium Desktop with 1.3.1. This fixed the issue.

**Comment by dpgraham** [comment]
This has been resolved in the last few releases. Sorry for the inconvenience this issue gave you all.
