### ISSUE TITLE
"About Appium" doesn't bring up version details, does exactly the same as "check for updates"

### ISSUE THREAD

**Issue by Fortnox** [appium/appium-desktop#405]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In the Appium server window, under "File" clicking "About Appium" brings up the exact same dialogue as "check for updates". I had expected a dialogue showing what version of the software I was on, authors & legal details, etc.

## Environment

- I am running Appium Desktop version x64 v1.23.3 (according to the download link in my history, and no updates available)
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Resolved with v1.4.1 (https://www.github.com/appium/appium-desktop/releases/latest)
