### ISSUE TITLE
Console.WriteLine does not produce logs in Appium desktop console

### ISSUE THREAD

**Issue by yotsubakoiwai** [appium/appium-desktop#408]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I usually use Console.WriteLine for debugging purposes to know if the code is working properly.
I have a XCUIElementTypeTable that currently have 3 XCUIElementTypeCell as pictured below.

When I try to get the count of XCUIElementTypeCell, it doesn't return "3" but gives me like 

`[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"9B422215-15AF-482B-A735-A0F735C362D0"},{"ELEMENT":"5E86CE5D-AB5C-4CC4-9FF0-C190D9E56B7B"},{"ELEMENT":"A78B3F26-F2B7-4200-B3D4-5DA474176F13"}]`

[
![screen shot 2018-02-07 at 4 11 55 pm](https://user-images.githubusercontent.com/26672384/35905370-d003a95c-0c21-11e8-97ce-7942bdace669.png)
](url)

I even tried printing "Hello World" but it's not writing any on the appium desktop console.

## Environment

- I am running Appium Desktop version 1.3.1, Appium Server 1.7.2
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

## Sample Code

int tblCells = driver.FindElementsByXPath("//XCUIElementTypeApplication[@name='tableAndPicker']/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell").Count;
 
Console.WriteLine("Hello World!");
Console.WriteLine(tblCells);

**Comment by gemingguo** [comment]
please tell me what program language do you use Java? or other? appium desktop console can not print the code you write

**Comment by yotsubakoiwai** [comment]
Hi @gemingguo I am using C#. When I ran the test in Visual Studio, it only writes the logs when it fails. 
Is there a way where we can see the output of the run in a console or any window? It usually is a good debugging tool especially in automation..

Thanks!

**Comment by gemingguo** [comment]
@yotsubakoiwai  you should call appium server by process cmd.exe -c  appium and then the appium log will write in debug window.
