### ISSUE TITLE
Not able to upgrade - "JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by Stylar66** [appium/appium-desktop#411]
Appium Desktop

Upgrading from 1.3.1 to 1.3.2 released 2018-01-30T20:07:56.431Z after downloading closing appium to install a JavaScript error is shown. See attached. 
![screen shot 2018-02-08 at 1 20 45 pm](https://user-images.githubusercontent.com/36281106/36001044-de162444-0cd9-11e8-828f-214f26045da5.png)

- I am running Appium Desktop version _<1.3.1>_.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by LasseHall** [comment]
I got the same and decided to look at the Appium.app related logs via Console app and searching "appium". Apparently ShipIt process does begin the upgrade process despite the Exception displayed. One has to fully close the Appium.app and patiently wait that ShipIt finishes its work silently. This results in a successful upgrade.
> default	11:42:25.191564 +0100	Appium	Download completed to: file:///Users/lassehall/Library/Caches/io.appium.desktop.ShipIt/update.VJI2dRi/app.zip
default	11:42:29.991237 +0100	Appium	TIC TCP Conn Event [1:0x60000036a8c0]: 2
default	11:42:29.991282 +0100	Appium	TIC TCP Conn Cancel [1:0x60000036a8c0]
default	11:43:00.233369 +0100	Appium	UNIX error exception: 17
default	11:44:06.284538 +0100	powerd	Process Appium.36833 Created PreventSystemSleep "Preparing update" age:00:00:00  id:30064808828 [System: PrevIdle PrevSleep DeclUser kCPU kDisp]
default	11:44:06.288824 +0100	Appium	Write options: 0 -- URL: <private> -- purposeID: 15835B25-AADD-4D2A-86C7-8327FFC9B001 -- claimID: D2BACDA2-94EF-4A19-99CF-DFCBD4FAE669
default	11:44:06.294961 +0100	Appium	Claim D2BACDA2-94EF-4A19-99CF-DFCBD4FAE669 granted in client
default	11:44:06.295010 +0100	Appium	Claim D2BACDA2-94EF-4A19-99CF-DFCBD4FAE669 invoked in client
default	11:44:06.310279 +0100	powerd	Process Appium.36833 Released PreventSystemSleep "Preparing update" age:00:00:00  id:30064808828 [System: PrevIdle DeclUser kDisp]
default	11:44:06.815867 +0100	ShipIt	Read options: ffffffff80000001 -- URL: <private> -- purposeID: 3F41D566-152E-426D-B2AA-9B7659DD3D36 -- claimID: 2E1FF68B-B5B9-430B-A0FE-B0088DCCE6B9
default	11:44:06.829507 +0100	ShipIt	Claim 2E1FF68B-B5B9-430B-A0FE-B0088DCCE6B9 granted in client
default	11:44:06.829588 +0100	ShipIt	Claim 2E1FF68B-B5B9-430B-A0FE-B0088DCCE6B9 invoked in client
default	11:44:32.261213 +0100	ShipIt	Read options: 1 -- URL: <private> -- purposeID: 3B13ABF5-7540-4C6C-BF69-D0B51581ADBC -- claimID: F7950197-1C47-4AB7-9821-6FC49AC47F44
default	11:44:32.262561 +0100	ShipIt	Claim F7950197-1C47-4AB7-9821-6FC49AC47F44 granted in client
default	11:44:32.262612 +0100	ShipIt	Claim F7950197-1C47-4AB7-9821-6FC49AC47F44 invoked in client
default	11:44:32.278009 +0100	ShipIt	Beginning installation
default	11:44:58.666015 +0100	ShipIt	UNIX error exception: 17
default	11:44:58.677976 +0100	ShipIt	UNIX error exception: 17
default	11:44:58.683523 +0100	ShipIt	UNIX error exception: 17
default	11:46:04.908446 +0100	ShipIt	Moved bundle from file:///Applications/Appium.app/ to file:///var/folders/dq/dd_9q3_538qdjvqv444_lr3h0000gn/T/io.appium.desktop.ShipIt.sMqlWi5c/Appium.app
default	11:46:04.909241 +0100	ShipIt	Moved bundle from file:///var/folders/dq/dd_9q3_538qdjvqv444_lr3h0000gn/T/io.appium.desktop.ShipIt.aesW9qDJ/Appium.app to file:///Applications/Appium.app/
default	11:46:11.455719 +0100	ShipIt	Couldn't remove owned bundle at location file:///var/folders/dq/dd_9q3_538qdjvqv444_lr3h0000gn/T/io.appium.desktop.ShipIt.aesW9qDJ/Appium.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Appium.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/dq/dd_9q3_538qdjvqv444_lr3h0000gn/T/io.appium.desktop.ShipIt.aesW9qDJ/Appium.app";
    NSUserStringVariant =     (
        Remove
    );
} }
default	11:46:20.313742 +0100	ShipIt	Installation completed successfully
default	11:46:20.314756 +0100	ShipIt	ShipIt quitting

**Comment by dpgraham** [comment]
We've made big changes to the autoUpdater (it's been re-written completely). Next release (1.4.1) it will start working (that is to say, once you have installed 1.4.1, future upgrades will work correctly).
