### ISSUE TITLE
Feature(Log view): keyboard shortcut to clear terminal logs

### ISSUE THREAD

**Issue by julien-c** [appium/appium-desktop#412]
Hi,

Would love to hit `⌘ + K` to clear the logs in the Log view.

Would you merge it if I add it?

Thanks!

**Comment by dpgraham** [comment]
Yeah definitely. If you could also add a button in the top right corner that clears the logs, that would be good too.

We had a PR for that previously but it was closed: https://github.com/appium/appium-desktop/pull/272

**Comment by julien-c** [comment]
I'm not big on the button because I don't want to clutter the nice interface, but I'll have a shot at the shortcut then.

Do Windows/Linux users use mostly the same shortcut to clear their terminals?

**Comment by dpgraham** [comment]
I don't think Windows has one. Linux I'm not sure. I'd be fine with it being `Ctrl + K` for Windows and Linux.

**Comment by julien-c** [comment]
Ok just opened a PR (#419)

**Comment by julien-c** [comment]
Thanks for merging!
