### ISSUE TITLE
Appium touch action issues + header files missing in xcui-test-driver, cannot build webdriver agent resulting in failure

### ISSUE THREAD

**Issue by Kenshin-Himura** [appium/appium-desktop#413]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Tried using touchaction to tap/drag and drop an element from one end of the screen to the other. The problem is that the appium inspector shows the device in landscape with the origin at the top but the swipe action uses different coordinates.

According to the inspector the origin is in the top left corner(just the same as in portrait mode) but the device orientation is in landscape(as in if device was viewed in landscape mode the origin would be near the bottom left). But according to the code, the origin is in the top right corner. I Cannot select and element and move here as this is a Unity3d screen. I am trying to move the element by simulating touch actions. This used to work a long time back (maybe 1.20 version  I'm not so sure). I tried updating to 1.3.2 but I'm having issues with webdriveragent xcodeproject file. I tried to manually download and replace the existing files but the coordinate issue still persists. I have attempted various solutions and gone through multiple forum posts but I have yet to find a solution. Pls help me understand the problem and find a workaround/fix.

I did the testing on Iphone 6s plus ios 11.2.2
## Environment

- I am running Appium Desktop version 1.3.3.
- I am on (pick one):
    - Mac High Sierra 10.13

**Comment by dpgraham** [comment]
Fixed with latest version
