### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability

### ISSUE THREAD

**Issue by parthamaity** [appium/appium-desktop#415]
## Appium Desktop?
- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium ## Desktop issue
Got one error i.e., mentioned in below
Error 1 ::- "An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability"
Error 2 :: - Could not connect to server; are you sure it's running?

## Environment
- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Windows 64 bit

**Comment by dpgraham** [comment]
Can you post logs/screenshot
