### ISSUE TITLE
Starting Appium-Desktop on linux ?

### ISSUE THREAD

**Issue by harald42** [appium/appium-desktop#416]
## Appium Desktop

How to start appium-desktop on linux ?_

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Download the .AppImage from: https://github.com/appium/appium-desktop/releases/latest

See https://appimage.org/ for any further reference.
