### ISSUE TITLE
Impossible to build WebDriverAgent

### ISSUE THREAD

**Issue by Biloleg** [appium/appium-desktop#417]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [*] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Impossible to build WebDriverAgent after update Appium from 1.2.7 to 1.3.2
**Steps:**
- Download and install Appium
- Open terminal and run:
    * cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent 
    * sh ./Scripts/bootstrap.sh
- Open WebDriverAgent project in xCode
- Rename bundleId
- Set autosign to WebDriverAgent and WebDriverAgentLib
- Run build of project

**Result:**
Build fail. 'FBPredicate.h' file not found.
Reinstall Appium, carthage and others does't help

**NOTE:** Also WebDriverAgent is not exist by old path (like in 1.2.7) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

## Environment

- I am running Appium Desktop version 1.3.2
- I am on (pick one):
    - [* ] Mac
    - [ ] Windows
    - [ ] Linux
- Xcode Version 9.2 (9C40b)

**Comment by dpgraham** [comment]
Thanks for reporting this. This is a regression from before. I'll work on a release right now.

**Comment by dpgraham** [comment]
I republished 1.3.2; the problem was that when you use Node version 9 it doesn't properly copy over the files in WebDriverAgent.

I reverted to Node version 7 and re-published the .dmg so you can download it again at https://github.com/appium/appium-desktop/releases/latest

**Comment by Biloleg** [comment]
Hi.

 

Thank you very much )))
