### ISSUE TITLE
Appium Desktop----recording  have many questions

### ISSUE THREAD

**Issue by Gaoyongxian666** [appium/appium-desktop#420]
when i choose  python，TouchAction(driver).tap([(183, 166)]).perform()，always have mistakes. i see the sourse ,the code is wrong.......................

**Comment by dpgraham** [comment]
What should it be?

**Comment by Gaoyongxian666** [comment]
after preform tap,the code is generated.
but Generated code has question.
tap()，appium have two，one in touch_action.py,the other in webdriver.py 
the parameter is list ，You should want to use the tap in webdriver.py 
so the Generated code should is     'driver.tap([(1188, 2454)])' 
or   'TouchAction(driver).tap(x=700, y=2460).perform()'

**Comment by Gaoyongxian666** [comment]
my english is not good ,I hope you can understand me

**Comment by dpgraham** [comment]
Awesome, thanks, I'll put in a fix for that.
