### ISSUE TITLE
Appium server doesnt get started gives service value as null.

### ISSUE THREAD

**Issue by parul001** [appium/appium-desktop#423]
****
**# this is the console output.**
C:\Users\parulb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js:1
(function (exports, require, module, __filename, __dirname) { import from 'lodash';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
 ## **this is my Exception info **

io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\parulb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js, --port, 4723, --address, 127.0.0.1, --log, C:\Users\parulb\Desktop\Flipkart_30Jan18\Reports\DeviceLog\Appium.log]  Process output: C:\Users\parulb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js:1  (function (exports, require, module, __filename, __dirname) { import from 'lodash';                                                                ^^^^^^  SyntaxError: Unexpected token import      at new Script (vm.js:51:7)      at createScript (vm.js:138:10)      at Object.runInThisContext (vm.js:199:10)      at Module._compile (module.js:624:28)      at Object.Module._extensions..js (module.js:671:10)      at Module.load (module.js:573:32)      at tryModuleLoad (module.js:513:12)      at Function.Module._load (module.js:505:3)      at Function.Module.runMain (module.js:701:10)      at startup (bootstrap_node.js:190:16)
--

**Comment by dpgraham** [comment]
Appium Desktop is a GUI Application.

What happens when you open the `.exe` file?

**Comment by dpgraham** [comment]
Aha. I understand now.

You'll want to change the path to `C:/Users/parulb/AppData/Local/Programs/appium-desktop/resources/app/node_modules/appium/build/lib/main.js`

**Comment by parul001** [comment]
thanks
