### ISSUE TITLE
 Appium Desktop Installer won't let me choose installation directory

### ISSUE THREAD

**Issue by etekes** [appium/appium-desktop#426]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I downloaded Appium.Setup.1.3.2.exe from https://github.com/appium/appium-desktop/releases
When I run it, it automatically installs Appium Desktop in C:\Users\MyUserName\AppData\Local\Programs\appium-desktop
I want to install it in C:\Program Files but I haven't found a way to do that. I tried running it both normally and as Admin.
I tried an older version (1.2.1) but got the same result.

Any help is appreciated.

## Environment

- I am running Appium Desktop version _1.3.2_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by 317174106** [comment]
you are not allowed to change the install path
