### ISSUE TITLE
Appium Desktop - Selecting dropdown value in android 7 is not working but it is working fine for Android 6.

### ISSUE THREAD

**Issue by maniz025** [appium/appium-desktop#427]
## Appium Desktop
Selecting dropdown value in android 7 is not working.
## The problem

 Selecting dropdown value in android 7 is not working. We have tested with web and Hybrid apps in Android 7 and the dropdown value is not selected when we run the automated tests. It is clicking on the object but it is not selecting the dropdown value. We have tried with Sendkeys, scrollToExact, selectByVisibleText, selectByValue, selectByIndex, etc and none of the options work. We are facing this issue for 3 weeks and it blocks our automation work. Only we are able to select the value for visible text using x & y coordinate values. But it is not the best practice to use the x & y coordinate for all the dropdown fields. Also We cant perform it for invisible dropdown values.  

We have seen this issue occurs only in Android 7 and there is no issue with Android 6.

Is anyone faced this issue? Could you please share if there are any solutions for this issue.

## Environment

- I am running Appium Desktop version 1.3.2 (Latest version).
- I am on (pick one):
    - [ ] Windows

**Comment by maniz025** [comment]
Is there any update on this?

**Comment by dpgraham** [comment]
If this is still a problem, let me know.
