### ISSUE TITLE
appium desktop (1.3.2) cannot find element by xpath or by ID on android 7.1.1 

### ISSUE THREAD

**Issue by csekamal** [appium/appium-desktop#428]
## Appium or Appium Desktop?
appium desktop
## The problem
appium desktop fails to find element by xpath or id after I upgraded Samsung Galaxy Tab E from android 6.0.1 to 7.1.1.
It was working fine with android 6.0.1 and appium desktop 1.3.2.

## Environment
appium desktop = 1.3.2, 1.3.1, 1.2.7 (tried all 3)
android = 7.1.1
device = Samsung Galaxy Tab E

- I am running Appium Desktop version _<1.3.2>_.
- I am on (pick one):
 Windows

Related Log from A.D:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.view.View[@text='OPSS']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.view.View[@text='OPSS']' using 'XPATH' with the contextId: '' multiple: false
[HTTP] <-- POST /wd/hub/session/9baf1bb7-fd98-4c84-94f2-4f5a640f8c14/element - - ms - - 
[HTTP] --> GET /wd/hub/session/9baf1bb7-fd98-4c84-94f2-4f5a640f8c14/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["9baf1bb7-fd98-4c84-94f2-4f5a640f8c14"]
[HTTP] <-- GET /wd/hub/session/9baf1bb7-fd98-4c84-94f2-4f5a640f8c14/screenshot - - ms - - 
[HTTP] --> POST /wd/hub/session/9baf1bb7-fd98-4c84-94f2-4f5a640f8c14/appium/app/close {}
[MJSONWP] Calling AppiumDriver.closeApp() with args: ["9baf1bb7-fd98-4c84-94f2-4f5a640f8c14"]
[AndroidBootstrap] Emitting alert message...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Emitting system alert message
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying

**Comment by dpgraham** [comment]
Try setting `automationName=UiAutomator2`.... bootstrap is no longer supported.
