### ISSUE TITLE
The server is stopped

### ISSUE THREAD

**Issue by hargoyal** [appium/appium-desktop#434]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<1.3.2>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] [Linux](url)

Hi

I downloaded latest version of Appium from our [github ](https://github.com/appium/appium-desktop/releases/tag/v1.3.2)

. I have installed it in two windows PCs,
- On first it works fine.
- But on second one, just by clicking "Start server v1.7.2" a window appear showing "The server is stopped". 
Please suggest me where i am wrong to configure?
Please fetch attachment:
![img_01032018_173243_0](https://user-images.githubusercontent.com/16696932/36844024-f4628c94-1d76-11e8-8c81-74f907244d15.png)
![screenshot 13](https://user-images.githubusercontent.com/16696932/36844025-f4b1b79c-1d76-11e8-833d-c5cc0f722743.png)

**Comment by dpgraham** [comment]
How are the PC's different from eachother?

On the PC that it isn't working, are you able to run appium from the command line?

ie:
```
npm install -g appium
appium
```

**Comment by hargoyal** [comment]
Getting some issue after hitting above command in command line.
![img-20180303-wa0005](https://user-images.githubusercontent.com/16696932/36931841-f8e41dae-1ee4-11e8-9601-3e491c34f5d8.jpg)

**Comment by dpgraham** [comment]
Is the PC behind a firewall?

**Comment by hargoyal** [comment]
Not sure but this PC has an antivirus, i uninstalled it. Still same issue persists.

**Comment by dpgraham** [comment]
Can you send the log that is being printed out: the one that ends in `debug.log`

**Comment by hargoyal** [comment]
Please fetch Attached log
[2018-03-03T06_52_58_380Z-debug.log](https://github.com/appium/appium-desktop/files/1780142/2018-03-03T06_52_58_380Z-debug.log)

**Comment by dpgraham** [comment]
Looks like it's a firewall issue `FetchError: request to https://registry.npmjs.org/appium failed, reason: getaddrinfo ENOENT registry.npmjs.org:443`.... are you able to hit https://registry.npmjs.org through your browser?

**Comment by hargoyal** [comment]
Yes getting this response in the browser.

`{"db_name":"registry","doc_count":818775,"doc_del_count":342,"update_seq":9812891,"purge_seq":0,"compact_running":false,"disk_size":7712333958,"data_size":4389722510,"instance_start_time":"1520336225219769","disk_format_version":6,"committed_update_seq":9812891}`

**Comment by hargoyal** [comment]
Thanks, @dpgraham for your time.
I Got solution for this error, it was due to an antivirus present in PC.

After uninstalling antivirus didn't help me but after that, I created a new User Account helps me to get all ports opened and Server runs successfully.
