### ISSUE TITLE
Could not update to the latest 1.4.0 version from version 1.3.0 --Java Script Error

### ISSUE THREAD

**Issue by ashwinibaisutrave** [appium/appium-desktop#438]
## Appium or Appium Desktop?

Appium Desktop 1.4.0

## The problem
Not able to update to latest 1.4.0 version from 1.3.0  -Download error and java script error as shown below .

## Environment
Mac machine .

<img width="762" alt="screen shot 2018-03-05 at 14 55 02" src="https://user-images.githubusercontent.com/28534028/36981698-b912ae1e-2085-11e8-8924-8666e987c580.png">
<img width="759" alt="screen shot 2018-03-05 at 14 55 20" src="https://user-images.githubusercontent.com/28534028/36981696-b86fd13a-2085-11e8-87d4-e728befed0e6.png">

**Comment by ashwinibaisutrave** [comment]
Had to do a fresh install.

**Comment by dpgraham** [comment]
@ashwinibaisutrave can you do a fresh install for v1.4.1 now? I just overhauled and tested autoupdate and I expect it to work seamlessly now.
