### ISSUE TITLE
New Appium Update 

### ISSUE THREAD

**Issue by MiriamCoelho** [appium/appium-desktop#440]
When i’m on the Home page of Appium: Always appears information about new version
![appium 1](https://user-images.githubusercontent.com/35959724/36985701-df8fdce2-208f-11e8-890f-3ce5f6782d30.png)

The download done the steps chargement
![appium 2](https://user-images.githubusercontent.com/35959724/36985710-e54ff284-208f-11e8-86ca-b75ea1847ecc.png)

After appear error:
![appium 3](https://user-images.githubusercontent.com/35959724/36985719-ebed4d94-208f-11e8-8c84-ddf03ba31a68.png)

But appear too this completed information:
![appium 4](https://user-images.githubusercontent.com/35959724/36985724-ef77703e-208f-11e8-8979-6a574983c724.png)

## Environment

- I am running Appium Desktop version <v1.7.2>.
- I am on :
   - [X ] Windows

**Comment by MiriamCoelho** [comment]
https://discuss.appium.io/t/new-appium-update/21182/2?u=miriamcoelho

**Comment by dpgraham** [comment]
@MiriamCoelho can you go to https://github.com/appium/appium-desktop/releases/latest and try to download and install v1.4.0 manually; the auto-updater has known problems that we expect to be resolved once v1.4.1 is released.

**Comment by MiriamCoelho** [comment]
Ok (Y)

**Comment by dpgraham** [comment]
@MiriamCoelho This is now fixed with Appium v1.4.1... after you install 1.4.1, future updates should work seamlessly.
