### ISSUE TITLE
Need help in using Custom Server in Appium Inspector

### ISSUE THREAD

**Issue by Anusha07** [appium/appium-desktop#441]
Hi,

Am trying to connect an Appium Server launched in Ubuntu machine from Windows Appium Server but seeing 'ECONNRESET' error.

Could you please check and suggest the steps to configure the connection.

Thanks & Regards

**Comment by Anusha07** [comment]
Hi,

Could anyone please share the steps to use Custom Server in Appium Inspector from Windows to Linux machine.

Thanks in Advance.

**Comment by Anusha07** [comment]
Hi, 

Could anyone please provide steps to use Custom server in Appium Inspector from Windows to Linux.

Thanks in Advance.

**Comment by dpgraham** [comment]
You just need to provide the host and port of the Linux server

Try opening http(s)://<LINUX_HOST>:<LINUX_PORT>/wd/hub/status in a browser from Windows. If it fails to connect, then it's a network problem and your Windows machine can't access the Linux appium server.
