### ISSUE TITLE
App not launching from Appium Desktop, app getting installed in device but unable to launch it.

### ISSUE THREAD

**Issue by Kiranhp** [appium/appium-desktop#442]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by Kiranhp** [comment]
Using capabilities.
{ "devicename" : "iphone 6",
  "platformName": "iOS",
"udid": device udid 
"app":  " app path "
"automationName" : "XCUITEST",
"platformVersion": "11.2",
"useNewWDA":"true"
}

**Comment by ashwinibaisutrave** [comment]
I am also facing the same issue .with the latest appium desktop version.

**Comment by dpgraham** [comment]
Try with the latest. I'm pretty sure this is resolved. If it's not I'll re-open.

**Comment by bp24acharya** [comment]
In the appium Desktop when I have changed the capability of Appium app, the app is not opening.
