### ISSUE TITLE
Provide a way to download the source from the inspector

### ISSUE THREAD

**Issue by tOkeshu** [appium/appium-desktop#447]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop's Inspector shows the source of the current screen being tested, but does not provide any way to download it. It can be useful, especially to investigate problems outside of the inspector.

## Environment

- I am running Appium Desktop version Version 1.3.2
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [X] Linux

**Comment by dpgraham** [comment]
We have another ticket open for this already.
