### ISSUE TITLE
Application can't find ideviceinstaller and adb

### ISSUE THREAD

**Issue by rosolko** [appium/appium-desktop#45]
I'm using Appium v1.0.0-beta.
Start server and create 2 sessions for iOS and Android application.
But when I try to start sessions application said that tools missing but actually they presented.
![screenshot at 12-01-37](https://cloud.githubusercontent.com/assets/11458319/23452860/0b09b08c-fe77-11e6-8025-bdd47daf7d4a.png)
![screen shot 2017-03-01 at 11 50 00 am](https://cloud.githubusercontent.com/assets/11458319/23452865/0d0fb930-fe77-11e6-98b4-029312043027.png)
![screenshot at 12-02-15](https://cloud.githubusercontent.com/assets/11458319/23452869/0ea3f91e-fe77-11e6-927b-0e32cb3a22c2.png)
![screen shot 2017-03-01 at 11 50 24 am](https://cloud.githubusercontent.com/assets/11458319/23452871/0fe89348-fe77-11e6-992a-2388d845a1ba.png)

**Comment by jlipps** [comment]
Hmm. How do you have these environment variables set? Maybe it's in some shell startup script that isn't run by Appium desktop?

@dpgraham this is an interesting case to consider; where does node running in electron get its env vars from? Running `npm run dev` probably grants you access to whatever you have in your terminal, whereas running the packaged version likely does not.

**Comment by jlipps** [comment]
Probably want to use something like https://www.npmjs.com/package/shell-env

**Comment by eliasnogueira** [comment]
I have the same problem (on issue duplicated #48 )
So, I did not understand correctly... the shell-env must be installed in Appium app package or globally?

I've tried globally, but doesn't works =/

**Comment by jlipps** [comment]
No, it's a fix we'd need to make to Appium Desktop. I'm trying it out now.

**Comment by JagatheswaranSelvakumar** [comment]
Hi All,

I am also facing this issue .
 I have started server with Appium UI and then started New session in Appium desktop and its working fine.

If we start server and New session in Appium desktop and getting below error
Error
An unknown server-side error occurred while processing the command. Original error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

**Comment by jlipps** [comment]
hi all, please head back to https://github.com/appium/appium-desktop/releases and re-download, I've updated with a dmg that resolved the problem for me.

**Comment by eliasnogueira** [comment]
Hey @jlipps working in my environment now (MacOS Sierra 10.12.3).
Thanks! 👍

**Comment by imurchie** [comment]
Awesome! I love the smell of solvable problems in the evening. 👍

**Comment by JagatheswaranSelvakumar** [comment]
Awesome!.working great after new dmg

**Comment by rosolko** [comment]
Nice. Work fine for me too. Thanks.

**Comment by JagatheswaranSelvakumar** [comment]
Hi Appium Team,

I was trying to launch MAC Calculator app through Appium desktop but i
don't have idea to set Desired Capabilities .Please help me on this.

**Comment by dpgraham** [comment]
@JagatheswaranSelvakumar There's documentation on that:(https://github.com/appium/appium/tree/master/docs/en/writing-running-appium, https://www.appium.io)

**Comment by jlipps** [comment]
@JagatheswaranSelvakumar Appium Desktop is not for automating mac applications, it's the desktop version of Appium.

**Comment by JagatheswaranSelvakumar** [comment]
Thanks Dan and Jonathan.

Kindly help me how to automate mac calculator app.

**Comment by JagatheswaranSelvakumar** [comment]
Please share the steps to automate MAC Calculator Desktop App

**Comment by JagatheswaranSelvakumar** [comment]
Hi,

Kindly share the steps to automate MAC Calculator app

**Comment by JagatheswaranSelvakumar** [comment]
Thanks ..I have attended webinar last week that time i saw the demo and its
code in python .The same code i executed but getting error.I have also
tried in java but getting error.

Java code

DesiredCapabilities cap = new DesiredCapabilities();
    cap.setCapability("platform", "Mac");
    calcDriver = new IOSDriver<IOSElement>(new URL("
http://127.0.0.1:4723/wd/hub"), cap);
    calcDriver.manage().timeouts().implicitlyWait(300, TimeUnit.SECONDS);
    calcDriver.get("Calculator");

**Comment by jlipps** [comment]
@JagatheswaranSelvakumar appium-mac-driver is not yet supported by the appium team. Please open an issue on that repo if you want, rather than continuing to discuss an unrelated topic on this closed issue.

**Comment by jamesbyo** [comment]
I'm seeing this on the latest version of Appium (1.6.2) on Mac OS 10.13.3 updated yesterday. When I attempt to start up appium server I get this message: 

Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

But my variable path is set:
{name}$ which adb
/Users/{name}/Library/Android/sdk/platform-tools/adb

{
  "platformName": "Android",
  "platformVersion": "8",
  "deviceName": "Pixel XL",
  "app": "path/to/some.apk"
}

Am I missing something important for launching an Android sim + app? iOS gives me zero issues. 
Thanks!

-jamesbyo

**Comment by R0xyLana** [comment]
@jlipps Good evening, I think
I still have this issue on appium 1.6.2 version and server 1.8.1 version, installed latest dmg (1.6.2)
https://github.com/appium/appium-desktop/releases
When try to run android platform

**Comment by MarcusBates** [comment]
^^^ I am as well. I set my environment variables with a bash profile. Same versions.

**Comment by Hellydays** [comment]
same problem
