### ISSUE TITLE
How to run two instances of Appium Desktop

### ISSUE THREAD

**Issue by karnikmg** [appium/appium-desktop#461]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I can run two instances of Appium Desktop on windows by opening application two times but on mac i can able to do that. I can run only one instance at a time. I want to perform parallel testing using Appium Desktop 

## Environment

- I am running Appium Desktop version 1.4.0
- I am on (Mac):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
I'm not sure how to do that
 That's more of an OS thing. But my advice is to install the Appium CLI and have multiple server instances running via the terminal.

**Comment by karnikmg** [comment]
Hey,
I am able to run two instances of Appium Desktop, all u have to do is 
1. Go to Applications
2. Find and right click on Appium
3. Select Duplicate- Another copy of appium gets created in applications folder.
4. Just run that two applications and configure with your parameters.

This solution is for those who are chasing to run two Appium Desktop instances on mac which works like a charm.
