### ISSUE TITLE
AndroidBootstrap Error in app.asar file 

### ISSUE THREAD

**Issue by badernmb** [appium/appium-desktop#464]
* Appium module 

I have very simple app to lunch appium server using Node js. When I build (Using electron builder) it packed the app fine. The issue is when I execute the app, It did start the server but once the init function executed it error there.

I believe there is an issue when the appium module got packed, because when I run the app before packing, it works fine

The error is shown below :

An unknown server-side error occurred while processing the command. Original error: Error occured while starting AndroidBootstrap. Original error: Error: Error executing adbExec. Original error: 'Command C:\PSATS\PSATS_Plugins\Appium_app\resources\app.asar\node_modules\appium\node_modules\appium-android-bootstrap\bootstrap\bin\AppiumBootstrap.jar /data/local/tmp/' exited with code 1'; Stderr: 'cannot stat 'C:\PSATS\PSATS_Plugins\Appium_app\resources\app.asar\node_modules\appium\node_modules\appium-android-bootstrap\bootstrap\bin\AppiumBootstrap.jar': No such file or directory'; Code: '1'
errorappium.txt

**Comment by dpgraham** [comment]
Did you enable asar compression on it?

When it's asar compressed, you can't run scripts because it's not a directory anymore, it's a zip.

**Comment by badernmb** [comment]
No I didn't, How I can I do this ?

**Comment by dpgraham** [comment]
How did you build it?

**Comment by dpgraham** [comment]
The npm build script is npm run package

**Comment by badernmb** [comment]
I used electron-builder to build

**Comment by dpgraham** [comment]
Are you using the global `electron-builder`? I would try running `npm run package` from the root folder to build it, that script has the proper `electron-builder` configurations (including asar compression disabling).

**Comment by badernmb** [comment]
Yes i'm using electron builder. I did build it using npm run pack but same issue appeared

**Comment by dpgraham** [comment]
Can you show me the logs?

**Comment by badernmb** [comment]
Sure. Attached 
[appiumLog.txt](https://github.com/appium/appium-desktop/files/1804586/appiumLog.txt)

**Comment by dpgraham** [comment]
Sorry, I meant what does the terminal log when you run the packager.

**Comment by badernmb** [comment]
It packed successfully nothing strange shown 

PS C:\Users\Admin\Desktop\test\psats-appium> npm run pack

> appium_app@0.0.1 pack C:\Users\Admin\Desktop\test\psats-appium
> electron-builder --dir

  • electron-builder version=20.4.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.3 appOutDir=dist\win-unpacked
  • default Electron icon is used reason=application icon is not set

**Comment by dpgraham** [comment]
Can you try `npm run package`?

**Comment by badernmb** [comment]
It shows error :  

PS C:\Users\Admin\Desktop\test\psats-appium> npm run package
npm ERR! missing script: package

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-03-12T21_32_30_041Z-debug.log

**Comment by dpgraham** [comment]
Are you in the root directory? The root directory should have a `package.json` that has a script called `package`.

**Comment by badernmb** [comment]
I'm in the root and i have package.json,and the script key contains the follwoing  

 "scripts": {
  "pack": "electron-builder --dir",
  "dist": "electron-builder"
 },

should I change it to follwoung? 

"script": "package"

**Comment by dpgraham** [comment]
This doesn't look like the `appium-desktop` project. What else is in your directory?

**Comment by dpgraham** [comment]
You should clone _this_ repo and then run the packager from the root.

**Comment by badernmb** [comment]
So, Let me clarify more. My small app is only use appium module to lunch the server. So, In the directory there's my app, the node_modules and the package.json. 

When I run the app before packing, works perfect. But the issue appeared after the packing. The server start but doesn't init a session.  

It seems after packing there's some issue with pathing.

**Comment by dpgraham** [comment]
So it's your own Electron app that you're packaging with Appium, if I understand correctly?

You'll need have the `asar` compression exclude `node_modules/appium`.

**Comment by badernmb** [comment]
Yeah that's correct. Why should I exclude appium ? and how that work ?

**Comment by dpgraham** [comment]
Because `asar` compression puts files in a zip folder and files in a zip folder can't be executed via shell. We faced this exact problem. We wanted to compress everything but it causes shell commands to break.

I don't know how to exclude it though, you'll have to look into the `electron-builder` documentation.

**Comment by badernmb** [comment]
Thanks Dan for help.

**Comment by dpgraham** [comment]
No problem!
