### ISSUE TITLE
How to Start Stop Appium Desktop from programming

### ISSUE THREAD

**Issue by udaythbs** [appium/appium-desktop#472]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I have tried running appium desktop auto start\stop by programming but it is not working. Any light on this article would help. Thanks

## Environment

- I am running Appium Desktop version _<1.7.2>_.
- I am on (pick one):
    
    - [ ] Windows

**Comment by dpgraham** [comment]
You'll need to provide more details.

**Comment by udaythbs** [comment]
Hi Dan,
Please see below more details.
   WebDriver driver;
    AppiumDriverLocalService appiumService;
    String appiumServiceUrl;
    
    String Appium_Node_Path="C:\\Program Files\\nodejs\\node.exe";
    String Appium_JS_Path="C:\\Users\\username\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\lib\appium.js";
appiumService = AppiumDriverLocalService
        		.buildService(new AppiumServiceBuilder()
        		 .usingDriverExecutable(new File(Appium_Node_Path))
        		.withAppiumJS(new File(Appium_JS_Path))
        		.withIPAddress("127.0.0.1")
        		.usingPort(4723));        
		appiumService.start();
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("deviceName", "ASUS_Z010D");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("platformVersion","6.0.1");		
		driver = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
                System.out.println("appium server started");
              appiumService.stop();

When we run above code with testNG. we are getting below error.

io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: 
The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\User\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\build\lib\appium.js, --port, 4723, --address, 127.0.0.1]

**Comment by dpgraham** [comment]
Can you try:

```String Appium_JS_Path="C:\\Users\\username\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\build\\lib\appium.js";```

**Comment by prateekchawla** [comment]
@dpgraham Can we pass chrome driver port using the appium service builder?

**Comment by dpgraham** [comment]
Not sure, I don't maintain the service builder. It is a server flag you can pass in though.

**Comment by udaythbs** [comment]
Hi Dan,
I had tried with below suggested details but the error remain same.
**Can you try:
String Appium_JS_Path="C:\\Users\\username\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\build\\lib\appium.js";**

However It works fine with main.js file now. I just used below path and works fine. Thanks a lot.

C:\\Users\\username\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\build\\lib\\main.js.

**Comment by prateekchawla** [comment]
DesiredCapabilities serverCapabilities = new DesiredCapabilities();
            OptionCollector argCollector = new OptionCollector().AddArguments(AndroidOptionList.ChromeDriverPort(openPort));
            AppiumLocalService service;
            service = new AppiumServiceBuilder().WithIPAddress(ConfigurationManager.AppSettings["AppiumIpAddress"]).WithLogFile(new FileInfo(ConfigurationManager.AppSettings["AppiumLogFilePath"] + DateTime.Now.ToString("_HHmmss") + ".txt")).UsingAnyFreePort().WithAppiumJS(new FileInfo(ConfigurationManager.AppSettings["AppiumJSPath"])).UsingDriverExecutable(new FileInfo(ConfigurationManager.AppSettings["AppiumNodePath"])).WithArguments(argCollector).Build();
            service.Start();

**Comment by prateekchawla** [comment]
@dpgraham I am using the above code to make chrome driver port dynamic using the free port on my machine but each time it is opening on Chrome driver port 9515.

**Comment by saikrishna321** [comment]
u can give chrome ports to DesiredCapabilities that works .. instead to AppiumServiceBuilder

**Comment by prateekchawla** [comment]
@saikrishna321  I don't see any General or Android Capability for setting up Chrome driver port ? Is there a way to pass it as an argument in caps?

**Comment by saikrishna321** [comment]
@prateekchawla check this https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java#L60-L61
