### ISSUE TITLE
Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Devapal** [appium/appium-desktop#473]
## Appium or Appium Desktop?
Appium

## The problem
A little backGround: I have installed and used appium on both iOS real device and cloud. After a month of smooth sail, I got the below error:
 **Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: read ECONNRESET".** 

## Environment
- I am running Appium Desktop version 1.4.1.
- I am on Mac

Please see attached appium log
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1839128/appium-server-logs.txt)

I am able to build the xCode projects successfully without any errors. I was also able to launch the integration app from the WebDriverAgent Project on my device from xCode.

I also tried to manually start the web driver by doing the below from **terminal**: 

`xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=67efaf3033f0625458f62ed51f8caac656f67b2d -configuration Debug -xcconfig /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig`

**When I manually ran the above command, I see the WebDriverAgent deployed successfully on my device but Test Build Failed:**  Please see attached log: [Manually_Invoked_WebDriverAgent_Terminal.txt]  
[Manually_Invoke_WebDriverAgent_Terminal.txt](https://github.com/appium/appium-desktop/files/1839229/Manually_Invoke_WebDriverAgent_Terminal.txt)

**Please advice, I haven't changed anything, not sure why all of a sudden web driver agent is not able to start**.

**Comment by fdPoornima** [comment]
Hi @Devapal  , were you able to resolve this error? Am facing similar issue

**Comment by Dev25141** [comment]
Yes!
I modified a few files in appium contents that caused it. What version of appium are you using ?

**Comment by ssk18** [comment]
@Devapal what files did you modify? can you please provide more details as i am facing the same issue.
