### ISSUE TITLE
Cannot find elements after the page refreshes. 

### ISSUE THREAD

**Issue by Stylar66** [appium/appium-desktop#474]
I have a page that has an element that can be refreshed within the page. Before the element is refreshed all elements on the page can be found. After the element within the page is refreshed elements that where found prior to the element being refreshed are no longer found. Has anyone experienced this as well. 

For example:
Page has individual cells that can be moved from one carousel to another carousel within the page.
Cell can be moved to another carousel via an action.
When cell is in the process of moving to another carousel, the cell shows a spinner until the cell is moved to that other carousel. 
After the cell is moved to the other carousel all elements on that page cannot be found. A value error occurs "Element locator """" did not match any elements. 
I do wait until the cell is moved before validating that the move happened. 

- I am running Appium Desktop version Appium Version 1.4.1 (1.4.1)
- I am on (pick one): Mac
- Android simulator

**Comment by dpgraham** [comment]
Does this happen with the latest version?
