### ISSUE TITLE
Set ANDROID_HOME from inside app

### ISSUE THREAD

**Issue by Nikhil1212** [appium/appium-desktop#479]
## Appium

I have setup the Android_Home Path that can be seen in bashrc file but still it is saying Android_home path is not set 

## Environment

- I am running Appium  version _<1.7.2>_.

[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1866580/appium-server-logs.txt)
 ##Problem
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=src/main/resources/AndroidAPK/HO-debug-nonprod.apk, appactivity=com.bidgely.mobile.energyfit.hydroottawa.MainActivity, apppackage=com.bidgely.mobile.energyfit.hydroottawa, platformName=Android, udid=330055ad1f81426b, deviceName=330055ad1f81426b}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'bidgely-Latitude-E5540', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-42-generic', java.version: '1.8.0_162'
Driver info: driver.version: AndroidDriver
- I am on Linux

**Comment by Nikhil1212** [comment]
@stuartbrussell-intuit please help

**Comment by dpgraham** [comment]
Multiple people have had issues with this. I'm going to make a new variable that let's you set ANDROID_HOME from within Appium Desktop.

We currently use this library to pick up the environment variables used in the shell so that we can use it in the electron app: https://www.npmjs.com/package/shell-env

**Comment by stuartbrussell-intuit** [comment]
@Nikhil1212 Hello, I'm sorry I can't help on this one. I just work on https://github.com/appium/appium-for-mac.

**Comment by cynthiabaran** [comment]
Have you _restarted the shell in which the Appium server was running_ after having set the env variables?
I was facing the same issue when I realized that I simply hadn't restarted the server shell after having set the variables in ~/.bashrc file. I had restarted the shell in which I was running the test script, but forgot the one in which the server was running

**Comment by dpgraham** [comment]
Added to latest release 1.6.3... added 'Edit Configurations' button on home screen which opens a UI where you can set ANDROID_HOME

**Comment by galenyjl** [comment]
@dpgraham Thanks for your effort to add the new variable ANDROID_HOME and could you tell how to add it in code like capabilities.SetCapability("","")?
Currently, I am using 1.72 and where is the 'Edit Configurations' button?
Many thanks

**Comment by arifkhanaj** [comment]
After troubleshooting the same issue for a few hours here is what worked for me and should work for you too:

1. Check if you have already set environment variables ANDROID_HOME and JAVA_HOME i.e. in ~/.bash_profile for Mac
2. If environment variables are already set in your machine then set ANDROID_HOME and JAVA_HOME from Appium Desktop by clicking on Edit Configurations from Appium Home screen.

I hope it works for you as well. Have fun

**Comment by vasiliy-ilto** [comment]
@arifkhanaj
