### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: An error occurred

### ISSUE THREAD

**Issue by MonkYU** [appium/appium-desktop#480]
## The problem
I have updated the appium-desktop
appium-desktop:  version 1.5.0 
appium-server   :  version 1.7.2

when I start the server on 0.0.0.0, everything is ok
but when the iphone-device screen is captured by the app-desktop
if I tap or pan the device area in the app-desktop, then I get the error as below:

> [MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (../../../lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at
 [HTTP] <-- POST /wd/hub/session/268d4d25-4a3d-43bc-882d-890f9eeb3c98/touch/perform 500 40 ms - 188
[HTTP] 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted

#### another point is , if I comman+u to test the webDriverAgentRunner alone, it's show success status on the web page

My new appium-desktop 1.5.0 directory is 

`/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent`

thanks

## Environment

- I am running Appium Desktop version _1.5.0_.
- I am on :
    - [·] Mac
- I am on Appium server 1.7.2

**Comment by dpgraham** [comment]
Can you try reproducing this using the Appium CLI? If you can reproduce it using the CLI, then it's an appium issue and should be opened at github.com/appium/appium/issues

**Comment by MonkYU** [comment]
@dpgraham 
Yeah, I am start the server and session using the Appium-Desktop,it's not working yet.

> [MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (../../../lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by MonkYU** [comment]
I succeed on running the server depend on appium-desktop 1.4.1
So, I'm not sure if it's the 1.5.0 problem, if u meet the same problem, so change the version will be right.Thanks guys

**Comment by dpgraham** [comment]
@MonkYU Yeah I republished the 1.5.0 DMG a couple days ago. There was a problem with the original build.
