### ISSUE TITLE
Impossible to find element inside element of list on iOS

### ISSUE THREAD

**Issue by Biloleg** [appium/appium-desktop#486]
Appium Desktop

If you try to findElement inside one of element in list you will get not such element exception.
For example next code work on 1.7.1 server but doesn't work on 1.7.2:
driver.findElementsById("{some containers id}").get(0).findElement(By.id("{some element inside container}"))
Note: reproduce on iOS only

Example of my code:
driver.findElementsById("GSLOfferOverviewCell").get(1).findElement(By.id("GSLOfferOverviewCellTitleLabel")).getText()

Note: List contains 5 elements

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version  1.4.0 (1.3.x also)
- Last Appium version that did not exhibit the issue (if applicable): 1.2.7
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

Appium log:
https://gist.github.com/Biloleg/a4e35b574de71f754c6907e4904ad361

**Comment by dpgraham** [comment]
If it works on 1.7.1 and does not work on 1.7.2 that means that it's an issue with the Appium CLI and not Appium Desktop.

Can you open an issue at https://github.com/appium/appium/issues

**Comment by Biloleg** [comment]
it was closed as appium issue https://github.com/appium/appium/issues/10306 with comment:
"This should be addressed in the recent appium@beta" 
What is appium@beta? How to report them this issue?

**Comment by dpgraham** [comment]
Appium beta is just the beta for 1.8.... it can be installed via:

```
npm uninstall -g appium
npm install -g appium@1.8.0-beta4
```

And you can run it from the CLI.

If they said in `appium/appium` that it's fixed in the beta, I'm going to close this. Once 1.8 is available I'll bundle it in with the next version of Desktop. In the meantime, I recommend either continuing using 1.7.1 from the CLI or using the beta.
