### ISSUE TITLE
Appium inspector failed to connect TestObject with error UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by mparimi06** [appium/appium-desktop#490]
## Appium Inspector
    Appium v1.7.2

   Failed to connect Test object server 
Error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

**Comment by dpgraham** [comment]
Try opening the `Advanced Settings` menu and checking the `Allow Unauthorized Certs` box.

**Comment by mparimi06** [comment]
Allow unauthorized certificates checkbox exist in latest version of appium 1.5.0
which solves the issue.
Thank you for your help

**Comment by dpgraham** [comment]
Great!
