### ISSUE TITLE
Installer for Latest version for Windows 64 Bit?

### ISSUE THREAD

**Issue by mzeeshanhussain** [appium/appium-desktop#491]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hi, I am seeing the 32 bit exe but no installer for Windows?

## Environment

- I am running Appium Desktop version _<1.5.0>_.
- I am on (pick one):
    - 
    - [x] Windows

**Comment by dpgraham** [comment]
@mzeeshanhussain Does the 32 bit installer not working on Win64?

**Comment by dpgraham** [comment]
Ok. Yeah we changed the installation process in 1.5.0 so it will be a bit different.
