### ISSUE TITLE
Installer for Windows fails to create a shortcut

### ISSUE THREAD

**Issue by jmazess** [appium/appium-desktop#494]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The installer for Windows doesn't create a shortcut anywhere on the system for launching Appium Desktop (%LocalAppData%\appium-desktop\Appium.exe).
Note: I am assuming this is a bug/oversight of some kind because it doesn't seem to make sense to not provide a shortcut for launching a GUI app like this.

## Environment

- I am running Appium Desktop version 1.4.1.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by spiderman04** [comment]
There is no desktop shortcut for with 1.5.0-ia32 release either.

**Comment by dpgraham** [comment]
@spiderman04 @jmazess Try this one: https://github.com/appium/appium-desktop/releases/download/v1.5.0/Appium.Web.Setup.1.6.0.exe

**Comment by dpgraham** [comment]
(updated: https://github.com/appium/appium-desktop/releases/download/v1.6.1/appium-desktop-setup-1.6.1.exe)
