### ISSUE TITLE
Feature request: Ability to disable check for updates

### ISSUE THREAD

**Issue by jmazess** [appium/appium-desktop#495]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Currently, immediately after installing and launching Appium Desktop, it checks for updates and, if it finds an update, prompts the user to Install Now or Install Later. For various reasons, it would be desirable to be able to disable the check for updates feature, such as when the update checker doesn't work in the organization's environment or when the organization's environment is centrally managed and they want to control all software installations and updates. Pertaining to the latter scenario, it would be nice if this could be controlled by a global, machine-level setting. Users should be able to decide whether update checking is enabled, too, but the machine-level setting should take precedence.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Same as the perMachine issue, this build checks for updates but it doesn't download them: https://github.com/appium/appium-desktop/releases/download/v1.5.0/Appium.Web.Setup.1.6.0.exe

**Comment by dpgraham** [comment]
NSIS doesn't support auto-update anyways, so either away it solves the problem of needing to disable updates: https://github.com/appium/appium-desktop/releases/download/v1.6.1/appium-desktop-setup-1.6.1.exe

**Comment by adrian-herscu-ge** [comment]
You closed it, but didn't provide any solution.

**Comment by LGFox** [comment]
MacOS AppiumDesktop app (v 16.0.0) freezes when the update dialog appears. I have to close the dialog to let the app to continue. That leads to test fail (timeout error). I wish I could disable checking updates.
