### ISSUE TITLE
Appium 1.5 - Lost folder appium_xcuitest_driver

### ISSUE THREAD

**Issue by nhhphuong** [appium/appium-desktop#496]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In Appium 1.4.1, I can go to /Applications/Appium.app/Contents/Resources/app/ node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent and execute some commands
./Scripts/bootstrap.sh -d
./Scripts/build.sh -d

But in Appium 1.5, I cannot go to this folder because it doesn't exist (/appium-xcuitest-driver/WebDriverAgent)

## Environment

- I am running Appium version _<1.5>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Are you not able to create  IOS sessions

**Comment by nhhphuong** [comment]
Yes, when I run script, it displayed a message "...doesn't exist /appium-xcuitest-driver/WebDriverAgent... "

**Comment by dpgraham** [comment]
When did you download the app? The .dmg was re-published a few days after the initial release because of an issue like this. Can you try re-downloading it and running it again?

**Comment by nhhphuong** [comment]
Thanks so much, dpgraham. I will close the issue.

**Comment by dpgraham** [comment]
No problem @nhhphuong 

That fixed it?

**Comment by ddubtsov35** [comment]
@dpgraham I have this problem( I download latest version appium desktop today https://github.com/appium/appium-desktop/releases
