### ISSUE TITLE
Feature request: Ability to optionally install Appium Desktop perMachine instead of perUser

### ISSUE THREAD

**Issue by jmazess** [appium/appium-desktop#497]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Currently, the Appium Desktop installer for Windows installs into the user profile under %LocalAppData%\appium-desktop (referred to as per-user). For various reasons, it would be useful to be able to install an instance global to the machine (referred to as per-machine) such that all users of the machine have access to the tool and not just the user who installed it. An example is when the organization's environment is centrally managed and the administrators want to deploy Appium Desktop to a group of machines whether or not anyone is logged on. It would also make it easier for the administrators to push updates to these machines since only one installation per machine needs to be updated rather than each user's personal installation.
Another reason why it would be desirable to install Appium Desktop per-machine is that the other components of Appium that are typically installed (Appium Server, Node.JS, Android SDK) are or are capable of being installed per-machine, so allowing Appium Desktop to install per-machine would allow alignment with the way the other products are installed.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
I added NSIS builds to our build artifacts: https://github.com/appium/appium-desktop/releases/download/v1.5.0/Appium.Web.Setup.1.6.0.exe

If you have a chance can you try this and see if it's what you want. It gives the perMachine and perUser options during installation. The only condition is that you need to have an internet connection without a firewall blocking GitHub during installation.

**Comment by jmazess** [comment]
An online installer won't work in some of our customers' environments because they may not permit internet access by the SYSTEM account (Computer account in the case of Active Directory). It must be an Offline installer. Is there any chance you can regenerate this as a fully self-contained Offline installer?

Thanks.

**Comment by dpgraham** [comment]
Added an offline installer too: https://github.com/appium/appium-desktop/releases/download/v1.6.1/appium-desktop-setup-1.6.1.exe
