### ISSUE TITLE
App Source is not coming in the Appium Inspector.

### ISSUE THREAD

**Issue by rdev-qualitrol** [appium/appium-desktop#501]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am having a Desktop application which is a .NET based application. When I am trying to launch it through appium desktop Inspector then application is getting launched but I am unable to get Appsource on Inspector. I can't find its xpath as elements are not shown as part of Appsource.

I am attaching the logs of server and snapshot of inspector.
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1935533/appium-server-logs.txt)
![imageiinspector](https://user-images.githubusercontent.com/23101788/39094721-d22a8ce0-4651-11e8-94b1-7a8c664b992c.PNG)

## Environment

- I am running Appium Desktop version _<1.7.2>_.
- I am on (pick one):
    - [ ] Windows 10

**Comment by dpgraham** [comment]
Is this something that worked in the past but doesn't work now?

**Comment by rdev-qualitrol** [comment]
No, It is not like that. I checked on Calculator App , it is working fine.

But on the app which I am trying to automate .It is not working

**Comment by dpgraham** [comment]
Judging by the logs I think WinAppDriver is not getting the screenshot properly. You should probably open an issue with them (https://github.com/Microsoft/WinAppDriver/issues)

```
[info] [WinAppDriver] [STDOUT] 
[info] [WinAppDriver] [STDOUT] 
[info] [WinAppDriver] [STDOUT] ==========================================
[info] [WinAppDriver] [STDOUT] GET /wd/hub/session/CFE85966-FAAF-41E9-9160-15A37FD72952/screenshot HTTP/1.1
[info] [WinAppDriver] [STDOUT] Accept: */*
[info] [WinAppDriver] [STDOUT] Connection: keep-alive
[info] [WinAppDriver] [STDOUT] Content-Type: application/json
[info] [WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[info] [WinAppDriver] [STDOUT] User-Agent: appium
[info] [WinAppDriver] [STDOUT] 
[info] [WinAppDriver] [STDOUT] [info] [WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[info] [WinAppDriver] [STDOUT] Content-Length: 242
[info] [WinAppDriver] [STDOUT] Content-Type: application/json
[info] [WinAppDriver] [STDOUT] 
[info] [WinAppDriver] [STDOUT] {"sessionId":"CFE85966-FAAF-41E9-9160-15A37FD72952","status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAIgAAAAnCAIAAABbkpc+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAmSURBVGhD7cEBDQAAAMKg909tDwcEAAAAAAAAAAAAAAAAAADAnxo+TwABm5oDQQAAAABJRU5ErkJggg=="}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"CFE85966-FAAF-41E9-9160-15A37FD72952\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAAAIgAAAAnCAIAAABbkpc+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAmSURBVGhD7cEBDQAAAMKg909tDwcEAAAAAAAAAAAAAAAAAADAnxo+TwABm5oDQQAAAABJRU5ErkJggg==\"}"
[info] [JSONWP Proxy] Replacing sessionId CFE85966-FAAF-41E9-9160-15A37FD72952 with 6c1510be-90bd-44be-a0d4-9b13f166a739
[info] [HTTP] <-- GET /wd/hub/session/6c1510be-90bd-44be-a0d4-9b13f166a739/screenshot 200 520 ms - 242 
```

**Comment by dpgraham** [comment]
I'm going to have to close this. Appium Desktop takes whatever is returned by the `/source` input and uses it as the screenshot. If it's not working, it's a WinAppDriver issue.

**Comment by RamakrishnanRajaram** [comment]
I am also facing similar issue.
Is the solution for this issue is provided elsewhere? 
If yes can I have the link to that
