### ISSUE TITLE
Appium Desktop 1.5.0 for Windows triggers Baidu antivirus engine

### ISSUE THREAD

**Issue by tester200xm** [appium/appium-desktop#502]
## The problem
The latest Windows binary build gets detected as a malware.
appium-desktop-Setup-1.5.0-ia32.exe
Baidu: Win32.Trojan.WisdomEyes.16070401.9500.9677
Link to virustotal
https://www.virustotal.com/#/file/6006b7295f64055507aca0aea719c7a633987964df7b33e436104eb818f9813d/detection

## Environment

- I am running Appium Desktop version 1.5.0.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Thanks for letting me know. Not sure if there's anything we can do about this though.
