### ISSUE TITLE
Unable to start appium server 1.7.2 from appium desktop 1.5.0

### ISSUE THREAD

**Issue by swatidigaskar** [appium/appium-desktop#503]
I am unable to run appium installer 1.5.0. While starting appium server 1.7.2 on host 0.0.0.0 and port 4723, it shows message appium server has stopped working

**Comment by dpgraham** [comment]
Sorry I missed this issue.

Is this still a problem? And if so, can you provide detailed reproduction steps.

**Comment by anshu1987** [comment]
Might be system restart can help on this issue.
