### ISSUE TITLE
Unable to Start WebdriverAgent: 'pgrep -nif xcodebuild.*' didn't detect any matching processes. Return code: 1

### ISSUE THREAD

**Issue by Devapal** [appium/appium-desktop#504]
## The problem:

 Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. 

Looks like this is a common problem yet the solution is unique to every case. I ran in to this issue myself several times, sometimes manually setting the port to 8100 in FBWebServer.m fixed it but sometimes it does not.
Could you guys help diagnose the issue ?

## Environment

- I am running Appium Desktop version  1.5.0
- I am on Mac using Real Device
- Device Details: iPhone 8 Plus, iOS 11.3
- xCode 9.3
-Mac OS High Sierra 10.13.4

 Any insight would be appreciated. 

Please see attached logs:

1. Appium Log   
](url
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1940117/appium-server-logs.txt)
)

2. Appium Device Log:
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1940132/appium-server-logs.txt)

**Comment by Devapal** [comment]
Below are the list of things I have tried but with no luck,
1. Restart the device
2. Made sure correct carthage package is installed
3.  "Appium.app/contents/resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/webdriveragent" directory and run: ./Scripts/bootstrap.sh
4. cd /Applications/Appium.app/Contents/Resources/app ; npm install

**Comment by Devapal** [comment]
FYI...Please see below Log with "showXcodeLog = true"
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1940410/appium-server-logs.txt)

**Comment by Devapal** [comment]
figured it out, Thanks Guys

**Comment by eillouz** [comment]
how?
