### ISSUE TITLE
Appium inspector very very slow and not get loaded the screen shot of the screen.

### ISSUE THREAD

**Issue by karnan008** [appium/appium-desktop#515]
## The problem

Open appium server and try to click on search button at the top of the appium server. Then it open the inspector session and i choose my existing setup from saved capability and start session but it keep on loading and very very slow and even after loading the screen - if i click on anything means it wont work anymore.

## Environment

* Appium version that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe): npm@6.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator iPhone 6

**Comment by Akulavenkatesh** [comment]
Facing the same issue with: 
Appium Desktop Client: v1.6.1
Appium Version: 1.8.0
Mac Version: Mac OS Sierra 10.13.4
NPM Version: 5.6.0
Platform: iOS

(ss attached)
<img width="1079" alt="screen shot 2018-05-23 at 6 29 51 pm" src="https://user-images.githubusercontent.com/1756744/40426252-3347bee8-5eb8-11e8-83c9-d2039ae86c65.png">


[HTTP] <-- POST /wd/hub/session 200 6697 ms - 604
[HTTP] 
[HTTP] --> POST /wd/hub/session/268724fd-dbcf-49d9-9fc9-eaf23ba95964/context
[HTTP] {"name":"NATIVE_APP"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","268724fd-dbcf-49d9-9fc9-eaf23ba95964"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'NATIVE_APP'
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/268724fd-dbcf-49d9-9fc9-eaf23ba95964/context 200 7 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/268724fd-dbcf-49d9-9fc9-eaf23ba95964/source
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["268724fd-dbcf-49d9-9fc9-eaf23ba95964"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/CC8E09FD-F90C-48FA-86A6-A4E6A777FFAE/source] with no body

**Comment by Akulavenkatesh** [comment]
[HTTP] <-- POST /wd/hub/session 200 10609 ms - 632
[HTTP] 
[HTTP] --> POST /wd/hub/session/99074228-cb97-4f87-9585-f0abfdc3f2e2/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","99074228-cb97-4f87-9585-f0abfdc3f2e2"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'NATIVE_APP'
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'startConsole' of undefined
[MJSONWP]     at XCUITestDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/commands/context.js:20:23)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session/99074228-cb97-4f87-9585-f0abfdc3f2e2/context 500 16 ms - 219
[HTTP] 
[HTTP] --> GET /wd/hub/session/99074228-cb97-4f87-9585-f0abfdc3f2e2/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["99074228-cb97-4f87-9585-f0abfdc3f2e2"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/6BB04BB7-5DAD-4FF7-9F02-BFD5D08610B8/source] with no body
[HTTP] --> DELETE /wd/hub/session/99074228-cb97-4f87-9585-f0abfdc3f2e2
[HTTP] {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["99074228-cb97-4f87-9585-f0abfdc3f2e2"]
[BaseDriver] Event 'quitSessionRequested' logged at 1527081395710 (18:46:35 GMT+0530 (IST))
[Appium] Removing session 99074228-cb97-4f87-9585-f0abfdc3f2e2 from our master session list
[JSONWP Proxy] Proxying [DELETE /session/99074228-cb97-4f87-9585-f0abfdc3f2e2] to [DELETE http://localhost:8100/session/6BB04BB7-5DAD-4FF7-9F02-BFD5D08610B8] with no body

**Comment by yangyang50** [comment]
I also have this error,Does anyone solve this error?

**Comment by DonnaZh** [comment]
any update on this issue. I got same problem.
Appium-desktop: 1.6.1
Appium server 1.8.0
Xcode 9.4

same error message, same symptoms

**Comment by dpgraham** [comment]
Have any of you tried running Appium CLI instead of running it from Desktop and then running a session from a custom server pointing to your CLI instance.

```
npm install -g appium
appium .
```

**Comment by Akulavenkatesh** [comment]
I did try both ways with CLI and Appium Desktop, used to get the same error. I did a whole clean up and now Appium Desktop is working fine for me.

These are the versions which I have in my mac, pasting it here just in case it helps someone:
appium-webdriveragent-driver@1.0.0
appium-base-driver@1.5.0
appium-logger@2.1.0
appium-support@2.16.1
appium-express@1.2.4
appium-ios-simulator@1.25.0
appium-xcode@3.5.0
appium-jsonwp-proxy@1.5.0
appium-safari-driver@1.1.1
appium-base-driver@2.31.0
appium-cookies@1.1.1
appium-ios-log@1.2.3
appium-remote-debugger@1.9.0
appium-atoms@0.1.0
appium-uiauto@2.4.0
appium-instruments@3.10.0
npmappium-logger@2.1.0
appium-xcuitest-driver@2.84.0
appium-ios-driver@2.4.4
appium-ios-simulator@2.12.2
appium-remote-debugger@3.12.0

**Comment by Seijan** [comment]
@Akulavenkatesh How did you do the clean up? I have the same issue with 1.8.1, it doesn't load anything. It would be helpful if you could provide the commands you used for the clean up.

**Comment by Akulavenkatesh** [comment]
@Seijan as of now I have Appium  v1.8.2-beta and Appium Desktop version 1.6.1

Before trying clean up, run the below command in terminal:
'npm list | grep 'appium' 

and check if there is a mismatch with my versions mentioned above, if yes try reinstalling only those packages and see if it helps.


Heads up: I was totally fine with removing node and npm from my mac =D

Please follow the steps in below link:
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by asislo** [comment]
I did this clean up and there are still some issues with the inspector loading slowly for a handful of pages for my app

**Comment by dpgraham** [comment]
Could somebody provide with the desired capabilities JSON that reproduces this issue?e

**Comment by Akulavenkatesh** [comment]
My setup is working fine now and these are my desired capabilities:

{
  "platformName": "iOS",
  "platformVersion": "11.4",
  "deviceName": "iPhone X",
  "noReset": true,
  "app": "app_path",
  "simpleIsVisibleCheck": true,
  "useJSONSource": true
}

Using simpleIsVisibleCheck and useJSONSource helps in loading the elements faster!

**Comment by jppercy** [comment]
Well.. I was facing this issue and solved updating some libs:

brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies ideviceinstaller

And after:

brew install --HEAD libimobiledevice
brew install --HEAD ideviceinstaller

after that appium inspector started working smoothly.

I think those steps also answer here:
https://github.com/facebookarchive/WebDriverAgent/issues/1015

**Comment by tanyamalhotra30** [comment]
Didnt work. Any solution to the loading issue on appium inspector?

**Comment by kingshuvo** [comment]
Hi, 
any update on this issue? till today I facing the same error. Please guide me if you have a solution.

**Comment by dancondurache** [comment]
Hello, I had the same issue, Appium Desktop Inspector was starting very slow, my solution is below

**My issue:**

Build the Npm/node_modules/../WebDriverAgent.xcodeproj onto the iOs real device
Run tests > ok

**Start AppiumDesktop Inspector > loads very slowly**

**_Issue: the WDA app gets removed from the iOs real devices and AppiumDesktop tries to rebuild it again_**

1. **For running the tests:**

     I am building the following WebDriverAgent.xcodeproj onto the iOS real device

     MAC > New Finder > Applications > Right click Appium-desktop > Show Package Contents > Contents > Resources > 
     app > node_modules > appium > node_modules > appium-webdriveragent > WebDriverAgent.xcodeproj

     I add the following to my desiredCapabilties:

     usePrebuiltWDA=true
     derivedDataPath=/Users/myUserName/Library/Developer/Xcode/DerivedData/WebDriverAgent- 
     ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app

2. **For AppiumDesktop Inspector:**

     **I am build the same WebDriverAgent.xcodeproj as above, onto the iOS real device**

     I add the following to my desiredCapabilties:

     usePrebuiltWDA=true
     derivedDataPath=/Users/myUserName/Library/Developer/Xcode/DerivedData/WebDriverAgent- 
     ciegwgvxzxdrqthilmrmczmqvrgu/

**_Attention: derivedDataPath is missing the last part because AppiumDesktop adds it automatically_**

Currently I use: npm appium@1.17.1 and AppiumDesktop@1.17.1-1

**Comment by Prasanth-chockalingam** [comment]
> My setup is working fine now and these are my desired capabilities:
> 
> ```js
> {
>   "platformName": "iOS",
>   "platformVersion": "11.4",
>   "deviceName": "iPhone X",
>   "noReset": true,
>   "app": "app_path",
>   "simpleIsVisibleCheck": true,
>   "useJSONSource": true
> }
> ```
> 
> Using simpleIsVisibleCheck and useJSONSource helps in loading the elements faster!

It worked dude . Thanks for the help. can we guys have seperate telegram group for these kind of best practices

**Comment by SillymanH** [comment]
Did anyone find a solutions for this? I'm having the same problem.

**Comment by abubakarafzal** [comment]
Same issue

**Comment by SillymanH** [comment]
@abubakarafzal check the page of your application which you’re trying to inspect. My problem was that the page had no pagination and XCUITEST was taking a lot of time to load all the objects on appium inspector. The page had almost 3000 objects in the json response.

**Comment by poojatiwari01** [comment]
If Appium Inspector is taking time to load, close Appium server GUI and Appium inspector, reopen it, then try to attach the freshly created session. It helped me.
