### ISSUE TITLE
Relaxed security setting

### ISSUE THREAD

**Issue by zgoda-mobica** [appium/appium-desktop#516]
## The problem

Allow specifying that Appium server should run with relaxed security.

## Environment

- I am running Appium Desktop version 1.5.0
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [x] Linux

**Comment by dpgraham** [comment]
Yeah definitely. I think we need to add a general feature that lets you set whatever server flag you want.

**Comment by Biloleg** [comment]
The same issue on Mac 1.6.x

**Comment by ash-lionell** [comment]
Is this feature going to be added?

**Comment by dpgraham** [comment]
Yeah it'll be in next version
