### ISSUE TITLE
Error when I try to save a preset

### ISSUE THREAD

**Issue by eliasnogueira** [appium/appium-desktop#52]
## Problem
When I try to save a preset on Appium Desktop main window, I receive this message: "There was a problem saving preset: Cannot set property 'my_preset' of undefined"

The "my_preset" is the preset name.
![my-preset](https://cloud.githubusercontent.com/assets/284888/23530881/8a512c56-ff82-11e6-9851-e4f9a09e2732.png)

## Environment
MacOS Sierra 10.12.3
Appium Desktop 1.0.0-beta

**Comment by jlipps** [comment]
I think I see what's going on here. I made a PR that might fix this, we'll see once we merge it.

**Comment by jlipps** [comment]
think i fixed it @eliasnogueira. we're trying to release a new version to see if the auto updater will work for us. hold on for a few hours while the release CI does its thing.

**Comment by eliasnogueira** [comment]
Thanks @jlipps 
I've tried to update, and I don't know if is the expected behavior, but when I click on Check for update... I receive a message: "Could not download update. Try again later."

**Comment by dpgraham** [comment]
Hi @eliasnogueira; this is a known problem, we're still working out the auto-updating feature. Until then we need to download updates via Github releases.

**Comment by eliasnogueira** [comment]
The problem persist in 1.0.0-beta.2

**Comment by jlipps** [comment]
@eliasnogueira do you mean the saving presets problem persists in beta.2? I can't reproduce it any more. Maybe try closing the app, deleting your appium desktop settings, then reopening? for me the way to delete them was:

```
~/Library/Application\ Support/appium-desktop/Settings
```

(if you don't want to delete, move them somewhere else)

**Comment by eliasnogueira** [comment]
Hey @jlipps, now it's working!
After delete the folder you mentioned and install again the version 1.0.0-beta2 I was able to save a preset. Thanks :)
