### ISSUE TITLE
appium-uiautomator2-server-v1.9.1.apk file doesn't exist

### ISSUE THREAD

**Issue by wuzhenhu** [appium/appium-desktop#524]
appium-uiautomator2-server-v1.9.1.apk file doesn't exist

**Comment by dpgraham** [comment]
@wuzhenhu Which version of Appium Desktop are using and which operating system?

**Comment by wuzhenhu** [comment]
appium-desktop-Setup-1.6.0-ia32

**Comment by Vijayabaskar03** [comment]
I'm facing the same issue with this version. Looks like appium-uiautomator2-server-v1.8.1.apk is present under node-modules instead of v1.9.1.

**Comment by dpgraham** [comment]
@wuzhenhu @Vijayabaskar03 can you try downloading it again. I just republished it and it should have a fix.

Just to confirm, you're both using the win exe right?

**Comment by Vijayabaskar03** [comment]
@dpgraham Thanks for the quick fix. It is working now.

**Comment by dpgraham** [comment]
@Vijayabaskar03 That's a relief! Thanks both of you for reporting this.

**Comment by AfonsoASilva** [comment]
I having the same problem with appium-desktop-1.6.1-x86_64.AppImage, I just downloaded this version today.
