### ISSUE TITLE
I don't know why , who can help me .

### ISSUE THREAD

**Issue by Suny1234** [appium/appium-desktop#529]
## The problem

This is a problem that has been annoying me for a long time
![cba1396496d2ae161ca2cc9522a422e](https://user-images.githubusercontent.com/39110655/39807630-5d2e64be-53af-11e8-8c6b-526ea8b76423.png)

- I am on (pick one):
  - [ ] Windows   win10
 It was also wrong when it was updated

![5bff079a5c1fe10dc10f15b23306241](https://user-images.githubusercontent.com/39110655/39807733-a655b2d2-53af-11e8-9756-353733d04e6b.png)

**Comment by Suny1234** [comment]
Do anyone know what this is the problem？

**Comment by dpgraham** [comment]
Try using this download link: https://github.com/appium/appium-desktop/releases/download/v1.6.1/appium-desktop-setup-1.6.1.exe

The Squirrel build was flaky.
