### ISSUE TITLE
Cannot check boxes in desktop 1.6.1

### ISSUE THREAD

**Issue by fypnlp** [appium/appium-desktop#535]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
  - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by fypnlp** [comment]
Pre requisite:  user has successfully run the desired capabilities and the app appears in appium desktop virtual device 


Scenario:  User can select the wifi option from preferences 

Given I am on   the android appidemos.apk   home screen
When I select preferences 
Then I select  preference dependencies 
When I select  select the wifi

Expected:  user can find the element for the wifi box  and perform the action to tick it.  

Actual:  What's  happening I can find all the elements for the scenario  UNTIL I get to the page which contains the wifi tick box.  I can't find the tick box so I am unable to select it and perform an action.

This is what appium desktop is telling me 

![checkbox](https://user-images.githubusercontent.com/39129689/39868700-a6bebf72-5452-11e8-9e2c-54a10252f7ea.png)

**Comment by dpgraham** [comment]
Try searching for it using the search feature (the magnifying glass icon on the top) and see if you can locate it and click on it.

**Comment by fypnlp** [comment]
Hi, 

I was just about to check before going to bed.  I opened appium desktop and got the following.  
![error message](https://user-images.githubusercontent.com/39129689/39899173-5b966044-54b2-11e8-825e-409a33bc0e8b.png)
I will have to do a total shut down again before appium will work again. 

I will try to find element again.  Do you know  of any good tutorials that might help me?

**Comment by dpgraham** [comment]
I don't know how `browser/init.js` is located in `electron.asar`. Are you using the .app that's download via releases or are you building it yourself somehow?
