### ISSUE TITLE
Error : An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.

### ISSUE THREAD

**Issue by kalp-shah** [appium/appium-desktop#541]
![screen shot 2018-05-11 at 3 51 21 pm](https://user-images.githubusercontent.com/38104571/39920064-5ff012f8-5533-11e8-82ce-25b3f10fcb1c.png)
## The problem

After insert desired capabilities when I start Appium server at that moment I got error "An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system."

My desired capabilities is 
{
  "platformName": "iOS",
  "platformVersion": "11.1.2",
  "deviceName": "iPhone 8",
  "app": "/Users/Desktop/iOSApp.ipa",
  "udid": "<device_udid>"
}

Previously It works and I am able to inspect element by Appium Inspector.
For Android App, It's working fine and I am able to inspect element of App by Appium inspector.
Here I attached my error message screen shot.

## Environment

- I am running Appium Desktop version _<1.6.1>_.
- I am on (pick one):
    - [ Y] Mac OS - 10.13.4
        Xcode version is :- 9.3

**Comment by dpgraham** [comment]
Did you try installing `npm install -g ios-deploy`?
