### ISSUE TITLE
Appium Desktop 1.6.1 & Appium Server 1.8.0 - Elements are not getting highlighted using inspector in android platform

### ISSUE THREAD

**Issue by shashank33** [appium/appium-desktop#544]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
After opening up the appium inspector i cannot highlight any of the elements due to which i m unable to identify any of the elements.I'm using emulator. Also attached the file for same.
![appiuminspector](https://user-images.githubusercontent.com/24203615/40282185-14901526-5c89-11e8-984e-ce67c51be971.PNG)

## Environment

- I am running Appium Desktop version _<1.6.1>_.
- I am on (pick one):
    - [ ] Windows

**Comment by dpgraham** [comment]
Did this work before and then it stopped working?

**Comment by shashank33** [comment]
No first time i installed appium client and then after doing all the setup this thing didnt work and without this highlighting nor working i cannot use inspector

**Comment by dpgraham** [comment]
Is this a webview app?

**Comment by shashank33** [comment]
No this is a contacts app that comes by default on genotion android
emulator.
