### ISSUE TITLE
Running FindElementById or working with AppiumDriver is very slow.

### ISSUE THREAD

**Issue by lhunnelSpiral** [appium/appium-desktop#546]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Try to Find Element is Extreme slow...
[HTTP] --> POST /wd/hub/session/ec6dbf5c-b7b6-4071-91b1-089eb8454d57/element
[HTTP] {"using":"id","value":"home_top_tv_middle_item"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","home_top_tv_middle_item","ec6dbf5c-b7b6-4071-91b1-089eb8454d57"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/9a21f62f-52c1-4f08-90a5-84f784e643f8/element] with body: {"strategy":"id","selector":"home_top_tv_middle_item","context":"","multiple":false}
[JSONWP Proxy] Got response with status 200: {"sessionId":"9a21f62f-52c1-4f08-90a5-84f784e643f8","status":0,"value":{"ELEMENT":"0c08ff8b-cd4b-49af-9e69-0f80dc4e6848"}}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"0c08ff8b-cd4b-49af-9e69-0f80dc4e6848"}
[HTTP] <-- POST /wd/hub/session/ec6dbf5c-b7b6-4071-91b1-089eb8454d57/element 200 **30273** ms - 122

also Click event
[HTTP] --> POST /wd/hub/session/ec6dbf5c-b7b6-4071-91b1-089eb8454d57/element
[HTTP] {"using":"id","value":"menu_transaction"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","menu_transaction","ec6dbf5c-b7b6-4071-91b1-089eb8454d57"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/9a21f62f-52c1-4f08-90a5-84f784e643f8/element] with body: {"strategy":"id","selector":"menu_transaction","context":"","multiple":false}
[JSONWP Proxy] Got response with status 200: {"sessionId":"9a21f62f-52c1-4f08-90a5-84f784e643f8","status":0,"value":{"ELEMENT":"efb2d76c-eee6-4c8b-b515-5bd258ea1fed"}}
[MJSONWP] Responding to client with **driver.findElement()** result: {"ELEMENT":"efb2d76c-eee6-4c8b-b515-5bd258ea1fed"}
[HTTP] <-- POST /wd/hub/session/ec6dbf5c-b7b6-4071-91b1-089eb8454d57/element 200 **30227** ms - 122
[HTTP] 
[HTTP] --> POST /wd/hub/session/ec6dbf5c-b7b6-4071-91b1-089eb8454d57/element/efb2d76c-eee6-4c8b-b515-5bd258ea1fed/click
[HTTP] {}
[MJSONWP] Calling AppiumDriver.click() with args: ["efb2d76c-eee6-4c8b-b515-5bd258ea1fed","ec6dbf5c-b7b6-4071-91b1-089eb8454d57"]
[JSONWP Proxy] Proxying [POST /element/efb2d76c-eee6-4c8b-b515-5bd258ea1fed/click] to [POST http://localhost:8200/wd/hub/session/9a21f62f-52c1-4f08-90a5-84f784e643f8/element/efb2d76c-eee6-4c8b-b515-5bd258ea1fed/click] with body: {"element":"efb2d76c-eee6-4c8b-b515-5bd258ea1fed"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"9a21f62f-52c1-4f08-90a5-84f784e643f8","status":0,"value":true}
[MJSONWP] Responding to client with **driver.click()** result: true
[HTTP] <-- POST /wd/hub/session/ec6dbf5c-b7b6-4071-91b1-089eb8454d57/element/efb2d76c-eee6-4c8b-b515-5bd258ea1fed/click 200 **20092** ms - 76
[HTTP] 

## Environment

- I am running Appium Desktop version _1.8.0_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by lhunnelSpiral** [comment]
But the issue is just happened recently.. before it was running fast,
tired the ff: 
-update/downgrade appium desktop
-change version of Appium.webdriver 3.0.0.1 and 3.0.0.2
-change version of selenium.Support and web driver 3.0.1, 3.12.0
-restart PC and android
-un/install appium and jdk and android appication
-also tired to 3 different machine, one machine is totally new.

**Comment by dpgraham** [comment]
Is this still an issue? Sorry for not replying when you opened this.

**Comment by mkikot-sigma** [comment]
Hi,
I'm experiencing similar issue, I believe: 25 seconds to find element by accessibility ID, 35 seconds to click it:

`[debug] [W3C (aa732d6f)] Calling AppiumDriver.findElement() with args: ["accessibility id","Allow","aa732d6f-8a8f-4878-8475-ef6d5e48a17a"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/B76D2996-1450-46C2-9A1E-6FB03A3B87A5/element] with body: {"using":"accessibility id","value":"Allow"}
[Xcode]     t =    17.44s Find: Descendants matching type Sheet
[Xcode]
[Xcode]     t =    17.45s Find the Application 'com.apple.mobilesafari'
[Xcode]
[Xcode]     t =    17.45s     Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    22.49s Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    27.56s Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    27.56s Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    27.57s Get all elements bound by accessibility element for: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    27.57s     Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    32.60s     Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    32.60s     Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    32.61s Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    37.64s Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    37.64s Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    37.65s Find: Identity Binding
[Xcode]
[Xcode]     t =    37.65s Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    37.65s Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    37.65s Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    37.65s Find: Identity Binding
[Xcode]
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"3E000000-0000-0000-8410-010000000000"},"sessionId":"B76D2996-1450-46C2-9A1E-6FB03A3B87A5","status":0}
[Xcode]     t =    37.66s Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[debug] [W3C (aa732d6f)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"3E000000-0000-0000-8410-010000000000"}
[HTTP] <-- POST /wd/hub/session/aa732d6f-8a8f-4878-8475-ef6d5e48a17a/element 200 24676 ms - 88
[HTTP]
[HTTP] --> POST /wd/hub/session/aa732d6f-8a8f-4878-8475-ef6d5e48a17a/element/3E000000-0000-0000-8410-010000000000/click
[HTTP] {"id":"3E000000-0000-0000-8410-010000000000","sessionId":"aa732d6f-8a8f-4878-8475-ef6d5e48a17a"}
[W3C (aa732d6f)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Matched '/wd/hub/session/aa732d6f-8a8f-4878-8475-ef6d5e48a17a/element/3E000000-0000-0000-8410-010000000000/click' to command name 'click'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/aa732d6f-8a8f-4878-8475-ef6d5e48a17a/element/3E000000-0000-0000-8410-010000000000/click] to [POST http://localhost:8100/session/B76D2996-1450-46C2-9A1E-6FB03A3B87A5/element/3E000000-0000-0000-8410-010000000000/click] with body: {"id":"3E000000-0000-0000-8410-010000000000","sessionId":"aa732d6f-8a8f-4878-8475-ef6d5e48a17a"}
[Xcode]     t =    42.69s Find: Descendants matching type Alert
[Xcode]
[Xcode]     t =    42.69s Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    47.72s Find: Descendants matching type Sheet
[Xcode]
[Xcode]     t =    47.72s Find the "Allow" Button
[Xcode]
[Xcode]     t =    47.73s     Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    52.76s     Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    52.76s     Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    52.76s     Find: Identity Binding
[Xcode]
[Xcode]     t =    52.77s Find the "Allow" Button
[Xcode]
[Xcode]     t =    52.77s     Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    57.80s     Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    57.80s     Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    57.80s     Find: Identity Binding
[Xcode]
[Xcode]     t =    57.91s Find the "Allow" Button
[Xcode]
[Xcode]     t =    57.91s     Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    62.96s     Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    62.96s     Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    62.96s     Find: Identity Binding
[Xcode]
[Xcode]     t =    62.96s Find the "Allow" Button
[Xcode]
[Xcode]     t =    62.96s     Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    68.00s     Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    68.00s     Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    68.00s     Find: Identity Binding
[Xcode]
[Xcode]     t =    68.01s Snapshot accessibility hierarchy for app with pid 69764
[Xcode]
[Xcode]     t =    73.07s Find: Descendants matching type Any
[Xcode]
[Xcode]     t =    73.07s Find: Elements matching predicate '"Allow" IN identifiers'
[Xcode]
[Xcode]     t =    73.07s Find: Identity Binding
[Xcode]
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"3E000000-0000-0000-8410-010000000000","value":"","sessionId":"B76D2996-1450-46C2-9A1E-6FB03A3B87A5"}
[JSONWP Proxy] Replacing sessionId B76D2996-1450-46C2-9A1E-6FB03A3B87A5 with aa732d6f-8a8f-4878-8475-ef6d5e48a17a
[HTTP] <-- POST /wd/hub/session/aa732d6f-8a8f-4878-8475-ef6d5e48a17a/element/3E000000-0000-0000-8410-010000000000/click 200 35648 ms - 118`

I'm just trying to click the "Allow" button in Safari when the page is trying to redirect me:
`driver.find_element_by_accessibility_id('Allow').click()`

Mac OS X Mojave,
XCode 10
Appium 1.9.2-beta.2 (Same thing on 1.9.1)
IPhone simulators at least for 6, 7, 8, 8 Plus, X and iOS 10.3.1, 11.4, 12.0 - basically everything.
