### ISSUE TITLE
Appium Desktop is still using relative coordinates for swipe (moveTo)

### ISSUE THREAD

**Issue by simongranger** [appium/appium-desktop#547]
## Appium or Appium Desktop?

In Appium 1.8.0 release notes:
All moveTo operations in touch actions now take coordinates as absolute

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In Appium Desktop, when using Swipe By Coordinates, the End coordinates are still using relative coordinates while Appium 1.8.0 mentions that all moveTo operations in touch actions now take coordinates as absolute

## Environment

- I am running Appium Desktop version 1.6.1.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Fixed with latest version
