### ISSUE TITLE
Get xpath from selected element

### ISSUE THREAD

**Issue by brentonhouse** [appium/appium-desktop#55]
It would be nice to be able to see the xpath of an element that is selected in the tree to be able to use that in a test.

**Comment by jlipps** [comment]
thanks for the request, @brentonhouse. we've got something like that in the works, but remember that xpath strings automatically generated are usually pretty bad locators.

**Comment by jlipps** [comment]
closing this here since I'm tracking the overall feature in https://github.com/appium/appium-desktop/issues/56

**Comment by brentonhouse** [comment]
yea... just having a lot of trouble with iOS accessibility labels being recognized

**Comment by jushiyuan** [comment]
accessibility id should be very useful! ^ ^ @jlipps

**Comment by brentonhouse** [comment]
It may have something to do with my mobile platform tool (@appcelerator) but the accessibility id is only working for static text labels and not for any other controls.
