### ISSUE TITLE
Appium Server Clear Console

### ISSUE THREAD

**Issue by pbmzbr** [appium/appium-desktop#552]
## The Question

Hello!

Every single test I run I need close and open Appium Server to "clear" the console. Has some command to clear this console after a test finished?

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Server v1.8.0
* Appium Driver version: Appium Driver v4.0.30319
* Last Appium version that did not exhibit the issue (if applicable): Same
* Desktop OS/version used to run Appium: Windows 10 Pro
* Node.js version (unless using Appium.app|exe): Node.js v10.1.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real device Samsung S9

## Details

If necessary, describe the problem you have been experiencing in more detail.

I'm using Visual Studio Community 2017 and C# 

![appium_server](https://user-images.githubusercontent.com/11395681/40611186-39e024d0-626d-11e8-9129-70d989574f26.png)

**Comment by dpgraham** [comment]
Command/Ctrl + K does that

We could add it as a GUI component in the future, but it's a low priority.

**Comment by pbmzbr** [comment]
Thank you, very much dpgraham. 😃
