### ISSUE TITLE
 iOS+appium+python use swipe error

### ISSUE THREAD

**Issue by qinqin-666** [appium/appium-desktop#553]
enviroment： os 10.13.4
Xcode： 9.3.1
appium -v 1.7.2

![image](https://user-images.githubusercontent.com/6150078/40705405-6076c566-641d-11e8-9e33-aa7c9d13ae02.png)

![image](https://user-images.githubusercontent.com/6150078/40705422-6720a832-641d-11e8-93ce-a44a283f2043.png)

**Comment by dpgraham** [comment]
Can you post the logs as text instead of a screenshot and post it to gist.github.com

**Comment by dpgraham** [comment]
Try again with the latest. I changed the swiping logic. If that still doesn't work let me know and I can re-open this.
