### ISSUE TITLE
Installation problem on Windows 10 (64-bit)

### ISSUE THREAD

**Issue by Graar** [appium/appium-desktop#554]
## Appium or Appium Desktop?
- [**X**] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I am trying to install Appium Desktop on a Windows 10 64-bit machine.

I have tried installing the image "appium-desktop-setup-1.6.1.exe" and "appium-desktop-web-setup-1.6.1.exe" and for both when I open the desktop app the window does not fill with any content.

This is caused by the renderer process not being able to find it's index.html file.  The DevTools console shows the following output:
`Not allowed to load local resource: file:///C:/Program%20Files%20(x86)/Appium/resources/renderer/index.html`

Strangely, this points to Appium being installed in the Program Files (x86) folder which is for 32-bit apps.  Did I get the wrong installer ?

Looking in the installation folder, I find the following path to the renderer index.html:
`C:\Program Files (x86)\Appium\resources\app\app\renderer`

If I go into the installation folder and copy:
`C:\Program Files (x86)\Appium\resources\app\node_modules` to `C:\Program Files (x86)\Appium`
`C:\Program Files (x86)\Appium\resources\app\dist` to `C:\Program Files (x86)\Appium`
and 
`C:\Program Files (x86)\Appium\resources\app\app\renderer` to `C:\Program Files (x86)\Appium\resources`
by following successive errors on the DevTools console window.  I then see the interface and there are no errors in the console, and I appear to be able to start a server.

Obviously, there is something going a little awry in the webpack configuration, or I am way off track.

Hope this helps.  Ask if you need more info.

## Environment

- I am running Appium Desktop version _1.6.1
- I am on (pick one):
    - [ ] Mac
    - [**X**] Windows
    - [ ] Linux

**Comment by Graar** [comment]
Dan,
Yes, that's right the installation appears to work successfully.  I get the desktop app and when I click on that link it opens the Electron app, but the renderer process fails.  Looking in the console output I see the message that I posted:

`Not allowed to load local resource: file:///C:/Program%20Files%20(x86)/Appium/resources/renderer/index.html`

Obviously, because the renderer is failing at its entry point means that nothing is displayed, other than the menu File/View/Help, which is in the main process.

The modifications I made do work and I now have a workign install.

At a cursory glance I wonder if there is a relationship with #557.

Let me know if you need me to do some experiments.

**Comment by dpgraham** [comment]
I just published a new version. Can you see if this happens still? https://github.com/appium/appium-desktop/releases/latest

**Comment by fypnlp** [comment]
@Graar   I have a same problem on mac. Its so frustrating and confusing.

**Comment by dpgraham** [comment]
@Graar Yeah I can try that.

**Comment by dpgraham** [comment]
@fypnlp What's the exact error you're getting on Mac?

**Comment by Graar** [comment]
@fypnlp  I gave the steps I used to manually solve the problem on Windows.  i.e. following the message in the console output of the Dev Tools and manually finding and copying the directories to the expected locations.  If you do that (or something similar because you are on Mac) can you make it work?

**Comment by fypnlp** [comment]
My specific problem is I download desktop (when it does unload as it's not unloading properly), unzip, add to applications try to run application and I get the same recurring java script error.  My defect is linked to your ticket.  So I am assuming this is what you are experiencing.

**Comment by Graar** [comment]
@dpgraham My colleague installed version 1.6.2 without a problem today.  I am confused about how that happened.  Maybe we should put this issue on hold and ask other folks to file their experiences.  I'll try and check this again myself to figure out what is going on.

**Comment by swathi-prasad** [comment]
Can anyone help? How di i get here? I can't see AppiumForWindows.zip.
![appium_error](https://user-images.githubusercontent.com/25812057/42489909-64e51372-842b-11e8-9e0e-02f300ea3853.png)

**Comment by Graar** [comment]
@swathi-prasad a bit off topic, but please pay back by letting us know if the installation works OK. 

It would seem that those instructions are out of date.

I downloaded:
[https://github.com/appium/appium-desktop/releases/download/v1.6.2/appium-desktop-setup-1.6.2.exe](https://github.com/appium/appium-desktop/releases/download/v1.6.2/appium-desktop-setup-1.6.2.exe)

If you are using a 32-bit operating system then you will need to download:
[https://github.com/appium/appium-desktop/releases/download/v1.6.2/appium-desktop-Setup-1.6.2-ia32.exe](https://github.com/appium/appium-desktop/releases/download/v1.6.2/appium-desktop-Setup-1.6.2-ia32.exe)

Just run the executable and it should install.

Given that this ticket is about problems I had installing, please could you let us know if it installed OK on your system?  Please tell us the version of windows you are using.

Good luck!

**Comment by amarchbanks** [comment]
I looked through the code and inside main.js I could see these lines:

```
	var isDev = process.env.NODE_ENV === 'development';
	// __dirname is this dir in dev, and the project root (where main.js is built) in prod
	var indexPath = _path2.default.resolve(__dirname, isDev ? '..' : 'app');
```

I had an evironmental variable set up on my machine for other projects set to "development". Perhaps the issue is that the app thinks it's in development mode and is attempting to load the resources from the wrong directory?

After removing the environmental variable the app started without problems.

**Comment by Graar** [comment]
@amarchbanks 
Adam,
Yes, that makes perfect sense.  I have the development variable set on my machine and had the problem.  My colleague does not have the variable set and it worked fine.
Good catch - just wish I'd spotted that.

**Comment by dpgraham** [comment]
If anyone has issues with this again, let me know and I'll re-open.
