### ISSUE TITLE
Appium-desktop (installed via chocolatey) upgrade fails from 1.4.1 to 1.6.1

### ISSUE THREAD

**Issue by IoTFier** [appium/appium-desktop#555]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hi,

I installed Appium-desktop using chocolatey on windows. The installed version from the chocoloatey repo is 1.4.1.

When will the latest version of the appium-desktop be available under chocolatey repository?
The current version on the Appium's site is 1.6.1 - https://github.com/appium/appium-desktop/releases/tag/v1.6.1

When tried to upgrade to v1.6.1
![image](https://user-images.githubusercontent.com/26844611/40866536-c875b508-65c3-11e8-96e4-e06859e8e35d.png)

I get following error

![image](https://user-images.githubusercontent.com/26844611/40866548-dc236672-65c3-11e8-89b8-e506097d1a17.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Yeah you'll have to install 1.6.1 manually. The updating workflow was changed in 1.5.0 so it's incompatible.
