### ISSUE TITLE
Ability to configure a default host value

### ISSUE THREAD

**Issue by chrisvasqm** [appium/appium-desktop#556]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I would like to be able to configure a default value for the `host` instead of `0.0.0.0`, I find myself having to change it to `127.0.0.1` quite often everyday.

## Environment

- I am running Appium Desktop version _1.8.0_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
There's a tab called 'Custom Server' where you can set the host and the port so you can set it to `127.0.0.1` there and set the port to whatever you set it as (4723 by default).
