### ISSUE TITLE
An old issue appears to have returned Uncaught Exception: Error: EACCES: permission denied, open '/Applications/Appium.app/Contents/Resources/app/main.js

### ISSUE THREAD

**Issue by fypnlp** [appium/appium-desktop#557]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by fypnlp** [comment]
Appium version: 
Mac air o/s: 10.13.4 (high sierra)
Java: 1.8.0_71

After a number of weeks with no problems I just got the following error message on my appium desktop.

How do I fix this?

![screenshot 2018-06-04 12 04 50](https://user-images.githubusercontent.com/39129689/40914514-663dd030-67f0-11e8-99f1-a3204b4fae7b.png)

**Comment by fypnlp** [comment]
Hi please close this ticket I was able to successfully download a new version of appium desktop

**Comment by dpgraham** [comment]
Let me know if this is still happening.
