### ISSUE TITLE
Possible appium issue: An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by fypnlp** [appium/appium-desktop#558]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by fypnlp** [comment]
Mac:  high sierra
Java: 1.8
Appium 1.6

Hi,

I was able to run the desired capabilities for appium desktop but, after a few minutes the simulator minimised and I got the following error message in eclipse (see below) how do I fix this? 

What is a Binary Carthage?: 

The only reason I am mentioning this here is after some reading they say this an appium issue: 

Eclipse Log
________________________________________
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'".

Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'

System info: host: 'Jacquelines-MacBook-Air.local', ip: '192.168.0.8', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_71'

Driver info: driver.version: IOSDriver

remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'".

    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:800:13)

    at asyncHandler$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:352:37)

    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:422)

at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)

at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)

at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)

at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)

at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)

at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)

at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)

at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)

at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)

at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)

at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)

at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)

at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)

at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)

at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)

at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)

at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)

at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)

at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)

at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)

at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)

at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)

at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)

at iostraining.InvokeIOS.main(InvokeIOS.java:22)

___________________________________________________________________

From appium server: 

Appium] Welcome to Appium v1.8.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},"capabilities":{"desiredCapabilities":{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},null,{"desiredCapabilities":{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1528130335406 (17:38:55 GMT+0100 (BST))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["app","automationName","deviceName","platformName"]. Falling back to JSONWP protocol.
[Appium] Creating new XCUITestDriver (v2.79.3) session
[Appium] Capabilities:
[Appium]   app: //Users//jacquelinegeorge//Desktop//UICatalog.app
[Appium]   automationName: XCuiTest
[Appium]   deviceName: iPhone 8
[Appium]   platformName: iOS
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"//Users//jacqueline...
[BaseDriver] Session created with session id: d69407b8-a3d5-47d6-a92a-9a8eeffab222
[XCUITest] Current user: 'jacquelinegeorge'
[XCUITest] Xcode version set to '9.4' 
[XCUITest] iOS SDK Version set to '11.4'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1528130341630 (17:39:01 GMT+0100 (BST))
[XCUITest] Simulator udid not provided, using desired caps to create a new simulator
[XCUITest] No platformVersion specified. Using latest version Xcode supports: '11.4' This may cause problems if a simulator does not exist for this platform version.
[simctl] Creating simulator with name 'appiumTest-d69407b8-a3d5-47d6-a92a-9a8eeffab222', device type id 'iPhone 8' and runtime id '11.4'
[iOSSim] Constructing iOS simulator for Xcode version 9.4 with udid '6552639D-A4B5-49AD-86D2-7D5A38A6B914'
[XCUITest] Created simulator with udid '6552639D-A4B5-49AD-86D2-7D5A38A6B914'.
[XCUITest] Determining device to run tests on: udid: '6552639D-A4B5-49AD-86D2-7D5A38A6B914', real device: false
[BaseDriver] Using local app '//Users//jacquelinegeorge//Desktop//UICatalog.app'
[BaseDriver] Event 'appConfigured' logged at 1528130352028 (17:39:12 GMT+0100 (BST))
[XCUITest] Checking whether app '//Users//jacquelinegeorge//Desktop//UICatalog.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '//Users//jacquelinegeorge//Desktop//UICatalog.app': 'com.example.apple-samplecode.UICatalog'
[BaseDriver] Event 'resetStarted' logged at 1528130352048 (17:39:12 GMT+0100 (BST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1528130352295 (17:39:12 GMT+0100 (BST))
[XCUITest] Continuing without capturing device logs: iOS Simulator with udid 6552639D-A4B5-49AD-86D2-7D5A38A6B914 is not running
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOSSim] No Simulator cache items for cleanup were matched in '/Users/jacquelinegeorge/Library/Developer/CoreSimulator/Devices/6552639D-A4B5-49AD-86D2-7D5A38A6B914/data/Library/Caches'
[iOSSim] Setting preferences of 6552639D-A4B5-49AD-86D2-7D5A38A6B914 Simulator to {"ConnectHardwareKeyboard":false}
[iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}
[iOSSim] Updated 6552639D-A4B5-49AD-86D2-7D5A38A6B914 Simulator preferences at '/Users/jacquelinegeorge/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"6552639D-A4B5-49AD-86D2-7D5A38A6B914":{"ConnectHardwareKeyboard":false}},"ConnectHardwareKeyboard":false}
[iOSSim] The count of running Simulator UI client instances is 0
[iOSSim] Booting Simulator with UDID 6552639D-A4B5-49AD-86D2-7D5A38A6B914...
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 6552639D-A4B5-49AD-86D2-7D5A38A6B914 -ConnectHardwareKeyboard 0
[iOSSim] Simulator with UDID 6552639D-A4B5-49AD-86D2-7D5A38A6B914 booted in 120 seconds
[BaseDriver] Event 'simStarted' logged at 1528130473524 (17:41:13 GMT+0100 (BST))
[XCUITest] Starting log capture for iOS Simulator with udid '6552639D-A4B5-49AD-86D2-7D5A38A6B914', using 'xcrun simctl spawn 6552639D-A4B5-49AD-86D2-7D5A38A6B914 log stream --style compact'
[BaseDriver] Event 'logCaptureStarted' logged at 1528130476414 (17:41:16 GMT+0100 (BST))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[XCUITest] Installing '//Users//jacquelinegeorge//Desktop//UICatalog.app' on Simulator with UUID '6552639D-A4B5-49AD-86D2-7D5A38A6B914'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1528130482366 (17:41:22 GMT+0100 (BST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[BaseDriver] Event 'wdaStartAttempted' logged at 1528130483862 (17:41:23 GMT+0100 (BST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at checkForDependencies$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/wda/utils.js:70:9)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[BaseDriver] Event 'wdaStartFailed' logged at 1528130484370 (17:41:24 GMT+0100 (BST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'".
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1528130495965 (17:41:35 GMT+0100 (BST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at checkForDependencies$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/wda/utils.js:70:9)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[BaseDriver] Event 'wdaStartFailed' logged at 1528130496020 (17:41:36 GMT+0100 (BST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'".
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'".
[XCUITest]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:427:13)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[XCUITest] Deleting simulator created for this run (udid: '6552639D-A4B5-49AD-86D2-7D5A38A6B914')
[XCUITest] Killing running processes 'xcodebuild.*6552639D-A4B5-49AD-86D2-7D5A38A6B914, 6552639D-A4B5-49AD-86D2-7D5A38A6B914.*XCTRunner' for the device 6552639D-A4B5-49AD-86D2-7D5A38A6B914...
[XCUITest] 'pgrep -nif xcodebuild.*6552639D-A4B5-49AD-86D2-7D5A38A6B914' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif 6552639D-A4B5-49AD-86D2-7D5A38A6B914.*XCTRunner' didn't detect any matching processes. Return code: 1
[BaseDriver] Event 'newSessionStarted' logged at 1528130510930 (17:41:50 GMT+0100 (BST))
[W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/jacquelinegeorge/.nvm/versions/node/v7.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacquelinegeorge/Documents/Chromedriver:/usr/local/MacGPG2/bin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/:/Users/jacquelinegeorge/Library/Android/sdk/tools:/Users/jacquelinegeorge/Library/Android/sdk/platform-tools:/Users/jacquelinegeorge/Documents/apache-maven-3.5.2/bin:/Users/username/custompath/adt-bundle-mac-x86_64-20130911/sdk/platform-tools/'".
[W3C]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:427:13)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at 
[HTTP] <-- POST /wd/hub/session 500 175715 ms - 3306
[HTTP]

**Comment by dpgraham** [comment]
There's some configuration that needs to be done on your machine before you can start running tests. One of them is installing `carthage` (run `brew install carthage` from terminal).

Here's the guide on configuring Appium for IOS: http://appium.io/docs/en/drivers/ios-xcuitest/

**Comment by swapnilshetes** [comment]
We are facing problem with Appium desktop : please check the below error : 

 Error
[element.sendKeys("12")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Unknown error


we have tried with Appium verions : 
appium-desktop-Setup-1.5.0-ia32.exe
appium-desktop-setup-1.6.2.exe
appium-desktop-setup-1.7.1.exe
appium-desktop-setup-1.8.0.exe

Window : 7 

using Physical device : REDMI 6.0 

While load app with Desired Capabilities its uploaded properly but getting Error while sending key . Major issue we are not able to select any element like button, text box and other available element

Please assist me on this ,

Thanks,
Swapnil

**Comment by kaushikbabbi** [comment]
ima also having the same problem , need help

**Comment by Gurjap** [comment]
I solved this issue by uninstalling the appium application in the emulator.
Then just run again with
{
  "deviceName": "emulator-5554",
  "platformName": "android",
  "noReset": true,
  "automationName": "UiAutomator2"
....
}
Then it worked fine

**Comment by Psingh17** [comment]
Hi,
I can see the topic is closed, but I am also getting this error intermittently, on my local execution (using emulation and user agent) it is fine ,; however, on Bstack getting Unknown server side error.
The following error occurred: An unknown server-side error occurred while processing the command.
Here are the capabilities I am using:-
DesiredCapabilities capabilities = new DesiredCapabilities();
if (MyDriverClass.deviceType.equalsIgnoreCase("Tablet")) {
capabilities.setCapability("os_version", "8.0");
capabilities.setCapability("device", "Samsung Galaxy Tab S3");
capabilities.setCapability("real_mobile", "true");
capabilities.setCapability("browserstack.platform",
"ANDROID");
capabilities.setCapability("project", "Tablet_PROJECT");
capabilities.setCapability("browserstack.browser", "chrome");
capabilities.setCapability("browserstack.browser_version", "76.0");
//also user appium version 1.6.5
capabilities.setCapability("browserstack.appium_version", "1.7.1");
capabilities.setCapability("deviceOrientation", orientation);
capabilities.setCapability("browserstack.local", browserstackLocal);
capabilities.setCapability("browserstack.localIdentifier", browserstackLocalIdentifier);
capabilities.setCapability("browserstack.debug", true);
capabilities.setCapability("browserstack.video", true);
capabilities.setCapability("build", browserStackTCBuild);
return new RemoteWebDriver(
new URL("https://" + username + ":" + accessKey + "@hub-cloud.browserstack.com/wd/hub"),
capabilities);
