### ISSUE TITLE
Could not determine Xcode version 

### ISSUE THREAD

**Issue by fypnlp** [appium/appium-desktop#560]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by fypnlp** [comment]
Hi, 

I am trying to run my desired capabilities for ios using appium desktop  I got the following: 
`[info] [Appium] Welcome to Appium v1.8.0
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> POST /wd/hub/session
[info] [HTTP] {"desiredCapabilities":{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},"capabilities":{"desiredCapabilities":{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},null,{"desiredCapabilities":{"app":"//Users//jacquelinegeorge//Desktop//UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 8","platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1528285642303 (12:47:22 GMT+0100 (BST))
[warn] [Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[warn] [Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["app","automationName","deviceName","platformName"]. Falling back to JSONWP protocol.
[info] [Appium] Creating new XCUITestDriver (v2.79.3) session
[info] [Appium] Capabilities:
[info] [Appium]   app: //Users//jacquelinegeorge//Desktop//UICatalog.app
[info] [Appium]   automationName: XCuiTest
[info] [Appium]   deviceName: iPhone 8
[info] [Appium]   platformName: iOS
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"//Users//jacqueline...
[info] [BaseDriver] Session created with session id: 74265ced-f456-4785-acf9-1a9aafd863c1[debug] [XCUITest] Error: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.
[debug] [XCUITest]     at getVersionWithoutRetry$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcode/lib/xcode.js:116:11)
[debug] [XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest]     at <anonymous>
[error] [XCUITest] Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.
[error] [XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[error] [XCUITest]     at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/utils.js:52:9)
[error] [XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [XCUITest]     at <anonymous>
[error] [XCUITest] Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.
[error] [XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[error] [XCUITest]     at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/utils.js:52:9)
[error] [XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [XCUITest]     at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1528285642465 (12:47:22 GMT+0100 (BST))
[error] [W3C] Encountered internal error running command: Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.
[error] [W3C]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[error] [W3C]     at getAndCheckXcodeVersion$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/utils.js:52:9)
[error] [W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [W3C]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [W3C]     at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session 500 198 ms - 1524
[info] [HTTP] 

How do I resolve this?

**Comment by dpgraham** [comment]
Have you installed Xcode and followed the setup guide (https://appium.io/docs/en/drivers/ios-xcuitest/)?

**Comment by fypnlp** [comment]
Hi, I was able to fix this issue.  I reinstalled the latest version of appium desktop. And it worked. Please close this ticket
