### ISSUE TITLE
Appium Desktop forcing session to end when selecting a picker object.

### ISSUE THREAD

**Issue by Asmohr** [appium/appium-desktop#564]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I’ve been using Appium desktop to acquire Element properties and recently, when I try to open up any picker objects, the session is automatically terminated. I'm running the session through TestObject and a physical device. The picker opens on the TestObject Side when I watch it execute. Appium Desktop just spins once I click the element and terminates the session.

## Environment

- I am running Appium Desktop version _1.6.1_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Can you share the Appium Server logs? You should be able to download these from the TestObject login area. It's probably an issue with Appium server or with the TestObject cloud.
