### ISSUE TITLE
SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 9.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

### ISSUE THREAD

**Issue by gratefulHeart** [appium/appium-desktop#567]
[Appium]   automationName: appium
[Appium]   deviceName: iPhone Simulator
[Appium]   platformName: iOS
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/gfy/Library/...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 42127c56-c6ad-413e-9eb2-29fa65c6584e
[iOS] Xcode version set to 9.1
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 9.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
[iOS]     at IosDriver.createSession$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/lib/driver.js:129:28)
[iOS]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[iOS]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[iOS]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[iOS]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[iOS]     at 
[BaseDriver] Event 'newSessionStarted' logged at 1528791832700 (16:23:52 GMT+0800 (CST))

**Comment by imurchie** [comment]
Yes. Set the `automationName` to `XCUITest`.
