### ISSUE TITLE
Appium Desktop crashes on a right click

### ISSUE THREAD

**Issue by kunal361** [appium/appium-desktop#568]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

```
uncaughtException: Options must be an object
{
  "date": "Thu Jun 14 2018 14:25:40 GMT+0530 (IST)",
  "os": {
    "loadavg": [
      1.58154296875,
      2.04541015625,
      2.23974609375
    ],
    "uptime": 416193
  },
  "process": {
    "argv": [
      "/Applications/Appium.app/Contents/MacOS/Appium",
      ""
    ],
    "cwd": "<cwd>",
    "execPath": "/Applications/Appium.app/Contents/MacOS/Appium",
    "gid": 20,
    "memoryUsage": {
      "external": 174509,
      "heapTotal": 230973440,
      "heapUsed": 218247560,
      "rss": 319098880
    },
    "pid": 57081,
    "uid": 501,
    "version": "v8.9.3"
  },
  "stack": [
    "TypeError: Options must be an object",
    "    at Menu.popup (/Applications/Appium.app/Contents/Resources/electron.asar/browser/api/menu.js:51:11)",
    "    at WebContents.<anonymous> (/Applications/Appium.app/Contents/Resources/app/webpack:/app/main/appium.js:195:9)",
    "    at emitTwo (events.js:126:13)",
    "    at WebContents.emit (events.js:214:7)"
  ],
  "trace": [
    {
      "column": 11,
      "file": "/Applications/Appium.app/Contents/Resources/electron.asar/browser/api/menu.js",
      "function": "Menu.popup",
      "line": 51,
      "method": "popup",
      "native": false
    },
    {
      "column": 9,
      "file": "/Applications/Appium.app/Contents/Resources/app/webpack:/app/main/appium.js",
      "function": null,
      "line": 195,
      "method": null,
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitTwo",
      "line": 126,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "WebContents.emit",
      "line": 214,
      "method": "emit",
      "native": false
    }
  ]
}
```

Steps to reproduce:

- Start App
- Start Appium Server
- Start Inspector Session
- Close the Appium Server Window
- Right click anywhere on the inspector window

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

Appium desktop version 1.6.2
Os Info: macOS Sierra 10.12.6

**Comment by kunal361** [comment]
@dpgraham Thanks for taking out time to go through the issue.
Would like to know if closing the session window when the server window is closed an expected behavior? Because, IMO, we can still run tests on custom servers or platforms like SauceLabs and Browserstack.
Thoughts?

Also would like to contribute towards fixing this, don't have a lot of context of the code-base, but would like to pitch in.

**Comment by dpgraham** [comment]
@kunal361 You can actually start a session without starting the server. 

Just open the menu `Appium > New Session Window...` (or Command->N for short)

That should cover the use case you're looking for.

It probably would be better to have a button on the main page that opens a new session window though.

**Comment by kunal361** [comment]
@dpgraham just discovered that option.
Yup would be better if we could have that on the main page.
Also in this case there is an exception thrown as well, when a right click is performed after the main window is closed.

```
Uncaught Exception:
TypeError: Options must be an object
    at Menu.popup (/Applications/Appium.app/Contents/Resources/electron.asar/browser/api/menu.js:51:11)
    at WebContents.<anonymous> (/Applications/Appium.app/Contents/Resources/app/webpack:/app/main/appium.js:195:9)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

Not sure if we should be pedantic about fixing this though :)

**Comment by dpgraham** [comment]
Fixed in PR
