### ISSUE TITLE
Same Recurring Problem:  Javascript Error occured in the main process  and now cannot download latest version of appium desktop

### ISSUE THREAD

**Issue by fypnlp** [appium/appium-desktop#569]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by fypnlp** [comment]
Update: there might be a connection issue with my broadband provider hence the issues downloading.   I was finally able  to successfully download  appium desktop (latest version)

However,  I still don't understand why I am experiencing the 'java script error' so consistently.   It makes no sense at all.  I've already raised a least 2 tickets.  Why would this happen?  My java 1.8 is up to date and check I it regularly.

**Comment by dpgraham** [comment]
What's the Javascript error?

I looked at your previous ticket and it says that it was trying to access a file inside `electron.asar` which is impossible because we don't use `asar` compression for Appium Desktop.

Are you downloading and running the DMG?

**Comment by dpgraham** [comment]
^ Disregard that

It sounds like from your previous issue, that you were unzipping Appium and stashing it in the /Applications folder

Have you tried actually downloading the .dmg and running that? That's the standard way to install it as an app on Mac.
