### ISSUE TITLE
Can't type Desired Capabilities - savedSessions.length is undefined

### ISSUE THREAD

**Issue by MaciejCiach** [appium/appium-desktop#57]
version : 1.0.0-beta.1 (1.0.0-beta.1)

I'm not able to type any character inside Name or Value field, after key press char is immediately deleted

![image](https://cloud.githubusercontent.com/assets/19686348/23537694/1c09ce3e-ff8b-11e6-8fe9-48c1a71adad4.png)

![image](https://cloud.githubusercontent.com/assets/19686348/23537776/9c3d86f4-ff8b-11e6-9fd7-f0537445aa75.png)

**Comment by jlipps** [comment]
Hi @MaciejCiach thanks for the clear error description. I was able to reproduce by moving my settings file out of Application Support, which means it's an issue with our settings handling on first run. Will look into it.

**Comment by jlipps** [comment]
Got a PR up (https://github.com/appium/appium-desktop/pull/58) which I believe resolves the issue. Hopefully we'll get another beta version out soon!

**Comment by MaciejCiach** [comment]
@jlipps Thank you , I've tried dev version where I just removed this element, apart from that working fine :)

**Comment by jlipps** [comment]
@MaciejCiach we just uploaded beta.2 so feel free to download and try again!

**Comment by MaciejCiach** [comment]
Still the same issue with beta.2 @jlipps 

![image](https://cloud.githubusercontent.com/assets/19686348/23625167/7ead239a-02a8-11e7-86ab-74bac78f7725.png)

**Comment by jlipps** [comment]
@MaciejCiach can you remove your Settings file and try again? It should be as easy as:

```
rm -rf "~/Library/Application Support/appium-desktop/Settings
```

**Comment by slipy12** [comment]
Tryed `rm -rf "~/Library/Application Support/appium-desktop/Settings"` and not working!
Btw: I moved to '~/Library/Application Support/appium-desktop' and executed `rm Settings`. It worked, Settings wasn't a directory

**Comment by dpgraham** [comment]
@slipy12 Did removing the 'settings' directory fix the bug though?

**Comment by slipy12** [comment]
Yes, solved the problem

**Comment by dpgraham** [comment]
Okay great, thanks for your help

**Comment by sampadrout** [comment]
I am still not able to type anything under desired capability. When clicking on Start Session without any desired capabilities, nothing is happening. Seems like button clicking is not working
