### ISSUE TITLE
Appium v1.8.1 fails to launch native app in Android 7.0 due to error --- java.lang.SecurityException: Permission Denial: starting Intent; launchParam=MultiScreenLaunchParams

### ISSUE THREAD

**Issue by karthiksm7** [appium/appium-desktop#575]
## The problem

Appium fails to launch native app like salesforce , gmail and few other apps due to below error :

Error executing adbExec. Original error: 'Command 'C\:\\Users\\karth\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s ce12171cc999780405 shell am start -W -n com.salesforce.chatter/com.salesforce.auth.ChatterLoginActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.salesforce.chatter/com.salesforce.auth.ChatterLoginActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } } from null (pid=23075, uid=2000) not exported from uid 10203

## Environment

Android - 7.0
Appium version - v1.8.1
Windows platform : windows 10 OS
device : samsung s8

appPackage - com.salesforce.chatter
appActivity - com.salesforce.auth.ChatterLoginActivity

- I am running Appium Desktop version _v1.6.2 (from latest releases)

**Comment by dpgraham** [comment]
Can you try running that adb command outside of Appium Desktop and see what happens:

```
C:\Users\karth\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ce12171cc999780405 shell am start -W -n com.salesforce.chatter/com.salesforce.auth.ChatterLoginActivity -S
```

If it doesn't work from the terminal via adb, it won't work on Appium.

**Comment by qifeiLiu** [comment]
@dpgraham 
appPackage - com.citrix.Receiver
appActivity - com.citrix.client.Receiver.ui.activities.WelcomeActivity 



`C:\Users\t_qifeil>adb.exe -P 5037 -s 19c1990b shell am start -W -n com.citrix.Receiver/com.citrix.client.Receiver.ui.activities.WelcomeActivity -S
Stopping: com.citrix.Receiver
Starting: Intent { cmp=com.citrix.Receiver/com.citrix.client.Receiver.ui.activities.WelcomeActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.citrix.Receiver/com.citrix.client.Receiver.ui.activities.WelcomeActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } } from null (pid=17066, uid=2000) not exported from uid 10333
        at android.os.Parcel.readException(Parcel.java:1693)
        at android.os.Parcel.readException(Parcel.java:1646)
        at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3629)
        at com.android.commands.am.Am.runStart(Am.java:658)
        at com.android.commands.am.Am.onRun(Am.java:392)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:125)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:316)`

**Comment by dpgraham** [comment]
@qifeiLiu Looks like your issue is probably an Android issue and not an Appium issue: https://stackoverflow.com/questions/19829507/android-java-lang-securityexception-permission-denial-starting-intent
