### ISSUE TITLE
ADB is not detecting android device after starting appium desktop

### ISSUE THREAD

**Issue by pranavswaroopg** [appium/appium-desktop#576]
## Appium or Appium Desktop?
APPIUM DESKTOP

## The problem

Installed Android SDK with the latest version of platform tools 28.0.0. 
Android device is getting when we try manually at first using ADB to connect before running appium desktop.
After running Appium desktop below error is thrown.
Environment variables for ANDROID_HOME, JAVA_HOME,PATH are set correctly.

## Environment
Win_10_64Bit(1803 and 1703)

##Log

Event 'newSessionStarted' logged at 1530601877818 (12:41:17 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Could not find a connected Android device.
[MJSONWP]     at ADB.getDevices$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:188:13)
[MJSONWP]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at enqueueResult (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[MJSONWP]     at new Promise ()
[MJSONWP]     at new F (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[MJSONWP]     at AsyncIterator.enqueue (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at Object.runtime.async (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[MJSONWP]     at getDevices (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\build\lib\tools\system-calls.js:402:38)
[MJSONWP]     at ADB.getDevices$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:205:20)
[MJSONWP]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at

**Comment by dpgraham** [comment]
Try running: `adb devices` and see if there's any devices connected

You may need to start an emulator or plug-in a real device (with developer mode enabled)

**Comment by pranavswaroopg** [comment]
@dpgraham 
Let me explain.
Step1: i connected real device to the PC and ran ADB devices, i was able to see the real device connected to the PC.
Step2: I start Appium Desktop latest Version (1.6.2) and initiate the tests using C# Library client.
Step3: When i do this the above mentioned log is appearing wit the error. 
Step4: Now again ran ADB devices i was unable to see the device in the list.
Step5: Tried(`Kill-server`) and no use, I reboot the PC and same happens all over again.

This is not happening in the OLD pc that i used to work with. This is happening only in the new PC that i am trying to configure.

**Comment by dpgraham** [comment]
Can you try using the CLI...

```
npm install -g appium
appium
```

And run the tests on that? If the problem still occurs, you'll need to open a ticket with `github.com/appium/appium/issues` and be sure to provide detailed description + reproduction steps as well as information about the environment (Windows version that it works on, Windows version that it does not work on, etc...)

**Comment by pranavswaroopg** [comment]
@dpgraham Please close this issue. This was caused by other tool that we are trying to integrate to Appium.

**Comment by ishah09** [comment]
@pranavswaroopg I am getting same issue, Which things resolved it ?
