### ISSUE TITLE
Appium Desktop (1.6.2) - Android - implicitly_wait not working

### ISSUE THREAD

**Issue by KaranikasN** [appium/appium-desktop#582]
## The problem

Trying to find an element which does not exist. Appium run the findElement command and return immediately NoSuchElementException without retrying findind the element forfor implicitly_wait time.
This is not an issue using version 1.6.1.

## Appium logs
[debug] [35m[BaseDriver][39m Set implicit wait to 20000ms
[debug] [35m[MJSONWP][39m Responding to client with driver.implicitWait() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/fcede9bb-68e8-4f4a-b6cd-793772d896e4/timeouts/implicit_wait [39m[32m200[39m [90m2 ms - 76[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/fcede9bb-68e8-4f4a-b6cd-793772d896e4/element[39m
[info] [35m[HTTP][39m [90m{"using":"id","value":"com.myvodafone.android:id/btnTermsAccept","sessionId":"fcede9bb-68e8-4f4a-b6cd-793772d896e4"}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.findElement() with args: ["id","com.myvodafone.android:id/btnTermsAccept","fcede9bb-68e8-4f4a-b6cd-793772d896e4"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 20000 ms for condition
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element] to [POST http://localhost:8202/wd/hub/session/0b6d93f3-d523-412e-927b-f86786147079/element] with body: {"strategy":"id","selector":"com.myvodafone.android:id/btnTermsAccept","context":"","multiple":false}[debug] [35m[JSONWP Proxy][39m Proxying [GET /source] to [GET http://localhost:8202/wd/hub/session/0b6d93f3-d523-412e-927b-f86786147079/source] with body: {}[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"0b6d93f3-d523-412e-927b-f86786147079\",\"status\":0,\"value\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><hierarchy rotation=\\\"0\\\"><android.widget.FrameLayout index=\\\"0\\\" text=\\\"\\\" class=\\\"android.widget.FrameLayout\\\" package=\\\"com.myvodafone.android\\\" content-desc=\\\"\\\" checkable=\\\"false\\\" checked=\\\"false\\\" clickable=\\\"false\\\" enabled=\\\"true\\\" focusable=\\\"false\\\" focused=\\\"false\\\" scrollable=\\\"false\\\" long-clickable=\\\"false\\\" password=\\\"false\\\" selected=\\\"false\\\" bounds=\\\"[0,0][1080,1920]\\\" resource-id=\\\"\\\" instance=\\\"0\\\"><android.widget.LinearLayout index=\\\"0\\\" text=\\\"\\\" class=\\\"android.widget.LinearLayout\\\" package=\\\"com.myvodafone.android\\\" content-desc=\\\"\\\" checkable=\\\"false\\\" checked=\\\"false\\\" clickable=\\\"false\\\" enabled=\\\"true\\\" focusable=\\\"false\\\" focused=\\\"false\\\" scrollable=\\\"false\\\" long-clickable=\\\"false\\\" password=\\\"false\\\" selected=\\\"f...
[debug] [35m[BaseDriver][39m Error finding element: Could not proxy command to remote server. Original error: 500 - {"sessionId":"0b6d93f3-d523-412e-927b-f86786147079","status":7,"value":"An element could not be located on the page using the given search parameters."}
.
.
[error] [35m[MJSONWP][39m Encountered internal error running command:  {"w3cStatus":400,"jsonwp":{"sessionId":"0b6d93f3-d523-412e-927b-f86786147079","status":7,"value":"An element could not be located on the page using the given search parameters."}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"sessionId":"0b6d93f3-d523-412e-927b-f86786147079","status":7,"value":"An element could not be located on the page using the given search parameters."}
[error] [35m[MJSONWP][39m     at JWProxy.proxy$ (C:\Users\***\AppData\Local\appium-desktop\app-1.6.2\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
[error] [35m[MJSONWP][39m     at tryCatch (C:\Users\***\AppData\Local\appium-desktop\app-1.6.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\***\AppData\Local\appium-desktop\app-1.6.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\***\AppData\Local\appium-desktop\app-1.6.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke (C:\Users\***\AppData\Local\appium-desktop\app-1.6.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[error] [35m[MJSONWP][39m     at <anonymous>
[debug] [35m[MJSONWP][39m Matched JSONWP error code 7 to NoSuchElementError

## Environment
Appium Desktop version, version 1.6.2, Android, Windows 10, automationName = 'UiAutomator2'

**Comment by mjtimblin** [comment]
I can also confirm this issue in version 1.6.2 on macOS 10.13.6. Reverting back to Appium version 1.6.1 fixes the problem.

**Comment by KazuCocoa** [comment]
What about the latest one? (1.7.1)

**Comment by Phaseowner** [comment]
> What about the latest one? (1.7.1)

On latest Appim Desktop all works fine again
