### ISSUE TITLE
Selectors for all elements on the app show up as: "AX error -25205" 

### ISSUE THREAD

**Issue by srykn** [appium/appium-desktop#587]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Selectors for all elements on the inspector show up as "@name=AX error -25205"

I am inspecting the element locators using appium desktop. This works intermittently. 
Some times the inspector shows the correct selectors - For example: login text field selector is:  "@name=login.input.username" 
But at other times it shows the selector as  "@name=AX error -25205"

## Environment

- I am running Appium Desktop version _1.6.2_.
- I am on Mac
- iPhone Simulator: iPhone 6 - 9.3

**Comment by dpgraham** [comment]
Closing as duplicate: https://github.com/appium/appium/issues/9439

This isn't something that can be fixed on the UI side, unfortunately.
