### ISSUE TITLE
Spinning indicator keep spinning and stuck

### ISSUE THREAD

**Issue by rishbaranwal** [appium/appium-desktop#589]
## Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## Environment

- I am running Appium Desktop version  1.6.2
- I am on (pick one):
    - [ ] Mac

## The problem

I have installed appium desktop successfully on my mac book 1 and it is working properly , on my mac book 2 , I did the same step to configure the appium desktop set up, but I am stuck while starting the session, it continues to spin through long time and suddenly spinner disappears.

Environment
Appium version : 1.6.2
Desktop OS/version used to run Appium: mac OS High Sierra 10.13.4 (17E199)
Mobile platform/version under test: iOS
Real device or emulator/simulator: Real Device

## Details
After doing all the necessary configurations mentioned in following link:

https://github.com/appium/appium-xcuitest-driver
https://github.com/appium/appium-desktop/releases
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am successfully able to setup and launch the web driver agent, but it always stuck on server url line
After that, when I start the session from the appium desktop after providing the device capabilities, it always keep spinning , after certain period of time , spinner on appium desktop keep disappear.

Please find the device capabilities as image in attachment.

<img width="1192" alt="43319105-20bad152-91c1-11e8-918d-21ce9c26d6a3" src="https://user-images.githubusercontent.com/5096659/43323064-2e9a6a14-91ce-11e8-823d-bd0c7122b7f1.png">

Please help me as I am stuck here from 3 days onwards.

Link to Appium logs
No Logs is generated on Appium logs

**Comment by rsarip** [comment]
I am facing same issue with Appium version : 1.7.0 since 3 days. It was working fine last week. 
No logs, spinner spins for a while and times out. 
Were you able to find a solution for this issue?

**Comment by dpgraham** [comment]
@rsarip The spinner timing out means that the session wasn't able to be created. Are you sure there's no logs? Do the Appium Server logs not output anything during that period?

**Comment by rsarip** [comment]
@dpgraham Yes, Appium Server is not logging anything. I have tried with both iOS and Android. 

Below list that comes up when I start server- is all that I see.
[Appium] Welcome to Appium v1.9.0
[Appium] Non-default server args:
[Appium]   selendroidPort: 8082
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

P.S: It was working fine till last week with same configurations and nothing changed.

**Comment by dpgraham** [comment]
Is this still happening with the latest?

**Comment by dpgraham** [comment]
Closing. If issue persists, will re-open.

**Comment by sumanthvakacharla** [comment]
Still seeing the issue with Appium 1.12.1 No Appium logs. But the spinner spins forever on the Appium Desktop DOM tree and element locator display
