### ISSUE TITLE
Inspector session got stuck in getPageSource()

### ISSUE THREAD

**Issue by ruberzen** [appium/appium-desktop#593]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium 
Desktop issue

## The problem

When I start an inspector session, the app is launched on the device but the inspector is stuck waiting response and trying to show the screenshot/source. I press refresh button and nothing happens. It doesn't happen with Android 6.0 and older.

![image](https://user-images.githubusercontent.com/13284866/43803947-f979c218-9a5f-11e8-8ee0-6d307d5d970e.png)

The log: 
  https://gist.github.com/ruberzen/1d8b636efe5d9f4d7e7eae9081f5b0f1

NOTE: If I press the Overview button on the device and then select my app, the inspector gets the screenshot and source immediately. Otherwise, nothing happens (I just have only waited for around 30 min, not more)
 
## Environment

- I am running Appium Desktop version 1.6.2 with 1.8.1 server
- I am on:
    - [ ] Mac
    - [ ] Windows
    - [x] Linux
- Mobile platform/version: Android 8.1, 8.0, 7.1.1, 7.0
- Real device or emulator: applicable for both

**Comment by LyubomirStoimchev** [comment]
Try adding capability `waitForQuiescence` to false.

**Comment by ruberzen** [comment]
@LyubomirStoimchev :

Thanx but not worked, the same thing happens adding `waitForQuiescence: false` .

**Comment by dpgraham** [comment]
@ruberzen Can you open the dev tools (`right click + Inspect Element`), navigate to the console tab and check if there's any errors being logged to the console? I'd like to see if it's a user interface error or an Appium error.

**Comment by ruberzen** [comment]
@dpgraham :
The console is in blank. I send multiple refresh and nothing appears:
![image](https://user-images.githubusercontent.com/13284866/43868385-f565732e-9b32-11e8-8d45-3343a53ebaa0.png)

**Comment by ruberzen** [comment]
@nmccormick  I will try adding that capability and update the issue.

**Comment by lovingyu** [comment]
@ruberzen hi, have u fix this ? i have found the same problem.

**Comment by dpgraham** [comment]
Is this still happening with the latest desktop version?
