### ISSUE TITLE
Android losing IDs when navigating to a different screen and back

### ISSUE THREAD

**Issue by zmeriksen** [appium/appium-desktop#595]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When first launching the Android app through Appium Inspector. 

I am able to search and select all the elements by their IDs. However, when I go to a different page and then go back, Appium Inspector cannot find any IDs. I copied the XML and found the IDs still there.

## Environment

- I am running Appium Desktop version 1.6.3.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Have you tried refreshing the page and then searching again?

**Comment by dpgraham** [comment]
I would recommend setting `automationName=UiAutomator2` in the capabilities and try using that. This driver uses a version of Google UiAutomator that's no longer supported.

Another thing is I would recommend trying to install Appium from the CLI instead of inside the app and see if it's reproducible from the CLI.

**Comment by zmeriksen** [comment]
That seems to have fixed some of my issues, now I am getting weird behavior with the back button in Android. Thank you for your help @dpgraham. 

Closing this issue...
