### ISSUE TITLE
Fix GitHub token issue

### ISSUE THREAD

**Issue by Walther** [appium/appium-desktop#596]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Running `npm run test` errors both locally and in CI.

```
  1) updateChecker "before all" hook:
     StatusCodeError: 401 - "{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}"
      at new StatusCodeError (node_modules/request-promise-core/lib/errors.js:32:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:104:33)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)
```

Looking at the test code, `appium-desktop/test/integration/update-checker.integration-test.js:14`:

```
    const latestReleaseUrl = `https://api.github.com/repos/appium/appium-desktop/releases/latest?access_token=${process.env.GITHUB_TOKEN}`;
```

it seems that a Github token should be exported in shell / provided as an environment variable, for the test to work. However, a) need for using such environment variable is not indicated in Contributing doc b) the environment variable doesn't seem to be populated in CI either, see [example build failure](https://travis-ci.org/appium/appium-desktop/builds/413705267?utm_source=github_status&utm_medium=notification)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
I'm just going to make it skip these tests in the case that it isn't set locally. This test should only be necessary in CI.
