### ISSUE TITLE
Launching app on real iOS device failing with latest Appium Desktop version 1.6.3

### ISSUE THREAD

**Issue by ashishyadav2020** [appium/appium-desktop#597]
## Appium or Appium Desktop?
I have taken latest source code of Appium and verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue.

## The problem

I have downloaded latest Appium desktop version for Mac. While running my old test scripts which used to work with previous Appium verison, failing with:
The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'

## Environment

- I am running Appium Desktop version _1.6.3.
- I am on : Mac_10.13.6
- Last Appium version that did not exhibit the issue (if applicable): Desktop version 1.6.2
- Mobile platform/version under test: iOS 11.3
- Real device or emulator/simulator: Real device

## Details
I have checked connected real device using command:
idevice_id --list
and it shows connected real device id (single device).

Also, Added path 'idevice_id' to $PATH variable and 'echo $PATH' command showing the updated path.

I tried executing command (provided in Appium error logs as solution):
'brew install libimobiledevice --HEAD'
and, it returned with 'already installed'. Though I tried reinstall as well and getting same problem.

## Link to Appium Logs
https://gist.github.com/ashishyadav2020/088f768c0f2dd0f5f80a9e59d707ddef

**Comment by dpgraham** [comment]
Can you folks try uninstalling it, downloading it again and then installing that? I put in a hot-fix recently to resolve problems with $PATH not being read properly.

**Comment by ashishyadav2020** [comment]
@dpgraham  Thanks for your response.

Just to confirm, while checking commit in repo, some Path fixes (made by you) was not included in latest release. https://github.com/appium/appium-desktop/compare/v1.6.3...master

Should we wait for next release, please confirm.

**Comment by ashishyadav2020** [comment]
@dpgraham Thanks for clarifying. I'll give it a try and confirm.
