### ISSUE TITLE
Click on the error appium-inspector swipe by Coordinates and tap by Coordinates

### ISSUE THREAD

**Issue by evezhou** [appium/appium-desktop#598]
appium 
version： 1.6.2 (1.6.2)

![image](https://user-images.githubusercontent.com/42266927/43948594-cd344cc2-9cbd-11e8-8cde-cf7eb7ddc9a0.png)
![image](https://user-images.githubusercontent.com/42266927/43948666-012cb82a-9cbe-11e8-8533-5ff99b7e9c16.png)

**Comment by dpgraham** [comment]
Closing. Will re-open if logs provided.
