### ISSUE TITLE
"npm start" fails with Cannot find module "../../package.json" error

### ISSUE THREAD

**Issue by WeirdGuyInRowOne** [appium/appium-desktop#6]
[npm-debug.log.txt](https://github.com/appium/appium-desktop/files/633170/npm-debug.log.txt)

**Comment by jlipps** [comment]
Did you run `npm install` and `npm run build` first?

The best way to try things out right now anyway is to run `npm run dev`

**Comment by WeirdGuyInRowOne** [comment]
Used npm run dev and worked like a charm! Thanks for your help.
