### ISSUE TITLE
Inspector: Recording function cannot work

### ISSUE THREAD

**Issue by xlion922** [appium/appium-desktop#601]
## Appium or Appium Desktop?
Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Recording function cannot work. when press recording button, no any window panel appear, and there are errors happen as show [..actionframework] not a constructor. and no any actions can be recorded.
## Environment

- I am running Appium Desktop version _1.8.1_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Can you provide screenshots and examples of recordings that are broken?

**Comment by xlion922** [comment]
![image](https://user-images.githubusercontent.com/7436531/44126364-6c6a611e-a06a-11e8-959f-19227b90fe50.png)

Error screen shot.  Thanks!

**Comment by xlion922** [comment]
When press recording button, no recording panel appeared as normal.
![image](https://user-images.githubusercontent.com/7436531/44126551-927cd07a-a06b-11e8-8df6-1ba84de5d9a5.png)

**Comment by dpgraham** [comment]
Does that error happen right after you press the recording button?

**Comment by xlion922** [comment]
yes. after press recording button, the "Recorder" panel cannot appear.

**Comment by xlion922** [comment]
Resolved by reinstall iOS-deploy and Appium.
