### ISSUE TITLE
Too many /session requests

### ISSUE THREAD

**Issue by mariusnita** [appium/appium-desktop#609]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop 1.6.x inspector issues `/wd/hub/session/<session_id>` requests every couple of seconds. It does not wait for the previous one to finish before issuing the next one. If these requests start to pile on top of each other, Appium can become unresponsive. Appium Desktop should space these commands out in time and always wait for the previous to finish before issuing the next.

## Environment

- I am running Appium Desktop version 1.6.2 and 1.6.1
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

cc @jlipps

**Comment by mariusnita** [comment]
I observed AD 1.6.x causing appium 1.8.x to become totally unresponsive when WDA `/source` requests take too long -- which is an ongoing performance issue with WDA in some situations. Appium goes into a state where it just logs the incoming getSession() requests and is no longer replying.

**Comment by dpgraham** [comment]
I'm not sure if we can do anything to fix this on the Appium Desktop size because we need to get the `/source` and `/screenshot` whenever there's a change of the app state.

Does the desktop application not lock up to wait whenever there's a /source call? It should wait until each /source is done before issuing another request.

**Comment by mariusnita** [comment]
> Does the desktop application not lock up to wait whenever there's a /source call? It should wait until each /source is done before issuing another request.

Precisely this. Appium Desktop keeps sending `getState` requests without waiting for previous requests to complete. A normal situation would be like this
```
--> getSource
<-- reply to getSource
--> getState
<-- reply to getState
--> getState
<-- reply to getState
```
But what happens now is
```
--> getSource # takes a long time
--> getState # doesn't wait for getSource to complete
--> getState # doesn't wait for the previous 2 to complete
--> getState # ... and so on ...
```

**Comment by dpgraham** [comment]
Okay, I think I may know why.

Do you mind sending me some logs?
