### ISSUE TITLE
iOS simulators launched by appium-desktop does not allow Mac Keyboards to interact with them

### ISSUE THREAD

**Issue by jmehtaebates** [appium/appium-desktop#61]
I launched the simulators via appium-desktop GUI as well as the older appium GUI. The  configurations used were exact same in both the cases (iOS 10.0 and iPhone 7)

The iOS simulators launched by appium-desktop does not allow Mac keyboard to interact with them where as the older one used to allow.

Can we please enable this feature again?

**Comment by jlipps** [comment]
I don't understand what you're saying, @jmehtaebates. Can you be more specific about what's not working, perhaps attaching screenshots?

**Comment by jmehtaebates** [comment]
Not sure how do I attach screenshots for this issue. So when I start a new session from appium-desktop, my physical keyboard can no longer interact with the simulator
e.g: on login screen, I am not able to type using my physical keyboard 

With the same simulator configs launched via the older GUI, I am able to interact with my app from my physical keyboard.
e.g: I am able to enter email/password from physical keyboard

**Comment by jlipps** [comment]
OK, I was able to reproduce what you're talking about. I have no idea why launching the sim from within Appium Desktop would affect the ability to use the keyboard with it. I'll keep this issue open to see if we can fix it. Meanwhile, a workaround is to use the software keyboard provided by the simulator.

**Comment by jmehtaebates** [comment]
Thank you. Only issue being the soft keyboard in the simulator is time consuming for debug/test purposes during automation development.

**Comment by imurchie** [comment]
Please try the `connectHardwareKeyboard` capability (set to `true`).

**Comment by jlipps** [comment]
Confirmed that setting `connectHardwareKeyboard` to `true` fixes the issue. maybe we should set that to `true` by default for the inspector?

**Comment by imurchie** [comment]
Yes, that sounds like a reasonable thing to do.

**Comment by jmehtaebates** [comment]
Thank you @imurchie  and @jlipps
