### ISSUE TITLE
Start Session error when  connecting to  company's network  using proxy server   

### ISSUE THREAD

**Issue by 141801** [appium/appium-desktop#610]
appium-desktop 1.6.4

error popup with message as follows 
 (message is company's proxy server login page)
![2018-08-23 16 00 44](https://user-images.githubusercontent.com/42635299/44511690-4afa9500-a6f3-11e8-92d7-a8978133a1d4.png)

I have tried do not using proxy when localhost but it not work
![2018-08-23 16 40 30](https://user-images.githubusercontent.com/42635299/44511672-40400000-a6f3-11e8-957b-767ea637b06a.png)

if I turn off the wifi , another error popup
![2018-08-23 16 44 04](https://user-images.githubusercontent.com/42635299/44511903-e0962480-a6f3-11e8-8afe-82e03e8e42ca.png)

**Comment by 141801** [comment]
![2018-08-23 16 00 44](https://user-images.githubusercontent.com/42635299/44511504-c6a81200-a6f2-11e8-875a-caaf95329021.png)

**Comment by dpgraham** [comment]
I think it's probably a firewall issue, which I don't think we can resolve.

**Comment by benfr1** [comment]
Reproduced on 1.11.1
I think it would be nice to provide a workaround at least in documentation ; I am working on it now
