### ISSUE TITLE
"Failed to locate element" when running the script on Android 7.0

### ISSUE THREAD

**Issue by jumurill** [appium/appium-desktop#613]
## Appium or Appium Desktop?

Appium Desktop

## The problem

I am new to Appium. Need assistance to solve the problem I encountered on Android 7.0. I have this line below in my code:

driver.findElement(By.id("com.testapp:id/button_addDevice")).click();

This is working on Android 5.0 and 6.0. But in Android 7.0, appium returned "Failed to locate element". Tried upgrading to uiautomator2 using "npm install appium-uiautomator2-driver", but I get some error on the console.

Hope you can help me on this so that I can continue my Android 7.0 script. Thanks!

## Environment

- I am running Appium Desktop version _v1.6.3_.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
You probably need to set `automationName=UiAutomator2` or you need to check the hierarchy to see if the ID is different on Android 7.0

I recommend discuss.appium.io for questions like this
