### ISSUE TITLE
can not update from 1.6.3 to 1.7.0 keep on getting error "Failed to download.."

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-desktop#617]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1.  I've got Appium desktop version 1.6.3 and tried updating to 1.7.0
2. I tried closing, re-opening multiple times to update but each time getting same error
3. There is no progress bar shown for downloading
Please refer to screenshot attached
<img width="652" alt="screen shot 2018-09-06 at 4 22 25 pm" src="https://user-images.githubusercontent.com/308490/45163840-82883780-b1f1-11e8-8a50-8c67c8ebd8bf.png">

## Environment

- I am running Appium Desktop version _<1.6.3>_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Also, we killed the progress bar because we switched the update server recently.

Can you check if this url works? https://hazel-server-pxufsrwofl.now.sh/update/mac/1.1.1

**Comment by vikramvi** [comment]
@dpgraham Thanks for looking into this issue, please find below updates

> Thanks for letting me know. Does it work if you download directly from releases? https://github.com/appium/appium-desktop/releases

In this case won't I loose existing settings, e.g. Saved capabilities etc ?

> Also, we killed the progress bar because we switched the update server recently.
> 
> Can you check if this url works? https://hazel-server-pxufsrwofl.now.sh/update/mac/1.1.1

url just open new tab with content as per screenshot, is this expected result ?

<img width="1436" alt="screen shot 2018-09-07 at 10 30 06 am" src="https://user-images.githubusercontent.com/308490/45207724-10633180-b289-11e8-936f-b2d7ad3ab869.png">

**Comment by dpgraham** [comment]
@vikramvi I'm almost 100% sure that it doesn't, but I'll test it on my machine to be safe.

And yes, the result is expected.

**Comment by dpgraham** [comment]
I just tested it. The settings get saved.

**Comment by vikramvi** [comment]
@dpgraham Thanks for clarification, so auto-upgrade not working a regression ? 

I tried direct download from https://github.com/appium/appium-desktop/releases and it kept on failing multiple times for 1.7.0 dmg file in Germany.

**Comment by dpgraham** [comment]
@vikramvi is it possibly a firewall issue? Have you tried on a non-corporate network? I have colleagues in Berlin who use A.D. and I haven't heard of any issues of downloading problems.

**Comment by vikramvi** [comment]
I tried from home internet and not from office network. May be network issue in downloading 200 MB file. Is somebody else also reported this issue or is it only me for now ?

**Comment by dpgraham** [comment]
Nobody else reported it.

**Comment by vikramvi** [comment]
Thanks for update, then I'll close the issue for now.
