### ISSUE TITLE
Touches dosen't work for elements inside web frame in hybrid iOS application.

### ISSUE THREAD

**Issue by Biloleg** [appium/appium-desktop#622]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

Touches dosen't work for elements inside web frame in hybrid iOS application.
If you try to send touch to any web element (checkbox, button, etc..) in web frame inside hybrid iOS application you will get two possible behaviour:
- page will swipe and click not happens
- just nothing happens
NOTE: work correct in Appium 1.6.3

## Environment

- I am running Appium Desktop version 1.7.0.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Unfortunately we don't support web in Appium Desktop. We only support native contexts. I would recommend using devtools to navigate your hybrid app.

**Comment by Biloleg** [comment]
Elements inside web frame recognize by appium like a native. But click doesn't work in 1.7.0

**Comment by dpgraham** [comment]
Hybrid apps report HTML elements inside of webviews as native elements. However, the interactions with these elements aren't always reliable and we don't have any way of resolving any problems you have them. That's why it's recommended you switch to a webview context (best way is to set `autoWebview` capability to true) and it will use Selenium.
