### ISSUE TITLE
appium desktop 1.7.0 Start session ERROR with "capabilities must include either 'appPackage' or 'browserName'"

### ISSUE THREAD

**Issue by 317174106** [appium/appium-desktop#624]
windows, appium desktop 1.7.0, java client 6.1.0

when i try to start a session, i get error "capabilities must include either 'appPackage' or 'browserName'",
why ? I really give the appPackage parameter.

And the same code works fine with appium desktop 1.6.3!

		AndroidCapabilities.setCapability("deviceName", deviceName);
		AndroidCapabilities.setCapability(AndroidMobileCapabilityType.PLATFORM_NAME, "Android");
		AndroidCapabilities.setCapability("recreateChromeDriverSessions", true);
		AndroidCapabilities.setCapability("autoWebviewTimeout", 5000);
		AndroidCapabilities.setCapability("noReset", true);
		AndroidCapabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, appPackage);
		AndroidCapabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, appActivity);
		AndroidCapabilities.setCapability("useKeystore", true);
		AndroidCapabilities.setCapability("keystorePath", keystore.getAbsolutePath());
		AndroidCapabilities.setCapability("keystorePassword", "CtripAndroid");
		AndroidCapabilities.setCapability("keyAlias", "******");
		AndroidCapabilities.setCapability("keyPassword", "******");
		AndroidCapabilities.setCapability("unicodeKeyboard", true);
		AndroidCapabilities.setCapability("resetKeyboard", false);
		AndroidCapabilities.setCapability("clearSystemFiles", true);
		AndroidCapabilities.setCapability("ignoreUnimportantViews", false);
		AndroidCapabilities.setCapability("autoGrantPermissions", true);
		AndroidCapabilities.setCapability("newCommandTimeout", 90);
		driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), AndroidCapabilities);

[Appium] Creating new AndroidDriver (v3.7.0) session
[Appium] Capabilities:
[Appium]   browserName: android
[Appium]   platform: ANDROID
[Appium]   platformName: android
[Appium]   version: 
[Appium]   appActivity: ctrip.business.splash.CtripSplashActivity
[Appium]   appPackage: ctrip.android.view
[Appium]   autoGrantPermissions: true
[Appium]   autoWebviewTimeout: 5000
[Appium]   clearSystemFiles: true
[Appium]   deviceName: emulator-5554
[Appium]   ignoreUnimportantViews: false
[Appium]   keyAlias: ****
[Appium]   keyPassword: ******
[Appium]   keystorePassword: ******
[Appium]   keystorePath: E:\workspace\vacation_autotest_ui\configuration\android.keystore
[Appium]   newCommandTimeout: 90
[Appium]   noReset: true
[Appium]   recreateChromeDriverSessions: true
[Appium]   resetKeyboard: true
[Appium]   unicodeKeyboard: true
[Appium]   useKeystore: true
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"appActivity":"ctrip.busin... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform, version.
[AndroidDriver] **Error: The desired capabilities must include either 'appPackage' or 'browserName'**
[AndroidDriver]     at Object.wrappedLogger.errorAndThrow (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[AndroidDriver]     at Object.helpers.validateDesiredCaps (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:705:14)
[AndroidDriver]     at AndroidDriver.validateDesiredCaps (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:470:20)
[AndroidDriver]     at AndroidDriver.callee$0$0$ (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:45:8)
[AndroidDriver]     at tryCatch (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[AndroidDriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (d:\Users\c_xian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)

**Comment by dpgraham** [comment]
@317174106 The wording in the logs is confusing. I put in a PR to update the verbiage.

The problem is that you can't have both a `browserName` _and_ an `appPackage`, it needs to be one or the other.

Based on your provided code, it looks like the browser name is being added automatically. Is this correct? The Appium java-client shouldn't be adding a `browserName` automatically.

If that is what it's doing, I think a workaround would be setting the `browserName` to `null`.

**Comment by 317174106** [comment]
yeah,  the browser name is added automatically.

I set the browserName to "", and it works ! 

BTW, i don't need to set this in 1.6.3, is this a bug or some new feature in 1.7.0 ?

**Comment by dpgraham** [comment]
@317174106 Yeah I think we may have added a check in the latest Appium version (1.9.0) that it should not have `browserName` _and_ an `app`.

I've made a PR to make the logging less confusing, but I don't think we'll change this. I'll bring it up with the Java client team though that we shouldn't be adding `browserName` automatically.

**Comment by VinothVinodhan** [comment]
Hello,
You can remove appPackageName line and follow the below suggestions,
You dont have to use BrowserName & appPackageName capabilities.
rather use only app and mention the location alone.

For example, I'm working on amazon app, where I received same exception

DesiredCapabilities capabilities = new DesiredCapabilities.android();
capabilities.setCapability(MobileCapabilityType.APP, "D:\\Amazon_shopping.apk");		capabilities.setCapability("appActivity", "com.amazon.mShop.home.HomeActivity");		capabilities.setCapability("appWaitActivity", "com.amazon.mShop.home.web.MShopWebGatewayActivity");
