### ISSUE TITLE
Appium Failed to identify the elements

### ISSUE THREAD

**Issue by mali5590** [appium/appium-desktop#626]
## Appium or Appium Desktop?

**Appium Desktop**

## The problem
Find elements failed to identify the object
Issue is only with the Appium 1.9 Version  when i downgrade to 1.8 it works fine as expected
## Environment

- I am running Appium Desktop version _<1.9>_.
- I am on (pick one):    - Mac

**Comment by dpgraham** [comment]
I'll need more details. Can you open a new issue with the server logs, description of issue and screenshots (if needed).
