### ISSUE TITLE
Error:Could not start session in appium desktop

### ISSUE THREAD

**Issue by archanarathnam** [appium/appium-desktop#627]
I am getting error saying “Could not start session”

Environment
Appium version (or git revision) that exhibits the issue: 1.9.0
Desktop OS/version used to run Appium: Windows 10
Mobile platform/version under test: 8.0.0
Real device or emulator/simulator: Real device
Details
Have added the following capabilities as per below image

![1](https://user-images.githubusercontent.com/37412798/45631915-f9e08580-ba93-11e8-8176-46710b771c0b.png)
Squid proxy server is running in the background with port 3128

When I try to access http://localhost:4723/wd/hub/status, I am getting below response -
{“status”:0,“value”:{“build”:{“version”:“1.9.0”}},“sessionId”:null}

but when I start session in appium desktop, it says Error:Could not start session

Can you please let me know why this is happening.

**Comment by imurchie** [comment]
What is in the server logs display?

**Comment by patrickbremm** [comment]
Hello,

I recommend you do different, pass the capabilities on new AndroidDriver ();

Appium Desktop manages automated testing on more than one device.

**Comment by archanarathnam** [comment]
> What is in the server logs display?

Server logs doesn't show anything as we are getting error 'Could not start session'

**Comment by dpgraham** [comment]
@archanarathnam There still should be logs in the window where you started the server.
