### ISSUE TITLE
Unable to get App Source in Appium Inspector if page has too many elements.

### ISSUE THREAD

**Issue by vagisha1989** [appium/appium-desktop#629]
##  Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am working on automation of an IOS application. When I am trying to launch it through appium desktop Inspector then application is getting launched but I am unable to get Appsource on Inspector. I can't find its xpath as elements are not shown as part of Appsource. This is happening only on those pages which have too many elements and appium is loading all the elements at once rather than loading only those which are visible on screen.

Please find screenshots:
<img width="1680" alt="screen shot 2018-09-24 at 5 03 05 pm" src="https://user-images.githubusercontent.com/43541837/45953956-b1d5db80-c01c-11e8-8fa6-eb31ef8d3727.png">
<img width="1680" alt="screen shot 2018-09-20 at 5 17 01 pm" src="https://user-images.githubusercontent.com/43541837/45953971-bb5f4380-c01c-11e8-8291-1dd6c3339b53.png">

- I am running Appium Desktop version _<V1.8.1>_ & _<V1.9.0>_.
- I am on:
    - [ ] Mac

**Comment by dpgraham** [comment]
Can you post the Appium logs for when it calls `/source`?

Also, as a workaround, you can maybe try running Appium from the command line and pointing to it in inspector using the `Custom Server` tab.

**Comment by yadavanand** [comment]
@vagisha1989 Did you find any solution to this problem

**Comment by shenjianyun** [comment]
I'm also encountering this issue

**Comment by shinde02** [comment]
Will you open this issue again? ..... I am encountering the same error.
