### ISSUE TITLE
NO ACCESS TO /private/var/folders/d9/

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium-desktop#63]
When I am trying to run the appium.app, it is trying to download dependencies (it is executing /bin/bash Scripts/bootStrap.sh -d) and its failing as it doesnot have access to /private/var/folders/d9/.

Gist of logs [https://gist.github.com/pavanbachu0604/3050c2553800e1b79b742523ee3fcefc](url)

Methods tried : 
1. sudo chmod -R 777 /path/mentioned
2. sudo chown -R 777 /path/mentioned 

Failure Message : Read-only file system

**Comment by jlipps** [comment]
@pavanbachu0604 you can't run Appium Desktop from the DMG. ensure you copy it to your file system before running it.

**Comment by pavanbachu0604** [comment]
@jlipps What do you mean by copying it to you file system ?
