### ISSUE TITLE
New release that uses Appium Server 1.9.1

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium-desktop#630]
Hello,

Is there any release scheduled that would include Appium Server 1.9.1?

We would need it in order to use the latest version of https://github.com/Microsoft/WinAppDriver/releases.

Or is there any "friendly" way to point the Appium Desktop to a different Appium Server version on Windows (and Mac OS as well, for that matter)?

Thank you,
Cosmin

**Comment by dpgraham** [comment]
In the latest.
