### ISSUE TITLE
Appium-Desktop 1.6.3 error AdbExec   exited with code 3221226356

### ISSUE THREAD

**Issue by robsonhamilton** [appium/appium-desktop#631]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Hi,
I'm running Appium-Desktop 1.6.3 on Windows 10 machine.
I'm using an AVD with Android 6.0 for test.

When I start a session, Appium-Desktop stops with this error:

[MJSONWP] Encountered internal error running command: Error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command 'C\:\\Android_Studio_SDK\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell echo ping' exited with code 3221226356'; Stderr: ''; Code: '3221226356''. Retrying by restarting ADB
[MJSONWP]     at ADB.callee$1$0$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:723:13)
[MJSONWP]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 15082 ms - 421
[HTTP] 

My session settings:

app: C:\Users\Public\Downloads\Apk_SICVC\SICVC-2408.apk
deviceName: Nexus_4_API_23
platformName: Android

The log and session print

[log_appium_163_avd_23.txt](https://github.com/appium/appium-desktop/files/2412679/log_appium_163_avd_23.txt)

![log_appium_163_avd_23](https://user-images.githubusercontent.com/43553383/45976261-a8e50a00-c01c-11e8-8c5c-754ddfb5785a.png)

## Environment

- I am running Appium Desktop version 1.6.3.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows 10
    - [ ] Linux

Can you help me?
Thx.

**Comment by dpgraham** [comment]
I don't think this is an Appium Desktop issue but rather an Appium android setup issue you're having. Similar to this: https://github.com/appium/appium/issues/9664
