### ISSUE TITLE
Add supporting to open Inspector for existing session

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium-desktop#64]
I think that it would be useful to have one feature from the old appium desktop. 

When we have started appium server from CLI and we had session on it (e.g. opened by java client), we can open Inspector for this session.

Thank you.

**Comment by jlipps** [comment]
Yes, attaching to an existing session ID sounds useful. Thanks!

**Comment by dpgraham** [comment]
I agree, this is a good idea.
