### ISSUE TITLE
Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install

### ISSUE THREAD

**Issue by ronjonesjr** [appium/appium-desktop#650]
## The problem

Install Appium Desktop 1.7.1, run a test, and you get an error "Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install".   None of the versions of WinAppDriver seem to work with this version of Appium Desktop.  Please add the target version of WinAppDriver that's required into the error message.

## Environment

- I am running Appium Desktop version _1.7.1_.
- I am on (pick one):
    - [ ] Mac
    - [x ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Have you tried running WinAppDriver from the command line and then using the Appium custom server?

**Comment by ronjonesjr** [comment]
Nope....but it works now that I figured out the right version of WinAppDriver to use.  I don't think that would work either though as the real issue is that Appium Desktop seems to require a very specific version of WinAppDriver.

**Comment by ronjonesjr** [comment]
Sorry, didn't mean to close the issue.

**Comment by dpgraham** [comment]
@ronjonesjr Appium Desktop is agnostic to which version is used so it shouldn't make a difference. It's probably Appium itself that has that restriction.
