### ISSUE TITLE
Appium Desktop does not start a session

### ISSUE THREAD

**Issue by rsarip** [appium/appium-desktop#653]
[x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

Problem: 
When I start Appium server from desktop and select a capability to start session, it just shows loading symbol (spinner) and times out after a while. It neither starts the session not displays any logs. Unable to find the issue as it does not show any error or logs. 

This is all I see on the console:
[Appium] Welcome to Appium v1.9.0
[Appium] Non-default server args:
[Appium]   selendroidPort: 8082
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

## Environment
- I am running Appium Desktop version 1.7.0, server 1.9.0.
- I am on Mac

![image](https://user-images.githubusercontent.com/43855805/46491370-8f8c4c80-c7d8-11e8-87a7-c41a12a28054.png)

**Comment by dpgraham** [comment]
What does the Appium Server output while it's loading? Does it not do anything?

**Comment by rsarip** [comment]
It does literally nothing.. As I mentioned in description, these 4 are the only lines that are displayed.

**Comment by zhaoxiaguo** [comment]
i have the same issues
![image](https://user-images.githubusercontent.com/33721167/46717028-c6f76f00-cc98-11e8-884b-245802e8a4da.png)

**Comment by rsarip** [comment]
My issue was Appium was unable to tunnel through proxy. I had to play with proxy settings to get it work. But it would have been nice if it logged something.
@dpgraham : I am unable to install Appium chromedriver it is giving me "Unable to verify first certificate error"

**Comment by dpgraham** [comment]
I doubt I'll have time to work on logging for that, but if somebody else wants to do it, they can take that up.
