### ISSUE TITLE
Neither its giving accessibility ids nor relative xpath for some elements of a hybrid app (Real device)

### ISSUE THREAD

**Issue by prateeksomani** [appium/appium-desktop#655]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I am automating an hybrid app in real ios device (from 9.2 to 11.1 iOS)
I have used latest WDA and Latest appim desktop (1.7.1) with server 1.9.1(started from desktop only)
Mac version is 10.12.6 and xcode is 9.2

For some of the element Appium desktop is identifying accessibility ids and correct relative xpath
but for some object its not identifying properly (mainly for webdialog or if you have more than one XCUIElementTypeother)
Please find attached screen shot.
For Incorrect object screen shot look like below screenshot:-

![incorrect object identification](https://user-images.githubusercontent.com/31627873/46528907-d0707980-c849-11e8-8d7f-17492c22ad5f.png)

For correct object its look like below screenshot:-

![correct identification of object](https://user-images.githubusercontent.com/31627873/46528957-f5fd8300-c849-11e8-9eb8-1e3397b36ee7.png)
Environment

- I am running Appium Desktop version :-1.7.1 appium desktop (Latest WDA and 1.9.1 server)
 - I am on Mac 10.12.6   -

**Comment by prateeksomani** [comment]
@dpgraham Please help me in this issue

**Comment by prateeksomani** [comment]
@dpgraham In the same view or page I am able to inspect two elements properly.but for third element I am facing issue.( both screen shots attached above)
Also with downgraded appium desktop which uses uiautomation I am able to inspect all elements properly

**Comment by dpgraham** [comment]
@prateeksomani uiautomation is different from xctest and is no longer supported by Apple. I would expect both to report different app hierarchies.

**Comment by prateeksomani** [comment]
@dpgraham  i can also identity same element by using appium desktop 1.5.0 and appium server 1.7.2 using xcuitest technology. But after upgrading to desktop 1.7 and server 1.9.1. My element visibility is coming false and I am unable to locate using accessibility id or xpath.

**Comment by dpgraham** [comment]
It probably uses a different underlying version of XCUITest which is reporting the element differently than before. Since it's web, the reporting of elements isn't always consistent.

**Comment by prateeksomani** [comment]
@dpgraham  My app is hybrid but it will not open in web browser.It is an ipa file. earlier all objects are identifying by using appium desktop but the current version i am unable.Please help me.

**Comment by dpgraham** [comment]
It's an XCUI issue. We don't have control over what elements get reported.

**Comment by dpgraham** [comment]
Try installing the latest beta and running it from terminal.
