### ISSUE TITLE
Appium desktop went black screen and not responding

### ISSUE THREAD

**Issue by xiezhuokui** [appium/appium-desktop#660]
![screenshot1](https://user-images.githubusercontent.com/25716834/46572789-31b95980-c9be-11e8-9046-21648d155dfe.png)
![screenshot2](https://user-images.githubusercontent.com/25716834/46572791-38e06780-c9be-11e8-9e66-dc7feabd46a7.png)

I am running Appium Desktop version1.7.1 on Windows 10 64bit.

In the benning, I uploaded two screenshots. After launching Appium, the interface start blinking and went black in the end, buttons are totally not working. Not responding at all! Could anybody help me with it?

**Comment by dpgraham** [comment]
Can you try right-clicking and choosing `Inspect Element` to see if any errors are being logged to console.
