### ISSUE TITLE
I can't find the elements by id of elements

### ISSUE THREAD

**Issue by ancining** [appium/appium-desktop#664]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
 
![image](https://user-images.githubusercontent.com/26423615/46710600-29417700-cc7b-11e8-8ec3-111628e517a6.png)

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<1.9.1>_.
- I am on (pick one):
    - [ ] Windows

**Comment by DayGitH** [comment]
This seems to be an issue in Appium, and not in Appium Desktop. You could probably get help at https://discuss.appium.io/
