### ISSUE TITLE
Emoji in TextView widget breaks Appium Inspector

### ISSUE THREAD

**Issue by DayGitH** [appium/appium-desktop#666]
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
When there is an emoji on-screen on an android device in a TextView widget, the appium inspector throws a parsererror. I have attempted this in Appium Desktop versions 1.6.3, 1.7.0, and 1.7.1 and on multiple apps with the same result.

The following is a demonstration of this issue. The parser works as expected on this page:
![capture1](https://user-images.githubusercontent.com/6502562/46772079-26f71100-ccab-11e8-9457-7f32c464cefe.PNG)

When emoji are added to the page, the parser breaks:
![capture2](https://user-images.githubusercontent.com/6502562/46772086-2b232e80-ccab-11e8-9a5b-1d14550219f3.PNG)

## Environment

- I am running Appium Desktop version 1.7.1 (Also attempted on 1.6.3 and 1.7.0).
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by DayGitH** [comment]
I tested automationName: 'Appium' in code to see if that was the issue. My code is able to access and parse textView elements as shown below. I ran the following code:

    driver.start_activity('com.samsung.android.app.memo', 'com.samsung.android.app.memo.Main')
    for el in driver.find_elements_by_class_name('android.widget.TextView'):
        print(el)
        print(el.text)

And it gave the following result:

    <appium.webdriver.webelement.WebElement (session="e810999f-246f-4120-a627-c504fd09b9b4", element="1")>
    All memos
    <appium.webdriver.webelement.WebElement (session="e810999f-246f-4120-a627-c504fd09b9b4", element="2")>
    Emoji 😎😎😎
    <appium.webdriver.webelement.WebElement (session="e810999f-246f-4120-a627-c504fd09b9b4", element="3")>
    Test

This is proof that the issue is not in Appium, but in Appium desktop.

**Comment by dpgraham** [comment]
@DayGitH yeah, it's probably an XML parsing issue.

The logs should have a return for the call to `/source` which will contain the app's source XML. Can you post that on here (scrub out any private details first, if necessary) and then I can re-create this issue and make a workaround?

**Comment by DayGitH** [comment]
This is the call to source without emoji:
[no_emoji.log](https://github.com/appium/appium-desktop/files/2521224/no_emoji.log)

and this is the call to source with emoji:
[emoji.log](https://github.com/appium/appium-desktop/files/2521227/emoji.log)

These were taken on the Samsung Memo app (the app in the screenshots from the screenshots in my previous comments). The source was taken on the main page of the app so it will be different from the screenshots.

**Comment by dpgraham** [comment]
I can reproduce this now. Working on a patch now.

**Comment by DayGitH** [comment]
@dpgraham Any update on this?

**Comment by dpgraham** [comment]
@DayGitH Have you tried the most recent version? I put in a fix for this.

**Comment by dpgraham** [comment]
Let me know if that fixes it.

**Comment by DayGitH** [comment]
Apologies. I will try it and update the ticket.

**Comment by dpgraham** [comment]
No problem. My bad for not updating this issue.

**Comment by DayGitH** [comment]
I can confirm that the XML is being parsed properly with emojis on screen.
