### ISSUE TITLE
Extra browser capability appears and session cannot be created

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium-desktop#667]
## Appium or Appium Desktop?
Appium Desktop

## The problem

I'm trying to start appium desktop for an android device using capabilities and appium desktop:
```
{
"platformName": "android",
"platformVersion": "7",
"deviceName": "huawei",
"app": "C:\automation\yamba-debug.apk",
"automationName": "uiautomator2",
"udid": "a350b460"
}
```
and i get
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' can't be blank

In logs i can see that some capabilities are put by default, especially:
[Appium] browserName: firefox
which can be the source of the problem.

Did something changed in latest version? 

Logs:
https://gist.github.com/vjmaiky/0e2109d830d2fbb0f9eaf4251500b3d9

## Environment
Windows x64, Appium desktop 1.7.1, Appium server 1.9.1, Real Android device, Android 7 and 6

- I am running Appium Desktop version _<1.7.1>_.
- I am on (pick one):
    - [ ] Mac
    - [x ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Try setting `browserName=""`

Sometimes Selenium clients add browserName automatically.

**Comment by vjmaiky** [comment]
still not; same error

**Comment by dpgraham** [comment]
Are you using the Java client?
