### ISSUE TITLE
Appium Inspector display  Invalid number value (infinite) in JSON write

### ISSUE THREAD

**Issue by willisfeng** [appium/appium-desktop#680]
Appium Desktop Version: 1.8.0
Mac Version: Mac OS Sierra 10.13.4
xcode Version: 9.4
------------------------------------------------------
Could not obtain source: {"cause":{"sessionId":"2e37f6b4-a6bb-49be-bbd3-cf6855d10b95","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: Invalid number value (infinite) in JSON write\n\n(\n\t0 CoreFoundation 0x00000001062461ab __exceptionPreprocess + 171\n\t1 libobjc.A.dylib 0x00000001058dbf41 objc_exception_throw + 48\n\t2 CoreFoundation 0x00000001062bacb5 +[NSException raise:format:] + 197\n\t3 Foundation 0x0000000105336278 _writeJSONNumber + 366\n\t4 Foundation 0x00000001052e6952 _writeJSONValue + 495\n\t5 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t6 CoreFoundation 0x00000001061d4604 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 164\n\t7 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t8 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t9 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t10 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t11 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t12 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t13 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t14 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t15 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t16 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t17 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t18 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t19 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t20 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t21 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t22 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t23 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t24 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t25 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t26 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t27 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t28 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t29 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t30 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t31 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t32 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t33 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t34 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t35 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t36 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t37 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t38 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t39 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t40 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t41 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t42 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t43 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t44 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t45 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t46 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t47 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t48 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t49 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t50 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t51 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t52 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t53 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t54 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t55 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t56 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t57 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t58 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t59 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t60 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t61 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t62 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t63 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226\n\t64 Foundation 0x0000000105335c87 _writeJSONObject + 483\n\t65 Foundation 0x00000001052e6e6f ___writeJSONArray_block_invoke + 130\n\t66 CoreFoundation 0x00000001061d30bf -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 223\n\t67 Foundation 0x00000001052e6b5b _writeJSONArray + 305\n\t68 Foundation 0x0000000105336084 ___writeJSONObject_block_invoke + 176\n\t69 CoreFoundation 0x00000001061caea2 -[__NSDictionaryM

**Comment by dpgraham** [comment]
This looks a bug XCUITest Driver issue.

Can you open an issue in https://github.com/appium/appium/issues and make sure to follow the issue creation instructions _completely_ in order to get help.
