### ISSUE TITLE
appium web driver element.clear() didn't work

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium-desktop#684]
let element = await driver.elementByAccessibilityId('textUserName');
  await element.clear();
 
the textfield in the iOS simulator didn't get clear
the appium log shows:
   
[debug] [MJSONWP] Calling AppiumDriver.clear() with args: ["2E000000-0000-0000-D8BD-000000000000","ab553dd1-e381-4fec-9004-471f891c754c"]
[debug] [XCUITest] Executing command 'clear'
[debug] [JSONWP Proxy] Matched '/element/2E000000-0000-0000-D8BD-000000000000/clear' to command name 'clear'
[debug] [JSONWP Proxy] Proxying [POST /element/2E000000-0000-0000-D8BD-000000000000/clear] to [POST http://localhost:8100/session/1B730C1F-2DDF-4C35-A7E9-4D3DC9C83AB4/element/2E000000-0000-0000-D8BD-000000000000/clear] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"status\" : 0,\n  \"id\" : \"2E000000-0000-0000-D8BD-000000000000\",\n  \"value\" : \"\",\n  \"sessionId\" : \"1B730C1F-2DDF-4C35-A7E9-4D3DC9C83AB4\"\n}"
[debug] [MJSONWP] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/ab553dd1-e381-4fec-9004-471f891c754c/element/2E000000-0000-0000-D8BD-000000000000/clear 200 75 ms - 76

## Environment

MacOS: 10.13.6
appium: 1.9.1
wd: 1.11.1

**Comment by dpgraham** [comment]
This isn't a GUI problem. This would be a Appium CLI problem.
