### ISSUE TITLE
webview

### ISSUE THREAD

**Issue by nixuewei** [appium/appium-desktop#685]
## Appium Desktop

I try to test Hybrid case. I use python script to login native app and switch webview successfully.  But when I use Java to switch. It always stop to be timeout.  I have try many times.  seems NOK.

I use the same Appium Server and Real Android phone

## The problem
I use below two way, all of them are failed.
cap.setCapability("androidProcess", "com.tencent.mm:tools");
or 
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("androidProcess","com.tencent.mm:toolsmp");
        cap.setCapability(ChromeOptions.CAPABILITY, options);

	public AppiumDriver testReadyApp(){
	    if(selectPlatform.toUpperCase() == "CELLPHONE"){
	    	DesiredCapabilities cap = new DesiredCapabilities();
			cap.setCapability("device", "Android");
			cap.setCapability("deviceName", "ced797860204");
			cap.setCapability("uuid", "ced797860204");
	    	cap.setCapability("platformName", "Android");
	    	cap.setCapability("platformVersion", "7.0");
	    	cap.setCapability("unicodeKeyboard", true);
	    	cap.setCapability("resetKeyboard", true);
	    	cap.setCapability("noReset", true);

	    	if(selectApplication.toUpperCase() == "WECHAR"){
				//cap.setCapability("app", "C:\\software\\jrtt.apk");  
	    		cap.setCapability("appPackage", "com.tencent.mm");
	    		cap.setCapability("appActivity", "com.tencent.mm.ui.LauncherUI");

				//cap.setCapability("automationName", "UiAutomator2");
				cap.setCapability("androidProcess", "com.tencent.mm:tools");
				cap.setCapability(CapabilityType.BROWSER_NAME, "");
				cap.setCapability("sessionOverride", true);

Failed LOG
Appium give log:found it can read androidprocess by python script by not by java script.
The following capabilities were provided, but are not recognized by appium: androidProcess, device, sessionOverride, uuid.

=============

[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running 'E:\Java\Appium\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ced797860204 forward --list'
[Chromedriver] Spawning chromedriver with: C:/Users/Administrator/AppData/Local/Programs/Appium/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[Chromedriver] Chromedriver version: '2.28.455520'
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"ced797860204"}}}

## Environment

- I am running Appium Desktop version _<1.7.1>_.
- I am on (pick one):
    - [ ] Windows 7
Test machine: Android 7.

**Comment by nixuewei** [comment]
How to add androidProcess to let me switch webview successfully

**Comment by nixuewei** [comment]
I can get webview name, but switch failed.
[NATIVE_APP, WEBVIEW_com.tencent.mm:toolsmp, WEBVIEW_com.tencent.mm:tools]

**Comment by dpgraham** [comment]
I recommend going to discuss.appium.io for help with this.
