### ISSUE TITLE
Keeps suggesting to upgrade to an older version

### ISSUE THREAD

**Issue by igasparis** [appium/appium-desktop#692]
## Appium or Appium Desktop?
- I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Every single time I open the appium desktop app, it suggests to upgrade to 1.7.1 although I am running 1.8.0. 

## Environment

- I am running Appium Desktop version 1.8.0.
- I am on Linux

**Comment by dpgraham** [comment]
Yeah, I'll have to unpublish and republish 1.8.0.... for some reason, our release server isn't recognizing 1.8.0 as the latest.

**Comment by dpgraham** [comment]
This is fixed now.
