### ISSUE TITLE
Please suggest how to download Appium desktop 1.9. Not able to see desktop installer for 1.9

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium-desktop#697]
Please suggest how to download Appium desktop 1.9. Not able to see desktop installer for 1.9

**Comment by dpgraham** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.7.1

This version has Appium 1.9.1 built into it.

**Comment by CharanpreetHora** [comment]
Getting error on console after launching inspector:-
[Appium] Cannot retrieve git revision for Appium version 1.9.1 from GitHub. Original error: Error: connect ETIMEDOUT 192.30.253.117:443

Unable to identify application on ios 12.x device. Working fine for 11.x.

Kindly suggest.
