### ISSUE TITLE
Appium 1.9.1 getting error on console after launching inspector

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium-desktop#701]
## Appium or Appium Desktop? 1.9.1

Getting error on console after launching inspector:-
[Appium] Cannot retrieve git revision for Appium version 1.9.1 from GitHub. Original error: Error: connect ETIMEDOUT 192.30.253.117:443

Unable to identify application on ios 12.x device. Working fine for 11.x.

Kindly suggest.

**Comment by zypherman** [comment]
I am seeing the same issue as well

**Comment by dpgraham** [comment]
Can you post the full logs as a [GIST](https://gist.github.com)

I don't think that the error message is what's causing your problems.

Also, can you try closing all of your simulators before starting the session and just using one and see if that fixes it?
