### ISSUE TITLE
Appium desktop don't open inspector.

### ISSUE THREAD

**Issue by jaelsonwagner** [appium/appium-desktop#705]
## The problem
Appium desktop don't open inspector.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.9.1 (appium-desktop-1.7.1-x86_64.AppImage)
* Desktop OS/version used to run Appium: 16.04.1-Ubuntu x86_64
* Node.js version (unless using Appium.app|exe): v11.0.0
* Mobile platform/version under test: Android 6.
* Real device or emulator/simulator: Android emulator version 27.3.10.0 (build_id 4969155)
* Appium CLI or Appium.app|exe:
* Java: java version "1.8.0_152" / Java(TM) SE Runtime Environment (build 1.8.0_152-b16) / Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

## Details

Using the following capabilities don't work:

{
  "platformName": "Android",
  "platformVersion": "6",
  "deviceName": "emulator-5554",
  "appPackage": "my.app.id",
  "noReset": true,
  "automationName": "UiAutomator2",
  "appActivity": "path.to.my.StartupActivity"
}

## Link to Appium logs

https://gist.github.com/jaelsonwagner/972f2adcfeafe3f4c3a34aa1dfe1571a

**Comment by jaelsonwagner** [comment]
Hi @mykola-mokhnach, in my casse I'm using Linux and I'm running the appium desktop from a sub directory in my home directory (~).
**-rwxr-xr-x  1 jaelson domain^users 139696774 Out 17 20:44 appium-desktop-1.7.1-x86_64.AppImage***
Thanks.

**Comment by jaelsonwagner** [comment]
@mykola-mokhnach, even setting a new temp directory for Appium, by setting the option "override temp path" in "Advanced" tab, don't work. Or even, running Appium as sudo, don't work.

[Appium] Welcome to Appium v1.9.1
[Appium] Non-default server args:
[Appium]   log: /home/user/temp
**[Appium]   tmpDir: /home/user/temp**
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by felipejorge** [comment]
I'm facing the same issue here! Please help us!!!!

**Comment by dpgraham** [comment]
I'll look into this. As a workaround, run Appium from terminal and run sessions using `Custom Server`.

**Comment by jaelsonwagner** [comment]
@dpgraham, I'm already doing that.
Thanks!

**Comment by Shubhanga** [comment]
@dpgraham I have encountered this issue while running tests on Ubuntu. Steps to reproduce this issue.
1)Switch to Ubuntu (I use 18.04)
2)Download latest Appium desktop App Image(I am using 1.8.2)
3)Open terminal
4)sudo ./appium-desktop-1.8.2-x86_64.AppImage

**Comment by dpgraham** [comment]
Has anyone tried 1.10 yet? It uses a new version of our electron packager.

**Comment by dpgraham** [comment]
Sorry, I meant to say Appium Desktop 1.9.0, which uses Appium 1.10

**Comment by Shubhanga** [comment]
Tested it on Appium  Desktop 1.9.1 which uses 1.10 on Ubuntu 18.04. Getting the same error.

[info] [35m[Appium][39m Welcome to Appium v1.10.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m8 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.myapp.SplashScreen","appPackage":"com.myapp","automationName":"UiAutomator2","deviceName":"AndroidEmulator","platformName":"Android","version":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.myapp.SplashScreen","appPackage":"com.myapp","automationName":"UiAutomator2","deviceName":"AndroidEmulator","platformName":"Android","version":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1546334755670 (14:55:55 GMT+0530 (IST))
[info] [35m[Appium][39m Creating new AndroidUiautomator2Driver (v1.24.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   appActivity: com.myapp.SplashScreen
[info] [35m[Appium][39m   appPackage: com.myapp
[info] [35m[Appium][39m   automationName: UiAutomator2
[info] [35m[Appium][39m   deviceName: AndroidEmulator
[info] [35m[Appium][39m   platformName: Android
[info] [35m[Appium][39m   version: 7.0
[info] [35m[Appium][39m   newCommandTimeout: 0
[info] [35m[Appium][39m   connectHardwareKeyboard: true
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"appActivity":"com.wishboo...
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: version, connectHardwareKeyboard.
[info] [35m[BaseDriver][39m Session created with session id: ebc9f365-91f3-4fb5-95ee-8bedd9dd5de8[info] [35m[AndroidDriver][39m Java version is: 1.8.0_171
[info] [35m[ADB][39m Checking whether adb is present
[info] [35m[ADB][39m Found 4 'build-tools' folders under '/home/tester/Android/' (newest first):
[info] [35m[ADB][39m     /home/tester/Android/build-tools/28.0.2
[info] [35m[ADB][39m     /home/tester/Android/build-tools/28.0.0
[info] [35m[ADB][39m     /home/tester/Android/build-tools/27.0.3
[info] [35m[ADB][39m     /home/tester/Android/build-tools/25.0.2
[info] [35m[ADB][39m Using adb from /home/tester/Android/platform-tools/adb
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: 3300d64127ec6317
[debug] [35m[ADB][39m Setting device id to 3300d64127ec6317
[debug] [35m[ADB][39m Running '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 24
[debug] [35m[ADB][39m Device API level: 24
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[ADB][39m Getting all processes with uiautomator
[debug] [35m[ADB][39m Running '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 shell ps'[debug] [35m[ADB][39m Running '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 shell am force-stop io.appium.uiautomator2.server'[debug] [35m[ADB][39m Checking app cert for /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk
[info] [35m[ADB][39m Using apksigner from /home/tester/Android/build-tools/28.0.2/apksigner
[debug] [35m[ADB][39m Starting '/home/tester/Android/build-tools/28.0.2/apksigner' with args '["verify","--print-certs","/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk"]'[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk' is already signed.
[debug] [35m[ADB][39m Checking app cert for /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [35m[ADB][39m Starting '/home/tester/Android/build-tools/28.0.2/apksigner' with args '["verify","--print-certs","/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: CN=Android Debug, O=Android, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: 3e4f2ab66d641bbbd363421151755f8b12b66ea37a5db43c52116596b7392a8e
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: e24fc8971c0aad07d1df6cc62af7fb0d48b45b60
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: 5623d53469c7f7147b52ace9d09901eb
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is signed with non-default certificate
[info] [35m[ADB][39m Checking whether zipalign is present
[info] [35m[ADB][39m Using zipalign from /home/tester/Android/build-tools/28.0.2/zipalign[debug] [35m[ADB][39m /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is already zip-aligned. Doing nothing
[debug] [35m[ADB][39m Signing '/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' with default cert
[debug] [35m[ADB][39m Starting '/home/tester/Android/build-tools/28.0.2/apksigner' with args '["sign","--key","/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/keys/testkey.pk8","--cert","/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/keys/testkey.x509.pem","/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'[warn] [35m[ADB][39m Got an error during apksigner execution: Command '/home/tester/Android/build-tools/28.0.2/apksigner sign --key /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/keys/testkey.pk8 --cert /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/keys/testkey.x509.pem /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' exited with code 1
[warn] [35m[ADB][39m apksigner stderr: Exception in thread "main" java.nio.file.FileSystemException: /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk: Read-only file system
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
[warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[warn] [35m[ADB][39m 
[warn] [35m[ADB][39m Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/home/tester/Android/build-tools/28.0.2/apksigner sign --key /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/keys/testkey.pk8 --cert /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/keys/testkey.x509.pem /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.FileSystemException: /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk: Read-only file system
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
[warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[warn] [35m[ADB][39m 
[debug] [35m[ADB][39m Resigning apk.[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[JSONWP Proxy][39m Matched '/' to command name 'deleteSession'
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [35m[ADB][39m Running '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 shell am force-stop com.myapp'[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 forward --remove tcp\:8200'
[debug] [35m[ADB][39m Running '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 forward --remove tcp\:8200'
[warn] [35m[UiAutomator2][39m Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/home/tester/Android/platform-tools/adb -P 5037 -s 3300d64127ec6317 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [35m[ADB][39m Device API level: 24
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1546334765735 (14:56:05 GMT+0530 (IST))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/usr/lib/jvm/java-8-oracle/bin/java -jar /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/jars/sign.jar /tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk --override' exited with code 1
[debug] [35m[MJSONWP][39m     at ADB.apkSigningMethods.signWithDefaultCert (/tmp/.mount_appiumuClWEj/resources/app/node_modules/appium-adb/lib/tools/apk-signing.js:124:13)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m10086 ms - 483[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m5 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by jeevaeastpoint** [comment]
Just in case if this helps to someone. This issue seems to be happening when using the uiautomator2 as the automation name for android. Since the issue is with Appium desktop version, i tried to run the appium installed from npm from the command prompt and opened the appium desktop just to open the appium inspector which worked.

**Comment by nurayttumer** [comment]
> Has anyone tried 1.10 yet? It uses a new version of our electron packager.

Yes ı'm trying it on 1.10 but problem is still unsolved.

**Comment by anurut** [comment]
Any update on this issue? Still getting it with Appium-Desktop 1.13.0

**Comment by AndrewElfimov** [comment]
> Just in case if this helps to someone. This issue seems to be happening when using the uiautomator2 as the automation name for android. Since the issue is with Appium desktop version, i tried to run the appium installed from npm from the command prompt and opened the appium desktop just to open the appium inspector which worked.

okay, how can i open appium inspector from command prompt?

**Comment by lefty1975** [comment]
@AndrewElfimov what I did to accomplish this was:
1.  start the Appium server via the desktop application.
2. Then start inspector session
3. Stop desktop Appium server
4. Start Appium server from Terminal
5. Set desired capabilities
6. Start session

This got me past the splashscreen and finally to my MainActivity so I can start reviewing elements.

Hope that helps if it's not too late for you.

**Comment by katebygrace** [comment]
That helped me @lefty1975 - thank you!
