### ISSUE TITLE
Loading spinner high cpu usage

### ISSUE THREAD

**Issue by Walther** [appium/appium-desktop#707]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

1. Open Appium Desktop
1. Run any operation that you know takes a while
1. Observe the spinner animation
1. Observe high cpu usage and fans spinning up if you keep the Appium Desktop window visible
1. Observe the cpu usage and fan speed slow down if you hide the window (e.g. move to a different space / virtual desktop)
1. Observe the high cpu usage again when making the Appium Desktop window visible again with its spinner

## Environment

- I am running Appium Desktop Version 1.7.1 (1.7.1.20180926.9)
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
What happens if you run Appium from the terminal and start a session using `Custom Server` instead of the internal Appium instance. Does it still happen then? It would be surprising if the UI alone was causing this problem.

**Comment by dpgraham** [comment]
@Walther any findings?
