### ISSUE TITLE
Appium GUI crashes when providing a Logfile path

### ISSUE THREAD

**Issue by noNotNiall** [appium/appium-desktop#72]
Starting the server with**out** a value in the "Logfile Path" field on the "Advanced" tab causes Appium to crash. Running on MacOS 10.12.2 with appium-desktop 1.0.0-beta-2.

**Comment by dpgraham** [comment]
Can you post the server logs? Or is it causing the whole GUI to crash.

**Comment by noNotNiall** [comment]
Sorry should've been more specific, it causes the entire GUI to crash for me, as if I've hit cmd + q. This is happening on my work Mac, but I've been unable to repro it on my own, or a windows machine.

**Comment by jlipps** [comment]
@noNotNiall what value are you putting into the field? And do you have any other non-standard options? I can't get it to repro either.

**Comment by noNotNiall** [comment]
Inputting a valid path seems to work OK now, so out of curiosity I just input "asdf" and that seems to crash it every time. Not a major issue but that seems to repro it ok.

**Comment by jlipps** [comment]
ah ok i can repro that. we'll fix so that an appropriate error is shown instead. but good to know it works in the happy path case :-)

**Comment by dpgraham** [comment]
I can't reproduce this. Was this fixed already?

**Comment by noNotNiall** [comment]
Still happens for me on Appium beta-6. 

**Steps to repro:**
1. Launch Appium-desktop
2. Click on "advanced" tab
3. Enter 'asdf' in Logfile Path field
4. Click "Start Server v1.6.4-beta"

This causes the program to crash for me at the minute

**Comment by jlipps** [comment]
Yeah I can still repro it as well

**Comment by dpgraham** [comment]
I can't reproduce the issue. These are my Appium logs:

```
[Appium] Welcome to Appium v1.6.4-beta (REV d15dd19f3f8fd720e7252fd557658beb0619c7c0)
[Appium] Non-default server args:
[Appium]   log: 'asdf'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
Appium server stopped successfully
```

**Comment by noNotNiall** [comment]
I'm seeing the same as this now, feel free to close this if nobody can repro it!
