### ISSUE TITLE
Appium: Unknown device or simulator UDID

### ISSUE THREAD

**Issue by deepuvsoman1985** [appium/appium-desktop#721]
I am getting the above error while starting session in appium inspector

{
“app”: “<path of the .app>”,
“platformName”: “iOS”,
“deviceName”: iPad Pro”,
“automationName”: “XCUITest”,
“udid”:”xxxxxxxxxx”,
“platformVersion”: “12.0”

}

The log is 
***********
[info] [Appium] Welcome to Appium v1.9.0
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> GET /wd/hub/sessions
[info] [HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[info] [HTTP] <-- GET /wd/hub/sessions 200 10 ms - 40
[info] [HTTP] [info] [HTTP] --> POST /wd/hub/session
[info] [HTTP] {"desiredCapabilities":{"app":"/Users/1568085/Desktop/iCount.app","automationName":"XCUITest","deviceName":"iPad Pro","platformName":"iOS","platformVersion":"12.0","udid":"AE864356D73D47C4923B3EAAF139ACB9","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/1568085/Desktop/iCount.app","automationName":"XCUITest","deviceName":"iPad Pro","platformName":"iOS","platformVersion":"12.0","udid":"AE864356D73D47C4923B3EAAF139ACB9","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1542190703599 (15:48:23 GMT+0530 (IST))
[info] [Appium] Creating new XCUITestDriver (v2.92.0) session
[info] [Appium] Capabilities:
[info] [Appium]   app: /Users/1568085/Desktop/iCount.app
[info] [Appium]   automationName: XCUITest
[info] [Appium]   deviceName: iPad Pro
[info] [Appium]   platformName: iOS
[info] [Appium]   platformVersion: 12.0
[info] [Appium]   udid: AE864356D73D47C4923B3EAAF139ACB9
[info] [Appium]   newCommandTimeout: 0
[info] [Appium]   connectHardwareKeyboard: true
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/1568085/Desk...
[info] [BaseDriver] Session created with session id: 56fed04e-0f39-45cf-bbb3-eed890f74936[debug] [XCUITest] Xcode version set to '9.4' (tools v10.1.0.0.1.1539992718)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1542190704617 (15:48:24 GMT+0530 (IST))[debug] [XCUITest] Available devices: 
[error] [XCUITest] Error: Unknown device or simulator UDID: 'AE864356D73D47C4923B3EAAF139ACB9'
[error] [XCUITest]     at XCUITestDriver.determineDevice$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[error] [XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [XCUITest]     at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1542190706003 (15:48:26 GMT+0530 (IST))
[error] [MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: 'AE864356D73D47C4923B3EAAF139ACB9'
[error] [MJSONWP]     at XCUITestDriver.determineDevice$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[error] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [MJSONWP]     at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session 500 2408 ms - 205
[info] [HTTP]

**Comment by dpgraham** [comment]
I won't be able to troubleshoot this. Try checking that the UDID corresponds to an actual and test that it can be launched via terminal: `xcrun simctl launch <YOUR-DEVICE-ID> <BUNDLE-ID-OF-APP-BUNDLE> `
