### ISSUE TITLE
Fix autoupdater

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-desktop#74]
Acceptance Criteria:
* [ ] Confirm that auto updating is successful on Mac
* [ ] Confirm that auto updating is successful on Windows
* [ ] Add release notes to publishing workflow
* [ ] Verify that the UI is acceptable

**Comment by hjianhui** [comment]
Android real machine, 5.0.1 ,Encountered internal error running command: Error: incorrect data checkat Zlib._handle.onerror (zlib.js:370:17)

Appium-desktop, beta 3

**Comment by dpgraham** [comment]
@hjianhui I don't think this is related to this issue. Can you open this as an issue at https://github.com/appium/appium/issues

**Comment by dpgraham** [comment]
Update: I'm able to autoUpdate from beta 2 to beta 3. However, when `quitAndInstall` is called on electron-updater, it's not re-opening the app. I don't think I'm the only other person to have this issue (see https://github.com/electron/electron/issues/6345). 

It is updating the app though, so that's the most important step. There's just a nuisance of users having to open the app themselves after they've called quitAndInstall

**Comment by slipy12** [comment]
![captura de pantalla 2017-03-14 a las 9 10 20](https://cloud.githubusercontent.com/assets/9083921/23891364/4160a6c6-0896-11e7-8a2e-db45a88e9201.png)
Also, pressing the `Download` button nothing happens.
Btw, why a text box is needed there? :S

**Comment by dpgraham** [comment]
Thanks @slipy12. Yeah I put in a commit to fix that.

* The CSS was bad and that was clipping the title
* The textbox is _supposed_ to show the release notes, so still working on fixing that
* I also added a fix so that clicking the `Download Update Now` shows download progress indicator

The not restarting issue is a little bit trickier. It looks like the framework we're using is successfully updating the app but not relaunching it.
