### ISSUE TITLE
 used "ID" as locator strategy but somehow its searching through CSS locator for native app

### ISSUE THREAD

**Issue by shrikish** [appium/appium-desktop#743]
My tests are failing - I've used "ID" as locator strategy but somehow its searching through CSS locator for native app. 

Appium  desktop - 1.8.2 but while launching it shows "Cannot retrieve git revision for Appium version 1.9.1 from GitHub. Original error: Error: unable to get local issuer certificate"
Client lib - java-client-6.1.0.jar

Error  log - 

org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html

**Comment by AdeAutomation** [comment]
I am having same issue. Please fix

**Comment by gr8viju** [comment]
I am also facing same issue in 1.8.2 and also in 1.10

**Comment by lgw8186** [comment]
It seems to be caused by a selenium jar conflict
