### ISSUE TITLE
Appium can't execute apkAnalyzer command (exited with code 1)

### ISSUE THREAD

**Issue by Kranuh** [appium/appium-desktop#745]
## The problem

While trying to run Appium for Android I'm encountering the following error:

`Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed.`

Checking the logs it becomes apparent that the problem starts with the following error:

`[ADB] Starting '/Users/timkranen/Library/Android/sdk/tools/bin/apkanalyzer' with args ["-h","manifest","print","/Users/timkranen/Downloads/test.apk"]
[ADB] Using the alternative activity name detection method because of: Command '/Users/timkranen/Library/Android/sdk/tools/bin/apkanalyzer -h manifest print /Users/timkranen/Downloads/test.apk' exited with code 1`

After it fails to execute this command it tries the following:

`Using the alternative activity name detection method because of: Command '/Users/timkranen/Library/Android/sdk/tools/bin/apkanalyzer -h manifest print /Users/timkranen/Downloads/test.apk' exited with code 1
[ADB] Extracting package and launch activity from manifest
[AndroidDriver] Shutting down Android driver`

This ultimately leads to the error described above. I'm assuming the 'alternative activity name detection' doesn't do well with an activity alias. Or somehow it fails. 

When I try running the exact apkanalyzer command (literally copy pasted from the Appium logs with the same args) the output looks normal. It prints a version of the manifest.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.8.2 (desktop app), v1.10.0 (through npm cli)
* Last Appium version that did not exhibit the issue (if applicable): n/a, first time trying to set it up
* Desktop OS/version used to run Appium: MacOS Mojave 10.14
* Node.js version (unless using Appium.app|exe): v10.6.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator/simulator
* Appium CLI or Appium.app|exe: v1.10.0

## Link to Appium logs

https://gist.github.com/Kranuh/455b74cb844f2a09f17617128eba633c

## Code To Reproduce Issue [ Good To Have ]

This occurs with any .apk supplied. The .apk used in the example is simply a Google Calendar .apk file.

**Comment by dpgraham** [comment]
Can you try again with 1.9.1?
