### ISSUE TITLE
XCUITest requires Appium version >= 1.6.0 (Appium::Core::Error::NotSupportedAppiumServer)

### ISSUE THREAD

**Issue by FirstAM** [appium/appium-desktop#761]
## The problem

Hello , today i update appium to last version 1.9.0 and  try to run my test like usually with XCUITEST driver. I run my test on Iphone 6 IOS v. 12.1. But in this time appium return me log with error: 

>  XCUITest requires Appium version >= 1.6.0 (Appium::Core::Error::NotSupportedAppiumServer)
>  ./features/support/hooks.rb:69:in `Before'
> 

69 line in my test is `$driver.start_driver`

Trying run with debug , and get same error 

> 
> Appium::Core::Error::NotSupportedAppiumServer: XCUITest requires Appium version >= 1.6.0
> from /Users/jenkins/.rvm/gems/ruby-2.6.0-preview2/gems/appium_lib-9.15.1/lib/appium_lib/driver.rb:333:in `check_server_version_xcuitest'
> 
> 

I try to update all dependent libraries , but it doesn't help

Main error in logs appium is 

> [[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}]

## Environment

- I am running Appium Desktop version 1.9.0.
- I am on (pick one):
    - [*] Mac

Log Appium in txt file 
[log_appium.txt](https://github.com/appium/appium-desktop/files/2648785/log_appium.txt)

**Comment by dpgraham** [comment]
@FirstAM This is a known issue with older versions of the Ruby client. Try updating to the latest and that should fix your problem.

**Comment by FirstAM** [comment]
> @FirstAM This is a known bug with older versions of the Ruby client. Try updating to the latest and that should fix your problem.

Ok , but i have latest version of Ruby , my version is 2.6.0

**Comment by dpgraham** [comment]
I mean the Appium ruby lib: https://github.com/appium/ruby_lib/releases
