### ISSUE TITLE
Swipe action in i-OS is not performing as expected

### ISSUE THREAD

**Issue by kethatharan** [appium/appium-desktop#770]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Performing a swipe on appium desktop against an i-OS device doesn't work as expected.

## Environment

- I am running Appium Desktop version 1.10.(I am facing this issue since 1.8)
- I am on Windows

When I perform a swipe in an iOS screen, I am unable to see the result for the swipe whereas I can see a click action getting performed in the swipe end point. Attached few video references.

[Dec 12, 2018 12_52 PM.zip](https://github.com/appium/appium-desktop/files/2674891/Dec.12.2018.12_52.PM.zip)

**Comment by dpgraham** [comment]
For swipe actions, `mobile: swipe` is recommended (http://appium.io/docs/en/commands/mobile-command/)
