### ISSUE TITLE
Code signature identifier 

### ISSUE THREAD

**Issue by blackthroat** [appium/appium-desktop#773]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Code signature identifier changed from "io.appium.desktop" to "Appium-1". Was this intentional and should we expect this moving forward or was this an oversight?

## Environment

- I am running Appium Desktop version _1.9.0_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
No that wasn't. Where do you see that?

**Comment by blackthroat** [comment]
```
$ codesign --display -r- --deep -v ~/Downloads/Appium-1.9.0.dmg
Executable=/Users/blackthroat/Downloads/Appium-1.9.0.dmg
Identifier=Appium-1
Format=disk image
CodeDirectory v=20200 size=296 flags=0x0(none) hashes=1+6 location=embedded
Signature size=8935
Timestamp=Dec 4, 2018, 3:47:32 PM
Info.plist=not bound
TeamIdentifier=G58F7ZX4UL
Sealed Resources=none
designated => identifier "Appium-1" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = G58F7ZX4UL
```

**Comment by dpgraham** [comment]
I'm going to close this. I don't think this causes any problems and I don't want to change the default behaviour of the Electron bundler.
