### ISSUE TITLE
Appium Inspector displays value, name, and label the same value as accessibility key for XCUIElementTypeStaticText 

### ISSUE THREAD

**Issue by ochemerys** [appium/appium-desktop#779]
## The problem

Appium Inspector displays value, name, and label the same value as accessibility key for iOS devices XCUIElementTypeStaticText 
<img width="1210" alt="screen shot 2018-12-19 at 12 50 40 pm" src="https://user-images.githubusercontent.com/20651535/50244902-4b97f500-038e-11e9-862b-6cbc6acf64d7.png">

Android devices have correct text values
<img width="1223" alt="screen shot 2018-12-19 at 1 42 15 pm" src="https://user-images.githubusercontent.com/20651535/50246997-01197700-0394-11e9-80d1-a49156ebfe80.png">

## Environment
Appium version 1.9.1; Server v1.10.0
- I am running Appium Desktop version _not sure where I can find it_.
- I am on (pick one):
    - [x ] Mac

**Comment by dpgraham** [comment]
Closing for same reason as https://github.com/appium/appium/issues/11883
