### ISSUE TITLE
Appium: iOS app installed but not launching

### ISSUE THREAD

**Issue by tgoswami013** [appium/appium-desktop#781]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
App is installed when I am running eclipse project using TestNG with below capabilities but its not launching. Even I click manually on installed app on simulator but it does not launch. Getting this in log: xcodebuild exited with code '65' and signal 'null'
```java
cap.setCapability("deviceName", "iPhone 8 (12.1)");
cap.setCapability("platformName", "iOS");
cap.setCapability("udid", "E174E9D8-046A-42A3-8C84-94ADA7055755");
cap.setCapability(MobileCapabilityType.APP, "/Users/tarungoswami/Downloads/testapp/Fliplearn.app");

cap.setCapability("automationName", "XCUITest");
cap.setCapability("xcodeOrgId","47M3CKSC66");	
cap.setCapability("xcodeSigningId","iPhone Developer");
driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
```
## Environment

- I am running Appium Desktop version : 1.10
- I am on (pick one):
    - [x] Mac

**Comment by dpgraham** [comment]
If you can't open it from inside the Simulator it's probably not an Appium issue.
