### ISSUE TITLE
appium-desktop always crashes after using the swipe in inspector

### ISSUE THREAD

**Issue by zy9096** [appium/appium-desktop#787]
## Appium or Appium Desktop?
Appium Desktop

## The problem
While using the inspector for recording, appium-desktop always crashes by using the swipe function. Other operations works normally. Why would this happen?

## Environment
android 6.0.1, 4.4.6, any apks.

- I am running Appium Desktop version _<1.9.1>_.

- I am on (pick one):
 Windows 8

**Comment by mcnalbant** [comment]
no problem on ios but same error on android in macos. appium instantly crashes after swipe.

**Comment by dpgraham** [comment]
I'll close it then. Let me know if it happens again and I'll re-open.
