### ISSUE TITLE
UiAutomator exited unexpectedly with code 4294967295, signal null

### ISSUE THREAD

**Issue by somnathsamane** [appium/appium-desktop#789]
UiAutomator exited unexpectedly with code 4294967295, signal null

.apk not open and showing above error in Appium need help.

**Comment by dpgraham** [comment]
Similar to https://github.com/appium/appium/issues/10226

This means the appActivity and appPackage are incorrect.

**Comment by masteufelipe** [comment]
I have the same error, how did you solve it? how to give permission to Appium folder?

**Comment by sharathchandraGupta** [comment]
Am also facing the same issues.. unable to launch one particular app...getting" exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent ". Please let me what would the issue. Looks like permission issue..!

**Comment by jahangiraali001** [comment]
I found a cold reboot of the emulator device fixed the issue.

**Comment by Master-An** [comment]
I solved it by reboot the test device.
