### ISSUE TITLE
Background app can't support waiting for too long.

### ISSUE THREAD

**Issue by Jessicabi** [appium/appium-desktop#794]
## Appium or Appium Desktop?

Appium Desktop

## The problem
When set background app for 900s, I met error as 'ProtocolError: ('Connection aborted.', BadStatusLine("''",))'

## Environment

- I am running appium-desktop-setup-1.10.0.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Can you share appium logs to assume your situation?
