### ISSUE TITLE
Fix Azure Pipelines MacOS builds

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-desktop#796]
Azure Pipelines stopped running e2e tests, thus breaking the build. This happens to all builds (even past builds) so it's something on Azure that's causing it

Resolution must be one of:
* [ ] Fix the E2E tests
* [ ] Stop running E2E tests on Azure if this isn't possible
* [ ] Wait until a later date, and test again to see if they fix the problem on Azure.

**Comment by KazuCocoa** [comment]
Current CI is working, so probably this issue had been resolved.
