### ISSUE TITLE
Include platform name in release download links

### ISSUE THREAD

**Issue by kkarakk** [appium/appium-desktop#797]
> http://appium.io/docs/en/about-appium/getting-started/     

page simply says download the latest version from the releases page

> https://github.com/appium/appium-desktop/releases

, the releases have very unhelpful names - 
how do i infer (apart from the file extension) which one is the appropriate one for windows? 
is there a document explaining all the different versions of the .exes and which one i need?    
right now i just played it safe and chose the shortest filename with an .exe after it but is that the version to use? 
what is the difference between desktop and desktop web setups?

**Comment by dpgraham** [comment]
That's not a bad idea. We could add the platform name so it says `appium-desktop-windows-setup-1.10.0.exe` instead of just `appium-desktop-setup-1.10.0.exe`

I won't have time to do this, but anyone is welcome to take this issue and put in a pull request.

**Comment by iammike** [comment]
Re: difference between web and desktop setups - that's a documentation thing.

I've done this work in a single line, but the Mac platform is returning "darwin" - accurate, but not too helpful. Thoughts? Can easily override this with an additional line of code.

**Comment by iammike** [comment]
PR: https://github.com/appium/appium-desktop/pull/836
