### ISSUE TITLE
Appium Desktop

### ISSUE THREAD

**Issue by suhasmy29** [appium/appium-desktop#798]
Hi

I downloaded latest version of Appium from our github,
But on just by clicking "Start server v1.10.0" a window appear showing "The server is stopped".
Please suggest me where i am wrong to configure?
And also, I am unable to download log, receiving error "An error as occurred. Logs not available".
![capture](https://user-images.githubusercontent.com/37245390/50739539-05ed8000-1208-11e9-9b6b-a21a999fce41.PNG)
![capture1](https://user-images.githubusercontent.com/37245390/50739540-05ed8000-1208-11e9-941f-993b124fada8.PNG)

**Comment by KazuCocoa** [comment]
Can you observe error messages when you run `npm run dev`?
https://github.com/appium/appium-desktop/blob/master/CONTRIBUTING.md#doing-development

**Comment by suhasmy29** [comment]
Thanks KazuCocoa .
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose config Skipping project config: C:\Users\Dell/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
6 verbose cwd C:\Users\Dell
7 verbose Windows_NT 6.1.7601
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
9 verbose node v11.6.0
10 verbose npm  v6.5.0-next.0
11 error path C:\Users\Dell\package.json
12 error code ENOENT
13 error errno -4058
14 error syscall open
15 error enoent ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
16 error enoent This is related to npm not being able to find a file.
17 verbose exit [ -4058, true ]

I went to the respective folder but I found package-lock.json' instead of package.json'.

**Comment by KazuCocoa** [comment]
Did it happen following below step?

```
$ git clone [this repo]
$ cd appium-desktop # please replace _cd_ properly on windows
$ npm install
$ npm run dev
```

I wondered why the log tired to access `C:\Users\Dell\package.json` (probably home directory)

**Comment by liaoyg8023** [comment]
when I install fbsimctl with command " ~ brew tap facebook/fb and brew install fbsimctl --HEAD"
it reports these error about GCDWebServer,
what can I do to fix them and install fbsimctl successfully

environment: macbook air , system:mojave 10.14.2 (18C54)

....
using target fbsimctl
using command build
using output directory /usr/local/Cellar/fbsimctl/HEAD-c2775e8
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20190109-32266-1hkq5zh/fbsimctl /private/tmp/fbsimctl-20190109-32266-1hkq5zh
***** Checking out GCDWebServer at "3.3.3"
*** Cloning GCDWebServer
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/swisspol/GCDWebServer.git /Users/netcaps/Library/Caches/org.carthage.CarthageKit/dependencies/GCDWebServer) failed with exit code 1:
/Users/netcaps/Library/Caches/org.carthage.CarthageKit/dependencies/GCDWebServer: Operation not permitted**

**Comment by KazuCocoa** [comment]
That is fbsimctl issue like https://github.com/facebook/FBSimulatorControl/issues/432
The command is optional in Appium.

Did you already resolve this original issue?

**Comment by divyaramamoorthy1987** [comment]
> Hi
> 
> I downloaded latest version of Appium from our github,
> But on just by clicking "Start server v1.10.0" a window appear showing "The server is stopped".
> Please suggest me where i am wrong to configure?
> And also, I am unable to download log, receiving error "An error as occurred. Logs not available".
> ![capture](https://user-images.githubusercontent.com/37245390/50739539-05ed8000-1208-11e9-9b6b-a21a999fce41.PNG)
> ![capture1](https://user-images.githubusercontent.com/37245390/50739540-05ed8000-1208-11e9-941f-993b124fada8.PNG)

how did you resolve the issue , am facing similar issue.

**Comment by KazuCocoa** [comment]
As i commented in https://github.com/appium/appium-desktop/issues/798#issuecomment-451814985 , you probably can get logs from CLI.

What about running appium-doctor, btw? (If you have some issues in your environment, it helps you)
