### ISSUE TITLE
What is the status of the Inspector?

### ISSUE THREAD

**Issue by PiotrNestor** [appium/appium-desktop#8]
As the issue title states: What is the status of the Inspector?

Is that tool available yet? If not when?

Cheers

**Comment by xtuc** [comment]
I was wondering how to use it.

Please remove the section from the README because it's confusing and time wasting...

**Comment by jlipps** [comment]
@PiotrNestor @xtuc this project is currently under development and is not ready for use by anyone except those wishing to develop it.

When it's ready for general use, the README will be updated with user-friendly instructions.

In short, the inspector part of this project is currently under development and not ready for use yet.
