### ISSUE TITLE
Appium app inspector is not inspecting the element id's under menu 

### ISSUE THREAD

**Issue by MahadevG** [appium/appium-desktop#806]
##Appium Desktop 
I am trying to inspect the elements under menu using appium app inspector. Appium is not inspecting the  unique id's of each element under menu.(From developer end confirmed that all elements are having unique id).Appium is returning same id for all the items under menu. Is this a issue with appium-app inspector?. 
Please find below attached files for more info
Actual file
https://drive.google.com/open?id=1PMLWhUTWEIhwr9pGTOr54bm-p1lgfvfd

xml file from appium-appinspector
https://drive.google.com/open?id=15IHnXXLlR9PFOTJlnkuurTzppBayU9zl

Can you help to resolve this issuse?

Also can you give some information about how appium-app inspector gets the screenshots? how does it fetches the xml file ?Wanted to know the working of app-inspector.

**Comment by dpgraham** [comment]
It doesn't fetch a file, it fetches a string XML, and it uses these endpoints to get source and screenshot

http://appium.io/docs/en/commands/session/source/
http://appium.io/docs/en/commands/session/screenshot/

@MahadevG did you have interest in developing on Appium Desktop?

**Comment by MahadevG** [comment]
@dpgraham 

When I tried to inspect the element using appium app-inspector it is not inspecting the elements under listView.
Our application has a 6 items in a list view and each item have unique ids. When I tried to inspect them i am not getting the unique ids for the element. For all the elements I am getting same id.

Actual file
https://drive.google.com/open?id=1PMLWhUTWEIhwr9pGTOr54bm-p1lgfvfd

xml file from appium-appinspector
https://drive.google.com/open?id=15IHnXXLlR9PFOTJlnkuurTzppBayU9zl

Can you help to resolve this issuse?

Thanks

**Comment by dpgraham** [comment]
Can you post the xml on gist.github.com... I can't access those docs

**Comment by MahadevG** [comment]
@dpgraham 
Please find attached files
App UI
https://drive.google.com/open?id=1Pnb8k76VhwU4iW8KrrN1I0b65xb0ob97
 
Xml file given by Developer 
https://drive.google.com/file/d/1PMLWhUTWEIhwr9pGTOr54bm-p1lgfvfd/view?usp=sharing

Xml file fetched from Appium-app-inspector 
https://drive.google.com/open?id=1y0SZLeebBpmtw4ezmxl1Tt_zt4AlSWzJ

Complete xml file(from appium-app-inspector)
https://drive.google.com/open?id=1c5rbB0ZAPHjfhfztj0gQkqruUxeO-31g
                                                                     ☺

**Comment by dpgraham** [comment]
Is this still an issue?

**Comment by KazuCocoa** [comment]
close for now. please try out the inspector and report issues in https://github.com/appium/appium-inspector/issues
