### ISSUE TITLE
 xcodebuild failed with code 65

### ISSUE THREAD

**Issue by HeminWon** [appium/appium-desktop#81]
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

**Comment by dpgraham** [comment]
Can you provide the server logs as well?

**Comment by jlipps** [comment]
This is most likely related to Appium and not Appium Desktop.

**Comment by vikramvi** [comment]
I've seen this issue came up multiple times in appium issue section. This is not related to Appium Desktop

@HeminWon you can search for this issue and its fix under Appium project.

@triager please close

**Comment by jlipps** [comment]
hmm i don't think @triager is set up on this repo
