### ISSUE TITLE
'tag'  attribute/field missing in inspector

### ISSUE THREAD

**Issue by sanjayvermaqa** [appium/appium-desktop#810]
Appium Desktop

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop

I am trying to find the element by Tag name and the element does has a tag value but in Appium Desktop inspector there is no attribute saying 'tag'.

I am running Appium Desktop version _1.10.0_
_

## Environment

- I am running Appium Desktop version _1.10.0_.
- I am on (pick one):
    - [x] Mac

**Comment by dpgraham** [comment]
Are you talking about this attribute https://developer.android.com/reference/android/view/View.html#attr_android:tag? 

Which automation are you using to run the test? Are you running Espresso?

Currently, the Espresso Driver does not report the `tag` attribute in the source XML, but that is something we could accept as a pull request: https://github.com/appium/appium-espresso-driver
