### ISSUE TITLE
I could not see the app source for the react mobile app

### ISSUE THREAD

**Issue by SanthanaSubbu** [appium/appium-desktop#811]
Configuration

{
  "deviceName": "##",
  "platformName": "Android",
  "appPackage": "host.exp.exponent",
  "appActivity": "host.exp.exponent.experience.HomeActivity",
  "VERSION": "8.1.0"
}

I am trying to automate the react mobile app developed using Expo

![image](https://user-images.githubusercontent.com/46918806/51523152-082f1b80-1e51-11e9-88bc-bd1b371f4f0b.png)

**Comment by kapiljain007** [comment]
I am also having the same issue. Please comment here if anybody has the solution.

**Comment by KazuCocoa** [comment]
What about using `automationName: uiautomator2` capability in Andorid 6+ case?

**Comment by dpgraham** [comment]
I second what @KazuCocoa says... try automationName `UiAutomator2` or `Espresso`.... if that doesn't work, let me know and I'll re-open the issue.
