### ISSUE TITLE
Issue in Appium-desktop in linux

### ISSUE THREAD

**Issue by sevenbitshweta** [appium/appium-desktop#812]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

when i am running appium in command line it shows the below given lines

**[Appium] Welcome to Appium v1.10.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723**

->But after that i am not able to see any sort of server or anything and i am not aware of how to access it 
-> i downloaded  **appium-desktop-1.10.0-x86_64.AppImage** but i am not able to open it or access it 

## Environment

- I am running Appium Desktop version _<1.10.1

->And when i tried to run it with the cmd line it throws this error as shown in the image below 

![screenshot from 2019-01-23 10 02 17](https://user-images.githubusercontent.com/43673509/51584487-8516cf80-1efb-11e9-8119-7f28c281c5d4.png)
>_.
- I am on (pick one):
    - [ ] Linux

**Comment by dpgraham** [comment]
What happens when you try running Appium tests?

And the AppImage problem looks like a permissions issue, which I don't know how to help with.

**Comment by sevenbitshweta** [comment]
I am not able to open the Appium desktop while opening it though the terminal in linux

**Comment by dpgraham** [comment]
Linux does support Appium Desktop... I just don't know how to help with this because it's an AppImage issue.

**Comment by sevenbitshweta** [comment]
So is there any solution i can do for this? or any alternative

**Comment by sevenbitshweta** [comment]
> I resolved this issue now thankyou
