### ISSUE TITLE
Localise the application interface

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium-desktop#818]
There is [i18next](https://www.i18next.com) library, which might be handy for localization purposes. We could start with adding one locale first. Crowdin.com could be used as TMS (free for open source).

[Here](https://phraseapp.com/blog/posts/building-an-electron-app-with-internationalization-i18n/) is the tutorial on how to perform the initial setup.

**Comment by KazuCocoa** [comment]
Will work for 🇯🇵

**Comment by dpgraham** [comment]
Closed as completed.
