### ISSUE TITLE
[Enhancement Request] -  Adding link to CAPS documentation

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-desktop#82]
Desired Capabilities section can have link to documentation https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
![screen shot 2017-03-14 at 10 44 05 am](https://cloud.githubusercontent.com/assets/308490/23894699/6a423e9e-08a3-11e7-95d9-2f741f9d4547.png)

This can be put on left side of  Save As.. , Start Session button.

1. This will help new users to refer to each of the capabilities easily and try them out in Appium desktop
2. Will be helpful to existing users of appium to try out new capability to improve upon existing setup

Please review

**Comment by dpgraham** [comment]
That's not a bad idea, what do you think @jlipps

**Comment by jlipps** [comment]
Yeah, I was already planning on doing this actually. Good idea 👍

**Comment by slipy12** [comment]
Since appium has a webpage with all documentation maybe is a better option to include this link:
http://appium.io/slate/en/master/?javascript#appium-server-capabilities
Just my opinion

**Comment by jlipps** [comment]
@slipy12 it's a good idea however i've noticed our docs renderer does a bad job of actually pointing to the right sections sometimes, and we're thinking of changing it. for now the github url is less likely to change i think.
