### ISSUE TITLE
WebView not wotks if there is Google Play on device ?!

### ISSUE THREAD

**Issue by dexterdj** [appium/appium-desktop#820]
Hello,

I have an issue on both version Desktop and CLI.

I use Appium 1.10.0 and also tester 1.7.1 (Desktop and CLI)

## The problem

I have a problem detecting WebView on a device where there is Google Play / Google Store installed.

In this configuration i have zero problem : 

 - Emulator Nexus and Galaxy Android 7.1.1 and 8.0.0
 - No Play Store

My code (Python 3.6) can detect 2 contexts "NATIVE_APP" and "WEBVIEW_app.android".
I can switch context, and make operation on the webview like executing JS, .... **All OK**

In others configuration, like this : 

 - Emulator Nexus and Galaxy Android 7.1.1 and 8.0.0
 - With Play Store

Or on real device (Galaxy S9 Android 8.0.0) connected in USB

My code can only detect "NATIVE_APP" and i cannot switch to webview. If try to switch to "WEBVIEW_app.android" I obtain a NoSuchContextException. 

Anyone have infos about this case ? Is Google Play can block WebViews access on other apps ?!

Thanks you,

**Comment by dpgraham** [comment]
Can you see if you're able to debug the WebView via Chrome, by opening `chrome://inspect`.

Also, try downloading Chromedriver and see if you can run a Selenium session. If Chrome inspector and Chromedriver can't find the WebView, then it's not an Appium issue.

**Comment by dexterdj** [comment]
Hi,

Thanks for your response.

On inspector i cannot detect the WebView. So yes it's not Appium issue ...

You have no idea why we have different results when there is Google Store on the device ?

On a device without Google Store, i can detect the webview on inspector, zero problem  ... 
(But my app have a Safety Net vérification and i need to have Google Store on the device so I cannot debug  ...)

Thanks again, i'll search on android side ;)

**Comment by dpgraham** [comment]
No problem. I'd be curious to know what your findings are. That's strange.
