### ISSUE TITLE
iOS class chain locator finds all descendent elements if desired child element not there in parent.

### ISSUE THREAD

**Issue by sandeeppremise** [appium/appium-desktop#821]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by sandeeppremise** [comment]
iOS class chain locator finds all descendent elements if desired child element not there in parent.

Having code as below:

<XCUIElementTypeTable>
       <XCUIElementTypeCell>
               <XCUIElementTypeStaticText name="US$ 4.00 ∙ 5-10 min">
               <XCUIElementTypeOther>
              <XCUIElementTypeStaticText name="QA- Hint Images (many images)">
              <XCUIElementTypeImage>
<XCUIElementTypeCell>
<XCUIElementTypeStaticText name="US$ 5.00 ∙ 55-10 min">
               <XCUIElementTypeOther>
              <XCUIElementTypeStaticText name="Test name">
              <XCUIElementTypeImage>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeCell>
<XCUIElementTypeTabBar>
<XCUIElementTypeWindow>
<XCUIElementTypeWindow>

Used below classchain:**/XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeStaticText[3]
If you see first TypeCell element, there are only 2 child elements of  type "XCUIElementTypeStaticText". So when i run ":**/XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeStaticText[3]" it should give no element because there are only two elements, instead it gives third element which is part of 2nd TypeCell element. And if i use "**/XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeStaticText" then it gives all descendant  "XCUIElementTypeStaticText" element.It should give only two elements as XCUIElementTypeCell[1] parent element have only 2 XCUIElementTypeStaticText

**Comment by dpgraham** [comment]
I don't think this can be fixed because class chain locator is defined by Apple not by Appium.

**Comment by sandeeppremise** [comment]
Thanks @dpgraham . any solution/workaround anyone knows. Xpath is giving correct me correct behaviour but i can not use it as it is taking much time in iOS Appium automation.

**Comment by dpgraham** [comment]
I'm not sure, unfortunately.

**Comment by sandeeppremise** [comment]
Ok. Thanks @dpgraham .
