### ISSUE TITLE
Is it possible to specify Multiple APK in Appium desktop path ???

### ISSUE THREAD

**Issue by SowmyaKarthik** [appium/appium-desktop#823]
Im automating the project using Appium technology. To locate the element I'm using Appium desktop.The project which I'm working has 5 apk file in it.

For Eg

- apk1
- apk2
- apk3
- apk4
- apk5

if I specify the path of apk1 in appium desktop it launches the apk1 for few seconds and it waits for apk2 to be launched and displays and error .And the same goes for apk2 .Its like a chain process.

how to resolve this issue??

**Comment by dpgraham** [comment]
Yes, there's an `otherApps` desired capability (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md).
