### ISSUE TITLE
[Enhancement Request] - Need option to try out different locators similar to older version of appium desktop

### ISSUE THREAD

**Issue by vikramvi** [appium/appium-desktop#83]
In older version of appium desktop there was a very useful feature to try out different locators
can we please add in this version as well ?

- sometimes app doesn't have id, accessibilityID and most of the engineers end up using absolute xpath.
- But without the locator checking mechanism it's hard to test absolute xpath.

Please review

![screen shot 2017-03-14 at 10 48 28 am](https://cloud.githubusercontent.com/assets/308490/23894993/80829e28-08a4-11e7-9c31-0e7041a3405f.png)

**Comment by dpgraham** [comment]
Yeah, this is on our list. Another thing we're going to do is make a locator generator that generates a locator for a given element.

**Comment by stmacker** [comment]
Probably in the works but even just a copy full xpath path button either on right clicking the element in the tree or listed in the element details in the right pane would be super helpful.

**Comment by dilsreccse** [comment]
@vikramvi can you tel the steps that you followed in using the appium dmg version , i'm facing the following issue  #https://github.com/appium/appium-desktop/issues/94

**Comment by jlipps** [comment]
a simple version of this feature has now been added

**Comment by vikramvi** [comment]
![screen shot 2017-04-05 at 12 06 01 pm](https://cloud.githubusercontent.com/assets/308490/24700710/4d635b58-19f8-11e7-9920-89aa6fd9c561.png)

@jlipps I checked for this requested feature with version 1.0.0-beta.6 but didn't find it.
Please refer to attached screen shot.

Ideally there should be field where I can check for locator, in this case I want to generate custom xpath for link "Continue using web browser" but can't do it.

can you please re-open this issue ?

Thanks & Regards,
Vikram

**Comment by dpgraham** [comment]
It's in the 'findBy' table in the top of the selected element panel

**Comment by vikramvi** [comment]
@dpgraham didn't get how to try out different identifiers per your last answer, can you please provide screen shot ?

**Comment by dpgraham** [comment]
The 'findBy' table under selected element has a locator strategy + a locator for the selectedElement.

I made a PR yesterday that does a shorter, more optimal xpath instead of the long, absolute xpaths we have now.

**Comment by vikramvi** [comment]
@dpgraham Thanks a ton for your awesome work; confirming that requested feature here is working as expected in release 1.2.0-beta.3

**Comment by dpgraham** [comment]
Thanks @vikramvi, it was my pleasure!

The feature is available, yes. And we also have a feature where you can test selectors.
