### ISSUE TITLE
After closing the protocol popup, APPIUM could not find all the elements of the page.

### ISSUE THREAD

**Issue by testeryang** [appium/appium-desktop#833]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
关闭弹出的协议弹窗后，APPIUM处于无响应的状态，导致该页面的其他元素都无法定位到
![11110](https://user-images.githubusercontent.com/22884300/53334686-783f2e80-3934-11e9-82bd-6ca526069208.png)

## Environment
win10
- I am running Appium Desktop version _1.7-1,10all have
- I am on (pick one):

    - [x] Windows

**Comment by dpgraham** [comment]
(original title: 关闭协议弹窗后，APPIUM无法找到页面的所有元素了)

**Comment by dpgraham** [comment]
Will re-open if this is still an issue.
