### ISSUE TITLE
the interface loaded into the phone always falls down

### ISSUE THREAD

**Issue by ZZXLX** [appium/appium-desktop#838]
Appium Desktop?

## The problem
 
When I use the new session window, I configure the parameters of the app, and the interface loaded into the phone always falls down.
## Environment

- I am running Appium Desktop version _<v1.10.0>_.
- I am on (pick one):
Windows
 
![image](https://user-images.githubusercontent.com/38346311/53476332-148c4100-3aad-11e9-806e-3a1459d5a5bb.png)

**Comment by dpgraham** [comment]
Can you try using adb to take a screenshot and see what happens?

https://blog.shvetsov.com/2013/02/grab-android-screenshot-to-computer-via.html
