### ISSUE TITLE
I can launch the iOS app but cannot click on any element using Appium 2 desktop

### ISSUE THREAD

**Issue by KajalJena** [appium/appium-desktop#840]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After I've upgraded to Appium Desktop 1.10.0 , i can launch the ios app on simulator but failed to click on any element or enter text value , basically can't do any action on app.  This worked fine with 1.7.0 version and ios 11 but after we upgrade to ios12 it stopped working and I took the latest version for desktop app which is partially working. Just managed to launch the app and eventually failed to find any element on page and doing any action.

Appium server error log

info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m15436 ms - 708[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c/element[39m
[info] [35m[HTTP][39m [90m{"using":"xpath","value":"//XCUIElementTypeTextField[@name='Email']"}[39m
[debug] [35m[W3C (009d6917)][39m Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTextField[@name='Email']","009d6917-fab4-4b22-81c9-6a01edb6d47c"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[JSONWP Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element] to [POST http://localhost:8100/session/016F06C4-9F05-4D2F-97D2-696E54DA9EE3/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[@name='Email']"}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"value":{"ELEMENT":"4D000000-0000-0000-EC5F-010000000000"},"sessionId":"016F06C4-9F05-4D2F-97D2-696E54DA9EE3","status":0}
[debug] [35m[W3C (009d6917)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"4D000000-0000-0000-EC5F-010000000000","ELEMENT":"4D000000-0000-0000-EC5F-010000000000"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c/element [39m[32m200[39m [90m1725 ms - 137[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c/element[39m
[info] [35m[HTTP][39m [90m{"using":"xpath","value":"//XCUIElementTypeTextField[@name='Email']"}[39m
[debug] [35m[W3C (009d6917)][39m Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTextField[@name='Email']","009d6917-fab4-4b22-81c9-6a01edb6d47c"]
[debug] [35m[XCUITest][39m Executing command 'findElement'
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[JSONWP Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element] to [POST http://localhost:8100/session/016F06C4-9F05-4D2F-97D2-696E54DA9EE3/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[@name='Email']"}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"value":{"ELEMENT":"4D000000-0000-0000-EC5F-010000000000"},"sessionId":"016F06C4-9F05-4D2F-97D2-696E54DA9EE3","status":0}
[debug] [35m[W3C (009d6917)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"4D000000-0000-0000-EC5F-010000000000","ELEMENT":"4D000000-0000-0000-EC5F-010000000000"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c/element [39m[32m200[39m [90m1801 ms - 137[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c/execute/sync[39m
[info] [35m[HTTP][39m [90m{"script":"return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca([39m
[debug] [35m[W3C (009d6917)][39m Calling AppiumDriver.execute() with args: ["return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca(a,b,c){return a.call.apply(a.b...
[debug] [35m[XCUITest][39m Executing command 'execute'
[debug] [35m[W3C (009d6917)][39m Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [35m[W3C (009d6917)][39m     at XCUITestDriver.extensions.execute (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[debug] [35m[W3C (009d6917)][39m     at curCommandCancellable._bluebird.default.resolve.then (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/driver.js:291:18)
[debug] [35m[W3C (009d6917)][39m     at tryCatcher (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [35m[W3C (009d6917)][39m     at Promise._settlePromiseFromHandler (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [35m[W3C (009d6917)][39m     at Promise._settlePromiseAt (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [35m[W3C (009d6917)][39m     at Promise._settlePromiseAtPostResolution (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [35m[W3C (009d6917)][39m     at Async._drainQueue (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [35m[W3C (009d6917)][39m     at Async._drainQueues (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [35m[W3C (009d6917)][39m     at Immediate.Async.drainQueues (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [35m[W3C (009d6917)][39m     at runCallback (timers.js:696:18)
[debug] [35m[W3C (009d6917)][39m     at tryOnImmediate (timers.js:667:5)
[debug] [35m[W3C (009d6917)][39m     at processImmediate (timers.js:649:5)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c/execute/sync [39m[33m405[39m [90m11 ms - 1738[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/009d6917-fab4-4b22-81c9-6a01edb6d47c[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (009d6917)][39m Ca

## Environment

- Platform version- 12.1 
- I am running Appium Desktop version _<1.10.0>_.
- I am on Windows and running the Appium app on Mac remotely.
    
```
Sample code:

            DesiredCapabilities caps = DesiredCapabilities.IPhone();
            caps.SetCapability("platformName", "ios");
            caps.SetCapability("automationName", "XCUITest");
            caps.SetCapability("clearSystemFiles", true);
            caps.SetCapability("deviceName", $"{deviceName}");
            caps.SetCapability("platform", "Mac");
            caps.SetCapability("platformVersion", $"{platformVersion}");
            caps.SetCapability("app", $"{app}");
            caps.SetCapability("xcodeSigningId", "iPhone Developer");
            caps.SetCapability("appPackage", "xxxx");
            caps.SetCapability("xcodeOrgId", xcodeOrgId);           
            caps.SetCapability("udid", $"{udid}");
             driver = new IOSDriver<IWebElement>(new Uri(ip), caps, TimeSpan.FromSeconds(240));
      

Assert.IsTrue(IosDriver.FindElementByAccessibilityId("Sign In").Displayed);            Assert.IsTrue(IosDriver.FindElementByXPath("//XCUIElementTypeTextField[@name='Email']").Displayed);
 IosDriver.FindElementByXPath("//XCUIElementTypeButton[@name='Sign In']").Click();
```
Any help would be appreciated

**Comment by dpgraham** [comment]
Sorry for the late reply

The Appium 2 branch is very stale. Probably needs a big overhaul or re-write.
