### ISSUE TITLE
 An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability (WARNING: The server did not provide any stacktrace information) 

### ISSUE THREAD

**Issue by sevenbitshweta** [appium/appium-desktop#841]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I'm finding the kind of error :  **An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability (WARNING: The server did not provide any stacktrace information)**
Command duration or timeout: 208 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 02:56:46'
System info: host: 'sevenbits-HP-Compaq-8100-Elite-SFF-PC', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-141-generic', java.version: '1.8.0_152-release'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

## Environment
"platformName": "Android",
"platformVersion": "5.1",
"deviceName": "Moto",

- I am running Appium Desktop version _<V1.10.0>_.
- I am on :
  
    - [ ] Linux

**Comment by viccky88** [comment]
@sevenbitshweta Please provide the complete desired capabilities JSON data.

**Comment by sevenbitshweta** [comment]
capabilities.setCapability(**"DEVICE_NAME", "Moto E"**);

(**CapabilityType.BROWSER_NAME, "Android"**);

(**"PLATFORM", "Android"**);

(**CapabilityType.VERSION, "5.1"**);

        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by viccky88** [comment]
PLATFORM is not a capability. Use "platformName". 
Please refer "http://appium.io/docs/en/writing-running-appium/caps/" for desired capabilities details.

**Comment by dpgraham** [comment]
Thanks for the help @viccky88 !

**Comment by michaeldeven** [comment]
![image](https://user-images.githubusercontent.com/97597835/159831750-9370ac83-bf5a-48fe-bb43-e8e8126a2834.png)

**Comment by michaeldeven** [comment]
help me

**Comment by wswebcreation** [comment]
@michaeldeven 

Please fix your typo in the `platformName` capability. The error message is telling you what's wrong 😉

**Comment by michaeldeven** [comment]
thankyou!
