### ISSUE TITLE
error - package not found on emulator device

### ISSUE THREAD

**Issue by aditigarg0120** [appium/appium-desktop#850]
I am getting an error - Original error: Could not find package "package name" on the device.
running appium desktop app with emulator -
{
"deviceName": "Nexus 6P API 28",
"appPath": "E:\app-debug.apk",
"appActivity": "activityname",
"appPackage": "packagename",
"platformName": "Android",
"skipUnlock": true,
"noReset": false
}

when clicked on start session it is showing package could not be found.
Using windows 10pro
C:\WINDOWS\system32>appium -v
1.11.1

C:\WINDOWS\system32>node -v
v11.10.1

C:\WINDOWS\system32>npm -v
6.7.0

appium error log -
[AndroidDriver] Error: Could not find package on the device
[AndroidDriver] at Object.wrappedLogger.errorAndThrow (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-support\lib\logging.js:78:13)
[AndroidDriver] at AndroidDriver.checkPackagePresent (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-android-driver\lib\driver.js:377:11)
[AndroidDriver] at process._tickCallback (internal/process/next_tick.js:68:7)
[AndroidDriver] Shutting down Android driver

Earlier everything was working fine. Suddenly appium stopped working on emulators.
One emulator got crashed between this, have tried with another emulator but no result.

Please help

**Comment by dpgraham** [comment]
```js
"appActivity": "activityname",
"appPackage": "packagename",
```

^ are you sure those are valid activity and package names?

**Comment by aditigarg0120** [comment]
Yes, these are the valid activity and package names, earlier the code was working fine. Suddenly it was stopped working due to emulator get crashed.

The issue has been resolved.
How - 
1. Created a new virtual device.
2. Passed the desired capabilities  - {
"deviceName": "Nexus 6P API 28",
"app": "E:\app-debug.apk",
"platformName": "Android"
}
3. this will install the apk very first time inside the emulator
(here app package name and activity name is not required)
4. Second time if we want to pass the app package name and activity we can pass it will work.
5. I have tried and it is working fine now.
{
"deviceName": "Nexus 6P API 28",
"app": "E:\app-debug.apk",
"appActivity": "<activityname>",
"appPackage": "<packagename>",
"platformName": "Android",
"skipUnlock": true,
"noReset": false
}

The issue can be closed.

**Comment by aditigarg0120** [comment]
first time it will not recognize the package name.
This is the reason it was showing error - package couldn't be found on your device.

**Comment by KazuCocoa** [comment]
In_this will install the apk very first time inside the emulator_ case, Appium assumes the package name from the manifest file. If the name is not expected one in step 5, this can happen.

otherwise, will close this as _The issue can be closed._
