### ISSUE TITLE
Xcode version '0.1'. Support for Xcode 0.1 is not supported

### ISSUE THREAD

**Issue by l3vick** [appium/appium-desktop#858]
## The problem

Error
An unknown server-side error occurred while processing the command. Original error: Xcode version '0.1'. Support for Xcode 0.1 is not supported. Please upgrade to version 7.3 or higher

## Environment

- I am running Appium Desktop version  1.11.0
- I am on Mac
- Xcode 10.1
  Build version 10B61

**Comment by imurchie** [comment]
Please provide the server logs as a link to a [gist](https://gist.github.com). This problem has been long-solved.

**Comment by mra419** [comment]
@l3vick - I am also facing the same issue, did you able to resolve this issue? if yes, Can you please provide the steps what you have done to resolve this issue.

**Comment by thepoppingone** [comment]
I have overcame this by doing 2 steps:
1) Update the appium-server in the appium npm module -> `npm -g i appium`
2) Try running WDA test on the device as a test run
