### ISSUE TITLE
Original error: Could not find aapt in /usr/local/share/android-sdk/platform-tools/aapt,/usr/local/share/android-sdk/emulator/aapt,/usr/local/share/android-sdk/tools/aapt,/usr/local/share/android-sdk/tools/bin/aapt. Do you have the Android SDK installed at '/usr/local/share/android-sdk'?

### ISSUE THREAD

**Issue by hash2530** [appium/appium-desktop#859]
## Appium Desktop Appium CLI

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

## Environment
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/2958078/appium-server-logs.txt)
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/2958083/appium-server-logs.txt)

- I am running Appium Desktop version _<1.11.1>_.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
It looks appium could not detect the commands.
Current Appium has been improved the detection logic, so try the newer one
