### ISSUE TITLE
How to access the Inspector window of Appium Desktop in the PC web browser

### ISSUE THREAD

**Issue by kangbo256** [appium/appium-desktop#861]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

How to access the Inspector window of Appium Desktop in the PC web browser？ my running environment is window10, Android, Firefox or Google Chrome。

## Environment

- I am running Appium Desktop version _1.10.0_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
That's not a feature we have yet. Right now it's only Electron.
