### ISSUE TITLE
v1.11.1 of AD reports notorious "code 65", but CLI of the same works fine 

### ISSUE THREAD

**Issue by semvo** [appium/appium-desktop#865]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_So, as the title says, I can run the same CLI version just fine, but the desktop GUI version reports "xcodebuild failed with code 65" error.

10:29:05.040 xcodebuild[22245:714965] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7fe06ac6bbc0 {Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for WebDriverAgentRunner-Runner.app couldn't be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: "/Users/xxxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app"., NSURL=file:///Users/xxxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/, NSFilePath=/Users/xxxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSLocalizedDescription=The bundle identifier for WebDriverAgentRunner-Runner.app couldn't be read.}}}
## Environment

- I am running Appium Desktop version _1.11.1_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
Does this still happen with Appium 1.12.1?
