### ISSUE TITLE
Appium inspector does not keep the session active

### ISSUE THREAD

**Issue by CAPie** [appium/appium-desktop#872]
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
issue is related to: https://github.com/appium/appium-desktop/issues/498
Appium inspector does not keep the session active.

### Steps to reproduce:
User use Appium inspector connected to Custom server.
After 5 mins of inactivity appears some popup which asks user what to do with current session.
Problem appears if user haven't seen that popup 
> Session Inactive
> Your session is about to expire
> buttons: [quit session] [keep session]

Because of coding in other window

After returning to Appium inspector user see:
> Error
> Session closed due to inactivity

I've tried to set the `newCommandTimeout: 1800` (30 min) in `desiredCapabilities`. Still the same.

As I understand this solution is required for some cloud services (like BrowserStack) 

### Possible solution:
- Do not interrupt session due to inactivity for "Automatic Server" and "Custom Server" cause it's not needed.
- Add some CLI flag to be able to run Appium inspector with different inactivity timeout.
- Parse `newCommandTimeout` from `desiredCapabilities` and use it as inactivity timeout.

## Environment

- I am running Appium Desktop version _1.10.0 (1.10.0.20181230.2)_.
- I am on (pick one):
    - [x] Mac
    - Probably other envs have the same issue

**Comment by dpgraham** [comment]
Yeah, I need to revisit this. This feature seems to have problems.

**Comment by Vijayabaskar03** [comment]
Yeah, this is a bit annoying since my app clears the session details everytime it is launched, so I have to login everytime Appium closes the session.

**Comment by dpgraham** [comment]
This will be in next version. I've set the timeout to 24 hours instead of 5 minutes.
