### ISSUE TITLE
#UI issue. Spelling of "improve" is wrong in window right after we launch the newest version.

### ISSUE THREAD

**Issue by SivaPrasad186** [appium/appium-desktop#878]
This issues was found in Appium Desktop in version v1.11.0. 

We will get this window when we are launching the client after downloading the newest version.
The text in the window is as below:

"Can Appium Desktop collect crash log data from you to help **immprove** the product?"

**Comment by dpgraham** [comment]
Yeah, that will be fixed in the next version. Thank you!
