### ISSUE TITLE
i am using appium version 1.11.0 i am facing one issue my application running on my physical  device properly this error coming"An element could not find given such as peremeters" please help me in this error

### ISSUE THREAD

**Issue by srisudhi** [appium/appium-desktop#879]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by rkn411** [comment]
Did u mentioned in setcapabilities  as Uiautomator2

**Comment by srisudhi** [comment]
hi,
using APPIUM STUDIO

**Comment by KazuCocoa** [comment]
Could you contact Appium Studio support?
