### ISSUE TITLE
How i can perform parallel test

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium-desktop#880]
i have managed to run test on multiple devices but one after another how i can run same test on multiple devices at same time (parallel)

**Comment by dpgraham** [comment]
You'll need to use [Selenium Grid](https://www.seleniumhq.org/projects/grid/) or you'll need to subscribe to a cloud Appium provider (SauceLabs, Browserstack, Headspin, etc...)

It can't be done from within Appium Desktop though.
