### ISSUE TITLE
Appium Desktop stucks/stop printing any logs as soon as mobile app login page loads

### ISSUE THREAD

**Issue by sensuraj92** [appium/appium-desktop#898]
Hi Team,

As soon as my mobile app login page loads, i am not able to perform any action through automation like finding elements, fetching page source etc

please help me in resolving the issue
![aplpium_server](https://user-images.githubusercontent.com/41458305/54862685-5f277300-4d64-11e9-9bcf-118648dba26f.PNG)

**Comment by rajkumar-cp** [comment]
@sensuraj92 
Any updates on this issue. I am also facing same kind of problem
Appium version : 1.9.0
Android version : 8.0
Emulator ( Using android studio)

**Comment by imurchie** [comment]
I would first try switching to UiAutomator2 for Android 8 (by setting the `automationName` capability to `"uiautomator2"`).

**Comment by rajkumar-cp** [comment]
@imurchie 
I have used that capability and i am still facing this issue.

**Comment by imurchie** [comment]
Please post the full server logs as a link to a [gist](https://gist.github.com).

**Comment by rajkumar-cp** [comment]
@imurchie 
I was not able to fetch the logs because after a while the screen (appium for desktop) frozen and turns to absolute white. I was not able to interact with the screen like stop the server ,get raw logs etc.

**Comment by imurchie** [comment]
Can you run from a script rather than `appium-desktop`?

**Comment by rajkumar-cp** [comment]
Can you run from a script rather than appium-desktop? -->  Can you please elaborate a bit more.

**Note:** This issue occurs only when we were trying t run the scripts in parallel(More than 1 emulator). It does not occurs when we were trying to execute our scripts individually or through 3rd parties (Saucelabs or pcloudy).

**Comment by imurchie** [comment]
Ok. Why does this have anything to do with `appium-desktop`? Run the Appium server from a command line terminal.
