### ISSUE TITLE
Appium-Desktop v.1.11.0 offers to update to v.1.10.0

### ISSUE THREAD

**Issue by dcnt** [appium/appium-desktop#900]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium-Desktop v.1.11.0 offers to update to v.1.10.0

## Environment

- I am running Appium Desktop version _<1.11.0>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

![Screen Shot 2019-03-25 at 6 30 58 PM](https://user-images.githubusercontent.com/2023434/54937361-f0494600-4f2c-11e9-8da9-f9ceba2e8a5f.png)

**Comment by CoryWritesCode** [comment]
Same 👆

**Comment by edominescy** [comment]
What they said 👆

**Comment by dpgraham** [comment]
I unpublished 1.11.0 due to a bug causing capability sets to be erased. You're welcome to keep using 1.11.0 but there's a risk of your data being lost.

**Comment by dpgraham** [comment]
I'm testing a fix right now and will have 1.11.1 out some time this week.

**Comment by CoryWritesCode** [comment]
@dpgraham this is still happening with the pre-release of 1.12.0 is that something that is still in the works?

**Comment by dpgraham** [comment]
Once the pre release is changed to a full release it won't happen.
