### ISSUE TITLE
Appium-1.11.0.dmg file has been removed?

### ISSUE THREAD

**Issue by hitsubunnu** [appium/appium-desktop#901]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The file has been removed. Can't download.
https://github.com/appium/appium-desktop/tags

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by RicardoTrivinoSanchez** [comment]
I have the same question. I have installed the 1.11.0 version of Appium Desktop, and yesterday night (March 25) I started to get a pop-up telling me to "upgrade to 1.10.0". And I see that now the last version on Github is the 1.10.0

**Comment by dpgraham** [comment]
That's correct, yes. 1.11.0 was unpublished due to a major bug causing Saved Capability Sets to be deleted. I'm working on 1.11.1 right now.
