### ISSUE TITLE
(iOS) An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID

### ISSUE THREAD

**Issue by jlee6890** [appium/appium-desktop#907]
## Appium or Appium Desktop?

This is for Appium Desktop. Appium itself is working fine.

## The problem

I got the issue with Appium Desktop as soon as I updated to XCode 10.2 and tried to run a session. The UDID I used for the simulator I got from running `instruments -s devices` in the terminal.

## Environment

Here is the desired capabilities i'm using:

```
{
  "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "12.2",
  "deviceName": "iPhone 7 Plus",
  "app": "test.app",
  "udid": "5F3E67D5-C96E-4D40-A32F-51E8A2DF82FF",
  "newCommandTimeout": "3600"
}
```
What i'm running:
macOS 10.14.4
XCode 10.2
Appium 1.12.1

- I am running Appium Desktop version _<1.10.0>_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by elmzaoug** [comment]
Same issue after updating xcode.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/12391#issuecomment-477057988

**Comment by KazuCocoa** [comment]
the cause is device list format has been changed in Xcode 10.2.
It could not downgrade if you install Xcode 10.2 (include beta) once, unfortunately.
The above comment is how to connect to running local Appium server via the desktop.
(as a workaround)
