### ISSUE TITLE
Appium desktop launches the app with Response status 13 unknownError

### ISSUE THREAD

**Issue by Ayetri** [appium/appium-desktop#908]
##  Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I am able to launch my app in emulator  but the moment I click on Refresh button in appium dektop gui to get the labels . It throws error and not loading  anything , showing continuous spinner .
![Uploading Screen Shot 2019-03-27 at 18.31.22.png…]()

## Environment

- I am running Appium Desktop version _<1.0.0>_.
- I am on (pick one):
    - [-- ] Mac
- Appium Server : 1.6.4

My Appium Capability set : 

{
  "platformName": "Android",
  "platformVersion": "7.1.1",
  "app": "*.apk"
  "automationName": "UiAutomator2",
  "deviceName": "Nexus_5X_API_23",
  "avd": "Nexus_5X_API_23"
}

**Comment by KazuCocoa** [comment]
I guess something happened on the server, Try out a newer version.
