### ISSUE TITLE
WAD not installed with Appium Desktop 

### ISSUE THREAD

**Issue by ososunfield** [appium/appium-desktop#910]
When I install Appium 1.10 on Windows 10  it does not install WAD automatically as mentioned in Documentation.

I have activated Developer mode on Windows 10 as described in Documentation as well.
Does anyone have experience with this issue? 

Thanks

**Comment by dpgraham** [comment]
Does this happen if you try to install Appium from the command line too? (`npm install -g appium`)

**Comment by ososunfield** [comment]
Hi Dan,

thanks for your response.

I uninstalled WAD and Appium. Then executed the command you provided in a cmd window as administrator.

I received the following feed back during install:

[cid:image004.png@01D4E609.C2DCC750]

Then started appium and received this feed back. This is the same “error” I received before. So, yes , it also happens when installing from cmd line.
Any suggestions ?

[cid:image005.png@01D4E609.C2DCC750]

Thanks for your help !

Regards
Oliver

**Comment by dpgraham** [comment]
I would open an issue with WinAppDriver github and see what they say... they may have a workaround for you.

We don't directly maintain WAD.
