### ISSUE TITLE
When i run desktop for a while,it automatic out of service

### ISSUE THREAD

**Issue by jx-coder** [appium/appium-desktop#913]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
When i run appium desktop for a while,it automatic out of service

## Environment

- I am running Appium Desktop version 1.11.0.
- I am on (pick one):
    - [ ] Windows

**Comment by dpgraham** [comment]
This is being fixed next version
