### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Bad app: ⁨⁨/../../. App(ipa) paths need to be absolute or an URL to a compressed file

### ISSUE THREAD

**Issue by sevenbitshweta** [appium/appium-desktop#915]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

when i am running these tests then constantly getting the error of Bad app:

_Replace this section with a description of your issue_

"platformName": "iOS",
  "deviceName": "iPhone Simulator",
  "platformVersion": "12.1",
  "app": "⁨⁨/../../...ipa",
  "automationName": "XCUITest",
  "noReset": true

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by dpgraham** [comment]
`"⁨⁨/../../...ipa"` is a bad URL

Wherever your IPA is, you need to provide an absolute path to it.

Something like: `/Users/<username>/path/to/app.ipa`
