### ISSUE TITLE
Why: when i install 1.9.1, the GUI says it is 1.10.0

### ISSUE THREAD

**Issue by austenjt** [appium/appium-desktop#918]
## Appium or Appium Desktop?

Problem with Appium Desktop on Mac oSX.   Downloaded from : https://github.com/appium/appium-desktop/releases/tag/v1.9.1

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I install Appium Desktop 1.9.1,  after having later versions of the app on my system, Appium desktop says it is version 1.10.0 

## Environment

- I am running Appium Desktop version 1.9.1 . (download url provided above)
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment]
The Appium version is 1.10.0 but the version of the GUI Client is 1.9.1

This is going to get more confusing now that the versions are almost the same.

**Comment by austenjt** [comment]
@dpgraham    Your last comment does not explain the  coincidence that when I install Appium desktop  v.1.12.1 GUI,   when it starts Appium, the appium console listener ALSO says it's version 1.12.1    .   Either your previous comment is accurate and this is a coincidence,  or perhaps  the GUI client is supposed to be in sync with Appium version?    At least it appears to be so from my point of view.
