### ISSUE TITLE
Elements are not highlighted in the preview screen on selecting Ids from the search result 

### ISSUE THREAD

**Issue by Vijayabaskar03** [appium/appium-desktop#919]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Upon searching for an element with a valid selector, the matching elementIDs are returned like earlier but on selecting the ID, the corresponding element is not highlighted anymore in the preview screen with the latest version of Appium Desktop.

## Environment

- I am running Appium Desktop version 1.12.0.
- I am on (pick one):
    - [x] Windows

![image](https://user-images.githubusercontent.com/24304928/55271852-10e81600-5308-11e9-8685-18e79ed3b9a6.png)

**Comment by vinaym512** [comment]
I am also facing the same with version 1.1.2.0, it was all fine in last version

**Comment by dpgraham** [comment]
Thanks for reporting this! I'll have a look today.

**Comment by dpgraham** [comment]
I have a fix in for this. This will be next release.

**Comment by denysvoskovets** [comment]
Still have this issue on Appium Desktop version 1.12.1

**Comment by benzionyunger** [comment]
I was having this issue on the latest release 1.20.2, I went back to 1.18.3 and I'm still having this issue. Unfortunately I don't remember which version I had previously which did work. 
Can you verify for me which version this did work? I am using Appium Desktop to test with WinAppDriver.

**Comment by htshawabkeh** [comment]
Hello Dears,

Im currently facing the same issue on Appium Server GUI 1.22.0 and Appium Inspector 2021.12.2 , when searching for any element locator, it wont highlight the element in the preview screen for the search results 

Appreciate your help

Thanks,
