### ISSUE TITLE
Elements highlighted goes outside box - Appium Inspector

### ISSUE THREAD

**Issue by AdarshKumarGM** [appium/appium-desktop#924]
**Appium Desktop Version:** 1.12.1
**IOS Simulator**: iPhone XS
**IOS Simulator Version**: 12.1
**Mac Version**: Mojave 10.14.3

After launching the native app in IOS simulator, In the Appium inspector, you can observe on the right hand side that element found will be outside the box i.e. it doesn't get trimmed/fit to the Appium Inspector box. We need to expand it manually to see the ID/Xpath. 

<img width="1071" alt="Screenshot 2019-04-02 at 11 25 04 AM" src="https://user-images.githubusercontent.com/46774573/55379491-e6ca6a00-553a-11e9-8b59-002704613f05.png">

**Comment by ervuks** [comment]
The same problem appears when launching an Android app as well. 
So this is Appium desktop issue for sure on [Appium desktop 1.20.x version](https://github.com/appium/appium-desktop/releases/tag/v1.12.0)

**Comment by AdarshKumarGM** [comment]
oh yes!! I have temporarily reverted back to 1.10.0 version. There is another issue opened i.e. Elements not getting highlighted( I am also facing the same ), I guess this release is not that stable.

**Comment by KazuCocoa** [comment]
The broken layout should be fixed in newer versions
