### ISSUE TITLE
I am encountering with an issue: Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\someName\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s TA09405IBZ forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''

### ISSUE THREAD

**Issue by gouravsonare** [appium/appium-desktop#927]
## Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I am trying to start emulator it is giving below errors related to the **Unable to remove port forward 'Error executing adbExec.
and Error: packageAndLaunchActivityFrommanifest failed.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [-] Windows
    

## Attaching Logs below:
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\someName\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s TA09405IBZ forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[ADB] Device API level: 22
[BaseDriver] Event 'newSessionStarted' logged at 1554347704440 (08:45:04 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: packageAndLaunchActivityFromManifest failed. Original error: Command 'C\:\\Users\\someName\\AppData\\Local\\Android\\Sdk\\build-tools\\29.0.0-rc1\\aapt.exe dump badging C\:\\Users\\someName\\Desktop\\Orange-TV.apk' exited with code 1; StdErr: W/ziparchive(11868): Zip: missed a central dir sig (at 0)
[MJSONWP] W/zipro   (11868): Error opening archive C:\Users\gsonare\Desktop\Orange-TV.apk: Iteration ended
[MJSONWP] ERROR: dump failed because no AndroidManifest.xml found
[MJSONWP] 
[MJSONWP]     at ADB.manifestMethods.packageAndLaunchActivityFromManifest (C:\Users\someName\AppData\Local\Programs\Appium\resources\app\node_modules\appium-adb\lib\tools\android-manifest.js:188:9)
[HTTP] <-- POST /wd/hub/session 500 10353 ms - 630
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP]

**Comment by gouravsonare** [comment]
Please help me to resolve the same.

Although, I was able to start an application over emulator and mobile devices earlier with the same configuration and capabilities.

Desired Capabilities below:
{
  "platformName": "Android",
  "platformVersion": "8.0",
  "deviceName": "Pixel API 26",
  "udid": "6844433e",
  "app": "C:/Users/someUser/Downloads/MobileApplication.apk"
}

**Comment by KazuCocoa** [comment]
Can you run with build-tools 28?
We have not fully tested the 29.0.0rc1.

And try to set `automationName: uiautomator2` for OS8.0 for the 2nd comment

**Comment by StefanVanElk** [comment]
I also have the "error: listener 'tcp:8200' not found" issue, using:
{
  "platformName": "Android",
  "deviceName": "Pixel 2",
  "app": "/Users/stefane/Downloads/app-qa-930-169.apk",
  "automationName": "uiautomator2"
}

I have tried using build-tools 28 (and 27), but without success.

**Comment by KazuCocoa** [comment]
I hope a newer Android SDK version works..
