### ISSUE TITLE
Refresh Source & Screenshot

### ISSUE THREAD

**Issue by toien44** [appium/appium-desktop#928]
## The problem

After I start the server and I get the splash screen, then go into the app I try to refresh source and get a new screenshot, but Appium will freeze and have a spinner and the page with elements will not render

## Environment
mac OS 10.14.4
Appium Desktop 1.12.1 ( but has been happening for a while)

Has issues periodically on Android and iOS
Simulator/Emulators

## Link to Appium logs

Appium Logs:
```
Calling AppiumDriver.getPageSource() with args: ["2e7f3ff2-66ac-48be-860c-79b43c702e83"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
```
Just repeats these logs and

**Comment by toien44** [comment]
Adding automationName=UiAutomator2 makes appium not even start up.

```
"deviceName": "Galaxy_Nexus_API_28",
  "automationName": "UiAutomator2",
  "platformVersion": "9",
  "platformName": "Android",
  "app": "com.company.name"
```
it says
```
Encountered internal error running command: Error: The application at 'com.company.name' does not exist or is not accessible
```
but I'm using the same app and emulator, but when I don't add the automationName it "starts" but has the above issue.

**Comment by dpgraham** [comment]
`app` needs to be an absolute path to an APK. Or you can use `appPackage` and `appActivity` in the caps.

**Comment by toien44** [comment]
That worked. Thanks, I was using app before without using automationName. Thank you and sorry for opening an issues that's not an issues I guess. You can close this.

**Comment by dpgraham** [comment]
No problem! Glad it worked.
