### ISSUE TITLE
[Enhancement Request] - Copy XPATH value for an selected element.

### ISSUE THREAD

**Issue by AliakseiLogvinenko** [appium/appium-desktop#93]
In some situations there is no way of using neither of standard element attributes, so we have to use XPATH directly. It would be great to have any way of acquiring this. Here is some suggestions:

- right-click on element -> copy XPATH
- new attribute in "Selected Element" section

**Comment by dpgraham** [comment]
This is what this ticket is about: https://github.com/appium/appium-desktop/issues/56

We'll probably do something like a new attribute that displays the optimal locator + locator strategy for a given element.
