### ISSUE TITLE
Snap package support [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [appium/appium-desktop#935]
I was wondering if you might have an interest in making [snap package](https://snapcraft.io/) version. Also, your app would be promoted on the [snap store page](https://snapcraft.io/store).

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by dpgraham** [comment]
That's a good idea but I don't know that I'd be able to prioritize this any time soon. However, if someone wants to contribute, I'd be happy to help them along.

**Comment by mikeroyal** [comment]
Hi @dpgraham, I made the snap https://github.com/mikeroyal/appium-desktop-snap. All you need to do is build and register the snap in the snap store, which you can do here. https://snapcraft.io/build

**Comment by dpgraham** [comment]
Okay... @mikeroyal I made it up to `This repo needs a snapcraft.yaml file, so that Snapcraft can make it buildable, installable, and runnable.`

**Comment by mikeroyal** [comment]
Hi @dpgraham, the snapcraft.yaml here in the snap folder. https://github.com/mikeroyal/appium-desktop-snap/tree/master/snap

**Comment by dpgraham** [comment]
Can you make a PR to get that in?

**Comment by mikeroyal** [comment]
Hi @dpgraham, here you https://github.com/appium/appium-desktop/pull/948

**Comment by KazuCocoa** [comment]
The PR had been merged
