### ISSUE TITLE
Appium Inspector taking more time to load in version 1.9.1 and above

### ISSUE THREAD

**Issue by Aravindhsc** [appium/appium-desktop#936]
![Appium](https://user-images.githubusercontent.com/24908279/55881736-db251600-5bc0-11e9-8bf9-43be54c6162c.png)
## The problem
Appium inspector is taking much time to load. I have reproduced this issue in all 1.9.1 and above versions of Appium.

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by ismailyankayis** [comment]
I have same problem, but I encounter that while running a test scenario. Click and find operations take more time while a video stream, song, or radio is playing on application. 

My issue explanation is as below:

## The problem

My problem is appium runs too slow while a stream is coming. For example, when a video, song, or radio is open, find and click operations take at least 20 seconds. This problem didnot happen on version which is published 6 months ago.

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.13.0**
* Last Appium version that did not exhibit the issue (if applicable): **v1.10.0 (about these version, I'm not sure )**
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: **Android 5 - Android 10**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[LOGS](https://gist.github.com/ismailyankayis/da49cbe993bb80c6cabd66897a5aa2eb)


## Code To Reproduce Issue [ Good To Have ]
**// A Scenario Example
Scenario: 77MP VideoIzleMaxiPlayerOncekiButonu
    When I go to search page and type "Tarkan" and swipe to first video list
    And I click first video list
    Then I see video list page
    And I swipe up until I see second video name
    Then I save first video name text as the first video name
    When I click second video name
    Then I see player page
    And I click pause button
    When I click previous button
    Then I wait for 3 seconds
    When I click previous button
    Then I wait for 3 seconds
    When I click pause button
    Then I save song name text as the current video name
    And I verify the current video name equals the first video name
    Then I click minimize button
    Then I see video list page**

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by wulfihm** [comment]
Could be related to https://github.com/appium/appium/issues/14281

**Comment by KazuCocoa** [comment]
Settings/Capabilities like https://github.com/appium/appium-desktop/issues/1378#issuecomment-624649434 may help

**Comment by ymonster** [comment]
Did anyone check and enabled VT option in BIOS?
I got two PC/Windows running appium client (1.18.x, 1.17.x(
The 1.18.x : Hyper-v/VT disabled  inspector on client was super slow
The 1.17.x : SVM enabled , inspector was pretty fast.
