### ISSUE TITLE
appium desktop 1.12.1 wda error

### ISSUE THREAD

**Issue by lijinzhou2016** [appium/appium-desktop#944]
## The problem

objc[411]: Class GCDAsyncSocket is implemented in both /private/var/containers/Bundle/Application/4F9D8CC0-C93E-4EE7-858C-273DAC01CB8D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x108d286b8) and /private/var/containers/Bundle/Application/4F9D8CC0-C93E-4EE7-858C-273DAC01CB8D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x108c95470). One of the two will be used. Which one is undefined.

## Environment

Appium Desktop 1.12.1
MacOS 10.13
Xcode 10.1
iOS 12.1

**Comment by rkn411** [comment]
update mac os to 10.14
