### ISSUE TITLE
Inspector unable to attach to existing active session

### ISSUE THREAD

**Issue by MithunKudupu** [appium/appium-desktop#95]
Appium.app inspector version: Version 1.0.0-beta.4 (1.0.0-beta.4)
Appium server session running on 0.0.0.0:4723, but while providing the server session id in Custom server >> Attach to Session  with  Session id, receiving below error message:

[sessionCapabilities()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Session [5d656512-7890-4db9-829b-d546e61734f2] not available and is not among the last 1000 terminated sessions. Active sessions are[]

Please let me know if am missing any configurations. Attached appium logs.
[appiumlogs.txt](https://github.com/appium/appium-desktop/files/851128/appiumlogs.txt)

https://gist.github.com/dpgraham/0f9cb1b7a30ab1900cd4cd8dd85d1492

**Comment by dpgraham** [comment]
Are you connecting to the right server? Make sure you have it set to the 'Custom Server' tab and that you have the hostname and port set to the Appium Server that the session is running on. Also, make sure that the session you are attaching to hasn't been terminated already.

**Comment by MithunKudupu** [comment]
My mistake, i did provide the 'Remote Port' in Custom Server field. Hence the error.
Thank you @dpgraham. New Appium app is awesome.

**Comment by vikramvi** [comment]
@triager please close per last comment

**Comment by dpgraham** [comment]
@MithunKudupu Thanks!
