### ISSUE TITLE
My app is empty

### ISSUE THREAD

**Issue by allenchann** [appium/appium-desktop#953]
I am mac os 10.14.4
And the appium version is 1.12.1
When i open the app.Everything is empty.
![image](https://user-images.githubusercontent.com/16041349/56717109-8cee4600-676e-11e9-82c8-3df694373089.png)

**Comment by dpgraham** [comment]
Can you open devtools (`right click the screen > select "Inspect Element"`) and check the contents of the 'Console' tab? 

What OS are you using?
