### ISSUE TITLE
Erro in Appium v1.3.2 when Start Session 

### ISSUE THREAD

**Issue by alefecvo** [appium/appium-desktop#959]
## Appium or Appium Desktop?

Hi guys,
   I need your help to solve the problem with appium 1.3.2.
I do not get to [Start session] because the error is displayed.

Can help me?

Thanks : D

## The problem

Error

An unknown server-side error occurred while processing the command. Original error: Cannot read manifest information from 'C:\Users\Álefe\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.3.0.apk'. Does the package exist and is accessible?

## Environment
  
    - [x] Windows
    - [x] Appium 1.3.2

![image](https://user-images.githubusercontent.com/14091983/56866810-340fef00-69b4-11e9-9a75-a0890f390d83.png)

![image](https://user-images.githubusercontent.com/14091983/56866818-468a2880-69b4-11e9-9830-09d12dd9ed9c.png)

![image](https://user-images.githubusercontent.com/14091983/56866823-4c800980-69b4-11e9-8195-699ffc3b274a.png)

**Comment by KazuCocoa** [comment]
the error looks similar to https://github.com/appium/appium-desktop/issues/931

Did `C:\Users\Álefe\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.3.0.apk` exist?

**Comment by dpgraham** [comment]
You'll probably need to use a newer version of Appium Desktop....

If you need to use Appium Desktop with an older version of Appium then what it's bundled with, you can install and run it from the command line and use `Custom Server`.
