### ISSUE TITLE
Look at using bitrise for Mac builds

### ISSUE THREAD

**Issue by dpgraham** [appium/appium-desktop#96]
Mac builds for Appium Desktop are consistently failing because of this error

https://travis-ci.org/appium/appium-desktop/jobs/211469999

We're not alone

https://travis-ci.org/electron-userland/electron-builder/jobs/149860993

**Comment by dpgraham** [comment]
This seems to have magically fixed itself

https://travis-ci.org/appium/appium-desktop/jobs/233437079

**Comment by jlipps** [comment]
Favorite kind of magic!

**Comment by dpgraham** [comment]
And it's back
