### ISSUE TITLE
Appium server error

### ISSUE THREAD

**Issue by solaiyappan123mca** [appium/appium-desktop#961]
Appium Desktop

## The problem

![bug](https://user-images.githubusercontent.com/43432818/56961962-dd044880-6b72-11e9-999a-990a4816f158.JPG)

i am using noReset also but same error occur any other solutions is      @@@@@there?
## Environment

- I am running Appium Desktop version _<1.12.1>_.

   
    - [ ] Windows

**Comment by dpgraham** [comment]
Are you able to open this app using adb? `adb am start -n <appActivity>/<appActivity>`

If you can't do it through that, then it's not an Appium issue.

**Comment by KazuCocoa** [comment]
Close since this issue is not AD specific one
