### ISSUE TITLE
 iOS 12.2 failing while changing to webview context

### ISSUE THREAD

**Issue by zhubinjqjy** [appium/appium-desktop#968]
[HTTP] --> POST /wd/hub/session/d6e528f6-fb7e-4f79-9c70-4d55143bfae5/context
[HTTP] {"name":"WEBVIEW_1"}
[debug] [W3C (d6e528f6)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","d6e528f6-fb7e-4f79-9c70-4d55143bfae5"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] Using full Web Inspector protocol communication
[debug] [RemoteDebugger] Connecting to WebKit socket: 'ws://localhost:27753/devtools/page/1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-1","type":"page"}}}'
[debug] [RemoteDebugger] Found method 'Target.targetCreated' 
[debug] [RemoteDebugger] Target created: {"targetId":"page-1","type":"page"}
[debug] [RemoteDebugger] Received WebKit data: '{"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":0}'
[debug] [RemoteDebugger] Found method 'Console.enable' 
[debug] [W3C (d6e528f6)] Encountered internal error running command: 'Console' domain was not found

Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Console.enable","params":{}}}}
[RemoteDebugger] Webkit response timeout: 10000
[RemoteDebugger] Received WebKit data: '{"error":{"code":-32000,"message":"Target not found.","data":[{"code":-32000,"message":"Target not found."}]},"id":1}'
[RemoteDebugger] Received receipt for message '1'

## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by imurchie** [comment]
You need the latest Appium server to be able to automate 12.2 webviews.

**Comment by dpgraham** [comment]
The latest Appium Desktop has the most recent Appium version.
