### ISSUE TITLE
Timestamps update in the log window

### ISSUE THREAD

**Issue by Brian-Watson** [appium/appium-desktop#97]
When you enable the 'Log Timestamps' option and start the Appium Server through the UI, every timestamp in the UI seems to get updated to the latest timestamp instead of keeping the actual timestamp of when the log action happened.

**Comment by dpgraham** [comment]
Can you provide the logs that give an example of the timestamps being off?

**Comment by Brian-Watson** [comment]
I took a quick video of what I'm seeing here...

https://youtu.be/q6pHTeHPaP0

Notice that as the logging is happening, the every timestamp in the window updates.
