### ISSUE TITLE
appium_python to locate and click elements so solw?

### ISSUE THREAD

**Issue by hudaiwei** [appium/appium-desktop#971]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by hudaiwei** [comment]
appium+python to locate and click elements by ID and xpath,  so slow , why ？

**Comment by KazuCocoa** [comment]
The full logs help us assume the cause.
android/ios, how slow to get elements in your app etc.

**Comment by KazuCocoa** [comment]
if it is ios, https://github.com/facebookarchive/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance helps to understand the performance
