### ISSUE TITLE
got error "[XCUITest] Could not find any available simulators for tvOS" on Mac

### ISSUE THREAD

**Issue by simplezhang1990** [appium/appium-desktop#972]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I got below error when run the test on Mac:

[XCUITest] WDA is not listening at 'http://localhost:8100/'
[XCUITest] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1557125248687 (14:47:28 GMT+0800 (CST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/Cellar/carthage/0.31.0/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.2"
[XCUITest] *** Checking out CocoaAsyncSocket at "7.6.3"
[XCUITest] *** Checking out YYCache at "1.1.0"
[XCUITest] *** xcodebuild output can be found in /var/folders/j9/z04hg_q101d58v1k0js9x4600000gn/T/carthage-xcodebuild.1vlI8a.log
[XCUITest] *** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
[XCUITest] *** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
[XCUITest] Could not find any available simulators for tvOS

## Environment

- I am running Appium Desktop version 1.13.0.
- I am on (pick one):
    - [x] Mac

**Comment by LGFox** [comment]
Try to update carthage:
`brew update && brew upgrade carthage`

**Comment by dodosophia** [comment]
> brew update && brew upgrade carthage

I have the same problem.my carthage version is 0.31.2

**Comment by KazuCocoa** [comment]
Newer Appium has an ability to avoid building tvOS if they are not on the test environment.
But newer Carthage had an issue. Not sure recent versions, but it can fix after creating a tvOS device simulator on your environment.
