### ISSUE TITLE
Getting ENOTFOUND error when I click on start session using test object app vis Appium Desktop

### ISSUE THREAD

**Issue by DilipOptum** [appium/appium-desktop#978]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I click on "start session" button in test object using Appium desktop Getting ENOTFOUND error 
below are the desired capabilities which I have used to connect to test object in sauce lab

{
  "testobject_device": "Samsung_Galaxy_S8_optum_us3",
  "testobject_appium_version": "1.6.1",
  "testobject_cache_device": "false",
  "testobject_test_name": "Android Desktop Test",
  "platformName": "Android",
  "testobject_app_id": "37"
}

## Environment

- I am running Appium Desktop version 1.6.1
- I am on (pick one):
Windows

**Comment by pramodKarande** [comment]
@DilipOptum 
ENOTFOUND occurs when client is not able to connect to endpoint.
i think you are missing **testobject_api_key** capability.

**Comment by DilipOptum** [comment]
@pramodKarande
API_Key given in the "TestObjectAPI Key" text box which was present in the Test Object tab

**Comment by imurchie** [comment]
I think that the version you are using may point to a server that does not exist any longer. Try upgrading `appium-desktop`.

**Comment by DilipOptum** [comment]
issues resolved now, it seems the issue is local system admin access.

**Comment by coolvasanth** [comment]
How you resolved the issue ? Is it something to do with the network access of the organisation ? can you please help me with it.

**Comment by gitdegu** [comment]
This is actually happening because of the  network issue. Hope changing the network incase of multiple access point in office or home might resolve the issue I have just resolved it changing my access point.
