### ISSUE TITLE
The appium driver invocation created a problem

### ISSUE THREAD

**Issue by ParthGandhi1** [appium/appium-desktop#98]
Hi, 
I have given platform version = 6.0 however while execution value is throwing null.
Script is working properly in Appium 1.4.13 but now m using appium-desktop 1.6.4 version. And i am not able to invoke native application

Please find below logs

[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:\\Framework\\Craft(1)\\Craft\\Demo.apk","deviceName":"Nexus 5","noReset":true,"platformName":"Android","platformVersion":"6.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"D:\\Framework\\Craft(1)\\Craft\\Demo.apk","deviceName":"Nexus 5","noReset":true,"platformName":"Android","platformVersion":"6.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1490621849644 (19:07:29 GMT+0530 (India Standard Time))
[Appium] Creating new AndroidDriver (v1.15.0) session
[Appium] Capabilities:
[Appium]   app: 'D:\\Framework\\Craft(1)\\Craft\\Demo.apk'
[Appium]   deviceName: 'Nexus 5'
[Appium]   noReset: true
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '6.0'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[AndroidDriver] AndroidDriver version: 1.15.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 590237b8-2c88-42e1-ad7d-11e01d0741a7
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_102
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Demo.com\Appium\adt-bundle-windows-x86-20131030\adt-bundle-windows-x86-20131030\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '6.0'
[ADB] Setting device id to 0775048a0221fdd6
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Demo.com\Appium\adt-bundle-windows-x86-20131030\adt-bundle-windows-x86-20131030\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0775048a0221fdd6","shell","getprop","ro.build.version.release"]
[AndroidDriver] Using device: 0775048a0221fdd6
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Demo.com\Appium\adt-bundle-windows-x86-20131030\adt-bundle-windows-x86-20131030\sdk\platform-tools\adb.exe
[ADB] Setting device id to 0775048a0221fdd6
[BaseDriver] Using local app 'D:\Framework\Craft(1)\Craft\Demo.apk'
[AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[ADB] Running 'D:\Demo.com\Appium\adt-bundle-windows-x86-20131030\adt-bundle-windows-x86-20131030\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","0775048a0221fdd6","wait-for-device"]
[ADB] Getting connected devices...
[ADB] 1 device(s) connected

[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[UiAutomator] Moving to state 'stopped'
[AndroidDriver] Shutting down Android driver
[ADB] Getting connected devices...
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'

**Comment by ParthGandhi1** [comment]
Capabilities Snapshot
![image](https://cloud.githubusercontent.com/assets/26715206/24359477/1affcf8e-1322-11e7-920f-c23cbe2344ca.png)

Appium Log Snapshot
![image](https://cloud.githubusercontent.com/assets/26715206/24359531/46798ae2-1322-11e7-85d6-8db71807838c.png)

**Comment by dpgraham** [comment]
This looks like an Appium issue and not an Appium Desktop issue.

Can you open this in https://github.com/appium/appium/issues

**Comment by BBQLTFF** [comment]
请问您最后怎么解决的这个问题，我遇见了相同情况
