### ISSUE TITLE
Capture Page Screenshot will get stuck

### ISSUE THREAD

**Issue by panda62** [appium/appium-desktop#987]
Win10 
appium-desktop 1.13.0
appium 1.12.0-1.13.0

The above versions have all tried. Appium will get stuck when I use the screenshot, and it will time out.
![图片](https://user-images.githubusercontent.com/40233059/57745703-c4626980-7700-11e9-800a-9f828e90d7ee.png)

appium1.11.0,This version will not get stuck.

**Comment by KazuCocoa** [comment]
Could you attach the logcat and the full log for Appium 1.13.0 bases to understand your situation?

**Comment by panda62** [comment]
@KazuCocoa 
I'm sorry. I tried to reproduce the problem but could not reproduce it. When I uninstalled 1.11.1 and reinstalled 1.13.0, the screenshot function is now working properly.

**Comment by KazuCocoa** [comment]
Okay, no problem. Glad to hear it.
If you get the error again, feel free to create a new issue with logcat :)
