### ISSUE TITLE
Cannot start the application

### ISSUE THREAD

**Issue by coharmon** [appium/appium-desktop#988]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Here is my code:

            AndroidDriver<AndroidElement> driver;
            // Set the capabilities instance
            DesiredCapabilities capabilities = new DesiredCapabilities();

            // Set device capabilities
            capabilities.SetCapability("deviceName", "Android Emulator");
            capabilities.SetCapability("appPackage", "com.aveanna.caregiver.scheduling");
            capabilities.SetCapability("appActivity", "host.exp.exponent.MainActivity");
            capabilities.SetCapability("deviceReadyTimeout", 20);

            // Create new Appium driver pointing to the MC server and based on the capabilities set above.
            driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities, TimeSpan.FromMinutes(50));

I get this error even my app launches for about 10 seconds and then shuts down.:
An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.aveanna.caregiver.scheduling' application. 

## Environment

- I am running Appium Desktop version _1.13_.
- I am on (pick one):
    - [ ] Mac
    - [x ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Could you attach the full log?
