### ISSUE TITLE
Add error message in case of missing adb shell command

### ISSUE THREAD

**Issue by hornyja4** [appium/appium-desktop#992]
Appium Desktop

## The problem

Hi, I tried to record a screen on Huawei mobile phones. Problem is, Huawei removed command _screenrecord <filename>_ from the adb shell commands long time ago. In this case, Appium didn't provide any information about missing shell command you are trying to use... Function _startRecordingScreen()_ failed because of missing video file which could be created by _screenrecord_ shell command at _/sdcard/filename.mp4_. Is Appium ignoring the results of adb commands? It would help if there will be some appropriate message related to real problem...

## Environment
- I am running Appium Desktop version 1.13.0
- I am on Windows

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/pull/544 might help this (message improvement)
