### ISSUE TITLE
I am trying to launch chrome browser. Since chrome has updated its latest version, appium is not launching the chrome browser. 

### ISSUE THREAD

**Issue by appiumusermohana** [appium/appium-desktop#993]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by appiumusermohana** [comment]
package test;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

@SuppressWarnings("unused")

public class LaunchChrome {
	
	
	static DesiredCapabilities caps = DesiredCapabilities.android();
	
	public static void main(String[] args) throws MalformedURLException {
		
						
				caps.setCapability("deviceName", "Samsung");
				caps.setCapability("udid", "5203098ab278b435"); //Give Device ID of your mobile phone
				caps.setCapability("platformName", "Android");
				caps.setCapability("platformVersion", "8.1.0");
				caps.setCapability("browserName", "Chrome");
				caps.setCapability("noReset", true);			
				//Set ChromeDriver location
				System.setProperty("webdriver.chrome.driver","D:\\EXE files\\ChromeDriver\\chromedriver.exe");				
				//Instantiate Appium Driver
				AppiumDriver<MobileElement> driver = null;
				try {
					driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), caps);
				} catch (MalformedURLException e) {
					System.out.println(e.getMessage());
				}
						
				//Open URL in Chrome Browser
				driver.get("http://www.google.com");	
			}
}	



This is the code i wrote and trying to launch the chrome browser, but is not launching because in android the chrome version is 74. Can you please help me to resolve the problem

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/writing-running-appium/web/chromedriver/ will help to resolve newer versions.
Around `chromedriverExecutableDir`, `chromedriverChromeMappingFile` or `chromedriver_autodownload`
