### ISSUE TITLE
Next release of the appium-desktop

### ISSUE THREAD

**Issue by ArtemVarnavskiy** [appium/appium-desktop#997]
Appium Desktop

**The problem (question)**

When will the next release of the appium-desktop?
I have installed version Xcode 9.2 and I'm reproducing a bug:
https://github.com/appium/appium/issues/12586
I installed appium@beta, but I need appium-inspector...

Thank you!

**Environment**

- I am running Appium Desktop version 1.13.0
- I am on Mac

**Comment by KazuCocoa** [comment]
You can connect to local another appium server via the inspector:
https://github.com/appium/appium/issues/12391#issuecomment-477057988

This should help with your situation. @ArtemVarnavskiy

**Comment by KazuCocoa** [comment]
try with `appium@beta` ^

**Comment by ArtemVarnavskiy** [comment]
@KazuCocoa 
It helps me. Thank!
