### ISSUE TITLE
Windows CalculatorTest example does not seem to work

### ISSUE THREAD

**Issue by Splinkle** [appium/appium-desktop#998]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue
No, I have not, because I don't know what that means!

## The problem

I am totally new to Appium, have followed the Windows driver setup documentation, and have reached to where it says to get CalculatorTest from github and fire up the tests.
I have Appium running on my windows machine (as administrator), the desktop client starts, and I can create a simple server with address 127.0.0.1:4723.
When I try to run the tests in CalculatorTest I get an error creating the session.    Visual Studio say "Unexpected error. The URL '/session' did not map to a valid resource
Appium desktop says "No route found"  "POST /session"
(Please see pictures for more info)

I assume I'm doing something wrong, but can't see what it is

## Environment

- I am running Appium Desktop version 1.13.0.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

![image](https://user-images.githubusercontent.com/24405784/58538950-8f710f00-81f6-11e9-9288-d4c34f70a6c6.png)
![image](https://user-images.githubusercontent.com/24405784/58539045-c810e880-81f6-11e9-968c-55ed30be0acb.png)

**Comment by KazuCocoa** [comment]
@Splinkle It looks an example in WinAppDriver.
Please ask their repo rather than here. I think you can get a proper reply there.
